### ISSUE TITLE
Segmentation fault with PHP 7.1 on trusty

### ISSUE THREAD

**Issue by nijel** [travis-ci/travis-ci#7504] opened 2017-03-22 09:10 UTC
Since recently we're getting segentation faults in PHP 7.1 builds on trusty.

For example see here:

https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/213741552#L479

It doesn't seem to be deterministic, sometimes it crashes during the testsuite, sometimes during collecting coverage.

**Comment by BanzaiMan** [comment] 2017-03-22 12:55
What's the nature of the segmentation faults? We provide xdebug, which could help you track it down. Also, you may want to see if the problem persists without the cache (if any of them has binary files that are linked to a different version of PHP runtime, for example, it could be more susceptible to bad memory access).

**Comment by nijel** [comment] 2017-03-22 15:21
Do you have some suggestions how to debug this? It doesn't fail regularly, I'd say that that 20% were failing (I can't get exact stats, because I've restarted many of the failed jobs). It started to happen about week ago.

**Comment by BanzaiMan** [comment] 2017-03-22 16:17
I'm sorry to say that I don't know enough about PHP or your application to suggest much beyond what I said above.

"A week ago" corresponds to our release of 7.1.3 (https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/213741552#L330 shows it was compiled on Mar 17), so it might be the cause. If your application relies on binary extension(s), it might be compiled agains the older binary, and causing the segmentation fault. I suggest disabling the cache to test this hypothesis first.

**Comment by nijel** [comment] 2017-03-22 17:24
We don't install any extensions, so that should not be problem. Anyway I've tried to delete the caches to see if that helps...

**Comment by BanzaiMan** [comment] 2017-03-24 00:50
Looks like the 7.1 job started passing. https://travis-ci.org/phpmyadmin/phpmyadmin/builds

**Comment by nijel** [comment] 2017-03-26 08:22
Indeed I haven't seen such failure since then (but it was happening on PRs, which start with no cache if I'm not mistaken).

**Comment by BanzaiMan** [comment] 2017-03-26 13:39
Can we close this, then?

**Comment by nijel** [comment] 2017-03-26 14:20
Probably, maybe it was just some temporary problem on the infrastructure...

**Comment by nijel** [comment] 2017-03-28 13:05
Obviously request to close this was good to trigger the segfault again:

https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/215920504#L604

**Comment by BanzaiMan** [comment] 2017-03-28 13:17
Does the segmentation fault ever happen if you don't use the cache? Also, please try xdebug.

**Comment by nijel** [comment] 2017-03-28 13:28
As mentioned before, it happens more or less randomly, so it's hard to say if removed caching will help.

I have no clue how to use xdebug to analyze PHP segfault, do you have some hints how to do that?

**Comment by BanzaiMan** [comment] 2017-03-28 13:35
Sorry, but I know much less about the PHP tooling than you do. https://xdebug.org/ would be a start.

**Comment by nijel** [comment] 2017-03-30 09:33
XDebug is for debugging PHP code, not about crashing interpreter...

But while looking at that, it might be actually cause of the crashes as 2.5.1 has fixed quite a lot of issues which might be causing this (eg. https://bugs.xdebug.org/view.php?id=1360) is there chance to get it updated?

**Comment by c9s** [comment] 2017-04-04 11:27
Same here https://travis-ci.org/maghead/maghead/jobs/218418873

Although I remove xdebug extension, it still crashes

**Comment by alcaeus** [comment] 2017-04-20 08:45
Segmentation faults are still happening on 7.1.3 with xdebug 2.5.0: https://travis-ci.org/doctrine/DoctrineMongoDBBundle/jobs/220984887

xdebug 2.5.3 was released a few days ago, any change to get an update?

**Comment by tristanbes** [comment] 2017-04-24 10:29
Same, a lot of random segfault, wih xdebug off. 

PHP 7.1.4 has been released on 13th April, any chance it gets updated on travis ?

**Comment by BanzaiMan** [comment] 2017-04-24 12:00
https://github.com/php-build/php-build/tree/master/share/php-build/definitions indicates that the runtimes would include xdebug 2.5.2 if we rebuild them.

I will build PHP 7.1.4 shortly.

**Comment by BanzaiMan** [comment] 2017-04-24 12:01
https://travis-ci.org/travis-ci/php-src-builder/builds/225180055

**Comment by theofidry** [comment] 2017-04-24 23:26
@BanzaiMan 👌 . I can't find the link anymore but there's an issue with datetimes in 7.1.3 causing a lot of segmentation faults. Updating to 7.1.4 will solve it.

**Comment by BanzaiMan** [comment] 2017-05-10 00:53
Is this still an issue?

**Closed** 2017-05-17 11:46 UTC
Labels: php
