### ISSUE TITLE
Travis is not building the merge commit of a PR

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#7418] opened 2017-03-03 11:18 UTC
When a PR is merged using the github UI, a merge commit is created, but travis is not building the merge commit, but the last commit of the PR. This is a new bug within the last couple of days.

See https://travis-ci.org/conda-forge/awesome-slugify-feedstock/builds/206867462

which tests conda-forge/awesome-slugify-feedstock@afa2ea4 instead of conda-forge/awesome-slugify-feedstock@057c9c3, but in the travis-ci UI, this commit is only there in the compare field.

```
 Commit afa2ea4
 Compare 2092367..057c9c3
```

Normally the last commit of `Compare` should be in the `Commit` field

**Comment by BanzaiMan** [comment] 2017-03-03 13:32
How was this build triggered? Was it "Create a merge commit", "Squash and merge", or "Rebase and merge"?

**Comment by isuruf** [comment] 2017-03-03 13:35
Create a merge commit from what I can tell. cc @jakirkham

**Comment by isuruf** [comment] 2017-03-04 10:53
I'm seeing more of these, https://travis-ci.org/conda-forge/pybinding-feedstock/builds/207320101

**Comment by jakirkham** [comment] 2017-03-08 17:21
I think this is a duplicate of issue ( https://github.com/travis-ci/travis-ci/issues/6669 ). Please let me know whether or not that is true, @isuruf.

**Closed** 2017-03-08 17:26 UTC
