### ISSUE TITLE
gfortran is no longer available for builds

### ISSUE THREAD

**Issue by fonnesbeck** [travis-ci/travis-ci#5231] opened 2015-12-06 14:49 UTC
Sometime during the past week, testing [PyMC](https://github.com/pymc-devs/pymc) with TravisCI fails because the gfortran dependency appears no longer to be available:

    Package gfortran is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source

    E: Unable to locate package liblapack-dev
    E: Package 'gfortran' has no installation candidate
    E: Unable to locate package libblas-dev
    travis_time:end:07d653bc:start=1449412593241414318,finish=1449412593357731962,duration=116317644
    [0K
    [31;1mThe command "sudo apt-get install liblapack-dev gfortran libblas-dev" failed and exited with 100 during .[0m

    Your build has been stopped.

[Here is an example build log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/95169691/log.txt)

**Comment by fniephaus** [comment] 2015-12-09 23:58
This looks like a duplicate of #5221

**Comment by BanzaiMan** [comment] 2015-12-10 00:37
Indeed, it does.

**Closed by BanzaiMan** 2015-12-10 00:37 UTC
