### ISSUE TITLE
Mac OS X failing perlbrew, using system perl version (wrong version)

### ISSUE THREAD

**Issue by harisekhon** [travis-ci/travis-ci#5324] opened 2015-12-17 22:26 UTC
https://travis-ci.org/harisekhon/lib/jobs/97557065

**Comment by BanzaiMan** [comment] 2015-12-17 22:32
Sorry, but Perl is not currently supported on OS X. I'm closing this as a duplicate of #2314.

**Closed by BanzaiMan** 2015-12-17 22:32 UTC
