### ISSUE TITLE
Strange build running time displayed

### ISSUE THREAD

**Issue by slodki** [travis-ci/travis-ci#7759] opened 2017-05-14 13:13 UTC
- Build was started with multiple jobs queued.
- 5th job failed and was restarted while other jobs were still building.

Running timer for the build was reseted to the restarted job, ignoring previously started (from queue) jobs running longer:
![travis build time](https://cloud.githubusercontent.com/assets/3155552/26034065/ed1ef512-38b6-11e7-97a7-6517ddf6d469.png)

Currently displayed time is simply wrong, inconsistent with timers displayed below.

What should be displayed when some jobs are restarted:
- during initial build?
- days after initial build completed?

**Comment by BanzaiMan** [comment] 2017-05-14 20:21
We currently reset the start time when a proper subset of the jobs comprising a build is restarted. I am afraid we will not reach consensus on "what kind of elapsed time should be displayed" in this case.

**Comment by slodki** [comment] 2017-05-15 07:15
So this information is wrong and useless in that case. Should be hidden maybe?

**Comment by BanzaiMan** [comment] 2017-05-15 13:22
Not displaying anything is also confusing, because the running time is shown everywhere else.

**Comment by slodki** [comment] 2017-05-15 13:48
A random number displayed there will have similar value for the user and will not be confusing, visual layout will be same for all builds.
;-)
It's easy to check timer for a specific job if user is interested in it. Displaying job time as build time when they are not the same is an error, should be replaced by "N/A" with tooltip "user manually changed restarted a job in this build".

**Comment by slodki** [comment] 2017-05-15 14:13
Test scenario:

1. Created new build 99 with 2 jobs
2. Both jobs failed: 99.1 after 10 min and 99.2 after 15 min
3. Running time is displayed as 15 min and accumulated time as 25 min
-> this is true
4. User restarts job 99.2 and cancels this job while waiting for job 99.2 start (at created status)
5. Running time is displayed as "-" and accumulated time as 10 min
-> running time is lost, accumulated time is wrong
-> "Not displaying anything is also confusing, because the running time is shown everywhere else."
6. User restarts job 99.1 and cancels this job after 16 sec
7. Running time is displayed as 16 sec and accumulated time as 16 sec
-> running and accumulated time are not build attributes, but one (unknown to the user) job's values, without any relation to build or other jobs values!
8. User restarts job 99.1 and cancels this job while waiting for job 99.1 start
9. All timers are reset to 0, both displayed as "-"
-> "Not displaying anything is also confusing..."

**Comment by BanzaiMan** [comment] 2017-05-17 11:55
I'm closing this as a duplicate of #7347.

**Closed by BanzaiMan** 2017-05-17 11:55 UTC
Labels: travis-web
