### ISSUE TITLE
Linux Python 3.0 tar.bz2 missing

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [travis-ci/travis-ci#7839] opened 2017-06-01 23:50 UTC
I'm running into an issue where Travis fails to install Python 3.0, giving an error:
`The command "sudo tar xjf python-3.0.tar.bz2 --directory /" failed and exited with 2 during .`

The link it uses to download the archive is: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.0.tar.bz2
If you try to navigate to this link, you'll get an XML AccessDenied page. However, if one visits:
https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.6.tar.bz2
It works fine. Any ideas?

**Comment by MicroTransactionsMatterToo** [comment] 2017-06-01 23:52
Pretty sure the primary error is cause by it downloading the XML page, then trying to unzip it

**Comment by BanzaiMan** [comment] 2017-06-02 00:57
This is a duplicate of #7310. In short, we can't compile it.

**Closed by BanzaiMan** 2017-06-02 00:57 UTC
