### ISSUE TITLE
Include / exclude files from triggering a build

### ISSUE THREAD

**Issue by henrik242** [travis-ci/travis-ci#6745] opened 2016-10-17 15:46 UTC
It would be great if I could configure paths in the Git repo that would not trigger a build, i.e. with something like this in `.travis.yml`:

```
exclude:
  - docs/
  - todo.txt
```

(And as a bonus: make it work with individual excludes for each matrix build also.)

**Comment by BanzaiMan** [comment] 2016-10-18 13:56
I'm closing this as a duplicate of #6301.

**Closed by BanzaiMan** 2016-10-18 13:56 UTC
