### ISSUE TITLE
python3-config yields incorrect output

### ISSUE THREAD

**Issue by dagheyman** [travis-ci/travis-ci#7138] opened 2017-01-11 15:44 UTC
[This build](https://travis-ci.org/Yubico/yubikey-manager-qt/jobs/179759983) succeeded before, now fails with
`(libpython3.5m.so.1.0: cannot open shared object file: No such file or directory).`

A [green build](https://travis-ci.org/Yubico/yubikey-manager-qt/jobs/179734282) the commit before.

@BanzaiMan in #5268:
> I am guessing that somehow python3-config is not valid, and giving configure (and make) bad configuration flags somehow.

Any ideas ?

**Comment by BanzaiMan** [comment] 2017-01-13 13:17
There appear to be a couple of issues at play.

1. `virtualenv` appears to set up only a handful of scripts and symlinks in the designated directory (e.g., `~/virtualenv/python3.5/bin/`). This is not entirely relevant to the indicated build, however, since it is a `cpp` build, not `python`.
1. We set up `$PATH` in `/etc/profile.d/pyenv.sh`, but the order in which the components appear is (presumably) dependent on the order in which the runtimes were installed on the build image. This is how `python3-config` is found at all on the `cpp` job such as this one. `python3-config` is found in one of the directories added by `/etc/profile/pyenv.sh`, but the first one (which I think is the last one installed during the build image provisioning process).

It is not clear how to *cleanly* fix this in all images without a fix from `virtualenv`, but in your case, tweaking `$PATH` to match the files that are present on the image might fix it.

**Comment by BanzaiMan** [comment] 2017-01-16 01:36
Actually this is a duplicate of #3107.

**Closed by BanzaiMan** 2017-01-16 01:36 UTC
Labels: python

**Comment by dagheyman** [comment] 2017-01-16 10:02
Solved the build by tweaking the `$PATH` as you suggested.
`export PATH="/opt/python/3.5.2/bin:$PATH"` is what was needed in my case.
Thanks!
