### ISSUE TITLE
"shell_session_update: command not found" with new XCode 7.3 image

### ISSUE THREAD

**Issue by matthew-brett** [travis-ci/travis-ci#6677] opened 2016-10-05 07:55 UTC
We've just run into a puzzling new bash / OSX failure that appears
unrelated to our own code, here:

https://travis-ci.org/python-pillow/pillow-wheels/jobs/164959058#L98

and here:

https://github.com/MacPython/terryfy/issues/7

The error is : 

```
multibuild/common_utils.sh: line 106: shell_session_update: command not found
```

That code does not itself call `shell_session_update`.

We believe this is due to your switch to the 7.3 XCode image default from 6.4, because:

* The same code ran correctly earlier on 4 October: instance: 16782137-e409-42c8-b363-fffe4051ae83:travis-ci-osx10.9-xcode6.1-1472151920 from https://travis-ci.org/python-pillow/pillow-wheels/jobs/164947028
* The code failed later on 4 October: instance: d9728977-df2b-4bc4-b664-ece05a87df47:travis-ci-osx10.11-xcode7.3-1475505633 from https://travis-ci.org/python-pillow/pillow-wheels/jobs/164959058
* The problem went away when we added `osx_image: xcode6.4` in the global envs of the `.travis.yml` file :  https://travis-ci.org/python-pillow/pillow-wheels/builds/165025244
* This same bash code continues to works correctly on Linux (earlier green entries on grid at
https://travis-ci.org/python-pillow/pillow-wheels/builds/164959049).

I see that this error can occur from problems with the ruby runtime :

https://github.com/direnv/direnv/issues/210

Is it possible something like that has happened here?

**Comment by BanzaiMan** [comment] 2016-10-05 12:35
Duplicate of #6522.

**Closed by BanzaiMan** 2016-10-05 12:35 UTC

**Comment by jakirkham** [comment] 2016-10-05 17:09
Thanks for the detailed info, @matthew-brett. 👍
