### ISSUE TITLE
Build on OS X errors with `/Users/travis/build.sh: line 109: shell_session_update: command not found`, apparently due to bad PATH definition

### ISSUE THREAD

**Issue by sjakobi** [travis-ci/travis-ci#6680] opened 2016-10-05 15:44 UTC
See e.g. https://travis-ci.org/commercialhaskell/stack/jobs/165228916#L4074:

```
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

Note the warning at the top:

```
$ rvm use
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.
```

**Comment by BanzaiMan** [comment] 2016-10-05 16:45
Duplicate of #6522.

**Comment by BanzaiMan** [comment] 2016-10-05 16:46
The warning is not related.

**Closed by BanzaiMan** 2016-10-05 16:45 UTC
