### ISSUE TITLE
Crystal installation fails

### ISSUE THREAD

**Issue by TPei** [travis-ci/travis-ci#8013] opened 2017-07-01 23:30 UTC
The crystal installation shows this error:
`W: GPG error: https://dist.crystal-lang.org crystal Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4EBAC6667697DD2`

A bit farther down it says:
```
The following NEW packages will be installed:
  crystal libgmp-dev libgmpxx4ldbl
0 upgraded, 3 newly installed, 0 to remove and 275 not upgraded.
```

and then:
`WARNING: The following packages cannot be authenticated! crystal`

Didn't have this on my last build, could this be `0.23.0` related?

Build System Information:
```
Build language: crystal
Build group: stable
Build dist: precise
Build id: 249213767
Job id: 249213768
travis-build version: 75a27e5e4
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
```

@asterite @jhass @waj @will

**Comment by BanzaiMan** [comment] 2017-07-02 02:26
Duplicate of #8005.

**Closed by BanzaiMan** 2017-07-02 02:26 UTC
