### ISSUE TITLE
Host shut down during build

### ISSUE THREAD

**Issue by abesto** [travis-ci/travis-ci#4924] opened 2015-10-12 17:54 UTC
We've seen this a couple of times, for example in https://travis-ci.org/openzipkin/docker-zipkin/builds/84941149.

```
Broadcast message from root@testing-gce-03e2cd86-76ae-4bc4-abbd-20ea07b052e7
	(unknown) at 15:45 ...
The system is going down for power off NOW!
```

And then of course things get confused, and the build fails a second or so later.

**Comment by BanzaiMan** [comment] 2015-10-19 13:40
Sounds like the GCE instance had to be shut down for one reason or another. Have you seen this recently?

**Comment by abesto** [comment] 2015-10-19 13:48
I haven't seen it since that build, but I'll ask around.

**Comment by solarce** [comment] 2015-10-21 17:57
I am on the infrastructure team at Travis and wanted to give you an explanation as to why you were seeing this.

For our Trusty beta, http://docs.travis-ci.com/user/trusty-ci-environment/, we're using Google Compute Engine to run the build VMs. The VMs we're using right now are provisioned as pre-emptible VMs, https://cloud.google.com/compute/docs/instances/preemptible, which means Google can shut them down at will.

We normally handle this case like any number of other failure scenarios that might require us to restart a build but we found that this particular scenario wasn't being handled properly in all cases, so builds were being marked as failed when they should have been restarted.

You should no longer see this happening and we should automatically restart a build when this scenario occurs. We're also looking into how we can better track this particular scenario in our metrics, as right now it's just counted as a single "requeued job" metric that covers a range of possible sources for requeue.

**Comment by abesto** [comment] 2015-10-21 18:26
Thanks a lot for the in-depth explanation, appreciate it :)

Love the work you're all doing on Travis :sparkling_heart:

**Comment by edmorley** [comment] 2015-10-23 00:13
Hi Brandon, small world :-)

> You should no longer see this happening and we should automatically restart a build when this scenario occurs.

I've just seen this on a run that started 20 minutes ago; is this expected?
https://travis-ci.org/mozilla/treeherder/builds/86937208#L712

**Comment by solarce** [comment] 2015-10-23 00:22
Hello @edmorley, good to *see* you :)

Thanks for the link, we'll dig into why we didn't restart that build properly

**Comment by buskamuza** [comment] 2015-12-21 21:08
Hi,

is it the same issue https://travis-ci.org/mazhalai/magento2/jobs/98193334 ?
Looks like the build is not automatically restarted.

**Comment by cesy** [comment] 2016-01-27 22:15
I'm still seeing this frequently on our repo - is there anything else going on? Will wrapping the commands in travis_retry help?

**Comment by dmitriivoitovich** [comment] 2016-03-17 12:25
It looks like the problem is still with us. We run about 100 builds per day and I see this "The system is going down for power off NOW!" quite often unfortunately.

**Comment by iangcarroll** [comment] 2016-03-24 00:46
Yes, this also just happened for us, and it isn't restarted:

```
Broadcast message from root@testing-gce-74fdc79e-f255-41ce-8c77-513b8f9077b6
	(unknown) at 0:44 ...
The system is going down for power off NOW!
```

**Comment by ecnalyr** [comment] 2016-04-08 17:34
Happened for me too, did not restart.

**Comment by nsuke** [comment] 2016-04-17 08:39
I'm affected by this regularly.
4 jobs just failed approximately at the same time because of this.
All of them were in the middle of travis_retry and/or travis_wait but I'm not sure if it's anything to do with your shutdown detection.

Here's full log after shutdown message for a `travis_retry travis_wait ...` command.
```
Broadcast message from root@testing-gce-af053011-bd8b-4715-a3ab-4957fcf9c2f4
	(unknown) at 6:20 ...
The system is going down for power off NOW!
The command docker build -q -t thrift-build build/docker/ubuntu exited with 1.

Log:
An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.23/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&q=1&rm=1&shmsize=0&t=thrift-build&ulimits=null: EOF
/home/travis/build.sh: line 112:  3545 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait docker build -q -t thrift-build build/docker/ubuntu" failed. Retrying, 2 of 3.


Still running (1 of 20): docker build -q -t thrift-build build/docker/ubuntu
The command docker build -q -t thrift-build build/docker/ubuntu exited with 1.

Log:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
/home/travis/build.sh: line 112: 30866 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait docker build -q -t thrift-build build/docker/ubuntu" failed. Retrying, 3 of 3.


Still running (1 of 20): docker build -q -t thrift-build build/docker/ubuntu
The command docker build -q -t thrift-build build/docker/ubuntu exited with 1.

Log:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
/home/travis/build.sh: line 112: 30886 Terminated              travis_jigger $! $timeout $cmd
The command "travis_wait docker build -q -t thrift-build build/docker/ubuntu" failed 3 times.

The command "travis_retry travis_wait docker build -q -t thrift-build build/docker/$DISTRO" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by rpaterson** [comment] 2016-04-18 23:37
Just had this problem on one of our travis.com builds: https://travis-ci.com/signpost/core/jobs/37876888

**Comment by rpaterson** [comment] 2016-04-18 23:44
@solarce can you reopen this issue?

**Comment by solarce** [comment] 2016-04-19 01:22
Sorry for the ongoing issue. We believe we've identified a fix and are looking to deploy it to production tomorrow.

**Comment by ogrisel** [comment] 2016-04-21 07:19
One more data point: it happened to us too, it wasn't restarted either and the build ended in "green" state:

https://travis-ci.org/pypa/manylinux/builds/124631630

**Comment by ppalaga** [comment] 2016-04-21 08:20
Same as @ogrisel here: the job got interrupted with "The system is going down for power off NOW!" but the job result was reported as success. It happened twice in a row after I restarted the job manually https://travis-ci.org/hawkular/hawkular-inventory/builds/124672840

**Comment by ogrisel** [comment] 2016-04-21 08:44
I also happened to me twice in row when restarted the job manually from the web UI.

**Comment by LuxoftAKutsan** [comment] 2016-04-21 15:20
Hello, during last 2 days I had the same issue. And terminated(via shutdown) build marked as succeed. It is quite confusing. 
https://travis-ci.org/smartdevicelink/sdl_core/builds/124763617

**Comment by ribasushi** [comment] 2016-04-21 18:34
@BanzaiMan This is not `mac`-specific. I see this on linux GCE all over.

**Comment by solarce** [comment] 2016-04-21 20:16
We've deployed an additional change that should hopefully fix this issue. Please report if you see any builds that enter this state that start after **2016-04-21 20:15 UTC**

**Comment by theuni** [comment] 2016-05-26 20:23
Hi @solarce 
We just saw this here: https://travis-ci.org/bitcoin/bitcoin/jobs/129694378

The test passed despite the shutdown. Even worse, a legitimate bug slipped in as a result :(

Mind having a look?

**Comment by solarce** [comment] 2016-05-26 21:00
@theuni my apologies for the issue. We found a couple of servers who'd been rebooted and came back up with an incorrect config, which was resulting in the issue you saw yesterday. The one that ran the build you linked to was one of them. They were fixed as of 09:00 PST this morning.

**Closed by solarce** 2016-05-26 21:00 UTC

**Comment by zachyee** [comment] 2016-07-06 22:12
Hey @solarce 
We just had a build that had this problem: https://travis-ci.org/prestodb/presto-admin/jobs/142881991
Line 414.

Would you mind looking into this?

**Comment by solarce** [comment] 2016-07-06 23:52
@zachyee thanks for the error report. I looked and did find that a server was missing the appropriate config after a host failover.

We've fixed the glitch and things should be good now.

![fixed_the_glitch](https://cdn.meme.am/instances/500x/64639708.jpg)

**Comment by kennytm** [comment] 2018-07-27 06:46
Hi. Recently we've got two jobs affected by this issue.

1. (2018-07-25T07:58:07Z) https://travis-ci.org/rust-lang/rust/jobs/407943808
2. (2018-07-27T02:32:08Z) https://travis-ci.org/rust-lang/rust/jobs/408754986

**Comment by phansch** [comment] 2018-08-02 07:47
This seems to happen frequently again, so I think it makes sense to ping maybe @BanzaiMan here?
Although, this only seems to have been noticed in the rust-lang/rust repo so far.
The logs don't contain any hint why the machines would be shutting down it's always just:

```
[... random part of the build]

Broadcast message from root@travis-job-bfe1c554-21f1-4290-ae40-a3e7db5a44cc
	(unknown) at 7:57 ...
The system is going down for power off NOW!
[00:21:54] 
[00:21:54] Session terminated, terminating shell... ...terminated.
```

**Comment by soulshake** [comment] 2018-08-07 15:38
Thanks for the reports. I believe we've found the cause, which was that VMs were set to `TERMINATE` on host maintenance instead of `MIGRATE`, due to recent changes.

We're looking into a workaround.

**Comment by RalfJung** [comment] 2018-08-13 20:41
Shouldn't this be reopened then until https://github.com/travis-ci/worker/pull/481 actually lands?
