### ISSUE TITLE
Build failing on Julia nightly on Mac only

### ISSUE THREAD

**Issue by juliohm** [travis-ci/travis-ci#7748] opened 2017-05-11 19:08 UTC
Could you please help me debug this issue? It looks like some dependencies are not being pulled on Mac.

https://travis-ci.org/juliohm/GeoStats.jl

@tkelman, @ninjin, @staticfloat, @simonbyrne

**Comment by BanzaiMan** [comment] 2017-05-11 19:17
Is this not a duplicate of #7514?

**Comment by staticfloat** [comment] 2017-05-11 19:18
It's the SONAME change of libgfortran due to the GCC 6 -> GCC 7 upgrade that we inherited from Homebrew.  I've fixed the issue on the buildbots, we just need to wait for a new nightly to come out

**Comment by BanzaiMan** [comment] 2017-05-22 12:58
@staticfloat Has this been fixed?

**Comment by tkelman** [comment] 2017-05-22 12:59
This should be working fine now.

**Comment by BanzaiMan** [comment] 2017-05-22 12:59
Thanks for the update.

**Closed by BanzaiMan** 2017-05-22 12:59 UTC
Labels: community:julia
