### ISSUE TITLE
LXD support: job stalling, error exit code with no output, blank page, ...

### ISSUE THREAD

**Issue by juju4** [travis-ci/travis-ci#6479] opened 2016-08-14 19:45 UTC
Hello,

I'm experimenting and switching more of my ansible role testing to lxd inside travis but I encounter multiple anomalies which I haven't with my local test either kitchen/lxd, either kitchen/virtualbox.

I'm looking for comments as local testing is mostly working and clearly not with same results that travis.

example of travis file
https://github.com/juju4/ansible-adduser/blob/master/.travis.yml

* job stalling after 10min without output
"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."
https://travis-ci.org/juju4/ansible-jenkins/jobs/152142084
https://travis-ci.org/juju4/ansible-bro-ids/jobs/152207301
https://travis-ci.org/juju4/ansible-mhn/jobs/152221219
https://travis-ci.org/juju4/ansible-redhat-epel/jobs/152229170
https://travis-ci.org/juju4/ansible-redhat-epel/jobs/152229169
https://travis-ci.org/juju4/ansible-mhn/jobs/152229319
https://travis-ci.org/juju4/ansible-icinga2/jobs/152226524
https://travis-ci.org/juju4/ansible-bro-ids/jobs/152207301
https://travis-ci.org/juju4/ansible-icinga2/jobs/152243716

* command bash script returns exit code 127 or 255 without any details
https://travis-ci.org/juju4/ansible-jenkins/jobs/152142083
https://travis-ci.org/juju4/ansible-jenkins/jobs/152142082
https://travis-ci.org/juju4/ansible-adduser/jobs/150469634
https://travis-ci.org/juju4/ansible-adduser/jobs/150469633

* blank page
https://travis-ci.org/juju4/ansible-mhn/jobs/152120865 (build 20.1)
https://travis-ci.org/juju4/ansible-bro-ids/jobs/152145868

* lost distribution informations: environment vars are not displayed.
https://travis-ci.org/juju4/ansible-bro-ids
https://travis-ci.org/juju4/ansible-lxd

code is inside github and freely accessible if you want to re-run it.
If you want a simple role, adduser is the one.

Thanks

Note: interface was feeling slower those days. lot more time to display jobs page and many times blank or loading error. Part of the behavior seems to happen more when opening new tabs for job results.

**Comment by BanzaiMan** [comment] 2016-08-18 02:55
I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/4851.

**Closed by BanzaiMan** 2016-08-18 02:55 UTC

**Comment by juju4** [comment] 2016-08-18 10:30
Sorry but, I don't think so.
I'm not asking for integration of lxd into travis.
It's possible to do it manually like a script inside a trusty instance and that's what I do.

but when you do so there are issues appearing which doesn't in non-travis testing.

first one is similar to
https://github.com/travis-ci/travis-ci/issues/6497
https://github.com/travis-ci/travis-ci/issues/6155

or why a bash script returns exit code 127 or 255 without any details, especially when -x flag is set

**Comment by juju4** [comment] 2016-08-23 18:34
Hello Hiro,

is it possible to reassess this problem?

Thanks
