### ISSUE TITLE
nvm not found

### ISSUE THREAD

**Issue by theofidry** [travis-ci/travis-ci#6027] opened 2016-05-09 12:36 UTC
I'm experiencing a weird issue with [nvm](https://github.com/creationix/nvm). When trying to use it in a shell script executed in my travis build, I get an error stating that the command nvm has not been found.

My configuration is the following:

```yaml
# .travis.yml
sudo: false
language: php

php:
  - '5.6'
  - '7.0'

install:
  - echo $NVM_DIR;
  - nvm --version;
  - ./test.sh;

script:
  - echo "hello";

notifications:
    email: false
```

```bash
# test.sh
#!/bin/bash

set -evo pipefail

echo $NVM_DIR;
nvm --version;
```

So I'm echoing `$NVM_DIR` and displaying the nvm version in both Travis script and the executed script. The result is the following:

```
# Travis script
$ echo $NVM_DIR;
/home/travis/.nvm

$ nvm --version;
0.23.3

$ .travis/js_setup.sh;
echo $NVM_DIR;
/home/travis/.nvm
nvm --version;
.travis/test.sh: line 7: nvm: command not found
The command ".travis/js_setup.sh;" failed and exited with 127 during .
```

**Comment by BanzaiMan** [comment] 2016-05-09 13:17
Duplicate of https://github.com/travis-ci/travis-ci/issues/5999.

In particular, see https://github.com/travis-ci/travis-ci/issues/5999#issuecomment-217201571.

**Closed by BanzaiMan** 2016-05-09 13:17 UTC

**Comment by theofidry** [comment] 2016-05-09 13:33
Thanks for the quick reply @BanzaiMan, but sadly that doesn't help.

>`nvm` is a function, so you can't call it unless it is loaded.
In the bash script you are trying to use Node.js, be sure to load ~/.nvm/nvm.sh.

When I'm not in a shell script, I can use `nvm` so I guess it's already loaded. Then why is it no longer loaded when I am using it in a shell script?

Also I tried to modify my script to either download the latest version first, or load it directly, node works:

```
# test.sh
#!/bin/bash

set -evo pipefail

# Option1
source $NVM_DIR/nvm.sh

# Option2
curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh

echo $NVM_DIR;
nvm --version;
```

In both cases, I get an error `No .nvmrc file found`. It would be tempting to say it's a problem with nvm and not Travis, but the thing is, it is working fine when not executed in a shell script, so I'm not sure nvm is at fault here.

**Comment by BanzaiMan** [comment] 2016-05-09 13:35
Could you point to the build log that shows the problem with `source`ing `~/.nvm/nvm.sh`?

**Comment by theofidry** [comment] 2016-05-09 13:38
Sure: [link](https://travis-ci.com/haircvt/haircvt/jobs/39471223) (it's a private build)

**Comment by BanzaiMan** [comment] 2016-05-09 13:45
@theofidry Looks like this is best handled by a support ticket. Please email support@travis-ci.com along with the content of `.travis/js_setup.sh`.

**Comment by theofidry** [comment] 2016-05-09 13:46
Ok, thanks for the help.

**Comment by theofidry** [comment] 2016-05-09 15:16
Having it as a private repository was a bit awkward, here's a [public repo](https://github.com/theofidry/travis-bug-demo) with the bug reproduced. You can see the build [here](https://travis-ci.org/theofidry/travis-bug-demo/jobs/128878695).

**Comment by BanzaiMan** [comment] 2016-05-09 15:57
@theofidry As you have heard from our support team, the failure here is caused by `set -e` and the absence of `$NODE_JS_VERSION` in your test. The latter causes the build to run `nvm install ` with no arguments, which exits with 127, and the former causes the build to halt immediately.

**Comment by michaeljcoyne** [comment] 2017-08-11 15:04
I have this problem with vagrant. NVM is being ignored by php shell script.
