### ISSUE TITLE
Node.js build suddenly starves on new Trusty (as well as on deprecated and Precise) dist

### ISSUE THREAD

**Issue by bkimminich** [travis-ci/travis-ci#8909] opened 2017-12-13 16:56 UTC
### :information_source: Affected build
https://travis-ci.org/bkimminich/juice-shop

#### :bomb: Original failing build
https://travis-ci.org/bkimminich/juice-shop/builds/315897310

### :bug: Problem
The build does not get past the `script` step that executes `npm test`. The tests all pass, but before the following command (`npm run frisby`) gets executed, the build freezes and times out after 10min.

### :x: Failed Fix attempts
* Using `group: deprecated-2017Q4` with `sudo` enabled
  * :bomb: https://travis-ci.org/bkimminich/juice-shop/builds/315939897
* Using `dist: precise` with `sudo` enabled
  * :bomb: https://travis-ci.org/bkimminich/juice-shop/builds/315954012
* Commenting out the `npm run frisby` step
  * :bomb: https://travis-ci.org/bkimminich/juice-shop/builds/315960065
* Running all steps of `script` in one concatenated with `&&`
  * :bomb: https://travis-ci.org/bkimminich/juice-shop/builds/316345457

**Comment by bkimminich** [comment] 2017-12-14 10:55
To get my build passing again I needed to completely turn off all test suites
* ✔️ https://travis-ci.org/bkimminich/juice-shop/builds/316351590 

I am very confident that no change on my side caused this problem, as all test scripts continue to work on my local machine. Also I did not change anything in the test scripts between the last passing and first failing build.

**Comment by BanzaiMan** [comment] 2017-12-14 13:20
Sounds like a duplicate of #8898.

**Comment by BanzaiMan** [comment] 2017-12-15 01:39
Closing as a duplicate.

**Closed by BanzaiMan** 2017-12-15 01:39 UTC
Labels: 2017-Q4-trusty-env-update, node.js

**Comment by bkimminich** [comment] 2017-12-18 10:39
Running `travis_wait npm test` instead of `npm test` seems to solve this problem.
