### ISSUE TITLE
sh: 1: sw_vers: not found when storing build cache

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#8766] opened 2017-11-15 12:53 UTC
~~~~
store build cache
0.00s
17.68s/home/travis/.casher/bin/casher:214: warning: Insecure world writable dir /usr/local/clang-5.0.0/bin in PATH, mode 040777
change detected (content changed, file is created, or file is deleted):
/home/travis/.cache/pip/http/4/8/1/e/9/481e9dbd91ecb7ff2275b3bb3c0f569aae009ccfef551bfa134ff0bf
/home/travis/.cache/pip/http/5/9/7/1/d/5971db2a7f6952a542b353fd20a96462c609c4b8a847e4d6998e2208
/home/travis/.cache/pip/http/6/9/7/3/b/6973b954582ec3dd2facb294ab1e8497e8cb16fca2b3d7bf33784fb5
/home/travis/.cache/pip/http/7/4/3/9/b/7439b1abfa451402cf159900fa9af20da9eaca3cbecee9d263276732
/home/travis/.cache/pip/http/7/b/a/7/8/7ba7822e1842241eee3c36bc6e01d95939517028ff9143958ef19b6e
/home/travis/.cache/pip/http/7/f/9/4/c/7f94cc2d1b5a06fc658f7ef0424a1b3c919e5377f0c64218102400a0
/home/travis/.cache/pip/http/8/d/e/d/a/8deda849bcfd627b8587addf049f79bb333dd8fe1eae1d5053881039
/home/travis/.cache/pip/http/8/f/5/5/e/8f55e537a9bfa06f9e2ecc75d12e5fb14ed02118a71806a24f0e427f
/home/travis/.cache/pip/http/9/4/b/1/1/94b11f4c0ecbc9df4c121b7e8f1ed0ca0894d5e8badaaaad57431533
/home/travis/.cache/pip/http/c/f/1/7/1/cf171239dd457b336c28871defb4c1ccf6afca1de6aa4593263f1e82
/home/travis/.cache/pip/http/d/e/f/7/0/de

...

changes detected, packing new archive
sh: 1: sw_vers: not found
.
.
~~~~~

This seems to be non-fatal, but it is unclear what is causing it.

**Comment by BanzaiMan** [comment] 2017-11-15 15:59
A duplicate of #8724

**Closed by BanzaiMan** 2017-11-15 15:59 UTC
