### ISSUE TITLE
Add ability to split each build job as a separate pull request status check

### ISSUE THREAD

**Issue by tjanez** [travis-ci/travis-ci#6229] opened 2016-06-29 07:57 UTC
Hi!

On numerous occasions I would have found it very useful to see each build job as a separate pull request status check:

- One reason would be to quickly see what has failed without having to guess or leaving the GitHub's pull request page.
- The other reason would be to make it possible to specify only a subset of jobs/checks as [required to pass before merging](https://github.com/blog/2051-protected-branches-and-required-status-checks).

Therefore I would propose a configuration option that would allow having just one pull request status check for a build (i.e. what we have now) or having separate pull request status checks for each build job.

**Comment by BanzaiMan** [comment] 2016-07-02 22:09
I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/5035. If you think otherwise, please elaborate further.

**Closed by BanzaiMan** 2016-07-02 22:09 UTC
