### ISSUE TITLE
"No space left on device" error during build

### ISSUE THREAD

**Issue by onyb** [travis-ci/travis-ci#4008] opened 2015-06-02 13:59 UTC
I gathered that this is a known problem which has been fixed before, but for some reason I am getting it during the build. Here is the [log](https://travis-ci.org/vgvassilev/cling/jobs/64740877), and the [travis.yml](https://github.com/vgvassilev/cling/blob/FixMacOS/.travis.yml) for reference.

Though it is a Debug+Asserts build, I don't think that is the culprit. The problem only came up recently after we moved to container based infrastructure by adding `sudo: false`.

**Comment by enigmagroup** [comment] 2015-06-11 07:34
Same here: https://travis-ci.org/enigmagroup/enigmabox-openwrt/builds/66330613#L1840

We need moar space...

**Comment by roidrage** [comment] 2015-07-23 18:26
Are you still experiencing these issues?

**Comment by enigmagroup** [comment] 2015-07-25 06:46
Well I can't tell, the build is failing, but...

```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```

**Comment by joshk** [comment] 2015-07-25 15:22
Can you look at reducing you log output? That way we can confirm if the issue is still, well, an issue :)

**Comment by enigmagroup** [comment] 2015-07-26 10:25
Well I ran the build with the reduced output: https://travis-ci.org/enigmagroup/enigmabox-openwrt/builds/72422904 - it says: "Please re-run make with -j1 V=s to see what's going on"... This is a deadlock situation.

**Comment by joshk** [comment] 2015-07-26 12:22
Ok, is the deadlock issue a Travis issue?

**Comment by enigmagroup** [comment] 2015-07-27 17:45
Is there a way to increase the log size of travis to more than 4 MB?

**Comment by joshk** [comment] 2015-07-27 21:49
Not at the moment sorry, this limit is set for everyone.

**Comment by enigmagroup** [comment] 2015-08-05 14:06
Ok. Then I have no chance for investigating the exact error at the moment. You can close this issue.

**Comment by meatballhat** [comment] 2016-11-16 20:30
I'm closing this out for now.  Please yell if you are still experiencing this problem!  :heart:

**Closed by meatballhat** 2016-11-16 20:30 UTC
Labels: awaiting-followup, containers

**Comment by digitalentity** [comment] 2017-10-09 06:50
Still having the issue: https://travis-ci.org/iNavFlight/inav/jobs/285091312

**Comment by HarryFengYX** [comment] 2018-03-09 01:10
Me too, why are all unanswered bugs closed?
