### ISSUE TITLE
elixir build with "sudo: required" is failing

### ISSUE THREAD

**Issue by adrienmo** [travis-ci/travis-ci#6116] opened 2016-05-31 09:56 UTC
It seems the directive "sudo: required" is incompatible with elixir language. When I activate it, elixir will not be installed properly:

```
checkdir:  cannot create extraction directory: /home/travis/.kiex/elixirs//elixir-1.2.0
           No such file or directory
$ echo 'export ELIXIR_VERSION=1.2.0
    export PATH=$HOME/.kiex/elixirs/elixir-1.2.0/bin:$PATH
    export MIX_ARCHIVES=$HOME/.kiex/mix/elixir-1.2.0' > $HOME/.kiex/elixirs/elixir-1.2.0.env
/home/travis/build.sh: line 47: /home/travis/.kiex/elixirs/elixir-1.2.0.env: No such file or directory
$ kiex use 1.2.0
kiex: command not found
$ elixir --version
elixir: command not found
```

link to a failing build:

https://travis-ci.org/adrienmo/hbasex/builds/134109307

**Comment by BanzaiMan** [comment] 2016-06-02 23:02
This is basically a duplicate of https://github.com/travis-ci/travis-ci/issues/5428, which reports issues with Trusty image and Erlang builds. The current default Trusty image lacks many things, including things you need to get Elixir and Erlang going. (Note that https://docs.travis-ci.com/user/trusty-ci-environment does not mention it.)

So, in order to get it going on Trusty, please add the following to the top level of your `.travis.yml`:

```yaml
group: edge
```

**Closed by BanzaiMan** 2016-06-02 23:02 UTC
Labels: bug
