### ISSUE TITLE
issue with build that uses oraclejdk7

### ISSUE THREAD

**Issue by pjfanning** [travis-ci/travis-ci#8455] opened 2017-09-18 11:10 UTC
https://travis-ci.org/swagger-api/swagger-core/builds/276800350?utm_source=github_status&utm_medium=notification

This build was working for a number of months but now oraclejdk7 doesn't seem to work.
The JAVA_HOME doesn't seem to be set up correctly.

```
sudo: false
language: java
script: ./mvnw clean verify
jdk:
  - oraclejdk7
```

A branch that uses oraclejdk8 is building ok.

**Comment by BanzaiMan** [comment] 2017-09-18 11:45
Duplicate of #7884.

**Closed by BanzaiMan** 2017-09-18 11:45 UTC
