### ISSUE TITLE
Account wide environment variables

### ISSUE THREAD

**Issue by andye2004** [travis-ci/travis-ci#9210] opened 2018-02-09 12:57 UTC
I'm looking for the ability to create account wide environment variables. E.g. we have a JFrog Artifactory instance where we upload the generated artefacts, I don't want to have to define the access attributes for Artifactory in every repo we have I just want to do it once. I've had a look through the docs and can't find anything that would suggest this is possible.

So my question is; is this possible? If so, can someone explain the process?

If this is not possible please regard this question as a feature request to have this ability added?

Many thanks, Andy.

**Comment by BanzaiMan** [comment] 2018-02-09 13:52
Hello there. Thanks for opening this issue. I'm closing this as a duplicate of #7128.

**Closed by BanzaiMan** 2018-02-09 13:52 UTC
