### ISSUE TITLE
Problem with Python 3.2 

### ISSUE THREAD

**Issue by rmk135** [travis-ci/travis-ci#5510] opened 2016-01-25 12:30 UTC
I've started getting some problems with py32 job on several of my projects - 

https://travis-ci.org/ets-labs/dependency_injector/jobs/103316509
https://travis-ci.org/ets-labs/domain_models/jobs/104455565

I'm 100% sure that https://travis-ci.org/ets-labs/dependency_injector/jobs/103316509 worked well previously. Problem was seen first on the 23th of January.

Can someone, please, take a look?

**Comment by BanzaiMan** [comment] 2016-01-25 12:55
This is a duplicate of #5485.

Fix your tools' requirement resolution so that virtualenv 14.0.x is not downloaded. (See  https://github.com/travis-ci/travis-ci/issues/5485#issuecomment-173796893 and compare that with https://travis-ci.org/ets-labs/dependency_injector/jobs/103316509#L102)

https://travis-ci.org/ets-labs/domain_models/builds/104455558 probably failed the first time for the same reason, but someone appears to have rerun it after the PR was merged, so we can't fetch the correct ref.

**Closed by BanzaiMan** 2016-01-25 12:55 UTC
