### ISSUE TITLE
Update Oracle Java JDK

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4100] opened 2015-06-16 16:09 UTC
Can we update the Java8 Oracle version to 45?

HS reference: 17068

**Comment by BanzaiMan** [comment] 2015-06-16 17:55
I'm going to close this as a duplicate of #4042. If 8u45 is required now, you can use the APT addon, as explained in https://github.com/travis-ci/travis-ci/issues/4042#issuecomment-109756980.

**Closed by BanzaiMan** 2015-06-16 17:55 UTC
