### ISSUE TITLE
RFE: Deploy GitHub Pages failures really should cause of failure and include git log

### ISSUE THREAD

**Issue by vorburger** [travis-ci/travis-ci#10211] opened 2018-10-09 23:50 UTC
https://docs.travis-ci.com/user/deployment/pages/

https://travis-ci.org/vorburger/opendaylight-simple/jobs/439401089
https://api.travis-ci.org/v3/job/439401089/log.txt

failed with:

```
Doing the git push (workdir: /tmp/d20181009-4263-10h167x/work)...
Couldn't push the build to github.com/vorburger/opendaylight-simple-binaries.git:gh-pages

travis_fold:end:dpl.3
failed to deploy
```

and it took me a while, far too long, to understand what the cause really was... when trying it locally:

```
git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 104.58 MiB | 3.91 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: cf46cb72e9c9bc20648c23b65a3baa36
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File poc-1.0.0-SNAPSHOT-simple.tar is 120.90 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:vorburger/opendaylight-simple-binaries.git
 ! [remote rejected] gh-pages -> gh-pages (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:vorburger/opendaylight-simple-binaries.git'
```

It would IMHO be very useful if whatever script does the deploy could show git output on failure?

At the very least with `verbose = true` on `deploy:`, or better just always.

**Comment by BanzaiMan** [comment] 2018-10-28 13:04
Duplicate of #921.

**Closed by BanzaiMan** 2018-10-28 13:04 UTC
Labels: deployment
