### ISSUE TITLE
Can't create MySQL DB with 2015-04 update

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#3793] opened 2015-04-28 10:00 UTC
> $ mysql -e 'CREATE DATABASE `cscms.travis`;'
ERROR 1045 (28000): Access denied for user 'travis'@'localhost' (using password: NO)

https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/60333925

**Comment by roidrage** [comment] 2015-04-28 10:12
Looks like a duplicate of or similar to #3781? Can you try using 127.0.0.1 for the hostname?

**Comment by nazar-pc** [comment] 2015-04-28 10:16
I saw that issue, but here I'm getting it from terminal command with default settings, not from client code.
If `127.0.0.1` is a solution - it should be set in MySQL configuration by default, so that [example from your documentation](http://docs.travis-ci.com/user/database-setup/#sts=MySQL) will work.

**Comment by LoicMahieu** [comment] 2015-04-28 10:17
I run into a similar issue:
```
 * Stopping MySQL Community Server 5.6.24
 * MySQL Community Server 5.6.24 is already stopped
 * Re-starting MySQL Community Server 5.6.24
......
 * MySQL Community Server 5.6.24 did not start. Please check logs for more details.
```

MySQL Server seems to not start correctly...
Job: https://travis-ci.org/iGLOO-be/geopostcodes-sequelize-import/builds/60353101

**Comment by nazar-pc** [comment] 2015-04-28 20:05
Now even more interesting. PHP 5.6 container succeed, PHP 7 container succeed, PHP 5.5 container failed (tried twice): https://travis-ci.org/nazar-pc/CleverStyle-CMS/builds/60432971

**Comment by BanzaiMan** [comment] 2015-04-28 20:36
I believe this is a duplicate of #3781.

**Closed by BanzaiMan** 2015-04-28 20:36 UTC
