### ISSUE TITLE
All builds keep failing with error: BlockingIOError: [Errno 11] write could not complete without blocking

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [travis-ci/travis-ci#8982] opened 2017-12-28 13:08 UTC
Hello dear friends,

I recently have a new problem, all my build fails with the same error.

The thing which makes me think that the error is not on my side, if I re-build an old build which passed with no problem (say on the master branch, but I tried other branches too), now it also fails with the same error.

```
BlockingIOError: [Errno 11] write could not complete without blocking
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking
```

For a little context, the project is running Django 1.11.* or Django 2.0 (I got the error for all versions).
It appears when I run the following command:

```python manage.py collectstatic --noinput```

Obviously, my unittest are failing since django didn't finished to collect static files. And thus, the build is marked as failed ...

#### Example Build: https://travis-ci.org/DEKHTIARJonathan/FeedCrunch.IO/builds/299114737

**Before Rebuild:**
![image](https://user-images.githubusercontent.com/10923599/34411587-d30ee860-ebd7-11e7-8be3-8886bba0ce46.png)

**After Rebuild:**
![image](https://user-images.githubusercontent.com/10923599/34411668-84351092-ebd8-11e7-970d-e96b4e35a450.png)

**Build Error:**
![image](https://user-images.githubusercontent.com/10923599/34411663-68e6a490-ebd8-11e7-9dfd-13378ac193a3.png)

-------------

The repository is accessible here: https://github.com/DEKHTIARJonathan/FeedCrunch.IO
Travis builds are available here: https://travis-ci.org/DEKHTIARJonathan/FeedCrunch.IO

I tried more or less everything I thought to debug this ... Nothing seems to work.

The only thing which could be possible to me, is the Travis maximum allowed disk size decreased recently ? It could explain such a behaviour...

If it can help, the last time a build successfully passed it was: https://travis-ci.org/DEKHTIARJonathan/FeedCrunch.IO/builds/312924399

Thanks a lot for your help,

Best Regards,

Jonathan

**Comment by avagin** [comment] 2017-12-28 19:11
It looks like https://github.com/travis-ci/travis-ci/issues/8920

**Comment by DEKHTIARJonathan** [comment] 2017-12-28 21:04
Wow ! 

Thanks to @avagin, problem seems to be solved. With this command line in the .travis.yml 

```
 before_install:
 +- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
```

Can anyone explain what happened here ?
Admin (@BanzaiMan) can close the Issue if they consider it as "Closed".

**Comment by BanzaiMan** [comment] 2018-01-02 15:48
Closing this as a duplicate of #8920.

**Closed by BanzaiMan** 2018-01-02 15:48 UTC
