### ISSUE TITLE
Issues using matrix.include

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#3674] opened 2015-04-15 14:46 UTC
I am trying to use the following travis.yml file:

``` yml
sudo: false
language: python
python:
 - '2.7'
matrix:
  include:
   - env: SERVICE=s1
   - env: SERVICE=s2
     addons:
       apt:
         packages:
          - pkg-X
```

but this is resulting in two issues:
1) An extra build with no `SERVICE` set.
![image](https://cloud.githubusercontent.com/assets/51059/7161345/a754fe20-e35c-11e4-8178-1eb6011bd11a.png)

2) This:

```
$ source ~/virtualenv/python["2.7"]/bin/activate
/home/travis/build.sh: line 41: /home/travis/virtualenv/python[2.7]/bin/activate: No such file or directory
```

**Comment by cancan101** [comment] 2015-04-15 15:04
If I change the yaml file to this, I still get issue 2:
```yml
sudo: false
language: python
python:
 - '2.7'
env:
 - SERVICE=s1
matrix:
  include:
   - env: SERVICE=s2
     addons:
       apt:
         packages:
          - pkg-X
```
```
$ source ~/virtualenv/python["2.7"]/bin/activate
/home/travis/build.sh: line 41: /home/travis/virtualenv/python[2.7]/bin/activate: No such file or directory
```

**Comment by BanzaiMan** [comment] 2015-04-15 15:06
Looks like the 1-element `python` array is not properly handled here. Could you try:

```yaml
python: '2.7'
```

**Comment by BanzaiMan** [comment] 2015-04-15 15:22
Probably a duplicate of #3670.

**Comment by andyli** [comment] 2015-04-20 02:55
Same as #3638

**Comment by BanzaiMan** [comment] 2017-01-16 01:59
See #4681. The default job is there, and it is correct.

**Closed by BanzaiMan** 2017-01-16 01:59 UTC
Labels: matrix expansion, travis-yaml
