### ISSUE TITLE
URL case sensitivity

### ISSUE THREAD

**Issue by JulienPalard** [travis-ci/travis-ci#7656] opened 2017-04-24 13:16 UTC
Hi,

I'm kind of reopenning https://github.com/travis-ci/travis-ci/issues/1545, I know. I also know that we really should consider URLs as case sensitive.

But users may not even be aware that their git account is capitalized (I was not, I have 61 repos, I always typed "/julienpalard/", never "/JulienPalard/" and actually never spotted it was capitalized when I clicked a github link.

So I used "julienpalard" in my configurations, leading to not-that-hard to debug issues for me, but which may be hard to debug and very time-consuming for newcomers. I can easily imagine a newcomer completly dropping the idea of using Travis thinking "It just don't work, I'm getting 404s everywhere", which is sad, isn't it?

So I'm still considering this as Travis bug being incompatible in some way with github, even if was "github's fault" in the first place.

**Comment by BanzaiMan** [comment] 2017-06-02 02:55
Duplicate of #3198.

**Closed by BanzaiMan** 2017-06-02 02:55 UTC
Labels: feature-request, travis-api
