### ISSUE TITLE
Android build fails: android-update-sdk: command not found

### ISSUE THREAD

**Issue by omjokine** [travis-ci/travis-ci#3738] opened 2015-04-22 10:34 UTC
Hi,

Recently all of our Android builds have been failed because travis doesn't find command "android-update-sdk". 

Here's the current .travis.yml:

```
jdk:
  - oraclejdk8
language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
script: ./gradlew test
```
and here's the output:
```
$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle
$ export TERM=dumb
Installing Android dependencies
0.01s$ android-update-sdk --components=build-tools-22.0.1
/home/travis/build.sh: line 41: android-update-sdk: command not found
```

**Comment by BanzaiMan** [comment] 2015-04-22 10:42
Could you point to the build log URL that shows this problem?

**Comment by omjokine** [comment] 2015-04-22 11:10
@BanzaiMan emailed URL to support@travis-ci.com, can't share build log URL here :)

**Comment by jaredzhang** [comment] 2015-04-22 11:15
I also have this issue today.

`The command "android-update-sdk --components=build-tools-21.1.1" failed and exited with 127 during`

**Comment by BanzaiMan** [comment] 2015-04-22 11:55
Thanks for the report. We've identified the problem, and we are working to bring it back as soon as possible.

The problem is confined to .com.

**Comment by twang2218** [comment] 2015-04-22 12:10
I tried run ```android list target``` on the test machine, this is what I received for api-22

```
id: 10 or "android-22"
     Name: Android 5.1.1
     Type: Platform
     API level: 22
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
```

The final line said it's no ABI for API 22, so there is no sys-img for API 22.

**Comment by BanzaiMan** [comment] 2015-04-22 15:17
This issue should be fixed now. Thank you for your patience.

If you continue to see problems, email support@travis-ci.com, please.

**Closed by BanzaiMan** 2015-04-22 15:17 UTC
Labels: android

**Comment by BanzaiMan** [comment] 2015-04-22 15:29
You could also re-run the failing build, if you wish.

**Comment by omjokine** [comment] 2015-04-22 15:37
Yep, works now. Thanks @BanzaiMan

**Comment by IgorGanapolsky** [comment] 2015-08-03 15:45
Can we now use `build-tools-23.0.0-rc3`?

**Comment by MGaetan89** [comment] 2015-08-22 11:32
Or `23.0.0` as it is now available in a stable release?
