### ISSUE TITLE
Regarding lftp issue

### ISSUE THREAD

**Issue by bravetux** [travis-ci/travis-ci#9738] opened 2018-06-11 16:43 UTC
I have this git hub code, using python and pelican framework to build and upload the output from https://github.com/rvp-ashram/website to Website www.sriramanavidyapeedam.org (Hosted in GoDaddy) via FTP. I am currently using LFTP Client.

Please find the attached travis.yml which i am using.

When trying to transfer files, I am running into the following issue
---- Connecting to sriramanavidyapeedam.org (43.255.154.95) port 21
WARNING: Certificate verification: hostname checking disabled
**** gnutls_handshake: A TLS packet with unexpected length was received.
**** Timeout - reconnecting

[travis.yml.txt](https://github.com/travis-ci/travis-ci/files/2090900/travis.yml.txt)

Could you please help to fix the configuration.

**Comment by BanzaiMan** [comment] 2018-09-06 14:14
Hello, there. I believe this is a duplicate of #9732.

**Closed by BanzaiMan** 2018-09-06 14:14 UTC
