### ISSUE TITLE
Random build failure caused by "power button pressed"

### ISSUE THREAD

**Issue by marc1706** [travis-ci/travis-ci#5822] opened 2016-03-26 14:22 UTC
We're getting random build failures while running tests on travis (e.g. https://travis-ci.org/phpbb/phpbb/jobs/118190092). The failure message seems to always be:
```
...................................
Broadcast message from root@testing-gce-89ccaec3-d073-4555-a21f-74fb03722223
	(unknown) at 10:08 ...
The system is going down for halt NOW!
Power button pressed 

Broadcast message from root@testing-gce-89ccaec3-d073-4555-a21f-74fb03722223
	(unknown) at 10:08 ...
The system is going down for halt NOW!
Power button pressed 
.EEESSEEEEEEEEEEEEEEEEEEEE 5185 / 5231 ( 99%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
Time: 7.21 minutes, Memory: 312.00Mb
There were 67 errors:
```
I'm not sure how this can happen but we're fairly certain that we're not pressing the power button.

**Comment by Joshua-Anderson** [comment] 2016-03-26 17:27
That's probably Travis CI shutting down the host machine that your tests are running one. The tests should be restarted automatically but that seems not to happen lately.

**Comment by Nicofuma** [comment] 2016-03-26 18:02
It happened ~5 times in the last days and the job was never restarted

**Comment by ribasushi** [comment] 2016-04-21 18:34
This should be closed as a duplicate of https://github.com/travis-ci/travis-ci/issues/4924

**Closed** 2016-04-21 20:15 UTC
Labels: team blue
