### ISSUE TITLE
Broken pypy on trusty?

### ISSUE THREAD

**Issue by tgoodlet** [travis-ci/travis-ci#8130] opened 2017-07-20 05:59 UTC
See the run here for the log:
https://travis-ci.org/SIPp/pysipp/jobs/217224788

Jist of it is that there seems to be a problem downloading the package due to a missing name?
```
pypy is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/-.tar.bz2
$ sudo tar xjf -.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf -.tar.bz2 --directory /" failed and exited with 2 during .
```

**Comment by BanzaiMan** [comment] 2017-07-20 12:27
Thanks for taking time to open this issue. I'm closing this as a duplicate of #6865.

**Comment by BanzaiMan** [comment] 2017-07-20 12:27
For now, please use `dist: precise`.

**Closed by BanzaiMan** 2017-07-20 12:27 UTC

**Comment by tgoodlet** [comment] 2017-07-20 14:05
@BanzaiMan thanks and sorry about the duplicate - I shouldn't scan issues lists late at night hehe.
