### ISSUE TITLE
"clang: command not found" when running under sudo

### ISSUE THREAD

**Issue by fgsch** [travis-ci/travis-ci#3088] opened 2015-01-07 06:40 UTC
fgsch/libvmod-geoip2 fails with clang, works fine with gcc.

"sudo make install" triggers clang but I guess is not in the PATH? I'd expect to either fail or succeed in both cases, not mixed results.

**Comment by fgsch** [comment] 2015-01-07 15:11
I did that change recently, before it was running make as the regular user.
Should we expect to work the same as gcc or this is expected? It's weird that works under one compiler but not the other? I don't mind changing the PATH but it feels wrong that works under one compiler and not the other.

**Comment by BanzaiMan** [comment] 2015-01-13 03:00
The appropriate directory will be placed on `$PATH` for login shells, but `sudo` by itself bypasses it. You can load the desired `$PATH` with `sudo -i`.

```
$ sudo -i  which clang
/usr/local/clang-3.4/bin/clang
$ sudo -i clang --version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Based on the way we install these packages, I'm inclined to just document this difference, rather than making `gcc` and `clang` behave the same way with respect to the `root` user.

**Comment by fgsch** [comment] 2015-01-13 05:47
If that's your preference I'm fine with it but I still believe is odd.  Re whether it will work with sudo you can tell sudo to preserve the environment in sudoers or use secure_paths. 
I've fixed my yml to do make under the regular user and make install with sudo.

**Comment by BanzaiMan** [comment] 2017-09-11 00:37
In essence, this is a duplicate of #1350.

**Closed by BanzaiMan** 2017-09-11 00:37 UTC
Labels: travis-build, travis-cookbooks
