### ISSUE TITLE
starting postgresql in osx build env

### ISSUE THREAD

**Issue by matthijs** [travis-ci/travis-ci#6581] opened 2016-09-09 07:35 UTC
Hello,

It seems that I can't get PostgreSQL started in an OSX build, I tried:
- brew services launch postgresql
  says: succesfully started, but a call with psql fails with cannot connect

On my local mac it works correctly, so I'm not sure what's going on here.

See my .travis.yml: https://github.com/matthijs/sqlpp11-connector-postgresql/blob/develop/.travis.yml

Can someone enlighten me what I'm doing wrong here?

Regards, Matthijs

**Comment by BanzaiMan** [comment] 2016-09-09 07:44
OS X images should have PostgreSQL pre-installed. https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

Why are you installing your own?

**Comment by matthijs** [comment] 2016-09-09 08:07
Ok, I just removed the installation from the yml file and now the results can be seen here:
https://travis-ci.org/matthijs/sqlpp11-connector-postgresql/jobs/158667818

It seems it cannot connect to PostgreSQL, so I assumed it was not installed or running.

**Comment by Apollon77** [comment] 2016-11-30 11:07
I found the following to work on default xcode images:

`  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi
`

ou need to remove the content of the postgres-DB directory because the inited DB is from v9.4 and will not start with 9.5, so remove and init and then start server.

**Comment by BanzaiMan** [comment] 2016-12-09 06:01
I think this is a duplicate of #1875. Closing for now.

**Closed by BanzaiMan** 2016-12-09 06:01 UTC
