### ISSUE TITLE
Bug in the retry/cancel build action

### ISSUE THREAD

**Issue by chriscct7** [travis-ci/travis-ci#3265] opened 2015-02-22 19:52 UTC
Depending on the build status, Travis offers the ability to either retry the build (if the build has completed) or cancel all remaining runs in a build if not.

Seems there's a bug in this option. I should be able to cancel the rest of the runs right now, but as you can see its instead offering me the option to retry the build:

![screenshot at 14-47-03](https://cloud.githubusercontent.com/assets/1324637/6320056/5c8630a4-baa2-11e4-8d22-8fd96a32172e.png)

**Comment by BanzaiMan** [comment] 2015-02-22 20:23
Sounds like a duplicate of #2658.

**Comment by chriscct7** [comment] 2015-02-22 20:29
Ah indeed. Didn't realize it was related to fast_finish. My apologies.

**Comment by joshk** [comment] 2015-02-23 02:07
Actually, this issue is different to what is reported in #2658. 

I'm going to reopen this as I think this bug is worth fixing while we consider the other issue.

**Comment by joshk** [comment] 2015-02-23 02:11
And I was wrong, it is the same issue. Closing again. Will talk to the team about this.

**Closed by joshk** 2015-02-23 02:11 UTC
Labels: bug, team teal, ui
