### ISSUE TITLE
lodash package not up to date in iojs v2.2.0

### ISSUE THREAD

**Issue by riggerthegeek** [travis-ci/travis-ci#3995] opened 2015-05-31 19:33 UTC
This is a bit of a weird one.  I'm running tests on NodeJS v0.10, 0.11 and 0.12 and also the iojs - today, this is v2.2.0.  I'm getting the following error on the iojs:

    npm ERR! notarget No compatible version found: lodash@'>=3.9.3 <4.0.0'
    npm ERR! notarget Valid install targets:
    npm ERR! notarget ["0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.4.2","0.5.0-rc.1","0.5.0","0.5.1","0.5.2","0.6.0","0.6.1","0.7.0","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1","0.9.2","0.10.0","1.0.0-rc.1","1.0.0-rc.2","1.0.0-rc.3","1.0.0","1.0.1","1.1.0","1.1.1","1.2.0","1.2.1","1.3.0","1.3.1","2.0.0","2.1.0","2.2.0","2.2.1","2.3.0","2.4.0","2.4.1","3.0.0","3.0.1","3.1.0"]

When I run it locally, it works.  Also, if you look at the [lodash](http://registry.npmjs.org/lodash) npm page, the current version is 3.9.3 (which is what I'm trying to install).  It's like the npm cache is broken (I have tried clearing it, but to no avail)

Can someone have a look at why this is failing please?

[View the log](https://travis-ci.org/slash-dev-slash-null/steeplejack-restify/builds/64823415)

**Comment by BanzaiMan** [comment] 2015-05-31 20:50
Sounds like a duplicate of https://github.com/travis-ci/travis-ci/issues/3992. Reopen if you have reasons to believe otherwise.

**Closed by BanzaiMan** 2015-05-31 20:50 UTC

**Comment by riggerthegeek** [comment] 2015-05-31 20:53
Yes, I'd agree with that.
