### ISSUE TITLE
Bug report: Getting many 'broken' emails

### ISSUE THREAD

**Issue by evert** [travis-ci/travis-ci#4975] opened 2015-10-20 03:09 UTC
I noticed when my build breaks I now get 8 distinct notification emails. When it's fixed again, I get just one. This looks like a bug. Could it have to do something with the `fast_finish` option?

* [My project](https://github.com/fruux/sabre-dav/)
* [A failed build that triggered 8 emails](https://travis-ci.org/fruux/sabre-dav/builds/86319684)

**Comment by joshk** [comment] 2015-10-20 12:08
There is a bug with `fast_finish` which we have not been able to look into yet. I would recommend removing it for the time being.

**Comment by evert** [comment] 2015-10-20 17:42
Turning off fast_finish did indeed fix my problem.

**Comment by Croydon** [comment] 2015-12-20 15:46
See also #4928 and #4988.

**Comment by joshk** [comment] 2015-12-21 14:29
Closing as this is a duplicate of #4928

**Closed by joshk** 2015-12-21 14:29 UTC
