### ISSUE TITLE
emails never reach google groups mailing list

### ISSUE THREAD

**Issue by crowell** [travis-ci/travis-ci#5321] opened 2015-12-17 16:45 UTC
I've set up travis to email `pagespeed-dev@googlegroups.com` on failed builds, and the emails never arrive even to be moderated.

I've added my personal email also to the list of email targets, and both show up in the to field.

full email that arrives on my email, but doesn't appear in the mailing list inbox

https://gist.github.com/crowell/4e70bba12acaf742a7c2

travis.yml in setup

https://raw.githubusercontent.com/pagespeed/mod_pagespeed/master/.travis.yml

**Comment by BanzaiMan** [comment] 2015-12-17 17:25
I think this is a duplicate of #2513.

**Comment by crowell** [comment] 2015-12-17 19:59
@BanzaiMan yep, looks like a dup, still no update in a year :-1:

**Comment by BanzaiMan** [comment] 2015-12-17 20:07
Sorry about the lack of updates. I'm closing this one as a duplicate.

**Closed by BanzaiMan** 2015-12-17 20:07 UTC
