### ISSUE TITLE
Travis can't test git branches with unicode

### ISSUE THREAD

**Issue by emord** [travis-ci/travis-ci#5653] opened 2016-02-18 15:49 UTC
https://travis-ci.org/dimagi/Vellum/builds/109944234

I have a branch named 🍌 that fails on pull (the merge test works fine though)

**Comment by BanzaiMan** [comment] 2016-02-18 16:40
A duplicate of #2169, which is a variant of #1376.

**Closed by BanzaiMan** 2016-02-18 16:40 UTC
