### ISSUE TITLE
GitHub integration: Exclude certain files from triggering the build

### ISSUE THREAD

**Issue by automatictester** [travis-ci/travis-ci#4292] opened 2015-07-11 09:56 UTC
Possibly a feature request, as I didn't find it documented anywhere. Commits pushed to GitHub which include changes only to certain files (like README.md) don't need to trigger a build, as they can't break/fix anything. The way I could imagine it is implemented, is `excluded_files:` entry with a number of sub-entries in `.travis.yml` file. If pushed changes do not include changes to any other files than listed under `excluded_files:`, build is not triggered. This could save Travis CI some resources and also prevent unnecessary changes from triggering pointless builds. Not sure how difficult it is to implement. What do you think about it?

**Comment by BanzaiMan** [comment] 2015-07-13 14:26
This is a duplicate of #2307. We understand the use case, but we are not planning to add this feature. Sorry.

**Closed by BanzaiMan** 2015-07-13 14:26 UTC
