### ISSUE TITLE
mozroots: command not found

### ISSUE THREAD

**Issue by paoolo** [travis-ci/travis-ci#3141] opened 2015-01-25 21:09 UTC
```
Installing Mono
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.5TmhTyd4fO --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
4.91s5.38sFailed to fetch http://download.mono-project.com/repo/debian/pool/main/n/nunit/libnunit-util2.6.3-cil_2.6.3+dfsg-1~xamarin2_all.deb  Hash Sum mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
0.01s/home/travis/build.sh: line 41: mozroots: command not found
```

Using default Travis config for C# project.

```
language: csharp
solution: directory/solution.sln
script:
  - cd driectory
  - xbuild /p:Configuration=Release solution.sln
```

/cc @joshua-anderson @akoeplinger @nterry

**Comment by paoolo** [comment] 2015-01-25 21:10
@joshua-anderson @akoeplinger @nterry would like to help?

**Comment by akoeplinger** [comment] 2015-01-25 23:46
@paoolo does this happen consistently for you? seems like it couldn't install Mono (or more specifically the nunit package) due to some hash mismatch, which might be a glitch with the particular CDN endpoint the build is using (it works fine here locally).

The "mozroots: command not found" is expected in this case as Mono installation failed.

**Comment by nterry** [comment] 2015-01-26 05:36
Indeed. See the error above the mozroots one. There's a hash sum mismatch
error. Mono failed to install and mozroots is part of mono I believe...

Is this consistent for you? If so, there may be an issue with the upstream
repo. This wouldn't be the first time ;)

**Comment by paoolo** [comment] 2015-01-27 21:30
I will try again use your solution to build C# project. During last day I mocked configuration using config:

```
language: c
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild Solution.sln
```

**Comment by matthid** [comment] 2015-03-06 14:17
I managed to get the same thing:
```
W: Size of file /var/lib/apt/lists/www.rabbitmq.com_debian_dists_testing_main_binary-amd64_Packages.gz is not what the server reported 495 497
W: Size of file /var/lib/apt/lists/www.rabbitmq.com_debian_dists_testing_main_binary-i386_Packages.gz is not what the server reported 495 497
10.29sFailed to fetch http://download.mono-project.com/repo/debian/pool/main/n/nunit/libnunit-core2.6.3-cil_2.6.3+dfsg-1~xamarin2_all.deb Hash Sum mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
0.00s/home/travis/build.sh: line 41: mozroots: command not found
```

Restarting the build fixed the problem.

**Comment by akoeplinger** [comment] 2015-03-06 14:24
@matthid just curious, did you get this on a repo that has `sudo: false` (i.e. the container-based infrastructure) or on the normal infrastructure? We've seen these network-related glitches on the normal one before, but never on the container-based.

**Comment by matthid** [comment] 2015-03-06 14:29
yes it was a `sudo: false` repository

**Comment by akoeplinger** [comment] 2015-03-06 14:33
Interesting. Anyway, those glitches are terribly hard to diagnose, let's hope they don't happen too often (and I assume they'll be even less often when we introduce caching for the APT repo).

**Comment by BanzaiMan** [comment] 2015-03-17 15:46
Closing, as this is working as designed.

**Closed by BanzaiMan** 2015-03-17 15:46 UTC
Labels: community:csharp
