### ISSUE TITLE
Sudo required no longer works in Travis

### ISSUE THREAD

**Issue by alexflav23** [travis-ci/travis-ci#8449] opened 2017-09-17 19:37 UTC
Using Travis OSS with a `.travis.yml` that looks like this:

```bash
language: scala
sudo: required
dist: trusty
```

The project in question is open source so you can have a look at the setup [here](https://github.com/outworkers/phantom/blob/develop/.travis.yml).

In the `install` phase this requires sudo access to install a suitable version of Cassandra. The one offered standard by `services: cassandra` is very old and we need fine grained control to make sure the software is tested across all JDKs, but since certain versions of Cassandra don't work with JDK 7 and certain features of Cassandra are not available in the one Travis includes but require testing by our software, there's no way around the custom install script.

```bash
install: ./build/install_cassandra.sh
``` 

This worked just fine up until 10 days ago or so, when it randomly started failing with the following error message:

```
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting ccm
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading ccm-2.8.4.tar.gz (70kB)
Requirement already satisfied: pyYaml in /usr/lib/python2.7/dist-packages (from ccm)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from ccm)
Building wheels for collected packages: ccm
  Running setup.py bdist_wheel for ccm: started
  Running setup.py bdist_wheel for ccm: finished with status 'done'
  Stored in directory: /home/travis/.cache/pip/wheels/cb/61/75/664b13846ee273982de966cd6ca6345b8dc9bf0492e71652d1
Successfully built ccm
Installing collected packages: ccm
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/ccmlib'
./build/install_cassandra.sh: line 38: ccm: command not found
```

**Comment by BanzaiMan** [comment] 2017-09-18 21:24
Do you have a build log URL that shows the problem you are describing here?

**Comment by makapuf** [comment] 2017-10-05 17:29
same issue for me with a ```pip install Pillow```

**Comment by guitorri** [comment] 2017-10-07 22:32
This one just failed with a similar `Permission Denied` error
https://travis-ci.org/Qucs/qucs/jobs/284809885
We just switched to Trusty. Shall we revert?

**Comment by BanzaiMan** [comment] 2017-10-07 23:32
Maybe this is a duplicate of https://github.com/travis-ci/travis-ci/issues/8464, of which a workaround is mentioned in https://github.com/travis-ci/travis-ci/issues/8464#issuecomment-334879790.

**Comment by BanzaiMan** [comment] 2017-10-07 23:33
Oops. That was for the SSL warning. Please disregard it.

**Comment by BanzaiMan** [comment] 2017-10-07 23:47
I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/8382. Try adding `--user` to `pip install`. Once confirmed, I'll close this as a duplicate.

**Comment by BanzaiMan** [comment] 2017-10-07 23:48
Also https://github.com/travis-ci/travis-ci/issues/8378.

**Comment by guitorri** [comment] 2017-10-08 11:24
`pip install --user [package]` worked for us. Thank you!

**Comment by BanzaiMan** [comment] 2017-10-08 13:53
Closing as a duplicate.

**Closed by BanzaiMan** 2017-10-08 13:53 UTC
Labels: 2017-Q3-trusty-env-update, python, trusty
