### ISSUE TITLE
No output has been received in the last 10 minutes

### ISSUE THREAD

**Issue by markroxor** [travis-ci/travis-ci#6751] opened 2016-10-19 11:09 UTC
When I tried sending a pull request to a [gensim](https://github.com/RaRe-Technologies/gensim) I am being greeted by the message `No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.` for the builds [2302](https://travis-ci.org/RaRe-Technologies/gensim/builds/2302),[2303](https://travis-ci.org/RaRe-Technologies/gensim/builds/2303) and [2306](https://travis-ci.org/RaRe-Technologies/gensim/builds/2306) whereas my builds pass perfectly in my own repository as in [24](https://travis-ci.org/markroxor/gensim/builds/24),[25](https://travis-ci.org/markroxor/gensim/builds/25) and [26](https://travis-ci.org/markroxor/gensim/builds/26).

**Comment by BanzaiMan** [comment] 2017-01-16 16:12
Sorry for the delay. Is this still an issue? Recent builds don't seem to have this problem.

**Comment by tmylk** [comment] 2017-01-16 17:09
There is still an issue with [this test](https://github.com/RaRe-Technologies/gensim/blob/699773a78f32ff2c254cf16a586a5d26a08394fe/gensim/test/test_wikicorpus.py#L29).  We have commented it out because it was causing too much noise.

**Comment by BanzaiMan** [comment] 2017-01-27 23:26
None of the links are functional for some reason right now. Could someone point to relevant links again?

**Comment by BanzaiMan** [comment] 2017-07-12 18:43
I'm closing this as a duplicate of #6861 for now. Please provide additional information if you believe otherwise.

**Closed by BanzaiMan** 2017-07-12 18:43 UTC
