### ISSUE TITLE
job priorities?

### ISSUE THREAD

**Issue by Leooo** [travis-ci/travis-ci#7356] opened 2017-02-21 15:10 UTC
in Travis, is there a way to set job priorities? We have a big app partitioned taking lots of jobs to complete, and we don't want to prevent other apps to run their smaller tests in our shared Travis, i.e. their jobs should have higher priority than ours.

We already tried to limit to 6 concurrent jobs for our partition of 12, but it will still queue the other jobs so will have to still wait for all the jobs to finish before someone else can run tests..

copy of https://github.com/travis-ci/docs-travis-ci-com/issues/976#issuecomment-281366471

**Comment by BanzaiMan** [comment] 2017-03-02 14:45
This is a duplicate of #2566. We are aware of the feature request, and we have an internal ticket to track the interest, but no update to share.

I'm closing this as a duplicate. If we have updates to share in the future, we will reopen the old one. Thanks!

**Closed by BanzaiMan** 2017-03-02 14:45 UTC
Labels: feature-request
