### ISSUE TITLE
ruby-head tests fails with unf-ext gem

### ISSUE THREAD

**Issue by marshall-lee** [travis-ci/travis-ci#5552] opened 2016-02-01 15:30 UTC
With `language: ruby`, when `unf-ext` gem is used as a dependency, `ruby-head` tests fail (for now `ruby-head` is `2.4.0`).

There are samples:
https://travis-ci.org/knu/ruby-unf_ext/jobs/106237895
https://travis-ci.org/e2/nenv/jobs/106121037

Probably requires fixing something related to rvm.

**Comment by BanzaiMan** [comment] 2016-02-05 23:44
I am going to close this in favor of #5580, which has more information. That ticket deals with 2.1.8, but I think the issue is an unexpected change in packaging process that manifests in similar ways.

**Closed by BanzaiMan** 2016-02-05 23:44 UTC

**Comment by ab** [comment] 2016-05-20 04:42
Is this fixed? I'm still seeing it on `ruby-head`. https://travis-ci.org/rest-client/rest-client/jobs/131599689
