### ISSUE TITLE
Bug: on `tags: true` deploys, `$TRAVIS_BRANCH` is set to the tag name instead of the branch

### ISSUE THREAD

**Issue by eteubert** [travis-ci/travis-ci#4802] opened 2015-09-15 05:32 UTC
Example build: https://travis-ci.org/eteubert/plugin-deployment-demo/builds/80370048 (tag and branch are echoed in the `Deploying Application` block):

```
Starting Build
Tag: 0.1-pre3
Branch: 0.1-pre3 # should be "master", there is no "0.1-pre3" branch
```

Example repo: https://github.com/eteubert/plugin-deployment-demo

```yml
# .travis.yml
sudo: false
language: php
php:
  - 5.4

deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy.sh
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ (pre|alpha|beta|rc)[0-9]+$"
```

```bash
# bin/deploy.sh
echo "Starting Build"
echo "Tag: $TRAVIS_TAG"
echo "Branch: $TRAVIS_BRANCH"
# ... deploy code
```

/edit:

I realize that the initial git clone already specifies the tag as a branch. Why does it do that?

```bash
git clone --depth=50 --branch=0.1-pre3 https://github.com/eteubert/plugin-deployment-demo.git 
```
/edit2:

Oh, I see. `--branch` on clone also takes tags as an argument but leaves git in a detached HEAD state. I guess it's not really a Travis issue then. Just the `$TRAVIS_BRANCH` value is misleading.

**Comment by BanzaiMan** [comment] 2015-09-15 12:10
I believe this is a duplicate of #4643. Please provide additional details if you think otherwise. Thanks.

**Closed by BanzaiMan** 2015-09-15 12:10 UTC

**Comment by eteubert** [comment] 2015-09-15 12:54
This is not PR related. It originates in the way Travis checks out tags.

Let me show you by example:

```
code
› git clone --depth=50 --branch=0.1-pre3 https://github.com/eteubert/plugin-deployment-demo.git eteubert/plugin-deployment-demo
Cloning into 'eteubert/plugin-deployment-demo'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (15/15), done.
Unpacking objects: 100% (29/29), done.
remote: Total 29 (delta 5), reused 0 (delta 0), pack-reused 12
Checking connectivity... done.
Note: checking out '2970f8a8b4e24633708b7fa49a2e35c6dc3259bf'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>


code
› cd eteubert/plugin-deployment-demo

plugin-deployment-demo
› git checkout -qf 2970f8a8b4e24633708b7fa49a2e35c6dc3259bf

plugin-deployment-demo
› git branch
* (no branch)

plugin-deployment-demo
› git branch -a
* (no branch)

plugin-deployment-demo
› cat .git/config
...
[remote "origin"]
	url = https://github.com/eteubert/plugin-deployment-demo.git
	fetch = +refs/tags/0.1-pre3:refs/tags/0.1-pre3
```

Look at the last line, the "fetch" entry in the config. Using `git clone --branch=<tagname>` rather than cloning and then switching to the tag results in a config very different from a normal clone. Instead of the usual `fetch = +refs/heads/*:refs/remotes/origin/*` there is `fetch = +refs/tags/0.1-pre3:refs/tags/0.1-pre3`. There are no branches at all, just tags.

**Comment by BanzaiMan** [comment] 2015-09-15 13:18
Ah, sorry. Please see #4745.

**Comment by eteubert** [comment] 2015-09-16 01:25
Ah, right, that's the same issue :)
