### ISSUE TITLE
Wrong version of PHPUnit binary

### ISSUE THREAD

**Issue by theofidry** [travis-ci/travis-ci#5752] opened 2016-03-06 16:04 UTC
By default PHPUnit binary on a PHP 5.6 build is PHPUnit 4.5.0. As reported in sebastianbergmann/phpunit#2107, PHPUnit versions prior to 4.6.5 cannot be self-updated.

Would it be possible to upgrade the default binary version to at least PHPUnit 4.6.5? I could even be upgrade to 4.8.x as PHPUnit is semver and would not have any BC break compared to the current version.

**Comment by BanzaiMan** [comment] 2016-03-06 19:35
I am afraid that the pre-installed version is not going to be updated.

Ones which were recently built and available for on-demand installation (such as 5.6.18) might have a version of PHPUnit recent enough for you.

**Comment by theofidry** [comment] 2016-03-06 19:40
@BanzaiMan they are not sadly, all on-demand installation for PHP < 7.0 have a PHPUnit 4.5.0 at best. All PHPUnit version <4.6.5 are affected, so any build with PHP < 7.0 suffers from this problem.

**Comment by BanzaiMan** [comment] 2016-03-06 19:43
Did you try it? https://travis-ci.org/BanzaiMan/travis_production_test/builds/114093367#L143

**Comment by BanzaiMan** [comment] 2016-03-06 19:45
Either way, I believe you can update PHPUnit by downloading an archive and installing it yourself.

**Comment by theofidry** [comment] 2016-03-06 19:56
My bad, `php: 5.6` defaults to `5.6.5`. But we very rarely add the patch number on PHP projects :/

>Either way, I believe you can update PHPUnit by downloading an archive and installing it yourself.

Oh we can for sure, or even use the one we are installing with Composer. The issue is however that when developing, we are often using PHPUnit 5.x (especially if we're developing on PHP7). The result is that the PHPUnit used is incompatible with older platform. In the end we're finding a workaround depending of the use case to install the appropriate version of PHPUnit for each platform.

The result is, however, that we are ending up extra work that requires more configuration and more build time for something that could easily be fixed by providing the right version by default. It is not a huge problem as there is some workarounds, but is definitely an inconvenience still.

**Comment by BanzaiMan** [comment] 2016-03-06 22:08
I understand what you're saying, and I agree that the default software is reasonably recent.

There are things that are delaying build environment updates, which will resolve this problem. Until then, some sort of workaround, be it updating PHPUnit yourself or specifying the TEENY version in the PHP, is necessary.

Thank you for your understanding.

**Comment by BanzaiMan** [comment] 2016-03-25 05:19
Closing as a duplicate of #4897.

**Closed by BanzaiMan** 2016-03-25 05:19 UTC
Labels: php, travis-cookbooks
