### ISSUE TITLE
Deploy error out on tag_name is not well-formed although git tag is presetn and created on git repo

### ISSUE THREAD

**Issue by linearregression** [travis-ci/travis-ci#5400] opened 2016-01-04 01:21 UTC
TravisCI build link:
https://travis-ci.org/linearregression/travis_elixir_plt_generator/jobs/100028517
I am using travis.yml:
https://github.com/linearregression/travis_elixir_plt_generator/blob/8b95c2de3c64a2b7052042a3eb6da2001fb7bb05/.travis.yml
Issue:

```
Installing deploy dependencies

Fetching: addressable-2.3.8.gem (100%)

Successfully installed addressable-2.3.8

Fetching: multipart-post-2.0.0.gem (100%)

Successfully installed multipart-post-2.0.0

Fetching: faraday-0.9.2.gem (100%)

Successfully installed faraday-0.9.2

Fetching: sawyer-0.6.0.gem (100%)

Successfully installed sawyer-0.6.0

Fetching: octokit-4.2.0.gem (100%)

Successfully installed octokit-4.2.0

5 gems installed

Fetching: mime-types-2.99.gem (100%)

Successfully installed mime-types-2.99

1 gem installed

dpl.2

Preparing deploy

Logged in as edwardttril

Deploying to repo: linearregression/travis_elixir_plt_generator

Current tag is: 

dpl.3

Deploying application

/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/linearregression/travis_elixir_plt_generator/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)

Error summary:

  resource: Release

  code: missing_field

  field: tag_name

  resource: Release

  code: custom

  field: tag_name

  message: tag_name is not well-formed

  resource: Release

  code: custom

  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release

    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'

    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
```

**Comment by BanzaiMan** [comment] 2016-01-04 02:09
Looks like a duplicate of #2510.

**Comment by linearregression** [comment] 2016-01-04 02:27
No it is not. 

before_deploy: git fetch --tags to your .travis.yml has already been added

**Comment by BanzaiMan** [comment] 2016-01-04 03:44
Hmm. https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/100028516 is not a tagged build, so this fails. Subsequent tagged builds (e.g., https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/100032024) have all been canceled. Try re-running one.

I should also point out that you should be more selective on your deployments with conditional deployment so that you don't attempt to deploy 36 times. https://docs.travis-ci.com/user/deployment/releases#Conditional-releases

**Comment by linearregression** [comment] 2016-01-04 04:21
Rerun:
https://travis-ci.org/linearregression/travis_elixir_plt_generator/jobs/100028517

Log:
The command "MIX_ENV=test mix dialyzer.plt" exited with 0.
before_deploy.1
0.00s$ export RELEASE_PKG_FILE=$(ls plts/*.plt)
before_deploy.2
0.00s$ echo "Deploying plt file $RELEASE_PKG_FILE to GitHub releases"
Deploying plt file plts/otp-17.4-elixir-1.0.0.plt to GitHub releases
before_deploy.3
0.15s$ git fetch --tags
From https://github.com/linearregression/travis_elixir_plt_generator
 - [tag update]      otp-17.4-elixir-1.0.0 -> otp-17.4-elixir-1.0.0    <<<<-------- looks like tag is 
before_deploy.4
0.00s$ ls -R plts/*
plts/otp-17.4-elixir-1.0.0.plt   <<<<<<<--------- this is the file I want to be committed 
dpl.0
Fetching: dpl-1.8.11.gem (100%)
ERROR:
Preparing deploy
Logged in as edwardttril
Deploying to repo: linearregression/travis_elixir_plt_generator
Current tag is:   <<<<<<<<<<<------------------------------------- no tag
dpl.3
Deploying application
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/linearregression/travis_elixir_plt_generator/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: missing_field   <-----------------NO Tag
  field: tag_name
  resource: Release
  code: custom
  field: tag_name
  message: tag_name is not well-formed  <<<<<<<<<<<<<<<<<<<<<<<<<<<<--------
  resource: Release
  code: custom
  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by linearregression** [comment] 2016-01-04 04:30
Other jobs that showa green in deployment actually does nothing.
Repo:
https://github.com/linearregression/travis_elixir_plt_generator

No file under plts!!1
No tags every created and pushed to repo.

Log:
The command "MIX_ENV=test mix dialyzer.plt" exited with 0.
before_deploy.1
0.00s$ export RELEASE_PKG_FILE=$(ls plts/*.plt)
before_deploy.2
0.00s$ echo "Deploying plt file $RELEASE_PKG_FILE to GitHub releases"
Deploying plt file plts/otp-17.0-elixir-1.0.5.plt to GitHub releases
before_deploy.3
0.18s$ git fetch --tags
From https://github.com/linearregression/travis_elixir_plt_generator
 * [new tag]         otp-17.1-elixir-1.0.5 -> otp-17.1-elixir-1.0.5  <-<<<<<<< No such tags on git repo
 * [new tag]         otp-17.3-elixir-1.0.5 -> otp-17.3-elixir-1.0.5  
 * [new tag]         otp-17.4-elixir-1.0.5 -> otp-17.4-elixir-1.0.5
 * [new tag]         otp-18.0-elixir-1.0.5 -> otp-18.0-elixir-1.0.5
before_deploy.4
0.00s$ ls -R plts/*
plts/otp-17.0-elixir-1.0.5.plt
dpl.0
Fetching: dpl-1.8.11.gem (100%)
Successfully installed dpl-1.8.11
1 gem installed

**Comment by linearregression** [comment] 2016-01-04 04:36
Build link:
https://travis-ci.org/linearregression/travis_elixir_plt_generator/jobs/100046034
Error:
Skipping a deployment with the releases provider because this branch is not permitted

app: xmerl
plt_file: plts/otp-17.3-elixir-1.0.1.plt
The command "MIX_ENV=test mix dialyzer.plt" exited with 0.
Skipping a deployment with the releases provider because this branch is not permitted

**Comment by BanzaiMan** [comment] 2016-01-12 06:50
I think I found a problem with your `.travis.yml`.

https://github.com/linearregression/travis_elixir_plt_generator/blob/bb144637e57930b0b06f6fea2d78bafae2ee866d/.travis.yml#L103

`all_branches` is not in the right place; it should be under `deploy.on`:

```yaml
deploy:
  provider: releases
  api_key:
    secure: KEY
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    repo: linearregression/travis_elixir_plt_generator
    all_branches: true
```

As is, the only condition is `repo`, which means that the branch names to be deployed will default to `master` (which does not work well for Releases). See item 2 in https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A.

**Closed** 2017-06-08 05:09 UTC

**Comment by vovtz** [comment] 2019-08-06 14:39
> […] See item 2 in https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A.

https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
