### ISSUE TITLE
Trusty upgrade: Python 2.7 (pip) build dependency install failure with generic language Travis setting

### ISSUE THREAD

**Issue by chrissimpkins** [travis-ci/travis-ci#8378] opened 2017-09-08 16:31 UTC
#### Problem

Received the following exception and warning with Python 2.7 (as default Linux install, not otherwise specified in .travis.yml build matrices) builds on default Linux platform with language specified in travis.yml file as `generic` beginning yesterday:

> OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/commandlines-0.4.1.dist-info' 
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.

This fails pip installs with non-zero exit code and ends tests.

#### Workaround

The testing was not against a specific version of Python (not important for these tests) and this was resolved with conversion of travis.yml settings to `language: python` and explicit inclusion of `python: "3.6"` in the build matrices for our testing on Linux builds with `pip3` (not `pip`) test dependency installs.

#### Files

Example error build job: https://travis-ci.org/source-foundry/Hack/jobs/273130180
Associated .travis.yml settings file for fail: https://github.com/source-foundry/Hack/blob/dev-hints/.travis.yml

Example workaround build job: https://travis-ci.org/source-foundry/Hack/jobs/273320550
Associated .travis.yml settings file for pass: https://github.com/source-foundry/Hack/blob/dev-travis-ci-python-v/.travis.yml

cc: #8315 

#### Summary of other issue reports with similar problems in this thread:

- `Could not find a version that satisfies the requirement Zenfilter (from versions: 0.1a0)` on attempt to execute ```sudo -H `which python3` -m pip install Zenfilter``` in https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328211257.  Workaround is to add `group: deprecated-2017Q3`
- SWIG's builds also fail with the same error message when running `pip install pip8` in https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328442029.  Workarounds include:  use of `group: deprecated-2017Q3` and use of `pip install --user` for pip installs (see https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328484987)
- New python packages fail to build (a new package is built when a new library is added in requirements.txt) in https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328618239

**Comment by seankarson** [comment] 2017-09-08 18:31
This is happening to us as well. We added `group: deprecated-2017Q3` to `.travis.yml` to keep our builds working for the time being. Perhaps the issue is related to the `pyenv` upgrade in the latest Trusty build?

**Comment by BanzaiMan** [comment] 2017-09-08 20:19
Our pyenv installation went from 1.0.6 to 1.1.3. Here's the diff: https://github.com/pyenv/pyenv/compare/v1.0.6...v1.1.3

Not a whole lot of changes jump at me. It seems `pyenv shell` is the only thing that went through substantial change in this span. Others are mostly keeping python-build up to date with new releases. Maybe I'm missing something obvious.

**Comment by shlomif** [comment] 2017-09-08 20:53
I am getting a similar error here - https://travis-ci.org/shlomif/fc-solve/builds/273425597 . Please look into fixing it. The `group:...` workaround seems to be helping.

**Comment by chrissimpkins** [comment] 2017-09-08 21:17
Seems to be a permission error with an attempt to create a new directory for the pip install on our issue in the OP.  

Occurs at this line of the build: https://travis-ci.org/source-foundry/Hack/jobs/273130180#L530

and raises a Python OSError.  

Summarizing the issues in other posts in this thread:

- `Could not find a version that satisfies the requirement Zenfilter (from versions: 0.1a0)` on attempt to execute ```sudo -H `which python3` -m pip install Zenfilter``` in https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328211257.  Solved with `group: deprecated-2017Q3`
- @seankarson Sean, can you include a link to the repository / Travis build that you are referencing above so that we can determine the link between these issues?

**Comment by wsfulton** [comment] 2017-09-11 07:29
SWIG's builds also fail with the same error message when running:
```shell
pip install pep8
```
Example failure: https://travis-ci.org/swig/swig/jobs/273885227. We use `language: cpp`. The `group: deprecated-2017Q3` workaround is working for us for now. What does Travis recommened as the correct way to use pip?

**Comment by bogdanap** [comment] 2017-09-11 10:10
With the new image updates we've cleanup up some things around our Python environment setup.
This means that `pip install` will work as before inside a virtualenv (which only gets activated when using `language:python`).
Since this is not the case here,  I'd suggest using `pip install --user`.

**Comment by wsfulton** [comment] 2017-09-11 18:11
Thanks @bogdanap, that seems to do the job. If there is any chance of fixing it in the image for `language: cpp` it would be much appreciated? I ask as we get pull requests from folk who have branched from a while ago which means the pull requests will break as they won't have this change which I will need to commit to the repo. Out of our 70 builds, 18 of them break due to this change which could make assessing pull requests quite hard as we would need to do 18 different manual builds.

**Comment by jong-eatsa** [comment] 2017-09-11 18:32
Also breaking our build here. New python packages fail to build (a new package is built when a new library is added in `requirements.txt`).

I see the following strange error related to pyenv in the Travis log:
```
INFO: artifact_get: no artifact 'python-d1290f.tgz' found
  File "/opt/pyenv/shims/pip", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
The command "./build.sh install" exited with 1.
```

**Comment by BanzaiMan** [comment] 2017-09-11 18:54
@jong-eatsa Please include a build log URL. What are you doing in `./build.sh`?

**Comment by jong-eatsa** [comment] 2017-09-11 19:05
@BanzaiMan 

[Build URL](https://travis-ci.com/Keenwawa/rotelle#L748)

Relevant `build.sh` (custom bash script) contents:
```
...
python_artifact="python-$(md5sum requirements.txt | cut -c-6).tgz"
...
if artifact_get $python_artifact; then
  artifact_extract $target $python_artifact
else
  # install newer pip for use below
  py_pip pip
  export PATH=$target/python/bin:$PATH
  py_pip --no-cache-dir -r requirements.txt
  artifact_create $target python $python_artifact
fi
```

`artifact_create` is a custom bash function that creates an artifact (pip-packaged Python) and uploads to S3 to Travis can pull and build in later stages.

**Comment by BanzaiMan** [comment] 2017-09-11 19:12
@jong-eatsa Sorry, but the log nor the snippet does not tell the whole story.

```
  File "/opt/pyenv/shims/pip", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
```

does not look like a bash error message. So something else is trying to interpret this file and giving you this error message.

If you'd like to discuss this in private, please email support@travis-ci.com. Thanks.

**Comment by wsfulton** [comment] 2017-09-12 06:45
@bogdanap was thinking about this more, we'll manage fine if you can't get the image working as it was before.

**Comment by bogdanap** [comment] 2017-11-28 09:14
Closing this, as the failure is expected - as mentioned in [this comment](https://github.com/travis-ci/travis-ci/issues/8378#issuecomment-328484987). 

If you're still experiencing problems, please open a separate issue.

**Closed by bogdanap** 2017-11-28 09:14 UTC
Labels: 2017-Q3-trusty-env-update, python
