### ISSUE TITLE
ENH: Create new build (number) on restart

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#7725] opened 2017-05-08 00:45 UTC
When restarting a build, it would be really nice for a new build number to be allocated for the job. The current system where the same build number is used when restarting results in old failed builds' logs being lost. Sometimes these logs are useful for debugging active issues with the Travis CI team. In other cases these are useful for keeping tabs on sporadic failures in a project. Depending on how autocancellation is implemented this could also fix a potential bug and/or simplify the existing code.

Sorry if this already exists as an issue, tried combing through the issue tracker, but was unable to find such an issue open or closed.

**Comment by BanzaiMan** [comment] 2017-05-08 11:55
I'm closing this as a duplicate of #2993.

**Closed by BanzaiMan** 2017-05-08 11:55 UTC

**Comment by jakirkham** [comment] 2017-05-08 13:30
Thanks @BanzaiMan. Sorry for the dup.

**Comment by BanzaiMan** [comment] 2017-05-08 13:42
No worries! Issues searching can be challenging sometimes.
