### ISSUE TITLE
APT whitelist request for libxerces-c-dev

### ISSUE THREAD

**Issue by kuba1** [travis-ci/travis-ci#4451] opened 2015-07-19 07:47 UTC
FreeCAD dependency http://www.freecadweb.org/wiki/?title=CompileOnUnix#Debian_and_Ubuntu

**Comment by Supporting** [comment] 2015-07-21 12:25
Duplicate of #4308

**Comment by BanzaiMan** [comment] 2015-07-22 23:22
Indeed, it is.

**Closed by BanzaiMan** 2015-07-22 23:22 UTC
Labels: apt-whitelist-check-run
