### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by colt05** [travis-ci/travis-ci#5173] opened 2015-11-28 00:48 UTC
Hi. I have been getting "RuntimeError: Validation Failed" on a Koding VM when I try to set up releases for Git. I have done this once successfully, but I left some fields blank and messed it up. Is there a way to revert these changes? Thanks.
Error:
```
from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/tools/github.rb:221:in `login'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/tools/github.rb:49:in `each_token'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/tools/github.rb:36:in `with_token'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/setup/service.rb:52:in `configure'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/setup/releases.rb:11:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/setup.rb:54:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
https://guides.github.com/features/mastering-markdown/
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by BanzaiMan** [comment] 2015-12-03 03:59
Could you try removing `~/.travis` and try again?

**Comment by colt05** [comment] 2015-12-04 21:25
I installed Travis on a new VM with "sudo gem install travis" but when it was installing I got 
Log:
Building native extensions.  This could take a while...
ERROR:  Error installing travis:
        ERROR: Failed to build gem native extension.
 
        /usr/bin/ruby1.9.1 extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... no
creating extconf.h
creating Makefile
 
make
sh: 1: make: not found
----------
Should I upload /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c/gem_make.out?

**Comment by BanzaiMan** [comment] 2015-12-04 21:32
So, do you still have a problem?

**Comment by colt05** [comment] 2015-12-04 21:41
Yes.

**Comment by colt05** [comment] 2015-12-04 21:42
LOG:
xxx: ~/travis-test $ sudo travis setup releases -r xxx/xxx 
Username: xxx
Password for xxx: ***
Validation Failed
for a full error report, run travis report --org
xxx: ~/xxx $

**Comment by BanzaiMan** [comment] 2015-12-04 22:18
Could you try it without `sudo` when you run `travis setup`?

**Comment by colt05** [comment] 2015-12-05 11:31
No, for some reason Koding has a problem with running commands without sudo.
LOG:
/var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:365:in `initialize': Permission denied - /home/xxx/.travis/err
or.log (Errno::EACCES)
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:365:in `open'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:365:in `save_file'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:282:in `store_error'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:214:in `rescue in execute'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:191:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

**Comment by BanzaiMan** [comment] 2015-12-14 23:14
`/home/xxx/.travis/error.log` is owned by `root` from the previous attempt to run it with `sudo`.

**Comment by colt05** [comment] 2015-12-19 00:58
Ok, I am (yet again) terminating and making a new VM.
I ran `sudo gem install travis` and it returned make command not found so I ran `sudo apt-get install make` and then installed Travis again. Sometimes it said 
`unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/ffi/library.rb, skipping` and then ran `sudo travis.` Travis said shell completion was not installed, so I allowed it to install. I cloned my travis-test repo to my VM, then ran `sudo travis init --force` there. I should not have done that, so I removed the folder, cloned the repo again and ran `sudo travis setup releases -r colt05/travis-test` and got validation failed again.

**Comment by avilleret** [comment] 2016-01-20 18:08
I also get the same error after upgrading travis to 1.8.2 on Ubuntu 15.10

**Comment by avilleret** [comment] 2016-01-20 18:09
here is my log : https://gist.github.com/avilleret/a47d3db561f4c5d3caa0

**Comment by colt05** [comment] 2016-01-20 23:34
well i guess this issue is dead ;(

**Comment by avilleret** [comment] 2016-01-21 11:16
why are you closing this issue since it's not fixed ?

**Comment by colt05** [comment] 2016-01-21 11:59
because i'm not using travis anymore

**Closed** 2016-01-21 11:59 UTC

**Comment by colt05** [comment] 2016-01-21 12:00
also this issue is probably dead

**Comment by erikdw** [comment] 2016-06-16 07:08
Leaving a cookie crumb for future readers of this issue:  based on the OP's description it seems the issue is the same as I was facing and [found a solution for here](https://github.com/travis-ci/travis.rb/issues/199#issuecomment-226404303):  if you need to regenerate the token for a project, you need to first delete the existing token on GitHub for said project.

Of course, the travis gem should probably be updated to have a more specific error, and ideally the ability to delete & replace the existing token.
