### ISSUE TITLE
Android Espresso tests

### ISSUE THREAD

**Issue by kotya341** [travis-ci/travis-ci#6402] opened 2016-08-02 15:33 UTC
I am trying to run espresso test in the travis 
launch emulator first and execute my flavor tests with gradle command `connectedDevDebugAndroidTest`
however all my tests that interact with UI fails passes only package check test 
and getting error message 
"_Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrongWaited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong_"

[my travis yml looks like this ](https://gist.github.com/kotya341/a618f720127806ef30a688ae4c2f7e11)

**Comment by BanzaiMan** [comment] 2016-08-02 16:14
Looks like a duplicate of #6340.

**Closed by BanzaiMan** 2016-08-02 16:14 UTC
