### ISSUE TITLE
Did anything happen to $TERM recently?

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#6852] opened 2016-11-11 01:03 UTC
Pre-last build from 31 of October [was successful](https://travis-ci.org/nazar-pc/CleverStyle-Framework/builds/171919244), but last build from just now have [failed](https://travis-ci.org/nazar-pc/CleverStyle-Framework/builds/174950666) with following in output:
> tput: No value for $TERM and no -T specified

There was [no changes related](https://github.com/nazar-pc/CleverStyle-Framework/compare/43f0f6b321e5...e06f04405479) to that test and tests run fine in my local environment, so this is 100% change on Travis CI side.

So I'm curious, did you just removed or emptied `$TERM` environment variable recently? Didn't find anything like that in your blog and in existing issues.

**Comment by BanzaiMan** [comment] 2016-11-11 03:59
Sorry about the issue. This was a regression due to the way we handle certain subset of remote communications.

This was been addressed by https://github.com/travis-ci/travis-build/pull/883. If you haven't done so, please try restarting the failing jobs.

I'm closing this now, but do let us know if you see continued problems.

**Closed by BanzaiMan** 2016-11-11 03:59 UTC
