### ISSUE TITLE
Build Failure: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by numberoverzero** [travis-ci/travis-ci#7430] opened 2017-03-06 00:46 UTC
My docs build has been consistently failing on a cert issue, here's [the latest failing build](https://travis-ci.org/numberoverzero/bloop/jobs/208034830#L209).

This is failing to load the [intersphinx inventory](https://pythonhosted.org/blinker/objects.inv) for a library called blinker, hosted on https://pythonhosted.org.  The remaining intersphinx inventories load successfully from the following domains:

* http://boto3.readthedocs.io/en/latest/objects.inv
* https://delorean.readthedocs.io/en/latest/objects.inv
* https://arrow.readthedocs.io/en/latest/objects.inv

I've verified this succeeds locally, and so does the ReadTheDocs build.  I can't link to the exact line, but it's [this build](http://readthedocs.org/projects/bloop/builds/5108577/) and expand the sixth fold (right after `cat conf.py`).  I copied those initial lines below:

```
Running Sphinx v1.4.8
making output directory...
loading translations [en]... done
loading intersphinx inventory from https://docs.python.org/3.6/objects.inv...
loading intersphinx inventory from https://pillow.readthedocs.io/en/3.4.x/objects.inv...
loading intersphinx inventory from https://delorean.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://arrow.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://pythonhosted.org/blinker/objects.inv...
loading intersphinx inventory from http://boto3.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 15 source files that are out of date
```

From my local machine, I see the following valid SSL Certificate for the [inventory url](https://pythonhosted.org/blinker/objects.inv) with serial number `00:8B:09:E6:3A:90:74:B7:B0:9E:61:2F:1D:C1:EB:9A:16`.

**Comment by BanzaiMan** [comment] 2017-03-06 01:56
I think this is a duplicate of #4757.

```sh-session
$ curl -IL -1 https://pythonhosted.org/blinker/objects.inv
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

The host is not accepting TLS connexions from a Precise image because it requires TLS v1.2. Please use Trusty.

**Closed by BanzaiMan** 2017-03-06 01:56 UTC

**Comment by numberoverzero** [comment] 2017-03-06 02:03
Thank you very much! :+1:
