### ISSUE TITLE
OSX Mono support

### ISSUE THREAD

**Issue by jbob182** [travis-ci/travis-ci#4520] opened 2015-07-22 00:56 UTC
@joshua-anderson @akoeplinger @nterry

When performing mono builds on osx, ubuntu installation commands are used:

```
Installing Mono
sudo: apt-key: command not found
The command "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" failed and exited with 1 during .
Your build has been stopped.
```

My travis.yml can be found here: https://github.com/FOGProject/fog-client/blob/mono/.travis.yml

**Comment by Joshua-Anderson** [comment] 2015-07-22 00:59
OS X is not currently supported at the moment. OS X support is planned, but I've been busy lately and haven't had time to add it.

**Comment by Joshua-Anderson** [comment] 2015-07-22 01:00
dupe of #3546

**Closed** 2015-07-22 10:44 UTC
