### ISSUE TITLE
sudo:required ignored

### ISSUE THREAD

**Issue by splitice** [travis-ci/travis-ci#6344] opened 2016-07-21 12:47 UTC
sudo: required is being ignored.

See build: https://travis-ci.org/splitice/IPTables.Net/builds/146366614

https://github.com/splitice/IPTables.Net/blob/master/.travis.yml#L8

**Comment by BanzaiMan** [comment] 2016-07-21 13:31
Thanks for the report, and sorry for the issue. This is a duplicate of #6334.

**Closed by BanzaiMan** 2016-07-21 13:31 UTC
