### ISSUE TITLE
Add Support for .NET Core 2.1

### ISSUE THREAD

**Issue by BillChirico** [travis-ci/travis-ci#9686] opened 2018-05-31 03:45 UTC
Hello,

Could you please add support for .NET Core 2.1?

My build is currently failing due to the following error:

`2.1 is either an invalid version of dotnet or unsupported on this operating system.`

2.1 is a valid version number.

**Comment by BanzaiMan** [comment] 2018-05-31 11:38
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by BanzaiMan** [comment] 2018-05-31 12:46
I'm closing this as a duplicate of #9684.

**Closed by BanzaiMan** 2018-05-31 12:46 UTC
