### ISSUE TITLE
java misconfigured and/or unavailable

### ISSUE THREAD

**Issue by izhangzhihao** [travis-ci/travis-ci#6928] opened 2016-11-24 03:20 UTC
```
jdk:
  - oraclejdk8
```

what's wrong with [my config]( https://github.com/izhangzhihao/SSMSeedProject/blob/e308f92aba6b7f977703b8168d5f4457e3bd8afc/.travis.yml)?

**Comment by BanzaiMan** [comment] 2016-11-27 14:20
This looks like a bug. For some reason, we are removing the symlink, but not reloading `jdk_switcher`. The function still thinks that the `$JAVA_HOME` is the symlink that's removed, and the switch fails.

Could you try setting `$JAVA_HOME` to `/usr/lib/jvm/java-8-oracle` until we fix this?

**Comment by BanzaiMan** [comment] 2016-11-27 14:22
I think this is the relevant commit: https://github.com/travis-ci/travis-build/commit/59a3db66d697ca44cb60154cc8ab9c1f83d648d6

**Comment by maximgubar** [comment] 2016-11-27 16:25
I have similar issue, in my travis config I use php language and sudo trusty dist.
but I install solr on top of it, and some time ago it started to erroring:

> The currently defined JAVA_HOME (/usr/lib/jvm/java-8-oracle-amd64) refers
> to a location where Java could not be found.  Aborting.
> Either fix the JAVA_HOME variable or remove it from the
> environment so that the system PATH will be searched.

I've tried to solved it as you recommended, defining JAVA_HOME directly, but it still keeps show me the message with old home path.

I have private repo, and payed travis plan, is it the right communication channel, or I should contact you in different channel ?

**Comment by BanzaiMan** [comment] 2016-11-27 17:35
@maximgubar Sorry about the continued problem. Please email us at support@travis-ci.com.

**Comment by izhangzhihao** [comment] 2016-11-28 02:41
@BanzaiMan thx! I try "export JAVA_HOME=/usr/lib/jvm/java-8-oracle" and it fixed!

**Comment by BanzaiMan** [comment] 2016-11-28 03:30
I'm reopening this, since the bug still exists and it should be fixed.

**Comment by fyockm** [comment] 2016-12-01 16:14
Just started seeing the same issue this morning when trying to start `elasticsearch` on trusty:
```sh
$ sudo service elasticsearch start
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME
```

**Comment by MariadeAnton** [comment] 2016-12-01 16:53
Since the promotion of the edge image to stable, see: https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/

This issue can now happen for the default configuration.

```yml
sudo: required
dist: trusty
```

Known workarounds are: 

- adding `group: deprecated` to the _.travis.yml_ file to use the previous stable image
- add the following lines

```yaml
before_install:
  - source /opt/jdk_switcher/jdk_switcher.sh
  - jdk_switcher use oraclejdk8
```

Thank you, we'll post an update when it's resolved!

**Comment by meatballhat** [comment] 2016-12-01 16:58
I have a runtime patch on the way via https://github.com/travis-ci/travis-build/pull/902

**Comment by fyockm** [comment] 2016-12-01 17:03
@MariadeAnton thanks for the workarounds. I tried setting `JAVA_HOME` in `before_install`. However, that's too late in the build cycle for me because `elasticsearch` is installed and started via "APT Sources", which occurs prior to `before_install`.

@meatballhat what's the timeframe for the patch? Will I need to set `group: edge`, or will it be pushed directly to `stable`?

**Comment by meatballhat** [comment] 2016-12-01 17:04
@fyockm that patch will apply to all jobs, and should be live in under ~20m

**Comment by meatballhat** [comment] 2016-12-01 17:27
@fyockm travis-ci/travis-build#902 is live now, btw :+1:  Thanks for your patience! :heart:

**Comment by scasagrande-d2l** [comment] 2016-12-01 17:36
@meatballhat I now see that `source /opt/jdk_switcher/jdk_switcher.sh` is being run, but I'm still getting `java is not present on your PATH.`. Is it now expected that I specify which JRE to use for xvfb?

**Comment by meatballhat** [comment] 2016-12-01 17:37
@scasagrande-d2l the exact behavior depends on multiple variables.  Do you have a job URL to which you can link?

**Comment by scasagrande-d2l** [comment] 2016-12-01 17:39
@meatballhat https://travis-ci.com/Brightspace/bulk-exemptions/jobs/58169122

**Comment by fyockm** [comment] 2016-12-01 17:39
@meatballhat I am also still getting the same error. 

here's my job url: https://travis-ci.com/BessemerAlliance/voyant-models/jobs/58184176

**Comment by meatballhat** [comment] 2016-12-01 17:42
@fyockm @scasagrande-d2l It looks like `update-java-alternatives` is not successfully switching the system java.  Still looking...

**Comment by scasagrande-d2l** [comment] 2016-12-01 20:25
Any news @meatballhat ?

**Comment by kiulkiel** [comment] 2016-12-01 20:50
sorry all.  so has all my computer issues been you guys? Just not sure if I blamed the wrong person or if it was her. If you have any idea what I'm talking about it would help (ha me asking for help) to know what has been happening. Or do I just sound crazy?

**Comment by david-wilson-mcn** [comment] 2016-12-01 20:58
the workaround of putting "group: deprecated" in the .travis.yml has been working for me.

**Comment by meatballhat** [comment] 2016-12-01 21:38
@scasagrande-d2l Sorry for delay.  Spinning multiple plates.  No update yet for `group: stable`.  Please use `group: deprecated` to get un-blocked :+1: :heart:

**Comment by sideshowbarker** [comment] 2016-12-02 01:18
I’ve worked around this by just calling `java` with the full path:

    /usr/lib/jvm/java-8-oracle/jre/bin/java

I’m sure that won’t work for all cases but it worked in mine at least.

**Comment by mp-jgoetzinger** [comment] 2016-12-02 10:34
@scasagrande-d2l you have to add

```
jdk:
  - oraclejdk8
```

to tell the switcher to switch ;). this fixed it for me.

**Comment by scasagrande-d2l** [comment] 2016-12-02 14:55
@mp-jgoetzinger Our problem is that we have several repos across multiple teams, so I'd rather not try to wrangle that mess.

**Comment by meatballhat** [comment] 2016-12-02 15:47
[This update](https://docs.travis-ci.com/user/build-environment-updates/2016-12-02/) included [a fix](https://github.com/travis-ci/travis-cookbooks/blob/cda21856562ac12a5d865a48e428c0eace270a6f/cookbooks/travis_java/recipes/default.rb#L32-L45) that [tested correctly](https://github.com/travis-ci/packer-templates/blob/10d938a0befbf17921ba3a6e7a7fb185ea2234fa/cookbooks/lib/features/jdk_spec.rb) during image mastering, yet I have confirmation that non-jvm language jobs do not have `java` in `$PATH`.  I'm still working on a permanent fix.  In the meantime, please continue to either stay on `group: deprecated` or explicitly invoke `jdk_switcher use default` (or whatever jdk you choose).  Thanks for your patience and understanding, everyone :heart:

**Comment by meatballhat** [comment] 2016-12-02 16:02
Latest cookbook changes [look promising](https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/180745869), fwiw.

**Comment by meatballhat** [comment] 2016-12-02 17:16
I've hit a snag with one of the stacks that performs a [deferred installation of `lein`](https://travis-ci.org/travis-infrastructure/packer-build/jobs/180754365#L3054-L3157).  Working on it...

**Comment by meatballhat** [comment] 2016-12-03 02:43
There are some fresh Trusty stack images available that I'm very much hoping address the remaining issues.  I'd appreciate input from anyone here who's able to run their jobs with:

``` yaml
group: edge
```

**Comment by xhochy** [comment] 2016-12-03 09:15
Can confirm that the `edge` images fixes the problem, build with `edge`: https://travis-ci.org/xhochy/arrow/jobs/180921629 

(Failing build with `stable`: https://travis-ci.org/xhochy/arrow/jobs/180629177 )

**Comment by andrerom** [comment] 2016-12-05 13:38
Can confirm getting solr to run on a `language: php` job is broken as of last week.
Besides `group:`  and `script:  jdk_switcher use oraclejdk8`workarounds, when is eta for fix in stable?

**Comment by scasagrande-d2l** [comment] 2016-12-05 14:49
Can also confirm that `group: edge` is working for me now :D

**Comment by meatballhat** [comment] 2016-12-05 16:40
@andrerom I'm preparing a release for `group: stable` right now, which will likely go out tomorrow morning US/Eastern 👍

**Comment by fyockm** [comment] 2016-12-05 18:10
I'll jump on the bandwagon - `group: edge` fixes it for my use case as well. Thanks @meatballhat!

**Comment by meatballhat** [comment] 2016-12-05 18:14
This is the `group: stable` push that will include the fix currently available via `group: edge`: https://docs.travis-ci.com/user/build-environment-updates/2016-12-06/

Please note that we currently do not have support for multiple group assignment, which means that once the above update goes live, anyone using `group: edge` will likely experience a *regression*, as the image most recently tagged `group: edge` will be from The Past ⌛️

**Comment by meatballhat** [comment] 2016-12-06 15:16
This build env update is complete https://docs.travis-ci.com/user/build-environment-updates/2016-12-06/.  Please holler if you are still experiencing issues on sudo-enabled Trusty that you believe are related to this issue 💖 .

**Closed by meatballhat** 2016-12-06 15:16 UTC
Labels: bug, build environment, trusty

**Comment by scasagrande-d2l** [comment] 2016-12-06 16:01
Everything is back to normal for us now :) many thanks @meatballhat, I owe you one :D
