### ISSUE TITLE
create separate caches depending on env variables

### ISSUE THREAD

**Issue by pohly** [travis-ci/travis-ci#5127] opened 2015-11-17 11:10 UTC
In http://docs.travis-ci.com/user/caching/#How-does-the-caching-work%3F it is said that:
    There is one cache per branch and language version/compiler version/JDK version/Gemfile location/etc.

However, in my experience a project whose .travis.yml file creates a build matrix (well, row) just with different env variables seems to get just one cache. At least the web UI only shows me one cache for the branch, and different builds after creating the cache seem to start with exactly the same cache content.

But the content of the cache depends on these env variables, so the cache will be useless in those cases where it was created for a different configuration.

Example (untested, my real case is more complex):
```
env:
  - FOO=foo BAR=bar
  - FOO=bar BAR=foo
cache:
  directories:
  - ~/some-custom-cache
script:
  - mkdir -p ~/some-custom-cache
  - echo "$FOO $BAR" >~/some-custom-cache/cachefile
```

**Comment by BanzaiMan** [comment] 2015-11-17 12:42
Thanks for opening this ticket, but this is a duplicate of #4393.

**Closed by BanzaiMan** 2015-11-17 12:42 UTC

**Comment by pohly** [comment] 2015-11-17 12:53
Thanks for pointing out the existing ticket. I had done some searching, but obviously not enough.
