### ISSUE TITLE
travis-ci.org build failure due to missing lxc-docker package

### ISSUE THREAD

**Issue by josiahcarlson** [travis-ci/travis-ci#5157] opened 2015-11-24 04:22 UTC
The last several builds at travis-ci.org for one of my open-source projects have died due to an error during the build process.

The link to the main build page is: https://travis-ci.org/josiahcarlson/rom/builds
Builds 65-68 have died due to the following:

```
$ sudo apt-get update
...
$ sudo apt-get install lxc-docker
Reading package lists... Done
Building dependency tree       
Reading state information... Done

Package lxc-docker is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

From here, the build fails and none of my code has been executed.

**Comment by BanzaiMan** [comment] 2016-01-23 04:04
Looks like we removed the apt source for docker (present here: https://travis-ci.org/josiahcarlson/rom/jobs/80033045#L48) from the image. I am not sure if this was by design, but you can re-add it (https://docs.docker.com/engine/installation/ubuntulinux/) before running `sudo apt-get update` and `sudo apt-get install`.

Closing this for now.

**Closed by BanzaiMan** 2016-01-23 04:04 UTC
Labels: build environment, team blue, travis-cookbooks

**Comment by josiahcarlson** [comment] 2016-01-23 06:46
All right, managed to fix my build. Thanks for pointing me in the right direction :)
