### ISSUE TITLE
New pip (version 8.0+) fails with tox and Python 3.2

### ISSUE THREAD

**Issue by bittner** [travis-ci/travis-ci#5517] opened 2016-01-27 00:01 UTC
I'm trying to [build a Django app](https://travis-ci.org/jcassee/django-analytical/builds/105024396) with Python 3.2 through 3.5 using `tox`, but the build [fails for Python 3.2](https://travis-ci.org/jcassee/django-analytical/jobs/105024400) due to `pip` version 8.0.2 being installed:

(Note the *"UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here."* message below.)

``` python
Installing setuptools, pip, wheel...
  Complete output from command /home/travis/build/j...ango17/bin/python3.2 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  /home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 35, in <module>
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/utils/ui.py", line 15, in <module>
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv.py", line 2278, in <module>
    main()
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv.py", line 703, in main
    symlink=options.symlink)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv.py", line 904, in create_environment
    download=download,
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv.py", line 861, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/virtualenv.py", line 781, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/travis/build/j...ango17/bin/python3.2 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /opt/python/3.2.5/bin/python3.2
```

`pip` version 8, released a few days ago, introduced a few [backward-incompatible changes](https://pip.pypa.io/en/stable/news/#release-notes), most noteworthy dropping Python 3.2 support. I've tried [installing `pip` version 7 explicitly](https://github.com/bittner/django-analytical/commit/b51a683aa9f1ab20af2858342bd658f34684b2e3), but `tox` seems to use the `pip` version installed in the site-packages, which is causing the trouble.

Maybe you could pin `pip` to the latest 7 version on the VM image? Or is there any (other) way I can make sure `pip` version 7 is used?

**Comment by BanzaiMan** [comment] 2016-01-27 00:38
A duplicate of #5485. Please review your dependency requirements. In particular, see https://github.com/travis-ci/travis-ci/issues/5485#issuecomment-173837358.

**Closed by BanzaiMan** 2016-01-27 00:38 UTC

**Comment by BanzaiMan** [comment] 2016-01-27 02:22
Perhaps it is worth pointing out that the source of the incompatibility is virtaulenv 14.0+, not pip 8+.
