### ISSUE TITLE
Provide IPv6 Connectivity in containerized environments

### ISSUE THREAD

**Issue by else** [travis-ci/travis-ci#3627] opened 2015-04-09 08:00 UTC
We have a on_success hook that does deployments via IPv6 if the build was successful. We would be very happy to use the containerized environments as they are much faster, but there is no IPv6 connectivity available and thus we cannot deploy. In the virtualized infrastructure this is no problem.

I know that EC2 does not have IPv6 :-1:, but it's not so much about having a global IPv6 address but instead just about being able to talk IPv6 would already be enough. Docker added support for IPv6 with v1.5.0.

Please provide IPv6 connectivity.

**Comment by BanzaiMan** [comment] 2015-04-14 03:04
This is a duplicate of #3302, I think.

**Comment by else** [comment] 2015-04-23 07:45
You're right, it's definitely related :), but #3302 was actually a request to list it as a limitation to the docs.

Hopefully you'll be able to add IPv6 connectivity to your container instances. Should be possible with a routable network, right? At least with Docker > v1.5.0

Cheers

**Comment by solarce** [comment] 2015-11-25 22:45
Unfortunately, the major public cloud providers do not provide any supported methods for having internal IPv6 connectivity nor are there any real options for in-bound IPv6 external connectivity in a way that is usable for Travis's build environments, so we're limited by what is supported on the providers which give us the best economies of scale and overall feature sets we need. So at this time we are unable to make any commitments to supporting IPv6 in our containerized builds.

**Closed by solarce** 2015-11-25 22:45 UTC
Labels: containers, networking issue
