### ISSUE TITLE
fatal: destination path 'xxxx' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by valentyp** [travis-ci/travis-ci#6545] opened 2016-08-31 15:36 UTC
I used this command twice, but after the second time I have received this message. How to fix it ???

**Comment by BanzaiMan** [comment] 2016-08-31 17:30
Duplicate of #2715.

**Closed by BanzaiMan** 2016-08-31 17:30 UTC

**Comment by osunkoyadavid** [comment] 2020-05-30 12:41
Getting the same error

**Comment by osunkoyadavid** [comment] 2020-05-30 12:42
when i run: git clone -b beta https://github.com/flutter/flutter.git, it shows the error below
fatal: destination path 'flutter' already exists and is not an empty directory.
