### ISSUE TITLE
Document support for python 3.6 stable

### ISSUE THREAD

**Issue by JordonPhillips** [travis-ci/travis-ci#7085] opened 2016-12-28 16:44 UTC
Python 3.6 was released on December 23rd. At the moment "3.6-dev" is supported, but not plain "3.6" (or at the very least, it's not documented [here](https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against)).

EDIT: It appears that it is supported, just not documented.

**Comment by BanzaiMan** [comment] 2016-12-29 15:06
Some variation of https://github.com/travis-ci/docs-travis-ci-com/pull/803 will be merged.

**Comment by samuelcolvin** [comment] 2016-12-31 13:27
I don't think 3.6.0 is supported.

`3.6-dev` is correctly pointing to `3.6.0+`, see [this](https://travis-ci.org/samuelcolvin/aiohttp-devtools/jobs/187890721) build. AFAIK that's correct.

What needs adding is `3.6` which points to the released version `3.6.0`.

**Comment by BanzaiMan** [comment] 2016-12-31 14:36
@samuelcolvin Have you tried it? https://travis-ci.org/BanzaiMan/travis_production_test/builds/187898790#L118

**Comment by BanzaiMan** [comment] 2016-12-31 14:38
Similarly for `3.6.0` https://travis-ci.org/BanzaiMan/travis_production_test/builds/187901109#L118

**Comment by samuelcolvin** [comment] 2017-01-05 12:40
Ok, my mistake, looks like all the needed versions of python are available and as @JordonPhillips said earlier the problem is just that `3.6` isn't included in docs.

**Comment by BanzaiMan** [comment] 2017-01-12 14:37
I've merged https://github.com/travis-ci/docs-travis-ci-com/pull/903. Closing this.

**Closed by BanzaiMan** 2017-01-12 14:37 UTC
Labels: docs
