### ISSUE TITLE
Containers & C11 builds

### ISSUE THREAD

**Issue by absalomedia** [travis-ci/travis-ci#5293] opened 2015-12-15 05:02 UTC
According to [this](https://docs.travis-ci.com/user/apt/) Travis documentation apt can be used to deploy GCC 4.8 inside Precise containers.

However all my tests are failing as the GCC version keeps on reporting 4.6.3 as seen [here](https://travis-ci.org/absalomedia/tensile/builds/96904995)  

Is there any chance of a Trusty based container image or will I have to roll back to using sudo (which is much slower with what I'm doing) ?

**Comment by BanzaiMan** [comment] 2015-12-15 05:14
You need to invoke `gcc-4.8`.

**Comment by BanzaiMan** [comment] 2015-12-15 05:15
You may also want to set `$CXX` and `$CC` accordingly.

**Comment by absalomedia** [comment] 2015-12-15 22:34
I've been trying to do that but the Precise container isn't honouring my env variables, even after invoking gcc-4.8:

I set it & then the container resets it back to 4.6.3 - taken from lines 357 to 361 of this [latest build attempt](https://travis-ci.org/absalomedia/tensile/builds/97095678)
```
$ export CC=gcc-4.8
$ export CXX=g++-4.8
$ export CXX=g++
$ export CC=gcc
```

**Comment by pranith** [comment] 2015-12-16 18:18
Exporting CXX and CC is not really an option if you want your build to be tested by multiple compilers like clang and gcc. These env variables should ideally be set during the build setup.

**Comment by BanzaiMan** [comment] 2015-12-18 05:11
I think, for the build script, `$CC` and `$CXX` should be overridden if and only if it is not set in `.travis.yml`; i.e.,

```sh-session
$ export CXX=${CXX:-g++}
$ export CC=${CC:-gcc}
```

(This is in contrast with other built-in env vars such as `$TRAVIS_RUBY_VERSION`, which should not be overridden by the env statements in `.travis.yml` _when the build starts_.)

Note that you can always override these environment variables in the middle of a build.

**Comment by BanzaiMan** [comment] 2015-12-20 06:16
Well, actually, this should work:


```yaml:
compiler:
  - gcc-4.8
  - clang-3.4
```

**Comment by BanzaiMan** [comment] 2015-12-20 18:59
I'm closing this as a duplicate of https://github.com/travis-ci/travis-ci/issues/3871.

**Closed by BanzaiMan** 2015-12-20 18:59 UTC
