### ISSUE TITLE
Encrypted environment variables: only encrypt value

### ISSUE THREAD

**Issue by OliverJAsh** [travis-ci/travis-ci#7613] opened 2017-04-14 09:31 UTC
I only want to encrypt the value of my environment variables. By making the key readable, it's clear in my `.travis.yml` which env vars are being provided.

Is this possible? I tried:

``` yml
env:
  global:
    - KEY:
      secure: "encrypted value"
```

… to no avail.

**Comment by BanzaiMan** [comment] 2017-04-14 12:46
It is not possible to encrypt just the value, as `env` key defines `NAME=VALUE` pair.

I should also add that

```yaml
env: # I'll assume that you forgot a colon here
  global:
    - KEY:
      secure: "encrypted value"
```

is valid, but defines a data structure that is not suitable for use.

**Comment by BanzaiMan** [comment] 2017-04-15 14:37
Can we close this?

**Comment by OliverJAsh** [comment] 2017-04-15 14:57
Could we consider adding this, or do you think it's not something you'd support?

Thanks!

**Comment by BanzaiMan** [comment] 2017-04-15 17:40
I'd have to say it's unlikely. The effort to support is not trivial, and the environment variable will be written to the logs.

**Comment by BanzaiMan** [comment] 2017-04-24 01:10
I'm closing this for now.

**Closed by BanzaiMan** 2017-04-24 01:10 UTC

**Comment by jaraco** [comment] 2019-08-21 08:34
I'd like to see support for this. GitLab supports this model, and forcing the user to encrypt the key and value together leads to awkward workflows, such as the one that led to the issue linked above. I'm guessing that 90% of the time (or more), the sensitive information is in the value and not the key, so writing the name to the logs would not be a problem.

**Comment by jaraco** [comment] 2019-08-21 08:39
This is essentially a dupe of #1446.
