### ISSUE TITLE
build continues after nvm install failure

### ISSUE THREAD

**Issue by rlgomes** [travis-ci/travis-ci#5501] opened 2016-01-22 19:28 UTC
This certainly isn't a desired behavior since when this happens there's no guarantee the underlying tests + build would ever work with the default `0.10.x` build available. It would be much better to see the whole run fail right there and then on the `nvm install`.

Here's one of our runs that show the problem:

https://travis-ci.org/juttle/juttle-viz/jobs/104132384#L83

**Comment by BanzaiMan** [comment] 2016-01-22 20:20
Closing as a duplicate of #5333.

**Closed by BanzaiMan** 2016-01-22 20:20 UTC
