### ISSUE TITLE
Folding can cause logs to be displayed out of (temporal) order

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#5971] opened 2016-04-29 19:04 UTC
# Setup

Consider this [`.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/5974478964aa717834cd4e1d379fadb968ae78e3/.travis.yml):

``` yaml
before_deploy:
  - echo "before_deploy"
  - date
deploy:
  - provider: script
    script: bash ./echo.sh first
    on:
      branch: default
  - provider: script
    script: bash ./echo.sh second
    on:
      branch: default

after_deploy:
  - sleep 5
  - echo "after_deploy"
  - date
```

`echo.sh` basically `echo`es the first arg (https://github.com/BanzaiMan/travis_production_test/blob/5974478964aa717834cd4e1d379fadb968ae78e3/echo.sh#L4)
# Expected behavior

In the order of execution, you should see:
1. `before_deploy`
2. `Deploy! first`
3. (sleep)
4. `after_deploy`
5. `before_deploy`
6. `Deploy! second`
7. (sleep)
8. `after_deploy`

The [raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/126470981/log.txt) shows that these events do happen in the expected order. (See also the `date` outputs.)
# Actual behavior

However, the [build log](https://travis-ci.org/BanzaiMan/travis_production_test/builds/126470980) shows:
1. `before_deploy`
2. `before_deploy`
3. `Deploy! first`
4. `Deploy! second`
5. (sleep)
6. (sleep)
7. `after_deploy`
8. `after_deploy`

**Comment by BanzaiMan** [comment] 2016-04-29 19:05
I suspect that travis-web is collecting certain "fold" outputs together and display them in bunches.

**Comment by BanzaiMan** [comment] 2016-04-29 19:06
cc @backspace @clekstro @rkh

**Comment by backspace** [comment] 2016-05-02 07:53
Scandalous! Thanks for the diligent documentation.

**Comment by BanzaiMan** [comment] 2016-09-21 16:45
I see what I think might be a different manifestation of this issue in [`travis-rubies`](https://github.com/travis-ci/travis-rubies). The build result of https://travis-ci.org/travis-ci/travis-rubies/jobs/161668130 appears [on the line 306](https://travis-ci.org/travis-ci/travis-rubies/jobs/161668130#L306), but that rolled up into `check.2`.

I think the issue here is that folds with identical names are gathered into one, regardless of their places in the logs.

**Comment by backspace** [comment] 2016-10-12 19:40
Hey, @BanzaiMan, this looks fixed [here](https://bd-double-fold.test-deployments.travis-ci.org/travis-ci/travis-rubies/jobs/161668130), do you agree?

**Comment by BanzaiMan** [comment] 2016-10-12 20:05
@backspace No, I don't. `travis-rubies` does its own folding (https://github.com/travis-ci/travis-rubies/blob/build/build.sh#L38-L44). A good test would be to try the config above.

**Comment by backspace** [comment] 2016-10-12 20:15
Hmm, well that log I linked to had two `travis_fold:start:check.2` lines, which previously rendered improperly. I think it renders properly on this deployment?

You can see the log for the `travis_production_test` job [here](https://bd-double-fold.test-deployments.travis-ci.org/BanzaiMan/travis_production_test/builds/126470980), it at least renders differently than on the production site, though it doesn’t exactly match up with what you listed for expected behaviour.

**Comment by BanzaiMan** [comment] 2016-10-12 20:39
@backspace I think it does. :-) https://bd-double-fold.test-deployments.travis-ci.org/BanzaiMan/travis_production_test/builds/126470980#L162.

**Comment by backspace** [comment] 2016-10-12 20:46
Okay! Great! Well I am somewhat paranoid that my changes will have unintentional consequences, since the logging code is mysterious to me and has no automated tests. I’ve asked in the Teal issue for others to look at logs on that deployment to see if anything appears to be amiss.

**Comment by backspace** [comment] 2016-10-31 08:05
This is deployed now. Closing! 💞🎉

**Closed by backspace** 2016-10-31 08:05 UTC
Labels: team teal, travis-web
