### ISSUE TITLE
Repo has no public key

### ISSUE THREAD

**Issue by parrish** [travis-ci/travis-ci#3647] opened 2015-04-10 19:46 UTC
Hi, I'm stumped on this one and IRC is probably just in Friday-mode right now.

I enabled travis on a repo today and tried to encrypt an environment variable:

```
$ travis encrypt foo --debug
** Loading "/Users/michael/.travis/config.yml"
** Loading gh
** GET "config"
**   took 0.082 seconds
** GitHub API: HEAD /repos/parrish/Congestion
**   took 0.27 seconds
** GET "repos/parrish/Congestion"
**   took 0.085 seconds
** GET "repos/4459414/key"
**   took 0.085 seconds
resource not found ({"file":"not found"})
```

After figuring out what those requests were up to, it appears that it just doesn't have a public key.

Other repositories are working fine.  I've tried logging out/back in, deleting ~/.travis and reinstalling the gem, and disabling/re-enabling the repository -- no luck so far.

Any suggestions?

**Comment by cyberjoac** [comment] 2015-04-14 11:42
+1

**Comment by spmiller** [comment] 2015-04-14 14:10
+1
Stuck on this with a brand new repo.

**Comment by parrish** [comment] 2015-04-14 14:31
I can also add that this occurs with other repos as well as in a fresh setup in a virtual environment.

**Comment by bill-auger** [comment] 2015-04-14 16:33
this is also issue 237 on the travis.rb repo being investigated atm
https://github.com/travis-ci/travis.rb/issues/237

**Comment by BanzaiMan** [comment] 2015-04-14 18:28
Seems that this is happening with increasing frequency.

The Key is supposed to have been created when the Repository object is created. We are looking into it.

**Comment by BanzaiMan** [comment] 2015-04-14 19:50
I've created a new repository, sync the user data, and the new repository doesn't have a key. So it seems the issue is reproducible. I don't know yet where the problem lies (or where to look for the error log).

**Comment by BanzaiMan** [comment] 2015-04-14 21:24
OK. I tracked this down to the recent changes in the way we sync user data.

**Comment by BanzaiMan** [comment] 2015-04-15 03:03
This ended up in http://www.traviscistatus.com/incidents/vcdh0dz4kjxb

We have generated keys for those repositories which were missing the keys going back to 2015-04-05.

If the issue was caused by the missing encryption key, then it should be fixed now. Please try again.

If your repository is _still_ missing the key (either because it was created before 2015-04-05, or somehow we missed generating it), let us know. We'll deal with it on a case-by-case basis.

If you see the key *and* `travis encrypt` still fails, please open a separate issue.

Thank you for your patience on this issue.

**Closed by BanzaiMan** 2015-04-15 03:03 UTC
Labels: bug

**Comment by BanzaiMan** [comment] 2015-04-15 03:09
Also, do keep in mind that `-r OWNER/REPO` is often a valid flag to pass to `travis encrypt` (and others) if your command fails.

**Comment by parrish** [comment] 2015-04-15 14:15
I can confirm that everything is working as expected again.  Thanks for your help on this!

**Comment by BanzaiMan** [comment] 2015-04-15 15:08
@parrish Thanks for the confirmation, and thanks for reporting the issue.

**Comment by bill-auger** [comment] 2015-04-15 16:42
working for me also - ty

**Comment by bill-auger** [comment] 2015-04-15 16:46
working for me also - ty

i believe this also closes travis.rb issue 237 https://github.com/travis-ci/travis.rb/issues/237

**Comment by BanzaiMan** [comment] 2015-04-15 17:13
@bill-auger It might not be the same issue; the repository reported in https://github.com/travis-ci/travis.rb/issues/237 is a few months old, and I believe it had the key all along (and it still does).

**Comment by nilsnolde** [comment] 2018-11-07 09:56
Huh, seems this didn't happen in a long time. 

Yet, https://api.travis-ci.org/repos/GIScience/openelevationservice/key responds with `{"file":"not found"}`.

Can you please have a look?
