### ISSUE TITLE
Docker tools updated, AWS CLI not updated?

### ISSUE THREAD

**Issue by jamesrgrinter** [travis-ci/travis-ci#8901] opened 2017-12-13 10:45 UTC
If you previously had
`eval $(aws ecr get-login --region us-west-2)`

or similar, somewhere in some build steps, you now need to use:

`eval $(aws ecr get-login --region us-west-2 --no-include-email)`

as the updated Docker CLI no longer accepts the -e that this version of `aws ecr get-login` generates by default as part of the docker login command. `--no-include-email` tells get-login to omit the -e option.

**Comment by BanzaiMan** [comment] 2017-12-13 20:26
Are we providing `aws` on our images? https://travis-ci.org/BanzaiMan/travis_production_test/builds/316076070#L471

How are you getting it?

**Comment by cotsog** [comment] 2017-12-18 15:28
Thanks for the tip, @jamesrgrinter!

This issue is indeed caused by the new Docker version installed on our newest image. As stated [in the AWS CLI documentation](http://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html#options):

> You must specify --no-include-email if you're using docker version 17.06 or later.

Sorry for the inconvenience.

We have documented it here: https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-352458433

For completeness, to you have a link to the build where this was failing before? We would like to add a sample of the error message you were getting so customers can identify the issue more easily.

Thanks again for your help!

**Comment by BanzaiMan** [comment] 2017-12-18 15:49
I see it now. Please update your configuration as @cotsog suggested. There is nothing for us to do here, so I'm closing this.

**Closed by BanzaiMan** 2017-12-18 15:49 UTC
Labels: 2017-Q4-trusty-env-update

**Comment by jamesrgrinter** [comment] 2017-12-18 23:17
@cotsog Well, it looks like we explicitly run `pip install --user awscli` in the before install phase, so perhaps the version available via pip (awscli-1.14.9-py2.py3-none-any.whl) hasn’t caught up yet. (But I thought I’d got a later version on my own local system)

For reference, anyway, the two errors that you see are:
“unknown shorthand flag: 'e' in -e ... See 'docker login --help'.” from `eval $(aws ecr get-login)`
Followed by “no basic auth credentials”, from the `docker push` command.
