### ISSUE TITLE
[C/C++] Cannot use latest gcc (v6.1.2) for C++ 17

### ISSUE THREAD

**Issue by AraHaan** [travis-ci/travis-ci#7015] opened 2016-12-12 04:02 UTC
Here is a problem currently by default travis ships for people to use an out of date gcc v2.8.1 Allow someone to actually specify a version newer so they can use ``-std=c++17`` command line switch otherwise build fails making them have to do a little ``.travis.yml`` hack if they can to bypass this in a much more so ``unreadable`` way. Allow for a much more simpler configuration where setting that value to ``latest`` implies to use the latest version of gcc for that platform (currently v6.1.2 I think).

**Comment by BanzaiMan** [comment] 2016-12-13 14:46
I think you are asking for an overall better support for C/C++. As such, can this be closed as a duplicate of #6300?

**Closed** 2016-12-13 21:39 UTC
