### ISSUE TITLE
support node.is "lts" version, similar to "stable"

### ISSUE THREAD

**Issue by nfriedly** [travis-ci/travis-ci#4944] opened 2015-10-14 23:45 UTC
Now that node.is is doing Long Term Support releases in addition to the current stable version, it would be handy for package maintainers to be able to quickly test against both the current LTS and the current stable node.us without having to continually update their .travis.yml.

For the moment, "LTS" and "stable" would point to the same 4.2 release of node. However once 4.3 or 5.0 is released, they would diverge with "LTS" continuing to point to 4.2 for the next 18 months or so.

**Comment by BanzaiMan** [comment] 2015-10-19 14:23
We rely on [nvm](https://github.com/creationix/nvm) to resolve Node.js versions. This feature request is best suited for that project instead.

cc @ljharb

**Comment by ljharb** [comment] 2015-10-19 18:14
This is a duplicate of https://github.com/creationix/nvm/issues/870 - feel free to close it.

@nfriedly also note that a given LTS may indeed change minor versions. For now, you can just add `4.2` in your `.travis.yml`, or locally, `nvm alias argon 4.2` and use `argon`.

**Comment by BanzaiMan** [comment] 2015-10-19 19:02
@ljharb Thanks for the info!

**Closed by BanzaiMan** 2015-10-19 19:02 UTC
Labels: node.js

**Comment by nfriedly** [comment] 2015-10-19 20:52
Right, that makes sense. Thanks guys!

**Comment by Berkmann18** [comment] 2019-01-31 13:04
Not sure, if anything for that has been done but having this in `.travis.yml` doesn't get TravisCI to test on all LTS versions:
```yml
node_js:
  - 'lts/*'
```
Here's [an example](https://travis-ci.org/Berkmann18/TemplateJS/jobs/486907330).

**Comment by BanzaiMan** [comment] 2019-01-31 14:49
@Berkmann18 You are overriding that with the definition in `jobs.include`: https://github.com/Berkmann18/TemplateJS/blob/430ee38e1f9986246b9559240fba8e75748c677e/.travis.yml#L22

**Comment by Berkmann18** [comment] 2019-01-31 15:49
@BanzaiMan That's only for the `release` build stage which only happens on the master branch.

**Comment by Berkmann18** [comment] 2019-01-31 16:51
@BanzaiMan Same behaviour:
- [here on `dev`](https://travis-ci.org/Berkmann18/TemplateJS/builds/487024581) with [this config](https://travis-ci.org/Berkmann18/TemplateJS/jobs/487024583/config).
- [here on `master`](https://travis-ci.org/Berkmann18/TemplateJS/builds/487024625)
- [here on `dev`](https://travis-ci.org/Berkmann18/TemplateJS/builds/487029264) with some changes to the [config](https://travis-ci.org/Berkmann18/TemplateJS/jobs/487029265/config)

Dropping `jobs` isn't an option because of the depreciation of `travis-deploy-once` (due to the introduction of build stages).

**Comment by ljharb** [comment] 2019-01-31 16:58
That last one says it’s running on node 10, which is LTS.

**Comment by Berkmann18** [comment] 2019-01-31 16:59
@ljharb True, however, the `lts/*` implies it will target all the matching LTS versions which visibly isn't the case.

**Comment by ljharb** [comment] 2019-01-31 17:07
No, it only targets a single version - `lts/*` implies, just like in the shell, that it will select the first matching version - which in this case is the latest LTS. `lts` by itself won't work with nvm because that might have been a user-defined alias.

**Comment by Berkmann18** [comment] 2019-01-31 17:11
I wonder why the articles I've seen where people used that to target, say v4-6-8, got that to work (perhaps a regression since then?).
Oh well.

**Comment by ljharb** [comment] 2019-01-31 17:15
@Berkmann18 usually people use a matrix, and test on multiple node versions at once. Here's my typical config: https://github.com/ljharb/is-callable/blob/master/.travis.yml#L4-L18
