### ISSUE TITLE
Filter out secure tokens from the output stream

### ISSUE THREAD

**Issue by mhevery** [travis-ci/travis-ci#7452] opened 2017-03-10 21:47 UTC
It has happen to our project several times now that we have accidentally leaked our secure tokens through travis. We place the encrypted secure token into `.travis.yaml`. Travis then decrypts the token and places it in the environment variable. The token must be in a file so it is common practice to `echo $TOKEN >> somefile`. It is also common practice to echo every command to log for debugging reasons `set -e`. The result is that the token is leaked into a public log for all to see. 

While the above is our fault, it could be mitigated if travis would search for all tokens it has decrypted and automatically replace them with `XXXXXXX` in the log. This would make it that even if the token would get accidentally echoed, it would still not show up in logs. If travis detect the token it could also email the owner and let them know that they are leaking a token.

**Comment by BanzaiMan** [comment] 2017-03-10 21:50
I'm closing this as a duplicate of #1487.

**Closed by BanzaiMan** 2017-03-10 21:50 UTC
