### ISSUE TITLE
I can't login travis-ci.com?

### ISSUE THREAD

**Issue by ZAntony** [travis-ci/travis-ci#7621] opened 2017-04-17 11:32 UTC
My account can't log on to travis-ci.com and click on the landing, what reaction all have no, reload the page again, check the developer tools also did not see the mistakes

**Comment by ZAntony** [comment] 2017-04-17 11:38
Tested, it's not a browser, chrom, firefox, and mobile phones are tested

**Comment by BanzaiMan** [comment] 2017-04-17 11:44
Sorry about the issue. I'm closing this as a duplicate of #7612.

**Closed by BanzaiMan** 2017-04-17 11:44 UTC

**Comment by ZAntony** [comment] 2017-04-17 12:07
Navigated to https://travis-ci.com/
Navigated to https://api.travis-ci.com/auth/handshake?code=ce09d4209cae744a7bf2&state=N5xedYVgtYmc3S2i7MOuAw%3A%3A%3Ahttps%3A%2F%2Ftravis-ci.com%2F
Navigated to https://travis-ci.com/
trans-src.js:57 Uncaught TypeError: Cannot read property 'appendChild' of null
    at trans-src.js:57
    at trans-src.js:263
(anonymous) @ trans-src.js:57
(anonymous) @ trans-src.js:263
lookup.js:1 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at lookup.js:1
(anonymous) @ lookup.js:1
Navigated to https://travis-ci.com/

**Comment by ZAntony** [comment] 2017-04-17 12:07
this my error
