### ISSUE TITLE
Job log doesn't escape \n

### ISSUE THREAD

**Issue by lorenzocafaro** [travis-ci/travis-ci#7475] opened 2017-03-16 12:50 UTC
Hello,

I've noticed that if I'm running a build with:

```
script:
  - set -o errexit; for script in *.js; do printf "\n\nrunning $script\n"; node $script; done
```

The job log seems to interpret `\n` along with the output:

![example](https://cloud.githubusercontent.com/assets/25922870/23996856/5641085a-0a4f-11e7-84a8-5b3320d6327e.PNG)

I know it's a very edge case but I thought I'd let you know.

**Comment by BanzaiMan** [comment] 2017-03-16 15:30
I think this is a duplicate of #3379.

**Closed** 2017-03-21 18:33 UTC
