### ISSUE TITLE
Python 3.4 broken on xenial

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#10193] opened 2018-10-06 13:47 UTC
Fails with
```
$ source ~/virtualenv/python3.4/bin/activate
/home/travis/.travis/job_stages: line 104: /home/travis/virtualenv/python3.4/bin/activate: No such file or directory
```
https://api.travis-ci.org/v3/job/438001410/log.txt

**Comment by BanzaiMan** [comment] 2018-10-06 13:52
Duplicate of #10185.

**Closed by BanzaiMan** 2018-10-06 13:52 UTC
