### ISSUE TITLE
Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-ci#9460] opened 2018-04-09 07:19 UTC
...is due out this month, but 14.04 LTS is still the latest Ubuntu version Travis supports.

Given the discussion in #5821, this is probably similarly a ways off, but seemed at least worth opening an issue for. ❤️

**Comment by BanzaiMan** [comment] 2018-04-09 12:52
Hello. We have plans for 16.04 and 18.04 work, but no ETA at the moment. In the mean time, I'm closing this as a duplicate of #5821.

**Closed by BanzaiMan** 2018-04-09 12:52 UTC

**Comment by reidpr** [comment] 2018-12-11 16:47
This is not a duplicate, because #5821 was closed after addressing 16.04 only.

**Comment by allencloud** [comment] 2018-12-24 02:54
We need Ubuntu 18.04 LTS as well because of the newer version of linux kernel !!! ❤️

**Comment by smaslennikov** [comment] 2019-01-31 23:11
It's a little silly that the newest supported OS is nearly 3 years old - Ubuntu 16.04. I hate to be negative, but after banging my head against a wall of old library packages for several hours, silly is all this seems to be (to me).

**Comment by lukehinds** [comment] 2019-02-05 14:33
The lack of decent distribution coverage is really making me question my selection of travis. No fedora, no opensuse, just old versions of Ubuntu.

**Comment by lazystone** [comment] 2019-03-01 09:37
@BanzaiMan could you reopen this issue since it's NOT a duplicate of #5821

**Comment by BanzaiMan** [comment] 2019-03-01 13:18
Any update will be posted in https://travis-ci.community/t/ubuntu-18-04-1-lts-bionic-beaver/1270. Thanks.

**Comment by reidpr** [comment] 2019-06-17 18:44
@BanzaiMan there is literally nothing official from Travis in that thread, just people asking for updates.

**Comment by Atem18** [comment] 2019-06-24 15:52
I think a solution is to build your apps in a container, that way you don't care about the OS. And then since you have a container, you can now also deploy it in production :)

**Comment by reidpr** [comment] 2019-06-24 16:40
> I think a solution is to build your apps in a container

Not all apps work in a container.

> you can now also deploy it in production

Not all apps get deployed that way.
