### ISSUE TITLE
PHP 7.0.0RC[12] lacks pecl

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#4800] opened 2015-09-15 01:02 UTC
Just got failed build, turns out `7.0` in `.travis-ci` now results in building PHP 7.1-dev
So it is time to fix PHP7 on some RC or use 7.0 branch, otherwise I'm already gettting errors with memcached module: https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/80350723

**Comment by BanzaiMan** [comment] 2015-09-15 01:05
You can use '7.0RC1' in the meantime.

**Comment by nazar-pc** [comment] 2015-09-15 01:08
What do you mean by that?
I do not see in docs how to configure specific RC version of PHP, only stable releases.
From my config:
```
language: php
php:
  - 5.5
  - 5.6
  - 7.0
sudo: false
services:
  - memcached
```

**Comment by BanzaiMan** [comment] 2015-09-15 01:09
For the time being, `7` (and `7.0`) is an alias for `nightly`. This is an oversight on our part that should've been avoided. Until PHP 7 is pre-installed, it will work this way.

**Comment by BanzaiMan** [comment] 2015-09-15 01:09
7.0RC1 is undocumented.

**Comment by BanzaiMan** [comment] 2015-09-15 01:12
Actually, if a final 7.0.0 release appears in the near future, it is reasonable to install that version instead of `nightly`.

**Comment by nazar-pc** [comment] 2015-09-15 01:12
Unfortunately, 7.0RC1 doesn't work: https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/80352131

**Comment by BanzaiMan** [comment] 2015-09-15 01:13
Sorry. It is `7.0.0RC1`.

**Comment by nazar-pc** [comment] 2015-09-15 01:16
Well, no luck either...
> rbenv: pecl: command not found

> The `pecl' command exists in these PHP versions:
>   5.2
  5.2.17
  5.3
  5.3.29
  5.3.3
  5.4
  5.4.37
  5.5
  5.5.21
  5.5.9
  5.6
  5.6.5

https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/80352386

I'll wait for proper fix. And thanks for instant response.

**Comment by BanzaiMan** [comment] 2015-09-15 01:17
You have a different problem. https://travis-ci.org/nazar-pc/CleverStyle-CMS/jobs/80352386#L93 shows that it is choosing 7.0.0RC1 correctly.

**Comment by nazar-pc** [comment] 2015-09-15 01:19
Yes, that is another problem, PHP is fine, but no pecl

**Comment by BanzaiMan** [comment] 2015-09-15 01:39
That is curious. I confirmed that `pecl` is available for the nightly build, including the most current `7.1.0-dev`, but it is not available for 7.0.0RC1 or 7.0.0RC2. We use php-build (https://github.com/php-build/php-build/tree/master/share/php-build/definitions) to build these archives. It is not immediately clear to me why the executable should be missing.

**Comment by GrahamCampbell** [comment] 2015-09-17 12:55
> It is not immediately clear to me why the executable should be missing.

It's because you;re pulling in an old version of php-build. I sent a PR to upgrade it, but it's still not been accepted. :/

**Comment by BanzaiMan** [comment] 2015-09-28 19:16
@GrahamCampbell Has your PR been merged? If so, I can re-compile RC3 (I don't think RC1 and RC2 need to be, since RC3 is available).

**Comment by BanzaiMan** [comment] 2015-09-30 16:21
OK. I figured this out. It turns out that php-build by default configures the compilation with `--without-pear`. We edited this to `--with-pear` on the master branch builds, but not others. I have re-packaged all RC's (1, 2, and 3) as well as 7.0snapshot, so `pecl` should be available for all now.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/82962871

**Closed by BanzaiMan** 2015-09-30 16:21 UTC
Labels: php, travis-build

**Comment by ramsey** [comment] 2015-09-30 16:27
I re-ran the job and can confirm that your new builds have fixed this. Thanks!

**Comment by Spomky** [comment] 2015-12-07 10:25
Hi,

It seems to be broken again: https://travis-ci.org/Spomky-Labs/jose/jobs/95297154

I cannot use PECL extension using `7.0`.
And I am expecting to build tests on a stable PHP 7.0 release but I got:
> php --version
PHP 7.0.1-dev (cli) (built: Dec  6 2015 22:41:42) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3-dev, Copyright (c) 2002-2015, by Derick Rethans

**Comment by rexxars** [comment] 2015-12-07 11:20
+1 - 7 should be aliased to release, not dev version

**Comment by tedivm** [comment] 2015-12-08 06:41
Yup, still broken. My tests aren't working because pecl isn't installed on the 7.0 machines.

**Comment by BanzaiMan** [comment] 2015-12-08 08:35
The most recent regression is described in #5207. Please subscribe to that instead.
