### ISSUE TITLE
Change git clone URL scheme

### ISSUE THREAD

**Issue by disconsented** [travis-ci/travis-ci#4705] opened 2015-08-25 01:05 UTC
How do I change travis from using git://foo to https://foo for cloning?
[I want to do this to resolve this error](https://travis-ci.org/disconsented/ANSSRPG/builds/76815456#L288-L289)

**Comment by BanzaiMan** [comment] 2015-08-25 01:11
Currently it is configured on our servers. I recall an issue calling for the use of `https://` URL scheme instead of the current `git://`, but I cannot find it at the moment.

**Comment by joshk** [comment] 2015-08-25 11:06
@BanzaiMan can you add this to the sapphire backlog?

@disconsented until we are able to fix this, you could add a step in your `.travis.yml` which updates `.git/config` to use the correct url.

**Comment by disconsented** [comment] 2015-08-25 23:46
That sorted it! However I noticed that even with attempting to adjust it with before_install: ```- sed -i 's/git:/https:/g' .git/config``` it will still clone from git://

**Comment by BanzaiMan** [comment] 2015-08-26 00:26
@disconsented `git clone` happens before any of your customization steps run, so that is expected.

**Comment by disconsented** [comment] 2015-08-26 00:36
Ah, cheers anyways. Works like a charm

**Comment by vszakats** [comment] 2015-08-27 23:30
Duplicate of https://github.com/travis-ci/travis-ci/issues/4384

**Comment by vszakats** [comment] 2015-08-27 23:31
@BanzaiMan Maybe https://github.com/travis-ci/travis-ci/issues/4384?

**Comment by vszakats** [comment] 2015-08-27 23:39
Tried [this](https://github.com/disconsented/ANSSRPG/blob/9b7fd8eb9cbd312858116bbd6bc84a511236c294/.travis.yml#L16) suggested solution [here](https://github.com/vszakats/harbour-core/commit/fb4b3a596c2f972ccd3d268ea308922527f651a0), but this won't resolve the initial plaintext `gti://` protocol used in the clone operation:
https://travis-ci.org/vszakats/harbour-core/jobs/77603266#L66

**Comment by BanzaiMan** [comment] 2015-08-28 00:00
Indeed! I am closing this as a duplicate. Thank you, @vszakats.

**Closed by BanzaiMan** 2015-08-28 00:00 UTC
Labels: team-sapphire
