### ISSUE TITLE
Using the new command sdkmanager to build Android

### ISSUE THREAD

**Issue by davigonz** [travis-ci/travis-ci#8596] opened 2017-10-17 11:31 UTC
Hi! I've read some of the issues here where you're suggesting to use the new command `sdkmanager` when building in Android. I have a question about it:

Do I have to continue defining android components in the next way?

   ![screen shot 2017-10-17 at 13 22 21](https://user-images.githubusercontent.com/15261363/31662334-3acf62f4-b33e-11e7-91fe-475cd24764c9.png)

Or shall I use only `sdkmanager` to install the Android SDK tools instead?

   ![screen shot 2017-10-17 at 13 23 55](https://user-images.githubusercontent.com/15261363/31662401-7fcc54de-b33e-11e7-9ebe-0fb67909ae3f.png)

If I do not set build-tools in android components, a warning is shown in the build logs but seems to be properly installed with the `sdkmanager` command.

Apart from that, when installing "platform-tools" and "tools" with `sdkmanager`(even with verbose flag enabled) the version that is being installed doesn't appear while with "build-tools" does, any idea? I suppose it gets the last versions, I will check with the command `sdk-manager --list` after installation commands, just in case.

**Comment by iriberri** [comment] 2017-10-18 12:00
Related: https://github.com/travis-ci/packer-templates/issues/483

(I'll revisit this issue again to try help as soon as possible, but posting that link for the time being 💛)

**Comment by BanzaiMan** [comment] 2017-10-23 02:13
I'm closing this as a duplicate of #8360.

**Closed by BanzaiMan** 2017-10-23 02:13 UTC
Labels: android
