### ISSUE TITLE
Please show "PHP 7.0" as label for the 7.0 tests, just like "5.4", "5.5", "5.6" and "7.1"

### ISSUE THREAD

**Issue by derickr** [travis-ci/travis-ci#7257] opened 2017-02-02 14:36 UTC
![labels](http://derickrethans.nl/files/dump/labels.png)

The flag in the ``.travis.yml`` file is already ``7.0`` too:

https://github.com/mongodb/mongo-php-driver/blob/master/.travis.yml#L2

**Comment by BanzaiMan** [comment] 2017-02-02 14:50
Closing as a duplicate of #7125.

**Closed by BanzaiMan** 2017-02-02 14:50 UTC
