### ISSUE TITLE
Android build-tools-23.0.3 not found

### ISSUE THREAD

**Issue by dmfrey** [travis-ci/travis-ci#5951] opened 2016-04-25 16:46 UTC
please update repository to be able to use android build-tools-23.0.3

**Comment by BanzaiMan** [comment] 2016-04-25 16:51
Duplicate of #5648.

**Comment by BanzaiMan** [comment] 2016-04-25 16:52
Also see #5891.

**Closed by BanzaiMan** 2016-04-25 16:51 UTC

**Comment by dmfrey** [comment] 2016-04-25 17:41
Mine is configured as they specified in those other issues/links and it is still failing

    android:
      components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository

**Comment by dmfrey** [comment] 2016-04-25 18:11
please disregard, found an errant 23.0.2 in one of the gradle files.

**Comment by BanzaiMan** [comment] 2016-04-25 18:16
@dmfrey Happy to hear that you were able to get it working!

**Comment by dmfrey** [comment] 2016-04-25 18:19
@BanzaiMan well, not quite just yet, at the end a message channel is throwing a ConnectionResetByPeer exception, and using a generic ipv6 address with all 0's. Not sure where that is coming from because it is not in my code. Still digging. But at least it got by the other build-tool-23.0.3 not found

**Comment by BanzaiMan** [comment] 2016-04-25 18:35
We do not support IPv6.

**Comment by dmfrey** [comment] 2016-04-25 18:41
i am not sure where this came from and it only occurred once. It is not
something that is in my code as I am not doing anything specific with ipv6
either.
