### ISSUE TITLE
Trusty 2017/Q3 pyenv fails for python 3.6

### ISSUE THREAD

**Issue by MarcoFalke** [travis-ci/travis-ci#8391] opened 2017-09-10 03:03 UTC
Travis yaml config: https://travis-ci.org/MarcoFalke/bitcoin/jobs/273753292/config

The pyenv advertises python3 (versions 3.4 and 3.6), though the call to python 3.6 fails:

```
pyenv: python3.6: command not found
The `python3.6' command exists in these Python versions:
  3.6
  3.6.1

**Comment by BanzaiMan** [comment] 2017-09-10 13:45
Looks like a duplicate of #8363.

**Closed by BanzaiMan** 2017-09-10 13:45 UTC
