### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by bannsec** [travis-ci/travis-ci#9005] opened 2018-01-04 02:04 UTC
I'm getting this error a lot when running tests. It seems to have nothing to do with my tests themselves, but rather travis seems to be failing to install from pypi:

```
[0K$ pip install -U pip setuptools && pip install .[dev]
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f41f2f7c320>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f41f2f7c3c8>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
Requirement already up-to-date: pip in /home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages
Collecting setuptools
  Downloading setuptools-38.2.5-py2.py3-none-any.whl (489kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.7
    Uninstalling setuptools-36.2.7:
      Successfully uninstalled setuptools-36.2.7
Successfully installed setuptools-38.2.5
Processing /home/travis/build/bannsec/pyCoW
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytest-runner/: [Errno 99] Cannot assign requested address -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-kgi5ok_1-build/setup.py", line 32, in <module>
        'dev': dev_tools,
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/setuptools/dist.py", line 455, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pkg_resources/__init__.py", line 866, in resolve
        replace_conflicting=replace_conflicting
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1146, in best_match
        return self.obtain(req, installer)
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1158, in obtain
        return installer(requirement)
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-kgi5ok_1-build/
```

**Comment by stefanbethke** [comment] 2018-01-04 11:03
See also #9000.

**Comment by BanzaiMan** [comment] 2018-01-05 14:44
Closing as a duplicate of #9000.

**Closed by BanzaiMan** 2018-01-05 14:44 UTC
