### ISSUE TITLE
Correct way to obtain build URL

### ISSUE THREAD

**Issue by csandanov** [travis-ci/travis-ci#9348] opened 2018-03-16 08:27 UTC
What is the correct way to obtain the build URL?

Having `TRAVIS_BUILD_ID` it's possible to obtain a build URL, i.e. `https://travis-ci.org/repo/name/builds/$TRAVIS_BUILD_ID`. However, I don't know whether the build comes from .org or .com version. 

Will .org build URL redirect to .com? If not, is there a way to differentiate .org build from .com via environment variables?

**Comment by BanzaiMan** [comment] 2018-03-16 12:31
I'm closing this as a duplicate of #8935.

**Closed by BanzaiMan** 2018-03-16 12:31 UTC
