### ISSUE TITLE
Travis failing on julia nightly

### ISSUE THREAD

**Issue by sbromberger** [travis-ci/travis-ci#5750] opened 2016-03-06 06:04 UTC
cc @tkelman  @ninjin and @staticfloat

See, e.g., https://travis-ci.org/JuliaGraphs/LightGraphs.jl/jobs/114003206 - this is happening for all CI efforts with LightGraphs. Something we need to change in our yml?

**Comment by BanzaiMan** [comment] 2016-03-06 06:44
Duplicate of #5740.

**Closed by BanzaiMan** 2016-03-06 06:44 UTC
