### ISSUE TITLE
Pip Python Path Missing on OSX

### ISSUE THREAD

**Issue by uxcn** [travis-ci/travis-ci#5030] opened 2015-10-30 01:40 UTC
The path for pip packages doesn't seem to be set on OSX.  As an example, I'm installing `cram` in this [build](https://travis-ci.org/uxcn/yafd/jobs/88047102), but the script isn't found in the path when it tries to run tests.

This isn't a major issue, and it has a fairly easy work-around, but I suspect it might also cause problems for others.

**Comment by BanzaiMan** [comment] 2015-10-31 11:43
You are using `language: c`, so you are responsible for setting up your build environment. I understand that we do not yet support Python on OS X, but this issue is expected (I doubt that this works on Linux).

**Comment by uxcn** [comment] 2015-10-31 17:07
The environment is correct in `os: linux`.  The following is also an easy work around for `os: osx`.

    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      export PATH=${PATH}:/Users/travis/Library/Python/2.7/bin
    fi

The project is `language: c`, but I use python packages for things like functional tests.  I would guess other projects do the same which was the reason I thought I'd let someone know.

**Comment by gappleto97** [comment] 2015-12-07 17:27
If you don't support python on OSX, why does it say you do in your documentation?

> Every worker has at least one version of Ruby, Java and Python to accommodate projects that may need one of those runtimes during the build.

That's from https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by BanzaiMan** [comment] 2015-12-08 02:11
OS X images do not have Python pre-installed. On Linux images, at least some version of Python is pre-installed, because it is a requirement (for `apt`-related things, I believe).

I am inclined to close this as a duplicate of #2312.

**Comment by uxcn** [comment] 2015-12-08 03:02
Do you have any documentation posted for people trying to use python with `os: osx`?  It looks like brew might be the simplest option.

e.g.

    brew update
    brew install python3

Feel free to close as a duplicate.

**Comment by BanzaiMan** [comment] 2015-12-08 03:10
#2312 is the current status of "Python support" on OS X.

**Closed by BanzaiMan** 2015-12-08 03:10 UTC

**Comment by uxcn** [comment] 2015-12-08 03:19
It might help people to have a workaround documented somewhere in the meantime.  Using `brew` seems pretty simple.
