### ISSUE TITLE
Allow custom badge text

### ISSUE THREAD

**Issue by patrikhuber** [travis-ci/travis-ci#5421] opened 2016-01-08 00:28 UTC
Currently, if you use travis for Linux/Mac CI, and AppVeyor for Windows CI, there will be two badges next to each other, both saying "build passing" (or failing or whatever).

AppVeyor allows to specify a custom text for pending, failing and passing: http://www.appveyor.com/blog/2014/11/26/customizing-text-of-build-status-badges

For example, the following would create an image saying "Windows: build passing", instead of just "build passing" (and the same for pending/failing):
`https://ci.appveyor.com/blahblah/repo/master?svg=true&passingText=Windows%3A%20build%20passing&failingText=Windows%3A%20build%20failing&pendingText=Windows%3A%20build%20pending`

Travis's badge always just shows "build passing", which is quite a bit confusing when next to another badge.

Could you consider adding a similar feature to that of AppVeyor, to be able to change the badge text?

This issue is a little bit related to #5037, though I'd prefer a custom text to a logo, because a logo doesn't mean that much to most users who are not familiar with travis (and most users aren't).

**Comment by BanzaiMan** [comment] 2016-01-08 13:04
Thanks for opening the issue. I'm going to close this as a duplicate of #5037. We will discuss changes to the badge there (though there is no immediate plan at this time).

**Closed by BanzaiMan** 2016-01-08 13:04 UTC
