### ISSUE TITLE
stage build not stopped after script run failed

### ISSUE THREAD

**Issue by AlloVince** [travis-ci/travis-ci#10248] opened 2018-10-17 05:57 UTC
Hi guys

Here is my config:

``` yml
language: python
python: 3.6
node_js: 10
install:
- pip install -r requirements.txt
jobs:
  include:
    - stage: test
      if: branch = master AND tag IS blank
      script:
        - pytest tests/
        - npm install
...more
```

Also here is build log:
https://travis-ci.org/bmqb/EvaScrapy/builds/442510777

The first script `pytest tests/` already failed, but follow scripts still started, please check whether it is work correct, thanks

**Comment by BanzaiMan** [comment] 2018-10-17 06:01
Thanks, but this is a duplicate of #1066. Closing.

**Closed by BanzaiMan** 2018-10-17 06:01 UTC

**Comment by worc** [comment] 2018-11-15 00:34
instead of making AlloVince wade through hundreds of comments, maybe it would help to summarize. this behavior is working "as designed," yes it's a bug, no travis won't do anything about it. the workaround seems to be using either an undocumented feature or chaining your scripts using `&&`

**Comment by AlloVince** [comment] 2018-11-15 01:50
@worc thanks for your kindly reply
