### ISSUE TITLE
Notifications are being reported per job instead of per build

### ISSUE THREAD

**Issue by ntwb** [travis-ci/travis-ci#4928] opened 2015-10-13 10:03 UTC
Travis builds: https://travis-ci.org/aaronjorbin/develop.wordpress
Travis config: https://core.trac.wordpress.org/browser/trunk/.travis.yml

```
notifications:
45	  slack:
46	    rooms:
47	      secure: WuMCpfgrm0GIdPbYzsGOsakZ5x7QIbEBwD+CPHVXGKbL3ZbqQ+BVcDRnMiwzxjgf1vzg2de0taXCSMGKBxsWce23NZkOnmwPdIB8XOnwDV7T7zylgYD5S7p3gI6gV0l8Y3/gROdXFZap6viC1qRr4E79ow53RKk7E3WyOo7TWqo=
48	    on_start: never
49	    on_failure: always
50	    on_success: change
```

The below shows multiple notifications for builds 4615 and 4616, there should only be one notification for each, not contained in the screenshot is the same scenario for builds 4607, 4608, 4609, 4610, 4611, 4612, 4613, and 4614.
<img width="793" alt="screen shot 2015-10-13 at 8 58 27 pm" src="https://cloud.githubusercontent.com/assets/1016458/10451651/36b0e902-71ed-11e5-8489-d86a83ab4492.png">

The above is also happening for the BuddyPress tests here https://travis-ci.org/buddypress/BuddyPress/builds as such the issue is not isolated to a single Travis CI repo.

**Comment by joshk** [comment] 2015-10-13 15:10
Hi @ntwb 

Thanks for reporting this.

Can you try removing the `fast_finish` section for now. This is a know bug which we are working on fixing.

Thanks a bundle

Josh

**Comment by ntwb** [comment] 2015-10-14 00:54
@joshk Thanks, the workaround appears to be working fine per the above repos :smirk:

**Comment by Croydon** [comment] 2015-12-20 15:45
Related to #4988.

**Comment by ezyang** [comment] 2016-04-08 03:02
Dupe is #1696.

**Comment by BanzaiMan** [comment] 2016-05-20 20:53
Closing as a duplicate of #1696.

**Closed by BanzaiMan** 2016-05-20 20:53 UTC
