### ISSUE TITLE
MySQL TO_BASE64 function does not exist

### ISSUE THREAD

**Issue by odan** [travis-ci/travis-ci#4088] opened 2015-06-15 17:11 UTC
My test:

$result = $db->compress('test', true);
$resultFromDb = $db->queryValue("SELECT TO_BASE64(COMPRESS('test')) AS result;", 'result');
$this->assertEquals($resultFromDb, $result);

The error message:
1) Molengo\Test\DbMySqlTest::testCompress
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION molengo_test.TO_BASE64 does not exist

Url: https://travis-ci.org/odan/molengo/jobs/66899081

Question:
Why is the SQL statement: "SELECT TO_BASE64(COMPRESS('test')) AS result;" not working with Travis-CI?

http://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_to-base64

Kind regards
odan

**Comment by roidrage** [comment] 2015-06-15 17:58
Thanks for submitting this issue!

The trouble is that we're still running MySQL 5.5, but TO_BASE64 was added in 5.6.

**Comment by BanzaiMan** [comment] 2015-06-15 20:21
I'm closing this as a duplicate of #1986. This SO answer shows you how to fake it with 5.5: http://stackoverflow.com/a/29912414

**Closed by BanzaiMan** 2015-06-15 20:21 UTC
