### ISSUE TITLE
OSX is not even procressing or booting at all.

### ISSUE THREAD

**Issue by AraHaan** [travis-ci/travis-ci#7341] opened 2017-02-18 01:15 UTC
This is what it looks like: http://puu.sh/u81LN/46eb94f269.png

For some reason it just sits there unless I explicitly cancel building all day today.

**Comment by BanzaiMan** [comment] 2017-02-19 20:40
Is this still a problem? If so, please indicate a build log URL.

**Comment by srazi** [comment] 2017-02-21 21:35
Maybe at some hours (e.g. right now 9:30 UTC) there are a lots of requests for osx build?

**Comment by srazi** [comment] 2017-02-23 12:23
It seems things getting worse. Today I have to wait at least one hour before starting each OSX build.

**Comment by nemequ** [comment] 2017-02-25 04:11
According to https://www.traviscistatus.com/ the backlog for OS X builds currently fluctuates between ~ 400 and 1200 jobs, depending on the time of day.  It seems like the free version of Travis just doesn't have enough OS X workers (128 currently) to meet demand anymore.

**Comment by nemequ** [comment] 2017-03-01 23:34
The queue dropped over the weekend, but it's back up to over 1400 now.

I have one project with 3 OS X builds which took about 2 hours for the OS X jobs to start (when the queue was smaller than it is now), but once they did all three ran at basically the same time, which got me thinking…

Assuming just throwing more resources at the problem (i.e., adding more OS X workers) isn't an option, how about changing the queue to only allow a single slot for each project (or maybe user) at a time?  If the project's position in the queue was reset on each build it would let projects with fewer OS X builds get results quicker, and probably encourage people to use fewer OS X configurations.

The current approach effectively encourages projects to add a bunch of OS X builds, bloating the queue for everyone else with no drawbacks for their own projects…

**Comment by BanzaiMan** [comment] 2017-03-02 04:39
You can limit the number of jobs running on a repository. https://docs.travis-ci.com/user/customizing-the-build#Limiting-Concurrent-Builds

**Comment by nemequ** [comment] 2017-03-02 05:21
How does that help?  The problem is that there are other projects in the queue.  What I'm suggesting is that Travis change the *global* queue to more evenly distribute time on the OS X workers across projects.

Let's consider an example:

 1. There is a backlog on Travis' OS X builders
 1. Project A, which has 5 OS X builds, triggers a build
 2. Project B, which has 1 OS X build, triggers a build

IIUC, right now Project B's won't start until all 5 of Project A's builds complete.

What I'm suggesting is that the queue to get through the backlog could be based on projects instead of individual builds.  When a worker becomes available and Project A's first build is started, that project would then be requeued at the end, *after* Project B's build.  Instead of a build order of AAAAAB, it would be ABAAAA.

That would allow projects with a single OS X build to get results more quickly instead of having to wait for hours for the first slot to become available because there are a bunch of projects with lots of OS X builds in front of them.

Right now, projects don't really have an incentive to reduce the number of OS X builds to below 5; their builds won't really happen any more quickly.  With what I'm suggesting, when there is no backlog everything would happen much the same as it currently does, but when there is a backlog on OS X projects with more OS X builds will take more time but projects with fewer OS X builds will take less time.

**Comment by aacalfa** [comment] 2017-03-07 21:46
Any updates on this? It always takes over an hour to get a build to start for my project, and since this is my first OS X project and I am still experimenting with travis configuration for it, it's been frustrating to figure out what's wrong with my configuration and get a passing build...

**Comment by AnthonyOliveri** [comment] 2017-03-07 22:23
Welcome to Travis-CI on Mac, @aacalfa. It's been like this for months, and only keeps getting worse. I have to wait a couple of hours for my builds to start. 

I thought the Travis team would have been working on this, but apparently not. They are in desperate need of more build machines.

**Comment by bbodenmiller** [comment] 2017-03-18 11:57
https://www.traviscistatus.com/ says they added new macOS build machines.

**Comment by aacalfa** [comment] 2017-03-18 16:15
@bbodenmiller they did but it's still really far from optimal since during business hours the backlog is huge

**Comment by Lyoness** [comment] 2018-01-30 13:44
We've been working hard to improve performance so that macOS/OSX open-source should have no backlog even on weekdays. We've migrated to new hardware and flash storage, which has solved our perpetual backlog problem for macOS Builds for Open Source Projects 

 https://www.traviscistatus.com/ 🎉 
Closing out.

**Closed by Lyoness** 2018-01-30 13:44 UTC
Labels: mac
