### ISSUE TITLE
Python X can not be installed on OSX builds due to an exception raised by tar

### ISSUE THREAD

**Issue by PrashntS** [travis-ci/travis-ci#5975] opened 2016-04-30 10:03 UTC
The following exception is raised while travis attempts to install Python on OSX builds.
Pretty sure that this is not a `.travis.yml` configuration error, since the error is triggered at `sudo tar xjf python-2.7.tar.bz2 --directory /`
```shell
Worker information
hostname: worker-jupiter-brain:7696b2a4-61c6-45ba-bdd0-7a4369d46b36
version: v2.0.0 https://github.com/travis-ci/worker/tree/ca6cb0c5d3920912b1c3acc87c44a5da2120a971
instance: fe2eaa81-3870-4069-8d9e-ac7c109d4280:
startup: 58.634575808s
Build system information
Build language: python
Build group: stable
Build dist: precise

$ export DEBIAN_FRONTEND=noninteractive
Fix WWDRCA Certificate
2.7 is not installed; attempting download
/Users/travis/build.sh: line 45: lsb_release: command not found
/Users/travis/build.sh: line 45: lsb_release: command not found
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

The command "sudo tar xjf python-2.7.tar.bz2 --directory /" failed and exited with 1 during .

Your build has been stopped.
```
Build history: https://travis-ci.org/PrashntS/metaRNA/builds/126733086

**Comment by BanzaiMan** [comment] 2016-04-30 10:04
Duplicate of #2312.

**Closed by BanzaiMan** 2016-04-30 10:04 UTC
