### ISSUE TITLE
The build was successfully restarted is not accurate

### ISSUE THREAD

**Issue by gpldecha** [travis-ci/travis-ci#7303] opened 2017-02-10 16:07 UTC
I cancelled a build which was in progress, made changes to the repository and pushed again.  My aim
is to now test the last push.

However travis seems to only be able to build the first commit and not the future ones.

I select the last pushed "Active **Branches**" and click build. It states that "The build was successfully restarted" but nothing happens.  The two yellow dotes which normally rotate during the build process are stuck.

This seems a bug to me.

see [myrepo/builds](https://travis-ci.org/gpldecha/non-parametric-regression/builds)

**Comment by BanzaiMan** [comment] 2017-02-10 20:07
Sorry about the issue. I see that https://travis-ci.org/gpldecha/non-parametric-regression/builds/198910446 is "queued". I tried canceling on our side, but it is not working for some reason. What happens if you push another commit to this repo?

**Comment by gpldecha** [comment] 2017-02-10 21:01
I pushed another commit to master (removed devel such that there is only one repo) and it seams to all pushes are "queued" and unable to proceed (see https://travis-ci.org/gpldecha/non-parametric-regression/builds).

This is not the only repo for which this has happened. This behaviour seems to occur if a build is cancelled by the user. Then any new commits will be "queued" and will not be addressed until the initial commit is built successfully. 

This is a recent bug, I do not seem to remember this was the case before. 

If there is anything else I can do to help debug, let me know.

**Comment by BanzaiMan** [comment] 2017-02-10 21:49
I think the culprit is this: https://github.com/gpldecha/non-parametric-regression/blob/5d7e0a1a51bbd3f911a4bbe11e2791556276b119/.travis.yml#L4, which I believe is a variation of #7296. Try dropping that line, or specify a valid value (`precise` or `trusty`).

**Comment by gpldecha** [comment] 2017-02-10 21:54
it was indeed the culprit. It works fine now, thanks!

Do you know when Xenial Xerus will be supported ?

**Comment by BanzaiMan** [comment] 2017-02-12 23:44
Support for Xenial has been requested before, and we have it on our roadmap, but we do not have ETA at the moment.

Since your issue has been resolved, I'm closing this now.

**Closed by BanzaiMan** 2017-02-12 23:44 UTC
