### ISSUE TITLE
[ANDROID] Error with Build-Tools 24.0.2

### ISSUE THREAD

**Issue by Khang-NT** [travis-ci/travis-ci#6624] opened 2016-09-22 03:55 UTC
`Error: Ignoring unknown package filter 'build-tools-24.0.2'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.`

`Error: Ignoring unknown package filter 'android-24'
Warning: The package filter removed all packages. There is nothing to install.
         Please consider trying to update again without a package filter.`

`You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 24.0.2, Android SDK Platform 24].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html`

**Comment by BanzaiMan** [comment] 2016-09-22 12:49
Looks like a duplicate of #6555.

**Closed by BanzaiMan** 2016-09-22 12:49 UTC
