### ISSUE TITLE
Trusty images are using an outdated version for PHP 7.0

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#7197] opened 2017-01-20 15:04 UTC
When I configure my PHP version as ``7.0``, the Precise image uses PHP 7.0.14 (latest available release), while the Trusty image uses the older 7.0.7 one.
It would be great if ``7.0`` could mean "the latest 7.0.x version" for Trusty too.

**Comment by BanzaiMan** [comment] 2017-01-20 16:02
Trusty images are newer, and has PHP 7.0 pre-installed, so if you specify `7.0`, `phpenv` will prefer that. At the moment, if you need a newer version, you need to specify `7.0.x` for some value of `x`.

**Comment by BanzaiMan** [comment] 2017-01-20 16:22
It is possible to change the way we provision images, and not have PHP 7 pre-installed, in which case PHP `7.0` is *always* installed on the fly (and therefore point to the latest release of `7.0.x`), which is not a good experience in my opinion.

**Comment by stof** [comment] 2017-01-23 09:51
it would be great to document this difference though, as it is quite unexpected to have the 7.0 alias pointing to an older version when switching to a newer image.

**Comment by BanzaiMan** [comment] 2017-01-23 13:21
This is how `5.6` and other aliases always worked.

**Comment by BanzaiMan** [comment] 2017-01-23 14:52
I'm closing this as a duplicate of #7014.

**Closed by BanzaiMan** 2017-01-23 14:52 UTC
Labels: php
