### ISSUE TITLE
docker pull sometimes timeouts

### ISSUE THREAD

**Issue by LebedevRI** [travis-ci/travis-ci#9156] opened 2018-01-29 12:57 UTC
E.g. https://travis-ci.org/darktable-org/darktable/jobs/332713039, https://travis-ci.org/darktable-org/darktable/jobs/332189101
`docker pull` does not finish within 10(yes, in that link the limit is 5) minutes limit.
And wrapping it into `travis_retry travis_wait 5 docker pull` does not help either.

This is a new problem, or at least it is much more frequent this month or so.

**Comment by soulshake** [comment] 2018-01-29 18:24
@LebedevRI Does it succeed with a higher timeout value, like `travis_wait 30` (without `travis_retry`)?

Potentially related:
- https://github.com/travis-ci/travis-ci/issues/9127
- https://github.com/docker/hub-feedback/issues/1233#issuecomment-361149200

**Comment by LebedevRI** [comment] 2018-01-29 18:28
> Does it succeed with a higher timeout value, like travis_wait 30 (without travis_retry)?

Did not try (yet?).
What i can tell, is that when i restart the job manually, it succeeds.

Thanks for the references, those do look related.

**Comment by soulshake** [comment] 2018-01-29 19:24
I'm going to close this for now as a duplicate of https://github.com/travis-ci/travis-ci/issues/9127
If you find reason to believe this is a separate issue, feel free to reopen.
Thanks!

**Closed by soulshake** 2018-01-29 19:24 UTC
