### ISSUE TITLE
Unknown SSL protocol error when fetching resource from releases.hashicorp.com

### ISSUE THREAD

**Issue by cirocosta** [travis-ci/travis-ci#7434] opened 2017-03-07 14:44 UTC
Hey,

firstly, keep up with the super great service you have! Travis is amazing ;)

Now, to the issue, i've seen that i can't fetch resources like https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_linux_amd64.zip when running in a travis container-based worker. 

```
curl -kL http://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_linux_amd64.zip -o consul.zip -v
* About to connect() to releases.hashicorp.com port 80 (#0)
*   Trying 151.101.33.183...   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0connected
> GET /consul/0.7.5/consul_0.7.5_linux_amd64.zip HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: releases.hashicorp.com
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: Varnish
< Retry-After: 0
< Location: https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_linux_amd64.zip
< Content-Length: 0
< Accept-Ranges: bytes
< Date: Mon, 06 Mar 2017 20:29:34 GMT
< Via: 1.1 varnish
< Connection: close
< X-Served-By: cache-iad2126-IAD
< X-Cache: HIT
< X-Cache-Hits: 0
< X-Timer: S1488832174.501712,VS0,VE0
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection #0
* Issue another request to this URL: 'https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_linux_amd64.zip'
* About to connect() to releases.hashicorp.com port 443 (#0)
*   Trying 151.101.33.183... connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* Unknown SSL protocol error in connection to releases.hashicorp.com:443 
* Closing connection #0
curl: (35) Unknown SSL protocol error in connection to releases.hashicorp.com:443 
```

I thought it could be something with hashicorp's  certs but even when explicitly telling curl to not check them, this SSL error appears. Also, it works well with the non-containerized worker.

Is there anything that i can do here?

Thx!

**Comment by BanzaiMan** [comment] 2017-03-07 15:54
Duplicate of #7131. Please use Trusty.

**Closed by BanzaiMan** 2017-03-07 15:54 UTC
