### ISSUE TITLE
Cannot build via python 3.7

### ISSUE THREAD

**Issue by liiight** [travis-ci/travis-ci#9552] opened 2018-04-29 22:27 UTC
I added python 3.7 to travis.yml, unfortunately, build seems to fail:
```
Network availability confirmed.
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to 
```
Full log: https://pastebin.com/duiq1hBm
Link to build: https://travis-ci.org/notifiers/notifiers/jobs/372609513

**Comment by BanzaiMan** [comment] 2018-04-29 22:53
This does not work because there is no Python 3.7 archive (and there is no 3.7 release). `3.7-dev` should work, but it is old, because Python 3.7 will not work with Trusty.

See https://github.com/travis-ci/travis-ci/issues/9069. I'm closing this as duplicate of that issue.

**Closed by BanzaiMan** 2018-04-29 22:53 UTC

**Comment by irmen** [comment] 2018-06-28 17:36
Python 3.7 has just been released now.

**Comment by stephenhky** [comment] 2018-06-28 19:52
Yes, Python 3.7 has just been released. However, I see no support in travis CI yet.

**Comment by aluttik** [comment] 2018-06-28 23:02
When will it be supported?

**Comment by aluttik** [comment] 2018-06-29 01:40
@BanzaiMan Any news on when it will be supported?

**Comment by RJ722** [comment] 2018-07-06 17:55
Related: #9815
