### ISSUE TITLE
Build was finished but still is running

### ISSUE THREAD

**Issue by moylop260** [travis-ci/travis-ci#6943] opened 2016-11-28 03:16 UTC
Steps to reproduce it:
1. Open the following [job#179327472](https://travis-ci.org/OCA/maintainer-quality-tools/jobs/179327472)
2. Press `Restart Job` button
3. Wait the output `Done. Your build exited with 0.`
4. After wait 2 minutes to finish the job...
5. Now wait +8 minutes to finish the job...

Expected:
Job finished after 1 minute or less

Saw:
The job finish after non-output trigger

After wait 2 minutes:
- ![travis](https://cloud.githubusercontent.com/assets/6644187/20655147/4f86712c-b4e5-11e6-9c84-ff64fa42111f.png)

After wait +8 minutes:
- <img width="1253" alt="screen shot 2016-11-27 at 9 15 25 pm" src="https://cloud.githubusercontent.com/assets/6644187/20655234/63b59cee-b4e6-11e6-984e-19b70c8c2129.png">

Environment:
 - I'm using dockerized builds. (`sudo: false`)
 - Chrome browser
 - MAC OSX
 - My [.travis.yml file](https://github.com/OCA/maintainer-quality-tools/blob/master/.travis.yml)

**Comment by BanzaiMan** [comment] 2016-11-28 03:31
I believe this is a duplicate of #6861. I'm closing this as such, but if you think it is not a duplicate, do let us know.

**Closed by BanzaiMan** 2016-11-28 03:31 UTC

**Comment by moylop260** [comment] 2016-11-28 03:36
Thanks for reply.
Yes, It is the same issue
