### ISSUE TITLE
Please add PHP 7.3 images

### ISSUE THREAD

**Issue by Majkl578** [travis-ci/travis-ci#9717] opened 2018-06-07 21:06 UTC
PHP 7.3.0alpha1 was released today: http://news.php.net/php.internals/102198

Please consider preparing PHP 7.3 image so it can be used for testing once 7.3 reaches beta.

Timetable for 7.3 can be found [here](https://wiki.php.net/todo/php73#timetable). PHP 7.3 should be branched on July 17 and master will become 7.4 (thus should become `nightly` on Travis).

Thanks!

**Comment by mlocati** [comment] 2018-06-21 15:33
And today they released 7.3.0alpha2: http://php.net/archive/2018.php#id2018-06-21-1

**Comment by BenMorel** [comment] 2018-07-31 16:01
PHP 7.3.0 is now beta: https://github.com/php/php-src/releases/tag/php-7.3.0beta1
Any ETA on this?

**Comment by Majkl578** [comment] 2018-08-02 11:31
Beta 1 is now officially released: http://news.php.net/php.internals/103024

@BanzaiMan Can you please give us any ETA? Thanks!

**Comment by BenMorel** [comment] 2018-08-14 16:09
Beta 2 [tagged](https://github.com/php/php-src/releases/tag/php-7.3.0beta2) today.

**Comment by localheinz** [comment] 2018-08-20 09:47
Any news on this one?

Using `nightly` currently installs `PHP 7.4.0-dev`, see

* https://github.com/TomasVotruba/tomasvotruba.cz/pull/444/files#diff-354f30a63fb0907d4ad57269548329e3R5
* https://travis-ci.org/TomasVotruba/tomasvotruba.cz/jobs/417861384#L433

/cc @TomasVotruba

**Comment by mlocati** [comment] 2018-08-20 09:59
Just for reference, here's the list of estimated release dates of PHP 7.3: https://wiki.php.net/todo/php73

**Comment by BanzaiMan** [comment] 2018-09-07 13:06
We will take a look some time next week. Sorry for the delay.

**Comment by Majkl578** [comment] 2018-09-12 02:47
7.3.0RC1 [tagged](https://github.com/php/php-src/tree/php-7.3.0RC1)

**Comment by BanzaiMan** [comment] 2018-09-12 18:30
For 7.3.0RC1, we are waiting for https://github.com/php-build/php-build/pull/527 to be merged.

**Comment by BanzaiMan** [comment] 2018-09-12 18:52
https://github.com/travis-ci/travis-nightly-builder/commit/264a8f5f8e46c81fde17eb672709242ea9147646 adds `7.3snapshot`.

**Comment by Majkl578** [comment] 2018-09-12 18:56
Thanks! Can we also expect the `7.3` alias? :pray:

**Comment by BanzaiMan** [comment] 2018-09-12 21:54
Trusty and Precise can't build 7.3 because `libzip` is too old. https://travis-ci.org/travis-ci/php-src-builder/jobs/427827063#L942

and the Xenial build has compilation error: https://travis-ci.org/travis-ci/php-src-builder/jobs/427827062.

**Comment by BanzaiMan** [comment] 2018-09-12 21:55
Maybe RC1 at least compiles on Xenail. We shall see.

**Comment by sodabrew** [comment] 2018-09-13 10:56
The build failure is in the ssh2 module, which does not yet have a PHP 7.3-compatible release: https://github.com/php/pecl-networking-ssh2/commits/master

This is a chicken-and-egg situation because the ssh2 module tests on Travis CI: https://github.com/php/pecl-networking-ssh2/blob/master/.travis.yml

**Comment by BanzaiMan** [comment] 2018-09-13 13:57
Disabling ssh2 on 7.3 should suffice, then, but 7.3 will only be available for Xenial with `sudo: required`. Once `ssh2` is in good shape, we can re-enable it.

**Comment by Majkl578** [comment] 2018-09-13 15:49
> 7.3 will only be available for Xenial with sudo: required. 

I can imagine this will be a problem in long-term. People will switch their configurations to Xenial (config-wide `dist: xenial`) + `sudo: required` in order to _also_ run their tests on PHP 7.3.
Xenial `dist` isn't documented either: https://docs.travis-ci.com/user/reference/overview/#stq=xenial&stp=1

**Comment by sodabrew** [comment] 2018-09-14 20:17
@BanzaiMan Can you advise when a PHP 7.3 image may become available?

**Comment by sodabrew** [comment] 2018-09-14 20:19
cc @remicollet to assist with some wider community coordination as PHP 7.3 gets ready to ship.

**Comment by cmb69** [comment] 2018-09-14 21:31
@BanzaiMan PHP 7.3 still has a bundled libzip, which can be used instead of the system lib by configuring with `--without-libzip` (that's not recommended, but may serve as a temporary solution for Trusty and Precise).

Not sure about the status of ssh2. @sgolemon?

**Comment by BanzaiMan** [comment] 2018-09-15 01:32
https://travis-ci.org/travis-ci/php-src-builder/jobs/428863269 builds 7.3.0RC1 without ssh2.

**Comment by remicollet** [comment] 2018-09-15 05:40
> I do not expect this libzip requirement to change. Providing PHP 7.3 on Trusty with the bundled libzip might be misleading, no?

We keep the bundled copy ONLY because of travis which have a very old base by default (trusty). This works. Any version > 0.11 are supported. 1.3.0 is only required to have the full feature set.

In a near future, the plan is to totally drop the bundled library, like for any extension (openssl, intl, etc)

**Comment by henriquemoody** [comment] 2018-09-16 17:07
Some versions of PHP 7.3 are available since yesterday! Check it out: https://s3.amazonaws.com/travis-php-archives

**Comment by BanzaiMan** [comment] 2018-09-16 17:33
@henriquemoody As I pointed out earlier in https://github.com/travis-ci/travis-ci/issues/9717#issuecomment-421521049, I don't think they are fit for use.

**Comment by sodabrew** [comment] 2018-09-16 17:47
I was able to work-around the 7.3.0RC1 tarball zip.so issue by adding `sudo apt-get install libzip4` to my before script.

**Comment by Majkl578** [comment] 2018-09-24 16:16
RC2 is going to be tagged tomorrow, any updates @BanzaiMan? :blush:

**Comment by DeepDiver1975** [comment] 2018-09-25 08:01
Shared lib libzip.so.4 is missing ....

https://travis-ci.org/sabre-io/dav/jobs/432824163

```
php: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory

**Comment by BanzaiMan** [comment] 2018-09-28 23:47
> RC2 is going to be tagged tomorrow, any updates @BanzaiMan? 😊

We rely on https://github.com/php-build/php-build to provide build configuration definitions to build our archives.

**Comment by BanzaiMan** [comment] 2018-09-28 23:55
I understand the reason that the 7.3.0RC1 compilation was fine but the archive fails at run time; the Xenial image is still in flux, and the image that was used for compilation (`language: shell`) was different from the one used at run time (with `language: php`) at the moment.

Until the new image (with `libzip4` pre-installed) is available, that needs to be installed on the fly.

**Comment by WyriHaximus** [comment] 2018-09-29 12:39
@redaxmedia thanks for the example config, that + `sudo: required` works great :+1: . Now having `7.3` available just like `7.2` would be perfect :1st_place_medal:

**Comment by BanzaiMan** [comment] 2018-09-29 12:45
@WyriHaximus You can do this with `matrix.include` or `jobs.include` (choose one).

```yaml
php:
  - "7.2"
  - "7.1"
jobs:
  include:
    - php: "7.3"
      sudo: required
⋮
```

**Comment by WyriHaximus** [comment] 2018-09-29 12:47
@BanzaiMan Cool thank you I didn't know that, but running everything on `sudo: required` works fine in my test case. Would be better if we could do this so there isn't a need to install `libzip4` every time:

```yaml
jobs:
  include:
    - php: "7.3"
      sudo: required
      addons:
       apt:
        packages:
        - libzip4
```

**Comment by BanzaiMan** [comment] 2018-09-29 12:48
@WyriHaximus Ah, yes. Understood.

**Comment by WyriHaximus** [comment] 2018-09-29 12:50
@BanzaiMan so you're looking for any `7.3.x` version without a suffix like `RC1` or `snapshot` in https://github.com/php-build/php-build/tree/master/share/php-build/definitions before for `7.3` can be used just as `7.2` can be now? (Ignoring the `libzip4` issue on `xenial` for a moment.)

**Comment by desrosj** [comment] 2018-10-03 14:20
@BanzaiMan With https://github.com/php-build/php-build/pull/531 merged, what is the missing step to making `7.3.0RC2` available? Happy to submit a PR, just not sure where a change is required.

**Comment by Danon** [comment] 2018-10-03 14:42
And when is `7.4` going to be available?

**Comment by johnbillion** [comment] 2018-10-03 14:47
@Danon Please keep the discussion on topic. 7.4 is available as `nightly`.

**Comment by BanzaiMan** [comment] 2018-10-03 15:54
https://travis-ci.org/travis-ci/php-src-builder/builds/436092125

**Comment by BanzaiMan** [comment] 2018-10-03 15:55
Unfortunately I don't have time to look into it too deep, but if any of you have suggestions or ideas, I am happy to work with you to get us over the hump.

**Comment by cmb69** [comment] 2018-10-03 16:14
@BanzaiMan `--with-password-argon2` requires [libargon2](https://github.com/P-H-C/phc-winner-argon2), not libsodium (the latter is required to build the sodium extension).

**Comment by cmb69** [comment] 2018-10-03 17:06
Regarding the [configure warnings](https://travis-ci.org/travis-ci/php-src-builder/jobs/436092128#L1707):

* `--with-freetype` is superfluous, since it's called `--with-freetype-dir` which is [already given](https://travis-ci.org/travis-ci/php-src-builder/jobs/436092128#L1623)
 * `--with-mcrypt` is superfluous, since the mcrypt extension is [removed as of PHP 7.2.0](http://php.net/manual/en/intro.mcrypt.php)
 * `--with-mysql` is superfluous, since the mysql extension is [removed as of PHP 7.0.0](http://php.net/manual/en/intro.mysql.php)
* `--with-inifile` has been [renamed to `--enable-inifile`](http://php.net/manual/en/dba.installation.php) in PHP 5.2.1 (just fixed the docs; will take a while until the fix is rolled out)

**Comment by Majkl578** [comment] 2018-10-03 21:48
@BanzaiMan @cmb69 libzip fix: travis-ci/php-src-builder#23 (on top of travis-ci/php-src-builder#22)

PHP 7.3: https://travis-ci.org/Majkl578/travis-ci-php-src-builder/builds/436859816
PHP 7.2: https://travis-ci.org/Majkl578/travis-ci-php-src-builder/builds/436859886
PHP 7.1: https://travis-ci.org/Majkl578/travis-ci-php-src-builder/builds/436860031
PHP nightly: https://travis-ci.org/Majkl578/travis-ci-php-src-builder/builds/436860115

**Comment by Majkl578** [comment] 2018-10-13 18:29
PHP 7.3 is now available on Trusty and Precise (`7.3.0RC3` aliased to `7.3`) in non-sudo mode.

libzip issue handled in https://github.com/travis-ci/php-src-builder/pull/23

PHP build: https://travis-ci.org/travis-ci/php-src-builder/builds/440768084
reference consumer PR with 7.3 enabled on Trusty: https://github.com/doctrine/dbal/pull/3323
reference consumer build with 7.3 enabled on Trusty: https://travis-ci.org/doctrine/dbal/builds/441068343

There is an unrelated [build problem with 7.3 on Xenial](https://github.com/travis-ci/php-src-builder/pull/23#issuecomment-429418018), will need to be debugged separately.

**Comment by ADmad** [comment] 2018-11-27 06:48
> I see that issue is now closed

The issue is still open :slightly_smiling_face:.

**Comment by ntwb** [comment] 2018-11-27 06:51
The linked issue is a pull request that has been merged: https://github.com/travis-ci/php-src-builder/pull/23#issuecomment-429418018

**Comment by Majkl578** [comment] 2018-11-27 06:52
I spent some time reproducing the Xenial build failure (in https://github.com/travis-ci/php-src-builder/pull/23#issuecomment-429418018) with no luck. I decided to abandon the effort since I have no plans on using Xenial anyway as it's undocumented and not stable anyway. Sorry. Use Trusty if you need PHP 7.3.

**Comment by DrTorte** [comment] 2018-12-05 05:59
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Closed by DrTorte** 2018-12-05 05:59 UTC
Labels: php

**Comment by BenMorel** [comment] 2018-12-05 16:59
Here: https://travis-ci.community/t/please-add-php-7-3-on-xenial/1238

For what it's worth, it's really a pity to see you move from highly usable GitHub issue tracker to a regular forum, that's much less readable & practical for us to use.
