### ISSUE TITLE
Environment variable sharing in pull requests

### ISSUE THREAD

**Issue by woodruffw** [travis-ci/travis-ci#8665] opened 2017-10-29 16:21 UTC
First of all, thanks for providing this service to the open source community! It's been absolutely invaluable.

I've run into a use case where I need forks of a repository to read a secret environment variable for unit tests. I understand, per https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions, that this is disabled by default and would require me to make the variable non-secret. That's not possible in my case, since the variable is a private encryption key.

I was thinking about how best to solve this, and I came up with two potential solutions:

1. Provide a way to whitelist either GitHub users or particular forks. This would allow maintainers to pick out their largest (and trustworthy) contributors and give them full CI builds.
2. Provide a way to greenlight PRs one-at-a-time. If I've reviewed some changes on GitHub and determined them to be non-malicious, then it would be nice to be able to click a button on the Travis website and allow the CI build to go through.

Have you (the Travis team) considered either or both of these options before? If you've rejected them, do you have any thoughts on how to accomplish the same goal (e.g., a Travis + GitHub bot)?

Best,
William

**Comment by BanzaiMan** [comment] 2017-10-29 17:39
I believe this is a duplicate of #1946.

**Closed by BanzaiMan** 2017-10-29 17:39 UTC

**Comment by woodruffw** [comment] 2017-10-29 18:09
The issue you linked doesn't address the two ideas above, and it's locked to non-collaborators. Is there any other channel for these ideas to be brought up in?

**Comment by j-rewerts** [comment] 2019-06-17 19:48
The referenced solution has also been deprecated since this issue was closed. I'm still interested in finding out if we can give PRs access to environment variables.
