### ISSUE TITLE
Badge is showing incorrect build status

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4024] opened 2015-06-04 12:51 UTC
Issue similar to https://github.com/travis-ci/travis-ci/issues/1597 is recurring, where the badge does not correctly reflect the current branch build status.

This is a different issue from the last one, so I'm opening a separate issue.

**Comment by BanzaiMan** [comment] 2015-06-04 12:52
https://travis-ci.org/jamesdbloom/mockserver
https://travis-ci.org/deltreey/moreon
https://travis-ci.org/repent/rwanda
https://travis-ci.org/famuvie/breedR
https://travis-ci.org/elkdanger/express-autoapi
https://travis-ci.org/haisum/urlshortner
https://github.com/infoxchange/docker-forklift

**Comment by BanzaiMan** [comment] 2015-06-04 12:54
https://travis-ci.org/SachinAgarwal1337/Php-reflection-deflector

**Comment by jails** [comment] 2015-06-04 14:55
Same here, one of my repo get stucks on the "canceled" badge.
https://travis-ci.org/crysalead/jit

**Comment by drogus** [comment] 2015-06-04 15:04
I just deployed one more things for status images cache and things should run better now. I'm going to leave this open for a while, though, while we monitor things.

**Comment by jamesdbloom** [comment] 2015-06-05 05:50
Perhaps this is related to the fact that the image has the following header:

`Cache-Control: public, must-revalidate, max-age=0`

As per the HTTP specification this cache control header will make it hard to predict is this content is cached or not as reverse proxy caches can and will cache expired content.  For example the Level3 CDN one of the big players will cache this content.  The only way to absolutely guarantee nothing is cached is to change the header as follows:

`Cache-Control: no-cache, no-store, must-revalidate, proxy-revalidate`

To also ensure older HTTP 1.0 caches don't cache  the following two headers should be used:

`Expires: 0`
`Pragma: no-cache`

The HTTP specification say the following:

*If a stored response is not "fresh enough" by the most restrictive freshness requirement of both the client and the origin server, in carefully considered circumstances the cache MAY still return the response with the appropriate Warning header (see section 13.1.5 and 14.46), unless such a response is prohibited (e.g., by a "no-store" cache-directive, or by a "no-cache" cache-request-directive; see section 14.9).*
http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html

I've personally seen CDNs and other reverse proxy caches cache content with `max-age=0`, in fact a fixed issue relating to this only just yesterday with Level3.

**Comment by achubaty** [comment] 2015-06-17 22:37
I've had this issue for a while now with one of my repos showing badge status "unknown" even though the builds are passing. https://travis-ci.org/PredictiveEcology/SpaDES

**Comment by BanzaiMan** [comment] 2015-06-18 04:19
@achubaty I resolved this conflict. Sorry for the issue.

**Comment by achubaty** [comment] 2015-06-18 05:16
@BanzaiMan thank you!

**Comment by waylonflinn** [comment] 2015-06-19 23:58
we changed the github profile name for our organization, now the build status says 'failing' even though it's not.
https://github.com/tailwind/bdot

**Comment by epwalsh** [comment] 2015-06-22 15:23
My builds have been passing for a while now yet the badge still says failing. 

[https://travis-ci.org/epwalsh/treemac](https://travis-ci.org/epwalsh/treemac)

**Comment by albertinad** [comment] 2015-06-26 15:42
Hi the badge status image has been stucked for a month in a "unknown status" image.

[https://travis-ci.org/albertinad/brackets-bower/builds](https://travis-ci.org/albertinad/brackets-bower/builds)

Even when the tests/tasks are passing/failing as expected.
Is there any updates related to this? 
Thanks!

**Comment by waylonflinn** [comment] 2015-06-26 19:16
Our badge is updating again. Thanks!

**Comment by BanzaiMan** [comment] 2015-06-26 19:51
@albertinad I've resolved your repo's conflict.
@epwalsh Yours should be fixed, too.

**Comment by epwalsh** [comment] 2015-06-26 20:02
@BanzaiMan Yes! Thank you!

**Comment by albertinad** [comment] 2015-06-26 23:58
Thank you @BanzaiMan !!

**Comment by jpadilla** [comment] 2015-07-17 01:56
I think this is happening to https://travis-ci.org/jpadilla/pyjwt

**Comment by roidrage** [comment] 2015-07-23 18:29
@jpadilla There was indeed a similar conflict, which I've now resolved.

I'm closing this issue in the meantime.

**Closed by roidrage** 2015-07-23 18:29 UTC
Labels: travis-web

**Comment by nryoung** [comment] 2015-09-26 18:53
I think I might be facing a similar issue: https://travis-ci.org/nryoung/algorithms

<img width="942" alt="screen shot 2015-09-26 at 11 52 16" src="https://cloud.githubusercontent.com/assets/1323750/10119249/2c0df2d4-6445-11e5-8aa5-541df0db6c63.png">

**Comment by BanzaiMan** [comment] 2015-09-26 19:01
@nryoung You are not. PR builds do not affect the branches badge. The red comes from https://travis-ci.org/nryoung/algorithms/builds/81134536

**Comment by nryoung** [comment] 2015-09-26 21:00
@BanzaiMan you are correct, I figured out the issue, had to push to `master` kick off another build. Thanks!

**Comment by clintonskitson** [comment] 2015-10-03 14:04
@BanzaiMan I believe I may be running into this conflict at https://travis-ci.org/emccode/dvdcli

**Comment by evolutics** [comment] 2015-10-06 18:29
https://travis-ci.org/evolutics/RFormatter has the same issue. The status image says "build failing", but master currently passes.

**Comment by aczietlow** [comment] 2015-10-06 20:53
I'm experiencing the same issues mentioned above. https://travis-ci.org/aczietlow/Pandoras-Box The most recent builds on master are passing, but the build status image shows failing for the master branch.  .

**Comment by hendrik-cliqz** [comment] 2015-10-07 17:02
:+1:  

Also the branch view is red for me: Is it because 1 out of 5 build failed? But the most recent one succeeded. I do not understand the logic behind it.

**Comment by goekay** [comment] 2015-10-07 18:43
we are experiencing the same issue with our repo https://github.com/RWTH-i5-IDSG/steve

**Comment by benschw** [comment] 2015-10-07 20:24
I'm seeing the same thing: https://travis-ci.org/benschw/srv-lb/builds

**Comment by d-led** [comment] 2015-10-08 08:41
same [here](https://travis-ci.org/d-led/dont_wait_forever_for_the_tests) today

**Comment by svenfuchs** [comment] 2015-10-08 10:04
Sorry about the troubles with the status badges. I am looking into this now.

**Comment by svenfuchs** [comment] 2015-10-08 10:28
I initially thought this is related to a recently updated component that is pre-caches the build status for branches. However, the cached data looks good on our side. I am thinking it might be a browser caching issue, since e.g. this badge just turned from red to green after reloading it a couple times: https://api.travis-ci.org/benschw/srv-lb.svg

**Comment by svenfuchs** [comment] 2015-10-08 11:26
I have found a bug on a recently deployed component that pre-caches the build status for branches. I have deployed a fix, and it seems to be working now. I'll work on re-playing updates for builds from when that component was last deployed.

**Comment by svenfuchs** [comment] 2015-10-08 12:20
Replaying status updates for these builds has finished, and the cache on our side seems up to date for all repositories reported here. However, I believe we also have some kind of oddity going on with our HTTP caching headers, since this badge is red and cached in my browser (304 Not Modified), while it should be green, according to the cache on our side, and our database.

![image](https://cloud.githubusercontent.com/assets/2208/10365985/a27ebb0c-6dc7-11e5-87f3-6e70325b954f.png)

**Comment by svenfuchs** [comment] 2015-10-08 12:20
I'm still going to close this issue, and talk to the team about the HTTP headers thing.

**Comment by evolutics** [comment] 2015-10-08 16:36
Thank you, @svenfuchs! [RFormatter](https://github.com/evolutics/RFormatter) is fine now.

**Comment by hendrik-cliqz** [comment] 2015-10-08 17:49
:+1:  @svenfuchs 

fixed for me as well.

**Comment by f0k** [comment] 2015-10-09 15:15
@svenfuchs: Doesn't seem to be fully solved. Compare:
https://api.travis-ci.org/Lasagne/Lasagne.svg
https://api.travis-ci.org/Lasagne/Lasagne.svg?branch=master
The former works, the latter still shows the wrong status.

**Comment by inodb** [comment] 2016-03-03 00:38
I think I might have the same issue:

![screen shot 2016-03-02 at 7 37 24 pm](https://cloud.githubusercontent.com/assets/1334004/13480790/4534fc40-e0ae-11e5-909c-49ad49648bf4.png)

**Comment by kreynes** [comment] 2016-05-14 12:57
https://travis-ci.org/kreynes/TeleBot I have the same issue, for some odd reason. Would appreciate if this gets fixed :]

**Comment by raould** [comment] 2017-02-10 06:10
(hi, it looks to me that even when it works, there is a delay between a passed build and the badge(s) being updated. That is probably confusing UX over all fwiw. I thought I had this issue here but went back to re-look and the badge had finally/eventually updated.)

**Comment by reach2jeyan** [comment] 2017-02-15 12:41
I still got the same issue, Anyone got it fixed? could help me as to how? I had the recent builds passing, but the badge still shows as `build failed`

**Comment by goedman** [comment] 2017-04-22 16:19
In my case I see this only happening with repositories part of a Github organization. Repositories under my name seem ok.

**Comment by dineshsprabu** [comment] 2017-05-05 06:10
Facing the same issue. Badge shows 'error' but the build passed.
<img width="1432" alt="screen shot 2017-05-05 at 11 39 34 am" src="https://cloud.githubusercontent.com/assets/8150188/25735257/ab65b862-3187-11e7-947c-43e2fa0cbc5d.png">

**Comment by goedman** [comment] 2017-05-05 13:31
Some how my problem got fixed the next day and I have not seen this since. I assumed someone had stepped in. I'd forgotten the closed issue (#4024) number to report back.

**Comment by mirik123** [comment] 2017-08-05 05:24
I have the same issue:
![image](https://user-images.githubusercontent.com/9895557/28993136-865e2504-79b7-11e7-9d69-2facc4b18789.png)

**Comment by HarshKhatore** [comment] 2017-08-08 10:13
This issue is showing up for my repository also.
![travis](https://user-images.githubusercontent.com/17762022/29067426-2706113e-7c50-11e7-856e-4faecf855408.png)

**Comment by HarshKhatore** [comment] 2017-08-08 10:17
But, after some time or a few refreshes, it shows the correct build status.
![travis](https://user-images.githubusercontent.com/17762022/29067574-d0d6e21a-7c50-11e7-9c51-3d33a46ef2cb.png)

**Comment by JohnLBevan** [comment] 2019-03-21 11:37
A note for anyone hitting this via a Google search (i.e. this is not an issue, but a gotcha to be ware of).

If you have a private GitHub repo and find that the Build Status icon in your project does not reflect the build status shown in Travis-CI, it could be because your link does not include a token in the URI's query string.

i.e. For a public repository, the URI: `https://travis-ci.com/organizationOrUserName/repositoryName.svg?&branch=branchToMonitor` is used to fetch the build status image, with the below values being replaced as appropriate:
- organizationOrUserName
- repositoryName
- branchToMonitor

However, for a private repository the URI: `https://travis-ci.com/organizationOrUserName/repositoryName.svg?&branch=branchToMonitor&token=SomeToken` should be used.  i.e. Here e have the additional parameter, `token`, the value of which (represented above as `SomeToken`) is used to authenticate access to this image / to safeguard visibility of the build status.  To find the exact value to use, go to the Travis-CI page for this repo (i.e. `https://travis-ci.com/organizationOrUserName/repositoryName/`), and click on the build status image.  A dialogue pops up giving the appropriate URI to use, including the correct token value.

**Comment by kandu** [comment] 2019-05-29 02:08
https://travis-ci.org/ocaml-community/lambda-term

**Comment by kandu** [comment] 2019-05-29 02:12
we run into the same issue:

https://travis-ci.org/ocaml-community/lambda-term
https://travis-ci.org/ocaml-community/utop

the master branch is passed but a get parameter ?branch=master will show `build failing`

**Comment by GalaxyDream** [comment] 2020-02-24 03:28
The same issue happens to me:

https://travis-ci.com/GalaxyDream/UMPIRE

**Comment by EmyRukundo** [comment] 2020-02-25 08:59
can you try to delete caches and rebuild again

**Comment by mvasilkov** [comment] 2020-05-11 06:46
Reproduces for me:

![Screen Shot 2020-05-10 at 19 22 53](https://user-images.githubusercontent.com/140257/81531933-42853a80-936c-11ea-8169-a90239a189f4.png)

The tooltip even says "passed".

**Comment by rehmanuet** [comment] 2020-05-15 11:47
Build is getting passed but badge shows failed status

**Comment by henrytomsf** [comment] 2020-05-17 09:41
Getting the same issue here as well even after multiple refreshes.

**Comment by trevorbaca** [comment] 2020-06-09 15:24
This has happened to me on and off for years:

<img width="995" alt="Screen Shot 2020-06-09 at 11 22 56 AM" src="https://user-images.githubusercontent.com/5804733/84167054-bd14a900-aa43-11ea-9407-3d2ab59422a2.png">

Any update?

**Comment by chaosink** [comment] 2020-06-14 01:56
Encountered the same problem...

**Comment by rajibchy** [comment] 2020-06-14 08:22
I think this is ```HTTP caching``` problem of ```Travis CI```.
```Travis CI``` should be revalidate before cache response of  this URL: ```https://api.travis-ci.org/organizationOrUserName/repositoryName.svg?branch=branchToMonitor```
or ```https://travis-ci.org/organizationOrUserName/repositoryName.svg?branch=branchToMonitor```

**Comment by manolodd** [comment] 2020-06-14 20:08
The same here:

https://github.com/manolodd/opensimmpls/blob/development/README.md

Markdown is not showing the correct status. Status is OK in Travis site:

https://travis-ci.org/github/manolodd/opensimmpls?branch=master
https://travis-ci.org/github/manolodd/opensimmpls?branch=development

But image URL is not retrieving the same when called from github readme.md (the same if you try the image URL in the browser directly)

**Comment by rehmanuet** [comment] 2020-06-15 05:51
I've found the workaround
In your Readme.MD use the following API link
https://api.travis-ci.org/rehmanuet/Puppeteer-Headless-Automation.svg?branch=master
instead of
https://travis-ci.org/github/rehmanuet/Puppeteer-Headless-Automation.svg?branch=master
It will do the trick

**Comment by ankane** [comment] 2020-06-23 04:09
fwiw, this used to happen occasionally for my projects, but in the past month or so, it started happening very often. https://travis-ci.org/github/ankane/searchkick

**Comment by Tochemey** [comment] 2020-06-23 17:13
The issue still persist wrong build status badge

**Comment by Svalorzen** [comment] 2020-06-24 09:45
This is happening with my repo as well: a grey "build error" badge is randomly shown instead of the standard green passing one. Randomly refreshing seems to update it sometimes, but I can't see the logic in it.

Maybe this issue should be reopened?

**Comment by alichry** [comment] 2020-06-25 15:20
Badge image keeps alternating despite hitting CTRL+SHIFT+R to delete browser cache. It alternated heavily prior recording this.

![travis-ci-broken-2](https://user-images.githubusercontent.com/32630359/85748072-78aa2e00-b710-11ea-88a9-cc8c12bb81e1.gif)

**Comment by tcamargo** [comment] 2020-07-08 18:20
Same here..

https://travis-ci.org/github/libretro/mame

Build ok, wrong badge in github markdown and in travis website.

**Comment by trevorbaca** [comment] 2020-07-08 18:40
The workaround suggested by @rehmanuet in https://github.com/travis-ci/travis-ci/issues/4024#issuecomment-643917403 **does NOT work**.

If you make the suggested change, the badge will appear correctly for a day or two and then return to being incorrect intermittently.

**Comment by tjfarrar** [comment] 2020-07-18 17:46
I'm also having this problem at [https://travis-ci.org/github/tjfarrar/skedastic](https://travis-ci.org/github/tjfarrar/skedastic). When I hover the cursor over the image it even confirms that the latest build passed, yet the image itself says 'build error.'
![image](https://user-images.githubusercontent.com/55871604/87858575-2636e880-c92f-11ea-9fba-fc8da0525779.png)
