### ISSUE TITLE
 Cannot start ChromeHeadless, No usable sandbox

### ISSUE THREAD

**Issue by njleonzhang** [travis-ci/travis-ci#9121] opened 2018-01-23 06:12 UTC
My CI used to work for a long time. but now it always failed with this error:

```
23 01 2018 05:53:47.217:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
23 01 2018 05:53:47.220:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
23 01 2018 05:53:47.224:INFO [launcher]: Starting browser ChromeHeadless
23 01 2018 05:53:47.752:ERROR [launcher]: Cannot start ChromeHeadless
	[0123/055347.371814:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5576a3de5d07 base::debug::StackTrace::StackTrace()
#1 0x5576a3dfc9c1 logging::LogMessage::~LogMessage()
#2 0x5576a2f58471 content::ZygoteHostImpl::Init()
#3 0x5576a2beb630 content::BrowserMainLoop::EarlyInitialization()
#4 0x5576a2bf211e content::BrowserMainRunnerImpl::Initialize()
#5 0x5576a7a7e217 headless::HeadlessContentMainDelegate::RunProcess()
#6 0x5576a3b31807 content::RunNamedProcessTypeMain()
#7 0x5576a3b32232 content::ContentMainRunnerImpl::Run()
#8 0x5576a3b3b0cc service_manager::Main()
#9 0x5576a3b30d72 content::ContentMain()
#10 0x5576a7a7d39f headless::(anonymous namespace)::RunContentMain()
#11 0x5576a7a7d41c headless::HeadlessBrowserMain()
#12 0x5576a3b37eec headless::HeadlessShellMain()
#13 0x5576a25571bd ChromeMain
#14 0x7fa42e49cf45 __libc_start_main
#15 0x5576a2557029 <unknown>
Received signal 6
```

full log: https://travis-ci.org/njleonzhang/vue-data-tables

**Comment by BanzaiMan** [comment] 2018-01-23 14:26
Duplicate of #8836. Please read https://docs.travis-ci.com/user/chrome#Sandboxing

**Closed by BanzaiMan** 2018-01-23 14:26 UTC

**Comment by njleonzhang** [comment] 2018-01-24 07:04
Tnx very much
