### ISSUE TITLE
Read [ci skip] from PR title and skip entire PR

### ISSUE THREAD

**Issue by bootstraponline** [travis-ci/travis-ci#7105] opened 2017-01-03 23:57 UTC
It'd be nice to skip the PR via editing the title instead of editing every commit with `[ci skip]`. A number of providers have this feature, such as [bitrise](http://devcenter.bitrise.io/tips-and-tricks/skip-a-build/).

**Comment by BanzaiMan** [comment] 2017-01-03 23:59
Closing as a duplicate of #5374.

**Closed by BanzaiMan** 2017-01-03 23:59 UTC
