### ISSUE TITLE
Feature Request: Specify custom notification addresses in repository settings

### ISSUE THREAD

**Issue by c-lipka** [travis-ci/travis-ci#5141] opened 2015-11-20 20:18 UTC
I think we should be given a way to specify custom notification addresses in the repository settings, so that we don't have to hard-code them in .travis.yml.

Use case in question: I want build notifications for my repository to be sent to an email mailing list; however, I do not want the mailing list address to become publicly known. Also, I want to make life easier for potential forks that might also build on Travis CI.

I tried setting up an environment variable in the repo settings, but couldn't find a way to reference that variable in .travis.yml.

(As a matter of fact, I think _all_ notification settings should be made available as repository settings, as they're really typically repo-specific.)

**Comment by daspecster** [comment] 2015-11-20 20:32
Would this cover kind of the ideas you're talking about?
http://docs.travis-ci.com/user/notifications/

**Comment by c-lipka** [comment] 2015-11-20 21:02
Am 20.11.2015 um 21:32 schrieb Thomas Schultz:
>
> Would this cover kind of the ideas you're talking about?
> http://docs.travis-ci.com/user/notifications/
>

No; I was already aware of those.
These are all options hard-coded inside `.travis.yml`.

What I'm looking for is a way to configure those settings -- most
specifically the email address(es) -- _without_ hard-coding them in that
file.

**Comment by BanzaiMan** [comment] 2015-11-20 21:58
Thanks for opening this issue. I believe this is a duplicate of #1094. It is on our radar, so stay tuned!

**Closed by BanzaiMan** 2015-11-20 21:58 UTC
Labels: notifications
