### ISSUE TITLE
Travis gives me ruby as language, even if I specified bash

### ISSUE THREAD

**Issue by deajan** [travis-ci/travis-ci#9150] opened 2018-01-26 17:19 UTC
Hello,

i'm facing some strange issue where travis "view config" shows
```
{
  "language": "ruby",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```
whereas my .travis.yml file is
```
language: bash

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

service
    mysql

os:
    linux
    osx

before_script:
    service --status-all; mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
```

My build https://travis-ci.org/deajan/obackup/jobs/333823743 fails with rake command which obviously is ruby...
Anything I missed in recent changes please ?

Best regards.

**Comment by BanzaiMan** [comment] 2018-01-26 19:32
This is weird. Your [`.travis.yml`](https://github.com/deajan/obackup/blob/204680d108496e0f7ccb69d7307b145f67c332f3/.travis.yml) is invalid. As a result, the parser should fail and show the error message to this effect. But instead, the default configuration is used.

**Comment by deajan** [comment] 2018-01-26 23:01
Indeed, fixed the file, no more ruby.
Initially, I've tried a lot of changes in the yaml file in order to get mysql working again.
Any think I can read ? I've tried a lot of solutions, but can't get mysql to work.

**Comment by BanzaiMan** [comment] 2018-01-30 14:56
In https://github.com/deajan/obackup/blob/2eed11303b75201400e0469b7c30d3f0d5290d25/.travis.yml you are using `language: bash`. I don't think we install MySQL on that image. Please try installing it yourself, or use another `language`.

While the initial issue (where an invalid YAML file triggers a build) is troubling, I am going to close this, since the issue is now resolved.

**Closed by BanzaiMan** 2018-01-30 14:56 UTC

**Comment by deajan** [comment] 2018-01-30 16:08
Thanks.
For the records, language: bash worked without trouble some months ago.
Also, nowhere in the travis doc is written that ```language: bash``` will exclude mysql.
I just checked with ```language: php``` and indeed I get mysql installed.
Maybe update the doc ?

Also, shall I open another issue for the invalid YAML file triggers a build ?

Thanks.

**Comment by sunnydevops** [comment] 2019-04-06 09:25
0.15s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.


i am facing this , when trying to deploy my application through travis

**Comment by mindplay-dk** [comment] 2019-05-22 06:59
In my case, I had a `.gitignore` pattern matching `.travis.yml`, so it wasn't getting check-in at all - the random `rake` errors definitely didn't help alleviate my confusion.

Could we get a warning for missing/bad `.travis.yml` config file in the control panel or something?

Might save somebody some embarrassment ;-)

**Comment by gruckion** [comment] 2019-08-02 12:53
This is really confusing. It should default to ruby. It should tell you that your travis file is invalid.
