### ISSUE TITLE
Feature Request: Enable Nested Virtualization on OSX builds

### ISSUE THREAD

**Issue by disrvptor** [travis-ci/travis-ci#6992] opened 2016-12-08 05:37 UTC
Please enable VHV (i.e. VT-x and EPT) for guests/agents that perform builds using the osx profile. This would enable the ability to run things like [xhyve](https://github.com/mist64/xhyve) and run tests on xhyve access libraries, such as [xhyve-ruby](https://github.com/dalehamel/xhyve-ruby). It may also address #5738, which it looks like the travis-ci team was not interested in supporting, but may have changed their minds now that docker is a supported service for non-osx builds.

Reference:

- [vSphere 5.5 - Enable VMware Hardware Assisted Virtualization](https://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.vsphere.vm_admin.doc/GUID-2A98801C-68E8-47AF-99ED-00C63E4857F6.html?resultof=%2522%2576%2574%252d%2578%2522%2520)
- [Some notes on VMWare VHV](http://www.virtuallyghetto.com/2012/08/how-to-enable-nested-esxi-other.html)

**Comment by rotemmiz** [comment] 2017-01-10 20:17
I heard that TravisCI mac infrastructure runs on MacStadium, I am a client of MacStadium as well. Today I enabled nested virtualization on my mac VMs and was able to install and run HAXM and x86 android emulators. 
Check out [this ESX 6 tutorial ](http://www.vladan.fr/nested-esxi-6-in-a-lab/) 

This means x86 Android Emulators in Travis!

Proof 
<img width="1024" alt="screen shot 2017-01-10 at 22 16 46" src="https://cloud.githubusercontent.com/assets/1361404/21823125/850e4e5e-d782-11e6-9230-f6486d98fbd4.png">

**Comment by BanzaiMan** [comment] 2017-06-08 05:08
I'm closing this for now, as a duplicate of #5738.

**Closed by BanzaiMan** 2017-06-08 05:08 UTC
Labels: feature-request, mac
