### ISSUE TITLE
Error caused secure env variable to be printed to log

### ISSUE THREAD

**Issue by igateno** [travis-ci/travis-ci#6081] opened 2016-05-19 22:16 UTC
As you can see in the screenshot below, my DOCKER_PASSWORD got printed to the log output as part of an error message.

![screenshot](https://cloud.githubusercontent.com/assets/847418/15411372/627caa1a-1dd4-11e6-8a11-6ba388d057e6.jpg)

**Comment by BanzaiMan** [comment] 2016-05-19 23:07
Duplicate of #1775.

**Closed by BanzaiMan** 2016-05-19 23:07 UTC
