### ISSUE TITLE
Linux builders saturated

### ISSUE THREAD

**Issue by pitrou** [travis-ci/travis-ci#8991] opened 2017-12-31 17:18 UTC
Linux builders have been saturated for a days now (see https://www.traviscistatus.com/), which seems rather odd in such a holiday period...

**Comment by pitrou** [comment] 2017-12-31 20:04
Not to mention that looking at the monthly graph, the current saturation for Linux builds clearly looks like an anomaly (all the while macOS builds are not saturated at all, which is quite exceptional).

**Comment by pitrou** [comment] 2017-12-31 20:31
Also note that many builds are now much longer than they used to be (2x or 3x longer).

**Comment by sjudd** [comment] 2017-12-31 20:45
There was a ~5x spike in container based builds from ~300 to ~1500 starting at ~7am on 12/31. There's also a large backlog that started on 12/30? 

I've seen my container based builds take > 40 minutes to start today.

**Comment by pitrou** [comment] 2017-12-31 20:57
And in VM builds, a large backlog has started building from December 24th...

**Comment by kortschak** [comment] 2018-01-01 02:56
I am seeing similar poor performance; I am unable to to get tests to complete due to 10 silence timeout or global timeout - locally the tests finish within small number of minutes. The previous state was passing with reasonable time, so I did a revert in the PR (subsequently rebased away) and this also times out as before, so this behaviour is not due to the changes in the PR.

**Comment by cactus** [comment] 2018-01-01 07:36
I'm seeing lots of my test failing with this now

```
oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"
```

😢

**Comment by auscompgeek** [comment] 2018-01-01 07:41
@cactus glad it wasn't just me. I had that worker failure a couple of hours ago too: https://travis-ci.org/robotpy/robotpy-wpilib/jobs/323719944 (I think someone ill-advised then tried to restart the job just now)

**Comment by kbrandwijk** [comment] 2018-01-01 09:35
Also still experiencing these errors :(

**Comment by unional** [comment] 2018-01-01 10:09
Same here. Builds that normally takes < 3 mins now takes 16+ mins to build. And many "disk quota exceeded" errors.

https://travis-ci.org/unional/domture/builds

Fast build:
https://travis-ci.org/unional/domture/builds/323482974

Slow builds:
https://travis-ci.org/unional/domture/builds/323710910
https://travis-ci.org/unional/domture/builds/323712918
https://travis-ci.org/unional/global-test-harness/builds/323743787

**Comment by kbrandwijk** [comment] 2018-01-01 10:15
Switched my config to CircleCI, all problems gone now...

**Comment by Bilge** [comment] 2018-01-01 13:18
At this time the issue appears to be more-or-less resolved. A few builds are still a touch slow, but for the most part, they're all booting normally and finishing in reasonable time.

**Comment by pitrou** [comment] 2018-01-01 15:33
Yes, things seem a lot better now...

**Comment by vladimiry** [comment] 2018-01-01 15:50
Same here, just got the `could not create session key: disk quota exceeded` error https://travis-ci.org/vladimiry/protonmail-desktop-app/jobs/323798719.

**Comment by skirpichev** [comment] 2018-01-01 16:30
> Yes, things seem a lot better now...

Still, there is 2x (or 3x) slowdown...

**Comment by xoviat** [comment] 2018-01-01 18:30
Root cause of this issue seems to be re-queuing.

**Comment by unional** [comment] 2018-01-01 19:31
Currently, even the job queue is not saturated (https://www.traviscistatus.com/), the `disk quota exceeded` error still persist. No build can go through.

**Comment by BanzaiMan** [comment] 2018-01-01 20:02
Hello. Sorry about the issue. We are looking into i.t

**Comment by Bilge** [comment] 2018-01-01 20:09
Hiro is the hero we need :^)

**Comment by BanzaiMan** [comment] 2018-01-01 20:11
We'll post updates on http://stspg.io/aaa99785f. Thanks.

**Comment by BanzaiMan** [comment] 2018-01-02 04:46
We believe the issue has been eradicated. I'm closing this now, but if you see problems resurface, do let us know.

**Closed by BanzaiMan** 2018-01-02 04:46 UTC

**Comment by unional** [comment] 2018-01-02 05:56
The builds still takes quite a while to start and very slow (15 minutes+ counting from build job started):
https://travis-ci.org/unional/domture/builds/324017975

compare to 3 minutes:
https://travis-ci.org/unional/domture/builds/323482974

One good thing is the `disk quote error` is gone.

**Comment by auscompgeek** [comment] 2018-01-02 06:02
I'm having builds time out (https://travis-ci.org/robotpy/robotpy-wpilib/builds/323719943) when I wouldn't expect them to take any longer than 4 minutes at worst (e.g. https://travis-ci.org/robotpy/robotpy-wpilib/builds/321673298).

**Comment by kortschak** [comment] 2018-01-02 07:55
Still having problems with timeouts.

**Comment by unional** [comment] 2018-01-02 10:31
Definitely network issues:

```sh
fatal: unable to access 'https://github.com/unional/global-test-harness.git/': Failed to connect to github.com port 443: Connection timed out
```

**Comment by BanzaiMan** [comment] 2018-01-02 13:30
Please open a separate issue for the networking problem. Thanks.
