### ISSUE TITLE
CI failing with .NET core project

### ISSUE THREAD

**Issue by quattro004** [travis-ci/travis-ci#6831] opened 2016-11-06 19:08 UTC
I setup up CI and it's saying the OS doesn't support .NET core. You can view the build results here => https://travis-ci.org/quattro004/Chesster

Thanks,

Reese

**Comment by BanzaiMan** [comment] 2016-11-06 20:19
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by Joshua-Anderson** [comment] 2016-11-07 06:22
Dupe of #6805 

Sorry the documentation hasn't been updated to fix it yet.

**Closed** 2016-11-07 10:33 UTC

**Comment by quattro004** [comment] 2016-11-07 15:13
ok, thanks.

**Comment by quattro004** [comment] 2016-11-07 15:53
I updated my config file but am now getting the following error: am I
supposed to run a command to install NuGet?

$ nuget restore Chesster.sln

No command 'nuget' found, did you mean:

 Command 'nget' from package 'nget' (universe)

nuget: command not found

The command "nuget restore Chesster.sln" failed and exited with 127 during .

**Comment by ThePadawan** [comment] 2017-01-15 20:35
@Joshua-Anderson I'm still running into this issue, even with
```
sudo: required
dist: trusty
```

in my .travis.yml. See results at https://travis-ci.org/ThePadawan/the_diary/builds/192176091.

Are there any more configuration steps I need to take to be able to use nuget?

**Comment by Joshua-Anderson** [comment] 2017-01-16 00:52
@ThePadawan You're using .NET core, which doesn't use the nuget CLI, so it isn't installed. You can use `dotnet restore` instead I believe.

**Comment by ThePadawan** [comment] 2017-01-16 07:18
@Joshua-Anderson Thanks, I did not know that :). I can work using that method.
