### ISSUE TITLE
Docker not available when `language: - haskell` set

### ISSUE THREAD

**Issue by lwm** [travis-ci/travis-ci#5711] opened 2016-02-29 13:26 UTC
I am working on [a Haskell project][1]. If I run a build with the following `.travis.yaml`:

```
sudo: required
language: sh
dist: trusty
group: edge
services: 
  - docker
before_install:
- docker build -t verbs .
... 
```

Docker is found, and the build continues. 

However, when `language: - haskell` is set, Docker cannot be found.

Related #5448, #5444.

[1]: https://github.com/lwm/es-api

**Comment by BanzaiMan** [comment] 2016-02-29 17:16
Where is a build that has `sudo: required` and `language: haskell`?

**Comment by lwm** [comment] 2016-02-29 18:50
@BanzaiMan 

This [.travis.yml](https://github.com/lwm/es-api/blob/2d87b022c0014258f2f5e4723dbd69ea4c5cb284/.travis.yml) file failed with this [build log](https://travis-ci.org/lwm/es-api/builds/104424798). 

I did a lot of force pushes, so can't find exact build with the `dist: trusty` and `group: edge` also. Can recreate if needed.

**Comment by BanzaiMan** [comment] 2016-02-29 20:41
I think this is a duplicate of #5262.

**Closed** 2016-03-05 22:16 UTC
