### ISSUE TITLE
coverage segfault on Python 2.7

### ISSUE THREAD

**Issue by daenney** [travis-ci/travis-ci#10070] opened 2018-09-01 17:12 UTC
While running with `coverage` for a project with different Python versions in its matrix, the 2.7 one errors after having ran all tests with:

```
/home/travis/.travis/job_stages: line 78:  1960 Segmentation fault      (core dumped) coverage run --source=vipaccess setup.py test
```

The full build can be found here: https://travis-ci.org/dlenski/python-vipaccess/jobs/423409000

The rest of the matrix is unaffected and builds on 3.3-3.7 work flawlessly.

The interesting bit is that the last build that did not display this issue, although 7 months ago, uses the same version of coverage as the builds that are now breaking, 4.5.1. This leads me to believe the isuse is in the Travis environment and not in coverage or the test suite.

|| [Last successful build](https://travis-ci.org/dlenski/python-vipaccess/jobs/340746989)|[Failing build](https://travis-ci.org/dlenski/python-vipaccess/jobs/423409000)|
|-|------------------------------|------------------|
|python|2.7.14|2.7.14|
|pip|9.0.1|9.0.1|
|coverage|coverage-4.5.1-cp27-cp27mu-manylinux1_x86_64.whl|coverage-4.5.1-cp27-cp27mu-manylinux1_x86_64.whl|
|worker version|3.4.0|4.0.0

**Comment by BanzaiMan** [comment] 2018-09-14 20:05
Hello, there. Could you try forking from https://travis-ci.org/dlenski/python-vipaccess/jobs/340746989 and see if the problem manifests?

**Comment by daenney** [comment] 2018-09-15 08:57
I'm not quite sure what you're asking? Should I try and run the build from that point in time?

**Comment by BanzaiMan** [comment] 2018-09-23 01:33
Create a new branch from https://github.com/tprasadtp/python-vipaccess/tree/upstream-hotp and open a PR for https://github.com/dlenski/python-vipaccess's `master` branch. This should re-create https://github.com/dlenski/python-vipaccess/pull/10. My guess is that it will fail. (I would also reckon that if you restart https://travis-ci.org/dlenski/python-vipaccess/jobs/340746989, it would also fail, but I'd like to keep that around for reference.)

Often there are a lot more changes than you are aware of, and they are the cause of the segmentation fault. Just at a glance, I see; `lxml` updated from 4.1.1 in the passing build to 4.2.4 in the failing build, pycryptodome from 3.4.11 to 3.6.6, urllib3 from 1.22 to 1.23, idna from 2.6 to 2.7, coveralls from 1.2.0 to 1.5.0, etc.

**Comment by BanzaiMan** [comment] 2018-11-08 04:33
Closing this for now.

**Closed by BanzaiMan** 2018-11-08 04:33 UTC
