### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Lazin** [travis-ci/travis-ci#9008] opened 2018-01-04 10:10 UTC
I have a test (python script, to be specific) that starts a server, sends some data over TCP, sleeps for five seconds, and then it tries to read data using HTTP. It always works on my machines but on Travis it sometimes fails with this error https://travis-ci.org/akumuli/Akumuli/builds/324748282#L2636 when the script is trying to read data through HTTP.

It's not the timing issue since the script retries query several times (with increasing pauses). I thought that maybe, this is an environmental problem of some kind. It only reproduces on Travis. I wasn't able to reproduce it anywhere else. On Travis, it affects about 20% of all my builds.

**Comment by stefanbethke** [comment] 2018-01-04 11:01
This might be similar to #9000.

**Comment by BanzaiMan** [comment] 2018-01-05 14:43
I'm closing this as a duplicate of #9000.

**Closed by BanzaiMan** 2018-01-05 14:43 UTC

**Comment by Lazin** [comment] 2018-01-05 14:53
It's not a network problem, everything works locally, I'm getting a refused connection on localhost.

**Comment by simlu** [comment] 2018-01-05 14:56
@Lazin There exists currently a severe problem wrt network for travis. Not sure if this is related or not, but I'd wait until that problem gets fixed and try again then. If this problem is still present this issue can be re-opened / recreated.

**Comment by BanzaiMan** [comment] 2018-01-05 15:00
@Lazin Do you have a build log that shows the connection problem to `localhost`? The job you indicated above appears to have been restarted (and succeeded).

**Comment by Lazin** [comment] 2018-01-05 15:02
This is the same error - https://travis-ci.org/akumuli/Akumuli/builds/324981191#L2636 both server app  and the client works on the same machine so it shouldn't be network related.

**Comment by simlu** [comment] 2018-01-05 15:09
@Lazin Looks to be #9000 - I'm not sure why you say it shouldn't be network related. The problems for #9000 are in the network stack and very likely inside the machine afaIct.

**Comment by Lazin** [comment] 2018-01-05 15:38
OK, let's see what happens there.

**Comment by simlu** [comment] 2018-01-11 01:43
@Lazin Did this resolve for you?

**Comment by Lazin** [comment] 2018-01-11 07:28
Restarted the build several times without any issues. Looks like everything is OK, thank you guys!
