### ISSUE TITLE
Online linters don't understand `language: r`

### ISSUE THREAD

**Issue by craigcitro** [travis-ci/travis-ci#5475] opened 2016-01-16 17:51 UTC
I tried using https://lint.travis-ci.org/ and http://yaml.travis-ci.org/ to lint a file like
    language: r
and got an error about unknown language. Does adding support require a separate CL to https://github.com/travis-ci/travis-yaml/blob/master/lib/travis/yaml/nodes/language.rb to add it? 

(Originally reported as https://github.com/craigcitro/r-travis/issues/171 by @cloudcello)

**Comment by BanzaiMan** [comment] 2016-04-27 09:02
Duplicate of #5084.

**Closed by BanzaiMan** 2016-04-27 09:02 UTC
Labels: travis-yaml
