### ISSUE TITLE
build failed for .NET project with sudo apt-get install -qq mono-complete...

### ISSUE THREAD

**Issue by jochenwezel** [travis-ci/travis-ci#5095] opened 2015-11-12 13:31 UTC
```
Using worker: worker-linux-docker-b112aa48.prod.travis-ci.org:travis-linux-4

Build system information
Build language: csharp
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"


C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
Installing Mono
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.y5XrEQb3lc --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 36669 36677
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-i386_Packages.gz is not what the server reported 36729 36733
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build-utilities-v4.0-4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build-engine4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-runtime-serialization-formatters-soap4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-data-tds4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-transactions4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-drawing4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-accessibility4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-webbrowser4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n-west4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-componentmodel-composition4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data-linq4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-design4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-extensions4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-http4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-management4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-oracle4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-io-compression4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-json-microsoft4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

The command "sudo apt-get install -qq mono-complete mono-vbnc fsharp nuget referenceassemblies-pcl" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by jochenwezel** [comment] 2015-11-12 13:33
@joshua-anderson @akoeplinger @nterry The build is configured as follows:
``` yaml
language: csharp
solution: CompuMaster.Data.VS2012.sln
install:
  - nuget restore CompuMaster.Data.VS2012.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CompuMaster.Data.VS2012.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CompuMaster.Test.Tools.Data/bin/CompuMaster.Test.Tools.Data.dll
```

**Comment by akoeplinger** [comment] 2015-11-12 13:33
We're aware of it and working on a fix, looks like the recent push of Mono 4.0.5.1 hasn't invalidated the CDNs correctly. Sorry!

**Comment by akoeplinger** [comment] 2015-11-12 14:07
This should be fixed now, please try again :)

**Comment by akoeplinger** [comment] 2015-11-12 16:09
We've invalidated the CDNs we're using, if you're still seeing issues then something else is caching it (which might be fixed by just waiting a few hours).

**Comment by FObermaier** [comment] 2015-11-13 07:05
Is there a way to mark build that are failing due to failure to set-up the build environment to inconclusive or sth like that and not failed?

**Comment by akoeplinger** [comment] 2015-11-13 10:28
@FObermaier no, we have no control over that from the C# language integration afaik. But the issue should now be fixed, so you can retry those builds by clicking on the retry/circle button on the build status page to schedule a new build and it'll replace the failed one.

**Comment by FObermaier** [comment] 2015-11-13 10:43
@akoeplinger, I can confirm the issue is fixed. Thanks

**Closed** 2015-12-15 15:21 UTC
Labels: community:csharp
