### ISSUE TITLE
Failed to install Mono

### ISSUE THREAD

**Issue by bunnyc1986** [travis-ci/travis-ci#7335] opened 2017-02-17 18:58 UTC
Builds are failing because the worker can't install Mono

> Installing Mono
> Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.sYoZ3omcvT --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
> gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
> gpg: no ultimately trusted keys found
> gpg: Total number processed: 1
> gpg:               imported: 1  (RSA: 1)
> W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/precise/main/binary-amd64/Packages  404  Not Found
> 
> W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> 
> 
> The command "sudo apt-get update -qq" failed and exited with 100 during .
> 
> Your build has been stopped.

**Comment by bunnyc1986** [comment] 2017-02-17 18:58
cc @joshua-anderson, @akoeplinger and @nterry.

**Comment by akoeplinger** [comment] 2017-02-17 19:14
Please see #7332 and https://www.traviscistatus.com/incidents/xlhdxb80swcq

**Comment by BanzaiMan** [comment] 2017-02-19 21:36
Closing as a duplicate of #7332.

**Closed by BanzaiMan** 2017-02-19 21:36 UTC
