### ISSUE TITLE
ImportError: no module named 'gi'

### ISSUE THREAD

**Issue by mrichar1** [travis-ci/travis-ci#8133] opened 2017-07-20 14:19 UTC
Since the trusty update my travis checks (which use gi/Gtk) no longer succeed.  Instead I get errors that python is unable to import gi.

Going back to  `group: deprecated-2017Q2` fixes this issue.

I've tried using `site-packages`, `vext` and other approaches to accessing the gi libraries, all without success.

Config here: https://github.com/mrichar1/clipster/blob/master/.travis.yml

It looks like this might be related to #8132 - am seeing others with the same issue using the same workaround - e.g. https://github.com/ctjacobs/pyqso/commit/9a8fedf4753162307d11920b054a8c6416f851b1

Happy to add more information if helpful!

**Comment by BanzaiMan** [comment] 2017-07-20 16:08
Indeed, I believe this is a duplicate of #8132. I'm closing this.

**Closed by BanzaiMan** 2017-07-20 16:08 UTC

**Comment by pvcraven** [comment] 2018-05-05 21:27
#8132 is nice to reference to learn about 

    virtualenv:
      system_site_packages: true

However, that generates an error with Python 3.6

```
$ source ~/virtualenv/python3.6_with_system_site_packages/bin/activate
/home/travis/.travis/job_stages: line 57: /home/travis/virtualenv/python3.6_with_system_site_packages/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.6_with_system_site_packages/bin/activate" failed and exited with 1 during .
```
