### ISSUE TITLE
Can't sign in on mobile 

### ISSUE THREAD

**Issue by nicolasnoble** [travis-ci/travis-ci#3338] opened 2015-03-06 04:16 UTC
The mobile website doesn't display the github sign in button. Also, requesting the desktop version still gives the mobile site. 

Nexus 5 running Android 5.1 with Chrome and Firefox.

**Comment by BanzaiMan** [comment] 2015-03-06 04:19
Thanks for the report. This is a duplicate of #3272.

**Closed by BanzaiMan** 2015-03-06 04:19 UTC
