### ISSUE TITLE
Cancel builds when exist new commits

### ISSUE THREAD

**Issue by latot** [travis-ci/travis-ci#6887] opened 2016-11-16 21:43 UTC
Hi all, well, as you know when we push a commit travis start working, but some times we send changes continually for one or other reason, but travis add every single commit to the list to build.....

Its possible when we send a new commit cancel previous builds automatically?
Normally i think when we send a commit for example is for fix a bug or similar, so i think have logic cancel actual builds and start the new.

Only to sure, i'll explain a little this with a example, we have a FOO pr, and we send a commit, now travis will build it, but now we found other problem, and we send the second commit and travis will build it, if we continues with this.. 7 times travis will have a list of 7 builds while we are waiting for the last....

Or maybe don't cancel it automatically but at least enable can cancel it when exist a newer commit.

Note, i think can be ideal enable this to the users send a pr to other repo.

Thx. Cya.

**Comment by BanzaiMan** [comment] 2016-11-16 21:46
I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/5160. Closing this as such, but if you think otherwise, do let us know.

**Closed by BanzaiMan** 2016-11-16 21:46 UTC

**Comment by latot** [comment] 2016-11-16 21:48
Ups!, thx!
