### ISSUE TITLE
APT whitelist request for re2c

### ISSUE THREAD

**Issue by njam** [travis-ci/travis-ci#4316] opened 2015-07-12 15:14 UTC

**Comment by BanzaiMan** [comment] 2015-07-20 20:14
Running a basic check to see if the package conatins suspicious setuid/setgid/seteuid calls.

**Comment by BanzaiMan** [comment] 2015-07-20 20:35
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71832658

**Comment by BanzaiMan** [comment] 2015-07-20 20:36
Duplicate of #4225.

**Closed by BanzaiMan** 2015-07-20 20:36 UTC
Labels: apt-whitelist, apt-whitelist-check-run

**Comment by njam** [comment] 2015-07-20 20:38
Ups, thought I looked for it. Sorry!
