### ISSUE TITLE
Job finishes without terminating, then timesout and fails

### ISSUE THREAD

**Issue by jonnybarnes** [travis-ci/travis-ci#8076] opened 2017-07-12 18:30 UTC
See this job: https://travis-ci.org/jonnybarnes/jonnybarnes.uk/jobs/252912119

It seems to have run all the tests, then it just sits there. If I don’t cancel it then after 10 minutes its terminated and is labelled a fail.

**Comment by BanzaiMan** [comment] 2017-07-12 18:42
Probably a duplicate of #6861. Please provide additional information if you believe otherwise.

**Closed by BanzaiMan** 2017-07-12 18:42 UTC
