### ISSUE TITLE
Crystal build fails

### ISSUE THREAD

**Issue by stefanwille** [travis-ci/travis-ci#6196] opened 2016-06-18 19:08 UTC
Hi!

@asterite @jhass @waj @will

My build of crystal-redis fails with
```
/home/travis/build.sh: line 45: crystal: command not found
```

Please can you help me fix this?

I have attached the full Travis log file.

Thanks!
Stefan

[log.txt](https://github.com/travis-ci/travis-ci/files/321926/log.txt)

**Comment by stefanwille** [comment] 2016-06-18 19:08
The build URL is https://travis-ci.org/stefanwille/crystal-redis/builds/138615443

**Comment by jhass** [comment] 2016-06-18 19:33
Duplicate of #5461

**Comment by BanzaiMan** [comment] 2016-06-19 01:41
Closing as a duplicate.

**Closed by BanzaiMan** 2016-06-19 01:41 UTC
