### ISSUE TITLE
"could not load module" in some Fortran codes

### ISSUE THREAD

**Issue by abelsiqueira** [travis-ci/travis-ci#3228] opened 2015-02-13 17:44 UTC
Hello @tkelman,
I'm having some problems with using a shared library compiled during the execution of Julia. The compiler returns "could not load module" and "Cannot open shared object file: no such file". However, the library is there, and this works on my computer. The build:
https://travis-ci.org/abelsiqueira/CUTEst.jl/builds/50652536

This package by @dpo shows the same problem:
https://travis-ci.org/dpo/MUMPS.jl/jobs/50441443#L853

Thank you,
Abel

**Comment by tkelman** [comment] 2015-02-13 18:02
Please try with Julia nightly, this should be fixed there. The issue is described at great length here https://github.com/JuliaLang/julia/pull/8442#issuecomment-69449027, it required building our own gcc instead of using the devtoolset on the buildbot where we make the Linux binaries. There hasn't been a release on the 0.3 branch since that fix was made, but there should be a new one soon.

A temporary workaround is deleting the file `~/julia/lib/julia/libgfortran.so.3`.

**Comment by abelsiqueira** [comment] 2015-02-13 18:21
Thanks a lot, changing to nightly worked.

**Comment by BanzaiMan** [comment] 2015-02-13 19:04
Closing this. Thanks, @tkelman

**Closed by BanzaiMan** 2015-02-13 19:04 UTC
Labels: community:julia

**Comment by tkelman** [comment] 2015-02-19 02:29
FYI this is now fixed on Julia release 0.3.6, tagged yesterday, in addition to nightly.

**Comment by abelsiqueira** [comment] 2015-02-19 02:58
Thanks, updated in Travis and it's working.
