### ISSUE TITLE
Build failing with An error occurred while generating the build script.

### ISSUE THREAD

**Issue by e-e-e** [travis-ci/travis-ci#8675] opened 2017-10-31 06:53 UTC
My build is failing with `An error occurred while generating the build script.`
https://travis-ci.org/loanmarket/react-router-redux-multi/builds/295185164

The config is super simple.
```yml
language: node_js
node_js:
- '6'
script: npm run test
```
and was passing moments before. The only change in the repo was to my `readme.md`.

**Comment by xtx1130** [comment] 2017-10-31 06:56
The same question.And it makes me my daily build failure..../(ㄒoㄒ)/~~

**Comment by lolgear** [comment] 2017-10-31 06:59
@xtx1130 maybe there is a correlation between this issue and https://www.traviscistatus.com/incidents/4vdl52d28hz3
?

**Comment by xtx1130** [comment] 2017-10-31 07:24
@lolgear I have seen this.But my build failed occurred just now, an hour ago it worked well.

**Comment by x4m** [comment] 2017-10-31 07:45
I'm experiencing same problem

**Comment by knipknap** [comment] 2017-10-31 07:52
Same here:
https://travis-ci.org/knipknap/SpiffWorkflow/jobs/295195555

**Comment by mkristian** [comment] 2017-10-31 08:11
just adding mine: https://travis-ci.org/torquebox/mavengem/builds/295198486

**Comment by BanzaiMan** [comment] 2017-10-31 13:05
Duplicate of #8674.

**Closed by BanzaiMan** 2017-10-31 13:05 UTC
