### ISSUE TITLE
Can't install uwsgi

### ISSUE THREAD

**Issue by chmduquesne** [travis-ci/travis-ci#3250] opened 2015-02-19 12:47 UTC
Installing uwsgi via apt fails:

    $ sudo apt-get install -qq uwsgi
    Selecting previously unselected package libzmq1.
    (Reading database ... 77462 files and directories currently installed.)
    Unpacking libzmq1 (from .../libzmq1_3.2.2-0~travis1_amd64.deb) ...
    dpkg: error processing /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb (--unpack):
     trying to overwrite '/usr/lib/x86_64-linux-gnu/libzmq.so.3.0.0', which is also in package libzmq3 3.2.2+dfsg-1~travis1
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    Selecting previously unselected package libjansson4.
    Unpacking libjansson4 (from .../libjansson4_2.2.1-1_amd64.deb) ...
    Selecting previously unselected package uwsgi-core.
    Unpacking uwsgi-core (from .../uwsgi-core_1.0.3+dfsg-1ubuntu0.1_amd64.deb) ...
    Selecting previously unselected package uwsgi.
    Unpacking uwsgi (from .../uwsgi_1.0.3+dfsg-1ubuntu0.1_amd64.deb) ...
    Processing triggers for man-db ...
    Processing triggers for ureadahead ...
    Errors were encountered while processing:
     /var/cache/apt/archives/libzmq1_3.2.2-0~travis1_amd64.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)
    
    The command "sudo apt-get install -qq uwsgi" failed and exited with 100 during .

Possibly related to #3106 and #982.

I tried all sorts of workarounds. Those where apt does not complain all give the same result:

    /usr/bin/uwsgi: error while loading shared libraries: libzmq.so.1: cannot open shared object file: No such file or directory

What I tried:
- deinstalling libzmq3 before installing uwsgi
- deinstalling libzmq3 and installing libzmq3-dev before installing uwsgi
- deinstalling libzmq3 and installing libzmq-dev before installing uwsgi
- same as the above, but also running ``sudo ldconfig`` after the installation of uwsgi

Related job: https://travis-ci.org/travel-intelligence/flasfka-deb

Workaround welcome.

**Comment by BanzaiMan** [comment] 2015-02-19 13:01
Before reinstalling `libzmq3`, try removing the file: `/etc/apt/sources.list.d/travis_ci_zeromq3-source.list`.

**Comment by BanzaiMan** [comment] 2015-02-19 13:03
I'm closing this as a duplicate of #3106, which deals with the conflict.

**Closed by BanzaiMan** 2015-02-19 13:03 UTC

**Comment by chmduquesne** [comment] 2015-02-19 13:22
It does the trick. Thank you!
