### ISSUE TITLE
make nodejs version configurable on PHP builds

### ISSUE THREAD

**Issue by Ma27** [travis-ci/travis-ci#5999] opened 2016-05-05 11:25 UTC
using this config: https://github.com/Sententiaregum/Sententiaregum/blob/master/.travis.yml
I've tried to use NodeJS 6 on my PHP Build in this commit (https://github.com/Sententiaregum/Sententiaregum/commit/fdc1b7bb71f6aa326ad7b760feb97c4d59bbba78), but the NVM command failed (https://travis-ci.org/Sententiaregum/Sententiaregum/jobs/128029715)

But according to lines like this (https://travis-ci.org/Sententiaregum/Sententiaregum/jobs/128028670#L158) NVM should be present.

Is there any way to use a current NodeJS Version in a PHP Build or is it possible to do some JS and PHP builds in one config file?

**Comment by Ma27** [comment] 2016-05-05 14:17
https://github.com/travis-ci/travis-ci/issues/4090
this one seems related, but the suggestion to use NVM doesn't work in my case (see the links provided in the description)

**Comment by BanzaiMan** [comment] 2016-05-05 16:27
`nvm` is a function, so you can't call it unless it is loaded.

In the bash script you are trying to use Node.js, be sure to load `~/.nvm/nvm.sh`. See https://github.com/BanzaiMan/travis_production_test/blob/9c02aef/.travis.yml and its build https://travis-ci.org/BanzaiMan/travis_production_test/builds/128089957

**Comment by BanzaiMan** [comment] 2016-05-05 16:27
I'm closing this as a duplicate of #4090.

**Closed by BanzaiMan** 2016-05-05 16:27 UTC
