### ISSUE TITLE
travis-web:  30 % CPU usage when travis-ci.org tab is open

### ISSUE THREAD

**Issue by ottok** [travis-ci/travis-ci#5067] opened 2015-11-08 12:50 UTC
I noticed that my laptop was getting warm even though I was not doing anything special. Turns out it was the travis-ci tab that consumed 30% of my CPU.

I did some JavaScript profiling and it seems the function t.default.Controller.extend.updateTimes that is the culprint. I think you should be able to optimize it a bit, maybe have it run only once in a second since the visible timers anyway only make a step once in a second.

See attached image with profiling results
![kuvakaappaus 2015-11-08 14 42 37](https://cloud.githubusercontent.com/assets/668724/11020413/ea73c7b8-8627-11e5-982d-df613b904caa.png)

**Comment by joshk** [comment] 2015-11-09 14:11
Thank you for creating this issue.

We will look into this ASAP and look into some improvements.

**Comment by drogus** [comment] 2015-11-11 10:19
@ottok thank you for the report and for profiling it

Unfortunately `updateTimes` function already runs only once a second, so we would have to increase it even further to optimise it that way. I suppose this problem can be some kind of leakage (we use `bind` + visibility API in that place), because the function itself doesn't do a lot.

I've tried to profile it locally, but I couldn't find anything suspicious, or anything that we could optimise right away. I'll keep this issue open and I'll look at it once more in the near future, possibly after we update Ember.js version as well, to make sure that it's not anything coming from the framework (in the past we had a similar problem with Ember's runloop bug).

**Comment by ottok** [comment] 2015-11-30 11:21
It is a joke but I cannot resist adding this comment:

If a lot of people suffer from the issue of a travis-ci.org browser tab eating up their CPU cycles, but they don't care, then you should consider taking an advantage of the situation and outsource some of your build farm CPU cycles to the users' browsers.

Projects like [Emscripten](http://kripken.github.io/emscripten-site/) and [Chreep](https://github.com/leaningtech/cheerp-clang) are able to compile C code into JavaScript. This guy Fabrice Bellard even got the [Linux kernel running in JavaScript](http://bellard.org/jslinux/). With some magic engineering you could move some of the workload to browsers of users who keep travis-ci.org open in a tab. They are anyway the people who care about getting the test results as fast as possible, so why not lend some of their CPU cycles to serve them too?

:)

**Comment by drogus** [comment] 2016-01-14 13:36
@ottok we've looked into it again and we found the problem was caused by CSS animations we were using for one of the SVG images. Profiling was confusing, because `updateTimes` is the only thing running periodically. So while it shows on top, it doesn't actually contribute to the slowness that much. If you look at the screenshot you posted again, most of the work is done by "program", not the application code. This should be fixed now, but please let me know if you still see any excessive CPU usage. I'm closing it for now.

**Closed by drogus** 2016-01-14 13:36 UTC
Labels: team teal, travis-web
