### ISSUE TITLE
Multi Os build with trusty enables precise build

### ISSUE THREAD

**Issue by Insoleet** [travis-ci/travis-ci#5337] opened 2015-12-19 10:34 UTC
Hello,

My travis.yml file contains only the following matrix : 

```yaml
matrix:
  include:
    - os: osx
    - dist: trusty
      sudo: required
```

And still, precise build is enabled ( https://travis-ci.org/ucoin-io/sakia/builds/97823383 )
I tried multiple configurations which all reproduces this bug : 

```yaml
matrix:
  include:
    - os: osx
    - os: linux
      dist: trusty
```

```yaml
matrix:
  include:
    - os: osx
    - dist: trusty
```
It looks like a bug. Is there any workaround ?

Thanks for your work and the great tool you offer to libre projects.

Inso

**Comment by BanzaiMan** [comment] 2015-12-19 11:22
I believe this is a duplicate of #4681.

**Closed** 2015-12-29 15:49 UTC
Labels: matrix expansion

**Comment by eighthave** [comment] 2016-02-15 12:37
I'm also afflicted by the bug, but I can't see how its related to #4681  In this case, there is not an additional build, there are just two builds, but the `linux` one reverts to Ubuntu/precise.  Here's my config snippet:

```yaml
language: android
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      env: ANDROID_HOME=/usr/local/opt/android-sdk
```

**Comment by BanzaiMan** [comment] 2016-02-15 13:01
@eighthave We do not support Android on OS X. See #2320.
