### ISSUE TITLE
Installing Mono Failed

### ISSUE THREAD

**Issue by tengyifei** [travis-ci/travis-ci#7346] opened 2017-02-19 00:18 UTC
On Ubuntu Trusty CI env

@joshua-anderson @akoeplinger @nterry

Raw log:
```
Worker information
hostname: i-0c6f65f-production-2-worker-com-ec2.travisci.net:07d0b6a0-6ab1-4fc9-9763-9c991115c7a7
version: v2.5.0 https://github.com/travis-ci/worker/tree/da3a43228dffc0fcca5a46569ca786b22991979f
instance: d6655e3:travis:default
startup: 459.461457ms
Build system information
Build language: csharp
Build group: stable
Build dist: trusty
Build id: 40274923
Job id: 65752669
travis-build version: f409d292d
Build image provisioning date and time
Thu Nov 10 03:26:46 UTC 2016
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Linux Version
4.4.0-45-generic
Cookbooks Version
58fad1f https://github.com/travis-ci/travis-cookbooks/tree/58fad1f
git version
git version 1.9.1
bash version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
clang version
clang version 3.5.0 (tags/RELEASE_350/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
jq version
jq-1.5
bats version
Bats 0.4.0
gimme version
v1.0.0
nvm version
0.32.0
perlbrew version
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.76
postgresql client version
psql (PostgreSQL) 9.6.1
phpenv version
rbenv 1.0.0-33-gc7dcaf1
rvm version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
default ruby version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Pre-installed Ruby versions
ruby-2.2.5
ruby-2.3.1

$ export DEBIAN_FRONTEND=noninteractive
W: Size of file /var/lib/apt/lists/toolbelt.heroku.com_ubuntu_._Packages.gz is not what the server reported 721 725
W: Size of file /var/lib/apt/lists/dl.google.com_linux_chrome_deb_dists_stable_main_binary-amd64_Packages.gz is not what the server reported 1156 1170
W: Size of file /var/lib/apt/lists/dl.hhvm.com_ubuntu_dists_trusty_main_binary-amd64_Packages.gz is not what the server reported 1741 1752
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_multiverse_source_Sources.gz is not what the server reported 7372 7374
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_webupd8team_java_ubuntu_dists_trusty_main_binary-amd64_Packages.gz is not what the server reported 3108 3110
W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
libc6 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 146 not upgraded.
Removing symlink /usr/lib/jvm/java-8-oracle-amd64
$ sudo rm -f /usr/lib/jvm/java-8-oracle-amd64
Reload jdk_switcher
$ source $HOME/.jdk_switcher_rc

C# support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new and cc @joshua-anderson @akoeplinger @nterry
Installing Mono
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.2WUf1oM1tx --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: key D3D831EF: public key "Xamarin Public Jenkins (auto-signing) <releng@xamarin.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
W: Size of file /var/lib/apt/lists/packagecloud.io_rabbitmq_rabbitmq-server_ubuntu_dists_trusty_main_binary-amd64_Packages.gz is not what the server reported 353 2072
W: Failed to fetch https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/dists/trusty/main/source/Sources  Hash Sum mismatch

W: Failed to fetch https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.


The command "sudo apt-get update -qq" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by cotsog** [comment] 2017-02-19 04:12
@tengyfei: I believe `csharp` builds aren't supported yet on Trusty container beta. Can you try to add `sudo: required` to your config?

**Comment by BanzaiMan** [comment] 2017-02-19 21:35
Duplicate of #7344.

**Closed by BanzaiMan** 2017-02-19 21:35 UTC
