### ISSUE TITLE
php7 tusty missing ldap.so

### ISSUE THREAD

**Issue by mcn-fredw** [travis-ci/travis-ci#8367] opened 2017-09-07 19:04 UTC
Our PHP 7.0 tests are generating:
PHPUnit_Framework_Exception: Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/7.0.22/lib/php/extensions/no-debug-zts-20151012/ldap.so' - /home/travis/.phpenv/versions/7.0.22/lib/php/extensions/no-debug-zts-20151012/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by BanzaiMan** [comment] 2017-09-07 19:08
Duplicate of #7067.

**Closed by BanzaiMan** 2017-09-07 19:08 UTC
