### ISSUE TITLE
PyPi deployment not working

### ISSUE THREAD

**Issue by cocodevienne** [travis-ci/travis-ci#7973] opened 2017-06-25 13:09 UTC
Okay so I have two Python whel repos both of which I want to deploy as soon as I push a new commit to the repo. Now Travis is complaining about the "setup.py" but I can build wheels and install the wheel when cloning the repo onto my machines. What's going on?? 
[Iconic] Link is here: https://travis-ci.org/cocodevienne/iconic/jobs/246174260
[Cupcake] https://travis-ci.org/cocodevienne/cupcake/jobs/246174127

**Comment by BanzaiMan** [comment] 2017-06-27 12:16
I'm closing this as a duplicate of https://github.com/travis-ci/travis-ci/issues/6891. In particular, see https://github.com/travis-ci/travis-ci/issues/6891#issuecomment-301968947 for testing a possible fix.

**Closed by BanzaiMan** 2017-06-27 12:16 UTC
Labels: python
