### ISSUE TITLE
jruby not installed with bundler

### ISSUE THREAD

**Issue by TiagoCardoso1983** [travis-ci/travis-ci#6085] opened 2016-05-20 12:19 UTC
If you look at https://travis-ci.org/swisscom/ruby-netsnmp/jobs/131680147 , you see that the build is failing because ```bundle``` cannot be found. This is only occurring for the jruby builds, and I can't understand why. I looked at https://github.com/jeremyevans/sequel/blob/master/.travis.yml for guidelines btw, and I see that the jruby builds are running, although no ```gem install bundler``` hook is defined in before_install. 

Or is this rvm specific?

**Comment by BanzaiMan** [comment] 2016-05-20 18:03
Duplicate of #5861.

**Closed by BanzaiMan** 2016-05-20 18:03 UTC
