### ISSUE TITLE
Corrupt perl downloads from s3

### ISSUE THREAD

**Issue by eserte** [travis-ci/travis-ci#9017] opened 2018-01-06 09:38 UTC
Every now and then I see the following error before the actual building and testing starts:
```
5.16 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-5.16.tar.bz2
$ sudo tar xjf perl-5.16.tar.bz2 --directory /
bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
```
(Full build log: https://travis-ci.org/eserte/Geo-Coder-Googlev3/jobs/325628046#L413)

This looks like a temporary network (?) glitch and restarting the job always fixes the problem. But it would be better if the travis build system could handle this situation more gracefully by first detecting that there was a download+extract problem (e.g. by checking fingerprints after the download, or maybe the download itself triggered an error which was ignored, or by checking the exit code of the tar command), and then retrying the download+extract itself.

**Comment by BanzaiMan** [comment] 2018-01-06 18:16
This is probably a variation of #9000, slow network problem. We can add `--retry` to `curl` to mitigate the problem.

**Comment by timofonic** [comment] 2018-01-08 14:19
@BanzaiMan Is curl command used directly? What about [Axel](https://github.com/axel-download-accelerator/axel) and [aria2](https://aria2.github.io)

What about [HTTPie](https://httpie.org)?

**Comment by BanzaiMan** [comment] 2018-01-08 14:46
@timofonic We use the ubiquitous `curl` directly.

**Comment by timofonic** [comment] 2018-01-08 14:49
@BanzaiMan I'm sorry. I thought using it as a library would be more efficient. Thanks for the answer!

**Comment by BanzaiMan** [comment] 2018-01-10 13:59
We have wrapped our `curl` calls with `--retry 2` (for a total of 3 attempts) with https://github.com/travis-ci/travis-build/pull/1285. Along with the changes described in https://github.com/travis-ci/travis-ci/issues/9000#issuecomment-356583359, we hope that the issue is far less likely to impact your builds now.

I'm closing this optimistically, but if you continue to see the problem, do let us know.

@timofonic We have not looked into rclone.

**Closed by BanzaiMan** 2018-01-10 13:59 UTC

**Comment by eserte** [comment] 2018-01-20 00:01
@BanzaiMan here's another one: https://travis-ci.org/eserte/Geo-Coder-Googlev3/jobs/331008345#L417

The interesting log lines:
```
5.26 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-perl-archives/binaries/ubuntu/14.04/x86_64/perl-5.26.tar.bz2
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
$ sudo tar xjf perl-5.26.tar.bz2 --directory /
bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
```

Is the retry feature already active? Maybe three attempts is not enough?
