### ISSUE TITLE
A rake build failed because of missing bundler/dep_proxy

### ISSUE THREAD

**Issue by breakfast1** [travis-ci/travis-ci#9333] opened 2018-03-14 12:28 UTC
Duplicate of: <https://github.com/bundler/bundler/issues/6340>. I really think this is more of a bundler issue than one of travis-ci but at least maybe I'll get to fix the problem.

Here is the said build: <https://travis-ci.org/tech-angels/vandamme/builds/353287717>. The error is happening at <https://travis-ci.org/tech-angels/vandamme/jobs/353287720#L852>.

As you can see the error is only happening with `ruby-head`.

The only change in the code base is that I updated dependencies. Previous builds were successful.

```
$ bundle exec rake
bundler: failed to load command: rake (/home/travis/build/tech-angels/vandamme/vendor/bundle/ruby/2.6.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/setup.rb:10:in `<top (required)>'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

**Comment by breakfast1** [comment] 2018-03-14 14:34
I fixed it by adding `before_install: gem install bundler` to `.travis.yml`.

**Comment by aprescott** [comment] 2018-03-29 15:26
I'm seeing this same issue across multiple Ruby versions (2.5.1, 2.4.4, etc.). It looks like it previously happened because of #8978. Not sure if this is a regression somewhere.

**Comment by aripollak** [comment] 2018-03-29 22:47
Can this ticket be reopened? Ideally this would be fixed on Travis instead of needing to add a workaround to .travis.yml.

**Comment by BanzaiMan** [comment] 2018-03-30 00:26
I guess #9383 has (slightly) more up-to-date information on this.

**Comment by mvz** [comment] 2018-05-17 11:09
The workaround for this bug started making builds fail just now.

* Re-install bundler: everything but 2.5 fails: https://travis-ci.org/troessner/reek/builds/380128897
* Don't re-install bundler: Only 2.5 fails: https://travis-ci.org/troessner/reek/builds/380127689

**Comment by BanzaiMan** [comment] 2018-05-18 20:58
I'm going to close this as a duplicate of https://github.com/travis-ci/travis-ci/issues/8969#issuecomment-390330259.

> Hi, everyone,
> 
>I _think_ I tracked down the issue to an older version of RubyGems in use by the current Ruby 2.5.1, 2.5.0, 2.4.4 archives (there may be others). I've repackaged the affected Linux archives so that they use RubyGems 2.7.7 (there should be a line in your build log `gem --version` inside the `ruby --version` fold; cf. https://travis-ci.com/BanzaiMan/vandamme/builds/73872255#L470). If applicable, please try restarting the affected job, or drop the `gem install bundler` workaround and test the latest archive, and please report the results here.
> 
> Thank you!

**Closed by BanzaiMan** 2018-05-18 20:58 UTC

**Comment by driv3r** [comment] 2018-07-06 14:17
still occurs on 2.6 preview 2
