### ISSUE TITLE
Cannot log into travis-ci.org or travis-ci.com

### ISSUE THREAD

**Issue by mattpalermo** [travis-ci/travis-ci#7612] opened 2017-04-14 07:57 UTC
This is my first time exploring Travis CI. I can log into travis-ci.com but I cannot log into travis-ci.org. When I try to log into travis-ci.org I get sent back to the log in page. I am not sure how to collect more information about this issue.

I am using Kubuntu 17.04 and I have tried this on the following browsers:
* Firefox 52
* Chrome 57
* Chromium 57

**Comment by BanzaiMan** [comment] 2017-04-14 12:52
Does the browser console show you anything interesting in terms of what might be happening?

**Comment by mattpalermo** [comment] 2017-04-14 20:53
@BanzaiMan I can't tell if anything is logged to the console before the redirect since the redirect seems to clear the browser console. But after the redirect I get the following messages:

```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Content Security Policy: The page’s settings observed the loading of a resource at self (“script-src https://travis-ci.org https://ssl.google-analytics.com https://djtflbt20bdde.cloudfront.net/ https://js.pusher.com https://cdn.travis-ci.org”). A CSP report is being sent. Source: onsubmit attribute on DIV element.  travis-ci.org
Content Security Policy: The page’s settings observed the loading of a resource at self (“script-src https://travis-ci.org https://ssl.google-analytics.com https://djtflbt20bdde.cloudfront.net/ https://js.pusher.com https://cdn.travis-ci.org”). A CSP report is being sent. Source: onchange attribute on DIV element.  travis-ci.org
Content Security Policy: The page’s settings observed the loading of a resource at self (“script-src https://travis-ci.org https://ssl.google-analytics.com https://djtflbt20bdde.cloudfront.net/ https://js.pusher.com https://cdn.travis-ci.org”). A CSP report is being sent. Source: onfocusin attribute on DIV element.  travis-ci.org
```

**Comment by mattpalermo** [comment] 2017-04-14 20:58
Ah, I found how to enable 'persistent logs' and I got two more messages:

```
Firefox can’t establish a connection to the server at wss://ws.pusherapp.com/app/5df8ac576dcccf4fd076?protocol=7&client=js&version=2.2.4&flash=false.  vendor-c83ae7f7e9c40fe359676b67796b3c81.js:24:29710
The connection to wss://ws.pusherapp.com/app/5df8ac576dcccf4fd076?protocol=7&client=js&version=2.2.4&flash=false was interrupted while the page was loading.  vendor-c83ae7f7e9c40fe359676b67796b3c81.js:24:29710
```

**Comment by BanzaiMan** [comment] 2017-04-14 21:23
@mattpalermo Sorry for the issue. We have an internal issue to track it. I know this isn't the same, but you might be able to work around with CLI. https://github.com/travis-ci/travis.rb#login.  

Installation instructions here: https://github.com/travis-ci/travis.rb#installation

**Comment by mattpalermo** [comment] 2017-04-14 21:26
Thankyou @BanzaiMan. I'll give the CLI a go.

**Comment by errogaht** [comment] 2017-04-16 08:07
![](https://goo.gl/psSvcV)
not work for me too

**Comment by mattpalermo** [comment] 2017-04-16 08:34
@errogaht's gif matches what I observed.

**Comment by Jakauppila** [comment] 2017-04-16 17:09
I am encountering this same behavior, but I am getting an error logged to the console:

```
Navigated to https://travis-ci.org/
travis-ci.org/:1 [Report Only] Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1…gpKTsKCQkJfQoJCX0KCX0pKCk7Cgl3aW5kb3cuX2dhcSA9IGdhcS5xZiA9IGdhcTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'self' https://ssl.google-analytics.com https://djtflbt20bdde.cloudfront.net/ https://js.pusher.com https://cdn.travis-ci.org".
```

**Comment by BanzaiMan** [comment] 2017-04-17 12:25
Investigation so far indicates that the issue is confined to accounts which are recently created.

**Comment by bsatoriu** [comment] 2017-04-17 21:38
I'm experiencing this as well. My account was recently created, about six hours prior to this comment.

**Comment by JohnTheodore** [comment] 2017-04-17 21:42
I wanted to signup for travis for the first time and integrate my github project with it. I'm not able to do any of this because signup/signin flow is broken through the web UI.

**Comment by brentertz** [comment] 2017-04-17 21:55
FWIW, I created a new account today and am facing the same issue.

**Comment by BanzaiMan** [comment] 2017-04-17 22:44
Thanks for the reports. When you report, could you indicate whether it's for .org or .com (or both)? If the account name is different from the one you're reporting from, include that, too.

**Comment by jonmast** [comment] 2017-04-17 23:43
@BanzaiMan I am unable to log in to either site. I didn't have an account with either of them before today.

**Comment by henyu6** [comment] 2017-04-18 00:21
I have the same issue. I am able to log on to .org but .com loops me back to the auth page after attempting to sign in.

**Comment by JohnTheodore** [comment] 2017-04-18 01:08
I am able to login to .com but not .org, .org is the loop back to the auth page

**Comment by Jakauppila** [comment] 2017-04-18 01:18
.com works for me, but .org does not.

**Comment by ZAntony** [comment] 2017-04-18 01:20
I rovke Access can't login, I can login. Org but cannot login. Com, this is a bug?

**Comment by ZAntony** [comment] 2017-04-18 01:21
![image](https://cloud.githubusercontent.com/assets/20660115/25110666/6a0a6e02-2418-11e7-95e7-641a82eba9dc.png)

这是我的错误

**Comment by thoughtmanifest** [comment] 2017-04-18 02:30
I can login to neither .com nor .org

Attempting to navigate to the api.travis-ci.com/auth/handshake returns:
"could not resolve github token"

**Comment by errogaht** [comment] 2017-04-18 04:20
Now i can login to .com
but cant login to https://travis-ci.org/

**Comment by ZAntony** [comment] 2017-04-18 06:21
@errogaht hi : You how to log in. Com

**Comment by JohnTheodore** [comment] 2017-04-18 06:42
➜  cloud-custodian git:(priority_email) travis enable
Detected repository as JohnTheodore/cloud-custodian, is this correct? |yes| yes
server error (500: "Sorry, we experienced an error.")

^CLI fails for me too. Though I can login, I can't enable. :(

**Comment by errogaht** [comment] 2017-04-18 10:06
@ZAntony
i think iam dont have account yet (but maybe)
1. Revoke Travic CI from Authorized applications (github)
2. go https://travis-ci.org/
3. click signup
4. confirm access

![https://goo.gl/t20Rvg](https://goo.gl/t20Rvg)

**Comment by brentertz** [comment] 2017-04-18 12:54
As of this morning, I am now able to log in to .org.

**Comment by belaczek** [comment] 2017-04-18 13:07
.org seems to be fixed. I am able to sign in (as a new user). 👍

**Comment by clekstro** [comment] 2017-04-18 13:47
@errogaht We've deployed [a fix](https://github.com/travis-ci/travis-api/pull/476) to our API and the feedback so far has been that this issue is now resolved. Could you try logging in again to confirm?

**Comment by jakauppila** [comment] 2017-04-18 13:58
Excellent, thank you! I am able to successfully able to login to .org now.

**Comment by errogaht** [comment] 2017-04-18 17:33
@clekstro thank you!
All work now ! i can login

**Comment by BanzaiMan** [comment] 2017-04-18 17:37
Thanks for your patience and confirmation, everyone. I'm closing this now.

**Closed by BanzaiMan** 2017-04-18 17:37 UTC
Labels: bug, team teal

**Comment by mattpalermo** [comment] 2017-04-18 23:27
Thankyou @BanzaiMan!

**Comment by mitm001** [comment] 2018-01-20 07:45
I hate to be a dead horse, or at least one that was thought to be dead, but this is still going on.

New public account, win 7, ie11.

Only way I can log in is to

1. Revoke Travis CI from Authorized applications (github)
2. Navigate to the travis-ci app on the GitHub Marketplace.
3. Select the link here: 

> You have already purchased this app on GitHub Marketplace. 
> To complete this installation, you must grant this app access to your GitHub account.

**Comment by BanzaiMan** [comment] 2018-01-20 13:19
@mitm001 I’m sorry to hear about the problem. Marketplace has a different workflow, so we’ll have to investigate your issue separately. Could you send email to supprt@travis-ci.com with details?

**Comment by mitm001** [comment] 2018-01-20 17:08
yes
