### ISSUE TITLE
Separate Github checks for each job in the build matrix

### ISSUE THREAD

**Issue by jarekwg** [travis-ci/travis-ci#6208] opened 2016-06-21 06:15 UTC
Currently, it seems TravisCI can have a maximum of two checks on a Github PR:
- local branch tests
- merged branch tests

However, each of the above may have a build matrix that runs several jobs. On a Github PR we see only the overall result of each test and not the individual jobs in the build matrix.
There should be an option to present each job in the build matrix as a separate check on the Github PR, rather than them being lumped together.

Forgive me if this is already possible, but I've googled and googled and so far come up with naught.

Cheers,
jarekwg

**Comment by BanzaiMan** [comment] 2016-06-21 12:45
I think this is a duplicate of #5035. If you think this is different, please elaborate further.

**Closed by BanzaiMan** 2016-06-21 12:45 UTC

**Comment by jarekwg** [comment] 2016-06-21 23:43
Ah yep it's a dupe. Thanks for linking.
