### ISSUE TITLE
The job exceeded the maximum time limit

### ISSUE THREAD

**Issue by okozlovlux** [travis-ci/travis-ci#6232] opened 2016-06-29 21:52 UTC
Build system info: 
 Setting environment variables from .travis.yml
 ...
 $ g++ --version
 g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

Every build runs success but ends with 
"The job exceeded the maximum time limit for jobs, and has been terminated."
Time spent for build 49m 6sec. 

Usually build terminates during first "long" unit test (50 sec) or during calculation code coverage: 
+lcov ....

Issue, build time is less 50min and lcov runs less 10min

**Comment by BanzaiMan** [comment] 2016-06-29 22:10
Please include a build log URL that shows this problem.

**Comment by okozlovlux** [comment] 2016-06-29 22:19
@BanzaiMan Please, https://travis-ci.org/smartdevicelink/sdl_core/builds/141111363

**Comment by BanzaiMan** [comment] 2016-06-29 22:55
One of your commands has consumed 2553 seconds (42'33") https://travis-ci.org/smartdevicelink/sdl_core/builds/141111363#L491, so I guess the overall build time has exceeded the limit. It is a little shorter than 50, because it includes the time to boot the VM.

I think this is expected behavior.

**Comment by LuxoftAKutsan** [comment] 2016-06-30 07:38
@BanzaiMan  Hi, is 50 minutes is limitation for free travis build? I didn't find any infirmation about it in Travis Help. 
I tested travis build time with dummy project and it was 2 hours. https://travis-ci.org/LuxoftAKutsan/example-c/builds/139713803

**Comment by BanzaiMan** [comment] 2016-07-02 22:03
https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts

**Comment by BanzaiMan** [comment] 2016-07-02 22:04
@LuxoftAKutsan Hmm. That shouldn't be happening. I'll have to look into it.

**Comment by BanzaiMan** [comment] 2016-07-06 01:01
@LuxoftAKutsan It is a known misconfiguration. It will be fixed in the future.

**Comment by BanzaiMan** [comment] 2016-07-06 01:01
OK. I don't think there is anything else to address here.

**Closed by BanzaiMan** 2016-07-06 01:01 UTC

**Comment by waghanza** [comment] 2018-06-04 19:35
@BanzaiMan I have a build that stop on 50 minutes
https://travis-ci.com/tbrand/which_is_the_fastest/builds/75294875

and my fork https://travis-ci.com/waghanza/which_is_the_fastest/builds/75273834 exceed 1 hour (same code base).

An idea, @waghanza use `travis-ci` for **private** and **public** projects and @tbrand use `travis-ci` only for **public** projects

**Comment by josephnicholas** [comment] 2018-08-06 08:24
@BanzaiMan my build was terminated after 50 minutes.
https://api.travis-ci.com/v3/job/138292442/log.txt

**Comment by DanielRuf** [comment] 2018-11-15 10:56
@josephnicholas 
> When a job on a public repository takes longer than 50 minutes.

**Comment by Empact** [comment] 2019-01-06 01:53
This test run passed, but then timed out during the cache upload step:
https://travis-ci.org/bitcoin/bitcoin/jobs/475830791

```
store build cache
0.00schange detected (content changed, file is created, or file is deleted):
/home/travis/.ccache/0/0/4fcd5fc68df3c7060e2cd9bd57d618-5584.manifest
/home/travis/.ccache/0/0/5d2d416eb102d8f4cdef62401ccfd8-3140700.o
/home/travis/.ccache/0/0/6cfc28f60690c8d47612b6549e9b5a-5611319.o
/home/travis/.ccache/0/1/2170194e240c4ac93534e0aeb92030-3172349.o
/home/travis/.ccache/0/1/5957d4e50b1e6c422a2ec5e878f97e-49809.manifest
/home/travis/.ccache/0/1/5d88bfd09dd8541040b365622c9e48-13942.manifest
/home/travis/.ccache/0/1/63cf159d4f815d5061fe7984e298f0-4501287.o
/home/travis/.ccache/0/1/7f05ea0d2fcd2858aa0e19be68f46e-12221.manifest
/home/travis/.ccache/0/1/a9df3dda85379837865f4fb5c5abf4-6156.manifest
/home/travis/.ccache/0/2/4c1cb66c556bdcaa91a3c3b97ac75e-12116.manifest
/home/travis/.ccache/0/2/887a2e7f6587a5874339f07e05bf86-5568912.o
/home/travis/.ccache/0/2/ae25f7e23addc73b509bcd0f75b618-646567.o
/home/travis/.ccache/0/2/cb8e69663b0a5844f85ec8709533ab-3278918.o
/home/travis/.ccache/0/3/316c471e4103a8b45cca0c05c0fa0c-15113.manifest
/home/travis/.ccache/0/4/4079573ea0fa0cf5b94e
...
changes detected, packing new archive
.
.
.
uploading PR.15112/cache-linux-xenial-7637c4c9fbac8ede307f91b63c028350d17ec2d8f8d6176838099823a84d989d.tgz
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by junaruga** [comment] 2019-01-06 16:19
Me too!
Even setting `travis_wait 70`, the job finishes with error for 50 mins.
https://travis-ci.org/junaruga/nanopolish/jobs/475985673

```
$ travis_wait 70 docker run --rm -t \
    -e HDF5="${HDF5:-install}" \
    -e HDF5_VERSION="${HDF5_VERSION}" \
    -e HDF5_CONFIG_ARGS="${HDF5_CONFIG_ARGS}" \
    -e H5_CFLAGS="${H5_CFLAGS}" \
    -e H5_INCLUDE="${H5_INCLUDE}" \
    -e LDFLAGS="${LDFLAGS}" \
    nanopolish
Still running (48 of 70): docker run --rm -t -e HDF5=install -e HDF5_VERSION=1.10.4 -e HDF5_CONFIG_ARGS= -e H5_CFLAGS=-w -e H5_INCLUDE= -e LDFLAGS= nanopolish
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by junaruga** [comment] 2019-01-06 16:42
Thank you. I understand it.

**Comment by LucaCappelletti94** [comment] 2019-02-05 09:46
I receive this error after a [build of 2-3 minutes](https://travis-ci.org/LucaCappelletti94/cnn-code), how is this possible? How could I proceed to fixing this issue? Thanks!

**Comment by BanzaiMan** [comment] 2019-02-05 13:01
@LucaCappelletti94 Yours is a log length limit violation. Click on the "Raw Log" button, and you'll see that `pip install` is writing a whole lot of log.

**Comment by BanzaiMan** [comment] 2019-02-05 13:02
I'm locking this now.
