### ISSUE TITLE
Firefox latest download failing

### ISSUE THREAD

**Issue by kpdecker** [travis-ci/travis-ci#5134] opened 2015-11-19 00:55 UTC
https://ftangftang.wordpress.com/2015/11/17/the-latest-on-firefoxreleaseslatest/?utm_source=twitterfeed&utm_medium=twitter

Mozilla has desupported the latest release symlink due to the above, resulting in:

```
Installing Firefox latest
Found Firefox http://releases.mozilla.org/pub/firefox/releases/latest/linux-x86_64/en-US/
3.05s$ wget -O /tmp/firefox-latest.tar.bz2 $FIREFOX_SOURCE_URL
--2015-11-19 00:05:12--  http://releases.mozilla.org/pub/firefox/releases/latest/linux-x86_64/en-US/
Resolving releases.mozilla.org (releases.mozilla.org)... 54.239.152.13
Connecting to releases.mozilla.org (releases.mozilla.org)|54.239.152.13|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-19 00:05:12 ERROR 404: Not Found.
```

This is failing but not failing the build, leading to some very difficult to debug issues downstream. Ex:

```
19 11 2015 00:08:15.948:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
19 11 2015 00:08:15.954:INFO [launcher]: Starting browser Firefox
19 11 2015 00:09:15.986:WARN [launcher]: Firefox have not captured in 60000 ms, killing.
19 11 2015 00:09:17.988:WARN [launcher]: Firefox was not killed in 2000 ms, sending SIGKILL.
19 11 2015 00:09:19.990:WARN [launcher]: Firefox was not killed by SIGKILL in 2000 ms, continuing.
```

**Comment by BanzaiMan** [comment] 2015-11-19 01:03
Thanks for opening this issue, but it's a duplicate of #5082.

**Closed by BanzaiMan** 2015-11-19 01:03 UTC
