### ISSUE TITLE
"No output has been received in the last 10m0s..." after "Done"

### ISSUE THREAD

**Issue by finom** [travis-ci/travis-ci#7618] opened 2017-04-14 22:02 UTC
[This build](https://travis-ci.org/matreshkajs/matreshka.io) always ends with "No output has been received in the last 10m0s..." message if run successfully and even if it's really broken. How can I fix it? [There is my config](https://github.com/matreshkajs/matreshka.io/blob/master/.travis.yml).

**Comment by BanzaiMan** [comment] 2017-04-15 01:10
I think this is a duplicate of #6861.

**Closed by BanzaiMan** 2017-04-15 01:10 UTC
