### ISSUE TITLE
Unable to load dynamic library memcache.so

### ISSUE THREAD

**Issue by melvin-ibuildings** [travis-ci/travis-ci#5296] opened 2015-12-15 08:50 UTC
Since this this morning i get the message

```
"This job ran on our new platform for Legacy Precise builds. Please read our blog post for more information."
```

My build now fails with the message 
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
```

And indeed when i check the log it is now filled with the message

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/memcache.so"
```

Exerpt of the travis.yml 

```
#
# This file has been generated by the Ibuildings QA-Tools
#
# Any custom Travis-ci configuration be added here
# This file should be added to your project repository
#

language: php

php:
  - 5.5

services:
  - memcached
 ```

Did anything change in how memcache need to be included ?

**Comment by catchamonkey** [comment] 2015-12-15 15:19
:+1: here then.

**Comment by bburnichon** [comment] 2015-12-15 17:24
I also have failures with memcache.so and zmq.so

```sh
$ echo 'extension="memcache.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
$ echo "extension=zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
```

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/memcache.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/memcache.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/memcache.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/memcache.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/zmq.so' - /home/travis/.phpenv/versions/5.5.30/lib/php/extensions/no-debug-zts-20121212/zmq.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by BanzaiMan** [comment] 2015-12-15 17:39
Here's an explanation. Currently, the new GCE image does not have PHP 5.5 pre-installed. This means that we need to install it on-demand, but that package is missing some extensions documented in https://docs.travis-ci.com/user/languages/php#PHP-extensions. I'm looking at re-packaging.

**Comment by bburnichon** [comment] 2015-12-15 17:45
OK, but the problem is not only for the PHP 5.5. I also have the issue with PHP 5.6

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.6.15/lib/php/extensions/no-debug-zts-20131226/redis.so' - /home/travis/.phpenv/versions/5.6.15/lib/php/extensions/no-debug-zts-20131226/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by BanzaiMan** [comment] 2015-12-15 18:00
@bburnichon Ah, I see. That's a variation on the same issue. The 5.6.15 archive was created with the same process that skipped it.

**Comment by bburnichon** [comment] 2015-12-15 18:08
@BanzaiMan Thanks for the info, will wait for an update then.

**Comment by BanzaiMan** [comment] 2015-12-15 19:48
I've repackaged 5.5.30 for GCE Precise. It should have all the extensions listed in https://docs.travis-ci.com/user/languages/php#PHP-extensions.

**Comment by BanzaiMan** [comment] 2015-12-15 23:14
I've also repackaged 5.6.15 for GCE (Precise and Trusty). Please test it.

**Comment by melvin-ibuildings** [comment] 2015-12-16 08:12
I retested and noticed 2 things.

1) if i rebuild a failed build i get the same error (even after clearing caches)
2) If i push to trigger a rebuild i am using the "legacy infrastructure" so i don't get the error.

Maybe important to know i am running build for a private repository.

**Comment by flipflopsandrice** [comment] 2015-12-16 08:23
Can confirm, 5.6 GCE builds are now working.

**Comment by bburnichon** [comment] 2015-12-16 09:48
@BanzaiMan I retested by clicking rebuild button. The issue is still there. Here is the instance that performed build testing-gce-ce1a018b-783b-410c-a42e-1711295ee212:travis-ci-php-precise-1449885455. The build date of this image is Sat 12 Dec.
Failures are gone on 5.6.

**Comment by catchamonkey** [comment] 2015-12-16 09:58
@bburnichon A rebuild failed again for me, but pushing a new commit to the PR/branch worked fine.
Try that.

**Comment by bburnichon** [comment] 2015-12-16 10:07
@catchamonkey Also tried by pushing new commit. Still failing for php 5.5.30. :(

**Comment by catchamonkey** [comment] 2015-12-16 10:47
@bburnichon worth noting that mine are private builds, might be why your's still fail.

**Comment by melvin-ibuildings** [comment] 2015-12-16 11:02
I see that the blog was updated https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

So my guess is that people that opted in will also have problems when pushing a new commit

**Comment by BanzaiMan** [comment] 2015-12-16 18:44
5.5.30 (which is aliased to 5.5 for on-demand installation) has been repackaged as well. Please test it.

**Comment by josegonzalez** [comment] 2015-12-16 19:09
PHP 5.5 works for me, but 5.6, 5.7, and 7.0 all fail on `amqp.so` and `memcache.so` using the one-liner from [the docs](https://docs.travis-ci.com/user/languages/php/#Preinstalled-PHP-extensions). I expect 7.0 to fail, but not the others :(

**Comment by josegonzalez** [comment] 2015-12-16 19:09
Of note, it says that `redis.so` is already loaded after manually copying in the extension.

**Comment by bburnichon** [comment] 2015-12-16 19:17
After checking logs thoroughly, I have a consistent behaviour for PHP 5.5 & 5.6, `memcache.so` fails to load. No problem with `amqp.so`. I also have a warning for `redis.so`: `PHP Warning:  Module 'redis' already loaded in Unknown on line 0`.

**Comment by josegonzalez** [comment] 2015-12-16 19:24
For reference, [here](https://travis-ci.org/josegonzalez/php-queuesadilla/builds/97283833) is a build that is failing for me in a few "interesting" ways.

**Comment by BanzaiMan** [comment] 2015-12-16 20:10
@josegonzalez your last build ran before the 5.5 package was done. Please rerun it.

**Comment by BanzaiMan** [comment] 2015-12-16 20:11
@josegonzalez Also, use `memcached` instead of `memcache`.

**Comment by BanzaiMan** [comment] 2015-12-16 20:38
Looks like I forgot about `memcache-beta`. I'm repackaging 5.5(.30) and 5.6(.16) now. Sorry about that.

Regarding the `redis.so` message… I am curious to know where I can see it. (And how it might be eradicated.) Is it an error, or just warning?

**Comment by josegonzalez** [comment] 2015-12-16 20:38
It's a warning. I guess you are already loading it? I think people might be able to turn those warnings into errors, so in the interest of keeping things as they were, maybe removing it from being auto-loaded would be best.

**Comment by BanzaiMan** [comment] 2015-12-17 00:41
Re-packaging is complete for 5.5(.30) and 5.6(.16). Could you test them again? Thank you!

**Comment by melvin-ibuildings** [comment] 2015-12-17 07:16
I can confirm it works for me now

**Comment by bburnichon** [comment] 2015-12-17 09:54
I also confirm it works properly now for both PHP 5.5 & 5.6.

**Comment by BanzaiMan** [comment] 2015-12-17 16:10
Yay! I'm closing this now.

**Closed by BanzaiMan** 2015-12-17 16:10 UTC
Labels: php, precise-gce

**Comment by josegonzalez** [comment] 2015-12-17 23:39
Worked on my end as well!

**Comment by enov** [comment] 2016-01-21 09:04
Hey :)

Looks like we're having problems of loading extensions for PHP 5.5, 5.6 and 7.0? Things are working fine for PHP 5.4:

https://travis-ci.org/kohana/cache/builds/103288224

Thanks for the wonderful service!

**Comment by BanzaiMan** [comment] 2016-01-21 12:34
@enov apc is not compiled with the recent PHP on-demand archives. Also, `memcache` is not compatible with PHP 7. You should use `memcached` instead.

**Comment by enov** [comment] 2016-01-21 13:01
Thank you for your support @BanzaiMan. We're [enabling the extensions](https://github.com/kohana/cache/blob/3.4/develop/cachedrivers.php.ini#L2) using `phpenv config-add` and Travis manual says it's available. Should we revert to the legacy infrastructure?

**Comment by BanzaiMan** [comment] 2016-01-21 14:23
@enov Well, looking back at the logs, it is not clear to me why "apc" is not compiled for the new archives. Please open a separate issue to track that. Thanks.

**Comment by enov** [comment] 2016-01-22 10:11
@BanzaiMan, turned out that the issue was there since [the day](https://travis-ci.org/kohana/cache/jobs/37645667) we enabled APC on Travis.

Those tests being skipped, it did not catch our attention. Now that some tests are running on separate process, the warnings are being bubbled up to the main process, breaking the build.

Looking around, I see that both [Symfony](https://github.com/symfony/symfony/blob/master/.travis.yml#L39) and [Zend](https://github.com/zendframework/zend-cache/blob/master/.travis.yml#L66) are installing APC from PECL. So I might as well go that way.

I'll open an issue here if the road's still bumpy. Thanks :)

**Comment by ovedanner** [comment] 2016-02-09 15:00
We appear to have the same problem only with PHP 5.5,  `phpenv config-add` and `apc.so`. We get the following output: `Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.5.21/lib/php/extensions/no-debug-zts-20121212/apc.so' - /home/travis/.phpenv/versions/5.5.21/lib/php/extensions/no-debug-zts-20121212/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0`

**Comment by BanzaiMan** [comment] 2016-02-10 03:48
@ovedanner Could you open a new ticket, indicating a build log URL that shows the problem? Thanks.

**Comment by lion5893** [comment] 2017-09-06 02:28
How to use https://docs.travis-ci.com/user/languages/php#PHP-extensions, i don't have phpenv. Please help me, I install mongodb driver on centos 6.5. But when i insert extension=mongo.so to php.ini, i checked php -v:

> Unable to load dynamic library '/usr/lib64/php/modules/mongo.so' - /usr/lib64/php/modules/mongo.so: undefined symbol: php_mongo_asn1_time_to_time_t in Unknown on line 0

I can't connect mongodb. Plesae help me.
