### ISSUE TITLE
Getting error on deploy to Pypi even if packages is released

### ISSUE THREAD

**Issue by pdonorio** [travis-ci/travis-ci#10242] opened 2018-10-15 15:58 UTC
Hello there,
we currently setup [deploy with travis](https://github.com/proof-media/rchain-grpc/blob/master/.travis.yml#L24) in our new repo.

As you can see I followed the instruction to encrypt the password for deploy to Python Pypi packaging system.

I'm not sure why I get always error even if the password is correct (tried maaaany times and also changed the password a couple of times):
https://travis-ci.com/proof-media/rchain-grpc/builds/87980544#L995

And what's even more weird is that it seems the package was also released correctly:
https://pypi.org/project/rchain-grpc/0.0.9/

(I know because I didn't manually do it and the release happened right after that test)

Would any one help understand if I have some misconfiguration?

**Comment by BanzaiMan** [comment] 2018-10-16 02:52
Looks like a duplicate of #10056. Let us know if you feel otherwise.

**Closed by BanzaiMan** 2018-10-16 02:52 UTC
