### ISSUE TITLE
Upgrade preinstalled version of yarn

### ISSUE THREAD

**Issue by dunnock** [travis-ci/travis-ci#7566] opened 2017-04-04 12:30 UTC
Build which uses yarn and docker is running on old version of yarn:
```
$ yarn --version
0.17.8
```
which has issues supporting private git repositories, for example (see https://github.com/yarnpkg/yarn/issues/2117):
```
$ yarn upgrade git://github.com/comaeio/skylab.git#v1.0.3
yarn upgrade v0.17.8
[1/4] Resolving packages...
error Refusing to download the git repo git://github.com/comaeio/skylab.git over plain git without a commit hash
```

**Comment by BanzaiMan** [comment] 2017-04-04 13:30
I don't think any of our container images have `yarn` pre-installed yet. Do you have an example of this issue?

**Comment by dunnock** [comment] 2017-04-04 13:43
It is in private repo https://travis-ci.com/comaeio/galileo/builds/43026501. According to the docs  yarn is preinstalled https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn. I'm not sure if I use container image, I have docker as a service:

```
language: node_js
node_js:
- '7'
services:
- mongodb
- docker
- rabbitmq
```

**Comment by BanzaiMan** [comment] 2017-04-04 15:19
I apologize. I'm not sure how I got the impression that you were talking about the containers. You are right. This is one instance where `yarn` is pre-installed.

**Comment by dunnock** [comment] 2017-04-04 15:42
@BanzaiMan thanks, I think because I mentioned docker in original message, because I was not sure if it has any impact.

**Comment by evan-scott-zocdoc** [comment] 2017-04-12 21:14
There's a lot of important stuff in the versions since 0.17.x, would be excellent to get this upgraded. https://github.com/yarnpkg/yarn/releases

**Comment by vaidas-lungis** [comment] 2017-04-22 22:07
it is a duplicate of issue #7471, isn't it? and solution is this comment  https://github.com/travis-ci/travis-ci/issues/7471#issuecomment-288832948

**Comment by dunnock** [comment] 2017-04-23 07:18
No, it is not, this issue is about base travis configuration with yarn does not support installation of dependencies from private git repos which is supposed yo be supported by travis, due to yarnpkg/yarn#2117

**Comment by rodet** [comment] 2017-05-18 12:03
Yes it would be cool to have an update. In enterprise environments we have quite some private or scoped packages, and people give up on Yarn because of that. I think at least version 0.23 would be good.

**Comment by keradus** [comment] 2017-07-20 15:03
any chances of an update? it's getter older and older...

**Comment by mmcgahan** [comment] 2017-08-03 23:38
Sort of tangential, but this issue prevents [lerna](https://github.com/lerna/lerna) from being used with yarn in the base Travis config - it now uses the `--non-interactive` flag that will throw an error in old versions of `yarn`.

Seems like it should be a simple update, and would make Travis easier to work with.

**Comment by edmorley** [comment] 2017-08-04 00:00
The pre-installed yarn for Ubuntu Trusty images was updated to 0.27.5 in travis-ci/travis-cookbooks#866.

**Comment by jmquigley** [comment] 2017-08-06 03:22
I just ran a build with a new project using "Trusty" and it used yarn 0.17.8.  It also didn't use the newer version that I tried to install (as part of "before_install").  This works in "Precise", as I downgraded my configuration to use "Precise" to make it work.  You can see that failed build below:

https://travis-ci.org/jmquigley/util.keys/builds/261440896

The next build shows that it works after downgrading (and it uses my new install of yarn).

https://travis-ci.org/jmquigley/util.keys/builds/261444828

**Comment by edmorley** [comment] 2017-08-06 16:19
Huh strange - perhaps there are multiple versions of yarn pre-installed and this is a PATH issue? @meatballhat any ideas?

**Comment by evan-scott-zocdoc** [comment] 2017-08-07 22:26
It's also using 0.17.8 on our images. Frustrating.

**Comment by rally25rs** [comment] 2017-08-14 20:18
There isn't much point in having Travis auto-detect `yarn.lock` and pre-install Yarn for you if it will never be updated to the latest version. Having to add a `pre_install` section to upgrade it myself means I might as well not have the pre-installed Yarn. Now it's just slowing down my build by having to install Yarn twice.
It would be great if we could specify Yarn version in the `.travis.yml` file like Node, something like:

```
node_js:
  - "8"
yarn:
  - "0.27.5"
```

**Comment by keradus** [comment] 2017-08-14 21:33
either newest, either none
having field to specify version is overkill imo

**Comment by andvgal** [comment] 2017-08-21 20:41
Another problem with old yarn bug:
```
/usr/local/bin/yarn install --production=false
error `install` has been replaced with `add` to add new dependencies. Run "yarn add false" instead.
```

**Comment by Lyoness** [comment] 2017-08-22 20:11
[Latest stable yarn was merged](https://github.com/travis-ci/travis-cookbooks/blob/master/cookbooks/travis_build_environment/attributes/default.rb#L266) is available on our sudo: required `group: edge` images.  We're promoting these to stable next week.

**Comment by Kerrick** [comment] 2017-09-06 18:29
@Lyoness How exactly do we opt into the latest stable yarn, now that "next week" has passed?

**Comment by jmquigley** [comment] 2017-09-08 18:24
I finally got this to work.  This is my travis config:

```
language: node_js
dist: trusty
cache: yarn
sudo: required

node_js:
    - '7'

before_install:
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.0'
    - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
    - 'yarn run clean && yarn run lint && yarn run build'

after_success:
    - 'yarn run coverage'
```

The part that solved my problem was the path export in the `before_install` hook.  That wasn't needed in the precise build (because it was upgrading yarn in precise and working without the path change).

https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn

I don't know when the PATH statement became required, but I know at one point it wasn't there because my old config worked without it.  Hope that helps anyone else that is having the issue.

**Comment by BanzaiMan** [comment] 2017-09-08 19:57
The latest Trusty image update includes `yarn` 0.27.5 pre-installed. Some Docker hosts are still hanging on to older ones, unfortunately, so you might see older versions popping up occasionally.

**Comment by mike360** [comment] 2017-09-29 20:37
With Yarn 1.x now available this is becoming more and more relevant. For instance, command switches are passed to the underlying npm script without having to use the `--` operator. (e.g. `yarn test --coverage` over `yarn test -- --coverage`)

**Comment by keradus** [comment] 2017-09-30 10:01
yeah, IMO upgrading preinstalled yarn to 1.x is must have !

**Comment by BanzaiMan** [comment] 2017-09-30 14:38
It seems to me keeping up with rapid release cycles is problematic.

**Comment by keradus** [comment] 2017-10-01 08:41
then maybe follow my suggestion: https://github.com/travis-ci/travis-ci/issues/7566#issuecomment-322315959 ?

if Travis cannot afford to update tools (whichever they are) and will provide extra outdated one, then for end-user it's extra problematic, as "tool is there, but doesn't work!", after time wasted for debugging - "oh, it's too old, I need to install it manually anyway"

**Comment by BanzaiMan** [comment] 2017-10-01 09:44
Right now, we prefer the pre-installed `yarn` to ensuring the latest version. If the user community’s preference is the latter, it is straightforward to switch to it. I tend to think the risk of breaking builds is low.

**Comment by blimmer** [comment] 2017-10-01 19:30
I really like the idea of being able to provide a version number for yarn or, better yet, "latest" would be great. It's hard to keep up with how fast they're moving, but I pretty much always want the newest, with the option to pin to a specific version in case there's some kind of problem.

**Comment by keradus** [comment] 2017-10-01 22:55
and for now, we continuously run into "yarn too old" issue

**Comment by tdmalone** [comment] 2017-10-14 11:59
This should ensure the latest version of Yarn is always available, without needing to pin to a specific version and keep that up-to-date:
```
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
```

You might also need to install another version of Node, if Yarn tells you it doesn't support what's currently there.

**Comment by keradus** [comment] 2017-10-14 12:30
@tdmalone , that's whay I saying, Travis shall either provide newest version, or it no version at all (as users will have to manually install yarn themselves, as you stated)

**Comment by edmorley** [comment] 2017-10-17 16:01
@BanzaiMan, what do you think of the idea of updating travis-cookbooks to always install the latest version of yarn, rather than pinning to a specific version? That way the latest releases are constantly tested on `group: edge` and then each time a new `group: stable` release is cut there will have been enough time to check the latest release works as expected?

**Comment by BanzaiMan** [comment] 2017-10-17 19:50
@edmorley I think that would be a worthy discussion to have in https://github.com/travis-ci/travis-cookbooks/issues. It may be the case, though, Ark (https://github.com/travis-ci/travis-cookbooks/blob/master/cookbooks/travis_build_environment/recipes/yarn.rb) needs the checksum to verify the validity of the archive when installing. (Of this, I am uncertain.)

**Comment by edmorley** [comment] 2017-11-16 23:17
In travis-ci/travis-cookbooks#935, I changed the image building process to always install the latest version of yarn available at the time the image was built, which means:
(a) there's now no chance to forget to bump the pre-installed yarn version when each new quarterly `group: stable` image is released (I believe there should be a new stable release soon, but you'd have to ask a Travis employee for what the plan is there), 
(b) those who using `group: edge` will always have a fairly up to date yarn (edge is roughly travis-ci/travis-cookbooks and travis-ci/packer-templates master, so long as the required travis-ci/packer-templates files have been bumped to generate a new image). Only use if you're prepared to adapt as things change/break.

As such I think this can now be closed :-)

**Comment by edmorley** [comment] 2017-11-16 23:22
But also note: `group: edge` only has an effect on the GCE infra (`sudo: required`), the docker builds can only use the stable images.

**Comment by BanzaiMan** [comment] 2017-12-13 20:37
A new version of `yarn` should now be available on all our images.

While I emphasize with the "always give me the latest version" sentiment (https://github.com/travis-ci/travis-ci/issues/7566#issuecomment-336632044) and we do our best, we cannot possibly ensure this for fast moving projects. If you absolutely need the latest and the greatest in every build, please ensure that happens with your build.

I'm closing this now.

**Closed by BanzaiMan** 2017-12-13 20:37 UTC
Labels: node.js, upgrade-request

**Comment by tdmalone** [comment] 2017-12-13 23:40
Looks like we still need to put Yarn's bin the PATH if installing global binaries:

```
before_install:

  # Ensure installed Yarn binaries are in the PATH.
  - export PATH="$HOME/.yarn/bin:$PATH"
```

**Comment by keradus** [comment] 2017-12-14 00:39
if installing by Travis our ourselves ?
if by Travis, I don't need to do it on my builds

**Comment by BanzaiMan** [comment] 2017-12-14 02:02
@tdmalone That is addressed in https://github.com/travis-ci/travis-ci/issues/8890#issuecomment-351188669

**Comment by tdmalone** [comment] 2017-12-14 23:42
Thanks, and just to cross-post the update here in case others come across it, it's now fixed as per https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-351395853

**Comment by vvo** [comment] 2017-12-16 16:46
Netlify has an env variable of YARN_VERSION that could greatly solve this issue. What do you think?

https://www.netlify.com/blog/2016/11/01/yarn-support-on-netlify/
