### ISSUE TITLE
Accidentally unsubscribed from e-mail build notifications, can't subscribe back

### ISSUE THREAD

**Issue by VioletGiraffe** [travis-ci/travis-ci#9972] opened 2018-08-10 07:11 UTC
I can't find a way to subscribe back to the e-mail build status notifications. How can I do that?
To top it off, the links " changing the email address" and "troubleshooting email notification" are dead on [this Help page](https://docs.travis-ci.com/user/notifications/).

**Comment by BanzaiMan** [comment] 2018-09-29 03:46
Build status notifications are explained in https://docs.travis-ci.com/user/notifications/#configuring-email-notifications. You might also want to read on the email recipients, which is described here: https://docs.travis-ci.com/user/notifications/#how-is-the-build-email-receiver-determined

**Comment by VioletGiraffe** [comment] 2018-09-29 05:34
@BanzaiMan, thanks, but that's not it. I never had any notifications configured in the .yml, and I don't want to add it now. Travis sends e-mail notifications by default, so it know how to do it even without special instructions in the .yml. Is there no way to restore notifications from the web interface?

**Comment by BanzaiMan** [comment] 2018-09-29 12:10
How did you unsubscribe?

**Comment by VioletGiraffe** [comment] 2018-09-29 15:17
@BanzaiMan, by clicking "unsubscribe" in Gmail.

**Comment by BanzaiMan** [comment] 2018-10-01 12:56
@VioletGiraffe Thanks for the feedback. Please email us at support@travis-ci.com, so we can take a look. In the mean time, I'm closing this as a duplicate of #9390.

**Closed by BanzaiMan** 2018-10-01 12:56 UTC
