### ISSUE TITLE
Chrome failing to start, running headless after the upgrade to 63

### ISSUE THREAD

**Issue by jenlindner** [travis-ci/travis-ci#9034] opened 2018-01-10 18:17 UTC
This issue has come up before, google searches show it seems to be a perennial, occasional problem. I'm seeing it in builds that had previously been passing, and in this one, where I tried to use the pre-upgrade version of chrome, from snaps. I've tried a variety of fixes suggested: sudo privileged, --no-sandbox, --disable-setuid-sandbox and so far none of them have worked. Please help? We really want to use this driver.

current build:
https://travis-ci.org/curationexperts/mahonia/builds/327327253

build that had been previously passing:
https://travis-ci.org/curationexperts/mahonia/builds/326427115

**Comment by BanzaiMan** [comment] 2018-01-10 18:30
Duplicate of #8836.

**Closed by BanzaiMan** 2018-01-10 18:30 UTC
