### ISSUE TITLE
Creating $TRAVIS_DEPLOY_RESULT to test the deployment result

### ISSUE THREAD

**Issue by jeanEpek** [travis-ci/travis-ci#2521] opened 2014-07-12 19:35 UTC
Sometimes and depending of the platform, the deployment fails and there is generally a way of testing it at the shell level. 

In the same spirit than $TRAVIS_TEST_RESULT, it would be great to have $TRAVIS_DEPLOY_RESULT (or equivalent) automatically populated in the after_deploy: section, in order to create subsequent tasks conditionally to the success of the deployment. For example, we could notify differently depending on the success of the deployment. We could also run some additional tests uniquely if the deployment was successful.

One could even wonder of the possibility of having an after_deploy_success and after_deploy_failure section, or the after_deploy section running only if there is a successful deployment, with a notification in case of failure.

**Comment by TomasTomecek** [comment] 2016-01-04 07:39
Coming here from #5393. 

How is it even possible not to test result of deploy by design? Can at least be something done in deploy hook? 

Big plus one to this rfe.

**Comment by BanzaiMan** [comment] 2016-01-12 06:53
I'm closing this as a duplicate of #1574. @TomasTomecek Sorry for the roundabout!

**Closed by BanzaiMan** 2016-01-12 06:53 UTC
Labels: feature-request, travis-build
