### ISSUE TITLE
Gems with native extensions failing to compile on containerized Ruby 2.1.8 build

### ISSUE THREAD

**Issue by derekprior** [travis-ci/travis-ci#5580] opened 2016-02-05 21:41 UTC
I have a project that tests several gemfiles against several rubies. All of the tests under 2.1.8 are failing building various native extensions. Sometimes it's Postgres that gets complained about, other times it's json or redcarpet. I am unable to check the `mkmf.log` file for more details as instructed.

You can see an example of the failing builds and the many error messages here: https://travis-ci.org/thoughtbot/scenic/jobs/107329280

You'll notice that it seems to be different native extensions in different install attempts. I'm not sure how to debug from my side except to add that I've also seen #4707 in the pg errors made me think that perhaps it's related?

**Comment by tkrajcar** [comment] 2016-02-05 21:54
Boy, am I glad you posted this and confirmed we're not going crazy :) We are also seeing this issue, albeit in a Travis Enterprise context so I can't post any links. We run hundreds of jobs daily across different Rubies and all of our 2.1.8 jobs started failing to install native dependencies today.

**Comment by BanzaiMan** [comment] 2016-02-05 22:04
Interesting. We did rebuild the 2.1.8 archive about 5 hours ago, and the last passing build on thoughtbot/scenic is a bit before that https://travis-ci.org/thoughtbot/scenic/jobs/107250108#L156

Does the build succeed with other Ruby 2.1.x versions?

**Comment by BanzaiMan** [comment] 2016-02-05 22:08
The repackaging did not alter the process, so I'd be a bit surprised if that triggered this problem.

**Comment by RUN-CMD** [comment] 2016-02-05 22:08
Our builds that began failing today with 2.1.8 pass with 2.1.7.

**Comment by segiddins** [comment] 2016-02-05 22:09
The same thing started happening with bundler within the past day: https://travis-ci.org/bundler/bundler/jobs/107298292

**Comment by BanzaiMan** [comment] 2016-02-05 23:22
To confirm, is the issue confined to 2.1.8 and native extensions?

**Comment by duncaan** [comment] 2016-02-05 23:35
I was getting this locally too with rvm 2.1.8 and solved it by building from source with the --disable-binary flag so headers were included.

**Comment by BanzaiMan** [comment] 2016-02-05 23:39
https://travis-ci.org/bundler/bundler/jobs/107298292#L417 and https://travis-ci.org/enriclluelles/route_translator/jobs/107319081#L185 show failure to build extensions on some functions that we expect to find everywhere (`random()` in the former, `main()` in the latter).

**Comment by BanzaiMan** [comment] 2016-02-05 23:40
The issue with `main()` was also reported in https://github.com/travis-ci/travis-ci/issues/5552.

**Comment by agrobbin** [comment] 2016-02-07 17:32
I've been seeing the same issues on a gem that is tested against a variety of Ruby versions. The issues are limited to [only Ruby 2.1.8](https://travis-ci.org/agrobbin/spritely/jobs/107356844), specifically when building:

* json 1.8.3
* byebug 8.2.2
* nokogiri 1.6.7.2

**Comment by BanzaiMan** [comment] 2016-02-08 21:15
Hello. I've repackaged 2.1.8, and my test installing `rdiscount` was successful. Could you try it? (You can either push a new commit, or re-run the previously failing build if it specified `2.1.8`.)

**Comment by agrobbin** [comment] 2016-02-08 21:53
@BanzaiMan success! Thanks so much for jumping on this so quickly.

**Comment by tagliala** [comment] 2016-02-08 22:35
@BanzaiMan it works for me, too. Thanks!

**Comment by BanzaiMan** [comment] 2016-02-08 23:26
Thanks for the reports. I'm closing this now.

**Closed by BanzaiMan** 2016-02-08 23:26 UTC
Labels: ruby
