### ISSUE TITLE
Conditional package installs via APT add-on

### ISSUE THREAD

**Issue by dregad** [travis-ci/travis-ci#5357] opened 2015-12-23 15:18 UTC
Greetings,

I was playing with the new APT addon in .travis.yml as an alternative to sudo apt-get install which I've been using so far.

I was wondering if there is (or will be) an option to conditionally install packages only when they will actually be needed (e.g. based on evaluation of environment variables).

The reason for my request is that we have different types of build depending on circumstances, some of them need specific packages that others do not. For example
- our Documentation builds rely on *publican*, but it's only necessary to run it once, not for every PHP/database back-end combination
- PHP 5.3 tests require a web server, so we currently install Apache, but that's not needed for PHP >= 5.4 as we can use the built-in one

Here is our [.travis.yml file for reference](https://github.com/mantisbt/mantisbt/blob/master/.travis.yml).

Thanks in advance for your reply.

**Comment by BanzaiMan** [comment] 2015-12-23 15:34
I think this is a duplicate of #5338.

**Comment by dregad** [comment] 2015-12-23 15:52
I saw that one before posting mine, but did not realize that the notion of "whitelisting" packages meant that packages should be conditionally installed. If you feel this is indeed the same request, then feel free to close it as duplicate.

**Comment by dregad** [comment] 2015-12-23 15:55
For the record, I'm not using the container-based infra.

**Comment by BanzaiMan** [comment] 2015-12-23 16:05
Conditional APT package installation via the addon has been asked before (prior to #5338, even, but I couldn't find it).

While it is possible to put it together via build matrix (https://travis-ci.org/BanzaiMan/travis_production_test/builds/98538274; https://github.com/BanzaiMan/travis_production_test/blob/f3fa07db674b979f29fd0025d39ea82b0858d6b6/.travis.yml#L5-L20) it is far from elegant.

**Closed** 2015-12-24 03:52 UTC
