### ISSUE TITLE
Trusty Python version mismatches

### ISSUE THREAD

**Issue by julen** [travis-ci/travis-ci#8904] opened 2017-12-13 12:51 UTC
Ever since the new VMs have been available our builds started to get random failures when running Python stuff ([example build](https://travis-ci.org/evernote/zing/jobs/315863745)).

The following snippet is quite puzzling, given that 3 (three!) different Python versions are mentioned:
```
$ python --version
Python 2.7.6
$ pip --version
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/pip", line 7, in <module>
    from pip import main
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/__init__.py", line 2, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

According to the latest [build environment update](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/), we'd expect the 2.7.14 version to be used.

**Comment by BanzaiMan** [comment] 2017-12-13 14:23
With the default configuration, it should. https://travis-ci.org/BanzaiMan/travis_production_test/builds/315907329#L406

This build used an older image: https://travis-ci.org/evernote/zing/jobs/315863745#L15 Perhaps that is the cause of the issue. Could you try pushing a new commit to this PR?

**Comment by julen** [comment] 2017-12-13 15:21
I pushed commits multiple times and in different PRs, and also manually cleared caches. I removed some problematic lines from our configuration.

I'm still seeing the previous Python version being reported:
```
$ python --version
Python 2.7.13
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages (python 2.7)
```

**Comment by julen** [comment] 2017-12-13 15:32
Now I get the new VM + Python version. It'd seem like it's been randomly picking one over the other 🤔.

**Comment by BanzaiMan** [comment] 2017-12-13 16:08
I am guessing that EC2 hosts are being replaced with newer images; if your job is picked up by an old one, it fails. I'll see what we can do to force old ones to go out of service faster.

**Comment by julen** [comment] 2017-12-13 16:41
Thanks for checking upon this! that explanation makes sense 👍

**Comment by trun** [comment] 2017-12-14 16:20
We are seeing the same error with python 2.7.14 on a newer host.

```
Build language: node_js
Build group: deprecated-2017Q4
Build dist: trusty
Build id: 61644487
Job id: 102887793
Runtime kernel version: 4.9.6-040906-generic
travis-build version: 724aa1721
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

Oddly it only seems to happen in our created virtualenv, but the system python is fine (if i re-run the build in debug mode this is easy to verify). Any other thoughts on what the root cause might be?

**Comment by BanzaiMan** [comment] 2017-12-14 16:37
@trun 
Do you have a build log URL that shows the problem you are describing here?

**Comment by trun** [comment] 2017-12-14 16:39
@BanzaiMan It's in a private repo so I'm not sure you'd be able to access it?

**Comment by BanzaiMan** [comment] 2017-12-15 02:02
I can. Or, if you'd rather not discuss it in public, please close this issue and email us at support@travis-ci.com, please.

**Comment by trun** [comment] 2017-12-15 15:43
A cache clear actually got us past this issue. Must have just been a cached venv from an old image.

**Comment by BanzaiMan** [comment] 2017-12-15 15:52
I think this can be closed now. Let us know if it resurfaces.

**Closed by BanzaiMan** 2017-12-15 15:52 UTC
Labels: 2017-Q4-trusty-env-update
