### ISSUE TITLE
Getting "bundler: failed to load command: rake" after upgrading to ruby 2.5.0

### ISSUE THREAD

**Issue by jasnow** [travis-ci/travis-ci#8978] opened 2017-12-27 00:39 UTC
This is error message after upgrading to ruby 2.5.0. Happened on 3 different repos.
```
bundler: failed to load command: rake (/home/travis/build/atlrug/atlrug/vendor/bundle/ruby/2.5.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
```
Last green build (before ruby 2.5.0 upgrade) was https://travis-ci.org/atlrug/atlrug/builds/321407642
Thanks

**Comment by alexgenco** [comment] 2017-12-27 01:44
I'm getting this error as well: https://travis-ci.org/alexgenco/neovim-ruby/jobs/321858012. Just wanted to add that uninstalling `rake` before `bundle install` fixed the problem. e.g.:

```
before_install:
  - bash -c "yes | gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.0@global rake"
```

This build passed using this approach: https://travis-ci.org/alexgenco/neovim-ruby/jobs/321857517.

**Comment by y-yagi** [comment] 2017-12-27 01:56
This occurs with the combination of Bundler 1.16.1 and rubygems 2.7.3. 
Since this problem has been addressed in rubygems 2.7.4, execute `gem update --system` in `before_install` should fix an error. 

Ref: https://github.com/rubygems/rubygems/issues/2123

**Comment by BanzaiMan** [comment] 2017-12-27 15:04
We'll update the 2.5 archives once the upstream fix is released.

**Comment by BanzaiMan** [comment] 2017-12-27 16:49
Perhaps a duplicate of #8969?

**Comment by BanzaiMan** [comment] 2017-12-27 19:33
Closing as a duplicate.

**Closed by BanzaiMan** 2017-12-27 19:33 UTC
Labels: ruby

**Comment by kolen** [comment] 2018-03-01 22:30
Now it happens on 2.6 HEAD version, I can't reproduce it locally
https://travis-ci.org/vmg/redcarpet/jobs/347241663

**Comment by SuperSandro2000** [comment] 2018-03-31 09:34
Just want to drop that here for other people experiencing this issue:
````
before_install:
  - gem install bundler
````

**Comment by ssaunier** [comment] 2018-04-01 09:19
@SuperSandro2000 Are you using Ruby 2.5.0 or 2.5.1? It seems it's failing with the 2.5.1 which was [released 3 days ago](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/)

**Comment by SuperSandro2000** [comment] 2018-04-01 10:20
@ssaunier I use Ruby 2.5.1 indeed. In the rvm section I specified only ruby 2.5 so it auto updated.

**Comment by loed-idzinga** [comment] 2018-04-01 21:37
@SuperSandro2000 That solved it indeed, thanks! 👍 

Also running Ruby 2.5.1, but it was also happening on Ruby 2.4.4, so guess that all newly released versions are affected by this.

**Comment by ioquatix** [comment] 2018-04-08 08:08
This problem seems to have cropped up again with Ruby 2.5.1 even after executing `gem update --system`. What's going on?

**Comment by ioquatix** [comment] 2018-04-08 22:15
Yes that worked.

**Comment by keithrbennett** [comment] 2018-04-16 13:57
According to the Travis build log (https://travis-ci.org/alexdalitz/dnsruby/jobs/367137602), bundler is already installed and at the current version, 1.16.1; yet we still get that error. What am I missing?
