### ISSUE TITLE
make emails configurable in the user interface

### ISSUE THREAD

**Issue by nschloe** [travis-ci/travis-ci#7411] opened 2017-03-02 08:39 UTC
[I see that emails can be configured per repository](https://docs.travis-ci.com/user/notifications#Configuring-email-notifications). Since I don't want any emails at all (as I check the status live on the page), I'll have to add
```yaml
notifications:
  email: false
```
to each an every one of my repos. Also, I cannot turn off emails for me without turning them off for everyone else.

A solution to this dilemma would be to allow for emails to be turned off per user in the user preferences on the travis website.

**Comment by BanzaiMan** [comment] 2017-03-02 13:18
I'm closing this as a duplicate of #3121. Also, see #1094.

**Closed by BanzaiMan** 2017-03-02 13:18 UTC
