### ISSUE TITLE
Build Jobs are 'Waiting to be queued' since morning

### ISSUE THREAD

**Issue by cheenamalhotra** [travis-ci/travis-ci#9228] opened 2018-02-15 23:55 UTC
We have been trying to run a number of builds lately, but they're all 'Waiting to be queued'..
https://travis-ci.org/Microsoft/mssql-jdbc/pull_requests

Are there not enough agents to pick up build jobs?

**Comment by BanzaiMan** [comment] 2018-02-16 09:17
This was most likely in part caused by this build processing issue: https://www.traviscistatus.com/incidents/t68jk6rj92q4. Please keep in mind, though, that Microsoft is a large organization with numerous repositories and many build requests; this can be a cause of delay during the work day.

The builds in question have now been processed, and there shouldn't be any build processing issue at this point. I'm closing this.

**Closed by BanzaiMan** 2018-02-16 09:17 UTC
