### ISSUE TITLE
pypy binaries list

### ISSUE THREAD

**Issue by Suor** [travis-ci/travis-ci#7890] opened 2017-06-11 11:50 UTC
Now and guess, try and error game to find how you should specify pypy versions and whether they exist in first place. Also, shortcuts would help, like `pypy-5.7` expanding to `pypy-5.7.1-beta`.

**Comment by BanzaiMan** [comment] 2017-06-11 13:09
Duplicate of #6865.

**Closed by BanzaiMan** 2017-06-11 13:09 UTC

**Comment by Suor** [comment] 2017-06-11 14:35
Looks more like dup of #7822.
