### ISSUE TITLE
Feature request: disable building tags

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8663] opened 2017-10-28 20:29 UTC
When I produce a tag, it's always at a pushed commit, so that commit ends up being built twice. It'd be nice if I could turn off builds for tags, while keeping them enabled for other kinds of branches.

**Comment by BanzaiMan** [comment] 2017-10-28 20:37
I'm closing this as a duplicate of #1532.

**Closed by BanzaiMan** 2017-10-28 20:37 UTC
