### ISSUE TITLE
gnutls_handshake() failed: A TLS fatal alert has been received.

### ISSUE THREAD

**Issue by dewittpe** [travis-ci/travis-ci#6883] opened 2016-11-16 16:18 UTC
Similar to #6881 and #6882.

When trying to build an R package the following error occurred:

```
$ sudo apt-get update -qq
W: Failed to fetch https://cloud.r-project.org/bin/linux/ubuntu/precise/Sources  gnutls_handshake() failed: A TLS fatal alert has been received.
```

A full log of the build attempt and configuration files are [here](https://travis-ci.org/dewittpe/qwraps2/jobs/176393986). 

Mentioning  @craigcitro, @hadley, and @jimhester as requested for R on Travis-CI.

**Comment by BanzaiMan** [comment] 2016-11-16 16:18
Thanks for taking time to open this issue, but I'm resolving this as a duplicate of #6882. I don't think we need separate issue for affected languages.

**Closed by BanzaiMan** 2016-11-16 16:18 UTC
