### ISSUE TITLE
Travis-ci can not detect whether the test has finished.

### ISSUE THREAD

**Issue by yunnysunny** [travis-ci/travis-ci#9060] opened 2018-01-13 04:47 UTC
I have a node.js project [queue-schedule](https://github.com/yunnysunny/queue-schedule), which uses `npm test` for default travis-ci  script.
But I found travis-ci can not detect the status of test now. I found the testcase's output as follows:
```
The command "npm test" exited with 0.
cache.2
store build cache
0.01s
7.79schange detected (content changed, file is created, or file is deleted):
/home/travis/build/e174596549/queue-schedule/kafka/logs/controller.log
/home/travis/build/e174596549/queue-schedule/kafka/logs/controller.log.2018-01-10-09
/home/travis/build/e174596549/queue-schedule/kafka/logs/kafkaServer-gc.log.0.current
/home/travis/build/e174596549/queue-schedule/kafka/logs/log-cleaner.log
/home/travis/build/e174596549/queue-schedule/kafka/logs/log-cleaner.log.2018-01-10-09
/home/travis/build/e174596549/queue-schedule/kafka/logs/server.log
/home/travis/build/e174596549/queue-schedule/kafka/logs/server.log.2018-01-10-09
/home/travis/build/e174596549/queue-schedule/kafka/logs/state-change.log
/home/travis/build/e174596549/queue-schedule/kafka/logs/state-change.log.2018-01-10-09
changes detected, packing new archive
uploading archive
Done. Your build exited with 0.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
The test has run finished with no error, but travis-ci think it was still running.

**Comment by BanzaiMan** [comment] 2018-01-16 15:03
Duplicate of either #8898 or #8082.

**Closed by BanzaiMan** 2018-01-16 15:03 UTC
