### ISSUE TITLE
"missing config" error when config is not missing (fails silently)

### ISSUE THREAD

**Issue by mholt** [travis-ci/travis-ci#5823] opened 2016-03-26 15:22 UTC
Build failed to run and reported this error: "missing config" even though config file exists. [Relevant commit](https://github.com/mholt/caddy/commit/eb279e7)

And yes, I know there's a YAML syntax error in the change, but the error message is wrong. Even more severe, though, is that the error is silent: all systems show tests passing, no email notifications either.

(Related: #2025 but locked with no comment, unfortunately.)

**Comment by BanzaiMan** [comment] 2016-03-27 09:49
This is a duplicate of #2025. I locked it because it was attracting :+1:'s without meaningful comment. The error is somewhat hidden, but you can see this in https://travis-ci.org/mholt/caddy/requests (until it is moved off the recent history).

We will update the other issue when we have updates to share.

Thanks.

**Closed by BanzaiMan** 2016-03-27 09:49 UTC
