### ISSUE TITLE
Need for newer dist-images

### ISSUE THREAD

**Issue by fnordahl** [travis-ci/travis-ci#6101] opened 2016-05-24 17:37 UTC
The dist:trusty is aging.

There is a growing need for a updated image with more recent kernels and more recent userspace being available.

For our specific need we cannot use containers to get a newer userland, we rely on more recent kernel functionality to perform our functional tests.

You can find an example of this need here: containernetworking/cni#210

**Comment by BanzaiMan** [comment] 2016-05-24 20:42
Closing as a duplicate of #5821. For the near future, our goal is to provide stable support for Trusty.

Thank you for your understanding.

**Closed by BanzaiMan** 2016-05-24 20:42 UTC
