### ISSUE TITLE
Xcode7 images don't have pip or virtualenv while the default OSX images do

### ISSUE THREAD

**Issue by glandium** [travis-ci/travis-ci#5523] opened 2016-01-28 07:24 UTC
Trying to use `pip` or `virtualenv` fails in xcode7 osx_images, while it works in the default osx image.

**Comment by BanzaiMan** [comment] 2016-02-03 21:28
We do not support Python on Mac at this time. Closing as a duplicate of #2312.

**Comment by glandium** [comment] 2016-02-03 23:07
language: python might not work (haven't tried), but python, pip and virtualenv *are* available on the default OSX image and can thus be used for scripts for e.g. language: c projects.

**Comment by BanzaiMan** [comment] 2016-02-04 00:10
Could you provide a build log URL that shows this problem? Thanks.

**Comment by glandium** [comment] 2016-02-12 09:53
Sorry for the delay. Here is one such log:
https://travis-ci.org/glandium/git-cinnabar/jobs/105371455

And another log on the same commit with the default OSX image:
https://travis-ci.org/glandium/git-cinnabar/jobs/105371453

**Comment by solojavier** [comment] 2016-07-08 23:53
@BanzaiMan What would be required to move this forward? Seems like the log provided by @glandium shows the problem. Is it a duplicate of #2312 ?

**Comment by BanzaiMan** [comment] 2016-07-09 02:06
@glandium I think the different behaviors in your two jobs comes probably from different OS X images. We do not provide full Python support (including virtualenv and other common Python tools) on the Mac at this time.

When we do provide it, we would need to make sure that common tools are functioning properly.

**Closed by BanzaiMan** 2016-07-09 02:06 UTC
Labels: team blue
