### ISSUE TITLE
CI Builds failing for Oracle Java 10 on Linux since yesterday

### ISSUE THREAD

**Issue by cheenamalhotra** [travis-ci/travis-ci#10263] opened 2018-10-18 18:51 UTC
Sample failing build with trace logs: https://travis-ci.org/Microsoft/mssql-jdbc/builds/442814245

CI build with **jdk: oraclejdk10** is not working on Linux OS (Ubuntu) since yesterday.

Command executed: `bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk`

Please suggest if this requires any changes in yml file, or when will this be fixed so we can proceed further.

**Comment by cotsog** [comment] 2018-10-18 19:01
Duplicate of #10249.

**Closed by cotsog** 2018-10-18 19:01 UTC
