### ISSUE TITLE
Travis fails to report status to GitHub

### ISSUE THREAD

**Issue by mgedmin** [travis-ci/travis-ci#5901] opened 2016-04-14 06:07 UTC
Here's a a pull request: https://github.com/gtimelog/gtimelog/pull/88

Here are the Travis builds for that pull request: https://travis-ci.org/gtimelog/gtimelog/pull_requests

Here are the Travis builds for the branch that corresponds to that pull request (`filtering`): https://travis-ci.org/gtimelog/gtimelog/branches

You can see that the builds exist and have succeeded, but GitHub is still "Waiting for status to be reported" for continuous-integration/travis-ci.

The problem is long-lasting: I first created the PR almost two weeks ago, and this happened (Travis job ran, didn't report status to GH).  My last push yesterday had the same effect (Travis job ran, didn't report status to GH).

**Comment by BanzaiMan** [comment] 2016-04-14 06:37
The short answer: We don't have the admin user assigned to this repo, and we cannot post results.

The long answer: There have been a few reports of this kind, and we are looking into it.

**Comment by BanzaiMan** [comment] 2016-04-14 07:00
In essence this is a duplicate of #5863.

**Closed by BanzaiMan** 2016-04-14 07:00 UTC
Labels: bug

**Comment by mgedmin** [comment] 2016-04-14 08:17
Thank you for that hint!  Indeed, if I go to https://travis-ci.org/profile/mgedmin, I don't see the 'gtimelog' organisation in the sidebar.  I can click the "review and add" link below it and hit the 'Grant access' button.  I expect that'll fix my problem.

It would be nice if the Travis UI would indicate failures to report to GitHub somewhere on the corresponding build page, with maybe a retry button (like GitHub itself does for webhooks).

**Comment by SkyzohKey** [comment] 2016-04-14 11:49
Same issue with Ricin. :x: 
https://github.com/RicinApp/Ricin/pull/109
