### ISSUE TITLE
gnutls_handshake() failed: A TLS fatal alert has been received on PHP builds

### ISSUE THREAD

**Issue by jenkoian** [travis-ci/travis-ci#7539] opened 2017-03-30 08:23 UTC
I know this is likely a duplicate of https://github.com/travis-ci/travis-ci/issues/6883 (and thus https://github.com/travis-ci/travis-ci/issues/6881 and https://github.com/travis-ci/travis-ci/issues/6882!) but what's strange in my particular case is that it only seems to be affecting the PHP builds. Example:

https://travis-ci.org/jenkoian/flysystem-gaufrette/builds/216655338

Seems to pass on the HHVM build, but same error on all PHP builds.

Just wondering if something has changed with PHP versions on travis, or how PHP uses curl or SSL?

So despite (and perhaps probable) an issue with the security checking service, wouldn't this manifest itself for all builds? I can also run the task in question locally without issue on multiple versions of PHP.

**Comment by jenkoian** [comment] 2017-03-30 08:39
Related: https://github.com/sensiolabs/security-checker/issues/73

**Comment by BanzaiMan** [comment] 2017-03-30 18:09
This is a duplicate of #6339.

**Closed by BanzaiMan** 2017-03-30 18:09 UTC
