### ISSUE TITLE
Cannot install ruby-1.8.7-p371 with rvm

### ISSUE THREAD

**Issue by JasonMannon** [travis-ci/travis-ci#5163] opened 2015-11-24 21:46 UTC
I want to use ruby version `1.8.7-p371` with my build, but rvm is having trouble installing it.  Does anyone know how to get this up and running?
```
$ rvm use 1.8.7-p371 --install --binary --fuzzy
ruby-1.8.7-p371 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-1.8.7-p371 do rvm gemset create ' first, or append '--create'.
```

**Comment by BanzaiMan** [comment] 2015-11-24 21:54
Are you using Trusty? Then this is a duplicate of #4984.

**Comment by JasonMannon** [comment] 2015-11-24 22:18
@BanzaiMan Not using trusty.
```

**Comment by BanzaiMan** [comment] 2015-11-24 22:37
Why is 1.8.7 not pre-installed on a precise image?

**Comment by JasonMannon** [comment] 2015-11-24 23:19
What do you mean by that?  ruby-1.8.7 installs fine, but when I try to use 1.8.7-p371 it's breaking.

**Comment by BanzaiMan** [comment] 2015-11-25 14:09
Can you install it with your local machine?

**Comment by BanzaiMan** [comment] 2015-11-25 14:53
We've built the binary package, so this should be doable on Precise.

**Closed by BanzaiMan** 2015-11-25 14:53 UTC

**Comment by annikoff** [comment] 2019-10-11 13:32
Hi. The same problem again

```yml
#...
matrix:
  include:
    - rvm: 1.8.7
#...
````

```sh
$ rvm use 1.8.7-p371 --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Required ruby-1.8.7-p371 is not installed - installing.
curl: (22) The requested URL returned error: 404 Not Found
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-1.8.7-p371 do rvm gemset create ' first, or append '--create'.
The command "rvm use 1.8.7-p371 --install --binary --fuzzy" failed and exited with 2 during .
```

**Comment by BanzaiMan** [comment] 2019-10-11 14:46
@annikoff Are you really testing against 1.8.7 in 2019? If you are, you need to use Trusty or Precise.

**Comment by annikoff** [comment] 2019-10-14 06:52
@BanzaiMan Thank you, this is not for my project. I'm going to fix builds in one open-source library.
