### ISSUE TITLE
Travis does do after_script commands when cancel the job or timeout

### ISSUE THREAD

**Issue by chenzhiwei** [travis-ci/travis-ci#8448] opened 2017-09-17 03:51 UTC
We use Travis to create some VMs from OpenStack env in `before_script`, and test our build on those VMs in `script`, and then to remove these VMs from `after_script`.

But if we cancel a Travis job or the job timeout, Travis will never run `after_script`.

Is there a way to make Travis always run `after_script` in any of the cases?

**Comment by BanzaiMan** [comment] 2017-09-17 04:09
I believe this is a duplicate of #4221. Let us know if you think otherwise.

**Closed by BanzaiMan** 2017-09-17 04:09 UTC
