### ISSUE TITLE
Cannot install iojs on osx images

### ISSUE THREAD

**Issue by justinmchase** [travis-ci/travis-ci#4155] opened 2015-06-29 14:05 UTC
My yml looks like this:
```
language: node_js
node_js:
  - "iojs-v2.3.1"

os:
  - linux
  - osx
```

And the error I am getting is this:
```
$ nvm install iojs-v2.3.1
/Users/travis/build.sh: line 41: nvm: command not found
The command "nvm install iojs-v2.3.1" failed and exited with 127 during .
Your build has been stopped.
```

How do I get iojs onto osx builds?

**Comment by BanzaiMan** [comment] 2015-06-29 14:10
This is a duplicate of #2311.

**Closed by BanzaiMan** 2015-06-29 14:10 UTC
