### ISSUE TITLE
Build status for PRs overwritten by branch commit build status

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#2977] opened 2014-11-21 15:42 UTC
A customer reports that

> We are having an issue where Github tells us our tests are passing sometimes when a PR fails but the build for the branch passes after the PR build has finished. It seems to me that Github should only show the status of the PR and never the status of an individual branch's test. Is there any way we can fix this?

and

> It is for the GitHub commit status, but not the circles next to the individual commits, I'm referring to the status indicated for the PR, image attached. And your paraphrase is correct, it seems that the build result for a branch commit overwrites the build result for the PR merge commit.

![image](https://cloud.githubusercontent.com/assets/2208/5144755/4591659c-719d-11e4-9163-10e350795c8d.png)

**Comment by BanzaiMan** [comment] 2015-03-09 11:34
This might have been a duplicate of #1910. We now report 2 distinct builds to GitHub, and as such I believe this is no longer an issue.

**Closed by BanzaiMan** 2015-03-09 11:34 UTC
Labels: bug
