### ISSUE TITLE
Build fails when trying to install Google Chrome on Ubuntu Trusty

### ISSUE THREAD

**Issue by kunagpal** [travis-ci/travis-ci#7988] opened 2017-06-28 11:04 UTC
https://travis-ci.org/postmanlabs/postman-sandbox/jobs/247886065

Appears to be related to #7987

**Comment by Lin-Buo-Ren** [comment] 2017-06-28 11:16
It does seems to be a duplicate of #7987 :-)

**Comment by BanzaiMan** [comment] 2017-06-29 12:36
Closing as a duplicate. Let us know if it continues to be a problem.

**Closed by BanzaiMan** 2017-06-29 12:36 UTC
