### ISSUE TITLE
Cancelling/restarting build via API stopped working

### ISSUE THREAD

**Issue by mwek** [travis-ci/travis-ci#7207] opened 2017-01-24 11:03 UTC
Hey Travis team,

recently all POST requests to `jobs/<job_id>/cancel` return `{"file":"not found"}` instead of cancelling the build. All `GET` API calls for the same Travis token work perfectly fine, so I doubt it's related to API rate limiting (see #6838).

The issue also affects `jobs/<job_id>/restart` API call.

Best,
Maciek

**Comment by carlad** [comment] 2017-02-14 16:40
I can confirm that when curling, I get the `{"file":"not found"}` error when attempting to restart or cancel a `job`.

I am able to restart and cancel a `build` though, and also able to restart and cancel builds and jobs using the CLI.

Wondering if we should close this issue for now, as pointing api clients to use v3 is a way around this issue...?

**Comment by mwek** [comment] 2017-02-14 19:36
Unfortunately, we're unable to use the CLI, as we have some custom logic in 3rd party system that depends on Travis.

We could move to v3 API, unfortunately I'm unable to find proper documentation for that. https://docs.travis-ci.com/api still mentions `jobs/<job_id>/cancel`, https://developer.travis-ci.org/ ends up with infinite login loop for me, https://github.com/travis-pro/developer results in 404 (referenced [here](https://github.com/travis-ci/travis-api#api-documentation)). Can you point me to the right documentation?

**Comment by acnagy** [comment] 2017-02-15 13:40
@mwek Sorry for the trouble! I just enabled the documentation for you, so you should be able to see it now (though you may need to login). If anyone else at your org would like to have access as well, please feel free to have them email support@travis-ci.com and ask for being added to the developer program. Thanks!

**Comment by carlad** [comment] 2017-02-15 15:42
Hi @mwek, While we'd encourage you to start using our soon-to-be announced v3, we actually found the root cause of the issue today and have managed to deploy a fix. Please get back in touch if you have any more issues.

**Closed by carlad** 2017-02-15 15:42 UTC
Labels: bug, travis-api
