### ISSUE TITLE
Timeout following successful build

### ISSUE THREAD

**Issue by jugglinmike** [travis-ci/travis-ci#7607] opened 2017-04-12 17:49 UTC
In [a recent build job](https://travis-ci.org/w3c/web-platform-tests/jobs/221321989), the build script completed successfully, and Travis reports as much with "Done. Your build exited with 0." This was immediately followed by a report of a timeout:

>     Done. Your build exited with 0.
>     
>     
>     No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
>     Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
>     
>     The build has been terminated

Because there seem to be no commands executed between this two events (and [the project's `.travis.yml` file does not reference any of the lifecycle events that follow `build`](https://github.com/w3c/web-platform-tests/blob/25e7665c3f3e3ab574501c949a3448ee157eb388/.travis.yml)), it's unclear why this job was interpreted as timing out. Can someone on the TravisCI side suggest what might be going wrong here?

I found a few previously-submitted reports that seemed related at first glance, but none are actually relevant:

- gh-6753 - an erroneous report
- gh-6861 - seems to be specific to DotNET environments (this is a Python-based build)
- gh-7264 - the most recent and most relevant-sounding, but closed as "fixed" and subsequently locked

Thanks for the great service!

**Comment by ivailop** [comment] 2017-04-13 06:34
We experienced the same problem... As pointed in #7605, two workers were started for the same job. One of them completed successfully, but the second one (I guess running much slower) timed out.

**Comment by BanzaiMan** [comment] 2017-04-15 01:11
This is a duplicate of #7605.

**Closed by BanzaiMan** 2017-04-15 01:11 UTC
