### ISSUE TITLE
Shared Cache

### ISSUE THREAD

**Issue by RobertBColton** [travis-ci/travis-ci#8563] opened 2017-10-10 12:27 UTC
Hi, I have been trying to enable the new stages feature of Travis on an open source project but seem to have run into some issues. I am trying to follow the documentation:
https://docs.travis-ci.com/user/build-stages
This guide presents it as though I should be able to "Warming up a cache with expensive dependencies"
Thus, I tried following this guide to do my cache warming in a pre-test stage, which seems to work until it runs jobs in the test phase which aren't able to download the cache.

Before moving this cache warming into a separate stage all of my scripts were working fine and the jobs were correctly sharing the cache. How exactly is this guide supposed to even work as it's conveyed? It doesn't really seem like that's usable at all yet?

**Comment by vb216** [comment] 2017-10-14 06:42
Think I have the same issue, from that example I was hoping something like this would work, one job to get all download dependencies which later stages would use. If it only works for gem bundler, would be good to clarify that in the example

dist: trusty
sudo: false
cache:
  directories:
      - $HOME/downloads
addons:
  apt:
    packages:
    - yasm
    - nasm

language: java
services:
      - docker

jobs:
   include:
      - jdk: oraclejdk8
        stage: cache
        os: linux
        install: true
        script: ./ci/install-deps.sh

      - jdk: oraclejdk8
        stage: build
        os: linux
        env: PROJ=opencv,chilitags,flandmark,openblas,mxnet,hdf5,caffe OS=linux-ppc64le
        install: true
        script: ./ci/install-ppc.sh

**Comment by BanzaiMan** [comment] 2017-10-16 16:21
I think this is a duplicate of #7590.

**Closed** 2017-12-01 19:46 UTC
Labels: caching
