### ISSUE TITLE
32 bit versions of linux images

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#5770] opened 2016-03-10 12:47 UTC
Would be nice also to have 32 bit versions of Trusty linux images.

**Comment by shoogle** [comment] 2016-03-17 08:58
This would be a nice feature to have, but in the meantime it's actually possible to enter a 32 bit Trusty chroot on 64 bit Travis via Docker.

Adding these commands to .travis.yml would get you inside a 32 bit CentOS6 image. (You could replace [toopher/centos-i386:centos6](https://hub.docker.com/r/toopher/centos-i386/) with a Trusty image - [daald/ubuntu32:trusty](https://hub.docker.com/r/daald/ubuntu32/) might work, but I haven't tried it myself.)
<pre>
services:
- docker

script:
- "docker run -i -v \"${PWD}:/MyProgram\" toopher/centos-i386:centos6 /bin/bash -c \"linux32 --32bit i386 /MyProgram/build.sh\""
</pre>

This sets up a Docker chroot, enters 32 bit mode (via `linux32`), mounts the directory containing your code inside the chroot (in a directory called "/MyProgram"), and runs the file "MyProgram/build.sh" which should contain any commands you want to run in the chroot, including fetching any dependecies you need via `yum -y install <packages>` (or `apt-get install -y <packages>` on Trusty). Once "build.sh" has finished, control is handed back to .travis.yml in the 64 bit host where you can do Travis-specific things like run more tests, binary deployment, or send notifications to email/IRC.

**Comment by BanzaiMan** [comment] 2016-03-19 23:36
Hello. This is a duplicate of #986. As before, we do not have immediate plans to support it. For now, please use a suitable 32-bit Docker image, as shown above.

**Closed by BanzaiMan** 2016-03-19 23:36 UTC

**Comment by ProfessorKaos64** [comment] 2016-10-28 19:59
@shoogle , sorry to ping you on this thread, but I followed your advice, but it doesn't seem apt-get wants to install the pre-req packages:

https://github.com/ProfessorKaos64/ges-code/blob/develop-master/.travis.yml

https://github.com/ProfessorKaos64/ges-code/blob/develop-master/build-ges-ubuntu-docker.sh
