### ISSUE TITLE
Trouble specifying version of R to build with

### ISSUE THREAD

**Issue by nealrichardson** [travis-ci/travis-ci#6458] opened 2016-08-10 19:51 UTC
cc @craigcitro, @hadley, @jimhester

I just submitted a package release to CRAN, and it was rejected because of a change in behavior between the current 3.3.1 R release and the devel R build (3.4.0, under development). This was surprising to me because I believed I was running against the devel build on Travis. [My .travis.yml](https://github.com/Crunch-io/rcrunch/blob/7d563ee749a136440841f31f103258153ccb8dac/.travis.yml) has been

```
language: r
cache: packages
r: devel
```

but when I inspected the log output from recent travis builds, I saw R 3.3.1 in the session info. I re-read [the docs](https://docs.travis-ci.com/user/languages/r#R-Versions) and tried specifying the devel build more like the example there,

```
language: r
cache: packages
r:
  - devel
```

and still had 3.3.1. 

My next check was to see what you guys do in your packages, so I looked at https://github.com/hadley/httr/blob/master/.travis.yml and https://github.com/jimhester/covr/blob/master/.travis.yml. The only difference that seemed possibly meaningful was the presence of `sudo: false`, but according to the docs, that's not necessary if you already see the message about container-based infrastructure, which I did. Interestingly, though, when I checked the travis output for [httr](https://travis-ci.org/hadley/httr/builds/150954088) and [covr](https://travis-ci.org/jimhester/covr/builds/151246537), I also saw R version 3.3.1 in the output, so unless I'm misreading it, you're not getting the devel version for your builds either.

So, either I'm missing something and would love a pointer as to how to do the right thing (and perhaps some more language in the docs to make the right thing more obviously clear), or the devel build specification isn't working as intended.

**Comment by jimhester** [comment] 2016-08-11 12:55
The `r:` config variable does not seem to be showing up in recent builds configs. In a [matrix build from 15 days ago](https://travis-ci.org/hadley/readr/builds/147838072) looking at one of the [configs](https://travis-ci.org/hadley/readr/jobs/147838073/config) you can see that it is included. However looking at a [build from 8 days ago](https://travis-ci.org/hadley/readr/jobs/149514100/config) the `r:` variable no longer exists (and there is no build matrix). The `.travis.yml` file has not changed, so something must have changed on the backend side. 

@BanzaiMan Do we need to specify this variable in some other fashion in our build script? Any ideas what is going on?

**Comment by BanzaiMan** [comment] 2016-08-15 12:42
I'm closing this as a duplicate of #6431.

**Closed by BanzaiMan** 2016-08-15 12:42 UTC
Labels: community:r
