### ISSUE TITLE
Switches on the "Beta Features" page look broken

### ISSUE THREAD

**Issue by maseev** [travis-ci/travis-ci#8260] opened 2017-08-17 04:35 UTC
![selection_002](https://user-images.githubusercontent.com/3434800/29396055-a3a68d72-833f-11e7-929f-7c1edae46b41.png)

Browsers: 

- Mozilla Firefox 55.0.1 (64-bit)
- Opera 47.0.2631.55
- Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)

OS: `Linux 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by backspace** [comment] 2017-08-17 18:09
Thanks for reporting this. I never saw this regression because I didn’t have any of those switches turned on locally. I’ll be adding a snapshot of this route so we shouldn’t have visual regressions on this route anymore.

**Comment by backspace** [comment] 2017-08-17 21:36
The [PR to fix this](https://github.com/travis-ci/travis-web/pull/1246) is now merged and deployed. Thanks again!

**Closed by backspace** 2017-08-17 21:36 UTC
Labels: bug, travis-web
