### ISSUE TITLE
Enabling the Docker service on php environments causes phpenv to fail

### ISSUE THREAD

**Issue by cweagans** [travis-ci/travis-ci#4750] opened 2015-09-04 14:23 UTC
I'm attempting to use Docker containers in my tests, and when I add `sudo: required`, everything runs fine. When I add

```
services:
  - docker
```

`phpenv` fails when the tests are starting.

Here's my .travis.yml:

```
language: php
sudo: required
services:
  - docker

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - ENABLE_MCRYPT=0
  - ENABLE_MCRYPT=1

matrix:
  allow_failures:
    - env: ENABLE_MCRYPT=0
  fast_finish: true

install:
  - travis_retry composer install

script:
#  - ./tests/run-tests.sh
  - true

```

Here's the test log:

```
Using worker: travis-worker-gce-org-prod-2: (testing-gce-da65540b-c3e3-48e3-a952-fd51408832a9:travis-ci-minimal-trusty-1439396079)
system_info
Build system information
Build language: php
Build image provisioning date and time
Wed Aug 12 16:20:52 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
Linux Version
3.16.0-31-generic
Cookbooks Version
fffffff https://github.com/travis-ci/travis-cookbooks/tree/fffffff
Docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Git version
git version 1.9.1
GCC version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.5.0 (tags/RELEASE_350/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
jq version
jq-1.4
gimme version
v0.2.3
nvm version
0.25.4
perlbrew version
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.73
postgresql client version
psql (PostgreSQL) 9.3.9
phpenv version
rbenv 0.4.0-153-g3b6faa8
rvm version
rvm 1.26.11 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
default ruby version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
git.checkout
0.44s$ git clone --depth=50 --branch=switch-to-docker-tests git://github.com/cweagans/mcrypt-polyfill.git cweagans/mcrypt-polyfill
Cloning into 'cweagans/mcrypt-polyfill'...
remote: Counting objects: 366, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 366 (delta 15), reused 0 (delta 0), pack-reused 339
Receiving objects: 100% (366/366), 79.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (216/216), done.
Checking connectivity... done.
$ cd cweagans/mcrypt-polyfill
$ git checkout -qf d35b4ebadc5e3c76163e5f34d846e1bb45a96547
services
0.02s$ sudo service docker start
start: Job is already running: docker
Setting environment variables from .travis.yml
$ export ENABLE_MCRYPT=1
0.02s$ phpenv global 5.4 2>/dev/null
5.4 is not pre-installed; installing
0.17sbzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
0.00s0.02s$ phpenv global 5.4
rbenv: version `5.4' not installed
The command "phpenv global 5.4" failed and exited with 1 during .
Your build has been stopped.
```

Am I doing something wrong? Or have I found a real bug?

**Comment by BanzaiMan** [comment] 2015-09-04 14:28
Sorry about the issue. We do not have PHP environment pre-installed on the Docker image, which uses Trusty. This is mostly due to the inability to provide 5.2.x and 5.3.x support (see https://github.com/travis-ci/travis-ci/issues/2963).

**Comment by cweagans** [comment] 2015-09-04 14:33
If one is using Docker for tests, perhaps only one version of PHP would be adequate as a stopgap? I'm not running any of my tests outside of the Docker containers. I just need to be able to run `composer install` to pull down my library dependencies.

**Comment by andrioli** [comment] 2015-09-21 17:39
Same problem here (using php 5.6)

**Comment by cweagans** [comment] 2015-09-21 17:48
FWIW, I sidestepped this in https://github.com/cweagans/mcrypt-polyfill. You can take a look there to see what I did.

**Comment by andrioli** [comment] 2015-09-21 22:44
@cweagans your workaround works, but with this approach I need to install all dependencies (e.g., PHP, composer, xdebug) manually. I can also use Docker images for all dependencies, but in both cases my build script become a mess :(

I'll be waiting for a definitive solution :)

**Comment by ramsey** [comment] 2015-10-06 06:14
I've run into the same problem. I'm trying to use the Docker service with PHP 5.4, 5.5, 5.6, 7.0, and hhvm.

**Comment by osma** [comment] 2015-11-04 15:42
This affects also Trusty images that don't enable Docker services. I reported that in #5058 but it was closed as a duplicate of this issue.

**Comment by brunoric** [comment] 2015-11-05 01:15
Same problem here!

=(

**Comment by BanzaiMan** [comment] 2015-12-15 19:57
PHP packages should be available for Trusty now (except 5.2.x and 5.3.x, which do not support). Some extensions may be missing; this is a variation of a known issue https://github.com/travis-ci/travis-ci/issues/5296.

Could you confirm that at least the PHP builds can start on Trusty?

**Closed** 2015-12-15 23:12 UTC
Labels: php

**Comment by cweagans** [comment] 2015-12-15 23:43
@BanzaiMan I could be wrong or misinterpreting, but it kind of sounds like that doesn't actually solve the issue here. The PHP packages and extensions don't matter at all. The problem is enabling Docker on PHP environments. Linked issue is also completely unrelated...

**Comment by BanzaiMan** [comment] 2015-12-16 00:49
I apologize for not being clear, but you can see that in https://travis-ci.org/BanzaiMan/travis_production_test/builds/97119355 you have PHP available for `services: [docker]` now.

**Comment by cweagans** [comment] 2015-12-16 01:23
Ah, okay. Great. Thanks!
