### ISSUE TITLE
pypy3 is not pre-installed on Trusty images

### ISSUE THREAD

**Issue by MartyMacGyver** [travis-ci/travis-ci#8160] opened 2017-07-26 07:44 UTC
I'm relatively new to Travis-CI but I'm noticing an unexpected error during an attempt to build with `pypy3` on the default (Trusty) environment:

https://travis-ci.org/MartyMacGyver/DirTreeDigest/jobs/257614214#L419

    ....
    $ source ~/virtualenv/pypy3/bin/activate
    /home/travis/.travis/job_stages: line 57: /home/travis/virtualenv/pypy3/bin/activate: No such file or directory
    The command "source ~/virtualenv/pypy3/bin/activate" failed and exited with 1 during .

My configuration is rather simple, and the other targets build as expected:
https://github.com/MartyMacGyver/DirTreeDigest/blob/master/.travis.yml

Could this be related to #6865 ?

**Comment by Suor** [comment] 2017-07-26 09:54
Have same issue here https://travis-ci.org/Suor/funcy/jobs/257655259

**Comment by BanzaiMan** [comment] 2017-07-26 12:12
@Suor Yours is a recurrence of #6865.

**Comment by BanzaiMan** [comment] 2017-07-26 12:23
As pointed out in https://github.com/travis-ci/travis-ci/issues/6865#issuecomment-318037004, this is a duplicate of #6865.

**Closed by BanzaiMan** 2017-07-26 12:23 UTC
Labels: build environment, python, team blue, trusty

**Comment by MartyMacGyver** [comment] 2017-07-26 12:37
As the original problem was closed out, it seemed appropriate to report this as new. Right now neither this nor #6865 is open to track the problem.

**Comment by BanzaiMan** [comment] 2017-07-26 12:42
@MartyMacGyver Did you read my latest message in #6865? It should be good now. Please restart your failing builds.

**Comment by MartyMacGyver** [comment] 2017-07-26 13:03
Per your note here I restarted the build a few minutes ago and pypy3 is working now. Thanks for getting this resolved!
