### ISSUE TITLE
OS X: perlbrew is missing?

### ISSUE THREAD

**Issue by FGasper** [travis-ci/travis-ci#8911] opened 2017-12-13 17:03 UTC
https://travis-ci.org/FGasper/p5-Net-WebSocket/jobs/315935632

**Comment by BanzaiMan** [comment] 2017-12-13 17:11
We don’t support Perl on the Mac. Duplicate of https://github.com/travis-ci/travis-ci/issues/2314.

**Closed by BanzaiMan** 2017-12-13 17:11 UTC

**Comment by FGasper** [comment] 2017-12-13 17:12
@BanzaiMan This worked until the most recent change, FWIW.

**Comment by BanzaiMan** [comment] 2017-12-13 19:05
If it was working, then it must have been by some accident. My issue above points to this job from 4 years ago showing that `perlbrew` was unavailable then: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/25122996#L14. Even on your passing job from a month ago, it clearly shows that `perlbrew` was not available then, either: https://travis-ci.org/FGasper/p5-Net-WebSocket/jobs/297275784#L36.

**Comment by FGasper** [comment] 2017-12-16 15:21
I got this to work by replacing {{cpan App::cpanminus}} with {{curl -L http://cpanmin.us | perl - --self-upgrade}}.

Even if it’s not supported, it can still be a useful.
