### ISSUE TITLE
Wrong Build Status.

### ISSUE THREAD

**Issue by therajanmaurya** [travis-ci/travis-ci#7366] opened 2017-02-22 19:29 UTC
I have changed something in build.gradle and made a PR 
https://github.com/openMF/android-client/pull/539 It is build in progress.
As I opened the detail of build.
https://travis-ci.org/openMF/android-client/builds/204147166
it's showing that It is completed and passed.

**Comment by BanzaiMan** [comment] 2017-02-22 20:46
Duplicate of #7363.

**Closed by BanzaiMan** 2017-02-22 20:46 UTC
