### ISSUE TITLE
Uploading to FTP via curl fails randomly

### ISSUE THREAD

**Issue by cbnolok** [travis-ci/travis-ci#9438] opened 2018-04-03 09:50 UTC
Hello, as you can see in the build log (https://travis-ci.org/Sphereserver/Source-experimental/builds/361539323#L1884 ), curl frequently (not always) fails when trying to upload a file to an FTP server. Of course, the credentials are valid, and with the same command i can upload files successfully on my Linux machine.
Here's the log of a travis session using curl without the timeout and retry options: https://travis-ci.org/Sphereserver/Source-experimental/builds/356415900#L1863 .
What could be the problem? Thanks

**Comment by BanzaiMan** [comment] 2018-04-03 11:49
Duplicate of #9391.

**Closed by BanzaiMan** 2018-04-03 11:49 UTC
