### ISSUE TITLE
support for .NET core

### ISSUE THREAD

**Issue by liushuping** [travis-ci/travis-ci#6256] opened 2016-07-03 03:23 UTC
Please add support for .NET core platform with commands
```
dotnet restore
dotnet build
dotnet run
dotnet test
```

**Comment by BanzaiMan** [comment] 2016-07-03 18:00
Please mention @joshua-anderson @akoeplinger @nterry for C# inquiries, as documented in https://docs.travis-ci.com/user/languages/csharp. Thanks.

**Comment by BanzaiMan** [comment] 2016-08-24 01:19
Looks like a duplicate of #5692, which, in turn, is a duplicate of #5189.

**Closed by BanzaiMan** 2016-08-24 01:19 UTC
Labels: community:csharp
