### ISSUE TITLE
PostgreSQL 9.3 failing on createuser in Travis

### ISSUE THREAD

**Issue by migurski** [travis-ci/travis-ci#4584] opened 2015-07-28 15:02 UTC
This behavior from Travis CI is new:

    $ sudo -u postgres createuser -p 5432 travis &>/dev/null
    Shall the new role be a superuser? (y/n)

The build dies before going any further, because it’s waiting for user input that it will never get. My Travis config [looks like this](https://github.com/openaddresses/machine/blob/9e299ed66ec184060e17184dfef296c492d37eeb/.travis.yml#L8), with the 9.3 addon specified. [Build 72615655](https://travis-ci.org/openaddresses/machine/jobs/72615655) is a sample failure, while [build 72408935](https://travis-ci.org/openaddresses/machine/jobs/72408935) is a successful build from two days earlier with an identical Travis configuration.

**Comment by meatballhat** [comment] 2015-07-28 15:08
@migurski hey, thanks for reporting this.  We pushed a fix yesterday that should resolve the issue.  Have you seen this problem in the last ~20 hours or so?

**Comment by BanzaiMan** [comment] 2015-07-28 15:08
Thanks for opening this issue, but this is a duplicate of #4570, the fix for which was deployed yesterday. Please restart the build, and let us know if you continue to have problems.

**Closed by BanzaiMan** 2015-07-28 15:08 UTC

**Comment by migurski** [comment] 2015-07-28 16:09
Thank you @BanzaiMan. Here’s the same problem on a restarted build from a few minutes ago: https://travis-ci.org/openaddresses/machine/jobs/72615655

**Comment by BanzaiMan** [comment] 2015-07-28 16:59
This is quite bizarre. Your restart build is not using the latest code.

**Comment by BanzaiMan** [comment] 2015-07-28 17:00
Could you try pushing a new commit?

**Comment by BanzaiMan** [comment] 2015-07-28 17:04
Actually, this log is not making sense. The job ran for 5 seconds, yet it errored because there was no output for 10 minutes.

Could you restart again, and not cancel it?

![job__814_1_-_openaddresses_machine_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/8937831/fc38762e-3528-11e5-82c3-13ad6b3f2e87.png)

**Comment by migurski** [comment] 2015-07-28 17:17
Sure—I did not cancel it previously either. Re-running…

**Comment by migurski** [comment] 2015-07-28 17:20
Ah crap, it references a deleted branch. I will re-create the branch, and restart again.

**Comment by migurski** [comment] 2015-07-28 17:26
Looks better this time.

**Comment by migurski** [comment] 2015-07-28 18:07
Still seeing at least one of these: https://travis-ci.org/openaddresses/machine/jobs/72870834

**Comment by BanzaiMan** [comment] 2015-07-28 18:42
Did you restart the job? I don't see any error.

**Comment by migurski** [comment] 2015-07-28 20:11
Oh—you’re right, it’s just a failing test of mine. Sorry for the confusion, and thank you for your help!
