### ISSUE TITLE
apt-get install failed when using debian-sid as source

### ISSUE THREAD

**Issue by danij** [travis-ci/travis-ci#8245] opened 2017-08-12 14:01 UTC
Hi, I have the following configuration which includes `debian-sid` as a package source as I need a newer version of boost:

    addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-trusty-4.0
                - debian-sid
            packages:
                - cmake
                - gcc-6
                - g++-6
                - clang-4.0
                - libicu-dev
                - libboost-all-dev

It fails with the following error:

    Extracting templates from packages: 100%
    Preconfiguring packages ...
    (Reading database ... 73915 files and directories currently installed.)
    Preparing to unpack .../locales_2.24-14_all.deb ...
    Unpacking locales (2.24-14) over (2.13+git20120306-12.1) ...
    dpkg: error processing archive /var/cache/apt/archives/locales_2.24-14_all.deb (--unpack):
     trying to overwrite '/usr/sbin/update-locale', which is also in package libc-bin 2.19-0ubuntu6.13
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    Selecting previously unselected package libc-l10n.
    dpkg: considering deconfiguration of locales, which would be broken by installation of libc-l10n ...
    dpkg: yes, will deconfigure locales (broken by libc-l10n)
    Preparing to unpack .../libc-l10n_2.24-14_all.deb ...
    De-configuring locales (2.13+git20120306-12.1) ...
    Unpacking libc-l10n (2.24-14) ...
    Preparing to unpack .../libc-dev-bin_2.24-14_amd64.deb ...
    Unpacking libc-dev-bin (2.24-14) over (2.19-0ubuntu6.13) ...
    Preparing to unpack .../linux-libc-dev_4.11.11-1+b1_amd64.deb ...
    Unpacking linux-libc-dev:amd64 (4.11.11-1+b1) over (3.13.0-123.172) ...
    Preparing to unpack .../libncursesw5_6.0+20170715-2_amd64.deb ...
    Unpacking libncursesw5:amd64 (6.0+20170715-2) over (5.9+20140118-1ubuntu1) ...
    Preparing to unpack .../libncursesw5-dev_6.0+20170715-2_amd64.deb ...
    Unpacking libncursesw5-dev:amd64 (6.0+20170715-2) over (5.9+20140118-1ubuntu1) ...
    Replacing files in old package ncurses-bin (5.9+20140118-1ubuntu1) ...
    Preparing to unpack .../libtinfo5_6.0+20170715-2_amd64.deb ...
    Unpacking libtinfo5:amd64 (6.0+20170715-2) over (5.9+20140118-1ubuntu1) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
    Errors were encountered while processing:
     /var/cache/apt/archives/locales_2.24-14_all.deb
    W: --force-yes is deprecated, use one of the options starting with --allow instead.
    E: Sub-process /usr/bin/dpkg returned an error code (1)

    apt-get.diagnostics
    apt-get install failed

    $ cat ~/apt-get-update.log
    Ign:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 InRelease
    Hit:3 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
    Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease
    Hit:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release
    Hit:6 http://dl.google.com/linux/chrome/deb stable Release
    Ign:1 http://toolbelt.heroku.com/ubuntu ./ InRelease
    Hit:7 http://toolbelt.heroku.com/ubuntu ./ Release
    Hit:8 http://dl.hhvm.com/ubuntu trusty InRelease
    Ign:9 http://archive.ubuntu.com/ubuntu trusty InRelease
    Get:10 http://ftp.us.debian.org/debian unstable InRelease [228 kB]
    Hit:12 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
    Hit:13 http://archive.ubuntu.com/ubuntu trusty-updates InRelease
    Get:14 http://apt.llvm.org/trusty llvm-toolchain-trusty-4.0 InRelease [4,236 B]
    Hit:15 http://archive.ubuntu.com/ubuntu trusty-security InRelease
    Hit:16 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease
    Hit:17 http://archive.ubuntu.com/ubuntu trusty Release
    Get:18 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [120 kB]
    Get:11 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
    Ign:19 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
    Hit:20 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
    Get:22 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages [29 B]
    Hit:23 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
    Hit:24 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
    Get:26 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease [15.5 kB]
    Hit:28 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
    Hit:29 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
    Get:30 http://dl.hhvm.com/ubuntu trusty/main i386 Packages [20 B]
    Hit:31 https://packagecloud.io/basho/riak/ubuntu trusty InRelease
    Get:32 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,716 B]
    Hit:33 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
    Get:34 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages [1,195 kB]
    Hit:35 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
    Hit:36 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
    Get:37 http://apt.llvm.org/trusty llvm-toolchain-trusty-4.0/main amd64 Packages [7,229 B]
    Get:38 http://apt.llvm.org/trusty llvm-toolchain-trusty-4.0/main i386 Packages [7,251 B]
    Get:39 http://ftp.us.debian.org/debian unstable/main amd64 Packages [10.2 MB]
    Get:40 http://archive.ubuntu.com/ubuntu trusty-updates/restricted i386 Packages [20.9 kB]
    Get:41 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse i386 Packages [16.1 kB]
    Get:42 http://archive.ubuntu.com/ubuntu trusty-updates/universe i386 Packages [544 kB]
    Get:43 http://archive.ubuntu.com/ubuntu trusty-security/main i386 Packages [749 kB]
    Get:44 http://archive.ubuntu.com/ubuntu trusty-security/restricted i386 Packages [17.6 kB]
    Get:45 http://archive.ubuntu.com/ubuntu trusty-security/multiverse i386 Packages [4,183 B]
    Get:46 http://archive.ubuntu.com/ubuntu trusty-security/universe i386 Packages [230 kB]
    Get:47 http://ftp.us.debian.org/debian unstable/main i386 Packages [10.2 MB]
    Get:48 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty/main i386 Packages [1,611 B]
    Get:50 http://archive.ubuntu.com/ubuntu trusty/main i386 Packages [1,739 kB]
    Get:51 http://ftp.us.debian.org/debian unstable/contrib amd64 Packages [69.7 kB]
    Get:52 http://ftp.us.debian.org/debian unstable/contrib i386 Packages [65.3 kB]
    Get:53 http://ftp.us.debian.org/debian unstable/non-free amd64 Packages [96.9 kB]
    Get:54 http://ftp.us.debian.org/debian unstable/non-free i386 Packages [86.9 kB]
    Get:55 http://archive.ubuntu.com/ubuntu trusty/restricted i386 Packages [16.4 kB]
    Get:56 http://archive.ubuntu.com/ubuntu trusty/multiverse i386 Packages [172 kB]
    Get:57 http://archive.ubuntu.com/ubuntu trusty/universe i386 Packages [7,597 kB]
    Get:58 http://dl.bintray.com/apache/cassandra 39x/main i386 Packages [682 B]
    Get:59 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,464 B]
    Get:60 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [4,392 B]
    Get:61 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [445 B]
    Get:62 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 Packages [82.3 kB]
    Get:64 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main i386 Packages [80.8 kB]
    Get:67 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages [3,145 B]
    Get:68 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages [985 B]
    Fetched 33.6 MB in 7s (4,619 kB/s)
    Reading package lists...
    W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
    W: There is no public key available for the following key IDs:
    7638D0442B90D010
    W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

    The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install cmake gcc-6 g++-6 clang-4.0 libicu-dev libboost-all-dev" failed and exited with 100 during .

    Your build has been stopped.

**Comment by MoritzKn** [comment] 2017-08-15 23:19
I have the same problem. Here is the full log of a job failed with this error: https://travis-ci.org/MoritzKn/ralculator/jobs/264847788

**Comment by MoritzKn** [comment] 2017-08-15 23:38
Seams to be a duplicate of #4838

**Comment by BanzaiMan** [comment] 2017-08-29 21:10
Yes, it is.

**Closed by BanzaiMan** 2017-08-29 21:10 UTC
