### ISSUE TITLE
Uploading fails

### ISSUE THREAD

**Issue by soerenschmidt89** [travis-ci/travis-ci#7581] opened 2017-04-06 13:46 UTC
Every time Travis starts to upload the files in the end of the build/deployment, it gets stuck and takes several hours to complete.
It has worked up untill now, but this morning it started acting weird - we have not changed anything since yesterday - you guys made som changes that broke the uploading?

(or does anyone else have the same problem?)

**Comment by BanzaiMan** [comment] 2017-04-06 13:51
Do you have a build log URL that shows the problem you are describing here?

**Comment by Karnich** [comment] 2017-04-06 13:56
@BanzaiMan it hangs when we try to upload container images to Azure. It does not break. But it does take almost 2 hours to upload ~300 MB. Its usually not more than 10-20 seconds at most. Pretty boring build log.

Uploading is not a problem locally..

**Comment by BanzaiMan** [comment] 2017-04-06 14:13
Please link to a build log URL that shows the problem. There are some crucial details in the logs that would help us understand the problem better. If you wish to not discuss this in public, please close this issue and send email to support@travis-ci.com.

Thanks.

**Comment by soerenschmidt89** [comment] 2017-04-06 14:18
Here is one that is stuck: https://travis-ci.com/EG-Xena/Gabrielle.Web/jobs/71280234

**Comment by BanzaiMan** [comment] 2017-04-06 14:21
Thank you! This is consistent with other reports of network issue. We are looking into it.

**Comment by tkunze** [comment] 2017-04-06 16:00
Same here. Uploading to Azure hangs. Sample log below, starting after build success.
Issue started about 18 hours ago.

![build-fail](https://cloud.githubusercontent.com/assets/239703/24763820/60129c28-1aa7-11e7-951f-ace2e7e15a7a.png)

**Comment by tkunze** [comment] 2017-04-06 16:02
Also, pushing to Azure from dev machine not an issue, so seems to be on Travis-Ci's end.

**Comment by dunnock** [comment] 2017-04-07 07:39
It still fails for all our builds pushing containers to Azure for already 30+ hours. Any solution/workaround?

**Comment by askarby** [comment] 2017-04-07 11:44
I can sadly confirm @dunnock's experience. Any update on this?

**Comment by webpapaya** [comment] 2017-04-07 12:42
We're experiencing the same issue while pushing docker containers to our own docker registry.

**Comment by florian-crewmeister** [comment] 2017-04-07 12:50
Same here!

**Comment by thehusted** [comment] 2017-04-07 12:57
@BanzaiMan can we get an update on this issue?

**Comment by karalabe** [comment] 2017-04-07 13:00
Would be nice, since the issue isn't even acknowledged on the travis stats page, even though it's been failing for almost 2 days now.

**Comment by BanzaiMan** [comment] 2017-04-07 13:50
Is anyone having problems with servers other than Docker Hub or Azure?

**Comment by BanzaiMan** [comment] 2017-04-07 13:52
@webpapaya When you say "our own docker registry", is it somewhere other than hub.docker.com?

**Comment by webpapaya** [comment] 2017-04-07 13:59
@BanzaiMan sorry my fault, we're pushing to azure as well.

**Comment by BanzaiMan** [comment] 2017-04-07 14:14
Is there any case of a public repository showing this problem? We want a reproducible case so that we can provide good information to the infrastructure service provider.

**Comment by karalabe** [comment] 2017-04-07 14:16
https://travis-ci.org/ethereum/go-ethereum/builds

(cron jobs are green, but they skip uploads)

**Comment by BanzaiMan** [comment] 2017-04-07 14:19
@karalabe Where is this uploading stuff to?

**Comment by karalabe** [comment] 2017-04-07 14:20
Azure

**Comment by BanzaiMan** [comment] 2017-04-07 14:39
Thanks for the reports, everyone, and we apologize for the delay in responding. We have opened an incident now: http://stspg.io/5GwY.

**Comment by BanzaiMan** [comment] 2017-04-07 14:40
My understanding is that the issue is limited to sudo-enabled jobs and various Azure instances. If you have a case that does not fit this description, please let us know with details.

Thank you!

**Comment by BanzaiMan** [comment] 2017-04-07 19:11
Hello. We are exchanging information with the service provider about this issue, but do not have updates to share yet.

Thank you for your patience.

**Comment by tkunze** [comment] 2017-04-07 20:55
Seems to be working for me now. Last 2 builds succeeded.

**Comment by BanzaiMan** [comment] 2017-04-07 21:22
@tkunze Thanks for the report. When was the first successful build?

**Comment by tkunze** [comment] 2017-04-07 22:13
2 hours ago

**Comment by dunnock** [comment] 2017-04-07 22:47
same to me!

**Comment by BanzaiMan** [comment] 2017-04-07 23:30
@dunnock Thank you!

**Comment by BanzaiMan** [comment] 2017-04-08 14:51
I'm closing this for now. If the issue resurfaces, do let us know.

**Closed by BanzaiMan** 2017-04-08 14:51 UTC
Labels: team blue
