### ISSUE TITLE
Python 3.5 Interpreter Not Found

### ISSUE THREAD

**Issue by chrisspen** [travis-ci/travis-ci#5993] opened 2016-05-04 02:28 UTC
Even if I specify python 3.5 in my config, Travis reports

    InterpreterNotFound: python3.5

My config:

    language: python
    python:
    -   "2.7"
    -   "3.3"
    -   "3.4"
    -   "3.5"
    install:
    -   pip install tox
    script:
    -   tox

The docs say Python 3.5 [is supported](https://docs.travis-ci.com/user/languages/python). Is this correct? What's wrong with my config?

**Comment by BanzaiMan** [comment] 2016-05-04 02:58
It is. Given this [`.travis.yml`](https://github.com/BanzaiMan/travis_production_test/blob/9012e729d9ccce6664cef4c23a67e82890be1db1/.travis.yml), you get https://travis-ci.org/BanzaiMan/travis_production_test/builds/127690830, where you can see Python 3.5 is found.

https://travis-ci.org/BanzaiMan/travis_production_test/jobs/127690831#L126
https://travis-ci.org/BanzaiMan/travis_production_test/jobs/127690832#L157
https://travis-ci.org/BanzaiMan/travis_production_test/jobs/127690833#L141

**Comment by BanzaiMan** [comment] 2016-05-04 03:01
Where do you see this error message?

**Comment by BanzaiMan** [comment] 2016-05-04 10:58
Looks like a duplicate of https://github.com/travis-ci/travis-ci/issues/4794.

**Closed by BanzaiMan** 2016-05-04 10:58 UTC

**Comment by chrisspen** [comment] 2016-05-04 14:03
I'm getting it here:

https://travis-ci.org/chrisspen/django-chroniker/jobs/127674590

Why did you close #4794? He's specifying python: 3.5, and you tell him he needs to specify python 3.5?

**Comment by BanzaiMan** [comment] 2016-05-04 16:54
@chrisspen https://travis-ci.org/chrisspen/django-chroniker/builds/127674589 says https://travis-ci.org/chrisspen/django-chroniker/jobs/127674590 is using Python 2.7. Since 3.5 is not pre-installed on the image, if you want to test with Python 3.5, you have to install it. And that is possible only when you set `python: 3.5`. If you look at your build, you see the error

    ERROR: InterpreterNotFound: python3.5

in each of the jobs ***except for*** https://travis-ci.org/chrisspen/django-chroniker/jobs/127674595, because that one has Python 3.5 installed.
