### ISSUE TITLE
nvm: command not found

### ISSUE THREAD

**Issue by SimenB** [travis-ci/travis-ci#6476] opened 2016-08-14 12:59 UTC
Lots of Mac builds (but not all) are failing for me with `nvm: command not found`

E.g. https://travis-ci.org/SimenB/wait-until-promise/builds/152166396

**Comment by BanzaiMan** [comment] 2016-08-14 13:32
Does the issue persist if you restart the failing jobs?

**Comment by SimenB** [comment] 2016-08-14 13:46
The web site is so slow for me ATM I'm unable to test. But yeah, a couple of the builds became green on restarting them

**Comment by BanzaiMan** [comment] 2016-08-14 13:54
Thanks for testing. We fetch `nvm` when it is not available or it is old, but we failed (presumably due to network problems). Restarting it rectified the problem.

**Comment by SimenB** [comment] 2016-08-14 13:57
I had the same issue in 5 separate repos at the same time, that's why I reported.

Why not have nvm preinstalled though? It's pretty tiny, and no real need to keep it updated (the project only recommends upgrading if you have issues). Although, if it were network issues, maybe the download of node would have failed, I don't know

**Comment by BanzaiMan** [comment] 2016-08-14 14:27
It is not there because the image is old, and we [did not support Node.js on OS X until very recently](https://github.com/travis-ci/travis-ci/issues/2311#issuecomment-205549262). I am not sure if the newer OS X images have nvm.sh pre-installed; I'll have to check.

**Comment by SimenB** [comment] 2016-08-14 14:33
Ok, looking forward to it stabilizing some more 😄 

You can close this unless you want to keep it for tracking purposes, I'll keep restarting the builds (4/5 repos failed after restart, new round now)

**Comment by BanzaiMan** [comment] 2016-08-14 14:36
I confirmed that at least the `xcode7.3` has `nvm` pre-installed. Set

```yaml
osx_image: xcode7.3 # or newer (maybe other older ones work, too)
```

at the top level of your `.travis.yml`.

I'm closing this now.

**Closed by BanzaiMan** 2016-08-14 14:36 UTC
Labels: node.js, travis-build

**Comment by SimenB** [comment] 2016-08-14 16:00
@BanzaiMan Adding the newer image made all the builds pass, thanks!

Any particular reason why it's not the default image?

**Comment by briananderson1222** [comment] 2016-10-18 16:39
What is the correct way to do a nvm fallback on Travis? I am currently getting a `nvm: command not found` on xcode7.3
