### ISSUE TITLE
API for registering a single repo

### ISSUE THREAD

**Issue by CJ-Wright** [travis-ci/travis-ci#9786] opened 2018-06-22 17:22 UTC
Would it be possible to have an API for registering a single repo with Travis-CI? Conda-forge is getting close to 5000 repos. When we hit 5000 repos Travis-CI sync will no longer be able to sync all the repos. It would be great if we could register an individual repo at creation time.

**Comment by isuruf** [comment] 2018-06-22 20:30
Duplicate of https://github.com/travis-ci/travis-ci/issues/6320 ?

**Comment by scopatz** [comment] 2018-06-22 20:39
I'd like to second @CJ-Wright and @isuruf here.  This has become a huge issue for us.

**Comment by scopatz** [comment] 2018-09-20 20:56
This issue has defintinely not been addressed, to the best of our knowledge.

**Comment by jakirkham** [comment] 2018-09-20 21:04
Indeed. Though maybe we should consolidate this into the other related issue. 😉

**Comment by DrTorte** [comment] 2018-12-05 05:43
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Closed by DrTorte** 2018-12-05 05:43 UTC
