### ISSUE TITLE
Add support for yarn

### ISSUE THREAD

**Issue by scottohara** [travis-ci/travis-ci#6720] opened 2016-10-13 06:18 UTC
(Kind of surprised there wasn't already an issue filed for this; given the mostly positive reception to the announcement of [Yarn](https://yarnpkg.com/) recently...)

(Apart from https://github.com/travis-ci/travis-ci/issues/6713, that is...)

Heroku appears to be working on a [experimental branch](https://github.com/heroku/heroku-buildpack-nodejs/compare/yarn) of their nodejs buildpack that detects the presence of a `yarn.lock` file. If found, use `yarn` to install dependencies instead of `npm`.

Is this something Travis would consider doing in the default `install` script for nodejs projects?

**Comment by sanex3339** [comment] 2016-10-13 08:22
I want it too.

With `npm i -g yarn && yarn` in `install` section - `npm i -g yarn` takes some time to install yarn. It would be nice select package manager with option like `package-manager: yarn`

**Comment by pi0** [comment] 2016-10-14 11:11
Please checkout [YarNPM](https://github.com/pi0/yarnpm) :)

**Comment by jimdebeer** [comment] 2016-10-19 13:25
yes please!

**Comment by MarkBennett** [comment] 2016-10-20 01:46
Others might find [this information on integrating `yarn` with TravisCi useful](https://yarnpkg.com/en/docs/install_ci) (click the Travis tab). Basically, Yarn recommend adding the following to your .travis.yaml:

```
before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.yarn-cache
```

**Comment by sanex3339** [comment] 2016-10-20 08:20
I got an error with code above. 

```
$ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo: must be setuid root
```

https://travis-ci.org/sanex3339/javascript-obfuscator/jobs/169138242

**Comment by sanex3339** [comment] 2016-10-20 08:47
I getting an error with yarn and node 0.12.0
https://travis-ci.org/sanex3339/javascript-obfuscator/jobs/169163143

`SyntaxError: Use of const in strict mode.`

**Comment by marvinhagemeister** [comment] 2016-10-28 19:51
@sanex3339 `node 0.12.0` has been superseded by no more than 2 LTS versions as of recently.

**Comment by Daniel15** [comment] 2016-10-30 02:07
I've got a pull request over at https://github.com/travis-ci/apt-source-whitelist/pull/322 to add the Yarn repo to TravisCI's apt source whitelist, which should make it easier to install Yarn on TravisCI. For now you can manually add the repo (see @MarkBennett's comment above) but that also requires `sudo: required` in your `_travis.yml` due to limitations in TravisCI's container architecture

Of course, it would be great if Yarn was preinstalled 😄

**Comment by F3rmiParad0x** [comment] 2016-11-08 21:15
You could try this in your .travis.yml file :

``` yaml
before_script:

  # install v6.x of nodejs
   - nvm install 6
  #install yarn globally
   - npm install -g yarn
  # yarn install is like npm install
   - yarn install
```

You can do this without having to resort to the `sudo: required` mode

**Comment by phueper** [comment] 2016-11-09 06:30
Regarding @F3rmiParad0x s proposal... it might be easier to do

```
node_js:
  - 6
```

instead of starting with the default node version and then `- nvm install 6` in the before_script?

and wouldn't you need `sudo` for `npm install -g` as well?

**Comment by domoritz** [comment] 2016-11-09 06:32
@phueper We're already doing that in https://github.com/vega/vega-lite/blob/vg3/.travis.yml and you don't need sudo. However, installing yarn is still slow so the benefits are minor.

**Comment by Daniel15** [comment] 2016-11-09 06:33
> installing yarn is still slow

Have you tried using the Debian package? npm is pretty slow to install Yarn, using the Debian package should be quicker.

**Comment by domoritz** [comment] 2016-11-09 06:45
@Daniel15 No. We don't want to use sudo. We will just wait for official support from travis and just accept the long installation times for now.

**Comment by Daniel15** [comment] 2016-11-09 06:45
> don't want to use sudo

Why not?

**Comment by domoritz** [comment] 2016-11-09 06:48
@Daniel15 haven't tried it, but the boot time seems so high that it's not worth it https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments.

**Comment by Daniel15** [comment] 2016-11-09 06:52
I hope Travis fix that limitation at some point. I can't think of a reason why container infrastructure would need to disable superuser access.

For what it's worth, for Yarn itself we didn't see any statistically significant increase in build times after enabling sudo: https://github.com/yarnpkg/yarn/pull/1117. Although, Travis is more of a secondary build for us - we're using CircleCI for our primary build.

**Comment by domoritz** [comment] 2016-11-09 06:57
@Daniel15 That would be great. 

I'd have to run more experiments but with build + test times around 2 minutes, it seems that the yarn install times are in the noise. https://travis-ci.org/vega/vega-lite/builds/174419207 vs https://travis-ci.org/vega/vega-lite/builds/174128943. Nonetheless, we like to use yarn over npm because we get reproducible builds :-)

**Comment by Daniel15** [comment] 2016-11-09 06:58
Hmm, the other thing you could try is download the tarball (https://yarnpkg.com/latest.tar.gz) and extract it. That should still be faster than installing through npm.

**Comment by domoritz** [comment] 2016-11-09 07:19
The differences seem to be in the noise, though. 

For reference, here are the three methods I tried

Download and extract yarn
```bash
install: wget https://yarnpkg.com/latest.tar.gz && tar -xf latest.tar.gz && dist/bin/yarn
```

Npm install yarn
```bash
install: npm install -g yarn && yarn
```

Install yarn via apt
```
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install: yarn
```

**Comment by damontgomery** [comment] 2016-11-16 16:41
I have added the following to a `php` project (Drupal) and it seems to work. Note that you cannot specify a node version as you could on a `node_js` project for a `php` or other system.

## Working Example (PHP 5.6 & Node 6.9.1)
```
sudo: required
language: php
dist: trusty

php:
  - 5.6

before_install:
  # Install proper version of node for front end tasks.
  - nvm install 6.9.1
  - nvm use 6.9.1
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
```

## Related issues?
Today the following stopped working for me. It seems fine without it.
```
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
```

## FYI
*DOES NOT WORK FOR PHP PROJECTS*
```
node_js:
  - 6
```

**Comment by BanzaiMan** [comment] 2016-11-16 16:45
@damontgomery The nodesource.com issue is one of DNS/CDN. See https://github.com/travis-ci/travis-ci/issues/6881#issuecomment-260989744.

**Comment by BanzaiMan** [comment] 2016-11-16 16:46
@damontgomery Also, the top level `node_js` key is only effective for repos with `language: node_js`.

**Comment by Daniel15** [comment] 2016-11-16 18:55
> Today the following stopped working for me. It seems fine without it.

Good catch, TravisCI should include an appropriate version of Node.js out-of-the-box so we probably don't need to suggest using the NodeSource repo. I removed the NodeSource repo from Yarn's CircleCI instructions: https://github.com/yarnpkg/website/commit/bc8873cd9c08f3c5e9bdbede433df33065c8c917

@BanzaiMan - Any chance we could get https://github.com/travis-ci/apt-source-whitelist/pull/322 merged to add Yarn to the whitelist? 😄

**Comment by BanzaiMan** [comment] 2016-11-16 19:28
@Daniel15 I don't think that's necessary to add Yarn support here.

**Comment by BanzaiMan** [comment] 2016-11-16 19:30
Here's an early test of what yarn support might look like on Travis: https://staging.travis-ci.org/BanzaiMan/example-yarn-package/builds/525387

By using the `curl | bash` installation method instead of `apt-get`, the overhead is about 1s to install yarn on the fly.

**Comment by BanzaiMan** [comment] 2016-11-16 19:32
Also note that we detect Node.js versions that do not support yarn. You may also notice that caching is enabled in the example build. This may or may not make it when we roll out support.

**Comment by BanzaiMan** [comment] 2016-11-16 19:36
I should add that this example build detects the presence of the `yarn.lock` file in the root of the repository, and runs `yarn` when it does.

If `yarn.lock` is present but Node.js version does not meet yarn's requirement (Node.js 4 or later), the install phase is a noop. This may not be the best behavior. Your input is welcome.

**Comment by BanzaiMan** [comment] 2016-11-16 19:37
I opened https://github.com/yarnpkg/website/issues/269 to make the Node.js version requirement of yarn more explicit.

**Comment by BanzaiMan** [comment] 2016-11-16 20:11
Since there may be some workarounds to install yarn on the fly, we should skip it if the command `yarn` is already available.

**Comment by BanzaiMan** [comment] 2016-11-16 20:30
That ↑ doesn't quite work, because our code to install `yarn` would run before any of the user code would be executed. (It would help some when we roll out build images with yarn pre-installed. That could take a little while.)

**Comment by Daniel15** [comment] 2016-11-16 21:12
> By using the curl | bash installation method instead of apt-get

The main issue with that is that the install script is less secure as it isn't GPG signed. Additionally, you can lock in a particular version number with apt-get (eg. `apt-get install yarn=0.16.1-1`) but can't do that with the install script at the moment (tracked by https://github.com/yarnpkg/yarn/issues/1856)

AppVeyor preinstalled Yarn onto their build worker images so that you can use it instantly  as part of your build, without having to install it. It would be nice if Travis could do this too, in the same way that npm is preinstalled when you have a Node.js build.

**Comment by BanzaiMan** [comment] 2016-11-16 21:35
We plan to add yarn pre-installed for a future image update. This will take time.

You are rightly concerned with the security of `curl | bash` (rightfully, I should add). We can fetch the script *now*, and store it on `travis-build`, or basically mimic what is happening on the script now. This could pose a maintenance problem down the road, but it might be a agreeable compromise. (Looking at the file content right now, though, it is just fetching the appropriate tarball, expanding it and adding it to `$PATH`.)

If this is truly a security concern, though, I would ask the Yarn team to not provide this installation method.

**Comment by BanzaiMan** [comment] 2016-11-16 22:06
I'll try `apt-get install` and `brew install` tomorrow.

**Comment by Daniel15** [comment] 2016-11-16 23:00
> If this is truly a security concern, though, I would ask the Yarn team to not provide this installation method.

It's all about tradeoffs :) The installation script is useful for environments where we don't have a native package yet (like Gentoo, Alpine, etc). We should investigate GPG signing the tarballs though.

**Comment by BanzaiMan** [comment] 2016-11-17 16:24
On Linux, installation via `apt-get` appears quite comparable with `curl | bash` in terms of speed. Compare https://staging.travis-ci.org/BanzaiMan/example-yarn-package/jobs/525440 (with `apt-get`) and https://staging.travis-ci.org/BanzaiMan/example-yarn-package/jobs/525452 (with `curl | bash`).

On OS X, on the other hand, installation via `brew` adds about 80 seconds (204 seconds total) https://staging.travis-ci.org/BanzaiMan/example-yarn-package/jobs/525441#L36, whereas with `curl | bash`, about 12. https://staging.travis-ci.org/BanzaiMan/example-yarn-package/jobs/525453#L67

I feel that use of `brew` here is not acceptable. And if we are to use `curl | bash` on one platform, I advocate using it on Linux as well for ease of maintenance.

**Comment by BanzaiMan** [comment] 2016-11-17 16:29
The 80 seconds figure I showed above is for the latest Xcode 8.1 image. I think this would be longer on older OS X images.

**Comment by BanzaiMan** [comment] 2016-11-17 19:18
https://github.com/travis-ci/travis-build/pull/895 introduces the yarn support. This PR is compatible with the existing workaround to make `yarn` available, and with the future work when a version of `yarn` is pre-installed.

**Comment by Daniel15** [comment] 2016-11-19 08:49
Adding GPG signature verification to the Yarn install script here: https://github.com/yarnpkg/yarn/pull/1949

This may make the installation a bit slower, it should still be significantly faster, more reliable and more secure than installing via npm though 😄

**Comment by BanzaiMan** [comment] 2016-11-21 17:47
Hello. We've deployed this a few hours ago, and finally announced it on our blog: https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

I'm closing this now. If you see problems, please open separate issues.

Thank you!

**Closed by BanzaiMan** 2016-11-21 17:47 UTC
Labels: feature-request, node.js, travis-build

**Comment by jamonkko** [comment] 2017-03-12 22:15
Just noticed that if you need to install yarn manually (e.g. to get that [custom install step to work](https://github.com/travis-ci/travis-ci/issues/6923#issuecomment-262397744)  ) and are using the container builds, you can install yarn like this:

```yaml
dist: trusty
sudo: false
cache: yarn
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn
```

**Comment by damianobarbati** [comment] 2017-06-21 15:27
Any news on this? 
The current way to use preinstalled yarn is to commit the `yarn.lock` file which is very bad since lots of devs are gitignoring .lock files.
On the otherside `npm install -g yarn` is slowing down a lot.

**Comment by keimlink** [comment] 2017-06-21 15:32
@damianobarbati Yarn's documentation [says](https://yarnpkg.com/en/docs/version-control) `yarn.lock` should be checked into source control. So why do you think "lots of devs are gitignoring .lock files"?

**Comment by Daniel15** [comment] 2017-06-21 21:42
Yeah, yarn.lock should be checked in, otherwise you lose the major benefits
of Yarn.

Sent from my phone.

On Jun 22, 2017 1:33 AM, "Markus Zapke-Gründemann" <notifications@github.com>
wrote:

@damianobarbati <https://github.com/damianobarbati> Yarn's documentation
says <https://yarnpkg.com/en/docs/version-control> yarn.lock should be
checked into source control. So why do you think "lots of devs are
gitignoring .lock files"?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/travis-ci/travis-ci/issues/6720#issuecomment-310117052>,
or mute the thread

**Comment by damianobarbati** [comment] 2017-06-22 08:08
Oh I see, wrong assumption in the office I was working (where I got the default gitignore file). Thanks!
