### ISSUE TITLE
Can I set shorter timeout for Jobs?

### ISSUE THREAD

**Issue by andreif** [travis-ci/travis-ci#8470] opened 2017-09-21 11:29 UTC
Today few our builds using Ubuntu images had a hanging job for 2 hours and blocked all workers so that the build queue grew a lot. I wonder if we can set a shorter job timeout to stop it in the case of such hanging. Our jobs run for about 5-10 minutes so we would prefer to fail them after say 15 min instead of waiting until someone notices the problem and restarts them.

**Comment by DrTorte** [comment] 2017-09-21 19:37
Hey there,

We can certainly add a hard timeout to your repos. Which specific ones were you looking at adding it to?

All the best,

Kris

**Comment by andreif** [comment] 2017-09-22 05:23
@DrTorte Ideally we would prefer to control timeouts by ourselves since it can be repo-dependent and can change with time.

**Comment by philmd** [comment] 2018-02-15 13:50
similar to #5306 and #6636

**Comment by BanzaiMan** [comment] 2018-02-15 14:47
I'm closing this as a duplicate of #5306.

**Closed by BanzaiMan** 2018-02-15 14:47 UTC
Labels: feature-request
