### ISSUE TITLE
Duplicate repository in 'My Repositories'

### ISSUE THREAD

**Issue by brbsix** [travis-ci/travis-ci#5880] opened 2016-04-10 05:31 UTC
I'm seeing a duplicate repository in 'My Repositories' and on the page with on/off switches. I don't recall doing anything out of the ordinary with this particular repo that would have caused this. I created a repo on GitHub, added a *.travis.yml* file, pushed some changes, then enabled the repository from https://travis-ci.org.

I then tested the webhook from GitHub, disabled/enabled it a few times from https://travis-ci.org, and hit the 'Sync account' button a few times as well. None of that seemed to resolve the issue.

![screenshot_2016-04-09_21-50-25](https://cloud.githubusercontent.com/assets/6672131/14408172/912ca30c-fe9d-11e5-87a9-7e805e0438fc.png)
![screenshot_2016-04-09_21-51-38](https://cloud.githubusercontent.com/assets/6672131/14408173/912e93e2-fe9d-11e5-86b4-a39adbc3605d.png)

**Comment by hut8** [comment] 2016-05-22 20:37
I have the same issue, after recently moving a repository which was originally a fork (tenex/rails-assets). Now I get both showing up.

Seems like a duplicate of:

https://github.com/travis-ci/travis-ci/issues/4075
https://github.com/travis-ci/travis-ci/issues/2664
https://github.com/travis-ci/travis-ci/issues/2663
https://github.com/travis-ci/travis-ci/issues/2663
https://github.com/travis-ci/travis-ci/issues/2617
https://github.com/travis-ci/travis-ci/issues/2623
https://github.com/travis-ci/travis-ci/issues/1469
https://github.com/travis-ci/travis-ci/issues/2501
https://github.com/travis-ci/travis-ci/issues/2472
https://github.com/travis-ci/travis-ci/issues/2388
https://github.com/travis-ci/travis-ci/issues/2333
https://github.com/travis-ci/travis-ci/issues/2325
https://github.com/travis-ci/travis-ci/issues/2208
https://github.com/travis-ci/travis-ci/issues/2144
https://github.com/travis-ci/travis-ci/issues/1861

.. and a lot of others :smile: 
/cc @joshjordan

**Comment by drogus** [comment] 2016-06-09 13:15
Sorry for a delay in response. Actually these are a distinct issues which manifest in the same way. I fixed the problem that @brbsix reported (I just cleaned up a DB, but we'll be rolling out a proper fix soon).

@hut8 could you e-mail support@travis-ci.com with the details you provided? thanks!

**Closed by drogus** 2016-06-09 13:15 UTC
Labels: team teal
