### ISSUE TITLE
Setting invalid/no language in .travis.yml silently defaults to Ruby

### ISSUE THREAD

**Issue by nabijaczleweli** [travis-ci/travis-ci#4895] opened 2015-10-07 18:23 UTC
According to [the Docs](http://docs.travis-ci.com/user/customizing-the-build/) one needs to specify the `language` node to use the build image optimized therefor.
(The list of accepted `language`s are, AFAICT in [the Docs](http://docs.travis-ci.com/user/languages/))

It would seem logical, that the `language` field is obligatory and needs to be valid to use The Service properly (invalid language -> no build image for it -> :cry:).
However, this does not seem to be the case:
  * With [no `language` specified](https://travis-ci.org/Skorezore/Gaem/builds/84146476) the build language [magically falls back to `ruby`](https://travis-ci.org/Skorezore/Gaem/jobs/84146477#L4)
  * With [invalid `language` specified](https://travis-ci.org/Skorezore/Gaem/builds/84149126) (set to `_` here) the error [is silently swallowed](https://travis-ci.org/Skorezore/Gaem/jobs/84149127#L4) and the build language [magically falls back to `ruby` without any mention thereof](https://travis-ci.org/Skorezore/Gaem/jobs/84149127#L264)

In both cases "no language set" is displayed in [the build overview](https://travis-ci.org/Skorezore/Gaem/builds/84146476) ([2](https://travis-ci.org/Skorezore/Gaem/builds/84149126)).

The expected behaviour for lack of `language` would be to either:
  * mention the fallback in the docs
  * error with "invalid .travis.yml"

The expected behaviour for invalid `language` would be to error with "invalid .travis.yml"

**Comment by rubik** [comment] 2015-10-21 08:07
I encountered this issue as well. This is annoying. There should also be a value to unset it (i.e. do nothing by default before `before_install`).

**Comment by jakemcgraw** [comment] 2015-10-23 20:59
:+1: encountered this behavior when using TravisCI to deploy a static site to S3. Defaulted to Ruby, couldn't find a Rake file and bailed. Supporting ```language: none``` with no ```before_install``` step seems to be the best option?

**Comment by BanzaiMan** [comment] 2015-10-23 22:01
This is basically a duplicate of #2708. For builds that don't fall into other categories, use `language: generic`, (which is currently undocumented; https://github.com/travis-ci/travis-ci/issues/2867#issuecomment-59262795).

**Comment by nabijaczleweli** [comment] 2015-10-25 16:48
Thanks, @BanzaiMan. Using `language: generic` works.

**Comment by BanzaiMan** [comment] 2016-04-27 06:40
The language name should now be case insensitive.

**Closed by BanzaiMan** 2016-04-27 06:40 UTC

**Comment by rbrtmrtn** [comment] 2017-02-22 21:01
This was super helpful. Are there any plans to make `language: generic` a documented/supported option?

**Comment by antony** [comment] 2017-03-02 15:02
Generic is great for building docker images and such that don't actually have any code to compile / test

**Comment by vharsh** [comment] 2017-11-15 05:29
As said `language: bash` is better than `language: generic` 
Ref: https://github.com/travis-ci/travis-ci/issues/5175#issuecomment-215016943

Any difference b/w language set to bash over generic ?
