### ISSUE TITLE
Re-build unchanged pull request to a branch that had its .travis.yml updated

### ISSUE THREAD

**Issue by danilobellini** [travis-ci/travis-ci#6395] opened 2016-08-01 04:33 UTC
Suppose there are 2 pull requests, A and B, both targeted to the same upstream branch. Also, let A include an update to `.travis.yml`, and B be anything else that doesn't change such file. For any reason, A was merged while B was kept untouched. If I re-run the B pull-request jobs (by clicking either "restart build" or "restart job"), it will test the new branch tip (the last commit, including stuff from A) "auto-merged" to the pull request commit (B), but it completely neglects the new `.travis.yml` description.

["Building Pull Requests" docs](https://docs.travis-ci.com/user/pull-requests) tells us that:

> Travis CI also currently doesn’t build pull requests when the upstream branch is updated

Actually, that documentation is just about the lack of a build trigger for the GitHub update notification, but this issue is about a manual build (clicking on "restart build"). Clearly, the new upstream branch tip commit is used when restarting the build, but not its new `.travis.yml`, which is an inconsistency.

There might be some matrix update, leading to a different number of jobs, or even a different matrix structure (where the "restart job" wouldn't make much sense, just the "restart build" would). That's actually my case: https://travis-ci.org/danilobellini/fractals/builds/146923616

In a more general case, both A/upstream and B might update `.travis.yml`. Travis CI is just generating garbage when it runs/restarts a job with a deprecated build script that wasn't generated by the actual `.travis.yml`.

Perhaps #6031 was about this issue as well.

**Comment by BanzaiMan** [comment] 2016-08-01 12:26
I think this is a duplicate of #1620. Please let us know if you think otherwise.

**Closed by BanzaiMan** 2016-08-01 12:26 UTC

**Comment by danilobellini** [comment] 2016-08-01 13:05
Related, but far from being duplicate. I'm not arguing about automation, nor about finding the last mergeable commit in "target" history. I'm arguing about something much more specific and explicitly manual: consistency regarding .travis.yml and the build script. Issue #1620 is an enhancement proposal, but this issue is a bug report.

**Comment by BanzaiMan** [comment] 2016-08-01 13:23
I am not sure if that is the case. Any 2 independent PRs can introduce potential conflicts like this (not just with `.travis.yml`), and without merging one PR (A in your case) into the other (B), there is no way that we can have a good build.

**Comment by danilobellini** [comment] 2016-08-01 13:33
Wrong. If B were merged before, there would be no problem. I'm not talking about the commit nor the fetch steps, these seem to be correctly done in the build. Only .travis.yml matters, and that file alone is the point of this issue.

**Comment by BanzaiMan** [comment] 2016-08-01 14:24
I see that now. In this case, I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/1485.

**Comment by danilobellini** [comment] 2016-08-01 15:21
I don't know if solving more general issues like that one would help here, nevertheless I think what I'm claiming here is simpler, and is a bug that can be manually reproduced without the need of any rare event.

Not a refetch, not a new numbered build, not a missing file. It has nothing to do with network errors. I don't think any file is missing at all, I'm pretty sure the .travis.yml is actually "refetched", as I trust git is doing its job as it should. Also, what I'm saying is just about pull requests, it doesn't apply to any other builds, yet some "edgy" cases like that one in #1485 might seem similar (e.g. when a new commit appeared upstream updating the .travis.yml during or after the `build.sh` generation and before `git clone` is called in a build job, even the first PR build would be inconsistent).

I believe that what I'm saying is something that passes unnoticed by most people that are trusting in the single bit "green checked" result without looking to the log. The inconsistency is about both false negatives and false positives.

The issue has to do with the fact that the Travis internal `build.sh` is never rewritten using the new updated `.travis.yml` upstream. If the build script just verify if the `.travis.yml` that generated it is the same one got by git cloning/fetching, that would be an enough assertion to ensure that the job is consistent about its build script. It would detect itself as an inconsistent job, and should stop as soon as possible to avoid producing garbage.

After an inconsistency is detected, the best solution would be a trigger to make the `build.sh` again and restart the whole build matrix, but the minimal solution for consistency is to avoid misleading results from "restart build/job" buttons.

**Comment by BanzaiMan** [comment] 2016-08-01 17:19
> The issue has to do with the fact that the Travis internal build.sh is never rewritten using the new updated .travis.yml upstream. 

This is basically what #1465 addresses, no? Once a build is configured, we do not re-fetch `.travis.yml` under any circumstance. Restart does not affect the configuration (it may contain undesirable configuration due to 404—which is what #1465 reported, or an updated head branch—which this one addresses).

**Comment by danilobellini** [comment] 2016-08-01 18:39
C'mon, why did you close this issue before this discussion started? Is this really the right place to report a bug?

> [...] we do not re-fetch .travis.yml under any circumstance.

And don't need to. But terminology is getting awful here.

Don't you think Travis CI reports (logs and results) should be trustful and consistent? Or Travis CI doesn't care on producing garbage without even stating it's garbage? Generally, issues demanding automation aren't issues demanding consistency and vice-versa.

Actually, the "git clone" and "git fetch" commands are already doing this "re-fetch" job for such a comparison. And that should be enough to simply compare hashes to assert if the build is consistent.

You seem to be saying that there's a major solution that would solve/fix every issue related to "rebuilding modified/damaged code" (the best scenario), but that would need to change some legacy architecture, something that maybe won't ever happen. If that's your point, I don't disagree, but that's not a solution/fix to any issue at all, and this one should had never been closed.

I'm saying there are simpler solutions that fix this issue. Yes, it's related to a lot of other issues, but it isn't the same. As exists something that fixes this issue but not those ones, I believe they're not the same.

**Comment by BanzaiMan** [comment] 2016-08-01 19:40
I understand your frustration, and I see that my initial closure was premature. The issue turned out to be something different from what I originally thought.

> > [...] we do not re-fetch .travis.yml under any circumstance.
> 
> And don't need to.

Yes, we do, if I understand what you are trying to address with this ticket.

The build script is compiled from the configured data for that build, which is based on the content of `.travis.yml` that we retrieved when we configured that build. We do not re-fetch `.travis.yml` under any circumstance for the purpose of configuring the build and compiling the build script.

We "re-fetch" `.travis.yml` with `git clone` *inside* the build script, but that does not affect the build script itself, since the script has already been compiled by then.

I agree that there is an inconsistency here, and it is a variation of #1465.

**Comment by danilobellini** [comment] 2016-08-01 22:24
What I propose is to store `sha1sum .travis.yml` in the build script during compilation, and let it compare that stored value with the new hash obtained after the git clone/fetch steps on the downloaded .travis.yml, inside the build script, erroring when these doesn't match. That seems simple, doesn't require a build script recompilation and would fix the inconsistency in the short run, and would avoid the highly undesired false positives (something that don't seem to appear in #1485). An "unable to evaluate" status would be better than "errored", but error would be better than "fail", and fail would be "less worse" than "passing".

I agree recompiling the build script on every re-build (restart build) would be the best in the long run as it solves a lot of other issues. But in the meantime the results can be at least consistent.

**Comment by BanzaiMan** [comment] 2016-08-01 23:47
In order to compare such checksums, we would need to fetch `.travis.yml` again. At that point, we might as well use that to configure the build. Storing the checksum requires changes in our database scheme with little benefit.

**Comment by danilobellini** [comment] 2016-08-02 06:11
> In order to compare such checksums, we would need to fetch .travis.yml again.

Nope. As I said before, there's no extra fetch, just what is already being done.

> Storing the checksum requires changes in our database scheme with little benefit.

Little benefit?!?!? I'm talking about something that should be trivial... travis-build (build.sh compilation) is in Ruby, isn't it?

```ruby
irb(main):001:0> require 'digest/sha1'
=> true
irb(main):002:0> Digest::SHA1.hexdigest File.open(".travis.yml").reduce :+
=> "b25d8fe1bc4f8fcc70d29b3857b8057d5c32e1be"
```

Just store that value in the build script (compilation time)! And for the comparison, that's just a really small change in the build script. After the git steps, just test:

```shell
test b25d8fe1bc4f8fcc70d29b3857b8057d5c32e1be = $(sha1sum .travis.yml | cut -c1-40)
```

And the benefit is obvious: as of today, people shouldn't ever trust in pull-request builds without looking to the logs. Unless they know there were no .travis.yml update, but how many people know about that? After the first "hey, this passed in the PR build but isn't passing now that I merged!", how's Travis CI reputation?

There's still the "garbage production": I'm talking about builds that are consuming resources for no benefit at all. Just detect the inconsistency and stop a build that would otherwise produce nothing useful.

It's probably faster to fix this issue than to complain about its usefulness or similarity with other issues. Keeping this issue closed expresses clear disdain towards both bug reporting and Travis CI reputation.

**Comment by BanzaiMan** [comment] 2016-08-04 13:23
I see that you are frustrated, and you wish to move this forward somehow.

However, `travis-build` does not have access to the content of `.travis.yml` itself; only the parts that are relevant to the job it needs to compile the script. So it cannot compute the checksum in the manner you suggest.
