### ISSUE TITLE
Drop trusty, start using bionic

### ISSUE THREAD

**Issue by KOLANICH** [travis-ci/travis-ci#9928] opened 2018-07-31 06:55 UTC
Trusty lacks some new packages like `openjdk-11-jre-headless`

**Comment by Peque** [comment] 2018-09-14 11:06
> **BanzaiMan** [commented on May 27](https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-392340511)
> *The work on Bionic is not too far behind. Thanks!*

@BanzaiMan Any updates on this matter since that comment?

**Comment by bittner** [comment] 2018-10-03 13:07
[python3-wxgtk4.0](https://packages.ubuntu.com/bionic/python3-wxgtk4.0) is an example of a package available neither in the Trusty no the Xenial image. Only Bionic would help. We're [unable to use Travis](https://github.com/cool-RR/PythonTurtle/pull/119) for running all tests due to that.

**Comment by dreibh** [comment] 2018-10-06 20:39
+1

**Comment by avikivity** [comment] 2018-11-15 17:40
+1 - need libc-ares 1.13 for https://github.com/scylladb/seastar, this is not available in xenial.

**Comment by BanzaiMan** [comment] 2018-11-15 21:54
Duplicate of #5821.

**Closed by BanzaiMan** 2018-11-15 21:54 UTC

**Comment by Peque** [comment] 2018-11-16 08:18
@BanzaiMan Being locked, we cannot even react with a :+1: on that issue. :disappointed:
