### ISSUE TITLE
Problem with build DONE.

### ISSUE THREAD

**Issue by brunoosilva** [travis-ci/travis-ci#7055] opened 2016-12-19 11:28 UTC
Hello,

I have a problem with build done, show of message "**Done. Your build exited with 0.**", but no exited, look of print screen:

![image](https://cloud.githubusercontent.com/assets/3465257/21311169/083b8048-c5cd-11e6-9ed5-7bdb0d825177.png)

Project: https://travis-ci.org/brunoosilva/express-api-es6

**Comment by BanzaiMan** [comment] 2016-12-19 13:24
Thanks for taking the time to open this issue. However, I believe this is a duplicate of #6861. I'm closing this as such.

**Closed by BanzaiMan** 2016-12-19 13:24 UTC
