### ISSUE TITLE
Running apt-get install can lead to timeouts waiting for y/n

### ISSUE THREAD

**Issue by roidrage** [travis-ci/travis-ci#5366] opened 2015-12-28 15:19 UTC
We received a report that there's incosistent behaviour between the Trusty and Precise environments when it comes to running `apt-get install` with specific packages, where `apt-get` might wait for user input on a y/n question.

An example build can be found here: https://travis-ci.org/rdeits/travis-trusty-apt-bug/builds/98793864

Is there maybe a difference in APT's configuration where we don't have the option to always assume yes configured on Trusty?

**Comment by BanzaiMan** [comment] 2015-12-28 15:27
Duplicate of #4995 (and also see #4996).

**Closed by BanzaiMan** 2015-12-28 15:27 UTC
Labels: trusty
