### ISSUE TITLE
PHPunit 4.8.11 and HHVM 3.6.6 result in a Segfault on Travis-ci build core dump

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#5634] opened 2016-02-15 19:40 UTC
```
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.2792.log
/home/travis/build.sh: line 45:  2792 Segmentation fault      (core dumped) libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
The command "libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml" exited with 139.
```

Example failing build
https://travis-ci.org/photodude/joomla-cms/jobs/109432023

**Comment by BanzaiMan** [comment] 2016-02-15 23:48
You are calling `libraries/vendor/bin/phpunit`. https://github.com/photodude/joomla-cms/blob/91970a0eca40700d0df649e5fa38c52bdd64291a/.travis.yml#L51 Where are you getting this `phpunit`? That is not the location of `phpunit` we provide.

**Comment by photodude** [comment] 2016-02-16 06:39
I believe it's composer installed from 4.8.11 in the PHPunit github repository

**Comment by BanzaiMan** [comment] 2016-02-17 16:59
Where is it coming from?

**Comment by photodude** [comment] 2016-02-17 18:50
PHPunit 4.8.11 is installed from Composer (link to the composer line)
https://github.com/photodude/joomla-cms/blob/91970a0eca40700d0df649e5fa38c52bdd64291a/composer.lock#L1422

so it's direct from the github repository for PHPunit at the tag for 4.8.11
https://github.com/sebastianbergmann/phpunit.git

**Comment by photodude** [comment] 2016-02-24 00:09
@BanzaiMan I ran a test updating PHPUnit to 4.8.23, Same Segfault issue.

https://travis-ci.org/photodude/joomla-cms/jobs/111357931
```
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.3343.log
/home/travis/build.sh: line 45:  3343 Segmentation fault      (core dumped) libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
```

**Comment by BanzaiMan** [comment] 2016-02-24 00:47
Thanks for the update. Is PHPUnit compatible with HHVM 3.6.x?

**Comment by photodude** [comment] 2016-02-24 05:09
I believe it is, 
I think HHVM and phpunit compatibility started in hhvm3.1.x

Although I think hhvm3.6.x is end of life but that's what is available in the container install.

**Comment by BanzaiMan** [comment] 2016-04-27 08:09
Sorry for the delay. I tend to think this is best investigated by HHVM team. https://github.com/facebook/hhvm/issues/3982 is an outstanding issue, though it is not clear how recent the issue is.

You could also try Trusty, as it can run a more recent version of HHVM.

```yaml
language: php

php:
  - hhvm

sudo: required
dist: trusty
group: edge # until the next update
⋮
```

If there is anything we should be doing, do let us know.

I'm closing this in the meantime.

**Closed by BanzaiMan** 2016-04-27 08:09 UTC
Labels: php

**Comment by photodude** [comment] 2016-04-27 13:44
So If we only wanted to run HHVM on trusty and still use containers for all other php versions, I guess we would do something like
```yaml
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  include:
    - php: 5.3
      env: INSTALL_APC="yes"
    - php: 5.4
      env: INSTALL_APC="yes"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: hhvm
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached
  - redis-server

before_script:
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then sudo: required .; fi
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then dist: trusty .; fi
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then group: edge .; fi
```

Are we going to have issues mixing container builds with legacy infrastructure?

**Comment by photodude** [comment] 2016-05-01 16:39
Looks like there is no issue mixing Container builds and legacy infrastructure (other than it's slow)

It does need to be set up in the matrix includes from what I have read

```yaml
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  include:
    #- php: 5.3
    #  env: INSTALL_APC="yes"
    #- php: 5.4
    #  env: INSTALL_APC="yes"
    #- php: 5.5
    #  env: INSTALL_APCU="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes"
    #- php: 7.0
    #  env: INSTALL_APCU="yes" INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled apcu_bc install until https://github.com/travis-ci/travis-ci/issues/5207 is resolved
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      env: INSTALL_APCU_BC_BETA="no" INSTALL_MEMCACHE="no" INSTALL_MEMCACHED="no" INSTALL_REDIS="no" # Disabled items that currently do not work in travis-ci hhvm
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached
  - redis-server
```

**Comment by photodude** [comment] 2016-05-01 18:17
Yep, this is working to get HHVM in legacy infastructure and everything else running containar based.

now the issue is MySQL in HHVM
I got the following error 
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

seems either mySQL isn't installed or it didn't start

**Comment by BanzaiMan** [comment] 2016-05-01 18:56
Perhaps it is not started by default on the Trusty image. Try adding:

```yaml
services:
  - mysql
  ⋮ # rest
```

**Comment by photodude** [comment] 2016-05-01 19:13
Will do, currently my biggest issue with using trusty is the build speed. I'm going on 53+minutes and it still says "booting"

https://travis-ci.org/photodude/joomla-cms/jobs/127063231

**Comment by photodude** [comment] 2016-05-01 20:30
Starting MySQL in service didn't work
Errorred

'mysql: unrecognized service'

https://travis-ci.org/photodude/joomla-cms/jobs/127072266

**Comment by photodude** [comment] 2016-05-01 20:54
Ok, so trusty needs to have MySQL installed as it's currently not included. 

Now that it's running, Still have the segfault issue
https://travis-ci.org/joomla/joomla-cms/jobs/127085633

**Comment by BanzaiMan** [comment] 2016-05-01 21:22
Thanks for testing. I think this is best investigated by the HHVM team.

**Comment by photodude** [comment] 2016-05-02 00:31
I was wrong, there is no segfault... I was looking at the results for the wrong branch. 

Trusty has a memory issue
Fatal error: request has exceeded memory limit in /home/travis/build/photodude/joomla-cms/libraries/vendor/phpunit/php-timer/src/Timer.php on line 97

https://travis-ci.org/photodude/joomla-cms/jobs/127113452

**Comment by photodude** [comment] 2016-05-02 16:11
The hhvm reported memory limit using `ini_get("memory_limit")` returns `17179869184` available (16gb?)

Not sure what's going on, about a year ago (the last time I tried testing with hhvm) I reported a similar memory limit issue to PHPunit https://github.com/sebastianbergmann/phpunit/issues/1714

I was told then "tells you that the execution of your test suite requires more memory than you allow in your HHVM configuration"

How do I increase the memory for this?

**Comment by photodude** [comment] 2016-05-04 04:01
Ok I figured out how to change the hhvm memory limit

```yml
 - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then cat build/travis/phpenv/hhvm.php.ini >> /etc/hhvm/php.ini; fi
```

with the hhvm.php.ini set to unlimited memory (i.e. system max)
```ini
memory_limit = -1
```
so now the memory limit is listed as 9223372036854775807 (should be more that enough for everything)

but I'm still getting the out of memory error
`Fatal error: request has exceeded memory limit in /home/travis/build/photodude/joomla-cms/libraries/vendor/phpunit/php-timer/src/Timer.php on line 97`

Peak memory is still listed as 2097152
