### ISSUE TITLE
[PHP 7.2 nightly] phpunit/sebastian-comparator DOMNodeComparator::assertEquals() bad method signature

### ISSUE THREAD

**Issue by claudiopro** [travis-ci/travis-ci#7239] opened 2017-01-29 16:35 UTC
Hi!

FYI, the PHP build is affected by [Issue #32](https://github.com/sebastianbergmann/comparator/issues/32) from  https://github.com/sebastianbergmann/comparator.

I hit an issue with the signature of `DOMNodeComparator::assertEquals()` and PHP 7.2 nightly [in this build](https://travis-ci.org/emeraldion/creso/jobs/196352278):

```
Fatal error: Declaration of
SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false)
must be compatible with
SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array)
in phar:///home/travis/.phpenv/versions/master/bin/phpunit/sebastian-comparator/DOMNodeComparator.php
on line 0
```

The issue was addressed by @sebastianbergmann with https://github.com/sebastianbergmann/comparator/commit/7c391956f8086a22a257cb26461544e4fc8e02e0

**Comment by claudiopro** [comment] 2017-01-29 16:50
If anyone is hit by this issue, switching to `vendor/bin/phpunit` instead of running the global `phpunit` is a [valid workaround](https://travis-ci.org/emeraldion/creso/jobs/196365040).

**Comment by sebastianbergmann** [comment] 2017-01-29 17:00
That is not only a workaround but the only sane way of running PHPUnit on Travis if you pull in PHPUnit via Composer on Travis.

**Comment by claudiopro** [comment] 2017-01-29 17:04
Thanks for chiming in. It would be valuable to add this to [the docs](https://docs.travis-ci.com/user/languages/php/). I saw the recommended workaround mentioned in #7226.

**Comment by BanzaiMan** [comment] 2017-01-29 17:21
Thanks for the report. I'm closing this as a duplicate of #7226.

**Closed by BanzaiMan** 2017-01-29 17:21 UTC
