### ISSUE TITLE
Build failing due to holding broken packages

### ISSUE THREAD

**Issue by nlowe** [travis-ci/travis-ci#9172] opened 2018-02-01 18:01 UTC
My [.net core builds](https://travis-ci.org/athena-scheduler/athena/builds/336210357?utm_source=github_status&utm_medium=notification) started failing with

```
E: Unable to correct problems, you have held broken packages.
```

My `.travis.yml` file has not changed in about a week and builds were passing as recently as 2 days ago. The build passes locally.

<details>
<summary>Travis YML File</summary>

```yml
language: csharp
mono: latest
dotnet: 2.0.0
dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.6"

script:
  - ./build.sh
```

</details>

I've tested a few other projects (mainly c++ and java based) and have not been able to reproduce the issue. I [restarted a build that was previously passing in a similar project](https://travis-ci.org/nlowe/dotnet-api-sandbox/builds/323985348) which failed in the same manner.

cc @joshua-anderson @akoeplinger @nterry

**Comment by nlowe** [comment] 2018-02-01 18:08
Appears to be a dupe of #9171

**Comment by BanzaiMan** [comment] 2018-02-01 20:33
Closing as a duplicate of #9171.

**Closed by BanzaiMan** 2018-02-01 20:33 UTC
