### ISSUE TITLE
Recent OS X images appear to have expired root certificate in keychain

### ISSUE THREAD

**Issue by chillpop** [travis-ci/travis-ci#4709] opened 2015-08-26 19:22 UTC
When I specify `osx_image: xcode6.4`, using shenzhen to upload IPAs to HockeyApp fails with the following error:

```
error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed. Use --trace to view backtrace
```

Using `doctor.rb` from https://github.com/mislav/ssl-tools to investigate reveals the following:

```
> ruby doctor.rb upload.hockeyapp.net:443

/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin/ruby (2.0.0-p643)
OpenSSL 1.0.1j 15 Oct 2014: /etc/openssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""
HEAD https://upload.hockeyapp.net:443
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
The server presented a certificate that could not be verified:
  subject: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
  issuer: /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
  error code 10: certificate has expired
Possible causes:
  `/etc/openssl/certs/' is empty
```

Based on this [issue](https://github.com/nomad/shenzhen/issues/288) and this [comment](https://github.com/nomad/shenzhen/issues/255#issuecomment-103381038), I have found a workaround that involves removing the expired certificate from the keychain by adding the following to `before_install`:

```
- sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338 /System/Library/Keychains/SystemRootCertificates.keychain
- rvm osx-ssl-certs update all
```

I believe the issue is that the [expired GlobalSign root certificate](https://support.globalsign.com/customer/portal/articles/1426272-expiration-of-old-globalsign-2014-root-ca-certificate) is in the keychain of the OS X image.

This also appears to be an issue using `beta-xcode6.3` but not on the default OS X image (no `osx_image` specified) or `beta-xcode6.2`.

Can you remove (or update) the expired certificate by default on these images (or find some other solution)?

**Comment by BanzaiMan** [comment] 2015-08-31 15:06
Thanks for the report. We will look into it.

**Comment by postmechanical** [comment] 2015-09-11 20:47
+1 ran into this issue recently too.

**Comment by postmechanical** [comment] 2015-12-24 18:40
Just started running into this issue again with `curl` and `xcode7.2` image.

**Comment by jacebrowning** [comment] 2016-01-19 23:09
I am now seeing this issue after updating to `xcode7.2` from `xcode7.1`.

**Comment by postmechanical** [comment] 2016-01-20 04:18
@jacebrowning try adding this TravisCI recommended workaround to your before_install:

    rvm reinstall 2.0.0-p643 --disable-binary

**Comment by jacebrowning** [comment] 2016-01-20 05:31
@postmechanical Thanks! That does the job.

It also adds 376 seconds to the build time. Is the ultimate fix to wait for Travis CI (@BanzaiMan) to update their `xcode7.2` images?

**Comment by fassko** [comment] 2016-01-20 07:51
I'm waiting for the fix as well. If somebody has a better solution/workaround then please post it here. Thanks!

**Comment by jacebrowning** [comment] 2016-01-20 13:35
I have found that I can guard the `rvm` call to only run on builds that are going to trigger a deploy deploy:

```
before_install: >
  if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$XCTOOL_NAME" == "iPad Air" ]]; then
    rvm reinstall 2.0.0-p643 --disable-binary
  fi
```
where `XCTOOL_NAME` one of the variables in my build matrix.

**Comment by emdantrim** [comment] 2016-01-22 22:08
From what I can tell, the issue with the `xcode7.2` image (and the `xcode7.3` image) is separate from the issue with 6.4 that was originally reported in this ticket.

I just fixed the `xcode 7.2` and `xcode7.3` images though, so that's cool! /cc @jacebrowning @postmechanical 

6.4 is different, though. I'm taking a look at that :)

**Comment by jacebrowning** [comment] 2016-01-23 02:05
@emdantrim I can confirm that works with my build on `xcode7.2`. Thanks!

**Comment by postmechanical** [comment] 2016-07-01 21:46
Running into this issue again using `xcode7.3` and `rvm: 2.2.2`.

**Comment by solarce** [comment] 2017-06-20 20:03
This has been resolved in image updates since this was originally reported. Closing.

**Closed by solarce** 2017-06-20 20:03 UTC
Labels: mac, travis-cookbooks
