### ISSUE TITLE
Trusty update adds world-writable dir to path

### ISSUE THREAD

**Issue by segiddins** [travis-ci/travis-ci#8892] opened 2017-12-12 21:47 UTC
See https://travis-ci.org/bundler/bundler/jobs/315559315#L829 for a newly failing build log.

Specifically, ruby is now printing out the following warning:
`warning: Insecure world writable dir /usr/local/clang-5.0.0/bin in PATH, mode 040777`
which was not printed before today's update. This breaks our build, as we assert that no warnings are printed.

**Comment by edmorley** [comment] 2017-12-13 01:11
This looks like a duplicate of #8645, which is also filed as travis-ci/travis-cookbooks#943.

**Comment by eregon** [comment] 2017-12-13 11:17
The same happens for the build of ruby/ruby itself:
https://travis-ci.org/ruby/ruby/builds/315794894

**Comment by cotsog** [comment] 2017-12-13 14:37
@segiddins @eregon we are aware of the issue. It will need either a fix on the image itself or in our YAML generation component (i.e. [travis-build](https://github.com/travis-ci/travis-build)). Sorry for the inconvenience.

In the meantime, could you add the following to your .travis.yml file?

```yaml
before_install:
  - sudo chmod go-w /usr/local/clang-5.0.0/bin
```

(Note: even if you have `sudo: false` adding this line ☝️  will route your build on our `sudo: required` infrastructure.)

We will update this issue when it's fixed on our side.

Thank you for your patience!

**Comment by BanzaiMan** [comment] 2017-12-13 15:00
Looks like LLVM's 5.0.0 has this wide-open permissions.

```drwxrwxrwx bcain/users        0 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/
-rwxr-xr-x bcain/users   209691 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/llvm-mt
-rwxr-xr-x bcain/users 21178199 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/c-index-test
-rwxr-xr-x bcain/users 45287589 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/llc
-rwxr-xr-x bcain/users 18825475 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/find-all-symbols
lrwxrwxrwx bcain/users        0 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/llvm-readelf -> llvm-readobj
-rwxr-xr-x bcain/users  3692190 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/llvm-readobj
-rwxr-xr-x bcain/users  2758041 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/clang-offload-bundler
-rwxr-xr-x bcain/users 42575174 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/llvm-lto2
-rwxr-xr-x bcain/users 20395457 2017-09-07 23:43 clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin/clang-query
```

We will work on a hot fix.

**Comment by BanzaiMan** [comment] 2017-12-13 15:01
The archive should be fixed.

**Comment by BanzaiMan** [comment] 2017-12-13 16:04
The 3.9.0 archive does not have this problem, which explains why this is new.

```
drwxr-xr-x root/root         0 2016-09-01 18:26 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/
-rwxr-xr-x root/root  16596384 2016-09-01 18:23 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/modularize
-rwxr-xr-x root/root  13557192 2016-09-01 18:24 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-mc
-rwxr-xr-x root/root  16689928 2016-09-01 18:25 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang-rename
-rwxr-xr-x root/root   2440144 2016-09-01 18:09 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-split
-rwxr-xr-x root/root   2256504 2016-09-01 18:03 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/obj2yaml
-rwxr-xr-x root/root     18099 2015-06-19 08:23 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/git-clang-format
-rwxr-xr-x root/root    672800 2016-09-01 18:01 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/yaml2obj
-rwxr-xr-x root/root  13486752 2016-09-01 18:09 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/bugpoint
lrwxrwxrwx root/root         0 2016-09-01 18:26 clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-lib -> llvm-ar
```

**Comment by segiddins** [comment] 2017-12-13 16:06
Thanks for looking into it! Sorry I didn't look further back in the issues, as it had just cropped up for us and reverting to the old image fixed it, so I assumed it was caused by the update. Let us know when you have a hot fix in place and I'd love to try it out!

**Comment by BanzaiMan** [comment] 2017-12-13 20:20
https://github.com/travis-ci/travis-build/pull/1272 has been merged and deployed. There may be additional fixes in the future, but users should no longer see this error.

**Closed by BanzaiMan** 2017-12-13 20:20 UTC
Labels: 2017-Q4-trusty-env-update
