### ISSUE TITLE
Django 1.10.1 is out and I have the link to the release notes python

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6527] opened 2016-08-26 13:44 UTC
I understand there may not have been a commit on the repo yet but I have a screenshot and a link to the release notes.
![screenshot_2016-08-26-14-41-19](https://cloud.githubusercontent.com/assets/20478546/18007337/89b081d2-6b9b-11e6-97ce-078a7cd2f841.png)
https://docs.djangoproject.com/en/1.10/releases/1.10.1/

**Comment by BanzaiMan** [comment] 2016-08-26 14:10
I'm closing this as a duplicate of #6502.

**Closed by BanzaiMan** 2016-08-26 14:10 UTC

**Comment by Monkeyboy2805** [comment] 2016-08-26 14:16
whaaaaaaaaaat? I am trying to help and you aren't doing anything about it?
