### ISSUE TITLE
Elastic Search Cannot start And i run sysctl -w vm.max_map_count=262144 

### ISSUE THREAD

**Issue by thedon007** [travis-ci/travis-ci#9092] opened 2018-01-18 10:09 UTC
shows error vm.max_map_count is  low and tried to fix using
![capture](https://user-images.githubusercontent.com/34158742/35092551-c604ca6a-fc65-11e7-9f64-0b6f0a37b16f.JPG)
shows like this

**Comment by BanzaiMan** [comment] 2018-01-18 18:59
Do you have a build log URL that shows the problem you are describing here?

That does not look like our build log.

**Comment by BanzaiMan** [comment] 2018-01-18 19:01
Assuming that you do see it in our builds, I am closing this as a duplicate of #6534.

**Closed by BanzaiMan** 2018-01-18 19:01 UTC
