### ISSUE TITLE
Python 3.3.6 should be compiled with -fPIC

### ISSUE THREAD

**Issue by msmolens** [travis-ci/travis-ci#6437] opened 2016-08-09 16:55 UTC
Compiling a Python extension with Python 3.3.6 now fails with the error:

    /usr/bin/ld: /opt/python/3.3.6/lib/libpython3.3m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
    /opt/python/3.3.6/lib/libpython3.3m.a: could not read symbols: Bad value

It looks like that Python 3.3 is no longer being compiled with -fPIC. Other versions of Python compile the extension successfully. 

An example failure is here:
https://travis-ci.org/scikit-build/scikit-build/jobs/150977762

**Comment by BanzaiMan** [comment] 2016-08-19 04:24
Hello. I've repackaged 3.3.6 with the same process as others. Could you test it with:

```yaml
python:
  - '3.3.6'
```

Thanks.

**Comment by msmolens** [comment] 2016-08-19 15:20
Thanks! I tested with version '3.3.6' specified explicitly, but still see get the same error:
https://travis-ci.org/scikit-build/scikit-build/jobs/153586295

Is it using the updated package?

**Comment by BanzaiMan** [comment] 2016-08-19 17:06
Ah, 3.3.6 is pre-installed, so the new package is not downloaded. Could you try `3.6-dev` (if your code is compatible)?

**Comment by BanzaiMan** [comment] 2016-08-19 19:20
Just realizing that this is a duplicate of #5333. Let us continue our discussion there.

**Closed by BanzaiMan** 2016-08-19 19:20 UTC
Labels: python

**Comment by BanzaiMan** [comment] 2016-08-19 19:27
Correction. The correct issue is #5533.

**Comment by msmolens** [comment] 2016-08-19 19:30
`3.6-dev` works: https://travis-ci.org/scikit-build/scikit-build/jobs/153650269
Will the build fix also be applied to version `3.3`?

**Comment by BanzaiMan** [comment] 2016-08-19 19:44
@msmolens See my comments in #5533.
