### ISSUE TITLE
Update git version in Container-based Trusty image

### ISSUE THREAD

**Issue by Chocobo1** [travis-ci/travis-ci#7416] opened 2017-03-03 06:37 UTC
Because I want to use `git submodule update --jobs=4 ...`
Current git version = 1.9.1, as it can be seen here: https://travis-ci.org/Chocobo1/rpcs3/jobs/207265096#L431
The version will need to be at least 2.9.

**Comment by BanzaiMan** [comment] 2017-03-03 06:43
Duplicate of #6328.

**Closed by BanzaiMan** 2017-03-03 06:43 UTC
