### ISSUE TITLE
Upgrade CMake to 2.8.11+ request

### ISSUE THREAD

**Issue by kaspermarstal** [travis-ci/travis-ci#3480] opened 2015-03-26 22:45 UTC
Hi

The ExternalData CMake module is a great way to manage large binary files etc without inflating the code repo size. We use it to manage our test data. This module is available in CMake >2.8.11 but Travis workers run 2.8.7 which effectively locks out any projects using this module from the container-based infrastructure (which is otherwise very nice, thank you very much) since sudo would be required to update CMake. 

Is it possible for you to upgrade your docker images to a newer version of CMake?

2.8.7 is more than three years old. 

Thank you for a wonderful build tool, we are very happy with Travis.

**Comment by BanzaiMan** [comment] 2015-03-27 03:44
At the moment, `cmake` is installed from the official Ubuntu package repository. For Precise, this is http://packages.ubuntu.com/precise/cmake, which puts us on 2.8.7. With the impending move to Trusty, I am of the opinion that spending much time on updating this component for Precise is not wise.

Having said that, you are welcome to look at https://github.com/travis-ci/travis-cookbooks/tree/master/ci_environment/cmake and update it to install it from source or an APT package from another PPA. We might be able to put that in for the next build environment update.

**Comment by kaspermarstal** [comment] 2015-03-27 15:29
It is only reasonable that you prefer to rely on official ubuntu repos. We are happy to hear that there *is* a move to Trusty in the works and this would be a solution in our case. Would you be able to give an estimate of when this is available? Just on an order of magnitude time scale, e.g. in a month, half year, year etc.

**Comment by dagar** [comment] 2015-03-31 23:36
I've been using ppa:kubuntu-ppa/backports to get cmake 2.8.12. I'd love to be able to get it through the docker infrastructure by whitelisting that ppa. https://github.com/travis-ci/travis-ci/issues/3530

**Comment by AmeBel** [comment] 2015-04-01 10:11
@BanzaiMan when is the "..impending move to Trusty" likely to occur?

**Comment by meatballhat** [comment] 2015-04-02 04:15
False alarm, sorry!

**Comment by BanzaiMan** [comment] 2015-04-02 04:56
@AmeBel We are alpha testing it currently.

**Comment by AmeBel** [comment] 2015-04-02 05:25
Great Thanks

**Comment by roidrage** [comment] 2015-07-23 18:41
Closing this as a duplicate of #2030.

**Closed by roidrage** 2015-07-23 18:41 UTC
