### ISSUE TITLE
Trouble encrypting with Travis gem

### ISSUE THREAD

**Issue by paololim** [travis-ci/travis-ci#5280] opened 2015-12-13 03:48 UTC
Hello there,

We are trying to encrypt using the Travis gem and have come across the following issue.

This is a log from the local laptop, for repo https://travis-ci.com/flowcommerce/authorization. Did a clean `gem install travis` and attempted to do according to the docs on the website.

It looks like the gem can't properly parse github with url `url = git@github.com:flowcommerce/authorization.git`.

Can you please advise?

```
[paolo @ ~/Flow/authorization] > travis encrypt BLAH=asdfasdfasdfasd
Invalid scheme format: git@github.com
for a full error report, run travis report

[paolo @ ~/Flow/authorization] > travis report
System
Ruby:                     Ruby 2.0.0-p645
Operating System:         Mac OS X 10.11.2
RubyGems:                 RubyGems 2.0.14

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-12-12 22:05:40 -0500

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "paololim"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis encrypt`:
    Addressable::URI::InvalidURIError: Invalid scheme format: git@github.com
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:867:in `scheme='
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:795:in `block in initialize'
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `defer_validation'
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:792:in `initialize'
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `new'
        from /Library/Ruby/Gems/2.0.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:71:in `detect_slug'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:60:in `find_slug'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:21:in `setup'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/command.rb:197:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by BanzaiMan** [comment] 2015-12-14 22:52
Looks like a duplicate of https://github.com/travis-ci/travis.rb/issues/342.

**Closed by BanzaiMan** 2015-12-14 22:52 UTC
