### ISSUE TITLE
cURL error 35: gnutls_handshake() failed: Handshake failed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html

### ISSUE THREAD

**Issue by markdza** [travis-ci/travis-ci#8912] opened 2017-12-13 20:30 UTC
Since yesterday (2017-12-12T17:32:11Z) our builds are getting the following error for Guzzle curl calls:

```
cURL error 35: gnutls_handshake() failed: Handshake failed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html
```

Any idea why the curl calls run fine on local and on our servers and only fails on Travis?

**Comment by BanzaiMan** [comment] 2017-12-13 22:27
Looks like a duplicate of #6339.

**Closed by BanzaiMan** 2017-12-13 22:27 UTC

**Comment by markdza** [comment] 2017-12-13 22:29
Could be the same but the error message is different
