### ISSUE TITLE
R: OSX build matrix feature request

### ISSUE THREAD

**Issue by imanuelcostigan** [travis-ci/travis-ci#6391] opened 2016-07-31 04:25 UTC
Is it possible to set up a build matrix to:

- Test against linux and OSX/macOS; AND
- Test against multiple R versions for at least one of these OS?

I [tried](https://github.com/imanuelcostigan/RSQLServer/blob/925bdda6449dac35024199b92af5e3032ea7cd5e/.travis.yml), and [failed](https://travis-ci.org/imanuelcostigan/RSQLServer/jobs/148617489#L369).

**Comment by imanuelcostigan** [comment] 2016-07-31 04:25
cc @craigcitro, @hadley, and @jimhester

**Comment by BanzaiMan** [comment] 2016-07-31 04:27
Probably a duplicate of #6385.

I'm closing this for now, unless there is a reason to separate it.

**Closed by BanzaiMan** 2016-07-31 04:27 UTC
