### ISSUE TITLE
Android: No tests found when running on Travis CI - Instrumentation run failed due to 'java.io.FileNotFoundException'

### ISSUE THREAD

**Issue by andrewhavens** [travis-ci/travis-ci#6488] opened 2016-08-16 07:30 UTC
I'm trying to get my Android tests running on Travis CI. I don't have any problems running the tests locally from the command line or through Android Studio. However, I'm getting this error when the build runs on Travis:

```
# ...
:MyappAndroid:packageMyappDebugAndroidTest
:MyappAndroid:assembleMyappDebugAndroidTest
:MyappAndroid:connectedMyappDebugAndroidTest
Tests on test(AVD) - 5.0.2 failed: Instrumentation run failed due to 'java.io.FileNotFoundException'

com.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 5.0.2] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
:MyappAndroid:connectedMyappDebugAndroidTest FAILED

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task :MyappAndroid:connectedMyappDebugAndroidTest'.
# ...
```

I've spent days chasing all sorts of different solutions and none of them have worked. Here is the current state of my `.travis.yml`:

```
---
language: android
jdk: oraclejdk7
# sudo: false # can't use this because running out of memory on containerized infrastructure
# Use "sudo: required" + "dist: precise" to increase available memory
sudo: required
dist: precise

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # again to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Emulator system images
    # - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - travis_wait ./gradlew clean testMyappDebugUnitTest connectedMyappDebugAndroidTest -PdisablePreDex --stacktrace
```

Any help figuring out a potential solution would be greatly appreciated. Thanks!

**Comment by BanzaiMan** [comment] 2016-08-17 19:03
Do you have a build log URL that shows the problem you are describing here?

**Comment by andrewhavens** [comment] 2016-08-17 19:46
@BanzaiMan https://travis-ci.com/yappbox/yapp-android/builds/29899424

**Comment by BanzaiMan** [comment] 2016-08-17 19:55
Thanks. I don't think we can diagnose this, since we don't have access to your code. We are happy to provide you with access to a live debug VM. Please email us at support@travis-ci.com.

I'm closing this here, since I do not think there is value in public discussion.

**Closed by BanzaiMan** 2016-08-17 19:55 UTC

**Comment by cliveleehere** [comment] 2017-07-27 15:13
curious to know whether there was a resolution to this problem. running into the same issue.

**Comment by yuriykulikov** [comment] 2017-08-10 19:31
Same here. Suddenly no tests can be found. No changes in travis or gradle files.

**Comment by mattvb91** [comment] 2017-11-06 20:35
@BanzaiMan @yuriykulikov any solution to this? Experiencing the same issue right now. All of a sudden the tests fail.

**Comment by luongvo** [comment] 2018-01-04 04:55
I also met the same issue, any solution? :(

**Comment by BanzaiMan** [comment] 2018-01-04 06:25
Try reproducing the problem with [our Docker images](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally).

**Comment by f4ww4z** [comment] 2019-03-01 01:02
2019: I met the same issue with emulator configuration of:
  - `android-18`
  - `armeabi-v7a`

My emulator startup command:

```yml
before_script:
- echo no | avdmanager create avd --force -n test -k "system-images;android-18;default;armeabi-v7a"
- $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
```
