### ISSUE TITLE
Many packages have gone missing

### ISSUE THREAD

**Issue by charris** [travis-ci/travis-ci#5223] opened 2015-12-05 20:36 UTC
```
$ sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran

E: Unable to locate package libatlas-dev

E: Unable to locate package libatlas-base-dev

E: Package 'gfortran' has no installation candidate
```

**Comment by BanzaiMan** [comment] 2015-12-05 21:09
I think this is a duplicate of #5221.

**Closed by BanzaiMan** 2015-12-05 21:09 UTC
