### ISSUE TITLE
The build has been terminated after Done. Your build exited with 0.

### ISSUE THREAD

**Issue by attiks** [travis-ci/travis-ci#9013] opened 2018-01-05 14:32 UTC
Build is not exiting properly, even if the command finish with exit code 0

After 10 minutes, travis kills the build and marks it as failed.

Since the repo is private, adding config and log below

`.travis.yml` file

```
dist: trusty
language: php

php:
  - 7.1

before_script:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Code sniff
  - cd $TRAVIS_BUILD_DIR
  - composer install
  - $TRAVIS_BUILD_DIR/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer

script:
  - $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/sites/all/modules/custom
  
```

```
$ $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/sites/all/modules/custom
.....................................
Time: 3.79 secs; Memory: 14Mb
The command "$TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/sites/all/modules/custom" exited with 0.
Done. Your build exited with 0.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by BanzaiMan** [comment] 2018-01-05 14:42
Looks like a duplicate of #8898.

**Closed by BanzaiMan** 2018-01-05 14:42 UTC

**Comment by attiks** [comment] 2018-01-05 14:55
"Fixed" by simplifying travis to

```
dist: trusty
language: php

php:
  - 7.1

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer install

script:
  - $TRAVIS_BUILD_DIR/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/sites/all/modules/custom
```
