### ISSUE TITLE
container-based infra does not catch failed apt install

### ISSUE THREAD

**Issue by yann-morin-1998** [travis-ci/travis-ci#5343] opened 2015-12-20 22:16 UTC
Hello!

When a container-based job has instructions to install extra
packages with the `apt` addon, failures to install those
packages are not caught, which causes build issues.

For example, for the Buildroot project, we have a job that
fails because of that:
    https://travis-ci.org/buildroot/buildroot-defconfig-testing/jobs/97773509

Excerpt:

```
Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.12
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com/ubuntu/ precise/main gcc-multilib amd64 4:4.6.3-1ubuntu5
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main bc amd64 1.06.95-2ubuntu1
  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Fetched 18.6 MB in 2min 19s (133 kB/s)
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6-dev_2.15-0ubuntu10.12_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc-multilib_4.6.3-1ubuntu5_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/b/bc/bc_1.06.95-2ubuntu1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.13 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

However, for some other jobs, it works without issue, for example:
    https://travis-ci.org/buildroot/buildroot-defconfig-testing/jobs/97773507

Our Travis configuration is at:
    https://github.com/buildroot/buildroot-defconfig-testing

Thanks!

**Comment by BanzaiMan** [comment] 2015-12-20 22:27
Duplicate of #5077.

**Closed by BanzaiMan** 2015-12-20 22:27 UTC

**Comment by yann-morin-1998** [comment] 2015-12-20 22:31
OK, I'll follow that other PR, then.
Thanks for the quick feedback! :-)
