### ISSUE TITLE
Build incorrectly tagges as failed?

### ISSUE THREAD

**Issue by andig** [travis-ci/travis-ci#7274] opened 2017-02-05 10:44 UTC
See https://travis-ci.org/volkszaehler/volkszaehler.org/jobs/198522736 which is imho a passing bild yet shows as "failed"?

**Comment by BanzaiMan** [comment] 2017-02-05 14:22
Thanks for reporting. This looks like a duplicate of #7264.

**Closed by BanzaiMan** 2017-02-05 14:22 UTC
