### ISSUE TITLE
Oracle JDK 7 doesn't work anymore

### ISSUE THREAD

**Issue by jqno** [travis-ci/travis-ci#8509] opened 2017-09-27 13:11 UTC
My `oraclejdk7` build fail consistently, before the actual build even starts. Looks like something is wrong in the environment on the build node.

Here's a link to the build in question: https://travis-ci.org/jqno/equalsverifier/jobs/279408169

Here's the log:

<img width="808" alt="screen shot 2017-09-27 at 15 10 42" src="https://user-images.githubusercontent.com/862385/30915138-19ff23b4-a396-11e7-8b84-cec83ef5f70f.png">

**Comment by BanzaiMan** [comment] 2017-09-27 15:22
Duplicate of https://github.com/travis-ci/travis-ci/issues/7884. Please use Precise if you need to use Oracle JDK 7.

**Closed by BanzaiMan** 2017-09-27 15:22 UTC
