### ISSUE TITLE
Xcode 9.3

### ISSUE THREAD

**Issue by asalom** [travis-ci/travis-ci#9442] opened 2018-04-04 08:27 UTC
Any update when this will be available?

EDIT. I'm trying  to compile with Swift 4.1

**Comment by BanzaiMan** [comment] 2018-04-04 11:28
Duplicate of #9416.

**Closed by BanzaiMan** 2018-04-04 11:28 UTC

**Comment by asalom** [comment] 2018-04-04 11:40
Is there anyway to compile with Swift 4.1? Not mentioned in #9416

**Comment by BanzaiMan** [comment] 2018-04-04 12:43
https://docs.travis-ci.com/user/reference/osx/#OS-X-Version Does `xcode: 9.3beta` meet your requirement?

**Comment by asalom** [comment] 2018-04-04 13:38
We tried with `osx_image: xcode9.3beta` and Swift version was still 4.0

**Comment by asalom** [comment] 2018-04-04 13:42
You can see the problem here: https://travis-ci.com/crvshlab/goat-ios/jobs/117706514
Config says
```

{
  "os": "osx",
  "osx_image": "xcode9.3beta",
  ...
}
```

Error log says: `... module file was created by a newer version of the compiler: ...`

**Comment by BanzaiMan** [comment] 2018-04-04 13:47
Thanks. It means currently it is not possible to test it. Please subscribe to the other issue, so that you'd be notified of any future update.

**Comment by ikesyo** [comment] 2018-04-10 11:17
Finally `xcode9.3` image has come! 

https://twitter.com/travisci/status/983523079593881600

But we didn’t get any news on GitHub. It’s very sad 😞
