### ISSUE TITLE
Final Status is not Correct

### ISSUE THREAD

**Issue by zjhzxhz** [travis-ci/travis-ci#3095] opened 2015-01-09 09:43 UTC
There are two continuous commit for a repository.

Build 12 ran successfully and Build 11 exited with error.
I found that the final status of the repository is error.

Maybe the reason of the bug is that I commit using `commit --amend`, and commit sha1 the build of 11 and 12 is the same: `7a008ac84ee915cf6d8ee9b6b8aa18c6e16422fa`.

But it sure is a bug. Please fix it.

My Travis CI Reposotory: https://travis-ci.org/zjhzxhz/TestZilla/builds

**Comment by BanzaiMan** [comment] 2015-01-09 12:16
Currently, the badge status reflect that of the build which finished most recently. In your case, it is build 19, not 20. If you restart 20 and when it passes, you'll see what you want.

**Comment by JamesMGreene** [comment] 2015-01-12 16:01
Duplicate of #483 / #1781?

**Comment by BanzaiMan** [comment] 2015-01-12 16:20
Indeed.

**Closed by BanzaiMan** 2015-01-12 16:20 UTC
