### ISSUE TITLE
Build fails with PHP_CodeSniffer, PHP 7.0 dist:trusty

### ISSUE THREAD

**Issue by apw1388** [travis-ci/travis-ci#8232] opened 2017-08-09 09:43 UTC
Hi,

after Trusty replaced Precise, the build with PHP 7.0 and CodeSniffer began to fail. It can't find some files. Using dist: precise will pass the build.
Build log: https://travis-ci.org/EUDAT-B2DROP/b2drop-theme/builds/262571563

.travis.yml:
language: php
php:
  - 7.0

install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --extensions=php --ignore=*/tests/*,*/templates/* .

**Comment by s3b4stian** [comment] 2017-08-09 10:33
I have similar problems but the guilty should be Phpunit
https://github.com/travis-ci/travis-ci/issues/8211

**Comment by BanzaiMan** [comment] 2017-08-14 13:36
Could you try `php: 7.0.21`?

**Comment by apw1388** [comment] 2017-08-15 05:51
Hi @BanzaiMan 
with php 7.0.21 everything is fine. Thanks for the hint.

**Comment by BanzaiMan** [comment] 2017-08-16 00:10
OK. I think this is a duplicate of #8211. The current PHP 7.0 has a dubious PHPUnit installation. It should be updated with the next build image update.

I'm closing this in the mean time.

**Closed by BanzaiMan** 2017-08-16 00:10 UTC
Labels: php
