### ISSUE TITLE
PHPUnit 6.x and PHP 5.6 compatibility

### ISSUE THREAD

**Issue by dregad** [travis-ci/travis-ci#7453] opened 2017-03-10 23:17 UTC
On 09-Mar-2016, [our builds started failing](https://travis-ci.org/mantisbt/mantisbt/builds) without significant change on our side. After a bit of research, it appeared to be caused by a change in PHPUnit version (upgrade to 6.0.8).

PHPUnit 6.0.8 only supports PHP >= 7.0, yet it was used for PHP 5.6 builds as well. 
PHP <= 5.5 builds remained unaffected (i.e. completing successfully), as Travis seems to be using an older version of PHPUnit in this case.

I would expect Travis to set the default PHPUnit to a version that is compatible with the currently running PHP version, i.e. for PHP 5.6, it should use PHPUnit 5.7.

**Comment by BanzaiMan** [comment] 2017-03-10 23:25
This should be a duplicate of https://github.com/travis-ci/travis-ci/issues/7448 and fixed now. Please rerun the failing build(s).

Let us know if you continue to see the problem. Thanks.

**Closed by BanzaiMan** 2017-03-10 23:25 UTC

**Comment by dregad** [comment] 2017-03-11 20:51
> This should be a duplicate of #7448 and fixed now

I apologize for missing the duplicate bug report. I did search for it, but did not think of searching in closed issues.

I just re-ran the failed builds as you suggested, and they are [successful](https://travis-ci.org/mantisbt/mantisbt/jobs/209250218), so I confirm your patch did the trick.

Many thanks for the quick response and for fixing the issue !
