### ISSUE TITLE
sauceconnect tunnels are not shut down if build is killed

### ISSUE THREAD

**Issue by tristanbes** [travis-ci/travis-ci#5304] opened 2015-12-15 16:07 UTC
Hello,

Sauceconnect tunnels to saucelabs website are not shut down if the build is stopped.

So it means that future builds will fails because there are a limitation of X (5 for us) open tunnels until we manually kill them in the saucelabs website or wait them to be timeout killed.

**Comment by BanzaiMan** [comment] 2015-12-19 16:09
I think this is a duplicate of #3091.

**Closed by BanzaiMan** 2015-12-19 16:09 UTC
