### ISSUE TITLE
APT whitelist request for liboctave-dev

### ISSUE THREAD

**Issue by cbm755** [travis-ci/travis-ci#4487] opened 2015-07-20 21:34 UTC
Split out from #4279 as per https://github.com/travis-ci/travis-ci/issues/4279#issuecomment-123048502

please label: `apt-whitelist`

**Comment by BanzaiMan** [comment] 2015-07-23 11:57
I'm going to close this one as a duplicate of #4486, assuming that a single source package (from the requested source) will define both `octave` and `liboctave-dev`.

**Closed by BanzaiMan** 2015-07-23 11:57 UTC
Labels: apt-source-whitelist, apt-whitelist, apt-whitelist-check-run
