### ISSUE TITLE
PR links from merge commits are broken

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#7568] opened 2017-04-04 17:01 UTC
Click on a link like the one hovered over below (see image) results in a link like ( https://github.com/[object%20Object]/staged-recipes/issues/2738 ), which doesn't have the org in it. So it leads to a non-existent location.

Guessing something just didn't get converted to a string properly in some code somewhere. Just noticed this in the past couple of days, so is probably in some recent change.

<img width="1552" alt="screen shot 2017-04-04 at 12 58 39" src="https://cloud.githubusercontent.com/assets/3019665/24668960/8bc32422-1936-11e7-8076-fd4546bf9765.png">

ref: https://travis-ci.org/conda-forge/staged-recipes/builds

**Comment by BanzaiMan** [comment] 2017-04-04 17:44
Duplicate of #7415.

**Closed by BanzaiMan** 2017-04-04 17:44 UTC

**Comment by jakirkham** [comment] 2017-04-04 17:46
Sorry, missed that when searching.
