### ISSUE TITLE
OS X: One more job than matrix include row · no custom environment variables

### ISSUE THREAD

**Issue by jdhealy** [travis-ci/travis-ci#6404] opened 2016-08-02 18:05 UTC
Hey amazing Travis people :wave:, seeing some troubling behavior,

[With `os: osx` and a 10 row `matrix` `include`](https://github.com/jdhealy/PrettyColors/blob/6c75913135c58e31db8836feaf8a4eafd3c3d477/.travis.yml), a [resulting build has 11 jobs](https://travis-ci.org/jdhealy/PrettyColors/builds/149002237), where [the first job doesn’t set any environment variables from .travis.yml](https://travis-ci.org/jdhealy/PrettyColors/jobs/149002238#L36), resulting in the job-therefore-build failing.

Curious as to why [this `.travis.yml`](https://github.com/ikesyo/PrettyColors/blob/72cce2110939653d97e4bd557eddd1b5f61f4aed/.travis.yml) results in [a build with the desired 10 jobs](https://travis-ci.org/ikesyo/PrettyColors/builds/147187219)?

**Comment by BanzaiMan** [comment] 2016-08-03 01:51
Looks like a duplicate of https://github.com/travis-ci/travis-ci/issues/4681.

**Closed by BanzaiMan** 2016-08-03 01:51 UTC
Labels: matrix expansion
