### ISSUE TITLE
API Linting warns about valid node_js versions

### ISSUE THREAD

**Issue by kevinoid** [travis-ci/travis-ci#5609] opened 2016-02-11 19:15 UTC
Linting a `.travis.yml` file which contains `stable`, `node`, or any major version without minor version in `node_js` causes a warning.  These values do work correctly during builds and are documented to work.  The first two aliases are mentioned explicitly in [Choosing Node versions to test against](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#choosing-node-versions-to-test-against) while the major-without-minor version is included in the "any version or alias of Node or io.js that nvm can install" phrasing.

For example, with the following content in `.travis.yml`:

```yaml
language: node_js
node_js:
  - node
  - iojs
  - 4
  - 0.12
  - 0.10
sudo: false
```

Running the command

```sh
curl -T .travis.yml https://api.travis-ci.org/lint
```

Returns the following JSON:

```json
{
  "lint": {
    "warnings": [
      {
        "key": [
          "node_js"
        ],
        "message": "value \"node\" is not a valid version"
      },
      {
        "key": [
          "node_js"
        ],
        "message": "value \"4\" is not a valid version"
      }
    ]
  }
}
```

Thanks,
Kevin

**Comment by BanzaiMan** [comment] 2016-02-26 01:24
Duplicate of #4852.

**Closed by BanzaiMan** 2016-02-26 01:24 UTC
Labels: travis-yaml

**Comment by kevinoid** [comment] 2016-02-26 01:26
Right you are.  Not sure how I missed that.  Sorry for the extra noise.
