### ISSUE TITLE
[Feature Request] Share environment variables across repositories

### ISSUE THREAD

**Issue by clekstro** [travis-ci/travis-ci#5987] opened 2016-05-03 09:57 UTC
A user [contacted support](https://secure.helpscout.net/conversation/197213898/28522/?folderId=30784) to request that we support shared environment variables across multiple repositories. They're currently having to copy the same encrypted API keys across repositories. Allowing customers to set environment variables at the organization level would make creating new projects easier (less initial config) while also reducing their maintenance burden when those configuration values change.

**Comment by BanzaiMan** [comment] 2016-05-03 16:18
This is a duplicate of #2069. For now, we suggest using the API (and CLI client) to automate the process.

**Closed by BanzaiMan** 2016-05-03 16:18 UTC
Labels: feature-request

**Comment by clekstro** [comment] 2016-05-03 16:31
@BanzaiMan Sorry. Searched for other "environment variables" issues but didn't see that one!
