### ISSUE TITLE
Go test coverage command not available in for some go versions

### ISSUE THREAD

**Issue by tantalic** [travis-ci/travis-ci#8095] opened 2017-07-15 00:25 UTC
As mentioned by @BanzaiMan in #8066 the go test coverage command is not available in the following Go versions:

- **go1.2.1**: https://travis-ci.org/tantalic/travis-go-vet/jobs/253800359
- **go1.4.3**: https://travis-ci.org/tantalic/travis-go-vet/jobs/253800382

**Comment by BanzaiMan** [comment] 2017-07-15 00:56
Closing this as a duplicate of #8066, which I just reopened.

**Closed by BanzaiMan** 2017-07-15 00:56 UTC
