### ISSUE TITLE
Webhook build repository url returning null

### ISSUE THREAD

**Issue by skiwi2** [travis-ci/travis-ci#2935] opened 2014-11-05 14:06 UTC
The webhook build repository url is returning null for our repository.

We are getting such messages posted to our StackExchange chatroom:

```
[[Cardshifter/Cardshifter](null)] build #630 for commit [a85d702f](null/commit/a85d702f51cadbdd551140e24772b1022d495a09) on branch [issue129-ecs-attributes](null/tree/issue129-ecs-attributes) passed
```

So I am pretty sure that the build repository url is null for some reason, has the webhook API changed within the last week?

First repeating occurence seems to have been on Nov 04 11:02 AM GMT+1, whereas a random occurence has been spotted on Oct 14 7:17 PM GMT+1.

The repository it happened at is https://travis-ci.org/Cardshifter/Cardshifter.

**Comment by grit96** [comment] 2015-02-13 15:02
I'm having the same problem trying to make [itsapi/github-listener](http://github.com/itsapi/github-listener) compatible with Travis webhooks.

```
{
  "id": 50624203,
  "repository": {
    "id": 2171466,
    "name": "github-listener",
    "owner_name": "itsapi",
    "url": null
  },
...
```

**Comment by BanzaiMan** [comment] 2015-02-13 16:39
@grit96 For yours, I see these errors in the log:

```
Feb 13 12:22:25 travis-tasks app/tasks.1:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:27:14 travis-tasks app/tasks.3:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:30:27 travis-tasks app/tasks.3:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:39:21 travis-tasks app/tasks.3:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:43:11 travis-tasks app/tasks.2:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=502 message="<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n" 
Feb 13 12:45:36 travis-tasks app/tasks.3:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:47:25 travis-tasks app/tasks.1:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:50:40 travis-tasks app/tasks.1:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=502 message="<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n" 
Feb 13 12:51:51 travis-tasks app/tasks.1:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 12:53:29 travis-tasks app/tasks.2:  E [task] task=webhook status=error build=50624203 url=http://geraint.ngrok.com error_code=400 message="Error: Invalid payload" 
Feb 13 16:13:15 travis-tasks app/tasks.3:  E [task] task=webhook status=error build=50651848 url=http://geraint.ngrok.com error_code=404 message="Tunnel geraint.ngrok.com not found\n" 
```

Yes, the errors need to be communicated better with users.

**Comment by grit96** [comment] 2015-02-13 16:43
I know why the errors occur, because I have been developing my webhook
handler. The problem I see is in the payload my app receives from Travis,
with the repository URL field blank.
Would this have anything to do with manually rerunning the build rather
than triggering it from GitHub?

**Comment by grit96** [comment] 2015-02-13 17:40
@BanzaiMan How do I see the webhook logs?

**Comment by BanzaiMan** [comment] 2015-02-13 17:46
@grit96 No, it wouldn't.

I've looked at this in more detail, and I found that `repository.url` was populated from GitHub's `homepage` field (see https://developer.github.com/v3/repos/), which you can add in this form: 
![banzaiman_travis_production_test](https://cloud.githubusercontent.com/assets/25666/6192219/be98bf68-b37d-11e4-9229-bf004e19d4e1.png)

Once you have that, you can [resync](https://travis-ci.org/profile) your user data (or wait for the daily resync to kick in), and you should see the field populated.

**Comment by grit96** [comment] 2015-02-13 18:05
Thanks a lot, that worked. It's interesting that Travis does not send the GitHub URL with the payload - it seems logical to me that `repository.url` would be the GitHub URL.

**Comment by BanzaiMan** [comment] 2015-02-13 19:02
Thanks for the confirmation. I'm going to close this, since this is the expected behavior.

You can concoct the GitHub url with

```javascript
'https://github.com/' + repository.owner_name + '/' repository.name
```

**Closed by BanzaiMan** 2015-02-13 19:02 UTC
