### ISSUE TITLE
ECC keys not supported on travis.com

### ISSUE THREAD

**Issue by stites** [travis-ci/travis-ci#8715] opened 2017-11-06 18:10 UTC
Not sure if this is a UI-specific bug, but my EC private key wasn't read as a valid private key.

**Comment by BanzaiMan** [comment] 2017-11-06 21:06
What private key are you talking about? Do you have a build log URL that shows the problem you are describing here?

**Comment by stites** [comment] 2017-11-06 22:13
No, this is something in the UI. I couldn't upload a private EC key in the settings page to give travis the credentials to clone a company repository. Uploading an RSA key works as expected. Here's roughly a screenshot of what I'm seeing:

![screenshot-2017-11-6 sentenai sentenai-research - travis ci 1](https://user-images.githubusercontent.com/1694705/32466690-c7c93360-c315-11e7-9485-18470dfc789d.png)


< then the actual key > 


![screenshot-2017-11-6 sentenai sentenai-research - travis ci 2](https://user-images.githubusercontent.com/1694705/32466699-cca5f2a6-c315-11e7-9d41-23f5deb60205.png)

**Comment by BanzaiMan** [comment] 2017-11-06 23:07
Duplicate of #2720.

**Closed by BanzaiMan** 2017-11-06 23:07 UTC
