### ISSUE TITLE
Git push to remote causes "remote" at start of log lines

### ISSUE THREAD

**Issue by OmgImAlexis** [travis-ci/travis-ci#7284] opened 2017-02-07 03:59 UTC
Here's what I get when I run the same command locally.
```
➜  medusa.github.io git:(master) ✗ git push deploy master
Counting objects: 1500, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (682/682), done.
Writing objects: 100% (1500/1500), 7.23 MiB | 1.15 MiB/s, done.
Total 1500 (delta 778), reused 1483 (delta 772)
-----> Cleaning up...
-----> Building cdn.pymedusa.com from dockerfile...
-----> Setting config vars
       DOKKU_DOCKERFILE_PORTS: 5000
-----> Setting config vars
       DOKKU_DOCKERFILE_CMD: CMD ["caddy", "--conf", "/etc/Caddyfile"]
remote: Sending build context to Docker daemon 5.857 MB
Step 1 : FROM alpine:3.3
 ---> 00b92c86273f
Step 2 : MAINTAINER Alexis Tyler <xo@wvvw.me>
 ---> Using cache
 ---> a6a769a3ea3e
Step 3 : RUN apk --no-cache add git openssh-client     && apk --no-cache add --virtual devs tar curl
 ---> Using cache
 ---> bc252e9e7bc9
Step 4 : RUN curl "https://caddyserver.com/download/build?os=linux&arch=amd64&features=DNS%2Cawslambda%2Ccors%2Cexpires%2Cfilemanager%2Cgit%2Chugo%2Cipfilter%2Cjsonp%2Cjwt%2Clocale%2Cmailout%2Cminify%2Cmultipass%2Cprometheus%2Cratelimit%2Crealip%2Csearch%2Cupload%2Ccloudflare%2Cdigitalocean%2Cdnsimple%2Cdyn%2Cgandi%2Cgooglecloud%2Clinode%2Cnamecheap%2Crfc2136%2Croute53%2Cvultr"     | tar --no-same-owner -C /usr/bin/ -xz caddy
 ---> Using cache
 ---> f088dd40acd5
Step 5 : RUN apk del devs
 ---> Using cache
 ---> 6b415aef2b89
Step 6 : RUN mkdir -p /var/www/html
 ---> Using cache
 ---> fa418b5055b0
Step 7 : WORKDIR /var/www/html
 ---> Using cache
 ---> 610d5f0ea3fd
Step 8 : ADD /static/ .
 ---> 74fe990d1e23
Removing intermediate container e4487020c3f9
Step 9 : ADD Caddyfile /etc/Caddyfile
 ---> 202764efee43
Removing intermediate container befaf97155ad
Step 10 : EXPOSE 5000
 ---> Running in 7fea71e42e2e
 ---> 8b9ba65e0d5e
Removing intermediate container 7fea71e42e2e
Step 11 : CMD caddy --conf /etc/Caddyfile
 ---> Running in fce699221ec1
 ---> b161f8489313
Removing intermediate container fce699221ec1
Successfully built b161f8489313
-----> Releasing cdn.pymedusa.com (dokku/cdn.pymedusa.com:latest)...
-----> Deploying cdn.pymedusa.com (dokku/cdn.pymedusa.com:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> No Procfile found in app image
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
=====> renaming container (d9025218a81d) condescending_goldstine to cdn.pymedusa.com.web.1
-----> Configuring cdn.pymedusa.com...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
=====> Application deployed:
       http://cdn.pymedusa.com

To 198.211.102.17:cdn.pymedusa.com
 * [new branch]      master -> master
```

Where as travis shows this.
```
 git push deploy master
Counting objects: 3, done.
Delta compression using up to 32 threads.
Compressing objects: 100% (1/1)   Compressing objects: 100% (1/1), done.
Writing objects: 100% (2/2)   Writing objects: 100% (2/2), 599 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 2 (delta 1)
remote: remote: edusa.com from dockerfile...
remote: remote: 
remote: remote: remote: e>
remote: remote: remote: remote: remote: remote: /download/build?os=linux&arch=amd64&features=DNS%2Cawslambda%2Ccors%2Cexpires%2Cfilemanager%2Cgit%2Chugo%2Cipfilter%2Cjsonp%2Cjwt%2Clocale%2Cmailout%2Cminify%2Cmultipass%2Cprometheus%2Cratelimit%2Crealip%2Csearch%2Cupload%2Ccloudflare%2Cdigitalocean%2Cdnsimple%2Cdyn%2Cgandi%2Cgooglecloud%2Clinode%2Cnamecheap%2Crfc2136%2Croute53%2Cvultr"     | tar --no-same-owner -C /usr/bin/ -xz caddy
remote: remote: remote: remote: K
remote: remote: kdir -p /var/www/html
remote: remote: remote: l
remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: remote: edusa.com (dokku/cdn.pymedusa.com:latest)...
remote: edusa.com (dokku/cdn.pymedusa.com:latest)...
remote: pting to run scripts.dokku.predeploy from app.json (if defined)
remote: age
remote: e/dokku/cdn.pymedusa.com/DOKKU_SCALE)
remote: remote: pting pre-flight checks
remote: ore efficient zero downtime deployments, create a file CHECKS.
remote: ent/zero-downtime-deploys/ for examples
remote: ple container check...
remote: remote: remote: remote: ed cdn.pymedusa.com.web.1
remote: ing container (d9025218a81d) cdn.pymedusa.com.web.1 to cdn.pymedusa.com.web.1.1486439876
remote: ing container (9c02db7ff552) dreamy_curran to cdn.pymedusa.com.web.1
remote: edusa.com...(using built-in template)
remote: remote: remote: remote: remote: remote: pting to run scripts.dokku.postdeploy from app.json (if defined)
remote: remote: remote: remote: edusa.com
remote: To dokku@198.211.102.17:cdn.pymedusa.com
   c67ea1c..e72b05d  master -> master
```

For exmaple: https://travis-ci.org/pymedusa/medusa.github.io/builds/199082412

**Comment by BanzaiMan** [comment] 2017-03-07 01:34
I tend to think that `remote:` is coming from, well, the remote you are using. Using github.com, for example, this build does not show `remote:` prefix. https://travis-ci.org/krlmlr/testTestthat/builds/169613645#L874

The local output defines the remote as `198.211.102.17:cdn.pymedusa.com`, while on Travis it is `dokku@198.211.102.17:cdn.pymedusa.com`. Can this difference explain the problem?

**Comment by OmgImAlexis** [comment] 2017-03-07 02:39
That doesn't change anything at all as locally I just have dokku setup in my git config.
I tried using dokku@ locally and I get the same results.

I noticed travis has similar issues when connecting via ssh and the remote is sending back coloured output. It's something to do with how Travis parses the response.

**Comment by OmgImAlexis** [comment] 2017-03-07 02:40
@josegonzalez may have some insight into this as he's one of the dokku devs.

**Comment by BanzaiMan** [comment] 2017-03-07 03:11
Ah, sorry about that. I should've checked the raw data. In https://s3.amazonaws.com/archive.travis-ci.org/jobs/199082413/log.txt, you see lines such as 

```
remote: [1G-----> Releasing cdn.pymedusa.com (dokku/cdn.pymedusa.com:latest)...[K
remote: [1G-----> Deploying cdn.pymedusa.com (dokku/cdn.pymedusa.com:latest)...[K
remote: [1G-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)[K
remote: [1G-----> No Procfile found in app image[K
remote: [1G-----> DOKKU_SCALE file found (/home/dokku/cdn.pymedusa.com/DOKKU_SCALE)[K
remote: [1G=====> web=1[K
```

The remote is sending `\[1G`, to move the cursor to the column 1, but in our stream-oriented log display these are just ignored. So, this is a duplicate of https://github.com/travis-ci/travis-ci/issues/1951.

I'm closing this, as we are not planning to support this ANSI sequence.

**Closed by BanzaiMan** 2017-03-07 03:11 UTC
Labels: travis-web
