### ISSUE TITLE
PyPi deployment marked successful even if authentication failed

### ISSUE THREAD

**Issue by benoit-pierre** [travis-ci/travis-ci#8416] opened 2017-09-13 21:05 UTC
Running a tagged build for setuptools on my personal repository triggered the deploy stage (as expected), but said deploy stage and job were marked as successful even though the authentication to PyPi failed (as expected):

```
Uploading setuptools-36.4.0-py2.py3-none-any.whl
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
Done. Your build exited with 0.
```

Full log here: https://travis-ci.org/benoit-pierre/setuptools/jobs/275208856

**Comment by BanzaiMan** [comment] 2017-09-13 21:29
This is a general problem with deployment failure not marking the build a failure.

Closing as a duplicate of https://github.com/travis-ci/travis-ci/issues/921 (deployment being a special kind of `after_success`).

**Closed by BanzaiMan** 2017-09-13 21:29 UTC
