### ISSUE TITLE
Container-based infrastructure fails to download file from www.cs.utah.edu

### ISSUE THREAD

**Issue by samth** [travis-ci/travis-ci#3012] opened 2014-12-10 17:37 UTC
This build: https://travis-ci.org/racket/rackunit/builds/43613280 seems to fail to download anything on the container-based travis. I have other travis builds that download that file from that host just fine, but I just tried the container version, and it just gets stuck. I cancelled and tried again, and it still got stuck.

**Comment by samth** [comment] 2015-01-02 23:02
Switching to a different server with the same content fixed the issue, but since this works fine from multiple systems here (at Indiana University) and from my Digital Ocean droplet, and from Travis builds in the non-docker version, it seems unlikely that it's a server issue.

**Comment by krono** [comment] 2015-01-06 14:33
Same for this: https://travis-ci.org/samth/pycket/jobs/46050004

**Comment by BanzaiMan** [comment] 2015-01-06 17:24
Since other servers work, this is an issue with the interaction between the server and the client. I don't know what the issue is. If you have any suggestion to troubleshoot further, we'd appreciate it.

**Comment by roidrage** [comment] 2015-01-06 17:30
Would be interesting to reproduce this from a bare EC2 instance to see if the virtual Docker network stack might somehow be involved?

But if not, then this is a connectivity issue between them and EC2, maybe they're even blocking it?

**Comment by samth** [comment] 2015-01-06 17:36
This works _on Travis_ from the same server in the non-container-based infrastructure. See, for example, https://travis-ci.org/racket/typed-racket/builds/45949715 which downloads exactly the same file, successfully, yesterday.

Are other Travis builds also on EC2?

I will test this command on another EC2 system.

**Comment by BanzaiMan** [comment] 2015-01-06 17:53
Workers on the [standard infrastructure](http://docs.travis-ci.com/user/workers/standard-infrastructure/) do not run on EC2.

**Comment by samth** [comment] 2015-01-06 18:13
I (or rather @tonyg) just tested the relevant command (below) on a newly created t2.micro instance in us-west-2c. It worked fine. Is there something else I can try to help check what's going on here? Should I spin up docker?

`curl -L -o out.sh http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-6.1.1.6-x86_64-linux-precise.sh`

**Comment by BanzaiMan** [comment] 2015-01-06 19:41
Interesting. Sorry, but I don't have any other suggestion at the moment. The name resolves, and the HTTP connection is made, but the server is not sending any data back. https://travis-ci.org/BanzaiMan/travis_production_test/builds/46111016

**Comment by krono** [comment] 2015-01-06 19:46
The Travis-CI documentation talks about the boxes (presumably the non-docker ones) have an IPv6 but no public IPv4, which be however not a problem, downloading should work. Indeed, it does no the non-docker boxes. 

Could there be a problem in this area? (Eg, some special IPv6 addresses used, just guessing)

**Comment by henrikhodne** [comment] 2015-01-06 20:26
I just checked this from a server on the same network `curl http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-6.1.1.6-x86_64-linux-precise.sh` stalls (before sending any data), but `curl -i http://www.cs.utah.edu/plt/snapshots/current/installers/min-racket-6.1.1.6-x86_64-linux-precise.sh` returns the right headers immediately.

Not quite sure what that means yet, but it seems like we are able to connect to the web server just fine, and the error happens when we attempt to GET the URL.

**Comment by samth** [comment] 2015-01-09 00:15
@henrikhodne Did you see the stall on that network with or without docker? And can you say more about the network -- my contacts at Utah don't think there's anything weird about their server.

**Comment by dopplershift** [comment] 2015-01-26 18:15
I'm seeing this here trying to run tests that hit some of our servers. The following two servers stall:
- http://thredds.ucar.edu
- http://atm.ucar.edu
while these work:
- http://thredds-test.unidata.ucar.edu
- http://thredds-dev.unidata.ucar.edu
- http://unidata2-new.ssec.wisc.edu

While we usually hit some lower pages on the server, testing revealed a simple `curl -vv` on the top level index will stall. I hadn't tried the `curl -I` trick mentioned above, but I have seen that occasionally the `curl -vv` will show that the header is received and just the rest of the GET fails. Switching back to the non-Docker infrastructure allowed the connections to work with no problem.

**Comment by BanzaiMan** [comment] 2015-06-02 02:33
I just tested the original server about which this issue was reported (https://travis-ci.org/BanzaiMan/travis_production_test/builds/65017911#L92; www.cs.utah.edu). It is working now, and I am closing this issue optimistically.

**Closed by BanzaiMan** 2015-06-02 02:33 UTC
Labels: awaiting-followup, docker

**Comment by samth** [comment] 2015-06-02 03:29
Awesome -- I just reran the specific build that failed, and it worked. Thanks!

**Comment by dopplershift** [comment] 2015-06-02 13:53
Works for me now here too. Out of curiosity, any idea what fixed it?

**Comment by henrikhodne** [comment] 2015-06-02 16:10
We changed the MTU from AWS' default of 9001 down to 1500, which fixed a lot of similar network issues. I think that is what caused this too.

**Comment by samth** [comment] 2015-09-30 16:42
This just started happening again. You can see it failing here: https://travis-ci.org/samth/pycket/jobs/82860393

and working here (on the old infra): https://travis-ci.org/samth/pycket/jobs/82958719

It worked on the container infra two days ago: https://travis-ci.org/samth/pycket/builds/82641009
