### ISSUE TITLE
Add Python to OSX Image

### ISSUE THREAD

**Issue by gfyoung** [travis-ci/travis-ci#6931] opened 2016-11-24 20:54 UTC
I have been trying to use Python with OSX, and according to the <a href="https://docs.travis-ci.com/user/osx-ci-environment/#Python-related-tools">docs</a>, the image should contain Python-related tools, though strangely no mention of Python <a href="https://docs.travis-ci.com/user/osx-ci-environment/#Languages">here</a>.  However, when I attempted to use `virtualenv` for example, the command just fails, as you can see <a href="https://travis-ci.org/gfyoung/scipy/jobs/178689827">here</a>.

It would be great if Python (with `pip` and `virtualenv`) could come out of the box.  If it does, then the documentation needs to be updated.

**Comment by BanzaiMan** [comment] 2016-11-24 23:26
Thanks for taking time to open the issue.

I'm closing this as a duplicate of #2312.

**Closed by BanzaiMan** 2016-11-24 23:26 UTC
