### ISSUE TITLE
R for travis: can't install bioconductor dependencies on OSX

### ISSUE THREAD

**Issue by vivekbhr** [travis-ci/travis-ci#9270] opened 2018-02-26 16:04 UTC
Hi

For my R package, Travis can't install Bioconductor dependencies on OSX, while it succeeds on Linux. 

The following command fails : 

```
Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
missing: BiocParallel, Biostrings, csaw, edgeR, GenomicAlignments, GenomicFeatures, GenomicRanges, ggplot2, IRanges, limma, plyr, reshape2, Rsamtools, rtracklayer, S4Vectors, ShortRead, SummarizedExperiment, VariantAnnotation
```
leading to error : 

`The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .

Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
`

Below is my `.travis.yml` setup: 

```
language: R
sudo: false
cache: packages
r: bioc-devel
bioc_packages: BiocCheck
# customize build to add biocCheck
script:
    - R CMD build . --no-resave-data --no-manual
    - R CMD check *tar.gz --as-cran --timings --no-manual
    - R CMD BiocCheck mypackage_0.98.0.tar.gz
os:
    - linux
    - osx
```

Any help appreciated. Thanks in advance...

ping @craigcitro @jimhester

**Comment by jimhester** [comment] 2018-02-26 16:44
Can you link to the full build report please? It would help pinpoint where the issue is.

**Comment by vivekbhr** [comment] 2018-02-26 21:52
Hi @jimhester . Thanks for the fast reply. The last build was private so I just re-did it on the public server. [Here is the report](https://travis-ci.org/vivekbhr/icetea/builds/346382769).

**Comment by vivekbhr** [comment] 2018-03-01 16:45
@jimhester could you see the issue?

**Comment by jimhester** [comment] 2018-03-09 14:50
Unfortunately it does not look like the **vivekbhr/icetea** repository is public, I cannot access it.

**Comment by vivekbhr** [comment] 2018-03-11 09:19
@jimhester I made it [public now](https://github.com/vivekbhr/icetea). Here's the [build](https://travis-ci.org/vivekbhr/icetea) .

**Comment by vivekbhr** [comment] 2018-03-12 22:59
@jimhester I think my issue is related to [issue #1530](https://github.com/r-lib/devtools/issues/1530) from devtools. My guess is that on r-devel on mac, devtools can't detect uninstalled dependencies, while the release version of R on my local mac does.

**Comment by vivekbhr** [comment] 2018-03-14 22:21
[Found more posts](https://github.com/r-lib/covr/issues/263) on other packages that lead to the same conclusion. r-devel builds on osx fail in general. I am now skipping the r-devel osx build from the build matrix.

**Comment by BanzaiMan** [comment] 2018-03-19 14:28
Sounds like this is a general problem we are unable to fix on our own. I'm closing this now.

**Closed by BanzaiMan** 2018-03-19 14:28 UTC
Labels: community:r
