### ISSUE TITLE
bad decrypt in windows 10

### ISSUE THREAD

**Issue by zhaoqize** [travis-ci/travis-ci#6936] opened 2016-11-26 03:08 UTC
when I try  push.
the travis ci failed.
```node
bad decrypt

140356638541472:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:evp_enc.c:532:

The command "openssl aes-256-cbc -K $encrypted_b5321099e062_key -iv $encrypted_b5321099e062_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d" failed and exited with 1 during .
```
what should I do?
[tarvis-ci](https://travis-ci.org/zhaoqize/blog/builds/178994959)

**Comment by BanzaiMan** [comment] 2016-11-26 16:23
If you are using Windows machine locally to execute `travis encrypt-file`, this is a duplicate of #4746.

**Comment by zhaoqize** [comment] 2016-11-27 15:14
Hmm,Got it

**Closed** 2016-11-27 15:14 UTC
