### ISSUE TITLE
Travis deploy to gh-pages failing

### ISSUE THREAD

**Issue by utzig** [travis-ci/travis-ci#9048] opened 2018-01-11 20:52 UTC
This might be the same error as #9047...

We maintain a site for a conference that is built and deployed using travis-ci to gh-pages. The process was working flawlessly up to 1 or 2 days ago. Now the deploy fails on rsync because it doesn't find the source directory. I put an `ls` for debugging purposes and confirmed the directory is there at the end of the build. Also `skip_clean` is there so not really sure what's going on.

My travis.yml is here: https://github.com/pythonsul/pythonsul2018-site/blob/master/.travis.yml
The build logs are here:  https://travis-ci.org/pythonsul/pythonsul2018-site/builds

**Comment by BanzaiMan** [comment] 2018-01-11 21:45
This is indeed a duplicate of #9047.

**Closed by BanzaiMan** 2018-01-11 21:45 UTC
