### ISSUE TITLE
Xcode 8.3 Image: Multiple iOS 10.2 Simulators

### ISSUE THREAD

**Issue by SlaunchaMan** [travis-ci/travis-ci#7532] opened 2017-03-28 20:19 UTC
In [a recent iOS app job failure](https://travis-ci.org/SlaunchaMan/Clusterfuck/jobs/216088437), I got this error:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:10.2, name:iPhone 7 }
The requested device could not be found because multiple devices matched the request.
```

Looking at the logs, it looks like every iOS 10.2 simulator is duplicated, like these duplicate iPhone 7 entries:
```
{ platform:iOS Simulator, id:22FA2149-1241-469C-BF6D-462D3837DB72, OS:10.2, name:iPhone 7 }
{ platform:iOS Simulator, id:E40727B3-41FB-4D6E-B4CB-BFA87109EB12, OS:10.2, name:iPhone 7 }
```
Removing the duplicates will allow us to refer to them by name and OS version.

**Comment by solarce** [comment] 2017-03-29 00:43
I'm sorry that this was carried forward to the 8.3 image.

We are working to resolve this and hope to have updates for 8.2 and 8.3, with this fix, out some time tomorrow

**Comment by SlaunchaMan** [comment] 2017-03-29 15:00
Thanks!

**Comment by solarce** [comment] 2017-03-29 19:34
Due to an issue with our logs database, the completion of this fix will be delayed by a day or so, but we've got a fix that we're doing QA and verification on. I'll post an update by tomorrow morning PDT at the latest.

**Comment by cocoahero** [comment] 2017-04-03 14:45
Any updates on this @solarce?

**Comment by solarce** [comment] 2017-04-04 03:35
My apologies for the delays.

I have two new images that believe are fixed, using a small ruby script, https://github.com/travis-infrastructure/osx-image-bootstrap/pull/20/files

But since simulator stuff isn't something we have a ton of experience with poking at, I have published them with a special _key_ for some testing before promoting them to the main stable images.

The new image names are:
- `xcode8.2simfix` - I confirmed the simulator list no longer has duplicated under 10.2, https://travis-ci.org/solarce/osx-tests/jobs/218313786#L496-L510
- `xcode8.3simfix` - I confirmed the simulator list no longer has duplicated under 10.2, https://travis-ci.org/solarce/osx-tests/jobs/218313787#L521-L534

Please give them a try and let us know if things look correct for you.

**Comment by SlaunchaMan** [comment] 2017-04-04 14:22
[Trying now!](https://travis-ci.org/SlaunchaMan/Clusterfuck/jobs/218479288)

**Comment by SlaunchaMan** [comment] 2017-04-04 14:29
Success!

**Comment by solarce** [comment] 2017-04-04 15:07
Awesome, since this looks good I am going to close this and wait for 8.2 confirmation over in https://github.com/travis-ci/travis-ci/issues/7031#issuecomment-291385484

**Closed by solarce** 2017-04-04 15:07 UTC
Labels: mac

**Comment by solarce** [comment] 2017-04-05 15:41
The image has been promoted to production, https://blog.travis-ci.com/2017-04-05-xcode-82-83-duplicate-simulator-fixes. The `simfix` images will be removed momentarily.

**Comment by ikesyo** [comment] 2017-04-06 04:45
You have duplicated simulators of watchOS 3.2 now 😲 

```
-- watchOS 3.2 --
    Apple Watch - 38mm (38C891AB-EC79-43E4-9311-6FDEB12DCF11) (Shutdown)
    Apple Watch - 38mm (35AB3F5D-069B-4B51-B04B-F6AD78C3041E) (Shutdown)
    Apple Watch - 42mm (BE78B202-BB77-4DC8-A6F0-0F648DA89B4A) (Shutdown)
    Apple Watch - 42mm (644B67CA-F6BA-4DE5-A826-CA96D88E3C0C) (Shutdown)
    Apple Watch Series 2 - 38mm (9DF64E1A-A613-4523-A9B7-B98376154190) (Shutdown)
    Apple Watch Series 2 - 38mm (3A12376B-EDE6-48DC-B8E0-CDA704E9D423) (Shutdown)
    Apple Watch Series 2 - 42mm (25EF4763-1942-4A3B-A80F-FC080592B82C) (Shutdown)
    Apple Watch Series 2 - 42mm (D5912402-77B7-44B8-93FD-B00406F46415) (Shutdown)
```
