### ISSUE TITLE
pecl not included with PHP 7.0.1-dev

### ISSUE THREAD

**Issue by bwoodmansee** [travis-ci/travis-ci#5213] opened 2015-12-04 22:53 UTC
```
PHP 7.0.1-dev (cli) (built: Dec  4 2015 22:42:20) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3-dev, Copyright (c) 2002-2015, by Derick Rethans

echo "no" | pecl install apcu-beta
rbenv: pecl: command not found
The `pecl' command exists in these PHP versions:
  5.2
  5.2.17
  5.3
  5.3.29
  5.3.3
  5.4
  5.4.37
  5.5
  5.5.21
  5.5.9
  5.6
  5.6.5
```

**Comment by BanzaiMan** [comment] 2015-12-05 00:05
Thanks for taking time to open this issue. This is a duplicate of #5207. I'm closing this.

**Closed by BanzaiMan** 2015-12-05 00:05 UTC
