### ISSUE TITLE
Travis Builds Error and Timeout instead of Passing on Exit Code 0

### ISSUE THREAD

**Issue by hayesmaker** [travis-ci/travis-ci#6998] opened 2016-12-09 10:56 UTC
<img width="1000" alt="screen shot 2016-12-09 at 11 56 41" src="https://cloud.githubusercontent.com/assets/593429/21048316/9b946b30-be06-11e6-9965-92398f168baf.png">
Even when my builds succeed and Exit Code 0 is received, my builds have continued, then timed out and reported as error'd / failed.

see my last build here:
https://travis-ci.org/hayesmaker/thrust-platform/jobs/182550796

**Comment by BanzaiMan** [comment] 2016-12-09 15:05
Looks like a duplicate of #6861.

**Closed by BanzaiMan** 2016-12-09 15:05 UTC

**Comment by hayesmaker** [comment] 2016-12-11 12:28
Still not fixed, though is it.
