### ISSUE TITLE
The command "source ~/virtualenv/python3.2_with_system_site_packages/bin/activate" failed and exited with 1 during .

### ISSUE THREAD

**Issue by ensonic** [travis-ci/travis-ci#8571] opened 2017-10-11 19:29 UTC
There are a few other builds besides mine (1st) that have the same issue:
https://travis-ci.org/OpenRoberta/robertalab-ev3dev/builds/286020361
https://travis-ci.org/SpriteLink/NIPAP/jobs/151577302

I need to stay with 3.2 and system site packages as the dbus package would not work otherwise.

**Comment by BanzaiMan** [comment] 2017-10-13 18:26
I believe this is effectively a duplicate of #4260, which effectively says that the support for `--with-system-site-packages` should be deprecated.

I'm closing this as a duplicate, but if you think it should be treated separately, do let us know.

**Closed by BanzaiMan** 2017-10-13 18:26 UTC

**Comment by ensonic** [comment] 2017-10-13 21:09
Thanks for triaging. I switched to python 3.4 and it builds again. I also explained in #4260, why I *need* system-site-packages option.
