### ISSUE TITLE
Cannot start ChromeHeadless

### ISSUE THREAD

**Issue by XhmikosR** [travis-ci/travis-ci#9024] opened 2018-01-09 13:02 UTC
Hi.

We started getting `Cannot start ChromeHeadless` errors in bootstrap. See [this build](https://travis-ci.org/twbs/bootstrap/jobs/326768045), for instance.

```
09 01 2018 12:59:30.113:ERROR [launcher]: Cannot start ChromeHeadless
	[0109/125929.984683:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
```

We haven't changed anything on our side for a long time, so it must be something that changed on your side, permissions related.

**Comment by jfrej** [comment] 2018-01-09 13:25
This is most likely caused by jobs being rerouted to `sudo: required` infrastructure, see this: https://blog.travis-ci.com/2018-01-08-travis-response-meltdown-spectre

We have the same problem. A temporary fix is to add this to your .travis.yml:
```
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
```

**Comment by XhmikosR** [comment] 2018-01-09 13:31
Thanks for the reply @jfrej. Wouldn't just changing the permissions suffice without requiring sudo?

I'll try to play with it later since this might take a while to be fixed here.

**Comment by jfrej** [comment] 2018-01-09 13:36
I guess it might work, but when your jobs are switched back to `sudo: false` infrastructure they might start failing because they won't have access to sudo.
It might be best to just wait until the security update is over.
https://www.traviscistatus.com/incidents/7k5kpkcldbnk

**Comment by XhmikosR** [comment] 2018-01-09 13:40
Oh, thanks so much for the info! I wasn't aware they are in the middle of the update.

Waiting is the best solution.

Thanks again for the info!

**Comment by markandrus** [comment] 2018-01-09 16:45
The incident is marked as resolved, but I still see a similar failure in my jobs. Maybe shifting back to  container-based linux jobs is not yet complete?

**Comment by gkalpak** [comment] 2018-01-09 18:51
Probably related to https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524.

**Comment by ryantmer** [comment] 2018-01-09 19:06
We've been seeing a slightly different error, namely `unknown error: Chrome failed to start: crashed` when trying to run tests via Selenium. The fix suggested in the comment linked by @gkalpak worked for us perfectly - thanks!

**Comment by BanzaiMan** [comment] 2018-01-09 19:44
Closing as a duplicate.

**Closed by BanzaiMan** 2018-01-09 19:44 UTC
