### ISSUE TITLE
Build hangs after finishing the build, gets terminated after 10 more minutes

### ISSUE THREAD

**Issue by quattro004** [travis-ci/travis-ci#6861] opened 2016-11-12 07:20 UTC
Hi @joshua-anderson, @akoeplinger, @nterry I have a .NET core project and have got some tests to run and pass but for some reason the build isn't detecting the output from the dotnet test command. Do I need to put that command into a script? Here's my build link https://travis-ci.org/quattro004/Chesster/builds/175266521 as you can see the tests passed after about 23 seconds but the build kept running. Thanks.
  Reese

**Comment by Joshua-Anderson** [comment] 2016-11-12 16:47
Huh. That's interesting. It looks like the CLI is hanging. Does that happen locally?

**Comment by quattro004** [comment] 2016-11-12 17:38
No but I'm using Ubuntu 16.04 for testing Linux. Let me know if there's
something I can do to help. Thanks.

**Comment by quattro004** [comment] 2016-11-14 16:23
Hi Joshua, I setup a 14.04 Ubuntu machine and when I run dotnet test
against my project it doesn't hang and I verified that it does return an
exit code by running "echo $?". Could it be the way the CI build process
executes the script?

**Comment by Joshua-Anderson** [comment] 2016-11-14 18:15
All Travis CI does is execute `dotnet test TestChessterUciCore`. In this build that command command never exited after running, causing it to be killed.

**Comment by BanzaiMan** [comment] 2016-11-14 19:55
Hello. I don't think this is an issue with C# builds, but rather a widespread issue with hanging builds, where process stops running, but we fail to clean up afterwards. Eventually log silence forcibly terminates the build.

We are investigating.

**Comment by mickael-ange** [comment] 2016-11-17 04:00
Hello,

We have same issue on an Erlang project using Ubuntu container infra since 3 days.

Cheers,
Mickael

**Comment by mickael-ange** [comment] 2016-11-22 07:25
Hi,

We figured out what was causing the hanging build in our case.

In our build steps, we install a specific PostgreSQL server (cause we need to modify the server config) and start it in background.

```
$POSTGRESQL_BIN/postgres -D $POSTGRESQL_DATA/ &
```

This was working perfectly fine since last week.

But now we need to stop the PostgreSQL server.
```
kill -INT `head -1 $POSTGRESQL_DATA/postmaster.pid`
```
After that change, the build ends normally.

Note: To troubleshoot, we use a minimal `.travis.yml`, which does nothing (the build should ends normally) then add build step by build step (by dichotomy would be faster if you have huge number of steps).

Hoping that might help with your investigation,

Regards,

Mickael

**Comment by eXpl0it3r** [comment] 2016-11-22 11:57
Any update on this? We're experiencing the same issue. I've provided more detailed information on the [moodle-plugin-ci issue tracker](https://github.com/moodlerooms/moodle-plugin-ci/issues/32).

**Comment by BanzaiMan** [comment] 2016-11-22 14:34
Sorry about the lack of response. We are looking into this issue. Sorry for the inconvenience.

**Comment by moylop260** [comment] 2016-11-28 03:38
Same case for [.travis.yml](https://github.com/OCA/maintainer-quality-tools/blob/4295871b9/.travis.yml#L45) using:

```yml
language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7

virtualenv:
  system_site_packages: true
...
```

**Comment by garex** [comment] 2016-12-08 02:40
Same with non-sudo containers but only for PHP5.2. 

And I also have background process there! I will research.

        USER=www-data PHP_FCGI_CHILDREN=15 PHP_FCGI_MAX_REQUESTS=1000 $PHP_CGI --bindpath 127.0.0.1:9000 &

**Comment by garex** [comment] 2016-12-08 05:23
My case confirmed. Issue was in started in background process `php-cgi`.

    killall php-cgi

Helped.

**Comment by djhi** [comment] 2016-12-15 07:55
In our case, we use pm2 to start some process before end to end tests. I just added a command to kill pm2 at the end and it has fixed the build for us.

**Comment by j0k3r** [comment] 2016-12-15 08:44
Following @djhi suggestion, we just tried with `sudo: false` again and in the `after_script` we killed all background process that were launched during the build (like `selenium`):

```yaml
after_script:
    # killing background process (because dockerized build no longer does it)
    - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
```

And the build no longer timeout :v:

**Comment by roperto** [comment] 2016-12-16 00:58
I am having a similar problem using `moodle-plugin-ci` which spawns a few processes and they don't get terminated properly unless sudo is enabled.

I modified @j0k3r to work with my particular issue to work with `sudo: false` again, as follows:

```
after_script:
    # See: https://github.com/moodlerooms/moodle-plugin-ci/issues/32
    - killall -9 java
```

**Comment by quattro004** [comment] 2016-12-17 06:52
I found if I don't run unit tests then the build succeeds, obviously not
ideal. Are .NET core projects supported yet?

https://travis-ci.org/quattro004/Chesster/builds/184730034

Reese

**Comment by roperto** [comment] 2016-12-17 13:34
Hi @quattro004 

In my case Unit and Acceptance tests are the main things I need to check in my code. I never worked with behat/acceptance tests in .NET .

I've never run .NET in linux, I'll peek a little in your code just because I am curious.

In any case, I'd guess there is some process left running by your unit tests (or testing framework). I'd suggest to add `ps aux` both at the beginning of your installation and also at the end so you can compare which process could be hanging the build, then you could use the `killall` on those.

Cheers,

**Comment by moylop260** [comment] 2016-12-17 16:08
In my case the project origin dont work (before works!)
But the fork still work fine!

**Comment by quattro004** [comment] 2016-12-17 17:06
Thanks Daniel, I'll give ps aux a try, what's interesting is that it
doesn't hang on my dev box.

**Comment by mrmark** [comment] 2017-01-24 23:05
@meatballhat sorry for bothering, but will this issue get some attention soon?

**Comment by idgserpro** [comment] 2017-02-09 16:32
Does anyone know if Travis kills the processes that were started in the ```script``` and ```after_script``` sessions? Is killing processes a condition for successful build?

**Comment by idgserpro** [comment] 2017-02-10 18:04
@quattro004 [this commit](https://github.com/quattro004/Chesster/commit/3181a99b6357fbf02de10f46b18a145f355d6cce) solve your problem? Can you explain it here?

**Comment by idgserpro** [comment] 2017-02-13 16:23
@quattro004 It looks like https://github.com/quattro004/Chesster/commit/3181a99b6357fbf02de10f46b18a145f355d6cce really solved your problem. I fork your project and run the build of commit several times. None of them failed:

https://travis-ci.org/idgserpro/Chesster/builds/201128492

Already the [previous commit](https://github.com/idgserpro/Chesster/commit/3a4bf54f4b062ecef94fcdaf952f4ee4c4d5dd08) failed intermittently. Time worked time failed:

https://travis-ci.org/idgserpro/Chesster/builds/201123087

Now the question is: did you change the code because of Travis? Locally functional tests without the commit?

**Comment by quattro004** [comment] 2017-02-13 16:35
No I was able to reproduce locally which helped me figure it out

**Comment by idgserpro** [comment] 2017-02-13 17:25
@quattro004 but the commit https://github.com/quattro004/Chesster/commit/3181a99b6357fbf02de10f46b18a145f355d6cce was to fix Travis's timeout problem? Can you explain it here?

**Comment by pond** [comment] 2017-02-13 21:09
I continue to waste a lot of my time nursemaiding Travis through repeated rebuilds of errored tests. It stalls our PR workflow in GitHub completely.

My company pays a lot for our service with Travis and you've not fixed this problem for months, with very little attention given to it either.

As our software architect, this is intolerable. I'm out of patience and going to recommend we investigate competitors and switch.

**Comment by eXpl0it3r** [comment] 2017-02-13 21:35
Did you try to just run it as sudo? Worked for me.

**Comment by idgserpro** [comment] 2017-02-14 11:20
> Did you try to just run it as sudo? Worked for me.
>
> Or kill at the tasks at the end? Seems to have worked for others.

@eXpl0it3r this may even work, but the problem has to be solved in the Travis. It used to work without it. From the end 2016 to here it started to give problem.

I think this is all is about permission trouble in Travis. The program that monitors the processes is not allowed to kill the processes started in the build.

**Comment by eXpl0it3r** [comment] 2017-02-14 11:24
>  but the problem has to be solved in the Travis.

That is true, however a simple and temporary fix on your end, will make things work automatically again and you wouldn't have to spend time manually doing things with Travis. Just a suggestion to save you some time, @idgserpro. 😉

**Comment by VariantXYZ** [comment] 2017-02-24 05:10
Similar to OP, I have a .NET core application

Here's a run with dotnet test: https://travis-ci.org/VariantXYZ/PolarisCore/jobs/204857145 (tests passed, still hanging)

Here's a run with the dotnet test command removed: https://travis-ci.org/VariantXYZ/PolarisCore/jobs/204856312  (passed)

**Comment by idgserpro** [comment] 2017-03-06 15:03
> Here's a run with dotnet test: https://travis-ci.org/VariantXYZ/PolarisCore/jobs/204857145 (tests passed, still hanging)

@VariantXYZ do you use linux in your development? Does this problem occur locally?

**Comment by VariantXYZ** [comment] 2017-03-06 17:34
@idgserpro Aha, I just tried it on the linux subsystem on Windows 10 and it looks like it's actually hanging there.

In that case, this doesn't seem like a travis-ci issue, ignore my previous comment. Sorry about that.

**Comment by idgserpro** [comment] 2017-03-06 18:58
@VariantXYZ  It seems that @quattro004  solved this problem with [this commit](https://github.com/quattro004/Chesster/commit/3181a99b6357fbf02de10f46b18a145f355d6cce). See if it helps you.

**Comment by finom** [comment] 2017-04-23 15:53
Getting the same issue after deployment a NodeJS project via PM2.

**Comment by jme783** [comment] 2017-05-12 02:16
Experiencing this as well in one of our ruby repositories. Are there any recommended troubleshooting steps here?

**Comment by mickael-ange** [comment] 2017-05-12 06:54
Hello @jme783,

I don't know if you have seen my comment above about troubleshooting.

> Note: To troubleshoot, we use a minimal .travis.yml, which does nothing (the build should ends normally) then add build step by build step (by dichotomy would be faster if you have huge number of steps).

Once you have figured out which step hangs, look for background running processes you might have started, and kill it manually when you don't need it anymore.

Regards,
Mickael

**Comment by jme783** [comment] 2017-05-15 16:05
Will try this, thanks

**Comment by KEHANG** [comment] 2017-07-14 19:44
Seems this problem is coming back again: https://travis-ci.org/ReactionMechanismGenerator/RMG-Py/builds/252972737?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment] 2017-07-14 20:54
I've written a little bit about this issue in https://github.com/travis-ci/travis-ci/issues/8082#issuecomment-315147561, and potential workarounds: https://github.com/travis-ci/travis-ci/issues/8082#issuecomment-315151953

@KEHANG Your build is running `ssh-agent`, which is in some ways a typical manifestation of this problem.

In the interest of streamlining future input, though, I am closing this issue, so that we can all follow #8082.

**Closed by BanzaiMan** 2017-07-14 20:54 UTC
Labels: bug, containers, team blue

**Comment by KEHANG** [comment] 2017-07-17 20:26
@BanzaiMan thanks a lot, just want to confirm that the trick in #8082 worked in my case.

**Comment by hantsy** [comment] 2017-09-09 05:29
I am using travis within an Angular application, the tests ran successfully, but finally travis did not quit and caused this error.

**Comment by fkanout** [comment] 2017-12-12 09:09
I had the same problem for about a month. eventually the problem was NOT Travis CI. 
I'm using Mocha for tests and the tests are async. so the problem is the V4 of mocha:
https://github.com/mochajs/mocha/issues/3044
https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit
I added `--exit` to the test command and it works perfectly no timeout any more

**Comment by HimanshuP90** [comment] 2020-04-04 15:56
In my case just added under scripts -e CI=true to exit immediately:
