### ISSUE TITLE
Plan for dynamic addons.apt.packages

### ISSUE THREAD

**Issue by cchantep** [travis-ci/travis-ci#4347] opened 2015-07-14 10:54 UTC
I'm currently checking how I could migrate the current Travis CI config to its new container architecture, for the ReactiveMongo driver.

As it has to be backward compatible, we currently setup different MongoDB server for each CI job, by selecting the APT package according the Java & Scala version, using a `beforeInstall` script.

Is there any plan to be able to do the same with `addons.apt.packages`? To be able to have a dynamic/different packages per job?

Best regards

**Comment by BanzaiMan** [comment] 2015-07-14 12:08
I believe this is a duplicate of #4173, which was closed for security reasons. #4291 is a feature request to replace that. Let us know if you believe otherwise.

**Closed by BanzaiMan** 2015-07-14 12:08 UTC
