### ISSUE TITLE
Github Showing 2 "checks" That Reference The Same Build After GitHub Apps Integration

### ISSUE THREAD

**Issue by ryant26** [travis-ci/travis-ci#9669] opened 2018-05-26 16:49 UTC
## Expected Behavior

Pull requests should show a single "check" for TravisCI, "Travis CI - Pull Request"
## Current Behavior

I am getting 2 checks that reference the same build:

* Travis CI - Pull Request 
* continuous-integration/travis-ci/pr

![duplicate checks](https://user-images.githubusercontent.com/3953165/40578428-051d39ec-60d1-11e8-8ef0-389479b43fee.PNG)

## Context (Environment)
This is happening on a travisci.com build.
I did not use the "Activate and Migrate" button to activate GitHub Apps integration. 
1. I deleted all the ssh keys for my github.com account to generate new ones. 
2. I logged into travisci.com and noticed that my build was no longer listed. 
3. I added a repository and was taken through the GitHub Apps workflow to authorize an application
4. I opened a PR and noticed this duplicate checks

**Comment by BanzaiMan** [comment] 2018-05-26 17:10
A duplicate of #9618.

**Closed by BanzaiMan** 2018-05-26 17:10 UTC
