### ISSUE TITLE
Duplicate status checks on PR

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#9874] opened 2018-07-11 19:16 UTC
![image](https://user-images.githubusercontent.com/4777512/42594452-ea5ae5b8-8557-11e8-83b6-d399d336a0f4.png)

Having 4 status checks on a pull request instead of 2.

How to get rid of the redundant 2 of them?

**Comment by tooomm** [comment] 2018-07-12 07:36
Duplicate of https://github.com/travis-ci/travis-ci/issues/9618

**Closed** 2018-07-12 22:08 UTC
