### ISSUE TITLE
Builds fail due to “no output in 10 minutes” on trusty after done message

### ISSUE THREAD

**Issue by Kwpolska** [travis-ci/travis-ci#8093] opened 2017-07-14 14:12 UTC
After setting `dist` to `trusty`, some of my builds started failing spuriosusly due to “no output in 10 minutes”, even after a *Done* message appears.

```
Done. Your build exited with 0.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

This used to work back on precise.

https://travis-ci.org/getnikola/wheelhouse/jobs/253613603
https://travis-ci.org/getnikola/wheelhouse/jobs/253613607
https://travis-ci.org/getnikola/invariant-builds/builds/253613564

**Comment by BanzaiMan** [comment] 2017-07-14 14:23
Duplicate of #8082.

**Closed by BanzaiMan** 2017-07-14 14:23 UTC
