### ISSUE TITLE
Add PyPy 5.4

### ISSUE THREAD

**Issue by scop** [travis-ci/travis-ci#6553] opened 2016-09-02 15:33 UTC
PyPy 5.4 was released earlier this week, would be nice to have it available in Travis.

https://morepypy.blogspot.com/2016/08/pypy2-v54-released-incremental.html

**Comment by BanzaiMan** [comment] 2016-09-03 03:30
Closing as a duplicate of #6277.

**Comment by BanzaiMan** [comment] 2016-09-03 03:59
Actually, it's a bit different for the purpose of packaging.

**Comment by BanzaiMan** [comment] 2016-09-03 04:08
PyPy 5.4 should be available now. https://travis-ci.org/travis-ci/cpython-builder/builds/157259077

**Closed by BanzaiMan** 2016-09-03 04:08 UTC
Labels: python
