### ISSUE TITLE
C# and OS X

### ISSUE THREAD

**Issue by sapek** [travis-ci/travis-ci#3546] opened 2015-04-02 03:11 UTC
I have a multi-platform, multi-language Travis CI configuration which recently stopped working:

https://github.com/Microsoft/bond/blob/master/.travis.yml

The project builds Haskell, C++ and C# programs. I have it configured for csharp as language and Linux and OS X for systems. On Linux Travis built-in support was installing Mono. On OS X my script was installing Mono explicitly: https://travis-ci.org/Microsoft/bond/jobs/53159734 

It appears that now a project configured for csharp as language fails immediately: https://travis-ci.org/Microsoft/bond/jobs/56765552

Any suggestions how to fix it? If Mono is not supported on OS X, is there a way to configure repository to use different language for Linux and different for OS X so that Travis doesn't try to install Mono on OS X?

@joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment] 2015-04-02 03:20
We could set up mono for Mac OS X pretty easily, but since multi is testing isn't available for general use yet we figured that nobody would use it.

**Comment by sapek** [comment] 2015-04-02 03:24
I was fine when it was just silently failing to install Mono on OS X. What causes me the problem is that now it hard-fails so I can't even work around from my script like I used to.
Is there any way I can tell Travis to ignore Mono for OS X? Any way to have different language configuration for different OS?

**Comment by Joshua-Anderson** [comment] 2015-04-02 13:16
If I have some time I will look into adding  mono support to Mac OS X. Otherwise I will just skip the mono installation stage on OS X.

**Comment by akoeplinger** [comment] 2015-04-02 13:24
@sapek As a short-term workaround, you should be able to switch to `language: c` and install Mono on Linux manually like we do internally in the script: [csharp.rb#L36-L44](https://github.com/travis-ci/travis-build/blob/2f4988bc44e9ca519069de01751ad24a90e8a9d2/lib/travis/build/script/csharp.rb#L36-L44)

**Comment by sapek** [comment] 2015-04-02 14:10
For now I switched the project to C++ with manual Mono install.

**Comment by martincostello** [comment] 2015-05-13 22:51
+1 for support for this out of the box. I've been doing some cross-platform testing for some C# code and got CI builds up and running for the same code using AppVeyor for Windows and Travis for Linux. It would be nice to get Travis supporting OS X as well by just being able to use a matrix for the OS in ```.travis.yml```.

**Comment by nulltoken** [comment] 2015-06-09 11:06
We'd also be really interested in benefiting from this. FWIW, here's **[how](https://github.com/libgit2/libgit2sharp/blob/vNext/CI/travis.osx.install.deps.sh)** we're dealing with this for now.

@Therzok Any chance Mono 3.28 could be published over at http://download.mono-project.com/archive/ ?

**Comment by akoeplinger** [comment] 2015-06-09 11:32
@Joshua-Anderson fyi, we now have better access to the "latest" Mono version for Mac [available here](https://github.com/mono/website/blob/gh-pages/_data/latestrelease.yml), I can expose this info in any way you need on the Mono website so you can pull the right package on Mac if you implement this.

**Comment by Joshua-Anderson** [comment] 2015-06-09 14:12
I see two easy ways for doing this.

1. There is a symlinked latest folder
2. You expose the version number a s plain text so I can just `curl http://someurl.com/version/latest` to get it.

Is there any way to get alpha or beta releases on OSX?

**Comment by akoeplinger** [comment] 2015-06-09 14:16
@Joshua-Anderson I'll ask about symlinks, but 2. is easy as well. [alpha](https://github.com/mono/website/blob/gh-pages/_data/alpharelease.yml)/[beta](https://github.com/mono/website/blob/gh-pages/_data/betarelease.yml) are available.

**Comment by Joshua-Anderson** [comment] 2015-06-09 14:20
Awesome! Not having symlinks isn't a big deal. I don't really care what URL you expose it at but would prefer that the version is in plain text so I don't have a parse it.

**Comment by akoeplinger** [comment] 2015-06-15 23:31
@Joshua-Anderson Look what we got here: http://download.mono-project.com/archive/mdk-latest-alpha.pkg thanks to @directhex :smile: We'll get similar links for `latest` and `beta` when new releases are pushed.

**Comment by Joshua-Anderson** [comment] 2015-06-15 23:35
Awesome!

**Comment by Joshua-Anderson** [comment] 2015-06-16 02:44
Taking a quick look into implementing this, I am finding some minor problems. For older releases, there is the version with the `major.minor.patch` symlinked to the `major.minor.patch.fix`. So `4.0.0` is availible at both http://download.mono-project.com/archive/4.0.0/macos-10-x86/MonoFramework-MDK-4.0.0.143.macos10.xamarin.x86.pkg and  http://download.mono-project.com/archive/4.0.0/macos-10-x86/MonoFramework-MDK-4.0.0.macos10.xamarin.x86.pkg . Starting with version 4.0.1 however, only the version with the patch release  http://download.mono-project.com/archive/4.0.1/macos-10-x86/MonoFramework-MDK-4.0.1.44.macos10.xamarin.x86.pkg is available. Any chance you could convince people to bring that symlink back so that users don't have to know what the current fix release is? 

It gets even more confusing because on linux the snapshots are only updated on the `minor` version, so  users testing `4.0.0` will get different versions on OS X and linux.

**Comment by directhex** [comment] 2015-06-16 10:15
Re-done manually for now. Should happen automatically in future too.

**Comment by directhex** [comment] 2015-06-16 10:17
The 4.0.0/4.0.1 situation is a mess which can't be fixed retroactively - but shouldn't happen again. The build numbers should now mirror Mac & Linux - e.g. "4.0.2 alpha" on Mac and Linux is 4.0.2.4, "4.0.1 stable" is 4.0.1.44

**Comment by Joshua-Anderson** [comment] 2015-06-16 14:48
Thanks for the help @directhex! :heart:

**Comment by martincostello** [comment] 2015-06-23 12:12
I'm not sure if this is related to the problems being discussed or not, so if not I'll open a new issue.

I noticed that [Mono 4.0.2](http://www.mono-project.com/docs/about-mono/releases/4.0.2/) was released on the 10th June which should contain a fix for the issue that prevents xUnit 2.0.0 from running on Mono.

A [build](https://travis-ci.org/experiandataquality/electronicupdates/builds/67761954#L954) of a repo I'm working on that ran on Sunday isn't configured to use a specific version of Mono, so uses the latest. Travis CI still has Mono 4.0.1 as the latest from reading the build logs, so I thought I'd try and circumvent this by explicitly configuring the use of Mono 4.0.2 instead [like so](https://github.com/martincostello/electronicupdates/commit/91887e6ee06c7b1aa72a9194a30771e7c4a575fe).

However this [fails](https://travis-ci.org/experiandataquality/electronicupdates/builds/67984825#L78) with a HTTP 404 when running ```apt-get```.

Am I specifying something incorrectly in ```.travis.yml``` or has Mono just not rolled 4.0.2 out far enough to allow it to be picked up yet?

Alternatively can Travis CI be updated to use 4.0.2 as the latest instead of 4.0.1?

**Comment by akoeplinger** [comment] 2015-06-23 13:38
@martincostello Mono 4.0.2 is still in alpha (I've updated the page to state the release notes are a draft). You should be able to try it by specifying `mono: alpha` in your .travis.yml.

Please also note that patch versions like `mono: 4.0.x` aren't supported by the Xamarin repositories, so you can't use them (i.e. specify 3.12.0 even if the latest 3.12 release is 3.12.1).

**Comment by BanzaiMan** [comment] 2015-06-23 13:41
Is there anything for Travis to address on this issue? Could we perhaps add extra information to the documentation?

**Comment by akoeplinger** [comment] 2015-06-23 13:44
@BanzaiMan hmm, the documentation already states "By default Travis CI will use the latest Mono release". I think the confusion was just caused by the fact that 4.0.2 wasn't explictly marked as being pre-release on the Mono website, which I've fixed.

If anyone has suggestions for improving the docs, please file a new issue as this one is meant for tracking the OSX progress :)

**Comment by martincostello** [comment] 2015-06-23 13:51
Thanks for the prompt reply @akoeplinger. I'll add a new issue shortly referencing this suggesting some tweaks/clarification to the Travis CI docs.

**Comment by Joshua-Anderson** [comment] 2015-07-25 21:39
I opened a PR for OS X support at travis-ci/travis-build#488

**Closed** 2015-08-05 14:05 UTC
Labels: community:csharp

**Comment by martincostello** [comment] 2015-08-05 19:05
I just tried this out (possibly prematurely) and only a Linux build ran without an OS X build also occurring.

Have I jumped the gun and run this when it's not deployed in production yet, or have I misunderstood and building with multiple Operating Systems using a matrix isn't supported?

**Comment by BanzaiMan** [comment] 2015-08-05 19:08
@martincostello Does your repo have multi-os feature enabled?

**Comment by martincostello** [comment] 2015-08-05 19:12
@BanzaiMan Sorry, I didn't realise it had to be opted into, I thought it was just a standard feature. I just found the [documentation](http://docs.travis-ci.com/user/multi-os/) for it from a quick Google.

I'll contact support as detailed there.
