### ISSUE TITLE
Compiler in matrix include is being combined rather than replacing

### ISSUE THREAD

**Issue by sitsofe** [travis-ci/travis-ci#7358] opened 2017-02-21 22:07 UTC
Description of the problem
Sometimes travis combines compilers rather than using one at a time.

Steps to reproduce:
1. Clone the repo https://github.com/sitsofe/travis-test.git which has the following .travis.yml
```
language: c
os:
  - linux
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
  exclude:
    - os: osx
      compiler: gcc
```
2. Do a push that kicks off a travis build.

Expected results
Three builds to be done (1 Linux clang, 1 Linux gcc, 1 OSX clang with xcode8.2 settings)

Actual result
Three builds are done but one has a strange non-nonsensical compiler (1 Linux clang, 1 Linux gcc, 1 OSX gcc,clang with xcode8.2 settings)

How reproducible is the issue?
Reproducible every time.

**Comment by BanzaiMan** [comment] 2017-02-21 22:38
Duplicate of #3670. Basically, you need to define `compiler` in each of the jobs you explicitly include in `matrix.include`. There is no way for these jobs to know which one to pick up.

**Closed by BanzaiMan** 2017-02-21 22:38 UTC

**Comment by sitsofe** [comment] 2017-02-22 04:07
@BanzaiMan So looking at https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Included-Jobs-need-complete-definitions which says "When including jobs, it is important to ensure that each job defines a unique value to any matrix dimension that the matrix defines."

So in the docs example because one part of the matrix defines `env` all parts must define `env`? And in the example I gave above should I also be defining `osx_image` in the exclude section or does this rule only apply to dimensions defined outside the matrix section?
