### ISSUE TITLE
Set proper CXX environment for Node 4 builds

### ISSUE THREAD

**Issue by kpdecker** [travis-ci/travis-ci#4856] opened 2015-09-26 20:00 UTC
Right now to test under Node 4 when using native modules, this flag has to be set in the .travis.yml file.

```
env:
  - CXX=g++-4.8
```

Causing a lot of people to have to hunt for the fix. This should be configured by default in these node environments so these things work out of the box without having to burn a bunch of time trying to find the fix for this CI specific failure.

This is sort of a dupe of #4771 but that was self closed so filing another to ensure visibility.

https://github.com/nodejs/node-gyp/issues/742#issuecomment-143198976

**Comment by BanzaiMan** [comment] 2015-09-26 20:08
At the moment, the Precise builds (legacy, containers) do not have the prerequisite. We are working on an update, but we do not have ETA.

This is indeed a duplicate of #4771. I'm going to close this and reopen the other.

**Closed by BanzaiMan** 2015-09-26 20:08 UTC
