### ISSUE TITLE
Unable to parse package file /var/lib/apt/lists/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-amd64_Packages (1)

### ISSUE THREAD

**Issue by forki** [travis-ci/travis-ci#8556] opened 2017-10-09 07:40 UTC
This builds fails repeatable: https://travis-ci.org/SAFE-Stack/SAFE-BookStore/builds/285426901?utm_source=github_status&utm_medium=notification

    Reading package lists... Error!
    W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109
    W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release' is not signed.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
    W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
    E: Failed to fetch store:/var/lib/apt/lists/partial/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-i386_Packages  Empty files can't be valid archives
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    E: Unable to parse package file /var/lib/apt/lists/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-amd64_Packages (1)
    W: You may want to run apt-get update to correct these problems
    E: The package cache file is corrupted
    The command "sudo apt-get update && sudo apt-get install yarn" failed and exited with 100 during .

@joshua-anderson @akoeplinger @nterry

**Comment by BanzaiMan** [comment] 2017-10-09 08:10
Duplicate of #8554.

**Comment by BanzaiMan** [comment] 2017-10-09 08:10
See, in particular, https://github.com/travis-ci/travis-ci/issues/8554#issuecomment-335052454.

**Closed by BanzaiMan** 2017-10-09 08:10 UTC

**Comment by forki** [comment] 2017-10-09 08:30
can you please reopen? I don't have control over the C# container. It should be solved generally, right?!

**Comment by akoeplinger** [comment] 2017-10-09 11:59
@forki it should be solved by https://github.com/travis-ci/travis-build/pull/1188 once it's deployed to prod.

**Comment by forki** [comment] 2017-10-09 12:06
we had a green build already. thank you!
