### ISSUE TITLE
Set the description for deployments to GitHub releases

### ISSUE THREAD

**Issue by Midnighter** [travis-ci/travis-ci#8568] opened 2017-10-11 12:29 UTC
I didn't see anything in the documentation or examples out on the web about how to actually provide a description for a release deployment. With one of our repositories, we keep markdown files with release notes in a directory so ideally I could copy one of those markdown files (or have its contents copied) to the release description on GitHub.

**Comment by BanzaiMan** [comment] 2017-10-11 17:48
What do you mean by "description"? If you mean the "body" of the release (https://developer.github.com/v3/repos/releases/#create-a-release), this is handled in https://docs.travis-ci.com/user/deployment/releases#Advanced-options. We could consider explaining what advanced options are, but at the risk of getting out of sync from time to time.

**Comment by Midnighter** [comment] 2017-10-12 08:23
That's exactly what I need! I was browsing the page for any option that looked like it might allow me to pass in a description but I missed the link to the Octokit API. Thank you.

A short description of the possible options probably would have helped me but I understand your concern about getting out of date.

**Comment by Midnighter** [comment] 2017-10-12 10:14
Okay, I was a bit too quick to declare success.

I tried three different cases and I'm not quite there yet:

1. When I configure a description directly in the `.travis.yml` I have no problems and it works:
   ```yaml
   body: "a simple description"
   ```
2. When I try to do something more complicated with newlines, I get a literal `\n` in the release.
   ```yaml
   body: "a description\non multiple lines"
   ```
   You can see the result [in my test repo](https://github.com/Midnighter/test-release/releases).
3. What I'm really trying to do, though, is to pass in the content of a markdown file.
   ```bash
   export TAG_NOTES=$(cat awesome.md)
   ```
   ```yaml
   body: $TAG_NOTES
   ```
   However, then I get an error with the GitHub API: `invalid option "--body=# Header\n\n* Nice list\n\nParagraph 3"` as you can see [in these logs](https://travis-ci.org/Midnighter/test-release/builds/286957987).

**Comment by Midnighter** [comment] 2017-10-12 11:55
Found the following related issues https://github.com/travis-ci/dpl/issues/155 but didn't spot a solution.

**Comment by BanzaiMan** [comment] 2018-01-12 20:53
Closing as a duplicate of the dpl issue.

**Closed by BanzaiMan** 2018-01-12 20:53 UTC
Labels: deployment
