### ISSUE TITLE
Suggestion: Avoid running re-travis if the source tree hasn't changed

### ISSUE THREAD

**Issue by jgunthorpe** [travis-ci/travis-ci#6691] opened 2016-10-07 18:11 UTC
I've noticed on our tree (linux-rdma / rdma-core) that Travis is running duplicate builds, we do not need it to do this, so it seems to be wasting resources.

For instance It ran build #27 against the github auto-merge, then build #28 against the final merge. The two source trees are identical except for some meta data in the git log (eg the time stamps and commit text). This is why they have different commit IDs.

Git makes it easy to tell if two source trees are identical on checkout, use  'git cat-file -p COMMIT' to extract the tree id hash and use that to de-duplicate build runs. The tree id only changes if the checkout would be different.

**Comment by BanzaiMan** [comment] 2017-01-28 16:36
Duplicate of #6301.

**Closed by BanzaiMan** 2017-01-28 16:36 UTC
Labels: feature-request
