### ISSUE TITLE
Oracle JDK 10 failing to install

### ISSUE THREAD

**Issue by lukehutch** [travis-ci/travis-ci#10266] opened 2018-10-18 23:52 UTC
This has been happening the last few days:

https://travis-ci.org/classgraph/classgraph/jobs/443437550

travis.yml here:

https://github.com/classgraph/classgraph/blob/master/.travis.yml

**Comment by BanzaiMan** [comment] 2018-10-19 01:05
Duplicate of #10262.

**Closed by BanzaiMan** 2018-10-19 01:05 UTC
