### ISSUE TITLE
failed build: trouble with your network connection.

### ISSUE THREAD

**Issue by pixelass** [travis-ci/travis-ci#9269] opened 2018-02-26 11:31 UTC
I keep getting this error: 

I'm not sure if this is just an issue with Travis. (I did not change my config. local build work)

```
info There appears to be trouble with your network connection. Retrying...
```

https://travis-ci.org/sinnerschrader/dekk/jobs/346228168

```
2.47s$ nvm install 6
Downloading and installing node v6.13.0...
Downloading https://nodejs.org/dist/v6.13.0/node-v6.13.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v6.13.0 (npm v3.10.10)
install.yarn
$ node --version
v6.13.0
$ npm --version
3.10.10
$ nvm --version
0.33.8
$ yarn --version
1.3.2
747.53s$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/generator/-/generator-7.0.0-beta.40.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/sinnerschrader/dekk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
The command "eval yarn " failed. Retrying, 2 of 3.
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/helper-annotate-as-pure/-/helper-annotate-as-pure-7.0.0-beta.40.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/sinnerschrader/dekk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn " failed. Retrying, 3 of 3.
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/template/-/template-7.0.0-beta.40.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/sinnerschrader/dekk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "eval yarn " failed 3 times.
The command "yarn" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by pixelass** [comment] 2018-02-26 11:33
This seems to happen randomly.

The node 8 build succeeded: https://travis-ci.org/sinnerschrader/dekk/jobs/346228169

(the same build failed before due to the same error)

**Comment by cpilson** [comment] 2018-02-26 11:42
I strongly suspect Travis-CI just went through some networking issues. I came back to it after a couple months away, about 20 minutes ago, and came across this same issue.

@pixelass are you working now? The issue came clear for me as of 5 minutes ago.

**Comment by pixelass** [comment] 2018-02-26 11:49
I had a few failed builds. The latest build passed, so I suspect a Travis CI issue. 
I haven't had this issue before but found some related closed issues.

This is just meant to address that some servers might have network issues.

**Comment by harrynull** [comment] 2018-02-26 14:47
I have similar issue. Travis can't even fetch apt:
```
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: Failed to fetch https://dl.hhvm.com/ubuntu/dists/trusty/InRelease  Operation timed out after 0 milliseconds with 0 out of 0 bytes received
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Could not connect to www.apache.org:80 (140.211.11.105), connection timed out
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.4/InRelease  Could not connect to repo.mongodb.org:80 (52.84.5.222), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
It's quite frequent and annoying recently.

**Comment by yovanoc** [comment] 2018-03-06 19:59
I have this problem too! Suddenly my builds are failed with the exact same error

**Comment by BanzaiMan** [comment] 2018-03-30 17:15
I'm closing this as a duplicate of https://github.com/travis-ci/travis-ci/issues/9112. See https://github.com/travis-ci/travis-ci/issues/9112#issuecomment-376305909 for the latest information.

Thanks.

**Closed by BanzaiMan** 2018-03-30 17:15 UTC
