### ISSUE TITLE
Numa no longer working

### ISSUE THREAD

**Issue by cchantep** [travis-ci/travis-ci#9152] opened 2018-01-27 19:01 UTC
Hi,

Having a container build, after a long time working, it's no longer ok, with [permission errors being raised](https://travis-ci.org/ReactiveMongo/ReactiveMongo/jobs/334134973#L551).

The involved script executing `numactl --interleave=all /path/to/custom/mongod ...`

**Comment by BanzaiMan** [comment] 2018-01-27 20:37
Probably a duplicate of https://github.com/travis-ci/travis-ci/issues/9089.

> I reckon this is a side effect of our recent security updates to deal with Meltdown. https://blog.travis-ci.com/2018-01-08-travis-response-meltdown-spectre

I suggest moving to `sudo: required`.

**Closed by BanzaiMan** 2018-01-27 20:37 UTC

**Comment by Condebk717** [comment] 2018-01-27 20:43
How to reactivate please
