### ISSUE TITLE
sudo: required is ignored

### ISSUE THREAD

**Issue by sebix** [travis-ci/travis-ci#6374] opened 2016-07-28 14:04 UTC
I tried the following three variants, but all are built in the container not supporting sudo. Build information says nevertheless:
> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.

> If you require sudo, add 'sudo: required' to your .travis.yml

> See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Repository:
* `sudo: required`: https://github.com/sebix/intelmq/blob/required/.travis.yml
* `sudo: require`: https://github.com/sebix/intelmq/blob/require/.travis.yml
* `sudo: true`: https://github.com/sebix/intelmq/blob/true/.travis.yml

Builds:
* `sudo: required`: https://travis-ci.org/sebix/intelmq/builds/148039608
* `sudo: require`: https://travis-ci.org/sebix/intelmq/builds/148039592
* `sudo: true`: https://travis-ci.org/sebix/intelmq/builds/148039504

According to the [docs](https://docs.travis-ci.com/user/ci-environment/) there shouldn't be more steps needed. And it worked until recently.

**Comment by michaelmior** [comment] 2016-07-28 14:42
I'm seeing this as well with [this build](https://travis-ci.org/michaelmior/NoSE/builds/148046802). Without any changes to my Travis configuration, this started happening today. Was working fine last night.

**Comment by BanzaiMan** [comment] 2016-07-28 15:10
Sorry for the issue. This is a duplicate of #6372, a potential fix for which we deployed not too long ago. Please push a new commit and confirm it is working for you now.

I'm closing this; if you have further comments, please update #6372.

**Closed by BanzaiMan** 2016-07-28 15:10 UTC

**Comment by sebix** [comment] 2016-08-09 17:42
This happens again: https://travis-ci.org/certtools/intelmq/jobs/150974532
