### ISSUE TITLE
Travis CI fails to switch to oracle jdk8 in OSX

### ISSUE THREAD

**Issue by bmsantos** [travis-ci/travis-ci#4957] opened 2015-10-16 02:23 UTC
```bash
$ jdk_switcher use oraclejdk8
/Users/travis/build.sh: line 41: jdk_switcher: command not found
```

https://travis-ci.org/bmsantos/cola-tests/jobs/85655043

**Comment by BanzaiMan** [comment] 2015-10-19 16:20
Thanks for opening this issue, but I'm closing this as a duplicate of #2316.

**Closed by BanzaiMan** 2015-10-19 16:20 UTC
