### ISSUE TITLE
Chrome not starting correctly 

### ISSUE THREAD

**Issue by shuynh** [travis-ci/travis-ci#7150] opened 2017-01-14 03:14 UTC
can't seem to for the life of my get Xvfb + chrome started on these docker containers, which is causing my specs to fail. builds are green on my current yaml config (`sudo: required`) 

here's what i started with: 
```
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
```
then my specs failed on this -- 
``` 
unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.8.12-040812-generic x86_64)  
```
ssh debug on the machine showed that Xvfb wasn't started because of missing fonts
```
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
```
i added all the fonts to apt except the `cyrillic` because it doesn't seem to be whitelisted. Xvfb wouldn't start because of this. 
 
then, i tried with `google-chrome-beta` package (and all fonts except for cyrillic) and got this --
``` 
Selenium::WebDriver::Error::WebDriverError:
            chrome not reachable
              (Session info: chrome=54.0.2840.90)
              (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.8.12-040812-generic x86_64)
```
a little closer, but chrome's still not starting. what am i missing here? really would like to migrate over to containers. 

could this be related to #6508 ?

**Comment by shuynh** [comment] 2017-01-17 20:31
ok i THINK i've narrowed this down to a docker + chrome issue. 
my setup is: `chrome=55`, `chromedriver=2.27`, `selenium-webdriver 3.0.0`

is it maybe that `/dev/shm` on these container machines are too small? this issue is documented [here](https://github.com/elgalu/docker-selenium/issues/20#issuecomment-133011186), [here](https://github.com/SeleniumHQ/docker-selenium/issues/198#issuecomment-270688135) and [here](https://github.com/SeleniumHQ/docker-selenium/issues/79)

`shm` is 64M, and i think might be causing chrome to crash. while boot-up time is fast, it seems like specs run considerably slower and fail more intermittently in these containers. maybe i'm misunderstanding though!  are there any workarounds for this??

**Comment by BanzaiMan** [comment] 2017-01-17 20:55
It could be. If the issue does not occur on GCE (with `sudo: required`), then try reducing the shared memory size to the same size and see if the problem occurs then.

If it does, it is likely that the shared memory segment size is to blame.

You can't change the size on containers, though, so I don't think we can accommodate Chrome on containers then. Containers run on shared EC2 instance, so changing such kernel parameters would require a lot of consideration.

**Comment by shuynh** [comment] 2017-01-17 21:59
thank you @BanzaiMan. looks like on GCE it is `3.7G     0  3.7G   0% /run/shm` !
this also explains the issue - http://testingrepository.com/fix-no-session-chromedriver-error

so, theres no way to bump up the shm and/or boot docker w/ the `--privileged` flag?

**Comment by BanzaiMan** [comment] 2017-01-17 22:03
Changing the way we boot containers is not a trivial task, as it involves many moving parts and potential breakage and instability. If the issue *is* the shared memory segment, there is no immediate solution available other than to use GCE and document it.

**Comment by shuynh** [comment] 2017-01-17 22:04
will do, should i close this issue for now?

**Comment by BanzaiMan** [comment] 2017-01-17 22:05
Docs improvement might be good. Not sure where it should fit yet. I'll keep this open for a little longer.

**Comment by meatballhat** [comment] 2017-01-20 19:53
We have a fix in the works via https://github.com/travis-ci/worker/pull/260, which, once merged, will require additional configuration over in https://github.com/travis-infrastructure/terraform-config and an infrastructure refresh before this issue can be closed.

**Comment by jantman** [comment] 2017-10-29 21:11
For what it's worth, current (62) chrome stable seems to work correctly in the containerized (``sudo: false``) trusty environment using Chrome's new ``--headless`` mode, which doesn't require xvfb. You just need to install the ``google-chrome-stable`` package using the docker package installation, i.e.:

```yaml
addons:
  apt:
    packages:
      - google-chrome-stable
```

instead of the documented addon:

```yaml
addons:
  chrome: stable
```

**Comment by CyborgMaster** [comment] 2017-12-16 00:42
I just started using TravisCI pro and am getting Chrome crashes with the following error messages from Selenium:

```
Selenium::WebDriver::Error::UnknownError:         Selenium::WebDriver::Error::UnknownError: unknown error: session deleted because of page crash
        from unknown error: cannot determine loading status
        from tab crashed
          (Session info: headless chrome=62.0.3202.94)
          (Driver info: chromedriver=2.33,platform=Linux 4.9.6-040906-generic x86_64)
```
These are the same errors discussed in the pages referenced by @shuynh, which makes me think that this is likely still a /dev/shm problem.  Has there been any progress in allowing us to increase the size of that volume in TravisCI?

**Comment by stramel** [comment] 2018-01-20 04:47
I am running into issues with using `sudo: false` + `--headless --disable-gpu`

**Comment by inad9300** [comment] 2018-01-29 18:02
@stramel Adding the `--no-sandobx` flag worked for me too, using the Intern framework. It's even recommended in Travis' docs (https://docs.travis-ci.com/user/chrome#Sandboxing), but it doesn't sound like the idea solution.

**Comment by stramel** [comment] 2018-01-29 18:27
@inad9300 The `--disable-gpu` is primarily for windows machines. (so not needed for travis) https://bugs.chromium.org/p/chromium/issues/detail?id=737678

**Comment by BanzaiMan** [comment] 2018-01-29 20:39
Sounds like this is a different manifestation of https://github.com/travis-ci/travis-ci/issues/8836, which says that some functionalities of Chrome may assume the sandbox feature, and disabling it with `--no-sandbox` (see https://docs.travis-ci.com/user/chrome#Sandboxing) helps on containers. (Alternately, you may use `sudo: required`.)

I'm closing this now.

**Closed by BanzaiMan** 2018-01-29 20:39 UTC
Labels: docs, trusty-container

**Comment by CyborgMaster** [comment] 2018-01-30 01:40
I'm fairly certain that this isn't the same issue as #8836 and petition to re-open this issue.  

I just tried it with the `--no-sandbox` options and am still getting crashes. 

Here is the relevant travis config:
``` yaml
dist: trusty
sudo: false

language: ruby
services:
  - mysql
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
```

and here's how I'm setting up selenium:
``` ruby
Capybara.register_driver :chrome do |app|
  browser_options = ::Selenium::WebDriver::Chrome::Options.new
  browser_options.args << '--headless'
  browser_options.args << '--disable-gpu'
  browser_options.args << '--window-size=1920,2000'
  browser_options.args << '--no-sandbox' if ENV['CONTINUOUS_INTEGRATION']
  Capybara::Selenium::Driver.new app, browser: :chrome, options: browser_options
end
Capybara.javascript_driver = :chrome
```

However, when running like this, I still get errors like this:
```
Selenium::WebDriver::Error::UnknownError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33,platform=Linux 4.14.12-041412-generic x86_64)
```

Running this with `sudo: required` causes the problem to go away.

It still seems to me to be caused by a too small `/dev/shm`, which can be configured in docker to boot with larger amount of memory.

**Comment by Dantemss** [comment] 2018-04-26 18:13
I found here: https://developers.google.com/web/tools/puppeteer/troubleshooting that Chrome 65 added a `--disable-dev-shm-usage` flag (the Travis addon installs Chrome 66 at the moment so we're fine). Specifying that together with `--headless` and `--no-sandbox` seems to have solved this for me.

**Comment by kyle-glick** [comment] 2018-07-12 16:10
I was having the same issue as @CyborgMaster. @Dantemss's solution worked for me as well.

**Comment by blimmer** [comment] 2019-01-09 21:54
Instead of trying to resolve all the issues with headless mode + Travis, I have switched to [using XVFB](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-directly), which removes my need to set any variables compared to my desktop machine.
