### ISSUE TITLE
Insecure world writable dir /usr/local/clang-5.0.0/bin in PATH, mode 040777

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#8645] opened 2017-10-26 08:41 UTC
I'm seeing this warning since a couple of days, both in the 'worker information' as we well as later when using the dpl ruby tool.

~~~~
hostname: 3f803a3d-9e56-49bc-a023-9715a862bc6a@1.production-1-worker-com-f-9-gce
version: v3.1.0 https://github.com/travis-ci/worker/tree/5b106cb773802277034d07b0a865af58d67bb1d2
instance: testing-gce-8988d2b0-7a44-4b71-964b-dea8ed69dd6d:travis-ci-garnet-trusty-1508249796-29cd77f (via amqp)
startup: 21.715372375s
/home/travis/filter.rb:63: warning: Insecure world writable dir /usr/local/clang-5.0.0/bin in PATH, mode 040777
~~~~

**Comment by bogdanap** [comment] 2017-12-13 10:12
Closing as duplicate of https://github.com/travis-ci/travis-cookbooks/issues/943

**Closed by bogdanap** 2017-12-13 10:12 UTC
