### ISSUE TITLE
Deploy on OpenShift V3

### ISSUE THREAD

**Issue by nmdantas** [travis-ci/travis-ci#8875] opened 2017-12-08 18:49 UTC
I have been unable to deploy a NodeJS application on OpenShift 3, I've updated .yml file with the instructions at openshift documentation section, but I still getting the error on deploy. Seeing the log, the error occurs in authentication using RHC client ("Not authenticated (RHC::Rest::UnAuthorizedException)"), but the version 3 of OpenShift no longer uses that client, they have OC client now, my question is, any application already have been deployed on OpenShift 3 using Travis? Travis have support for this?

**Comment by BanzaiMan** [comment] 2017-12-10 15:46
I’m closing this as a duplicate of https://github.com/travis-ci/dpl/issues/705.

**Closed by BanzaiMan** 2017-12-10 15:46 UTC
