### ISSUE TITLE
The command "eval sudo apt-get install -y r-cran-devtools " failed

### ISSUE THREAD

**Issue by mrustl** [travis-ci/travis-ci#7654] opened 2017-04-24 12:54 UTC
@craigcitro and @jimhester 

See: https://travis-ci.org/KWB-R/aquanes.report/builds/225194440

**Comment by singmann** [comment] 2017-04-24 19:54
pinging @craigcitro and @jimhester as advised. I have the same problem.

**Comment by jimhester** [comment] 2017-04-24 20:26
Typically this is just due to a transient issue, try restarting the build and see if it works the second time.

**Comment by corinsexton** [comment] 2017-04-24 21:51
Same problem here @jimhester. I've restarted 3 times.

https://travis-ci.org/corinsexton/MAGNAMWAR/builds/225389057

**Comment by singmann** [comment] 2017-04-25 08:06
Still happening for me. Even after 12 hours and a few tries: 
https://travis-ci.org/quentingronau/bridgesampling/builds/225345813

**Comment by singmann** [comment] 2017-04-25 08:15
One can avoid this problem when following the instruction (here)[https://blog.travis-ci.com/2017-04-17-precise-EOL] and add the following to the `.travis.yml`:
```
dist: trusty
```
Should not be necessary anymore in a few weeks when trusty is the default `sudo: true` setup.

**Comment by mrustl** [comment] 2017-04-25 08:41
Thanks @singmann that works nicely!

**Comment by mschilli87** [comment] 2017-04-25 14:10
I hit the same issue but I don't understand the cause/solution:

The linked blog post comments on Ubuntu 12.04 (precise) loosing support and the upcoming switch to Ubuntu 14.04 (trusty) image by default.

However, it clearly says:

> - All builds using Precise 12.04 after April 28th, the EOL date, will be working as usual.

So first of all, the support did not end yet.
Second, build *should* remain working even after trusty's end-of-life.

The only thing that is suggestive of a failing `apt-get install` is the following:

> - There will be [apt repo URL changes upstream at Canonical](http://old-releases.ubuntu.com/) for Precise 12.04 and this will be updated in [travis-build](https://github.com/travis-ci/travis-build) to continue fetching precise apt-packages during build time.

So there is a URL change, but it should be handled properly by travis-build.
Again, I don't see why any of this should result in all our builds failing on setup.

The 'solution' suggested is mentioned in the blog post in another context:

> If you’d like to go ahead and start testing how Ubuntu Trusty would work for you, feel free to specify `dist: trusty` directly in your `.travis.yml` file.

I think a no time, the default should be broken: If trusty becomes the default, I'll use trusty, but as long as precise is the default, I expect it to work.
Moreover, the blog post promises

> - For those using the default sudo: false container-based Precise 12.04 images: everything will continue as it is.

and

> - `sudo: required` images will be getting one last round of service and distribution updates, and will be available long-term as-is. These updates are already available and are tagged with `group: edge`, and will be promoted to stable on May, 3rd 2017. We will retain the previous `group: stable` as `group: deprecated` following this update.

So precise remains the default as of now because it *should* (still) work as of now.
And even once trusty becomes the default, setting `dist: precise` in `travis.yml` should keep working.

So why do I need to actively switch the distribution to trusty now?
I'd just use something 'experimental' (I know that's exaggerated speaking of Ubuntu 14.04) now instead of the (*still*! recommended) default and risk missing the next update (that is when 16.04 becomes the default and I keep running 14.04 because I forgot removing the `dist: trusty` from my `travis.yml`.

Can someone please shed some light on what is going on and what isn't?
And if the recommended solution is to switch from precise to trusty now, why should every user do this explicetly instead of changing the default (*now*)?

**Comment by mhines-usgs** [comment] 2017-04-25 14:23
Thanks, seems to be helping my failed build, too. :D

**Comment by BanzaiMan** [comment] 2017-04-25 14:38
@mschilli87 I do not think our ongoing effort to switch to Trusty has anything to do with the error you are seeing. The package r-cran-devtools is provided by a third-party repository set up by the R build (I am guessing it's the CRAN mirror; perhaps someone can confirm).

If the build continues to fail for `dist: precise` (which is the default), but works with `dist: trusty`, then the explanation is that someone who is maintaining the R repository pulled the plug on the Precise package. This is beyond our control. If you want to continue using Precise, I suggest getting in touch with the repository maintainer(s).

**Comment by mschilli87** [comment] 2017-04-25 15:02
@BanzaiMan Thx for the feedback.
That sounds much more reasonable to me.
As trusty will become the default in July, I guess I'll have to switch to trusty until the as it's gonne be hard to convince anyone to re-introduce support for 12.04 just when it's official support ends for a use case of a couple of months.

In general I think it would still be worthwhile to aim for updating the default image distribution before it's EOL (as now precise will remain the default on Travis until July at least, without any official support) to avoid such cases in the future.

**Comment by marutter** [comment] 2017-04-26 02:42
Said maintainer of the R Ubuntu packages raising his hand to confirm the removal of the Precise R packages from CRAN and the PPA's as we reach EOL.  I stopped updating the Precise packages about a year ago when we were unable to build R 3.3.0 in May of 2016.  I ran out of space on the c2d4u PPA and with Precise EOL on Friday, it was time to move on.

My apologizes for throwing a wrench in the works.  I don't use Travis, so I am not really aware of the level of dependence or the progress in moving to Trusty.  I think it is great that you are using the packages that have been made available.  Hopefully, when Trusty goes EOL in 2019, I can cushion the transition better.

**Closed** 2017-04-27 11:58 UTC
Labels: community:r

**Comment by i2000s** [comment] 2017-04-29 18:00
@marutter and others, thanking for putting the efforts on updating the service! I don't know the space limitation of the PPA repos. Is it possible to have old PPA binary builds stored somewhere permanently (like to have a doi forwarding) so that if people fix the `dist: trusty` setting in Travis-ci for later Travis-ci updates, those ppa packages can still be retrieved? If either Travis-ci or other communities can offer this type of support, that will be wonderful to me!
