### ISSUE TITLE
OSX worker image cannot download Python from s3 amazon

### ISSUE THREAD

**Issue by psi29a** [travis-ci/travis-ci#7240] opened 2017-01-30 12:50 UTC
Builds are failing on OSX worker images because it can't download the different Pythonv versions from Amazon.

Link: https://travis-ci.org/psi29a/pyffi/builds/196560238

Output:
> 3.5 is not installed; attempting download[0m
> Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.12/x86_64/python-3.5.tar.bz2[0m
> $ sudo tar xjf python-3.5.tar.bz2 --directory /
> tar: Unrecognized archive format
> tar: Error exit delayed from previous errors.
> The command "sudo tar xjf python-3.5.tar.bz2 --directory /" failed and exited with 1 during .

If I try to directly go to link provided above I get:
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied</Message>
> <RequestId>FB6D262F8270200B</RequestId>
> <HostId>8GfDC7JXuy0FQ8ldqn+U+EXDraMNuciN/C1LuHkCilPUsBG4fc7QvmN7/hTmq1SwjDUwIXnJ5hM=</HostId>
> </Error>

Here is the full readout:
https://travis-ci.org/psi29a/pyffi/jobs/196560246

**Comment by BanzaiMan** [comment] 2017-01-30 13:00
We do not support Python on the Mac at the moment. This is a duplicate of #2312.

**Closed by BanzaiMan** 2017-01-30 13:00 UTC

**Comment by psi29a** [comment] 2017-01-30 13:07
Really, then how does this work?
https://travis-ci.org/psi29a/pyffi/jobs/196560248

> nightly is not installed; attempting download
> Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.12/x86_64/python-nightly.tar.bz2
> $ sudo tar xjf python-nightly.tar.bz2 --directory /

**Comment by BanzaiMan** [comment] 2017-01-30 13:14
`nightly` works because the archive exists, and it does because it was once built. Others are not.

**Comment by psi29a** [comment] 2017-01-30 13:16
Thanks for that. Does "at the moment" mean future support? :)
