### ISSUE TITLE
fails to install pypy or pypy3

### ISSUE THREAD

**Issue by niklasf** [travis-ci/travis-ci#7972] opened 2017-06-25 08:20 UTC
Example build: https://travis-ci.org/niklasf/python-chess/jobs/246728295

```
pypy is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/-.tar.bz2
                            note the wierd filename ----------------------------------------------^^^

$ sudo tar xjf -.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf -.tar.bz2 --directory /" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by BanzaiMan** [comment] 2017-06-25 13:54
duplicate of #6865

**Closed by BanzaiMan** 2017-06-25 13:54 UTC
Labels: python
