### ISSUE TITLE
libgeoip-dev fails to install

### ISSUE THREAD

**Issue by meejah** [travis-ci/travis-ci#5341] opened 2015-12-19 23:06 UTC
It appears from #4086 that installing libgeoip-dev should work (and, it has for me in the past). But now it is failing. For example: https://travis-ci.org/meejah/txtorcon/jobs/97896833

I tried adding ``dist:precise`` and ``sudo: required`` explicitly but that didn't seem to fix it. This was working minimum 17 days ago, according to my build history (e.g. https://travis-ci.org/meejah/txtorcon/builds/94570577 worked) with the same install line.

**Comment by BanzaiMan** [comment] 2015-12-20 01:40
I believe this is a duplicate of #5221. Please run `sudo apt-get update` prior to the first invocation of `sudo apt-get install`. Thanks.

**Closed by BanzaiMan** 2015-12-20 01:40 UTC
