### ISSUE TITLE
PHP 7.3 "bzip2: (stdin) is not a bzip2 file."

### ISSUE THREAD

**Issue by majkel89** [travis-ci/travis-ci#10068] opened 2018-09-01 08:12 UTC
I'm constantly getting the error `bzip2: (stdin) is not a bzip2 file.` when building using php 7.3.

https://travis-ci.org/majkel89/dbase/jobs/423235227

**Comment by Majkl578** [comment] 2018-09-06 21:14
Duplicate of #9717, 7.3 is not supported yet.

**Closed** 2018-09-07 13:06 UTC
Labels: php
