### ISSUE TITLE
Storing the build cache fails without an error

### ISSUE THREAD

**Issue by bdesham** [travis-ci/travis-ci#6326] opened 2016-07-17 18:34 UTC
[This OS X build log](https://travis-ci.org/bdesham/pinboard-notes-backup/jobs/145374485) ends with

```
travis_fold start cache.2
  echo -e "store build cache"
store build cache
  if [[ -f $CASHER_DIR/bin/casher ]]; then
    travis_cmd type\ rvm\ \&\>/dev/null\ \|\|\ source\ \~/.rvm/scripts/rvm --timing
    travis_cmd rvm\ 1.9.3\ --fuzzy\ do\ \$CASHER_DIR/bin/casher\ push\ https://travis-cache-production-org-gce.storage.googleapis.com/62139448/v1.0.1-test3/cache-osx-precise-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--compiler-gcc.tgz\\\?Expires\\\=1468784314\\\&GoogleAccessId\\\=GOOGZFGMULTAVLI3C63H\\\&Signature\\\=PHE\\\%2BeM8Oc2AxqG\\\%2FVSAXFyvLulLI\\\%3D --timing
  fi
printf %08x $(( RANDOM * RANDOM ))
travis_nanoseconds
uname
stype rvm &>/dev/null || source ~/.rvm/scripts/rvm
travis_nanoseconds
uname
printf %08x $(( RANDOM * RANDOM ))
travis_nanoseconds
uname
rvm 1.9.3 --fuzzy do $CASHER_DIR/bin/casher push https://travis-cache-production-org-gce.storage.googleapis.com/62139448/v1.0.1-test3/cache-osx-precise-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--compiler-gcc.tgz\?Expires\=1468784314\&GoogleAccessId\=GOOGZFGMULTAVLI3C63H\&Signature\=PHE\%2BeM8Oc2AxqG\%2FVSAXFyvLulLI\%3D
umask
```

and the build is marked as failed. However, as far as I can see there are no error messages here. What’s going wrong with my build? [Here](https://github.com/bdesham/pinboard-notes-backup/blob/master/.travis.yml) is a direct link to the relevant travis.yml file.

**Comment by bdesham** [comment] 2016-07-17 18:36
This may have been caused by the same confusion as in #5120… I’ll investigate.

**Comment by BanzaiMan** [comment] 2016-07-22 16:05
Indeed, I think this is a duplicate of #5120. https://github.com/bdesham/pinboard-notes-backup/blob/98c0ab5fce9849a0ff04d34554c54895d5773a0e/.travis.yml#L37

**Closed by BanzaiMan** 2016-07-22 16:05 UTC

**Comment by bdesham** [comment] 2016-07-22 16:14
Oh, yes, I meant to close this issue. Thank you.
