### ISSUE TITLE
All JDK 9 builds failing today 

### ISSUE THREAD

**Issue by JLLeitschuh** [travis-ci/travis-ci#8608] opened 2017-10-18 17:48 UTC
It seems that the oracle JDK 9 builds have all been failing for the past day or so.

This is the `travis.yml` [file we are using](https://github.com/gradle/kotlin-dsl/blob/master/.travis.yml):
```yml
language: java

matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk8
    - os: linux
      sudo: false
      jdk: openjdk8
    - os: linux
      sudo: false
      jdk: oraclejdk9 # JDK 9+175 or newer
      addons:
        apt:
          packages:
            - oracle-java9-installer # Forces use of even newer JDK 9 build

script: ./gradlew :provider:check --info --stacktrace --console=plain --max-workers=1 --no-daemon -Dkotlin.compiler.execution.strategy="in-process" -Dkotlin.colors.enabled=false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```

Here's the history of our builds, you can see that the most recent ones have all been failing for pretty much the same reason.
https://travis-ci.org/gradle/kotlin-dsl/builds

Here's one of the logs:
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install oracle-java9-installer
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  visualvm ttf-baekmuk | ttf-unfonts | ttf-unfonts-core ttf-kochi-gothic
  | ttf-sazanami-gothic ttf-kochi-mincho | ttf-sazanami-mincho
  ttf-arphic-uming
The following packages will be upgraded:
  oracle-java9-installer
1 upgraded, 0 newly installed, 0 to remove and 84 not upgraded.
Need to get 30.5 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 oracle-java9-installer amd64 9b181-1~webupd8~2 [30.5 kB]
Fetched 30.5 kB in 0s (94.4 kB/s)
Preconfiguring packages ...
(Reading database ... 74154 files and directories currently installed.)
Preparing to unpack .../oracle-java9-installer_9b181-1~webupd8~2_amd64.deb ...
oracle-license-v1-1 license has already been accepted
Unpacking oracle-java9-installer (9b181-1~webupd8~2) over (9b181-1~webupd8~0) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Setting up oracle-java9-installer (9b181-1~webupd8~2) ...
No /var/cache/oracle-jdk9-installer/wgetrc file found.
Creating /var/cache/oracle-jdk9-installer/wgetrc and
using default oracle-java9-installer wgetrc settings for it.
Downloading Oracle Java 9...
--2017-10-18 15:04:22--  http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.215.130.114, 23.215.130.99
Connecting to download.oracle.com (download.oracle.com)|23.215.130.114|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz [following]
--2017-10-18 15:04:22--  https://edelivery.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.49.182.138, 2600:1408:10:286::2d3e, 2600:1408:10:297::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.49.182.138|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz?AuthParam=1508339182_62351694bd405d29ca77588f46f527d9 [following]
--2017-10-18 15:04:22--  http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz?AuthParam=1508339182_62351694bd405d29ca77588f46f527d9
Connecting to download.oracle.com (download.oracle.com)|23.215.130.114|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-18 15:04:23 ERROR 404: Not Found.
download failed
Oracle JDK 9 is NOT installed.
dpkg: error processing package oracle-java9-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 InRelease
Hit:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release
Get:3 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release.gpg [801 B]
Hit:5 http://dl.hhvm.com/ubuntu trusty InRelease
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:4 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:7 http://toolbelt.heroku.com/ubuntu ./ Release
Hit:8 http://dl.google.com/linux/chrome/deb stable Release
Hit:10 http://security.ubuntu.com/ubuntu trusty-security InRelease
Hit:12 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
Ign:13 http://archive.ubuntu.com/ubuntu trusty InRelease
Get:9 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Hit:15 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Hit:16 http://archive.ubuntu.com/ubuntu trusty-updates InRelease
Hit:17 http://archive.ubuntu.com/ubuntu trusty-backports InRelease
Hit:18 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease
Hit:19 http://archive.ubuntu.com/ubuntu trusty Release
Ign:20 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Hit:22 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
Hit:23 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease
Get:24 https://packagecloud.io/basho/riak/ubuntu trusty InRelease
Ign:24 https://packagecloud.io/basho/riak/ubuntu trusty InRelease
Hit:25 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease
Hit:26 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
Hit:27 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Hit:29 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Hit:30 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Hit:31 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease
Get:32 https://packagecloud.io/basho/riak/ubuntu trusty Release
Ign:32 https://packagecloud.io/basho/riak/ubuntu trusty Release
Ign:33 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources
Ign:34 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages
Ign:36 https://packagecloud.io/basho/riak/ubuntu trusty/main all Packages
Ign:33 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources
Ign:34 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages
Ign:36 https://packagecloud.io/basho/riak/ubuntu trusty/main all Packages
Ign:33 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources
Ign:34 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages
Ign:36 https://packagecloud.io/basho/riak/ubuntu trusty/main all Packages
Ign:33 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources
Ign:34 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages
Ign:36 https://packagecloud.io/basho/riak/ubuntu trusty/main all Packages
Ign:33 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources
Ign:34 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages
Ign:36 https://packagecloud.io/basho/riak/ubuntu trusty/main all Packages
Err:33 https://packagecloud.io/basho/riak/ubuntu trusty/main Sources
  HttpError401
Err:34 https://packagecloud.io/basho/riak/ubuntu trusty/main amd64 Packages
  HttpError401
Err:35 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages
  HttpError401
Ign:36 https://packagecloud.io/basho/riak/ubuntu trusty/main all Packages
Fetched 3,969 B in 5s (714 B/s)
Reading package lists...
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: The repository 'https://packagecloud.io/basho/riak/ubuntu trusty Release' does not have a Release file.
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/main/source/Sources  HttpError401
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/main/binary-amd64/Packages  HttpError401
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/trusty/main/binary-i386/Packages  HttpError401
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install oracle-java9-installer" failed and exited with 100 during .
```

**Comment by BanzaiMan** [comment] 2017-10-18 19:07
Duplicate of #8600. Oracle appears to have removed the archive.

**Closed by BanzaiMan** 2017-10-18 19:07 UTC
