### ISSUE TITLE
PyPy environment is broken for the new Travis CI ubuntu 14.04.5 image 

### ISSUE THREAD

**Issue by elemount** [travis-ci/travis-ci#7977] opened 2017-06-26 03:19 UTC
PyPy build environment is broken for the new Travis CI build.
For the same commit on the same branch, PyPy env is broken.
Comparing https://travis-ci.org/PyMySQL/PyMySQL/jobs/245310487 with https://travis-ci.org/PyMySQL/PyMySQL/jobs/246118949 .
The error message is 

```
Patching redis-server init script
pypy is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/-.tar.bz2
$ sudo tar xjf -.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command "sudo tar xjf -.tar.bz2 --directory /" failed and exited with 2 during .
Your build has been stopped.
```

The origin build info is
```
Worker information
hostname: production-2-worker-org-b-2-gce:44b7a69f-ab91-456c-a4f8-522daf39b3ad
version: v2.7.0 https://github.com/travis-ci/worker/tree/66fc24311e055643710f4e0567f6888c927d3ab8
instance: testing-gce-3620c9f1-782a-4eb9-aac5-95802ed4e76a:travis-ci-sugilite-trusty-1480960799
startup: 21.260425885s
system_info
Build system information
Build language: python
Build group: stable
Build dist: trusty
Build id: 245310481
Job id: 245310487
travis-build version: c72e0fe0d
Build image provisioning date and time
Mon Dec  5 18:47:20 UTC 2016
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Linux Version
4.4.0-51-generic
Cookbooks Version
998099c https://github.com/travis-ci/travis-cookbooks/tree/998099c
```
and the broken one is
```
Worker information
hostname: production-4-worker-org-c-3-gce:39840cec-9ee6-4736-9685-cce914c52ad6
version: v2.7.0 https://github.com/travis-ci/worker/tree/66fc24311e055643710f4e0567f6888c927d3ab8
instance: testing-gce-49e98f26-af75-4348-ab26-0f5ab8f0406b:travis-ci-sugilite-trusty-1498160800
startup: 21.596169186s
system_info
Build system information
Build language: python
Build group: stable
Build dist: trusty
Build id: 246118943
Job id: 246118949
travis-build version: abafa3b18
Build image provisioning date and time
Thu Jun 22 20:58:29 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Linux Version
4.4.0-81-generic
Cookbooks Version
ab523d9 https://github.com/travis-ci/travis-cookbooks/tree/ab523d9
 ```

**Comment by BanzaiMan** [comment] 2017-06-26 09:29
Basically the duplicate of #6865. The image does not have `pypy`/`pypy3` installed, and the current on-demand installation cannot find the appropriate archive.

**Closed by BanzaiMan** 2017-06-26 09:29 UTC
Labels: python
