### ISSUE TITLE
MacOs public builds not starting

### ISSUE THREAD

**Issue by j3mdamas** [travis-ci/travis-ci#9075] opened 2018-01-15 21:27 UTC
Hi,

We've been experiencing problems with public builds of MacOS, with them taking too long to start or not even starting. Checking https://www.traviscistatus.com/, it seems like the capacity for MacOS builds has been severely diminished and the backlog is accumulating to almost 2000 builds.

Is this a situation that you are addressing or are you planning on terminating the support for MacOS builds?

Thanks,
João

**Comment by szeck87** [comment] 2018-01-15 22:52
Has been an issue the last several days:  https://www.traviscistatus.com/incidents/6xb4kjczh4k6

**Comment by kosloot** [comment] 2018-01-16 10:32
still Isn't solved :{

**Comment by maelvalais** [comment] 2018-01-16 14:16
Looks like they increased the number of macOS workers from 90 to 180 at 2pm CET!
Backlog is still at ~1800 but let's hope it will lower!

**Comment by BanzaiMan** [comment] 2018-01-17 17:11
The Mac queue is in general overwhelmed by demand. We did have build request processing issue yesterday and this didn't help. The issue is now resolved, but the general wait time will remain.

I'm closing this now.

**Closed by BanzaiMan** 2018-01-17 17:11 UTC
