### ISSUE TITLE
Feature Request: detect connection timeouts building upstream dependencies and auto-retry builds

### ISSUE THREAD

**Issue by HariSekhon** [travis-ci/travis-ci#9311] opened 2018-03-08 11:36 UTC
I often see upstream timeouts failing builds and there are a few tickets open for these issues across languages and builds.

Feature Request to detect when the last failing commands were the result of network / upstream dependency timeouts (regex matching of the last N lines would suffice) and auto-reschedule build retries with an exponential back-off between each retry.

To maintain backwards compatibility you could enable this as a configuration option including the regex and number of lines back to search.

**Comment by BanzaiMan** [comment] 2018-03-25 03:27
I understand that there are unresolved issues that we need to improve, but I feel that detecting and restarting the affected jobs automatically is going to require far more resources to achieve than actually finding the cause of network issues.

Here's why:

I don't think this is generally possible to understand some command failed because of network problems. Any command can use network (`curl`, `wget`, `ruby`, `python`, `node`) and they do not give you hints (if any) about the cause of the failure in a uniform way.

Furthermore, rescheduling a job requires another component to know that the job failed *because of* network issues.

Again, I understand why you might think such a feature is useful, but I'm closing this, since it is very unlikely that we can work on it.

**Closed by BanzaiMan** 2018-03-25 03:27 UTC
