### ISSUE TITLE
Ubuntu package libsdl2-dev installation fails on Trusty image

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [travis-ci/travis-ci#8330] opened 2017-09-02 11:48 UTC
Hi,

My Travis CI Linux build suddenly stopped working on August, 30. It was working fine and I did not change anything. It seems that libsdl2-dev package can't be installed anymore. Did you change something to the Trusty images ?

```
if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y update; fi

Ign:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty InRelease

Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates InRelease

Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports InRelease

Hit:4 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty Release

Ign:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 InRelease

Hit:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release

Hit:7 http://security.ubuntu.com/ubuntu trusty-security InRelease

Ign:9 http://dl.google.com/linux/chrome/deb stable InRelease

Hit:10 http://dl.hhvm.com/ubuntu trusty InRelease

Hit:11 http://dl.google.com/linux/chrome/deb stable Release

Get:12 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages [1,204 kB]

Ign:8 http://toolbelt.heroku.com/ubuntu ./ InRelease

Get:14 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates/restricted i386 Packages [20.9 kB]

Get:15 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates/universe i386 Packages [550 kB]

Hit:16 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease

Get:17 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates/multiverse i386 Packages [16.1 kB]

Hit:18 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease

Hit:19 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease

Get:20 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports/main i386 Packages [14.8 kB]

Get:21 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports/restricted i386 Packages [40 B]

Get:22 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports/universe i386 Packages [52.5 kB]

Get:23 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-backports/multiverse i386 Packages [1,381 B]

Ign:24 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease

Get:26 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/main i386 Packages [1,739 kB]

Hit:27 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease

Hit:28 https://download.docker.com/linux/ubuntu trusty InRelease

Get:29 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/restricted i386 Packages [16.4 kB]

Get:30 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/universe i386 Packages [7,597 kB]

Hit:32 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease

Get:33 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages [29 B]

Hit:34 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease

Hit:13 http://toolbelt.heroku.com/ubuntu ./ Release

Hit:35 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease

Get:36 http://security.ubuntu.com/ubuntu trusty-security/main i386 Packages [758 kB]

Hit:37 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release

Get:38 http://dl.hhvm.com/ubuntu trusty/main i386 Packages [20 B]

Get:40 http://security.ubuntu.com/ubuntu trusty-security/restricted i386 Packages [17.6 kB]

Get:41 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty/multiverse i386 Packages [172 kB]

Get:42 http://security.ubuntu.com/ubuntu trusty-security/universe i386 Packages [236 kB]

Get:43 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,716 B]

Get:44 http://security.ubuntu.com/ubuntu trusty-security/multiverse i386 Packages [4,183 B]

Hit:45 https://packagecloud.io/basho/riak/ubuntu trusty InRelease

Hit:46 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease

Get:47 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty/main i386 Packages [1,611 B]

Hit:49 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease

Get:50 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,464 B]

Get:51 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [122 kB]

Get:48 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]

Get:52 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [4,392 B]

Hit:53 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease

Get:55 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [445 B]

Get:57 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages [3,145 B]

Get:58 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages [985 B]

Get:59 https://packagecloud.io/basho/riak/ubuntu trusty/main i386 Packages [20 B]

Get:60 https://packagecloud.io/computology/apt-backport/ubuntu trusty/main i386 Packages [848 B]

Get:62 https://packagecloud.io/github/git-lfs/ubuntu trusty/main i386 Packages [4,779 B]

Get:61 http://dl.bintray.com/apache/cassandra 39x/main i386 Packages [682 B]

Get:63 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty/main i386 Packages [3,025 B]

Fetched 12.6 MB in 2s (5,638 kB/s)

Reading package lists... Done

W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)

W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

0.57s$ if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev; fi

Reading package lists... Done

Building dependency tree       

Reading state information... Done

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:

The following packages have unmet dependencies:

 libsdl2-dev : Depends: libegl1-mesa-dev

               Depends: libgles2-mesa-dev

E: Unable to correct problems, you have held broken packages.

The command "if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev; fi" failed and exited with 100 during .

Your build has been stopped.
```

Travis CI is a good service, thank you for providing it.

Regards,
Adrien

**Comment by BanzaiMan** [comment] 2017-09-02 13:17
Duplicate of #8317. The root cause is unknown, but there are a couple of workarounds suggested there.

**Closed by BanzaiMan** 2017-09-02 13:17 UTC
