### ISSUE TITLE
APCu not present on PHP 7.0 (Trusty)

### ISSUE THREAD

**Issue by nazar-pc** [travis-ci/travis-ci#8151] opened 2017-07-24 07:00 UTC
One more inconsistency: https://travis-ci.org/nazar-pc/CleverStyle-Framework/builds/256768597
APCu is installed on PHP 7.1 and Nightly, but not on 7.0.
Documentation says it should be there.

**Comment by BanzaiMan** [comment] 2017-07-24 13:34
Duplicate of #7525.

**Closed by BanzaiMan** 2017-07-24 13:34 UTC
