### ISSUE TITLE
Too many Fixed mails for CRON jobs

### ISSUE THREAD

**Issue by sokra** [travis-ci/travis-ci#8506] opened 2017-09-27 05:42 UTC
Small bug with Emails send from CRON Jobs.

It happens when:
* Normal build failed
* Cron build succeed multiple times

Issue:
Each succeeded cron job sends a "Fixed" mail (see image)

Expected behavior:
Only the first succeeded cron build reports via "Fixed" mail.

Problem:
My guess is that job results are only compared against lastest normal build but it should be compared against lastest build from normal and cron builds.

![image](https://user-images.githubusercontent.com/1365881/30897569-3cba0430-a357-11e7-92a2-88fb39b1a838.png)

![image](https://user-images.githubusercontent.com/1365881/30897574-4337ab32-a357-11e7-8e5b-d0bae205f6e0.png)

**Comment by BanzaiMan** [comment] 2017-09-27 07:23
Do you have `fast_finish: true` set? If so, I believe this is a duplicate of https://github.com/travis-ci/travis-ci/issues/1696.

**Comment by BanzaiMan** [comment] 2017-10-06 19:28
https://github.com/webpack/webpack/blob/b8f181f57fdc33fc8fccd99e07a3684c9fb723d6/.travis.yml#L32

Closing as a duplicate.

**Closed by BanzaiMan** 2017-10-06 19:29 UTC
Labels: notifications
