### ISSUE TITLE
Crystal build fails, missing signature

### ISSUE THREAD

**Issue by waghanza** [travis-ci/travis-ci#8020] opened 2017-07-03 09:52 UTC
Hi,

I have a build (https://travis-ci.org/waghanza/cab/jobs/249345022) failing.

@asterite @jhass @waj @will : The signature is missing for gpg keys on https://dist.crystal-lang.org/

Regards,

**Comment by waghanza** [comment] 2017-07-03 09:54
@BanzaiMan I can not add crystal label

**Comment by BanzaiMan** [comment] 2017-07-03 11:30
Duplicate of #8005.

**Closed by BanzaiMan** 2017-07-03 11:30 UTC
