### ISSUE TITLE
Postgres server version change is stochastic

### ISSUE THREAD

**Issue by wasade** [travis-ci/travis-ci#4578] opened 2015-07-27 23:33 UTC
I have a need for Postgres Server >= 9.3, however, switching the version appears to be successful only part of the time. Here is the relevant [line](https://github.com/wasade/american-gut-rest/blob/master/.travis.yml#L4) `.travis.yml`. An example of the failed build can be found [here](https://travis-ci.org/wasade/american-gut-rest/builds/72531587). An example of a successful build can be found [here](https://travis-ci.org/wasade/american-gut-rest/builds/72494858).

**Comment by BanzaiMan** [comment] 2015-07-28 00:46
Thanks for opening the issue, but this is a duplicate of #4570, the fix for which we deployed earlier today. Please restart the failing build, and let us know if you see further problems.

**Closed by BanzaiMan** 2015-07-28 00:46 UTC

**Comment by wasade** [comment] 2015-07-28 01:35
Ah, thank you and I apologize for the duplicate -- I didn't search
thoroughly enough.
