### ISSUE TITLE
Build failing after 10 minutes of inactivity, ignore end of bash script

### ISSUE THREAD

**Issue by flodolo** [travis-ci/travis-ci#8106] opened 2017-07-18 06:46 UTC
I have a [repository](https://github.com/mozilla-l10n/localizer-documentation/blob/master/.travis.yml) running two scripts, one node.js and one bash.

The bash script generates a GitBook version of the repository and pushes it to the gh-pages branch, so it's run only when a pull request is merged to master. On pull requests everything works fine, only the node.js script is run and build ends as expected.

Two weeks ago the script was working fine, this week it started misbehaving on master. The script runs, it pushes to gh-pages, but the build never ends and fails for lack of input after 10 minutes.
Working build: https://travis-ci.org/mozilla-l10n/localizer-documentation/builds/250825923
Failed build: https://travis-ci.org/mozilla-l10n/localizer-documentation/builds/254448754

I've compared the two logs, and the only significative difference is node 8.1.3 vs 8.1.4. The other thing is that the working build didn't have a `The command "bash ./scripts/deploy.sh" exited with 0.` at the end.

I've even tried to add output to the script, or explicitly `exit 0` at the end, with no luck.

**Comment by musikele** [comment] 2017-07-18 11:08
This affects me too. Don't know if I add informations, but I compile my jekyll blog via a shell script that is executed by travis.

**Comment by BanzaiMan** [comment] 2017-07-18 12:09
Duplicate of https://github.com/travis-ci/travis-ci/issues/8082#issuecomment-315147561.

**Closed by BanzaiMan** 2017-07-18 12:09 UTC

**Comment by flodolo** [comment] 2017-07-18 12:12
Argh, I swear I searched for a while before opening this.
