### ISSUE TITLE
Make deployment not run unless the buid passess

### ISSUE THREAD

**Issue by Aaron1011** [travis-ci/travis-ci#1548] opened 2013-10-26 01:51 UTC
Currently, there are two options for deploying: the default, which runs the deploy for every job, and, adding an `on` option to specify which job the deploy should be run on. However, when using the `on` option, the deploy will run as soon as the job is complete. It would be nice if a user could specify that the deploy should only run if the build passes. The job running the deployment could just wait until the build has finished to run the deployment.

**Comment by mbrodala** [comment] 2016-03-18 09:28
Notice that this is basically the same issue as #929 which at least has a workaround in [travis-after-all](https://github.com/dmakhno/travis_after_all).

**Comment by BanzaiMan** [comment] 2017-01-15 05:42
Closing as a duplicate of #929.

**Closed by BanzaiMan** 2017-01-15 05:42 UTC
Labels: deployment, travis-build
