### ISSUE TITLE
SonarQube no C# results

### ISSUE THREAD

**Issue by 304NotModified** [travis-ci/travis-ci#7388] opened 2017-02-26 14:29 UTC
First of all, I don't know if this is a Travis or a SonarQube issue. Any help is highly appreciated .

I got SonarQube running on my C# project! It's only working on master (see #6977 ), but that's fine to me for now.

But the funny thing, SonarQube is fully ignoring my c# files. The only files that we're analyses where XML files (and I added them to the ignore list)

In the build log I see : `INFO: Download sonar-csharp-plugin-5.7.0.612.jar`

- [build log Travis](https://travis-ci.org/NLog/NLog/builds/203972489)
- [sonar results](https://sonarqube.com/dashboard/index?id=nlog)

In travis it shows all (empty) lines:

![image](https://cloud.githubusercontent.com/assets/5808377/23340501/8b7cdd08-fc37-11e6-8dff-6dd99e10678c.png)

The only issues it found where on XML files (indenting): https://sonarqube.com/component_issues/index?id=nlog#resolutions=FIXED

Zero issues on C#, I can hardly believe that's as I [checking the rules](https://sonarqube.com/coding_rules#languages=cs), there a some we don't honor (with good reason)

Any idea what's going on? 

- I double-checked the filter rules

**Comment by BanzaiMan** [comment] 2017-03-02 13:56
@dbmeneses @bellingard Could you help us on this issue?

**Comment by bellingard** [comment] 2017-03-02 14:26
@304NotModified It's not a TravisCI issue, the problem is linked to the way you try to run a SonarQube analysis (basically, you're trying to analyze a .NET solution on a Linux environment where MSBuild is not available, and we support only MSBuild for this kind of project - not xbuild). 

Please close this issue and come on https://groups.google.com/forum/#!forum/sonarqube where we'll be happy to guide you on the best way to solve your problem.

Thanks!

**Comment by BanzaiMan** [comment] 2017-03-02 15:31
@bellingard Thank you!

**Closed by BanzaiMan** 2017-03-02 15:31 UTC
Labels: addons:sonarqube

**Comment by 304NotModified** [comment] 2017-03-02 19:24
Thanks!
