### ISSUE TITLE
Feature request - Multiple notifications of the same type (Slack)

### ISSUE THREAD

**Issue by vojbarzz** [travis-ci/travis-ci#9165] opened 2018-01-31 18:34 UTC
It would be great to have multiple notifications of the same type. I need to notify a slack channel about a status of each build and also another slack channel about releases. Both needs to have different template.

**Comment by BanzaiMan** [comment] 2018-01-31 18:44
Duplicate of #4106.

**Closed by BanzaiMan** 2018-01-31 18:44 UTC
