### ISSUE TITLE
Upgrade SSL and Curl in containers

### ISSUE THREAD

**Issue by icco** [travis-ci/travis-ci#7180] opened 2017-01-18 21:50 UTC
When `sudo: true` is enabled, 
```
curl -svLO https://releases.hashicorp.com/packer/0.12.1/packer_0.12.1_linux_amd64.zip
``` 
works great.

When `sudo: false`, the build fails because Hashicorp requires TLS 1.2, which travis containers don't seem to support.

 - Failing build: https://travis-ci.org/icco/onesie/builds/193196303 
 - Working build: https://travis-ci.org/icco/onesie/builds/193193398

Comment from Hashicorp: https://twitter.com/armon/status/821540153848041472

Please help! I'd assume this just requires upgrading libssl and curl in the container.

**Comment by BanzaiMan** [comment] 2017-01-18 21:53
Thanks for taking the time to open this issue. I'm closing this as a duplicate of #4757.

(A short of the current suggested workaround is to use Trusty.)

**Closed by BanzaiMan** 2017-01-18 21:53 UTC
