### ISSUE TITLE
Node builds failing - Cannot install Node version via NVM

### ISSUE THREAD

**Issue by oshalygin** [travis-ci/travis-ci#7571] opened 2017-04-04 22:48 UTC
Looks like an issue with nvm than Travis-CI itself, but Travis-CI uses NVM under the hood to install the NodeJs version requested in the configuration.  

Not sure what the Travis team can do.  Maybe cached tarballs that you can point to?

Currently everything NodeJs seems down.

![image](https://cloud.githubusercontent.com/assets/7675942/24682366/2e32ce12-194e-11e7-9858-d0606b6dde81.png)

**Comment by BerkeleyTrue** [comment] 2017-04-04 22:52
Experiencing this with at least three of my repo's installing either node 4 or 6
https://travis-ci.org/freeCodeCamp/react-vimeo/builds/185675052
https://travis-ci.org/freeCodeCamp/freeCodeCamp/builds/218659381
https://travis-ci.org/BerkeleyTrue/react-redux-subdivide/builds/218660094

**Comment by citycide** [comment] 2017-04-04 22:53
Related: https://github.com/creationix/nvm/issues/1435

So it's not the first time. Looks like it was temporary in that issue ^

**Comment by edmorley** [comment] 2017-04-04 23:07
Whilst nvm should definitely exit non-zero to make the failures more obvious (travis-ci/travis-ci#7001 -> creationix/nvm#1347) - the root cause here is actually nodejs.org is experiencing issues again (nodejs/nodejs.org#1191).

**Comment by hitz** [comment] 2017-04-04 23:11
me too: https://travis-ci.org/ENCODE-DCC/encoded/jobs/218658055

**Comment by ptgamr** [comment] 2017-04-05 00:07
Me too, on my local machine:

```
`Downloading and installing node v7.7.0...
Downloading https://nodejs.org/dist/v7.7.0/node-v7.7.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Provided checksum to compare to is empty.
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Binary download failed, trying source.
Detected that you have 4 CPU core(s)
Running with 3 threads to speed up the build
Downloading https://nodejs.org/dist/v7.7.0/node-v7.7.0.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Provided checksum to compare to is empty.
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
nvm: install v7.7.0 failed!

```

**Comment by BanzaiMan** [comment] 2017-04-05 00:10
Thanks, everyone, for the report. I think the issue is well understood; we are just waiting for npmjs.org to come back up, at which point restarting the affected builds should resolve the issue.

We can hold off on me-toos at this time. :-)

**Comment by BanzaiMan** [comment] 2017-04-05 00:36
There are some reports of Node downloads working now. Could anyone confirm?

**Comment by jupl** [comment] 2017-04-05 00:38
Looks like it is now.

**Comment by citycide** [comment] 2017-04-05 00:39
@BanzaiMan working for all my previously affected repos.

**Comment by richRemer** [comment] 2017-04-05 00:39
Confirmed.  Was not working before, but is now.

**Comment by BanzaiMan** [comment] 2017-04-05 00:40
Sweet! I am closing this now. Let us know if the problem resurfaces.

Again, thanks for the report!

**Closed by BanzaiMan** 2017-04-05 00:40 UTC
