### ISSUE TITLE
Android build constantly gets killed with code 137

### ISSUE THREAD

**Issue by aaronjwood** [travis-ci/travis-ci#5782] opened 2016-03-12 15:50 UTC
If you look here you'll see that the majority of my builds are getting killed and exiting with code 137 https://travis-ci.org/aaronjwood/PortAuthority/builds. What's strange is that build 27 passed while the rest have continued to fail.

This is a new thing for me as my builds have been passing until the other day. I found some other tickets mentioning that 137 usually means the OOM killer is killing the build due to memory constraints. It looks like it's getting killed when it gets to the step of proguard doing various things. Is there anything I can do about this on my end with my project?

Here's my `.travis.yml` file, it's pretty simple https://github.com/aaronjwood/PortAuthority/blob/development/.travis.yml

**Comment by BanzaiMan** [comment] 2016-03-12 20:43
Could this be a duplicate of #5582?

**Comment by aaronjwood** [comment] 2016-03-13 02:48
Yes, that looks really similar. Also #3416 looks related but it sounds like he wasn't using the container infrastructure.

**Comment by BanzaiMan** [comment] 2016-03-13 06:17
Yes, please.

**Closed by BanzaiMan** 2016-03-13 06:17 UTC
