### ISSUE TITLE
@nex3 @a14n   

### ISSUE THREAD

**Issue by Andrious** [travis-ci/travis-ci#10280] opened 2018-10-22 01:05 UTC
Hello you two!
Good of you to help out, being that Dart for Travis-CI is not officially supported.

Please, it's been a long day, and admittedly I'm just too tired to do a little 'research' and figure out
how to make this Travis thingy work. :)

Currently, this is all my .travis.yml file consists of:
  language: dart

I suspect I have to indicate further somehow that I simply want it to run whatever is in the test directory as, right now, I get this error:
https://travis-ci.org/AndriousSolutions/mvc_pattern/jobs/444517539

I did make some of an effort and looked at a past issue: 
https://github.com/travis-ci/travis-ci/issues/9678

Wow! What is all that in his .travis.yml file?!

**Comment by BanzaiMan** [comment] 2018-10-22 11:30
Duplicate of #10279

**Closed** 2018-10-22 11:30 UTC
