### ISSUE TITLE
Secure environment variables should be available when building a PR from a fork owned by someone with write access on the target repo

### ISSUE THREAD

**Issue by pelotom** [travis-ci/travis-ci#8424] opened 2017-09-14 08:34 UTC
I'm part of an org on GitHub that hosts private repo X. I fork X to my own account, where I do feature work. But when I submit a PR from my fork to the main repo, Travis fails to build it:

```
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
```

I assume this is due to [this](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions). But it seems like that rule shouldn't apply here, because I am a contributor with write access to the main repo. I could equally well create this branch within the main repo, I'm just not doing so because I want to keep my work private until its presentable, and avoid cluttering up the main repo's branch list.

**Comment by BanzaiMan** [comment] 2017-09-14 12:32
Closing as a duplicate of #1946.

**Closed by BanzaiMan** 2017-09-14 12:32 UTC

**Comment by tvald** [comment] 2017-09-14 17:36
A better duplicate for this might be #6611:

>I propose that this restriction be relaxed for forks of private repositories within an organization. A further possible restriction would be to limit use of secured environment variables to those PR submitters who have write access on the upstream repository.
