### ISSUE TITLE
PostgreSQL 9.5

### ISSUE THREAD

**Issue by vitaly-t** [travis-ci/travis-ci#5491] opened 2016-01-21 10:54 UTC
PostgreSQL 9.5 was officially released on January 7, 2016.

As of now it is still not supported by default. Here's my script:
```
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database pg_promise_test;' -U postgres
```
When I have it with "9.4", it works, but with "9.5" it says:
```
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
The command "psql -c 'create database pg_promise_test;' -U postgres" failed and exited with 2 during .
```

Is 9.5 still not supported by Travis? If so, when should we expect it?

**Comment by BanzaiMan** [comment] 2016-01-21 12:34
Duplicate of #4264.

**Closed by BanzaiMan** 2016-01-21 12:34 UTC

**Comment by vitaly-t** [comment] 2016-01-21 12:40
@BanzaiMan that was about using an Alfa version of 9.5, which required additional steps. There is no reason in requiring additional steps for a released version of PostgreSQL.

Hence the question - when will it be supported by default, the same as 9.4 and previous versions?

**Comment by NegativeMjark** [comment] 2017-03-01 10:48
It looks like you need to set:

```yml
dist: trusty
```

Otherwise it silently fails to setup the postgres.
