### ISSUE TITLE
Moving .travis.yml server side / Building without a .travis.yml file

### ISSUE THREAD

**Issue by ocornut** [travis-ci/travis-ci#4773] opened 2015-09-10 20:26 UTC
Apologies if this issue is a duplicate, I found it hard to search through existing issues with those keywords.

Basically I would really like to be able to move the .travis.yml file out of my repository and out of sight of the average user. Either in a different location or on the Travis website. I don't think it is possible with the current Travis website but I was wondering if this was planned.

This blog post mention having more settings available from the website, so maybe allowing full travis.yml hosted there would be a logical extension to that?
http://blog.travis-ci.com/2014-03-05-repository-settings/

Thanks!
Regards,
Omar

(
Also somehow related
https://github.com/travis-ci/travis-ci/issues/1000
)

**Comment by BanzaiMan** [comment] 2015-09-10 21:55
Thanks for opening the issue. Indeed, this is a duplicate of #3540.

I am sorry, but, at this time, we do not have plans to implement this.

**Closed by BanzaiMan** 2015-09-10 21:55 UTC

**Comment by ocornut** [comment] 2015-09-10 22:00
Thanks for you answer!
I think it is a different feature than #3540, moving the main/unique ,travis.yml server side I'd hazard would have much less UI/build implications that the "support multiple .yml" solution suggested in that other ticket. Anyway I don't want to push that too far, just wanted to plant the idea.
Thanks again for your work on this project.

**Comment by BanzaiMan** [comment] 2015-09-10 23:30
#3829 is also similar.
