### ISSUE TITLE
Dynamic Matrix Generation

### ISSUE THREAD

**Issue by nbrady-techempower** [travis-ci/travis-ci#7033] opened 2016-12-14 19:34 UTC
We have over 180 matrix combinations that need to complete on a full run. Currently we're running a diff and we know which matrix combinations might be affected. However, since we can't generate the matrix dynamically, we have to boot up an instance, find out we don't need this particular test, then exit. If we only need to test 1 item out of 180, we're spending a lot of time and resources  we don't need to. A way to generate the matrix (some sort of before-matrix hook - just spit-balling) would be amazing.

**Comment by BanzaiMan** [comment] 2016-12-15 16:24
This is a duplicate of #2568.

**Closed** 2016-12-23 01:08 UTC
