### ISSUE TITLE
Buildmatrix from gcc x clang x gfortran in different versions

### ISSUE THREAD

**Issue by matyro** [travis-ci/travis-ci#8564] opened 2017-10-10 13:12 UTC
Hi,
I am looking for an automatic way to describe a buildmatrix with different versions of gcc, clang and gfortran in a single project.

Currently i want to test following versions combined in any possible way:
gcc-4.6, gcc-4.9, gcc-5, gcc-6
gfortran-4.6, gfortran-4.9, gfortran-5, gfortran-6
clang-3.6, clang-3.7, clang-3.8, clang-3.9

I could write all cases by hand but for 4x4x4 or with newer versions even more its quite some task.
Is there some way to describe all 3 vectors and automatically build the matrix?

Sincerely
Dominik B.

**Comment by BanzaiMan** [comment] 2017-10-13 18:29
Closing as a duplicate of #5959.

**Closed by BanzaiMan** 2017-10-13 18:29 UTC
