### ISSUE TITLE
[Trusty] Asks for confirmation when running apt-get install

### ISSUE THREAD

**Issue by decriptor** [travis-ci/travis-ci#5339] opened 2015-12-19 16:27 UTC
running
    sudo apt-get install automake libtool intltool
results:
    After this operation, 5,655 kB of additional disk space will be used.
    Do you want to continue? [Y/n]

This means that the build waits 10 minutes and then times out.

**Comment by BanzaiMan** [comment] 2015-12-19 17:33
This is a duplicate of #4996.

**Closed by BanzaiMan** 2015-12-19 17:33 UTC
