### ISSUE TITLE
Writing colored text to the console is broken on Travis

### ISSUE THREAD

**Issue by rsimha** [travis-ci/travis-ci#10112] opened 2018-09-12 22:24 UTC
See https://travis-ci.org/ampproject/amphtml/jobs/427870439 for example

Whenever colored text is printed to the console, the preceding space is overwritten

![screenshot from 2018-09-12 18-24-14](https://user-images.githubusercontent.com/26553114/45456507-11e18f00-b6b9-11e8-873f-45cafd1c2739.png)

**Comment by clekstro** [comment] 2018-10-05 10:50
@rsimha I tried to reproduce but it looks like this has been fixed in the interim. I've submitted https://github.com/travis-ci/travis-web/pull/1829 to ensure we don't break this in the future.

Going to close for now but feel free to re-open if you feel this hasn't been addressed.

**Closed by clekstro** 2018-10-05 10:50 UTC
Labels: travis-web

**Comment by ron190** [comment] 2019-12-23 22:40
It seems broken again since the 16th of December.
- https://travis-ci.org/ron190/jsql-injection/builds/625411869 =>  :large_blue_circle:
- https://travis-ci.org/ron190/jsql-injection/builds/625841438 =>  :white_circle:
