### ISSUE TITLE
PHP 7.0 environment installation fails

### ISSUE THREAD

**Issue by flaupretre** [travis-ci/travis-ci#5136] opened 2015-11-19 14:52 UTC
See https://travis-ci.org/flaupretre/pecl-pcs/builds/92040102

When installing the PHP 7.0 environment : 

     $ phpenv global 7.0 2>/dev/null
     7.0 is not pre-installed; installing
     tar: 7.0snapshot: Cannot mkdir: Permission denied
     tar: 7.0snapshot/share: Cannot mkdir: No such file or directory
     ...
     <error messages>
    $ phpenv global 7.0
    rbenv: version `7.0' not installed
   
    The command "phpenv global 7.0" failed and exited with 1 during .
    
    Your build has been stopped.

Seems it was working yesterday.

**Comment by BanzaiMan** [comment] 2015-11-19 14:57
Thanks for the report. This is a duplicate of #5111

**Closed by BanzaiMan** 2015-11-19 14:57 UTC
