### ISSUE TITLE
Link from build to issue in commit message is generated wrongly

### ISSUE THREAD

**Issue by ankon** [travis-ci/travis-ci#7463] opened 2017-03-14 11:35 UTC
Assume a build is triggered with a commit message such as `Closes #9`. Travis' UI converts the `#9` to a link, but renders the organization wrongly, and we end up with 
https://github.com/[object%20Object]/project/issues/9.

You can see one instance at https://travis-ci.org/Collaborne/collaborne-frontend-proxy/builds/210895212

**Comment by BanzaiMan** [comment] 2017-03-14 13:24
Duplicate of #7415.

**Closed by BanzaiMan** 2017-03-14 13:24 UTC
Labels: bug, travis-web
