### ISSUE TITLE
Please also give the ability of cancel a build to contributor

### ISSUE THREAD

**Issue by PeterDaveHello** [travis-ci/travis-ci#6894] opened 2016-11-17 20:14 UTC
Some projects, like nvm - https://travis-ci.org/creationix/nvm/pull_requests
Each round of the test will need so many matrixes which will block the other builds, if I do some updates before the build finished, the new one will be blocked/hanged by the old one, and only the maintainers have the permission to cancel the old and useless builds, which is efficient and resource wasting, please consider to give contributors to close their own tests on their own PRs, thanks a lot.

BTW, CircleCI supports automatically stop the old ones if new ones come, it could also be a great feature if you would like to have it 😄

**Comment by BanzaiMan** [comment] 2016-11-17 22:24
I think this is a duplicate of #4867. I'm closing as such, but if you think otherwise, do let us know.

**Closed by BanzaiMan** 2016-11-17 22:24 UTC

**Comment by PeterDaveHello** [comment] 2016-11-18 06:04
Same thing, sorry that I didn't note that.
