### ISSUE TITLE
Create custom test machines and SSH into them

### ISSUE THREAD

**Issue by HaraldNordgren** [travis-ci/travis-ci#7095] opened 2016-12-31 18:34 UTC
I want to specify certain parameters and spin up machines through the Travis CLI, then start an SSH connection to be able to debug different commands.

Something like

    travis ssh --os osx --osx_image xcode8.2 --env SOME_PARAMETER=Some_value

These machines could be subject the the same limitations as regular build jobs. So 50 minutes max time.

**Comment by BanzaiMan** [comment] 2016-12-31 21:52
Closing as a duplicate of #761.

We are working on this feature; if you want one now, do send email to support@travis-ci.com.

**Closed by BanzaiMan** 2016-12-31 21:52 UTC
