### ISSUE TITLE
Headless Chrome not working correctly

### ISSUE THREAD

**Issue by SudharakaP** [travis-ci/travis-ci#9723] opened 2018-06-08 15:12 UTC
Hi everyone, 

I am trying to build an Angular project on Tavis and run its unit tests. I am using Karma and trying to use the Chrome headless mode to run the unit tests. I've tried a lot of times and it seems although everything works perfectly fine locally, Travis seems to be unable to start the browser. Here's the link to the repository; https://github.com/SudharakaP/Service-Link-Angular and here's the link to the build that is unsuccessful; https://travis-ci.org/SudharakaP/Service-Link-Angular/builds/389766913

Any help or pointers on this matter is greatly appreciated. I've tried disabling the sandbox mode in chrome (which is already done in the build that is linked). Here's my .travis.yml and karma.config.js files.

```
language: node_js
node_js:
  - "8.9.0"
install:
  - npm install
script:
  - npm test
```

```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html
process.env.CHROME_BIN = require('puppeteer').executablePath();

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadlessNoSandbox', 'Chrome'],
    singleRun: false,
    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }
    }
  });
};
```

Thank you.

**Comment by SudharakaP** [comment] 2018-06-09 20:27
Just for the information, I managed to get it working without any issues on TravisCI with OSX. 

https://travis-ci.org/SudharakaP/Service-Link-Angular/builds/390207187

So I believe this is something specific to the Travis Linux distro.

**Comment by joepvd** [comment] 2018-06-19 17:56
Duplicate of https://github.com/travis-ci/travis-ci/issues/8836

Could you try again with `sudo: required` in your `.travis.yml`?

**Closed by joepvd** 2018-06-19 17:56 UTC

**Comment by SudharakaP** [comment] 2018-06-19 18:18
@joepvd : Thanks for the reply. I have tried with sudo: required as well and it didn't work. If you want me to do a build with sudo: required to verify let me know and I'll do it for you :)

I have contacted Travis support through email and they've requested for three builds with OSX and three builds with Linux which I sent them last week. Will update this thread when I hear back.
