### ISSUE TITLE
Build list doesn't render correctly with large number of digits in build numbers

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#8595] opened 2017-10-17 00:48 UTC
https://travis-ci.org/pyca/cryptography/builds/288831511:

Note the last three builds

![screen shot 2017-10-16 at 8 48 20 pm](https://user-images.githubusercontent.com/772/31641540-5df0d3b6-b2b3-11e7-907b-5a55c8c9b98a.png)

**Comment by BanzaiMan** [comment] 2017-10-17 12:55
A duplicate of #8587.

**Closed by BanzaiMan** 2017-10-17 12:55 UTC
