### ISSUE TITLE
Update on GHC 7.10?

### ISSUE THREAD

**Issue by nh2** [travis-ci/travis-ci#4667] opened 2015-08-19 01:12 UTC
Hi,

I'd like to check the status on https://github.com/travis-ci/travis-ci/issues/3785, which is unfortunately locked since May.

@BanzaiMan mentioned there that GHC 7.10 would be in the 2015-06 update, but now it's almost 3 months later. Did the update somehow not work, is there something we can contribute to help? Many Haskellers would appreciate 7.10 support.

Thanks!

**Comment by shockkolate** [comment] 2015-08-20 16:19
I too have been wondering the same thing, as my current project uses functionality only added in base 4.8.0.0 which isn't supported in GHC 7.8; only in GHC 7.10.

**Comment by BanzaiMan** [comment] 2015-08-25 02:19
Sorry for the delay in build environment updates, which is caused by recent changes to our infrastructure.

ghc-7.10.2 is now whitelisted for containers. You can use:

```yaml
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
```

on containers. You should be able to use the APT addon on legacy infrastructure as well (you could also use `sudo` to install package as well).

Please use this until the build environments are updated.

I'm closing this for now.

**Closed by BanzaiMan** 2015-08-25 02:19 UTC
