### ISSUE TITLE
gvm is not installed on osx

### ISSUE THREAD

**Issue by themihai** [travis-ci/travis-ci#3100] opened 2015-01-11 03:57 UTC
It seems the osx vm is misconfigured 
```
language: go
go:
- 1.3
os:
  - linux
  - osx
before_script: 
```

```

gvm get
/Users/travis/build.sh: line 41: gvm: command not found
The command "gvm get" failed and exited with 127 during .
Your build has been stopped.
```

**Comment by BanzaiMan** [comment] 2015-01-11 04:05
Duplicate of #2318.

**Closed by BanzaiMan** 2015-01-11 04:05 UTC
