### ISSUE TITLE
Duplicate jobs for PRs originating from the same repo

### ISSUE THREAD

**Issue by DirectXMan12** [travis-ci/travis-ci#3276] opened 2015-02-24 20:21 UTC
I noticed that Travis seems to be running two jobs for pull requests originating from the same repository, the job on the branch, and the job on the pull request.  Since these jobs are effectively the same, it doesn't make sense to have both.

Previously, it seemed that Travis would detect this and only use the branch's job, but within the last couple of days, I've notice the duplication.

**Comment by joshk** [comment] 2015-02-24 20:24
Hi @DirectXMan12 

Thanks for creating the issue.

The two builds are technically different, one is testing the branch commit, and the other is testing the PR merge commit. 

We have actually always worked this way for PRs created from the same repo, it is just that we haven't had the means to add the commit status to GitHub until now.

If you don't want to test the branch but only test the PR, you can do this by whitelisting branches you do want to test (eg. master) and we will also test the PRs for them.

I'm going to close this issue for now as it is intended behaviour.

Have an awesome day!

**Closed by joshk** 2015-02-24 20:24 UTC

**Comment by marutosi** [comment] 2015-02-26 18:05
> Previously, it seemed that Travis would detect this and only use the branch's job, but within the last couple of days, I've notice the duplication.

I think too as I commented on https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-76228566 .

**Comment by BanzaiMan** [comment] 2015-02-26 19:10
Travis has run two builds for each push to a branch for which there is an open PR. We used to report these results with the same ID, which caused the illusion that there is only one build. Now we report them with different IDs, and they appear twice.

**Comment by schneems** [comment] 2017-03-30 19:21
Are there any best practices for distinguishing a PR build from a "push"? The ruby buildpack code only works when run against the current branch you're building against, so the merge commit tests always fail. If we could error out or `exit 0` early by looking at `TRAVIS_*` env vars that would save us a bunch of un-needed API requests.
