### ISSUE TITLE
Singleline comments in if statements

### ISSUE THREAD

**Issue by vgvassilev** [travis-ci/travis-ci#3990] opened 2015-05-30 20:19 UTC
There seems to be a parsing bug with this configuration:
```
language: cpp

compiler:
- gcc
- clang

os:
- linux
- osx

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    # GCC
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  fi
```

**Comment by BanzaiMan** [comment] 2015-05-30 22:40
`before_install` is collapsed into single line before compiling it into a Bash script. Remove the comment, and it should work.

**Comment by vgvassilev** [comment] 2015-05-31 09:22
No, the problem is that it cannot parse it and cannot run the build. The yml file is unparsable yielding funny syntax error.

**Comment by BanzaiMan** [comment] 2015-05-31 11:49
Could you point to the failing build log URL?

**Comment by vgvassilev** [comment] 2015-05-31 16:38
https://travis-ci.org/vgvassilev/cling/requests
```
about 23 hours ago #68 9275cdf Add the current branch to build branches. - Build created successfully 
```
(not very descriptive, but the build wouldn't start at all because of the bogus yml.

If you copy-paste the reproducer in the yml validator you will see what I am talking about.

**Comment by BanzaiMan** [comment] 2015-06-01 12:33
My initial assessment was wrong. I now believe that the comment terminates the array, and the rest is left bare to the YAML parser, and the file ends up being invalid.

**Comment by vgvassilev** [comment] 2015-06-01 12:45
Now that makes more sense.

**Comment by BanzaiMan** [comment] 2015-07-07 03:53
Is there something left to do?

**Comment by vgvassilev** [comment] 2015-07-08 05:41
Is it fixed?

**Comment by roidrage** [comment] 2015-07-08 06:40
YAML treats the single line comment as it it would separate the lines, expecting two separate items of a scalar, but the line below the comment is not a scalar item (preceded by a `-`) so parsing fails. I was able to reproduce this parsing error with the Ruby parser.

It seems like there's little we can fix about this, as this is due to the YAML parsing (# is a valid YAML escape for comments). The easiest fix would be remove the comment or to move it above the list item:

```yaml
before_install:
# GCC
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  fi
```

As this is an issue beyond our control and there is a simple fix, I'm closing this issue.

**Closed by roidrage** 2015-07-08 06:40 UTC
Labels: awaiting-followup
