### ISSUE TITLE
Python appears to have static library, want dynamic library

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#5533] opened 2016-01-29 14:57 UTC
By default Python builds with a static library. I have yet to see a case where this helps, but I have seen many cases where it causes problems. In particular, if you are C/C++ code that links against the library, it really needs to be dynamic. Here is an example build where this Python static library is getting picked up and causing problems ( https://travis-ci.org/ukoethe/vigra/jobs/105681112#L373 ).

To change this Python can be rebuilt with this flag `--enable-shared`. Alternatively, an environment variable can be set with this and other options right before the build ( `PYTHON_CONFIGURE_OPTS='--enable-shared'` ).

**Comment by jakirkham** [comment] 2016-02-23 20:55
Any thoughts on this? It would be nice to be able to test using Python 3.4 on Linux.

**Comment by jakirkham** [comment] 2016-08-19 04:57
Any chance we can get this Python rebuilt/fixed?

**Comment by BanzaiMan** [comment] 2016-08-19 13:17
@jakirkham Sorry for the delay. I have confirmed the issue.

**Comment by BanzaiMan** [comment] 2016-08-19 13:18
I'll be working on this soon.

**Comment by BanzaiMan** [comment] 2016-08-19 13:46
Is your code compatible with the latest development branch of Python? If so, could you test with:

```yaml
language: python
python:
  - '3.6-dev'
```

Thanks.

**Comment by jakirkham** [comment] 2016-08-19 13:52
It is compatible with Python 3.5. Not sure about 3.6.

In any event, we need to use Boost and the package from Trusty is built with Python 3.4. So the interpreter we build against needs to also be Python 3.4.

**Comment by BanzaiMan** [comment] 2016-08-19 19:34
I've rebuilt a few:

(Search for `-fIPC`)
`3.4.5`: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/153653772#L139
`3.5` and `3.5.2`: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/153655569#L139
`3.6-dev`: https://travis-ci.org/BanzaiMan/travis_production_test/jobs/153653771#L139

**Comment by BanzaiMan** [comment] 2016-08-19 19:43
3.3.x appears to work right now, too. (https://travis-ci.org/BanzaiMan/travis_production_test/builds/153658270; https://travis-ci.org/BanzaiMan/travis_production_test/builds/153657794)

Is this still a problem? If so, could you point to a build log that doesn't have the flag `-fPIC` set? Thanks

**Comment by BanzaiMan** [comment] 2016-08-19 19:58
All the pre-installed Python runtimes have `-fPIC` in the config options in all infrastructures. https://travis-ci.org/BanzaiMan/travis_production_test/builds/153661651

**Comment by msmolens** [comment] 2016-08-19 20:01
@BanzaiMan I re-ran this job that uses `3.3` and it still shows the `recompile with -fPIC` error: https://travis-ci.org/scikit-build/scikit-build/jobs/153564022. Any ideas?

**Comment by BanzaiMan** [comment] 2016-08-19 20:10
@msmolens It is certainly possible that `python -c 'import sysconfig; print(sysconfig.get_config_vars())'` is lying to me.

I've re-packaged 3.3.5. Could you try that? (3.3.6 won't work, because it is pre-installed.)

**Comment by jakirkham** [comment] 2016-08-19 20:14
Hmm...still running into this issue. See [build]( https://travis-ci.org/ukoethe/vigra/jobs/153662546#L884 ).

**Comment by BanzaiMan** [comment] 2016-08-19 20:17
@jakirkham Thanks for testing. Could you try `3.4.5`, please?

**Comment by msmolens** [comment] 2016-08-19 20:20
@BanzaiMan I can confirm that specifying `3.3.5` in place of `3.3` results in a successful build: https://travis-ci.org/scikit-build/scikit-build/jobs/153666527

**Comment by BanzaiMan** [comment] 2016-08-19 20:21
@msmolens Awesome. I've also rebuilt 3.3.6, so that will be used in the next image update.

**Comment by BanzaiMan** [comment] 2017-06-08 04:51
I think we can close this now. Let us know if you continue to see problems.

**Closed by BanzaiMan** 2017-06-08 04:51 UTC
Labels: python

**Comment by jakirkham** [comment] 2017-06-08 05:56
Indeed. Does appear to be fixed. Thanks.
