### ISSUE TITLE
Automatically close PR builds if the PR was merged/closed

### ISSUE THREAD

**Issue by isuruf** [travis-ci/travis-ci#9151] opened 2018-01-26 19:48 UTC
If the PR is merged/closed before the PR build ends (Usually for PRs with trivial changes), the PR builds are not closed.

**Comment by BanzaiMan** [comment] 2018-01-26 19:49
Duplicate of #9143.

**Comment by isuruf** [comment] 2018-01-26 19:50
Sorry about the duplicate issue

**Closed by BanzaiMan** 2018-01-26 19:49 UTC
