### ISSUE TITLE
Build fails and does not stop upon amend commit

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#6808] opened 2016-11-01 16:45 UTC
Job 112 at LolexOrg/Lolex-Tools. It has created a new build for my amend but has not stopped the old job even thought the builds are getting fatal error due to "reference is not a tree".

**Comment by BanzaiMan** [comment] 2016-11-01 17:08
https://travis-ci.org/LolexOrg/Lolex-Tools/builds/172343201 Looks like you've merged the PR before certain jobs got to run the PR build. There is no more PR commit to test, so the jobs fail.

It is working as designed. If this happens again, you should just cancel the older build.

**Closed by BanzaiMan** 2016-11-01 17:08 UTC

**Comment by Monkeyboy2805** [comment] 2016-11-03 16:50
@BanzaiMan I was just wondering, to make the provess nore efficient, in case you don't notice it?

**Comment by BanzaiMan** [comment] 2016-11-03 16:54
@Monkeyboy2805 I'm sorry, but I don't understand what you just wrote.
