### ISSUE TITLE
Cache most popular docker images

### ISSUE THREAD

**Issue by Hainish** [travis-ci/travis-ci#6102] opened 2016-05-24 20:19 UTC
It would be great to have caching on various popular images, which is not currently in place:

```shell
$ docker images

REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZEThe 


command "docker images" exited with 0.
```

This will cut down on test time and bandwidth for travis.

**Comment by BanzaiMan** [comment] 2016-05-24 21:00
Closing as a duplicate of #5358.

**Closed by BanzaiMan** 2016-05-24 21:00 UTC
