### ISSUE TITLE
addons hosts failing with `Device or resource busy`

### ISSUE THREAD

**Issue by fommil** [travis-ci/travis-ci#3350] opened 2015-03-08 18:10 UTC
I think my tests are failing because the hostname of the build machine is too complex, so I was pleased to see that custom hostnames can be set http://docs.travis-ci.com/user/hosts/

However when I tried this with 

```
addons:
  hosts:
    - freeslick
```

in my build https://travis-ci.org/fommil/freeslick/builds/53559992

I seen this

```
sed: cannot rename /etc/hosts: Device or resource busy
```

and then tried my own code to see if it had been set:

```
echo $HOSTNAME
testing-worker-linux-docker-bd80cc92-3210-linux-3
```

So it looks like this functionality is broken right now.

**Comment by BanzaiMan** [comment] 2015-03-08 18:23
Duplicate of #2969, the fix of which is planned to be rolled out tomorrow.

**Closed by BanzaiMan** 2015-03-08 18:23 UTC
