### ISSUE TITLE
Central Maven returns 403 on "sudo: false" instances

### ISSUE THREAD

**Issue by sormuras** [travis-ci/travis-ci#10055] opened 2018-08-30 03:04 UTC
### `sudo: false`
- fails http://central.maven.org https://travis-ci.org/sormuras/bach/jobs/422335820#L543
- fails https://repo.maven.apache.org https://travis-ci.org/sormuras/bach/jobs/422360824#L543

### `sudo: true`
- works http://central.maven.org https://travis-ci.org/sormuras/bach/jobs/422365071#L561
- works https://repo.maven.apache.org https://travis-ci.org/sormuras/bach/jobs/422362260#L561

**Comment by jodastephen** [comment] 2018-08-30 09:46
Similar example: https://travis-ci.org/JodaOrg/joda-time/jobs/422349542

```
Plugin org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1 or one of its 
dependencies could not be resolved: Failed to read artifact descriptor for 
org.apache.maven.plugins:maven-enforcer-plugin:jar:3.0.0-M1: Could not transfer 
artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:3.0.0-M1 from/to 
central (https://repo.maven.apache.org/maven2): Access denied to: 
https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.pom , 
ReasonPhrase:Forbidden.
```

**Comment by DrTorte** [comment] 2018-08-30 18:31
Hey there,

Is anyone here still experiencing this issue as of the last few hours? I believe it has been resolved, but if not, please let us know and we'll get right on it. Thanks!

**Comment by sormuras** [comment] 2018-08-30 18:33
Failed 2 minutes ago: https://travis-ci.org/junit-team/junit5-samples/jobs/422540034#L456

**Comment by sormuras** [comment] 2018-08-30 18:43
Now, after another restart, it worked out: https://travis-ci.org/junit-team/junit5-samples/jobs/422540034

**Comment by jodastephen** [comment] 2018-08-30 18:47
Still broken https://travis-ci.org/JodaOrg/joda-time/jobs/422473104

**Comment by jodastephen** [comment] 2018-08-30 18:49
But an extra restart fixed it

**Comment by sormuras** [comment] 2018-08-30 19:08
...fails now-and-then, again. Restarting sometimes helps, sometimes not: https://travis-ci.org/junit-team/junit5-samples/jobs/422717366#L486

**Comment by DrTorte** [comment] 2018-08-30 21:40
Thanks everyone - I'll keep you all posted with updates!

**Comment by hiranya911** [comment] 2018-08-30 23:56
Just ran into it: https://travis-ci.org/firebase/firebase-admin-java/builds/422814975

Restarted build also failed with the same error.

**Comment by sffc** [comment] 2018-08-31 05:58
Another failure: https://travis-ci.org/googlei18n/myanmar-tools/jobs/422348405

**Comment by regisd** [comment] 2018-08-31 11:28
For reference, the error looks like
```
[ERROR] Plugin org.apache.maven.plugins:maven-install-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-install-plugin:jar:2.4: Could not transfer artifact org.apache.maven.plugins:maven-install-plugin:pom:2.4 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

```

**Comment by regisd** [comment] 2018-08-31 11:29
Duplicate of #10053

**Comment by sormuras** [comment] 2018-09-04 03:41
@DrTorte Install and use a Repository Manager? ;-)

https://twitter.com/sonatypeDev/status/1036734093529047040

**Comment by cotsog** [comment] 2018-09-05 01:02
We believe this should be fixed now. [Sonatype proactively safe listed our IP addresses](https://twitter.com/sonatype_ops/status/1036980257109233667) and we also opened [a ticket](https://issues.sonatype.org/browse/MVNCENTRAL-3826) with them today.

Could you tell us if this issue resurfaces again? Thank you for posting links to builds where this happens if it's the case.

Thank you for your patience!

**Closed by cotsog** 2018-09-05 01:02 UTC

**Comment by waldbaerkoch** [comment] 2019-06-27 13:07
Many builds fail when connecting to maven central, e.g. https://travis-ci.com/waldbaerkoch/gen/builds/117140661

(default-resources) on project gentest: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources failed: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven:maven-profile:jar:2.0.6, org.apache.maven:maven-plugin-registry:jar:2.0.6, org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6, org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7, commons-cli:commons-cli:jar:1.0, org.apache.maven:maven-artifact:jar:2.0.6: Could not transfer artifact org.apache.maven:maven-profile:jar:2.0.6 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.jar , ReasonPhrase:Forbidden. -> [Help 1]
