### ISSUE TITLE
build continued even after failure to install desired node version

### ISSUE THREAD

**Issue by rlgomes** [travis-ci/travis-ci#5724] opened 2016-03-01 19:46 UTC
Looks like there have been similar issue with [install python](#5492), seeing the issue here:

https://travis-ci.org/juttle/juttle/builds/112931312

nvm hit:

```
$ nvm install 5.0
curl: (35) Unknown SSL protocol error in connection to nodejs.org:443 
Binary download failed, trying source.
```

then later instead of running with 5.0 we were running with:
```
$ node --version
v0.10.36
```

Is this the case of a different kind of failure ? The first error message does indicate trying source but seems like `nvm` didn't get to install the required version of node and instead of failing things there the run proceeded to fail in a way more cryptic manner later.

**Comment by rlgomes** [comment] 2016-03-01 19:46
@edmorley FYI opened the issue separately here.

**Comment by BanzaiMan** [comment] 2016-03-01 19:51
A duplicate of #5333.

**Closed by BanzaiMan** 2016-03-01 19:51 UTC
