### ISSUE TITLE
bundle command failing due to RubyGems bug

### ISSUE THREAD

**Issue by jnimety** [travis-ci/travis-ci#8969] opened 2017-12-22 17:34 UTC
This started happing on our builds yesterday. We have made no changes to .travis.yml in the past few weeks.
```
./bin/bundle:104:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from ./bin/bundle:104:in `<main>'
```

```
sudo: false
dist: trusty
language: ruby
cache:
  bundler: true
  yarn: true
rvm:
  - 2.4.2
bundler_args: --without "development debug"
env:
  matrix:
    # Run the quickest builds first to get them out of the way
    - TEST_SCRIPT=./script/ci/database_test.sh
    - TEST_SCRIPT=./script/ci/javascript_specs.sh
    - TEST_SCRIPT=./script/ci/simple_ruby_specs.sh
    - TEST_SCRIPT=./script/ci/flickering_specs.sh
    - TEST_SCRIPT=./script/ci/non_feature_specs.sh
    - TEST_SCRIPT=./script/ci/feature_specs.sh
    - TEST_SCRIPT=./script/ci/scss_lint.sh
    - TEST_SCRIPT=./script/ci/bundle_audit.sh
before_install:
  # prep node and yarn
  - nvm install 6.9.1
  - nvm use 6.9.1
  - npm install -g yarn
  # Prep gem and bundler
  - export PATH=./bin:./node_modules/.bin:./script/ci:$PATH
  - gem update --system
  - gem install bundler
before_script:
  - yarn install
  - RAILS_ENV=development webpack
  - RAILS_ENV=development webpack
  # Print versions for debugging
  - gem --version
  - node --version
  - yarn --version
  - eslint --version
  - phantomjs --version
  # this gives ElasticSearch time to start before the tests start
  - sleep 10
script: "${TEST_SCRIPT}"
branches:
  except:
    - /^[0-9]/
...
```

**Comment by jnimety** [comment] 2017-12-22 19:53
ok, I removed `.bin` from PATH thinking that the rails bundle wrapper script was causing issues, but I still get a similar error:

```
/home/travis/.rvm/gems/ruby-2.4.2/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.2/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by buianhthang** [comment] 2017-12-24 05:52
i think i have same issue

```
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.6
before_install:
  - gem update --system
  - gem update --remote bundler
before_script:
  - git config --global user.name "$(git --no-pager show --no-patch --format='%an')"
  - git config --global user.email "$(git --no-pager show --no-patch --format='%ae')"
script:
  - git clone -b gh-pages --depth 1 "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" _site >/dev/null 2>&1
  - rm -r _site/*
  - bundle exec jekyll build
after_success:
  - cd _site
  - git add -A
  - git commit -m "Updated to $(git rev-parse --short $TRAVIS_COMMIT) at $(date -u +'%Y-%m-%d %H:%M:%S %Z')"
  - git push "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" gh-pages >/dev/null 2>&1
branches:
  only:
    - master
```

error message
```
$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
/home/travis/.rvm/gems/ruby-2.3.6@global/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/gems/ruby-2.3.6@global/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.3.6@global/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `<main>'
/home/travis/.rvm/gems/ruby-2.3.6@global/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/gems/ruby-2.3.6@global/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.3.6@global/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.3.6/bin/ruby_executable_hooks:15:in `<main>'
The command "eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle} " failed 3 times.
The command "bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed and exited with 1 during .
```

**Comment by glennsarti** [comment] 2017-12-27 08:57
I have the same issue on https://github.com/puppetlabs/puppetlabs-registry/pull/146 and https://github.com/puppetlabs/puppetlabs-stdlib/pull/869

I tired reverting the the image used as per https://github.com/travis-ci/travis-ci/issues/8870 to no avail.  Only workaround that works so far is NOT updating bundler i.e. remove `gem update bundler` (or --remote in the post above) and just use the default 1.16.0

The interesting thing in the logs is:
``` text
...
$ bundle --version
Bundler version 1.16.0
...
$ gem update bundler
Updating installed gems
Updating bundler
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
Gems updated: bundler
...
$ bundle install --without system_tests --path=${BUNDLE_PATH:-vendor/bundle}
...
Using bundler 1.16.1   <--- so the bundle install is definitely using 1.16.1
...
$ bundle exec rake release_checks   <--- it then ACTUALLY runs bundle ...
...
(But later on the rake file it calls bundle  (or something else does) inside the rake task)
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
And the binstub is missing!

There seems to be some chatter about the 1.16.1 release and combination with rubygems version 2.7.x

Could possibly be related to https://github.com/bundler/bundler/issues/6072

**Comment by jnimety** [comment] 2017-12-27 16:09
removing the following from my build worked for me, removing `gem install bundler` alone was not enough.

```
  - gem update --system
  - gem install bundler
```

**Comment by BanzaiMan** [comment] 2017-12-27 16:50
See https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443

**Comment by buianhthang** [comment] 2017-12-27 17:41
@jnimety it's work for me, thanks 👍

**Comment by glennsarti** [comment] 2017-12-28 00:12
@BanzaiMan I tried adding `gem update --system`. Nothing changes as it thinks it's up to date

https://travis-ci.org/puppetlabs/puppetlabs-registry/jobs/322383254

``` text
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.0
$ gem --version
2.7.4
$ gem update --system
Latest version already installed. Done.
$ gem update bundler
Updating installed gems
Updating bundler
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
Gems updated: bundler
install.bundler
$ bundle install --without system_tests --path=${BUNDLE_PATH:-vendor/bundle}
...
Using bundler 1.16.1
...
Bundle complete! 14 Gemfile dependencies, 62 gems now installed.
Gems in the group system_tests were not installed.
Bundled gems are installed into `./vendor/bundle`
$ bundle exec rake release_checks
...
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
...
```

**Comment by jrochkind** [comment] 2018-01-08 19:15
Should we expect travis to fix/work around this at some point, or will we all have to do workarounds ourselves for ever more?  An update from travis maintainers would be welcome.

**Comment by johnnyshields** [comment] 2018-01-17 05:07
@BanzaiMan can you please update on this?

**Comment by BanzaiMan** [comment] 2018-01-24 22:03
I have repackaged the 2.5.0 archive for Linux to include RubyGems 2.7.4, which should have the fix for this issue. Please restart the affected jobs, and let us know how it goes for you.

The Mac archives are still waiting to be built. They will become available in due time.
 
Thank you!

**Comment by jrochkind** [comment] 2018-01-24 22:43
@BanzaiMan when i try re-running my job, I very strangely get an actual segfault. The segfault is coming from during execution of one of my tests, the tests do start. So it may not be related. 

Except I've never seen a segfault like this ever, and it does not segfault in the MRI 2.4.3 job in the same build. Weird. 

https://travis-ci.org/traject/traject/jobs/324891768

[raw log](https://gist.github.com/jrochkind/7188b62286505a0a9f11b34c943da772)

**Comment by BanzaiMan** [comment] 2018-01-24 23:04
@jrochkind I'm guessing that the new archive is somehow incompatible with your cache. Try deleting or disabling the cache.

**Comment by jrochkind** [comment] 2018-01-25 15:04
@BanzaiMan That makes sense, but flushing caches the problem still reproduces. 

HOWEVER, I just reproduced the problem locally on my MacOS workstation using ruby 2.5.0 and rubygems 2.7.4. 

So it's not a travis problem. It is troubling however, doh.

**Comment by y-yagi** [comment] 2018-01-26 07:43
@BanzaiMan
Rails's test using Ruby 2.5 has been an error since yesterday. 
https://travis-ci.org/rails/rails/jobs/333568773#L1235
 
It was not an error until the day before yesterday. 
Is there anything related to repackaged?

**Comment by MaxLap** [comment] 2018-02-14 11:32
I believe ruby-head has the same problem on ubuntu.

**Comment by perlun** [comment] 2018-04-10 09:04
Was first unable to find a way around this on Ruby 2.5.1:

```
$ bundle --version
Bundler version 1.16.1
$ gem --version
2.7.6
$ yarn install
$ gem update --system
Latest version already installed. Done.
$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
$ bundle exec rake
bundler: failed to load command: rake (/home/travis/build/ecraft/uxfactory-hub/vendor/bundle/ruby/2.5.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

**Even though I already had 1.16.1 in place**, adding `gem install bundler` to the `before_install` hook helped:

```yaml
before_install:
  - gem update --system
  - gem install bundler
```

(Posting this here in case it helps somebody.)

**Comment by jrochkind** [comment] 2018-04-14 13:15
Or if not fixed in the image, an official travis-endorsed workaround provided?  This lingering issue is challenging my opinion of Travis as easy to use.

**Comment by pond** [comment] 2018-04-15 20:52
👍 to all above comments. Lack of moment here is rather absurd - it's been well over a _quarter of a year_ since this fault first surfaced, and now we've got half the Travis-using world implementing gross workarounds in their configuration files.

An official statement here would take you all of two minutes to type up. Get on with it. We pay for your service, and it doesn't work properly with Ruby right now. Please fix this _urgently_. Thanks.

**Comment by mnoack** [comment] 2018-05-07 07:09
@BanzaiMan - We've just joined the list of people who have done the workaround.

I think most here would be happy with any kind of formal response, e.g.
"Travis are very busy with lots of features but will are trying to look into it soon"
"Travis are awaiting Ubuntu update for Ruby 2.5 to function well out of the box",
"Travis will have an update in a few more weeks"

**Comment by BanzaiMan** [comment] 2018-05-18 20:57
Hi, everyone,

I _think_ I tracked down the issue to an older version of RubyGems in use by the current Ruby 2.5.1, 2.5.0, 2.4.4 archives (there may be others). I've repackaged the affected Linux archives so that they use RubyGems 2.7.7 (there should be a line in your build log `gem --version` inside the `ruby --version` fold; cf. https://travis-ci.com/BanzaiMan/vandamme/builds/73872255#L470). If applicable, please try restarting the affected job, or drop the `gem install bundler` workaround and test the latest archive, and please report the results here.

Thank you!

**Comment by BanzaiMan** [comment] 2018-05-18 21:00
If you see this issue in other Ruby versions, do report them, too.

**Comment by pond** [comment] 2018-05-21 20:42
@BanzaiMan https://github.com/LoyaltyNZ/hoodoo/pull/263 indicates passes on Ruby 2.5.1, 2.4.4, 2.3.7 and 2.2.10. Thanks for resolving this issue. It allows us to migrate our many software components to the latest Ruby security patch levels without spreading `.travis.yml` workarounds all over the place, so it is very much appreciated.

**Comment by cben** [comment] 2018-05-23 11:12
@BanzaiMan Still happens for ruby 2.6.0-preview1:
https://travis-ci.org/cben/kubeclient/jobs/382615146
```
bundler: failed to load command: rake (/home/travis/build/cben/kubeclient/vendor/bundle/ruby/2.6.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-2.6.0-preview1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
...
```
Thanks!

**Comment by BanzaiMan** [comment] 2018-05-24 00:19
@cben Thanks for the ping. I've initiated the 2.6.0-preview1 builds again. https://travis-ci.org/travis-ci/travis-rubies/builds/382952466

**Comment by BanzaiMan** [comment] 2018-05-24 15:14
I think we can close this issue now. If see a problem, do report.

Thanks, everyone, for your reports and patience.

**Closed by BanzaiMan** 2018-05-24 15:14 UTC
Labels: ruby

**Comment by nikhilgupta1211** [comment] 2019-01-03 08:30
`The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'`

`The command "eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.`

Getting the error for ruby version `2.4.2`

**Comment by davygora** [comment] 2019-01-04 10:52
@nikhilgupta1211 
try: 
```
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.17.3
```

or:
```
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.3
```
