### ISSUE TITLE
docker: unrecognized service

### ISSUE THREAD

**Issue by karlkfi** [travis-ci/travis-ci#5448] opened 2016-01-13 01:25 UTC
Added docker to a travis build on a Kubernetes PR and am now getting:

```
$ sudo service docker start
docker: unrecognized service
```

and later

```
exec: docker: not found
```

Full log: https://api.travis-ci.org/jobs/101948276/log.txt?deansi=true

The top of the travis config is:

```
sudo: required

services:
  - docker

language: go

matrix:
  include:
    - go: 1.5.2
```

Potentially related to https://github.com/travis-ci/travis-ci/issues/5444 and https://github.com/travis-ci/travis-ci/issues/5142 which seemed to be caused by some permutations of build images not having docker installed.

**Comment by BanzaiMan** [comment] 2016-01-13 01:28
Please try `group: edge` at the top level of your `.travis.yml`.

**Comment by karlkfi** [comment] 2016-01-13 01:32
Is that for temporary workaround to use new fixes or a long term fix?

**Comment by BanzaiMan** [comment] 2016-01-13 01:34
For a temporary workaround until we update the stable image.

**Comment by BanzaiMan** [comment] 2016-01-13 01:36
Duplicate of #5370.

**Comment by karlkfi** [comment] 2016-01-13 01:43
What does `group: edge` do and when should I be able to remove it?

**Comment by karlkfi** [comment] 2016-01-13 18:30
That workaround didn't work:

```
Worker information
hostname: travis-worker-gce-org-prod-5:46ff8807-ad28-4796-b653-65c875bdca82
version: v2.0.0-24-g8f5b41a https://github.com/travis-ci/worker/tree/8f5b41a07b602643e7ee8cf307787f9ca8f4b00b
instance: testing-gce-9b518a22-d953-42a9-a049-66c8d72f9d20:travis-ci-go-precise-1452051147
startup: 21.559041512s
Build system information
Build language: go
Build group: edge
Build dist: precise
Build image provisioning date and time
Wed Jan  6 03:45:39 UTC 2016
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-63-generic
Cookbooks Version
53ebb2d https://github.com/travis-ci/travis-cookbooks/tree/53ebb2d
Git version
git version 1.8.5.6
bash version
GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

Same error:

```
$ sudo service docker start
docker: unrecognized service
```

https://api.travis-ci.org/jobs/101999363/log.txt?deansi=true

**Comment by BanzaiMan** [comment] 2016-01-13 18:43
That is interesting.

Could you try `dist: trusty` instead of `services: [ docker ]`?

**Comment by karlkfi** [comment] 2016-01-13 19:21
Adding `dist: trusty` seemed to resolve the issue (with `services: [ docker ]` still in there).

https://api.travis-ci.org/jobs/102169599/log.txt?deansi=true (failed for other unrelated reasons).

**Comment by BanzaiMan** [comment] 2016-01-13 20:15
Cool. As this is the preferred way now (as documented in https://docs.travis-ci.com/user/trusty-ci-environment#tl%3Bdr---Using-Trusty), I am closing this again.

**Closed by BanzaiMan** 2016-01-13 20:15 UTC

**Comment by karlkfi** [comment] 2016-01-13 23:38
is `group: edge` required if using `dist: trusty`?

**Comment by BanzaiMan** [comment] 2016-01-13 23:49
@karlkfi No. `group: edge` is for choosing a newer Trusty image.

**Comment by Tyoshi14** [comment] 2016-07-27 07:15
@BanzaiMan  hello， I also have the same problem and have tried all the methods you mentioned, but failed. Here is my [file ](https://github.ibm.com/bjzhaoyq/SWC_Web_eOrder/commit/298e2722696523b6c7612d1441f13b72911d5eca)and [log](https://travis.innovate.ibm.com/bjzhaoyq/SWC_Web_eOrder/builds/663144). What is the problem?
