### ISSUE TITLE
julia: IOS nightly errors on hdiutil mount

### ISSUE THREAD

**Issue by gdziadkiewicz** [travis-ci/travis-ci#5745] opened 2016-03-04 22:51 UTC
@tkelman, @ninjin, @staticfloat,
It seems that there is a problem with the image used for IOS nightly Julia build. All my Julia repos builds error on IOS nightly with:
```
hdiutil mount -readonly -mountpoint juliamnt julia.dmg
hdiutil: mount failed - image not recognized
The command "hdiutil mount -readonly -mountpoint juliamnt julia.dmg" failed and exited with 1 during .
```
Full log from one of the repos:
[log.txt](https://github.com/travis-ci/travis-ci/files/159501/log.txt)

**Comment by BanzaiMan** [comment] 2016-03-05 00:54
I think this is a duplicate of #5740.

**Closed by BanzaiMan** 2016-03-05 00:54 UTC
