### ISSUE TITLE
Support 'rebar3' tool for erlang projects

### ISSUE THREAD

**Issue by clarete** [travis-ci/travis-ci#6506] opened 2016-08-20 17:15 UTC
Hello dear Travis people,

I've being using the `rebar3` tool to manage a few Erlang projects, I'd love to not have to copy it to the source control of the project. It would easy the setup on my end a lil bit.

I think this issue is different from #5052 because I think a lot of projects are still using `rebar` which is forwards incompatible with the one I'm using: `rebar3`. I think the version suffix is to enable both to coexist in the same environment.

Also, the default script could still point to the currently most used version, `rebar`.

Thank you!

**Comment by binarytemple-bet365** [comment] 2016-12-22 11:03
Is there an alternative to copying in the binary blob? I'd like to integrate a couple of projects with Travis.

**Comment by altaica** [comment] 2017-01-21 11:14
rebar is [deprecated](https://github.com/rebar/rebar). rebar3 is now the [official](http://erlangcentral.org/blog/industrial-erlang-user-group/rebar3-has-been-added-to-erlang-github-organization/) build tool and will be included in future OTP releases, starting (unconfirmed, but from a reliable source) with R20. In the mean time, I use the following, which to all intents and purpose does not affect build times:

```# Travis uses rebar by default. Get rebar3 instead.
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

**Comment by meatballhat** [comment] 2017-01-25 18:22
The solution @altaica shows above is effectively what I've opted to implement: https://github.com/travis-ci/travis-cookbooks/blob/9ac3e469bdbc953335ed4a3e9a0aa3d18b3e5cec/cookbooks/travis_build_environment/recipes/rebar.rb
This means that once the next build environment update is live, both `rebar` and `rebar3` will be available in `$PATH`.

**Comment by rexim** [comment] 2017-06-20 16:52
@altaica your workaround works perfectly! Thank you very much!

**Comment by eproxus** [comment] 2017-06-28 10:23
@meatballhat Still getting this:

```
$ rebar3 eunit
/home/travis/.travis/job_stages: line 54: rebar3: command not found
```
(from https://travis-ci.org/eproxus/meck/jobs/247877133)

Anything we have to do to enable it?

**Comment by vladdu** [comment] 2017-08-17 08:24
The default 'install' step calls "rebar get-deps", which does a useless operation (directory locations have changed). I'm not sure how you would detect if a project wants 'rebar' or 'rebar3'.

**Comment by eproxus** [comment] 2017-08-17 09:23
Rebar3 is adopted by Erlang itself as the de facto build tool for Erlang projects. I see no reason not to use it as a default build tool. People are free to install older versions if they need it (as _has_ to be done right now for Rebar3, since it is not installed by default).

**Comment by BanzaiMan** [comment] 2017-08-17 18:05
`rebar3` is available in `/usr/local/bin` on Trusty images (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/265677796#L419; https://travis-ci.org/BanzaiMan/travis_production_test/jobs/265677797#L429).

Currently, we look for `./rebar` first in the repository root. If it's there, it is executed instead of `rebar`. Is there a similar convention for `rebar3`? (Meaning, `./rebar3` should be sought?)

It is simple enough to look for `rebar3` for those builds that can find it by default; switch the default command from

    rebar get-deps

to

    if (command -v rebar3); then rebar3 get-deps; else rebar get-deps; fi

and so on.

(Installing `rebar3` on Precise on the fly is also an option, but I don't know if that is in the interest for the long term, as Precise is on its way out.)

**Comment by BanzaiMan** [comment] 2017-08-17 18:40
We choose `rebar` if either `rebar.config` or `Rebar.config` is found on the repository root. Is this still valid for `rebar3`?

If we run `rebar3` where an older version of `rebar` is expected, would it fail? How? Is there a reliable way to detect the use of `rebar3`? If not, switching to `rebar3` as default would break some builds.

**Comment by eproxus** [comment] 2017-08-21 15:20
@BanzaiMan Unfortunately it's called `rebar.config` for both versions, so there's no way to auto detect the build tool being used here. You could maybe change the Erlang build tool configuration somehow so that old `.travis.yml` config files are detected and expected to use the old Rebar version?

As a side note, I seem to get Precise images as default. How do I use the Trusty images? I have `os: linux' in my `.travis.yml`

**Comment by BanzaiMan** [comment] 2017-08-21 15:32
> If we run `rebar3` where an older version of rebar is expected, would it fail? How?

We *could* switch to `rebar3` and hope for the best; if it fails _*safely*_ (by some definition of "safe"), we can then fall back to `rebar`. (And display a warning about the change in the default command.)

**Comment by eproxus** [comment] 2017-08-21 15:51
It totally depends on the app, see http://www.rebar3.org/docs/from-rebar-2x-to-rebar3. Most apps would work, but apps that use C-code or have non-trivial configuration will probably break.

**Comment by BanzaiMan** [comment] 2017-08-23 19:05
@eproxus In the case where `rebar3` does fail, is it admissible to move on to call `rebar` _after the failure_?

We would like to offer the change with least amount of friction.

**Comment by binarytemple-external** [comment] 2017-08-23 21:02
Can't rebar 2 just be depreciated on modern build images? Rebar 3 has been
stable a long time now. Rebar 2 is deprecated anyway.

**Comment by ddeboer** [comment] 2017-08-23 21:05
That would be the best way to go about it. Rebar3 could also fail other reasons (an error in the rebar.config file for instance) and you wouldn't want to switch to rebar (2) in that case.

**Comment by BanzaiMan** [comment] 2017-08-23 22:03
https://github.com/travis-ci/travis-build/pull/1147 changes the behavior such that `rebar3` is invoked when it is available (`./rebar` is still preferred to `rebar3`). See also https://github.com/travis-ci/docs-travis-ci-com/pull/1386 for the documentation change.

**Comment by BanzaiMan** [comment] 2017-08-29 19:28
Does anyone have a repo that I can fork and test https://github.com/travis-ci/travis-build/pull/1147 with? I'd want one with `rebar`, another with `rebar3`, if possible.

**Comment by ddeboer** [comment] 2017-09-04 06:39
For rebar3, you could take the [most popular](https://hex.pm) Erlang repo: https://github.com/ninenines/cowboy. Not sure with repos still use the (deprecated) rebar.

**Comment by binarytemple-external** [comment] 2017-09-04 07:02
All Loic repos use makefile build system so rebar3 is going to be
distinctly second class.

Here's a much better project - tanodb - a demonstration riak core
application - heavy rebar3 leverage.

**Comment by binarytemple-external** [comment] 2017-09-04 07:02
Sorry missed the link -
https://github.com/marianoguerra/tanodb/blob/master/rebar.config

**Comment by BanzaiMan** [comment] 2017-09-06 19:36
Cowboy with default configuration with new rebar3: https://staging.travis-ci.org/BanzaiMan/cowboy/builds/623474 (e.g., https://staging.travis-ci.org/BanzaiMan/cowboy/jobs/623475#L414) 0 tests.

**Comment by BanzaiMan** [comment] 2017-09-06 19:52
tanodb: https://staging.travis-ci.org/BanzaiMan/tanodb/jobs/623478 I don't think this is meant to be run with `rebar3`?

**Comment by binarytemple** [comment] 2017-09-07 08:08
@marianoguerra any suggestions? Migrating rebar support to rebar3 on Travis CI.

**Comment by eproxus** [comment] 2017-09-07 08:21
@BanzaiMan Meck uses Rebar 3: https://github.com/eproxus/meck

**Comment by marianoguerra** [comment] 2017-09-07 09:24
tanodb was created using rebar3, maybe it needs some updates to make it run again (usually warnings-as-errors in dependencies)

**Comment by binarytemple** [comment] 2017-09-07 09:58
Lager parse transform in cuttlefish in this case

**Comment by marianoguerra** [comment] 2017-09-07 10:05
I'm making it build again now

**Comment by marianoguerra** [comment] 2017-09-07 10:47
ok, tanodb master (https://github.com/marianoguerra/tanodb/) builds and runs on erlang 19.3 and 20.0

**Comment by marianoguerra** [comment] 2017-09-07 10:59
ok, tanodb master (https://github.com/marianoguerra/tanodb/) builds and runs on erlang 19.3 and 20.0

@BanzaiMan can you pull latest changes and try again?

**Comment by BanzaiMan** [comment] 2017-09-07 13:31
tanodb after merge with upstream: https://staging.travis-ci.org/BanzaiMan/tanodb/builds/623530

**Comment by BanzaiMan** [comment] 2017-09-07 13:33
In all cases, I'm using the default configuration (except changing OTP Release); e.g., https://github.com/BanzaiMan/tanodb/blob/2cbac4eed1e2847e93d0f7049b98b15e9f9d25d2/.travis.yml

**Comment by BanzaiMan** [comment] 2017-09-07 13:41
- meck with the current configuration (which, incidentally has two `script` sections, the first of which is ignored and harmless): https://staging.travis-ci.org/BanzaiMan/meck/builds/623533
- meck with the new default (after removing both `install` and `script`): https://staging.travis-ci.org/BanzaiMan/meck/builds/623540

**Comment by BanzaiMan** [comment] 2017-09-07 13:44
Seems these tests are… good?

**Comment by eproxus** [comment] 2017-09-07 14:02
@BanzaiMan Yeah, looks good to me. This is what I expected as default if Rebar 3 would be bundled in Travis

**Comment by umatomba** [comment] 2017-09-27 12:39
hi, when it will be released/available in travis?

**Comment by BanzaiMan** [comment] 2017-10-06 19:26
I reckon we can merge and deploy the PR next week.

**Closed** 2017-10-11 17:49 UTC
Labels: build environment, erlang, travis-build

**Comment by binarytemple** [comment] 2017-10-13 15:50
Nice @hiro thanks for your assistance!

**Comment by BanzaiMan** [comment] 2017-10-13 16:04
@binarytemple That’s not me, but you are welcome! :-)
