### ISSUE TITLE
jdk_switcher does not work on trusty images

### ISSUE THREAD

**Issue by felixbarny** [travis-ci/travis-ci#8348] opened 2017-09-05 11:45 UTC
See build https://travis-ci.org/stagemonitor/stagemonitor-integration-tests/jobs/271136950

```
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
```

**Comment by BanzaiMan** [comment] 2017-09-05 12:10
Duplicate of #7884.

**Closed by BanzaiMan** 2017-09-05 12:10 UTC
