### ISSUE TITLE
Cannot negotiate TLS 1.2

### ISSUE THREAD

**Issue by sethvargo** [travis-ci/travis-ci#7170] opened 2017-01-17 16:58 UTC
Recently we upgraded our infrastructure to only support TLS 1.2 (as is required by June, 2017). Now it seems the Docker containers are unable to speak TLS 1.2, as shown below:

```
$ export VAULT_VERSION=0.6.2
# ...
$ curl -v -sLo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
* About to connect() to releases.hashicorp.com port 443 (#0)
*   Trying 151.101.33.183... connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* Unknown SSL protocol error in connection to releases.hashicorp.com:443 
* Closing connection #0
```

Compare that to my local curl, which returns:

```
# ...
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [107 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3014 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc; CN=s.ssl.fastly.net
*  start date: Jan  9 22:31:02 2017 GMT
*  expire date: Jun 29 17:46:45 2017 GMT
*  subjectAltName: host "releases.hashicorp.com" matched cert's "*.hashicorp.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign CloudSSL CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
# ...
```

Here is a link to one of the builds: https://travis-ci.org/hashicorp/vault-ruby/jobs/192747358. 

Is there any way to get support for the new TLS in Travis?

Cross-linking with https://github.com/travis-ci/travis-ci/issues/4757.

**Comment by sethvargo** [comment] 2017-01-17 17:10
Moving to https://docs.travis-ci.com/user/trusty-ci-environment/ fixed the issue. I'm going to leave this open for google-ablility though.

**Comment by BanzaiMan** [comment] 2017-01-17 17:25
@sethvargo I'm closing this as a duplicate of #7131.

**Closed by BanzaiMan** 2017-01-17 17:25 UTC
