### ISSUE TITLE
Job logs being cut short

### ISSUE THREAD

**Issue by rizhang** [travis-ci/travis-ci#6536] opened 2016-08-29 17:53 UTC
https://travis-ci.org/sharethrough/iOS-SDK/builds/155998706

It looks like the "Job Log" stops printing prematurely. I don't see the line that tells you how many pass or failed. Is this expected behavior?

**Comment by joepvd** [comment] 2016-10-01 19:45
Thanks for reporting! Closing as a duplicate of #4716.

**Closed by joepvd** 2016-10-01 19:45 UTC
