### ISSUE TITLE
Travis-ci broke my build script.

### ISSUE THREAD

**Issue by Neopallium** [travis-ci/travis-ci#5496] opened 2016-01-22 05:07 UTC
My build script was working before.
Now travis-ci is ignoring the custom build script commands in my .travis.yml file:
https://github.com/Neopallium/lua-zmq/blob/master/.travis.yml

travis-ci is trying to use the default "Autotools and Make" instead of using cmake.  My .travis.yml file had commands for running cmake, these worked before.

Even a very simplify build script doesn't work:
https://travis-ci.org/Neopallium/lua-zmq/builds/104018257

I have tried many different changes to the build script.  Even the before_install, install & before_script commands seem to be ignored.

Debugging problems like this is very difficult when I can't see the generated code that the VM runs.  So I have no idea why it is failing.

**Comment by BanzaiMan** [comment] 2016-01-22 05:16
Hello there. Believe or not, this is a duplicate of #4839. Your `.travis.yml` has a byte order mark at the beginning of the file, so the customization is ignored. Please remove the BOM and try again.

**Closed by BanzaiMan** 2016-01-22 05:16 UTC
