### ISSUE TITLE
Job to be executed when all other jobs in build finish successfully

### ISSUE THREAD

**Issue by szpak** [travis-ci/travis-ci#6053] opened 2016-05-15 09:33 UTC
Using build [matrix](https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines) I'm able to divide my integration/acceptance tests across different VMs. However I have also an automatic artifacts upload/release task which should only happen only if ALL jobs for given build are successful.

How to create a job which will be executed **only** if **all** other jobs in a given build finish successfully?

**Comment by BanzaiMan** [comment] 2016-05-15 09:45
Duplicate of #929.

**Closed by BanzaiMan** 2016-05-15 09:45 UTC
