### ISSUE TITLE
BOM prevents correct CPP configuration

### ISSUE THREAD

**Issue by NSchertler** [travis-ci/travis-ci#7785] opened 2017-05-19 08:18 UTC
When an UTF-8 byte order mark exists in `.travis.yml` and the language is set to `cpp`, all configurations from the YAML file except the language will be ignored. I.e., in a `.travis.yml` like the following:

    [BOM]language: cpp
    sudo: false
    os: linux
    dist: trusty
    before_install:
      - git submodule update --init --recursive
    script:
      - cmake -DCMAKE_CXX_COMPILER=g++-4.9
      - make    
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - kubuntu-backports
          - boost-latest
        packages:
          - g++-4.9
          - cmake
          - libboost1.63-all-dev
 The configuration as parsed by Travis CI is the following

    {
      "language": "cpp",
      "group": "stable",
      "dist": "precise",
      "os": "linux"
    }
, which obviously misses important parts. Especially, the default script `./configure && make && make test` is used instead of the provided one.

This problem does not seem to occur with other languages.

**Comment by BanzaiMan** [comment] 2017-05-19 10:53
Thanks for the report. This is a duplicate of #4839. Please remove the BOM.

**Closed by BanzaiMan** 2017-05-19 10:53 UTC

**Comment by NSchertler** [comment] 2017-05-19 12:26
Sorry for the duplicate. I agree that removing the BOM is a valid solution. However, there should be an error message somewhere that points to this problem. Right now, you just get an empty config and wonder why this is happening. Also, it would be nice if the online validator could check for this.

**Comment by BanzaiMan** [comment] 2017-05-19 12:41
@NSchertler My test shows that our [current error message](https://travis-ci.org/BanzaiMan/travis_production_test/builds/234000759#L7) is:

```
ERROR: An error occured while trying to parse your .travis.yml file.
Please make sure that the file is valid YAML.
http://lint.travis-ci.org can check your .travis.yml.
The log message was: Build config file had a parse error: control characters are not allowed at line 1 column 1.
```

Is this not what you saw? Do you have a log URL to show?

**Comment by NSchertler** [comment] 2017-05-19 12:46
@BanzaiMan I didn't see any of this, indeed: https://travis-ci.org/NSchertler/ns_test/builds/233672638

**Comment by BanzaiMan** [comment] 2017-05-19 13:16
Interesting. The UTF-8 BOM passes through to the point where the build can actually run (but with an empty configuration).
