### ISSUE TITLE
Time out error after build completed

### ISSUE THREAD

**Issue by mchurchward** [travis-ci/travis-ci#6898] opened 2016-11-18 13:54 UTC
Hi -
I'm getting a time out error at the end of my build, causing the build to be flagged as erroneous. The message is:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> 
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

Here is an [example job](https://travis-ci.org/remotelearner/moodle-mod_questionnaire/jobs/177016481).

I tried adding a "travis wait" command, but that didn't work.
Any ideas?

**Comment by mhines-usgs** [comment] 2016-11-19 15:07
Our team has been experiencing the same problem for a few days. There are no problems with local checks, and not sure where it would make any sense for a wait argument.  https://travis-ci.org/USGS-R/repgen/builds/177124931

**Comment by mickael-ange** [comment] 2016-11-21 02:48
Relates/duplicates https://github.com/travis-ci/travis-ci/issues/6861

**Comment by BanzaiMan** [comment] 2016-11-22 14:36
@mhines-usgs appears to be a slightly different issue, as your build stalls in the middle. The issue raised here concerns hangs *after* the script ended, which is indeed a duplicate of #6861.

I'm closing this as a duplicate.

**Closed by BanzaiMan** 2016-11-22 14:36 UTC
Labels: team blue
