### ISSUE TITLE
APT source whitelist request for protobuf 2.5.0

### ISSUE THREAD

**Issue by riteshkfb** [travis-ci/travis-ci#3931] opened 2015-05-20 18:44 UTC
The launchpad url for the ppa is : https://launchpad.net/~chris-lea/+archive/ubuntu/protobuf. The ppa desc is ppa:chris-lea/protobuf

Need this for compiling apache hadoop.

**Comment by BanzaiMan** [comment] 2015-07-20 16:33
Did not run automated check because title 'Addition of protobuf 2.5.0 to apt whitelist for ubuntu precise' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment] 2015-07-25 16:29
Looks like a duplicate of #3794.

**Closed by BanzaiMan** 2015-07-25 16:29 UTC
Labels: apt-source-whitelist, apt-whitelist, apt-whitelist-ambiguous, apt-whitelist-check-run
