### ISSUE TITLE
Connection timeout for some repositories

### ISSUE THREAD

**Issue by pevik** [travis-ci/travis-ci#9131] opened 2018-01-24 14:50 UTC
Hi,

this is similar to #8834, which is closed.

We experienced several timeouts during January which break build:
http://lists.linux.it/pipermail/ltp/2018-January/thread.html

Sometimes it occurs but it does not break build:
https://api.travis-ci.org/v3/job/332737266/log.txt
```
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Could not connect to www.apache.org:80 (140.211.11.105), connection timed out
W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com port 443: Connection timed out
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
NOTE: were not using `apt update` in  our config as I don't think it would help to solve it.
https://github.com/linux-test-project/ltp/blob/master/.travis.yml

**Comment by BanzaiMan** [comment] 2018-01-24 15:05
Closing as a duplicate of https://github.com/travis-ci/travis-ci/issues/9112.

**Closed by BanzaiMan** 2018-01-24 15:05 UTC
