### ISSUE TITLE
Cannot download JDK 8

### ISSUE THREAD

**Issue by jinhyukchang** [travis-ci/travis-ci#9431] opened 2018-04-02 18:27 UTC
Same issue as #9379 and seems occurring again. (Recreating an issue as previous one has been closed.)

https://travis-ci.org/apache/incubator-airflow/jobs/361250290
https://travis-ci.org/apache/incubator-airflow/jobs/361250292
https://travis-ci.org/apache/incubator-airflow/jobs/361250294

Using curl command from my local host has no problem.
```
$ curl -L -b "oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   531  100   531    0     0    876      0 --:--:-- --:--:-- --:--:--  2751
100  180M  100  180M    0     0  15.7M      0  0:00:11  0:00:11 --:--:-- 16.7M
```

**Comment by BanzaiMan** [comment] 2018-04-02 18:31
Duplicate of #9419.

**Closed by BanzaiMan** 2018-04-02 18:31 UTC
