### ISSUE TITLE
Add support for PhantomJS 2.0

### ISSUE THREAD

**Issue by habdelra** [travis-ci/travis-ci#3225] opened 2015-02-12 14:54 UTC
For our build environment we want to start using PhantomJS 2.0 to address stability problems we are encountering with PhantomJS 1.9.7 randomly crashing. Currently only phantomjs 1.9.7 is available in the build environment. Building phantomjs manually as part of our build is not feasible as it requires us running `apt-get` for the necessarily dependencies, and the build takes multiple hours to run in order to compile phantom JS. 

It would be great if the PhantomJS 2.0 binary was available in the build environment. I think it would make sense to have multiple ver of phantomjs available, where we could set a property in our `.travis.yml` to select the version we want to use.

thanks!

**Comment by BanzaiMan** [comment] 2015-02-12 16:43
We should have PhantomJS 1.9.8 at the moment. What breaking changes does 2.0 bring?

**Comment by msridhar** [comment] 2015-02-12 18:26
@BanzaiMan see the [release notes](http://phantomjs.org/release-2.0.html); removal of CoffeeScript support is one breaking change listed there.  A big plus for 2.0 is that it is based on a much more recent version of WebKit, which I imagine makes it applicable in more scenarios.

**Comment by BanzaiMan** [comment] 2015-02-13 03:58
There is no official binary available yet. (https://github.com/ariya/phantomjs/issues/12948) The process is a major resource hog, and it is not feasible to compile it on the fly. If it's still not available for the next update (1st week of April), we can compile a binary separately for our purposes.

**Comment by BanzaiMan** [comment] 2015-03-02 17:39
For those brave souls who want to try PhantomJS 2.0.0 now, you can use https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2. The archive expands to the binary `phantomjs` for Ubuntu 12.04 64-bit, and the license file to comply with PhantomJS's BSD license.

**Comment by parndt** [comment] 2015-03-02 22:32
PhantomJS fails many tests that pass on PhantomJS 1.9.8 for me, due to the reasons outlined in teampoltergeist/poltergeist#574 / ariya/phantomjs#12506 / teampoltergeist/poltergeist#585

File upload doesn't seem to work consistently.

**Comment by BanzaiMan** [comment] 2015-03-02 22:50
@parndt In a way, then, these are expected failures with PhantomJS 2.0.0, correct?

**Comment by parndt** [comment] 2015-03-03 21:15
@BanzaiMan yes, I'm just vocalising objection to upgrading the default version until they're worked out.

**Comment by BanzaiMan** [comment] 2015-03-03 21:26
@parndt Got it. I'm leaning towards offering both 1.9.8 and 2.0.0.

**Comment by esbanarango** [comment] 2015-03-11 16:55
:+1:

**Comment by Thibaut** [comment] 2015-03-28 17:34
>  I'm leaning towards offering both 1.9.8 and 2.0.0.

:+1:

**Comment by BanzaiMan** [comment] 2015-04-06 16:44
See https://github.com/travis-ci/travis-cookbooks/commit/e38732d It will be available as `/usr/local/phantomjs-2.0.0/bin/phantomjs`. 1.9.8 remains the default.

**Comment by BanzaiMan** [comment] 2015-04-28 04:37
Sorry about the high hopes, but we have decided to cancel the 2015-04 updates, due to issues unrelated to PhantomJS 2.0.

If you want to use it now, you can grab it from S3 as indicated above.

**Comment by robcolburn** [comment] 2015-05-27 21:21
@BanzaiMan any update?

**Comment by BanzaiMan** [comment] 2015-06-08 14:49
@robcolburn I miss this comment. We are working on the next updates, but we don't have the concrete date for them yet.

**Comment by blimmer** [comment] 2015-06-09 16:04
Our test suite fails without Phantom 2. To work around this, we do the following:
```yaml
install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
```

**Comment by armandocanals** [comment] 2015-06-28 02:41
I ended up packaging PhantomJS 2.0 from source into a deb to make my life a little easier.

Ubuntu 12.04 64-bit (precise)
https://packagecloud.io/armando/phantomjs/packages/ubuntu/precise/phantomjs_2.0.0_amd64.deb

Ubuntu 14.10 64-bit (utopic)
https://packagecloud.io/armando/phantomjs/packages/ubuntu/utopic/phantomjs_2.0.0_amd64.deb

**Comment by Jell** [comment] 2015-07-13 15:33
any update on this?

**Comment by robcolburn** [comment] 2015-07-17 00:14
@armandocanals How do we use the debian files?

**Comment by robcolburn** [comment] 2015-07-17 00:18
The script from @BanzaiMan now breaks for me :(
https://travis-ci.org/robcolburn/drupal-app_link/builds/71345678

But, Travis's Phantom is crashing & burning for me.
https://travis-ci.org/robcolburn/drupal-app_link/builds/71343755

My suite runs ~50 or so near-identical tests, but attempts to re-use the Phantom Instance

**Comment by BanzaiMan** [comment] 2015-07-17 00:33
@robcolburn Where is `mocha`? https://travis-ci.org/robcolburn/drupal-app_link/builds/71345678#L109 I cannot remember if it's supposed to be available by default.

**Comment by robcolburn** [comment] 2015-07-17 00:38
@BanzaiMan,
It's not.

I have mocha as a dev dependency, which means npm will make a symlimk at `node_modules/.bin/mocha` so npm can see it when running scripts.

**Comment by armandocanals** [comment] 2015-07-17 00:43
@robcolburn you can download and install the deb package manually using something like `dpkg`. In the link there is an option to download the package from the web.

`$ dpkg -i path/to/phantomjs_2.0.0_amd64.deb`

or install the [phantomjs repo](https://packagecloud.io/armando/phantomjs) I created and use `apt-get` to install the package. I have also provided the Debian source package `dsc` for each distro that I packaged for phantomjs. Both are available in the phantomjs packagecloud repo.

**Comment by BanzaiMan** [comment] 2015-07-17 01:05
@robcolburn You have [overridden the `install` section](https://github.com/robcolburn/drupal-app_link/blob/996370b2aadd01ec31fb1c34614ddeeb6e7c2764/.travis.yml#L4-L8), so it is your responsibility to run `npm install` there, so that `mocha` is available.

**Comment by robcolburn** [comment] 2015-07-17 01:05
@armandocanals,
Does the Debian package yield any advantage over the Travis script that @blimmer posted?

**Comment by robcolburn** [comment] 2015-07-17 01:06
@BanzaiMan,
Interesting, thanks! I assumed it was append to the default install. Replace does make more sense.

**Comment by robcolburn** [comment] 2015-07-17 01:26
@BanzaiMan,
High Today: Totally have newer version of Phantom.
Low Today: Random crashes on Travis. Nothing makes sense anymore.
https://travis-ci.org/robcolburn/drupal-app_link/builds/71350737

**Comment by BanzaiMan** [comment] 2015-07-17 01:44
@robcolburn Sorry to hear, but that seems a separate issue. If you want a debug VM, we are happy to spin one up for you. Please email support@travis-ci.com. Thanks.

**Comment by cantonic** [comment] 2015-07-17 12:21
@robcolburn The 2.0.0 version caused problems for me as well. File uploads for example didn't work due to a known bug in 2.0.0. I have compiled an ubuntu binary of a patched version of 2.0.1 which works on TravisCI: https://github.com/cantonic/phantomjs/releases/tag/2.0.1-regression-12506

**Comment by simpixelated** [comment] 2015-07-17 22:47
I've been using this https://github.com/gskachkov/karma-phantomjs2-launcher for running Karma with PhantomJS2 locally and on Jenkins successfully for several days. But on Travis CI when it tries to start the unit tests I get:
```
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS2
ERROR [launcher]: Cannot start PhantomJS2
INFO [launcher]: Trying to start PhantomJS2 again (1/2).
...
ERROR [launcher]: PhantomJS2 failed 2 times (cannot start). Giving up.
```
I tried using the .yml code suggested by @blimmer to get PhantomJS2 from the S3 link, but I get the same error. Installing 1.9.8 results in "Script error" during the tests, but at least it starts.

**Comment by cantonic** [comment] 2015-07-17 23:01
@simpixelated try my binary from https://github.com/cantonic/phantomjs/releases/tag/2.0.1-regression-12506 on TravisCI. That one worked for me

**Comment by simpixelated** [comment] 2015-07-17 23:22
@cantonic From the link on the release page? Link is broken for me:
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/39252520/a1bf61b4-2c8e-11e5-9685-890c1b667c33.04_64bit
</Key>
<RequestId>D26C1ABFA9A7546C</RequestId>
<HostId>
DSYeYCjYtJ7PCxY6w4nkQspfovYGEmG1alzjx38MRbUkdwZi3kww9IjG1SJ/uf5K
</HostId>
</Error>
```

**Comment by robcolburn** [comment] 2015-07-22 00:02
@BanzaiMan,
FYI: For my use-case, I'll be able to return to using Travis's stock Phantom! \o/

My PR that was dying was attempting to optimize my test-plan, by re-using the `phantom` process to speed-up execution time. Unfortunately, I had a bug in my Phantom recycling code that would leave "pages" (like browser tabs) open until Phantom crashed.  Previously, I had fewer tests and didn't mind re-starting new phantom processes each time (250ms expense).  Anyway, I've figured out to close those pages, and be easier on memory over all.

Thanks for all your help!

**Comment by rgbkrk** [comment] 2015-08-21 19:08
How's 2.0 support looking on Travis now?

**Comment by blimmer** [comment] 2015-09-01 23:02
Is there any estimate on when this will be available? I dislike having to use this hack...

**Comment by dirk** [comment] 2015-09-05 20:24
Seconding @blimmer on wanting to have an ETA. PhantomJS 1.x is extremely out of date and hampering progress.

**Comment by spadin** [comment] 2015-09-11 18:09
@BanzaiMan [you mentioned](https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-90145295) phantomjs 2.0.0 is available at `/usr/local/phantomjs-2.0.0/bin/phantomjs` is that true for paid travis accounts too?

I ran `PATH=/usr/local/phantomjs-2.0.0/bin:$PATH which phantomjs` but it only found the `phantomjs` at  `/usr/local/phantomjs/bin/phantomjs`

**Comment by silvenon** [comment] 2015-09-12 16:46
@spadin later he said that they had to cancel that update due to some issues, so it's not available yet.

Don't really see what the downside of the v2 download hack is, other than feeling dirty.

**Comment by youurayy** [comment] 2015-10-16 17:56
So, almost a year, is PhantomJS2 still not supported on Travis CI?

**Comment by youurayy** [comment] 2015-10-16 22:47
Please what is the ETA on this @BanzaiMan?

**Comment by BanzaiMan** [comment] 2015-10-19 16:33
We are working on the next build environment updates. There are a few infrastructure issues that needs to be taken care of before unleashing them, which is causing the delay. Thank you for your patience.

**Comment by dvoytenko** [comment] 2015-10-19 22:53
Would love to see Phantom2 support as well!

**Comment by erwinmombay** [comment] 2015-10-20 00:13
+1

**Comment by domenkozar** [comment] 2015-10-20 10:03
:+1:

**Comment by vinsonchuong** [comment] 2015-10-27 04:01
From what I can tell, PhantomJS 2.0.0 is installed in the Trusty environment: http://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by meatballhat** [comment] 2015-11-03 08:46
@vinsonchuong that is correct!  PhantomJS 2 is available in Ubuntu Trusty, which is currently available only in fully-virtualized.  We are planning to roll out Ubuntu Trusty support on container-based as well.  There are no plans (currently) to support PhantomJS on Ubuntu Precise.

**Comment by wkoszek** [comment] 2015-11-28 07:11
+1. I basically can't test my website which has `<script async .....>` stuff. The `async` is causing 1.9.8 PhantomJS to die.

Had to switch to Firefox for testing.

**Comment by silvenon** [comment] 2015-11-28 10:24
Yeah, we just have to be patient.

**Comment by alecha** [comment] 2015-12-23 19:10
almost 1 year and still no good news :(

**Comment by djones** [comment] 2016-01-21 18:58
+1

**Comment by BanzaiMan** [comment] 2016-01-25 04:48
PhantomJS 2.1 is out, and there is a static Linux binary: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 (see http://phantomjs.org/download.html).

If you are using the workaround above (https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-110416315), you might want to try this static binary file instead.

**Comment by djones** [comment] 2016-01-25 16:30
Building upon @blimmer's example, PhantomJS 2.1 is working for me using this config in my `.travis.yml` file:

```yaml
before_install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
```

**Comment by fivetanley** [comment] 2016-01-31 19:21
I had to make some tweaks to @djones's code:

```yaml
before_install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
```

It needed the `bin` directory, as well as the extracted `phantomjs-2.1.1-linux-x86_64` directory. It's possible the download may have changed from PhantomJS.

**Comment by agconti** [comment] 2016-02-19 15:57
@fivetanley thanks for sharing!

**Comment by nlundquist** [comment] 2016-03-05 03:56
+1

**Comment by agconti** [comment] 2016-03-17 18:18
I'm running into a lot of `429` too many requests with @fivetanley method that stops builds. Is there a way authenticate to get over being rate limited?

**Comment by fauxparse** [comment] 2016-03-18 20:12
Push less often? ;)

**Comment by BanzaiMan** [comment] 2016-03-18 20:35
If Bitbucket is denying the download, then I suggest getting the archive from some other trusted source (perhaps add it to your cache—if applicable).

**Comment by harianus** [comment] 2016-03-24 18:45
@BanzaiMan Bitbucket is cancelling the download indeed. That is why we are hosting another version. 

I improved the script of @fivetanley a little to allow caching.

```yml
cache:
  directories:
    - "travis-phantomjs"

before_install:
  - "phantomjs --version"
  - "mkdir travis-phantomjs && PHANTOM_EXISTS=false"
  - "if [ $PHANTOM_EXISTS = 'false' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $PHANTOM_EXISTS = 'false' ]; then tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs; fi"
  - "export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
```

Please use the cache method demonstrated above so our S3 bills would not be that high.

**Comment by BigAB** [comment] 2016-03-25 04:32
Not sure why it didn't work for me but the Phantom version did not change for me using the script/method @harianus posted above.

**Comment by harianus** [comment] 2016-03-30 11:53
@BigAB I updated the script above and tested it with clearing the Travis cache. The first time you run this script you will see the output of the last `phantomjs --version` as the wrong version, but the right one is installed.

**Comment by BanzaiMan** [comment] 2016-04-02 02:35
FYI: https://github.com/ariya/phantomjs/issues/13953

**Comment by jdalton** [comment] 2016-08-07 01:04
Any updates from the Travis-CI team on this?
It's less than 6 months until 2017 and it'd be great not to test in a Safari 5 (2010) environment (Phantom.js 1.x).

**Comment by tjwebb** [comment] 2016-08-31 15:33
+1

**Comment by popmonkey** [comment] 2016-09-30 18:20
+1

**Comment by froots** [comment] 2016-10-06 10:02
The [.travis.yml install steps](#issuecomment-200965782) above work fine, but it's neater to put it in a separate shell script. This worked well for me:

https://gist.github.com/froots/a9d48cb8b8320056f9bce4d3c193285a

**Comment by brettz9** [comment] 2016-10-22 01:50
@jdalton : You might want to update your post to indicate https://github.com/testdouble/present/blob/e4a8fb49029ad32c5682d17a64131aeddca86070/.travis.yml#L5-L16

**Comment by nathanl** [comment] 2017-03-08 16:08
> @BigAB I updated the script above and tested it with clearing the Travis cache. The first time you run this script you will see the output of the last phantomjs --version as the wrong version, but the right one is installed.

@harianus I observed this, too. I even saw that `$(which phantomjs) --version` was different from `phantomjs --version`, which I couldn't understand because they should both consult `$PATH`.

Then I remembered that the shell has a cache for where it finds commands. `hash -d phantomjs` says "forget where you found it before; look for it in `$PATH` again", and made it find the right one for me.

**Comment by harianus** [comment] 2017-03-08 16:29
Thanks, @nathanl, I [updated the script](https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-200965782) to include `hash -d phantomjs`.

**Comment by nathanl** [comment] 2017-03-08 16:50
@harianus Whoops, I had used `hash -d` in debug mode but not in `.travis.yml` as you show. That made my build fail. The line `- "hash -d phantomjs || true"` works though - it's like, "clear the cache if you can, and if not, don't worry about it."

**Comment by nathanl** [comment] 2017-03-09 14:48
If anybody is worried about downloading the phantomjs binary from an unfamiliar site, you could compare the checksum with the original one. Running `sha512sum phantomjs-2.1.1-linux-x86_64.tar.bz2` on the copy I get from `wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O phantomjs-2.1.1-linux-x86_64.tar.bz2` gives me `039b62ecf2fa4196357e129727871a53b046948e17b21900c78a1af4d0b523e41b9d4137e7454b0a638333d7fc27e65d14f4af8c665e982a504c12f828525419  officialphantomjs.tar.bz`.

If anyone else can replicate, please do.

**Comment by nathanl** [comment] 2017-03-09 20:11
Here's an installation method that automatically checks the downloaded binary's SHA512 against the one of the official package (as seen by me - others can confirm/deny that it's the correct SHA512).

```yaml
sudo: false

cache:
  directories:
    - "travis_phantomjs"

before_install:
  # Ensure we have newer version of PhantomJS to fix weird test failures from 1.9.8
  - export TRAVIS_PHANTOMJS_INSTALL_PATH="$PWD/travis_phantomjs"
  - export TRAVIS_PHANTOMJS_VERSION_NAME="phantomjs-2.1.1-linux-x86_64"
  - export PATH="$TRAVIS_PHANTOMJS_INSTALL_PATH/$TRAVIS_PHANTOMJS_VERSION_NAME/bin:$PATH"
  - hash -d phantomjs || true
  - echo "phantomjs version is $(phantomjs --version)"
  - if [ $(phantomjs --version) != '2.1.1' ]; then $PWD/bin/travis_get_updated_phantomjs; hash -d phantomjs || true; echo "updated phantomjs version is $(phantomjs --version)"; fi
```

It relies on the presence of `$PWD/bin/travis_get_updated_phantomjs`, which is this shell script, adapted from the solution @harianus provided:

```bash
#!/usr/bin/env bash
# Script to ensure we're using an updated version of PhantomJS when testing on Travis
set -e

if [ -z "$TRAVIS_PHANTOMJS_INSTALL_PATH" ]; then
  echo "must set env var TRAVIS_PHANTOMJS_INSTALL_PATH"
  exit 1
fi
if [ -z "$TRAVIS_PHANTOMJS_VERSION_NAME" ]; then
  echo "must set env var TRAVIS_PHANTOMJS_VERSION_NAME"
  exit 1
fi

BINARY_FILENAME="$TRAVIS_PHANTOMJS_VERSION_NAME.tar.bz2"
DOWNLOAD_FILENAME="$TRAVIS_PHANTOMJS_INSTALL_PATH/$BINARY_FILENAME"
BIN_PATH="$TRAVIS_PHANTOMJS_INSTALL_PATH/$TRAVIS_PHANTOMJS_VERSION_NAME/bin"
EXPECTED_SHA512="039b62ecf2fa4196357e129727871a53b046948e17b21900c78a1af4d0b523e41b9d4137e7454b0a638333d7fc27e65d14f4af8c665e982a504c12f828525419"

rm -rf $TRAVIS_PHANTOMJS_INSTALL_PATH
mkdir -p $TRAVIS_PHANTOMJS_INSTALL_PATH

echo "downloading requested phantomjs binary '$BINARY_FILENAME'"

# download from official location, or failing that, a mirror
# wget is availabile on MacOS via `brew install wget`
wget "https://bitbucket.org/ariya/phantomjs/downloads/$BINARY_FILENAME" -O $DOWNLOAD_FILENAME || wget "https://assets.membergetmember.co/software/$BINARY_FILENAME" -O $DOWNLOAD_FILENAME

# gsha512sum is available on MacOS via `brew install coreutils`
DOWNLOADED_SHA512=$((sha512sum $DOWNLOAD_FILENAME || gsha512sum $DOWNLOAD_FILENAME) | cut -d ' ' -f 1)

if [ "$DOWNLOADED_SHA512" == "$EXPECTED_SHA512" ]; then
  echo "download SHA confirmed - unpacking"
  tar -xvf "$DOWNLOAD_FILENAME" -C $TRAVIS_PHANTOMJS_INSTALL_PATH
  echo "sucessfully installed phantomjs in $TRAVIS_PHANTOMJS_INSTALL_PATH"
else
  echo "downloaded file had unexpected SHA512 $DOWNLOADED_SHA512"
  exit 1
fi

set +e
```

**Comment by BBonifield** [comment] 2017-03-24 17:33
@nathanl It looks like Travis is already using 2.1.1 by default on the `dist: trusty` instances.  I'm having the intermittent PhantomJS crashes with 2.1.1 as well.

**Comment by whit537** [comment] 2017-03-24 19:04
> It looks like Travis is already using 2.1.1 by default on the `dist: trusty` instances.

Really? I believe I am [seeing](https://travis-ci.org/gratipay/gratipay.com/builds/214761214#L303-L304) 2.0.0 [with](https://github.com/gratipay/gratipay.com/commit/63e4cbc6092ce897cfa87c0d5ea612dea33093c7) `dist: trusty`.

**Comment by BanzaiMan** [comment] 2017-10-07 03:12
As this issue calls for PhantomJS 2.0, I'm closing this.

Please note that 2.1.1 can also be downloaded from bitbucket.org (http://phantomjs.org/download.html), but this is subject to the rate limiting by bitbucket.org, as previously mentioned.

For the base image installation of PhantomJS, see https://github.com/travis-ci/travis-cookbooks/issues/910. When it is generally available, it should be announced in https://docs.travis-ci.com/user/build-environment-updates.

**Closed by BanzaiMan** 2017-10-07 03:12 UTC
Labels: travis-cookbooks
