### ISSUE TITLE
Postgres pg_config binary missing

### ISSUE THREAD

**Issue by chochkov** [travis-ci/travis-ci#7209] opened 2017-01-24 11:31 UTC
I'm trying to build this project `https://travis-ci.org/adjust/dumbo` which requires building a PostgreSQL extension at test-runtime. For that I need the `pg_config` binary that gets distributed with postgres. However the binary isn't there under `/usr/lib/postgresql/9.5/bin/` as I'd expect and the one found under `/usr/bin/pg_config` is from Postgres 9.6, which is useless as I can't start the 9.6. server.

Here's my config:

```yml
services:
  - postgresql

addons:
  postgresql: "9.5"

sudo: required
dist: precise
```

**Comment by BanzaiMan** [comment] 2017-01-26 02:50
Could you test the Trusty image?

**Comment by BanzaiMan** [comment] 2018-01-04 18:54
See https://github.com/travis-ci/travis-ci/issues/9011#issuecomment-355366295 and related comments. I'm closing this as a duplicate of it.

**Closed by BanzaiMan** 2018-01-04 18:54 UTC
