### ISSUE TITLE
Crystal macOS images: bad repository key fingerprint

### ISSUE THREAD

**Issue by olbat** [travis-ci/travis-ci#7894] opened 2017-06-12 08:31 UTC
For ~one week all my builds<sup>[1](https://travis-ci.org/olbat/libgen/jobs/241740993),[2](https://travis-ci.org/olbat/icu.cr/jobs/241127481)</sup> using TravisCI's macOS images (osx_image: `xcode8.3`) are failing with the following error:
```
Installing Crystal
gpg: directory '/Users/travis/.gnupg' created
gpg: keybox '/Users/travis/.gnupg/pubring.kbx' created
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
The repository key needed to install Crystal did not have the expected fingerprint. Your build was aborted.
/Users/travis/.travis/job_stages: line 341: shell_session_update: command not found
```
Is there anything I can do to get them working ?

/cc @asterite, @jhass, @waj and @will

**Comment by olbat** [comment] 2017-06-20 21:49
Bump

**Comment by olbat** [comment] 2017-06-29 14:04
https://github.com/crystal-lang/crystal/pull/4528

**Comment by olbat** [comment] 2017-07-04 17:42
see https://github.com/crystal-lang/crystal/issues/4648

**Comment by matiasgarciaisaia** [comment] 2017-07-07 17:09
The builds are no longer failing due to GPG, but Ubuntu 14.04 is not supported by 0.23.0 pre-built packages.

We're working on recovering that support in crystal-lang/crystal#4647, though.

**Comment by olbat** [comment] 2017-07-07 17:44
Are you sure ? I still got some GPG errors with my macOS builds<sup>[1](https://travis-ci.org/olbat/libgen/jobs/251189291),[2](https://travis-ci.org/olbat/libgen/jobs/251189295),[3](https://travis-ci.org/olbat/icu.cr/jobs/251188657)</sup> today ...

**Comment by matiasgarciaisaia** [comment] 2017-07-07 17:52
Sorry - I've confused this with Debian builds. I'll try to take a look at this next week.

**Comment by olbat** [comment] 2017-07-08 02:18
Thank you very much ! 👍

**Comment by matiasgarciaisaia** [comment] 2017-07-14 19:04
Hi @olbat!

Quickly looking at your build history, it seems the issue is not related with crystal-lang/crystal#4648 - it started _before_ we released 0.23.0 with the new GPG keys.

Specifically, the issue seems to be that `gpg` on OSX isn't showing the key's fingerprint as it seems to do on Linux (see [the relevant code](https://github.com/travis-ci/travis-build/blob/168dbbfb43dca8a5a6b0743066c5d55a68db6c69/lib/travis/build/script/crystal.rb#L16-L18)).

```
vagrant@debian-7:~$ gpg --with-fingerprint RPM-GPG-KEY 
gpg: directory `/home/vagrant/.gnupg' created
gpg: new configuration file `/home/vagrant/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/vagrant/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/vagrant/.gnupg/secring.gpg' created
gpg: keyring `/home/vagrant/.gnupg/pubring.gpg' created
pub  4096R/7CC06B54 2014-10-05 Crystal Distribution Signing <dist-sign@crystal-lang.org>
      Key fingerprint = 5995 C83C D754 BE44 8164  1929 0961 7FD3 7CC0 6B54
sub  4096R/F438C220 2014-10-05
```

```
mgarcia@macOS:~$ gpg --with-fingerprint RPM-GPG-KEY
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2014-10-05 [SC]
uid           Crystal Distribution Signing <dist-sign@crystal-lang.org>
sub   rsa4096 2014-10-05 [E]
```

So it seems we never intended the Travis script to work on OSX, **or** the `gpg` OSX command changed its output recently.

I haven't found how to print the fingerprint from a file on OSX. We should fix that file on Travis somehow (maybe importing the key, then `gpg --fingerprint KEY_ID`).

```
mgarcia@macOS:~$ gpg --fingerprint Crystal
pub   rsa4096 2014-10-05 [SC]
      5995 C83C D754 BE44 8164  1929 0961 7FD3 7CC0 6B54
uid           [ unknown] Crystal Distribution Signing <dist-sign@crystal-lang.org>
sub   rsa4096 2017-06-27 [S] [expires: 2021-06-27]
```

**Comment by olbat** [comment] 2017-07-14 22:19
Yes, it started before the 23.0 release (sry I didn't know the GPG key change was related to this release).

The version of the GPG tool may have recently changed in Travis CI's macOS images ?
I can't find anything on their blog, I'm not sure they communicate a lot about updates on this images ... I'll give it another look tomorrow.

**Comment by olbat** [comment] 2017-07-14 22:37
The daily test of one of my projects started to fail with this build [#204](https://travis-ci.org/olbat/libgen/builds/240397274), the last working one was this one [#203](https://travis-ci.org/olbat/libgen/builds/239990089) (from the day before).

**Comment by matiasgarciaisaia** [comment] 2017-07-14 23:04
I was discussing with Waj today that you don't actually _need_ the GPG keys for Crystal on OSX, since they are not being used. You can see at [#203](https://travis-ci.org/olbat/libgen/jobs/239990097) that all the apt-whatever commands fail, and then your script installs Crystal via Homebrew.

We should update the Travis script to check for the platform like your custom script, and do the GPG + apt dance for Linux, or brew install for OSX.

**Comment by olbat** [comment] 2017-07-15 08:10
> I was discussing with Waj today that you don't actually need the GPG keys for Crystal on OSX, since they are not being used. You can see at #203 that all the apt-whatever commands fail, and then your script installs Crystal via Homebrew.

I noticed that yes ...

> We should update the Travis script to check for the platform like your custom script, and do the GPG + apt dance for Linux, or brew install for OSX.

That would be very nice, thank you ! 👍

**Comment by olbat** [comment] 2017-07-15 15:37
Should I propose a PR in Crystal's repository or you prefer for the core team to work on this issue ?

**Comment by matiasgarciaisaia** [comment] 2017-07-15 16:30
The code that should be fixed is the one [on travis-ci/travis-build repo](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/crystal.rb). Feel free to send a PR there and mention us, so we can review it 👍

**Comment by olbat** [comment] 2017-07-15 19:59
Ok, I'll give it a try as soon as I can :)

Is there something such as a nightly build brew repository (something like `https://nightly.crystal-lang.org/apt`) ?

**Closed** 2017-07-28 17:51 UTC
Labels: community:crystal
