### ISSUE TITLE
Deployment can fail without failing the build

### ISSUE THREAD

**Issue by pmorie** [travis-ci/travis-ci#8569] opened 2017-10-11 14:39 UTC
It appears that the deployment can fail without failing the build that it's part of:

From https://travis-ci.org/kubernetes-incubator/service-catalog/builds/285930705:

```console
Preparing deploy

Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.

error: open(".kube/config"): Permission denied

fatal: Unable to process path .kube/config

Cannot save the untracked files
```

**Comment by BanzaiMan** [comment] 2017-10-11 23:56
Closing as a duplicate of #1574.

**Closed by BanzaiMan** 2017-10-11 23:56 UTC
