### ISSUE TITLE
Issues with SBT

### ISSUE THREAD

**Issue by joshk** [travis-ci/travis-ci#3140] opened 2015-01-23 18:15 UTC
Received this support email from a customer:

```
Hi, I've been using Travis CI with a Scala + Play Framework project. I've had strange issues with using SBT. When using SBT as described on your page on build Scala projects, I got unusual failures that contained no error messages. I eventually gave up on that because without an error message, there wasn't much to go on. The output in that case was:
$ jdk_switcher use default
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
$ export JVM_OPTS=@/etc/sbt/jvmopts
$ export SBT_OPTS=@/etc/sbt/sbtopts
$ java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
$ javac -version
javac 1.7.0_72

Using Scala 2.11.5
$ sbt test
Detected sbt version 0.13.5
:
/sbt-launch.jar
/sbt-launch.jar
/sbt-launch.jar

The command "sbt test" exited with 1.

As we can see, the only output there seems to be is a colon. I don't really know why.

I later tried to use the activator script that one would use to create (and often run) Play Framework programs. It's really just a wrapper to SBT. It initially failed:
$ jdk_switcher use default
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
$ export JVM_OPTS=@/etc/sbt/jvmopts
$ export SBT_OPTS=@/etc/sbt/sbtopts
$ java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
$ javac -version
javac 1.7.0_72

Using Scala 2.11.5
$ ./activator test
Error: Could not find or load main class @.etc.sbt.sbtopts

The command "./activator test" exited with 1.

This is because SBT_OPTS is set to `@/etc/sbt/sbtopts`. I don't understand this setting, considering that the SBT documentation uses that env var to store simply JVM options. And indeed, the solution to my problem was to override SBT_OPTS to the value in the link (SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M").

I'm not completely sure if this means something wrong on your end, but it seems like a very questionable value for SBT_OPTS. I'm also curious as to why the first attempt (using SBT directly) failed, particularly since Activator isn't doing anything special and SBT should be able to everything I need here. If SBT_OPTS is indeed what it's supposed to be, perhaps this workaround should be documented, as it seems to be necessary to run a Play Framework application (and this is a barebones Play Framework application -- we just got started).

Cheers,
Mike
```

@gildegoma your thoughts and ideas on this?

**Comment by gildegoma** [comment] 2015-01-23 20:12
### First Problem:

> ```
Using Scala 2.11.5
$ sbt test
Detected sbt version 0.13.5
:
/sbt-launch.jar
/sbt-launch.jar
/sbt-launch.jar
```
> As we can see, the only output there seems to be is a colon. I don't really know why.

This is quite odd. Are we sure that this is the complete log output?  Are we sure that `which sbt` still returns `/usr/local/bin/sbt` for this project?

Usually it should look like this:

```
$ jdk_switcher use openjdk7
Switching to OpenJDK7 (java-1.7.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-7-openjdk-amd64
$ export JVM_OPTS=@/etc/sbt/jvmopts
$ export SBT_OPTS=@/etc/sbt/sbtopts
$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
$ javac -version
javac 1.7.0_65
Using Scala 2.11.5
$ sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m check-gen-type-classes test
Detected sbt version 0.13.7
Downloading sbt launcher for 0.13.7:
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.7/sbt-launch.jar
    To  /home/travis/.sbt/launchers/0.13.7/sbt-launch.jar
Using jvm options defined in file /etc/sbt/jvmopts
# Executing command line:
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-Xmx3784m
-jar
/home/travis/.sbt/launchers/0.13.7/sbt-launch.jar
++2.11.5
check-gen-type-classes
test
```

----
### Second Problem:

> ```
$ ./activator test
Error: Could not find or load main class @.etc.sbt.sbtopts
```

In [JVM Travis CI environment](http://docs.travis-ci.com/user/languages/scala/#Projects-using-sbt), the default `/usr/local/bin/sbt` launcher script is [paulp/sbt-extras](https://github.com/paulp/sbt-extras), which is capable to auto-detect and auto-install the required version of SBT. In addition, this `sbt-extras` launcher also [supports to load SBT_OPTS and JVM_OPTS values from configuration files](https://github.com/paulp/sbt-extras/blob/master/sbt#L275).

In this case, typesafe `activator` script also uses the `SBT_OPTS` environment variable, but not the same way:

```
declare -r java_opts=( "${ACTIVATOR_OPTS[@]}" "${SBT_OPTS[@]}" "${JAVA_OPTS[@]}" "${java_opts[@]}" )
```

To properly run `./activator test`, I think that the following should be sufficient:

```yaml
language: scala

before_install: unset SBT_OPTS JVM_OPTS

script: ./activator test
```

**Comment by MikeHoffert** [comment] 2015-01-24 10:25
As requested in email, I created a public repo that demonstrates this problem. [Repo is here](https://github.com/MikeHoffert/TestPlayFrameworkSBT) and [Travis CI build is here](https://travis-ci.org/MikeHoffert/TestPlayFrameworkSBT).

**Comment by gildegoma** [comment] 2015-01-24 11:40
@MikeHoffert thanks for that public repo, it really helps a lot :heart: 

Problem 1 was indeed not fully clear with the log excerpt, as the plain logs are wrongly displayed in Travis Web UI. See the [raw logfile](https://s3.amazonaws.com/archive.travis-ci.org/jobs/48149529/log.txt):

```
Detected sbt version 0.13.5

Downloading sbt launcher for 0.13.5
:
  From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5
/sbt-launch.jar
    To  /home/travis/.sbt/launchers/0.13.5
/sbt-launch.jar
Download failed. Obtain the jar manually and place it at /home/travis/.sbt/launchers/0.13.5
/sbt-launch.jar
travis_time:end:080c57a5:start=1422095256494568106,finish=1422095256634980368,duration=140412262
[0K
[31;1mThe command "sbt test" exited with 1.[0m

Done. Your build exited with 1.
```

But this error is quite strange, because the failing URL http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar does respond well for me. 
@joshk Could it be a networking cache issue from the travis VMs?

@MikeHoffert If the download problem can be resolved, I suppose that using `sbt-extras` as sbt wrapper/launcher script should behave correctly as well. Later, I may create a second pull request to demonstrate it. But for the moment, please checkout the solution to problem 2, below...

-----

Problem 2 can be fixed as previously said, by unsetting `SBT_OPTS`. See https://github.com/MikeHoffert/TestPlayFrameworkSBT/pull/1

**Comment by gildegoma** [comment] 2015-01-24 13:00
@MikeHoffert I found the cause of Problem 1: `sbt-extras` script does not support Windows end-of-line format! 

See https://github.com/MikeHoffert/TestPlayFrameworkSBT/pull/2

**Comment by MikeHoffert** [comment] 2015-01-24 13:58
Nice catch, gildegoma. Can confirm that this fixes the issue. I'm going to add an issue to the `sbt-extras` project about this (the file in question was automatically generated, so presumably anyone who creates a Play Framework project on Windows will encounter this issue). I'm not sure if it will be resolved anytime in the near future, though, since there's an existing ticket regarding Windows that mentions lack of support for it.

**Comment by gildegoma** [comment] 2015-01-25 00:02
I created a pull request for `sbt-extras`: https://github.com/paulp/sbt-extras/pull/94

**Comment by ExNexu** [comment] 2015-01-28 23:03
Had the same issue with [ExNexu/spray-json-annotation](https://github.com/ExNexu/spray-json-annotation)
Removing the line break in `build.properties` fixed it for me: [commit](https://github.com/ExNexu/spray-json-annotation/commit/f019946a93dd3874745ac232bade7657da036da6#diff-148476c471986e89f6d9100118cb633d)

**Comment by gildegoma** [comment] 2015-01-29 06:15
@BanzaiMan I have a fixed version of `sbt-extras` script, is it still possible to include it into upcoming VM updates?

**Comment by gildegoma** [comment] 2015-01-29 08:54
@BanzaiMan The pull request has been merged in paulp/sbt-extras and I've updated the travis-cookbooks.

**Comment by BanzaiMan** [comment] 2015-02-13 05:02
This should be fixed by the recent Java environment update. Let us know if you still see problems.

**Closed by BanzaiMan** 2015-02-13 05:02 UTC
Labels: scala
