### ISSUE TITLE
'ping' command fails in the Trusty environment.

### ISSUE THREAD

**Issue by ProgVal** [travis-ci/travis-ci#8270] opened 2017-08-18 17:35 UTC
Hi,

When using Trusty, using `ping` results in this error: `ping: icmp open socket: Operation not permitted`.

This is likely to be caused by `ping` not having the setuid bit set ([related issue](https://github.com/travis-ci/travis-ci/issues/3080#issuecomment-68756505)).

**Comment by meatballhat** [comment] 2017-08-18 17:53
@ProgVal Are you intending to run on sudo-enabled?  The expected behavior in container-based environments is for setuid executables to be stripped of that bit, meaning `ping` _should not_ be usable.

**Comment by ProgVal** [comment] 2017-08-18 18:00
> Are you intending to run on sudo-enabled?

I could use sudo; but it's better for travis to use container-based envs performance-wise, right?

> The expected behavior in container-based environments is for setuid executables to be stripped of that bit, meaning `ping` _should not_ be usable.

Could you make a whitelist of safe binaries, that keep their setuid bit?

**Comment by meatballhat** [comment] 2017-08-18 18:10
If your job(s) tend to take more than ~4m, I recommend you use sudo-enabled as the execution time will generally be faster on that infrastructure.  I wouldn't worry too much about the relative expense :smiley:.

Keeping a safelist of binaries for which we allow setuid is not planned work, and I don't see us doing that any time soon given that we offer the sudo-enabled option.

**Comment by BanzaiMan** [comment] 2017-08-18 19:48
This is a duplicate of #3080, right?

**Comment by meatballhat** [comment] 2017-08-18 19:52
@BanzaiMan Looks that way to me 😃

**Closed by meatballhat** 2017-08-18 19:52 UTC
