### ISSUE TITLE
HHVM is no longer supported on Ubuntu Precise.

### ISSUE THREAD

**Issue by ShahrokhNiakan** [travis-ci/travis-ci#7827] opened 2017-05-31 10:50 UTC
I got this error on hhvm: 
HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
https://travis-ci.org/anetwork/validation/jobs/237868311

**Comment by BanzaiMan** [comment] 2017-05-31 12:10
A duplicate of #7712. Please use Trusty if you need HHVM.

**Closed by BanzaiMan** 2017-05-31 12:10 UTC
