### ISSUE TITLE
On Trusty, Rubies installed on demand lack bundler

### ISSUE THREAD

**Issue by cardil** [travis-ci/travis-ci#5578] opened 2016-02-05 10:58 UTC
Hello,

All builds running on virtual machines infrastructure provided by GCE are now failing with messages that there is no `bundler` installed. We are using it to test docker enabled builds that use beaker to run puppet acceptance tests:

```bash
rvm use 2.1 --install --binary --fuzzy
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
ruby-2.1.8 is not installed - installing.
# [..]
$ ruby --version
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
$ rvm --version
rvm 1.26.11 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'
$ gem --version
2.4.8
```

It was working fine yesterday.

Here are some failed build: https://travis-ci.org/coi-gov-pl/puppet-jboss/jobs/107172688

Yesterday it was working just fine: https://travis-ci.org/coi-gov-pl/puppet-jboss/jobs/106962038

This issue blocks our work, for example on PR https://github.com/coi-gov-pl/puppet-jboss/pull/55

**Comment by cardil** [comment] 2016-02-05 15:11
Another PR is blocked due to this error: coi-gov-pl/puppet-jboss#57

**Comment by BanzaiMan** [comment] 2016-02-05 17:10
Sorry about the issue. For now, as a workaround, you can install bundler in `before_install`.

```yaml
before_install:
  - gem install bundler
```

**Comment by BanzaiMan** [comment] 2016-02-11 00:14
Actually this is a duplicate of #3985, but I'm going to let this stand, since this contains a workaround, as well as a reference from a hot fix.

**Comment by BanzaiMan** [comment] 2016-02-11 00:32
The fix mentioned above has been deployed to production. Could you try it? You can retry an old failing build, or push a new commit.

**Comment by cardil** [comment] 2016-02-11 08:22
It has been fixed. Proof here: https://travis-ci.org/coi-gov-pl/puppet-jboss/jobs/108376314#L199-L208

However, the Ruby versions switched back to `2.1.7` from `2.1.8` for `2.1` alias. Is it ok? @BanzaiMan

**Closed** 2016-02-11 08:25 UTC
Labels: ruby

**Comment by BanzaiMan** [comment] 2016-02-11 17:38
@cardil The alias '2.1' → '2.1.8' was reverted, so, that's expected.

**Comment by sodabrew** [comment] 2016-02-24 23:29
There is still no "bundler" in the Ruby 2.3.0 RVM on Trusty images, however it is available on lower Ruby versions. Perhaps an incomplete fix?
