### ISSUE TITLE
wish: please add xcode image aliases

### ISSUE THREAD

**Issue by sitsofe** [travis-ci/travis-ci#9375] opened 2018-03-23 09:10 UTC
At the time of writing the OSX image versions look like this:

osx_image: xcode9.3beta
osx_image: xcode9.2
osx_image: xcode9.1
osx_image: xcode9
osx_image: xcode8.3 (Default)

As it would be useful to target both the default and latest images without perpetually changing `.travis` files it would be good if there were aliases like `xcodeunstablelatest`(which would currently point at `xcode9.3beta`) and `xcodestablelatest` (which currently would point at `xcode9.2`)..

**Comment by BanzaiMan** [comment] 2018-03-23 12:06
Duplicate of #8922.

**Closed by BanzaiMan** 2018-03-23 12:06 UTC
Labels: feature-request
