### ISSUE TITLE
Why does it take so long to extract the cache?

### ISSUE THREAD

**Issue by Trii** [travis-ci/travis-ci#3283] opened 2015-02-25 17:28 UTC
Each of my pro builds end up spending a long time setting up each directory that was previously cached.
![image](https://cloud.githubusercontent.com/assets/638073/6376096/ba96890c-bce9-11e4-8191-5a11d7bb3627.png)
Am I doing it wrong or is there something broken with the cache?

**Comment by rkh** [comment] 2015-02-25 17:29
Ouch. How large is your cache?

**Comment by rkh** [comment] 2015-02-25 17:32
Found your caches. They are not that large (~200 MB). Not sure what's going on. We shell out to the tar unix binary for extraction.

Would it be ok if we download one of your caches and try to extract them locally?

**Comment by Trii** [comment] 2015-02-25 17:33
@rkh please do!

**Comment by Trii** [comment] 2015-03-02 18:43
@rkh I was messing around locally with `tar` and it just seems like the google cloud sdk is massive. I'm not sure if it is worth caching or installing fresh every time. My latest iteration looks like so:

```cfg
install:
  - if [[ ! -f google-cloud-sdk/path.bash.inc ]]; then
      echo "Downloading google cloud sdk";
      wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip;
      unzip -qq google-cloud-sdk.zip;
      google-cloud-sdk/install.sh --usage-reporting false --path-update false --rc-path=~/.bashrc --bash-completion false --override-components app;
    fi;
  - google-cloud-sdk/bin/gcloud components update preview app --quiet
  - [[ -d google-cloud-sdk/.install/.backup ]] && rm -r google-cloud-sdk/.install/.backup

cache:
  directories:
    # this because it is slow to install...
    - google-cloud-sdk
```

**Comment by henrikhodne** [comment] 2015-04-20 12:54
I think I found the cause of this. The MTU on the machines that we use are 9001 by default. While I haven’t tried this particular download, several other reported slow downloads speed up a lot when I decrease the MTU to 1500 (including some from S3), so we’re going to change the MTU down to 1500 in order to improve the networking situation.

**Comment by Trii** [comment] 2015-04-20 12:58
Great, thank you! I'm trying to speed up the archiving my removing unnecessary data as well. Unfortunately the gcloud tool comes with a lot of things we don't use but can't exactly cherry pick.

**Comment by henrikhodne** [comment] 2015-04-28 22:00
We’ve deployed the change that reduces the MTU to 1500 as of about April 28th, 2015 at  4:00 UTC. Do things seem to download faster after that?

**Comment by Trii** [comment] 2015-04-28 23:35
I will check it out tomorrow and report our findings. Thanks!

**Comment by Trii** [comment] 2015-04-29 12:52
I'm testing with this build here: https://magnum.travis-ci.com/KAPx/kapx-courses/builds/11494827

If I restart the same build, will it use the same cache over and over or would I need to make a new push to the branch to get a true test of the difference?

**Comment by henrikhodne** [comment] 2015-04-29 12:56
There’s one cache per branch and matrix entry (if you have a single job in your build matrix, there’s one cache per branch). Every build on the same branch will try to get the same cache, so if you restart a build it will download the cache that was uploaded by the last build that ran on that branch.

**Comment by Trii** [comment] 2015-04-29 12:58
Great, thanks! Then I can keep restarting the same build then go back to one with caching off to check the difference. So far, so good.

**Comment by Trii** [comment] 2015-04-29 16:45
It still seems pretty slow whenever it has to do network IO. Even cloning from GitHub is taking 40s or more today.
https://magnum.travis-ci.com/KAPx/kapx-courses/builds/11497231

**Comment by BanzaiMan** [comment] 2015-07-13 19:10
Hi, @Trii, is this still an issue for you? We've recently changed the default compression algorithm to gzip, which should speed up this part. (It makes slightly larger archives, but the download speed difference should be minimal.)

**Comment by Trii** [comment] 2015-07-13 19:15
We have them down to a couple of minutes now but I haven't checked recently. I'll take a look!

**Comment by joshk** [comment] 2015-07-25 21:56
I'm going to close this issue for now as it looks like caching has improved dramatically recently.

Please open a new issue if you continue to run into problems.

Thank you.

**Closed by joshk** 2015-07-25 21:56 UTC
Labels: awaiting-followup, caching, containers, networking issue
