### ISSUE TITLE
Failed to query the list of test cases in the test bundle

### ISSUE THREAD

**Issue by armadsen** [travis-ci/travis-ci#5276] opened 2015-12-12 03:58 UTC
My builds are failing with:

>Failed to query the list of test cases in the test bundle: Test bundle not found at: <PathThatLooksReasonable>

This is a mixed Swift/Objective-C OS X framework project that includes a regular Xcode unit test target. I see the failure when specifying Xcode 7.1 or 7.2 in .travis.yml. The build itself works fine, it's the test phase that's failing. If I run xctool (0.2.7) locally using the exact same command as shown in the Travis log, everything works fine and the test phase passes.

I found #2179, which is an old issue about the same error. I explicitly added a `brew upgrade xctool` step to my .travis.yml, but that errored out because 0.2.7 is already installed.

Any ideas?

**Comment by BanzaiMan** [comment] 2016-04-27 08:47
Sorry for the delay. Closing as a duplicate of #3001.

**Closed by BanzaiMan** 2016-04-27 08:47 UTC
