### ISSUE TITLE
Old Android tools version is installed

### ISSUE THREAD

**Issue by WonderCsabo** [travis-ci/travis-ci#6059] opened 2016-05-16 16:33 UTC
The [documentation](https://docs.travis-ci.com/user/languages/android#Overview) says if we want to use the latest SDK, we should declare this in the [build config](https://github.com/WonderCsabo/maven-android-plugin/blob/fix-ci/.travis.yml#L9):
```yml
android:
  components:
    - tools
    - platform-tools
```

However, still a really old version is [installed](https://travis-ci.org/WonderCsabo/maven-android-plugin/builds/130608658#L316). The version installed is 24.4.1 (October 2015), but the latest version is [25.1.6](https://developer.android.com/tools/sdk/tools-notes.html).

**Comment by WonderCsabo** [comment] 2016-05-16 16:42
I guess the problem is that the bundled SDK version is really old, and can only "see" the 24.4.1 version when updating. The workaround is updating `tools` twice:
```yml
android:
  components:
    - tools
    - tools
    - platform-tools
```

**Comment by BanzaiMan** [comment] 2016-05-16 19:35
Duplicate of https://github.com/travis-ci/travis-ci/issues/6040. See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943.

**Closed by BanzaiMan** 2016-05-16 19:35 UTC
Labels: android

**Comment by WonderCsabo** [comment] 2016-05-16 19:38
Thanks! We found the same ingenuity it seems. 😆  Sorry for the duplicate, i searched for this but found no relevant issues for some reason.

**Comment by BanzaiMan** [comment] 2016-05-16 21:57
@WonderCsabo No worries! The next person who's perplexed my find this issue! :-)
