### ISSUE TITLE
Build logs not displaying on website

### ISSUE THREAD

**Issue by campagnola** [travis-ci/travis-ci#6811] opened 2016-11-01 20:49 UTC
Greetings,
I am getting empty job logs via the website for some of my builds. Example:
https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/172410344

Is there something I have done wrong? The logs appear empty even for passing builds.

**Comment by BanzaiMan** [comment] 2016-11-01 21:03
This is a duplicate of https://github.com/travis-ci/travis-ci/issues/6810.

We are having DB issues with the logs. Please follow on https://www.traviscistatus.com/incidents/lp492hx0z1my.

I'm closing this now.

**Closed by BanzaiMan** 2016-11-01 21:03 UTC
