### ISSUE TITLE
Timeout after successful build

### ISSUE THREAD

**Issue by auchri** [travis-ci/travis-ci#5935] opened 2016-04-20 17:26 UTC
One of our [build jobs](https://travis-ci.org/telegramdesktop/tdesktop/jobs/124469817) just failed because of "The job exceeded the maximum time limit for jobs, and has been terminated.".

But our build script exited before that message:

![image](https://cloud.githubusercontent.com/assets/5092164/14683958/be12c91c-072d-11e6-9905-6937cc451082.png)

**Comment by BanzaiMan** [comment] 2016-04-20 18:06
This is very curious. It might be a timing issue. Whilst the job ran for 48'33", it is close to the maximum time limit of 50 minutes. My guess would be that we started initiating shutdown, but your job finished before we completed the process.

How often does this happen?

**Comment by auchri** [comment] 2016-04-20 18:10
> How often does this happen?

I'm not entirely sure, but I think it happened for the first time.

**Comment by BanzaiMan** [comment] 2016-04-21 03:46
Could you try restarting it? If the job finishes sufficiently early, we should not see this error.

**Comment by weitjong** [comment] 2016-04-21 16:02
We also see this kind of problems. Here is one of them from our last build. https://travis-ci.org/urho3d/Urho3D/jobs/124770303. I want to log it as an issue but saw this one so I just comment here instead. We understand that the time limit should be 50 minutes but we have observed in many cases that the job error out a few minutes sooner than 50 minutes mark. We have just implemented a built-in interrupt mechanism which would terminate our build job at precisely 45 minutes and expect the remaining 5 minutes is enough to perform the after-script step like storing the cache objects. However, it seems we have to adjust our interrupt timer to cut off at sooner instead to counter the imprecision of Travis-build.

**Comment by auchri** [comment] 2016-04-25 10:26
@BanzaiMan we are building on linux and not on mac os x.

**Comment by weitjong** [comment] 2016-04-25 10:36
My apology. It appears I should have opened a new issue instead :smiley:

**Comment by BanzaiMan** [comment] 2017-05-17 11:36
Is this still a problem?

**Comment by auchri** [comment] 2017-05-17 12:22
Maybe, but we have not experienced more builds with that curious behavior because we decreased the build time.

**Comment by BanzaiMan** [comment] 2017-05-17 12:26
@auchri Thanks for the update. There is a similar issue reported in #7702, but I think the cause is probably different. I'm closing this one at this time.

**Closed by BanzaiMan** 2017-05-17 12:26 UTC
Labels: mac

**Comment by flpStrri** [comment] 2017-06-23 13:44
@BanzaiMan you got any updates on it? We are still having this problems on our builds.
