### ISSUE TITLE
Fast finishing does not seem to work with stages

### ISSUE THREAD

**Issue by akosyakov** [travis-ci/travis-ci#8425] opened 2017-09-14 08:43 UTC
I'm trying to configure fast finishing with stages:  https://github.com/theia-ide/theia/blob/aa1c5c19996123e8155b7c4aa7f57e7f5f62aea3/.travis.yml#L40-L44

In the way that the build should be marked as finished without the last stage running osx jobs. But travis does not seem to do it: https://travis-ci.org/theia-ide/theia/builds/275357453?utm_source=github_status&utm_medium=notification

**Comment by BanzaiMan** [comment] 2017-09-14 12:30
This is not working at the moment. I've added this to the beta-features issue above.

**Comment by tech-somish** [comment] 2018-08-21 05:43
This issue is still present.

**Comment by wagenet** [comment] 2018-09-12 00:37
I'm also frustrated by this.

**Comment by BanzaiMan** [comment] 2018-12-11 21:45
@jmalloc No. Your key is wrong. It is `allow_failures`, not `allowed_failures`. https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

**Comment by BanzaiMan** [comment] 2018-12-11 21:48
Duplicate of #9677, which is superseded by https://travis-ci.community/t/work-out-kinks-in-interactions-between-stages-allow-fail-and-fast-finish/1090.

**Closed by BanzaiMan** 2018-12-11 21:48 UTC
Labels: build stages

**Comment by jmalloc** [comment] 2018-12-11 22:39
> @jmalloc No. Your key is wrong. It is `allow_failures`, not `allowed_failures`. https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

:disappointed: How embarrassing! Thank you for pointing this out.
