### ISSUE TITLE
Artifact Addon 'unsupported protocol scheme ""' error

### ISSUE THREAD

**Issue by programatt** [travis-ci/travis-ci#9282] opened 2018-03-01 23:28 UTC
My `.travis.yml`

    language: python
    python:
      - "3.6"
    
    addons:
      artifacts:
        s3_region: "us-east-2"
        paths:
          - ./coverage.tar.gz
        debug: true
    install:
      - pip install -r requirements.txt
    
    script:
      - REUSE_DB=1 ./manage.py test
    
    after_success:
      - tar -cvzf coverage.tar.gz ./cover

Relevant Build Output:

    WARNING: invalid region, defaulting to us-east-2
      default: us-east-2
      region: us-east-2

    DEBUG: more artifact details
      bucket: mybucket
      cache_control: private
      content_type: application/x-gzip
      dest: mybucket/myacct/myproj/10/10.1/coverage.tar.gz
      max_size: 1.0GB
      percent_max_size: 0.009441471099853516
      source: /home/travis/build/myacct/myproj/coverage.tar.gz

    ERROR: failed to upload:  /home/travis/build/myacct/myproj/coverage.tar.gz

    err: Put /mybucket/myacct/myproj/10/10.1/coverage.tar.gz: unsupported protocol scheme ""

    Done uploading artifacts
    Done. Your build exited with 0.

**Comment by IGassmann** [comment] 2018-03-08 20:05
Same here https://travis-ci.org/RnDome/test_travis_artifacts/builds/252396698

**Comment by BanzaiMan** [comment] 2018-03-08 23:10
Duplicate of https://github.com/travis-ci/artifacts/issues/57. Choose a region that can use the V2 signature, or use the S3 deployment instead.

**Closed by BanzaiMan** 2018-03-08 23:10 UTC
