### ISSUE TITLE
Building Elixir projects on mac error

### ISSUE THREAD

**Issue by timCF** [travis-ci/travis-ci#5547] opened 2016-01-31 23:44 UTC
Config 

```
os:
  - linux
  - osx
language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
```

Gives error on build

```
/Users/travis/build.sh: line 45: lsb_release: command not found
/Users/travis/build.sh: line 45: lsb_release: command not found
```

Full log

```
Remove log Raw log
 worker_info
Worker information
hostname: worker-jupiter-brain:211f4869-29fa-453c-b6b6-7d3952b97851
version: v2.0.0 https://github.com/travis-ci/worker/tree/ca6cb0c5d3920912b1c3acc87c44a5da2120a971
instance: eca7cdc2-aa05-4efc-bcec-d337cf085cc7:
startup: 57.483449978s
system_info
Build system information
Build language: elixir
Build group: stable
Build dist: precise
git.checkout
2.00s$ git clone --depth=50 --branch=master https://github.com/timCF/wwwest.git timCF/wwwest
Cloning into 'timCF/wwwest'...
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 115 (delta 21), reused 0 (delta 0), pack-reused 77
Receiving objects: 100% (115/115), 20.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (57/57), done.
Checking connectivity... done.
$ cd timCF/wwwest
$ git checkout -qf 04a3cea822a075c9fca973579c0c54721a0bcac6
Setting environment variables from repository settings
$ export YANDEX_TOKEN=[secure]
18.2.1 is not installed. Downloading and installing pre-build binary.
1.00s$ wget https://s3.amazonaws.com/travis-otp-releases/binaries/$(lsb_release -is | tr "A-Z" "a-z")/$(lsb_release -rs)/$(uname -m)/erlang-18.2.1-nonroot.tar.bz2
/Users/travis/build.sh: line 45: lsb_release: command not found
/Users/travis/build.sh: line 45: lsb_release: command not found
--2016-01-31 23:28:53--  https://s3.amazonaws.com/travis-otp-releases/binaries///x86_64/erlang-18.2.1-nonroot.tar.bz2
Resolving s3.amazonaws.com... 54.231.9.168
Connecting to s3.amazonaws.com|54.231.9.168|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-01-31 23:28:54 ERROR 403: Forbidden.
```

**Comment by BanzaiMan** [comment] 2016-02-03 20:58
Erlang (and Elixir by extension) is not supported on Mac at this time.

This is a duplicate of https://github.com/travis-ci/travis-ci/issues/2315.

**Closed by BanzaiMan** 2016-02-03 20:58 UTC
