### ISSUE TITLE
Node.js (8.11.3 / 7.10.1) build uses wrong npm version (3.5.4)

### ISSUE THREAD

**Issue by Alexander-Krause** [travis-ci/travis-ci#9798] opened 2018-06-25 14:39 UTC
Hi,

since a few days ago we have problems with our nodejs / ember.js build. The npm version does not fit the nodejs version, e.g., `NodeJS 8.11.3` and `npm 3.5.4`. The same behavior is reproducible with `NodeJS 7.10.1`.

But here comes the weird thing. On the first run with a newly added (.travis.yml) nodejs version, the build succeeds. A second execution of the build fails, since it now uses a different npm version. See the following examples:

https://travis-ci.org/ExplorViz/explorviz-frontend/jobs/396402806

https://travis-ci.org/ExplorViz/explorviz-frontend/jobs/396424726

I don't think nvm is the problem, since the build succeeds on the first run. Local builds succeed, since they use the correct npm versions (5.6.0 / 4.2.0).

**Comment by BanzaiMan** [comment] 2018-09-06 15:09
Hello, there.

Looks like your build was (is still?) [installing npm 3.5.4](https://travis-ci.org/ExplorViz/explorviz-frontend/jobs/396402806#L1275) during `npm install`. This would be included in your cache, and I suspect this is the cause of your build woes.

**Comment by BanzaiMan** [comment] 2018-09-29 04:43
Recent builds seem passing. I'm closing this now.

**Closed by BanzaiMan** 2018-09-29 04:43 UTC
Labels: caching, node.js
