### ISSUE TITLE
There was an error while loading data | Repository settings

### ISSUE THREAD

**Issue by vishrutshah** [travis-ci/travis-ci#7835] opened 2017-06-01 17:54 UTC
Hello @BanzaiMan,

I am having trouble seeing the setting on only one repository. https://travis-ci.org/Azure/azure-rest-api-specs/settings It says `There was an error while loading data` since yesterday.

I tried logout/login again and from multiple browser it does not work. I am not sure who is the right person to contact. Feel free to redirect if possible. 

Thanks,

**Comment by davidtw** [comment] 2017-06-01 19:51
Hey,

I have the same issue https://travis-ci.org/davidtw/home-dashboard/settings

Thanks!

**Comment by BanzaiMan** [comment] 2017-06-01 20:29
This is very likely a duplicate of https://github.com/travis-ci/travis-ci/issues/7831. Please either try a manual fix shown in https://github.com/travis-ci/travis-ci/issues/7831#issuecomment-305604425, or if it doesn't work, send us email. Thanks.

I'm closing this as a duplicate.

**Closed by BanzaiMan** 2017-06-01 20:29 UTC

**Comment by vishrutshah** [comment] 2017-06-01 22:09
@BanzaiMan I tried the fix shown in the comment with no success. I was in the bucket 2a. It still shows message `There was an error while loading data`. Let me know where should i send an email, please. Thanks!

**Comment by BanzaiMan** [comment] 2017-06-01 22:13
The email address is support@travis-ci.com.
