### ISSUE TITLE
Error after release deployment on github

### ISSUE THREAD

**Issue by reyman** [travis-ci/travis-ci#6096] opened 2016-05-23 14:13 UTC
Hi,

https://travis-ci.org/gama-platform/gama/builds/132293259

Sometime build failed with this error after upload : 

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/gama-platform/gama/releases/3254194/assets?name=msi.gama.application.product-1.7.0-SNAPSHOT-macosx.cocoa.x86_64.zip: 502 - Error uploading asset (Octokit::BadGateway)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:130:in `upload_file'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:115:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider.rb:143:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/provider.rb:143:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.16/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy

```

**Comment by BanzaiMan** [comment] 2016-05-23 17:11
This is an error from GitHub. I am not sure if we can troubleshoot much beyond this. How often does it happen? Does restart fix the issue?

**Comment by BanzaiMan** [comment] 2016-05-28 03:28
Duplicate of https://github.com/travis-ci/travis-ci/issues/6068, which I reopened.

**Closed by BanzaiMan** 2016-05-28 03:28 UTC
Labels: deployment
