### ISSUE TITLE
XCode7 logs are cut off

### ISSUE THREAD

**Issue by d-frey** [travis-ci/travis-ci#4932] opened 2015-10-13 15:59 UTC
Title says it all. Running on XCode7, the log is cut off and causing me problems. Example of where it fails:

https://travis-ci.org/taocpp/sequences/jobs/85055339 (scroll to the end)

On XCode6 (or Linux), it does not happen:

https://travis-ci.org/taocpp/sequences/jobs/85055336 (scroll to the end)

**Comment by mattyohe** [comment] 2015-10-13 18:03
@d-frey Assume this is related to #4716

**Comment by BanzaiMan** [comment] 2015-10-19 14:06
Thanks for opening this issue. I'm closing this as a duplicate of #4716.

**Closed by BanzaiMan** 2015-10-19 14:06 UTC
