### ISSUE TITLE
"hg clone https://bitbucket.org/shlomif/quad-pres" - hg clone from bitbucket is failing on the trusty workers

### ISSUE THREAD

**Issue by shlomif** [travis-ci/travis-ci#8859] opened 2017-12-04 11:57 UTC
See  https://travis-ci.org/shlomif/shlomi-fish-homepage/builds/311065315 - the hg clone is working fine locally here on mageia v7 x86-64. Please look into fixing it.

**Comment by BanzaiMan** [comment] 2017-12-04 17:33
Sounds like a duplicate of #8843.

**Comment by BanzaiMan** [comment] 2017-12-05 19:24
`hg clone` issues a warning, but the `clone` itself should work. https://travis-ci.org/BanzaiMan/travis_production_test/builds/312030174#L1449 If your build is failing, it is failing for a different reason.

**Comment by shlomif** [comment] 2017-12-05 19:48
@BanzaiMan : hi! quoting from the log -

```
+hg clone https://bitbucket.org/shlomif/quad-pres mygit

warning: connecting to bitbucket.org using legacy security technology (TLS 1.0); see https://mercurial-scm.org/wiki/SecureConnections for more info

applying clone bundle from https://api.media.atlassian.com/file/a6cdd1fe-a153-49a2-8baa-6cc68bd80294/binary?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzMTE3MWRjMC0wYWNiLTRhMGQtODg1NS00NzEyNDEyOGRhZWMiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmE2Y2RkMWZlLWExNTMtNDlhMi04YmFhLTZjYzY4YmQ4MDI5NCI6WyJyZWFkIl19LCJuYmYiOjE1MTIzODY3NzMsImV4cCI6MTUxMjM4NzE5M30.a4fKqK3Ok9G95xwxeZT5SX42qINh6Widw9NvdnHVjGY&client=31171dc0-0acb-4a0d-8855-47124128daec

warning: connecting to api.media.atlassian.com using legacy security technology (TLS 1.0); see https://mercurial-scm.org/wiki/SecureConnections for more info

abort: api.media.atlassian.com certificate error: certificate is for *.atlassian.io, atlassian.io

(set
```

notice the "abort:"

**Comment by BanzaiMan** [comment] 2017-12-05 20:06
https://travis-ci.org/BanzaiMan/travis_production_test/builds/312048213#L1437

Your invocation appear to be more strict, then.

**Comment by shlomif** [comment] 2017-12-06 10:57
@BanzaiMan : thanks for your help and insights. Thanks to that, I found out it only happens after I do "apt-get install mercurial" and removing that fixes the problem. I'm fine with you closing this issue report.

**Comment by BanzaiMan** [comment] 2017-12-06 13:15
Thanks for the update. I suppose the updated package has a more restrictive default.

I'm closing this.

**Closed by BanzaiMan** 2017-12-06 13:15 UTC
