### ISSUE TITLE
Regression: PECL no longer available on PHP7 machines

### ISSUE THREAD

**Issue by tedivm** [travis-ci/travis-ci#5250] opened 2015-12-08 06:42 UTC
Similar to #4800 

```
rbenv: pecl: command not found
The `pecl' command exists in these PHP versions:
  5.2
  5.2.17
  5.3
  5.3.29
  5.3.3
  5.4
  5.4.37
  5.5
  5.5.21
  5.5.9
  5.6
  5.6.5
```

From [this job](https://travis-ci.org/tedious/Stash/jobs/95514528).

**Comment by BanzaiMan** [comment] 2015-12-08 08:34
Thanks for opening this issue. This is a duplicate of #5207. I'll close this as a duplicate.

**Closed by BanzaiMan** 2015-12-08 08:34 UTC
