### ISSUE TITLE
travis-build: container addon: apt: support  for update-alternatives

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/travis-ci#3757] opened 2015-04-24 01:11 UTC
Updating to different gcc/g++ versions, and uses of update-alternatives require sudo. A good example of use is https://github.com/travis-ci/travis-ci/issues/1379#issuecomment-34530988

With containers prohibiting sudo can update-alternatives form part of the yaml syntax:

e.g. - my current config is https://github.com/openquery/mariadb-server/blob/be279f850c1d79607bc01d2be127a5072aee8036/.travis.yml

A container build could start like:
<pre>
sudo: false

language: cpp
compiler:
  - gcc
  - clang
cache:
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mariadb-10
    packages:
      - gcc-4.9
      - g++-4.9
      - binutils
      - libjemalloc-dev
      - zlib1g-dev
      - libbz2-dev
      - libsnappy-dev
      - libtool
      - libncurses5-dev
      - perl
      - libwrap0-dev
      - zlib1g-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - libpam0g-dev
      - psmisc
      - po-debconf
      - chrpath
      - automake1.9
      - doxygen
      - texlive-latex-base
      - ghostscript
      - dpatch
      - gawk
      - bison
      - lsb-release
      - libaio-dev
      - devscripts
      - libevent-dev
      - sphinxsearch
    update-alternatives:
       - install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
       - install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
    packages:
      - hardening-wrapper
    sources:
      - trusty
    packages:
      - binutils
</pre>

late note: the hardening-wrapper requires the alternative are in place hence the ordering.

**Comment by SethTisue** [comment] 2015-04-27 21:04
duplicate of #3668

**Comment by kamalmarhubi** [comment] 2015-05-28 19:27
Should this be closed as a duplicate?

**Closed** 2015-05-28 19:42 UTC
