### ISSUE TITLE
Document language: generic

### ISSUE THREAD

**Issue by annevk** [travis-ci/travis-ci#7152] opened 2017-01-14 08:38 UTC
That you can set language to generic in .travis.yml isn't documented. It probably should be.

**Comment by BanzaiMan** [comment] 2017-01-14 13:11
Thanks for taking the time to open this issue. I'm closing this as a duplicate of https://github.com/travis-ci/docs-travis-ci-com/issues/910.

**Closed by BanzaiMan** 2017-01-14 13:11 UTC
