### ISSUE TITLE
Avoid duplicate builds caused by same commit hash within small time window

### ISSUE THREAD

**Issue by isiahmeadows** [travis-ci/travis-ci#7074] opened 2016-12-23 23:38 UTC
Say, I tag a commit as `v0.3.1`, and I push both the commit and its tag. It'd be nice if that could be deduplicated within the project, so I only have one build, not two, for the two separate events.

Additionally, if I have a pull request based on a branch within the repo (e.g. `fix-12345` &rarr; `master`), I'd prefer that could also be similarly deduplicated between the pull request and the raw push itself, instead of doing two separate identical builds for two separate commits.

It doesn't have to be on by default (not everyone has reproducible builds), but merely the option would be a big time saver by being less spammy.

Obviously, as I mentioned in the title, it needs to only be done in a small time window, because you don't want an identical hash down the line not being built a month later, just spammy duplicate hashes within a few minutes deduplicated.

**Comment by BanzaiMan** [comment] 2016-12-24 01:12
I'm closing this as a duplicate of #2200.

**Closed by BanzaiMan** 2016-12-24 01:12 UTC
