### ISSUE TITLE
Skip PR build with Github PR label

### ISSUE THREAD

**Issue by bjorncs** [travis-ci/travis-ci#8278] opened 2017-08-21 12:22 UTC
Hi,

It would be great to be able to skip a PR build by adding a specific label to the Github pull request, e.g. _skip-ci_ or _ci-skip_. I would prefer a label on the PR over adding a _[ci-skip]_ to the commit messages.

Thanks.

**Comment by BanzaiMan** [comment] 2017-08-21 12:41
Duplicate of #5374.

**Closed by BanzaiMan** 2017-08-21 12:41 UTC
