### ISSUE TITLE
npm deploy issue

### ISSUE THREAD

**Issue by gyzerok** [travis-ci/travis-ci#4738] opened 2015-09-02 07:32 UTC
After moving my npm publish process to travis I've ended up with npm install problems. To reproduce error you can just do ```npm i adrenaline@0.4.0```. For the old versions which I've published with my own all is ok ```npm i adrenaline@0.2.0```.

**Comment by BanzaiMan** [comment] 2015-09-02 12:37
Could you point to the failed deployment?

**Comment by gyzerok** [comment] 2015-09-02 14:08
@BanzaiMan You can check deploy for [this buid](https://travis-ci.org/gyzerok/adrenaline/builds/78018298).

**Comment by BanzaiMan** [comment] 2015-09-02 14:23
You are deploying from all branches, so the first job in the build matrix to finish will upload to npm (https://travis-ci.org/gyzerok/adrenaline/jobs/78018303#L590), and the subsequent ones (https://travis-ci.org/gyzerok/adrenaline/jobs/78018299#L589 https://travis-ci.org/gyzerok/adrenaline/jobs/78018301#L590) fail.

You should restrict your deployment to exactly one (http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A) to avoid errors. (If you don't care about which branch uploads, and can ignore the errors, you don't have to do this.)

**Comment by BanzaiMan** [comment] 2015-09-02 14:36
I don't know what is causing the checksum error, though. Did npm upload a faulty package? Or does subsequent uploads mangle the checksum, even thought they failed?

**Comment by gyzerok** [comment] 2015-09-02 14:48
@BanzaiMan I would try to change multiple deploy branch to a single branch. Hope it would help. Let me come tomorrow with the results.

Thank you for helping!

**Comment by BanzaiMan** [comment] 2015-09-02 14:56
If deploying from a single branch helps (which I believe will), it seems to me that there is something wrong with the way npmjs.org handles multiple upload attempts.

**Comment by gyzerok** [comment] 2015-09-03 06:00
@BanzaiMan Issue solved with one-branch deploy. It would be nice to mention it in the docs.

**Comment by BanzaiMan** [comment] 2015-09-04 01:45
What should be documented?

**Comment by gyzerok** [comment] 2015-09-08 15:31
@BanzaiMan this case I guess. How anyone else should get this?

**Comment by BanzaiMan** [comment] 2015-09-08 15:34
Conditional release is already documented. It is not clear to me how the checksum got corrupted; is it possible that a second upload attempt did? Have you contacted npmjs.org support?

**Comment by kbrock** [comment] 2015-10-05 19:03
It seems that the problem is on npm's side.

Does anyone have a fix? I did find https://github.com/npm/npm/issues/9574#issuecomment-139940172

**Comment by BanzaiMan** [comment] 2015-11-24 02:34
Is there anything to do on our end?

**Comment by kbrock** [comment] 2015-11-24 04:38
@BanzaiMan I am not sure. Think this may have to do with npm's infrastructure and bad proxy servers. So it would seem to be a non-travis issue. But it is happening way too often to just say "not travis".

**Comment by BanzaiMan** [comment] 2015-12-18 13:32
I've documented this with https://github.com/travis-ci/docs-travis-ci-com/commit/ffed550c73780b404bb596f6d185a19f1ab2d43e. We are happy to look into this issue if the deployment from a single job continues to cause problems. In the meantime, I'm closing this.

**Closed by BanzaiMan** 2015-12-18 13:32 UTC
Labels: deployment

**Comment by kbrock** [comment] 2015-12-18 20:05
@BanzaiMan thanks
