### ISSUE TITLE
allow to link to newest build on master branch

### ISSUE THREAD

**Issue by tooomm** [travis-ci/travis-ci#8585] opened 2017-10-13 15:52 UTC
I realized that in your badge you give the option to show a status for a particular branch, but the link will always point to the very general page with the most recent build shown. That's confusing for the user!

AppVeyor solved it like this:
`https://ci.appveyor.com/project/OWNER/REPO/branch/master`

**Comment by BanzaiMan** [comment] 2017-10-13 18:08
A duplicate of #5024.

**Closed by BanzaiMan** 2017-10-13 18:08 UTC
