### ISSUE TITLE
Feature request: ETA for queued OSX jobs

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8417] opened 2017-09-13 22:56 UTC
Since Travis-CI.org seems to be limited to running 180 Mac OS X jobs at a time, and the backlog seems to extend to at least a few hours during daytime in the Americas, it would be handy if the status page for a queued OS X job would show a rough estimate of how much longer it was going to wait to start.

**Comment by Safihre** [comment] 2017-09-15 09:11
Indeed. We know resources are limited for free builds and we appreciate all we can get, but some indication of ETA or the number of jobs  that are ahead of the current job in the queue?

**Comment by BanzaiMan** [comment] 2017-09-19 12:43
Closing as a duplicate of #6598.

**Closed by BanzaiMan** 2017-09-19 12:43 UTC
Labels: feature-request

**Comment by jleni** [comment] 2018-04-15 09:35
The duplicate has also been close so there is no issue tracking this feature request.
Could you reopen this? I think it is an important and useful feature given the time it takes for OSX builds to start
