### ISSUE TITLE
Update pypy3 to 5.2

### ISSUE THREAD

**Issue by scop** [travis-ci/travis-ci#6277] opened 2016-07-07 13:55 UTC
The PyPy3 available in Travis is version 2.4.0, corresponding to Python 3.2.x. PyPy 5.2 which corresponds to Python 3.3.5 is out; it would be good to upgrade to be able to add pypy3 back to the test matrix of quite a few projects that have dropped Python 3.0-3.2 support.

**Comment by BanzaiMan** [comment] 2016-07-11 20:35
The build image needs an update, but in the meantime, you can use:

```yaml
pyton:
  - pypy-5.3.1
```

**Comment by scop** [comment] 2016-07-12 07:23
@BanzaiMan Please note that I'm requesting an update to pypy3, not pypy. PyPy 5.3.1 is the Python 2.7 compatible version (known in Travis as pypy); I'm requesting an update the the Python 3 compatible version (known in Travis as pypy3), the latest version of which at the moment is 5.2-alpha.

See http://pypy.org/download.html

**Comment by BanzaiMan** [comment] 2016-07-12 11:35
PyPy3 5.2 alpha1 cannot install `pip`, so it is unusable. https://travis-ci.org/travis-ci/cpython-builder/jobs/143970422

**Comment by scop** [comment] 2016-07-12 12:37
The tracebacks contain lots of paths starting with `/usr/local/lib/python2.7/` (local Python version 2.x). Is it intentional that PyPy3 ends up using modules from hose dirs? Sounds wrong to me on first sight.

**Comment by BanzaiMan** [comment] 2016-07-12 12:46
That is where `virtualenv` is installed.

**Comment by scop** [comment] 2016-07-12 12:54
So is it actually virtualenv that is failing? If not, having a pypy3 build actually run code from an obsolete pip version (7.1.0, see the paths in the log, current is 8.1.2) from a Python 2.x setup path really sounds like something's wrong with the build to me.

**Comment by BanzaiMan** [comment] 2016-07-12 12:56
Could very well be. We rely on https://github.com/yyuu/pyenv/tree/master/plugins/python-build/share/python-build for that build.

**Comment by jayvdb** [comment] 2016-07-12 13:02
Ping @yyuu ;-)

**Comment by jayvdb** [comment] 2016-07-12 14:09
pyenv has a "pypy3.3-5.2-alpha1" environment, added in https://github.com/yyuu/pyenv/commit/aed0eaecebc

I can reproduce the error, using virtualenv<13.

https://travis-ci.org/jayvdb/pyenv/jobs/144168674#L242

But it doesnt occur with virtualenv 15.0.2

**Comment by jayvdb** [comment] 2016-07-12 18:42
The following works ok, with `VERSION=pypy3.3-5.2-alpha1` in the repository settings.

https://github.com/jayvdb/cpython-builder/compare/4b9566...7d35bef

https://travis-ci.org/jayvdb/cpython-builder/builds/144234801

That upgrades virtualenv to 15.0.2 for all python venvs; maybe you would prefer it to only occur for the custom pypy3 venvs.

But then I am not sure whether the generated venv is going to work OK on the workers.

**Comment by BanzaiMan** [comment] 2016-07-12 20:00
Very interesting. I was able to package PyPy3.3-5.2-alpha1. https://travis-ci.org/travis-ci/cpython-builder/builds/144267014

It should be available for use now.

**Comment by scop** [comment] 2016-07-12 20:40
Cool, `pypy3.3-5.2-alpha1` in `.travis.yml` gets it. Until `pypy3` is upgraded to it, could this be made available e.g. as `pypy3.3`?

Just one observation from my test build log; an error message from `rm` (see that tarball name it is trying to remove):
```
[...]
pypy3.3-5.2-alpha1 is not installed; attempting download
rm: cannot remove `5.2-alpha1.tar.bz2': No such file or directory
[...]
```

**Comment by BanzaiMan** [comment] 2016-07-12 20:43
You can ignore the error message for now.

**Comment by edmorley** [comment] 2016-08-06 00:43
> Just one observation from my test build log; an error message from rm (see that tarball name it is trying to remove):

This will be fixed by travis-ci/travis-build#814 :-)

**Comment by BanzaiMan** [comment] 2016-09-03 04:19
PyPy3 5.2 alpha1 is now available. When a newer version is available, we can create a newer package.

Closing this for now.

**Closed by BanzaiMan** 2016-09-03 04:19 UTC
Labels: python, team blue, travis-cookbooks, upgrade-request

**Comment by ofek** [comment] 2016-11-12 17:00
@BanzaiMan Now that a few months have passed, how should one use pypy3 in .travis.yml?

**Comment by lrq3000** [comment] 2016-12-06 11:36
[pypy3 on Travis is currently broken](https://travis-ci.org/tqdm/tqdm/jobs/181600081), because it is still by default the old pypy3 based on Python 3.2.5, and setuptools recently dropped support for Python 3.0 - 3.2.

I think the pypy3 5.2 alpha1 should be set as default now (since the current pypy3 can only fail), don't you think?

```
/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
setuptools requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.5
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/travis/build/t....tox/pypy3/bin/pypy3 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /opt/python/pypy3-2.4.0/bin/pypy3
```

**Comment by tseaver** [comment] 2016-12-16 15:53
@BanzaiMan I don't believe this issue should be closed:  tox- / virtualenv-based Travis builds using `pypy3` are going to fail until the default version is updated.

**Comment by peterjc** [comment] 2017-02-08 18:53
Since PyPy3 v5.2 alpha 1 was released the PyPy team have released pypy3 v5.5.0:

https://morepypy.blogspot.co.uk/2016/10/pypy3-550-released.html
http://doc.pypy.org/en/latest/release-pypy3.3-v5.5.0.html

This ought to solve the pip/venv/setuptools etc problems in using ``pypy3`` under TravisCI?

**Comment by neilsh** [comment] 2017-05-26 23:24
From my own experimentation with Travis, the latest target that actually builds properly is `pypy3.3-5.5-alpha`. I've also tried `pypy3.5-5.7.1-beta` (since it's listed in pyenv), but I get the following error:

https://travis-ci.org/hhatto/autopep8/jobs/236547978
```[0K[33;1mpypy3.5-5.7.1-beta is not installed; attempting download[0m
[33;1mDownloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/pypy3.5-5.7.1-beta.tar.bz2[0m
$ sudo tar xjf pypy3.5-5.7.1-beta.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

[31;1mThe command "sudo tar xjf pypy3.5-5.7.1-beta.tar.bz2 --directory /" failed and exited with 2 during .[0m

Your build has been stopped.```

**Comment by ofek** [comment] 2017-05-26 23:45
Pre-built works fine https://github.com/biopython/biopython/blob/ae89947c158551a0c908614dfe7ed4b5e0efb458/.travis.yml#L72
