### ISSUE TITLE
Showing the time from start to end not the time spent on the history list

### ISSUE THREAD

**Issue by MiguelMadero** [travis-ci/travis-ci#9177] opened 2018-02-03 21:03 UTC
Today the time shows the total time spend: 

![image](https://user-images.githubusercontent.com/47388/35771505-8d616644-08e2-11e8-8e68-202e3e857d38.png)

That could be useful if we needed to know the total compute time. However, we often want to know how much we had to wait for a successful build. That information is only available in the details: 

![image](https://user-images.githubusercontent.com/47388/35771499-7a041236-08e2-11e8-9f1f-dad917c171fb.png)

Also, in case of Allowed Failures, I think it should exclude that if that step was the slowest.

**Comment by BanzaiMan** [comment] 2018-02-03 21:10
Duplicate of #1486.

**Closed by BanzaiMan** 2018-02-03 21:10 UTC
