### ISSUE TITLE
SSLException when using openjdk7 on trusty distribution

### ISSUE THREAD

**Issue by wangjoshuah** [travis-ci/travis-ci#8503] opened 2017-09-26 22:30 UTC
I'm not sure if I'm missing something obvious here, but I have a build failure on `trusty` when using `openjdk7`. According to the travis [docs on trusty](https://docs.travis-ci.com/user/reference/trusty), you should be able to use `openjdk7`.

I'm getting an error on travis, that I am not able to get locally. Is it a network issue with the travis ci system?
```
Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
```

Travis logs can be found [here](https://travis-ci.org/optimizely/java-sdk/jobs/279755651).
The repo is open source so feel free to poke around at the .yml file as well or any other settings.

**Comment by BanzaiMan** [comment] 2017-09-28 07:27
Issues such as https://github.com/facebook/react-native/issues/14091 and https://github.com/mesosphere/hdfs-deprecated/issues/141#issuecomment-115440894 suggest that using Java 8 might help. Is there a reason that you want to stick with Java 7?

**Comment by wangjoshuah** [comment] 2017-09-28 17:50
I know that Java 7 is no longer the standard and that Oracle pulled support in 2015, but we still want to ensure that our SDK is compatible with Java 7 in case any users out there might not be able to upgrade to Java 8 for various reasons.

**Comment by BanzaiMan** [comment] 2017-09-28 21:58
Unless the tool is supported with Java 7, I don't think there is much we can do here. Is it?

**Comment by javabrett** [comment] 2017-10-27 11:14
* This issue is probably impacting a reasonable number of projects - at least any that are running on the Trusty image, using Gradle with the Gradle Wrapper, and wanting to build with JDK7, which since https://github.com/travis-ci/travis-ci/issues/7884 requires `openjdk7` instead of `oraclejdk7`.
* Root cause seems to be openjdk7 ceasing to ship the `SunEC` crypto provider, combined with the strong algorithms used on the Gradle download sites.
* A few options to fix, including running Gradle with a different JDK, or installing BouncyCastle JCE provider.

Here's a demonstration of the problem and a candidate solution using a Docker build on the ubuntu:14.04 base.

# Dockerfile

```
FROM ubuntu:14.04
MAINTAINER Brett Randall <javabrett@gmail.com>

RUN apt-get update && apt-get install -y zip curl locate openjdk-7-jdk libbcprov-java

RUN mkdir /gradle
WORKDIR /gradle

RUN curl -vLO http://services.gradle.org/distributions/gradle-4.2.1-bin.zip
RUN unzip gradle-4.2.1-bin.zip

# install gradle wrapper
RUN gradle-4.2.1/bin/gradle wrapper --gradle-version 4.2.1

# this will fail with EC crypto errors, return true to continue
RUN ./gradlew tasks || true

# install BouncyCastle provider
RUN ln -s /usr/share/java/bcprov.jar /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/bcprov.jar \
        && awk -F . -v OFS=. 'BEGIN{n=2}/^security\.provider/ {split($3, posAndEquals, "=");$3=n++"="posAndEquals[2];print;next} 1' /etc/java-7-openjdk/security/java.security > /tmp/java.security \
        && echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" >> /tmp/java.security \
        && mv /tmp/java.security /etc/java-7-openjdk/security/java.security

```
The run the container `docker run -it --rm travis-8503:latest /bin/bash` and `./gradlew tasks` will now work and the wrapper can download http://services.gradle.org/distributions/gradle-4.2.1-bin.zip

**Comment by javabrett** [comment] 2017-10-27 11:19
See also solution in https://github.com/eseifert/gral/issues/161 and https://github.com/eseifert/gral/commit/c24e08a91952a99b8c8b686a1b172335db8cdf87 .

**Comment by BanzaiMan** [comment] 2017-10-27 13:03
@javabrett Thanks for the information.

I do not think this is something we can fix, so I'm closing this.

**Closed by BanzaiMan** 2017-10-27 13:03 UTC
