### ISSUE TITLE
seg. fault "./home/travis/build.sh: line 45:  3090 Segmentation fault" with python

### ISSUE THREAD

**Issue by MrOerni** [travis-ci/travis-ci#6655] opened 2016-09-30 05:51 UTC
I'm getting a seg. fault while testing. 
These test run fine locally.

I found a bunch of other issues like this, but they do not refer to python.

https://travis-ci.org/MrOerni/InphimaHelperCoordinator/jobs/163920078#L252

**Comment by BanzaiMan** [comment] 2016-09-30 10:39
Try deleting the cache first.

**Comment by MrOerni** [comment] 2016-09-30 11:54
Nothing changed. Still failing.

**Comment by BanzaiMan** [comment] 2016-09-30 13:42
Do you have native extensions? I'm guessing that you have faulty extensions.

This build https://travis-ci.org/MrOerni/InphimaHelperCoordinator/builds/162995616 added many new things. Compare https://travis-ci.org/MrOerni/InphimaHelperCoordinator/jobs/161917490#L232 and https://travis-ci.org/MrOerni/InphimaHelperCoordinator/jobs/162995617#L251.

**Comment by MrOerni** [comment] 2016-10-01 13:51
Thats a hint.
There was a [hypothesis update](http://hypothesis.works/articles/hypothesis-3.5.0-release/) right before the failing started. It added `uncompyle6` to the dependencies.

Ich updated my requirements to the state where it last works. 
-> same result :-( (I didn't expected that)

**Comment by BanzaiMan** [comment] 2016-10-10 21:47
Looks like the build has been fixed. https://travis-ci.org/MrOerni/InphimaHelperCoordinator/builds/166375143 Can we close this?

**Comment by MrOerni** [comment] 2016-10-13 12:06
I just reverted the tests.

**Comment by BanzaiMan** [comment] 2016-10-13 12:56
I can reproduce the problem on Docker using our image. See https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally.

**Comment by BanzaiMan** [comment] 2016-10-13 13:00
The Python 3.5 archive is https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.5.2.tar.bz2. Download this, and expand to `/`:

```sh-session
$ docker run --rm -it quay.io/travisci/travis-python /bin/bash
root@a83e992deac5:/# su - travis
travis@a83e992deac5:~$ wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.5.2.tar.bz2
--2016-10-13 12:50:08--  https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.5.2.tar.bz2
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.49.228
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.49.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47491861 (45M) [application/octet-stream]
Saving to: `python-3.5.2.tar.bz2'

100%[==================================================================================================================================================================================================================================================================================>] 47,491,861  8.54M/s   in 5.2s

2016-10-13 12:50:13 (8.78 MB/s) - `python-3.5.2.tar.bz2' saved [47491861/47491861]

travis@a83e992deac5:~$ sudo tar xf python-3.5.2.tar.bz2  -C /
```

Then follow the steps:

<details>
```sh-session
travis@a83e992deac5:~$ git clone --depth=50 --branch=playground/travis-ci https://github.com/MrOerni/InphimaHelperCoordinator.git MrOerni/InphimaHelperCoordinator
Cloning into 'MrOerni/InphimaHelperCoordinator'...
remote: Counting objects: 265, done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 265 (delta 139), reused 236 (delta 127), pack-reused 0
Receiving objects: 100% (265/265), 43.39 KiB | 0 bytes/s, done.
Resolving deltas: 100% (139/139), done.
Checking connectivity... done.
travis@a83e992deac5:~$ cd MrOerni/InphimaHelperCoordinator/
travis@a83e992deac5:~/MrOerni/InphimaHelperCoordinator$ git submodule update --recursive --init
Submodule 'EventShiftSchedule' (https://github.com/MrOerni/EventShiftSchedule) registered for path 'EventShiftSchedule'
Cloning into 'EventShiftSchedule'...
remote: Counting objects: 410, done.
remote: Total 410 (delta 0), reused 0 (delta 0), pack-reused 410
Receiving objects: 100% (410/410), 58.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (237/237), done.
Checking connectivity... done.
Submodule path 'EventShiftSchedule': checked out 'a50be4d801f6da8849e018dc2657f940be15142e'
travis@a83e992deac5:~/MrOerni/InphimaHelperCoordinator$ source ~/virtualenv/python3.5/bin/activate
travis@a83e992deac5:~/MrOerni/InphimaHelperCoordinator$ python --version
Python 3.5.2
travis@a83e992deac5:~/MrOerni/InphimaHelperCoordinator$ pip install -r requirements.txt
Collecting Django==1.10 (from -r requirements.txt (line 1))
  Downloading Django-1.10-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 18kB/s
Collecting django-auth-ldap==1.2.8 (from -r requirements.txt (line 2))
  Downloading django_auth_ldap-1.2.8-py3-none-any.whl
Collecting pyldap==2.4.25.1 (from -r requirements.txt (line 3))
  Downloading pyldap-2.4.25.1.tar.gz (124kB)
    100% |████████████████████████████████| 133kB 2.9MB/s
Collecting django-registration==2.1.2 (from -r requirements.txt (line 4))
  Downloading django-registration-2.1.2.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 4.0MB/s
Collecting hypothesis[django]==3.4.2 (from -r EventShiftSchedule/requirements.txt (line 1))
  Downloading hypothesis-3.4.2.tar.gz (71kB)
    100% |████████████████████████████████| 71kB 3.7MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (from pyldap==2.4.25.1->-r requirements.txt (line 3))
Collecting pytz (from hypothesis[django]==3.4.2->-r EventShiftSchedule/requirements.txt (line 1))
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 481kB 1.6MB/s
Collecting fake-factory<=0.5.3,>=0.5.2 (from hypothesis[django]==3.4.2->-r EventShiftSchedule/requirements.txt (line 1))
  Downloading fake-factory-0.5.3.tar.gz (392kB)
    100% |████████████████████████████████| 399kB 2.1MB/s
Building wheels for collected packages: pyldap, django-registration, hypothesis, fake-factory
  Running setup.py bdist_wheel for pyldap ... done
  Stored in directory: /home/travis/.cache/pip/wheels/26/ff/3d/5ca25e5a9d6552f9851ed2eea60fdb2219acf0a5b67e6b2cf4
  Running setup.py bdist_wheel for django-registration ... done
  Stored in directory: /home/travis/.cache/pip/wheels/d4/4e/9e/219991840b5063d94b23d05a3ffff051b9d4fec8fcdb573324
  Running setup.py bdist_wheel for hypothesis ... done
  Stored in directory: /home/travis/.cache/pip/wheels/70/13/1b/ded62e1ad7d6f189c7dd5008a57b7b97e2c92ebf16069cf54e
  Running setup.py bdist_wheel for fake-factory ... done
  Stored in directory: /home/travis/.cache/pip/wheels/23/b2/d1/84b5a53f03aa9b577fb0ee2c1b2d988edb3d04724f5bbf4c56
Successfully built pyldap django-registration hypothesis fake-factory
Installing collected packages: Django, pyldap, django-auth-ldap, django-registration, pytz, fake-factory, hypothesis
Successfully installed Django-1.10 django-auth-ldap-1.2.8 django-registration-2.1.2 fake-factory-0.5.3 hypothesis-3.4.2 pyldap-2.4.25.1 pytz-2016.7
travis@a83e992deac5:~/MrOerni/InphimaHelperCoordinator$ python manage.py collectstatic --no-input
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate_init.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/popup_response.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/change_form.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/cancel.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/home/travis/MrOerni/InphimaHelperCoordinator/EventShiftSchedule/static/EventShiftSchedule/js/main.js'

62 static files copied to '/home/travis/MrOerni/InphimaHelperCoordinator/static'.
travis@a83e992deac5:~/MrOerni/InphimaHelperCoordinator$  python manage.py test -v 2
Creating test database for alias 'default' (':memory:')...
Operations to perform:
  Synchronize unmigrated apps: messages, staticfiles
  Apply all migrations: EventShiftSchedule, admin, auth, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying EventShiftSchedule.0001_initial... OK
  Applying EventShiftSchedule.0002_auto_20160927_1946... OK
  Applying EventShiftSchedule.0003_auto_20160927_1952... OK
  Applying EventShiftSchedule.0002_auto_20160927_0736... OK
  Applying EventShiftSchedule.0003_auto_20160927_0802... OK
  Applying EventShiftSchedule.0004_merge_20160928_0700... OK
  Applying EventShiftSchedule.0005_auto_20160928_0710... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
test_enter_no_500 (EventShiftSchedule.tests.NoEventTest) ... ok
test_shift_schedule_no_500 (EventShiftSchedule.tests.NoEventTest) ... ERROR

======================================================================
ERROR: test_shift_schedule_no_500 (EventShiftSchedule.tests.NoEventTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/MrOerni/InphimaHelperCoordinator/EventShiftSchedule/tests.py", line 52, in test_shift_schedule_no_500
    response = self.client.get(reverse('EventShiftSchedule:shift_schedule'))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/client.py", line 529, in get
    **extra)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/client.py", line 333, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/client.py", line 494, in request
    six.reraise(*exc_info)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/travis/MrOerni/InphimaHelperCoordinator/EventShiftSchedule/views.py", line 22, in shift_schedule
    return redirect("event/{}".format(Event.objects.earliest().id))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 545, in earliest
    return self._earliest_or_latest(field_name=field_name, direction="")
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 542, in _earliest_or_latest
    return obj.get()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
EventShiftSchedule.models.DoesNotExist: Event matching query does not exist.

----------------------------------------------------------------------
Ran 2 tests in 0.886s

FAILED (errors=1)
Destroying test database for alias 'default' (':memory:')...
```
</details>

**Comment by BanzaiMan** [comment] 2016-12-09 05:56
Segmentation fault is no longer occurring. https://travis-ci.org/MrOerni/InphimaHelperCoordinator/builds

**Closed by BanzaiMan** 2016-12-09 05:56 UTC
