### ISSUE TITLE
KVM not installed

### ISSUE THREAD

**Issue by instrap** [travis-ci/travis-ci#8586] opened 2017-10-13 20:19 UTC
I get the following error:

> emulator: ERROR: x86 emulation currently requires hardware acceleration!
> Please ensure KVM is properly installed and usable.
> CPU acceleration status: KVM requires a CPU that supports vmx or svm
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

I am trying to start the android-26 emulator and the following is that part of my`.travis.yaml`:

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - sys-img-x86-google_apis_playstore-26

before_script:
    - android list targets
    - echo no | android create avd --force -n test -t android-26 --abi google_apis_playstore/x86
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

**Comment by BanzaiMan** [comment] 2017-10-13 21:43
Closing as a duplicate of https://github.com/travis-ci/travis-ci/issues/1419.

At this point, we are unable to provide KVM capabilities on our service. https://github.com/travis-ci/travis-ci/issues/1419#issuecomment-148759845

**Closed by BanzaiMan** 2017-10-13 21:43 UTC

**Comment by thsaravana** [comment] 2017-10-14 04:15
> $ android list targets
> Available Android targets:
> 
> id: 1 or "android-25"
>      Name: Android 7.1.1
>      Type: Platform
>      API level: 25
>      Revision: 3
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : no ABIs.
> 
> id: 2 or "android-26"
>      Name: Android 8.0.0
>      Type: Platform
>      API level: 26
>      Revision: 2
>      Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
>  Tag/ABIs : google_apis_playstore/x86

I only got 2 targets. Both android-25 and 26 emulators requries Hardware Acceleration and wouldn't start without KVM capabilities. But android-21 doesn't need this. Why is android-21 unavailable?

**Comment by LewisMagri** [comment] 2019-02-13 17:43
should probs remove it from your docs:
https://docs.travis-ci.com/user/languages/android/
`sys-img-x86-android-26`
