### ISSUE TITLE
GLX error with xvfb since 14.04.4

### ISSUE THREAD

**Issue by Insoleet** [travis-ci/travis-ci#6508] opened 2016-08-20 22:05 UTC
Hello dear travis team,

I'm using travis to test my PyQt5 application on Linux. It was working perfectly until the release of Ubuntu Trusty 14.04.4.

The error is the following : 
```
Xlib:  extension "GLX" missing on display ":10.0".

ci/travis/test.sh: line 14:   534 Segmentation fault      (core dumped) python setup.py test
```

I tried many methods to initialize xvfb, the first one being to force extension enabling : 
```
export XVFBARGS=":99 -screen 0 1280x1024x24 +extension RANDR +extension RENDER +extension GLX"
sudo sh -e /etc/init.d/xvfb restart
```

Or to start xvfb manually : 
```
sudo sh -e /etc/init.d/xvfb stop
LIBGL_DEBUG=1 Xvfb :10 -screen 0 1280x960x24 +extension RANDR +extension RENDER +extension GLX &
```

But no method worked. When logging xvfb start, it correctly enables GLX extension : 

```
Stopping virtual X frame buffer: Xvfb.
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
```

For reference, here is the original build which was working as intended, running on Trusty 14.04.3 : https://travis-ci.org/duniter/sakia/jobs/148654914

And here is ono of my tries, ending in failure on Trusty 14.04.4 : https://travis-ci.org/duniter/sakia/jobs/153844390

Looking at TrustyTahr release logs, I could not find a cause which would be fixable without changing the image : https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes

Is it possible to force usage of Trusty 14.04.3 ?

**Comment by BanzaiMan** [comment] 2016-08-20 22:16
A duplicate of https://github.com/travis-ci/packer-templates/issues/220, the fix for which is expected to go into production Monday.

**Closed by BanzaiMan** 2016-08-20 22:16 UTC
