### ISSUE TITLE
Tests succeed, but Travis does not detect the end of test suite and eventually times out

### ISSUE THREAD

**Issue by pond** [travis-ci/travis-ci#6995] opened 2016-12-08 19:09 UTC
For the last few weeks we have seen this across _all_ of our builds on both public and private Travis CI test suites. Example:

```
Worker information
hostname: i-bf0cdaa8-precise-production-2-worker-com-docker.travisci.net:0039870a-6d5e-4ea0-9b08-3b9c00641b30
version: v2.5.0-8-g19ea9c2 https://github.com/travis-ci/worker/tree/19ea9c20425c78100500c7cc935892b47024922c
instance: b7c1f1a:travis:ruby
startup: 771.052752ms
Build system information
Build language: ruby
Build group: stable
Build dist: precise
Build id: 36333419
Job id: 58914325
travis-build version: d801da0af
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

[... lots of prerequisites, e.g. installing Ruby, set up DB ...]

Loading testing environment

Randomized with seed 59610
[...]
Finished in 1 second (files took 1 second to load)
4 examples, 0 failures

Randomized with seed 59610

Coverage report Rcov style generated for RSpec to /home/travis/build/[redacted]/coverage/rcov



The command "TZ=Pacific/Auckland bundle exec rspec spec --backtrace" exited with 0.

Done. Your build exited with 0.
```

...but the build **DOES NOT COMPLETE**. Travis just sits there, for another ten minutes, then coughs out:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

It happens with very small suites like the above, or much larger ones that take several minutes to complete.

This is completely screwing our workflow - we have to bypass our normal GitHub checks and permit merges on failed tests, on the trust that an engineer reviews the Travis output and confirms it was actually a pass, but Travis broke.

It's happening 100% on our Ruby microservice builds; re-running doesn't seem to make any difference. On our Hoodoo gem I can usually re-run 2 or 3 times to eventually get a working pass test that Travis "notices". One of our engineers suggested that `sudo: false` to enable containerisation was at the root of this; I'm not sure it makes a difference, but if so, isn't that a whopping great Travis bug? And how come I can't find anyone else reporting the same? It seems to be just us.

Any suggestions / advice welcome! Thanks.

**Comment by BanzaiMan** [comment] 2016-12-08 19:47
Thanks for opening the issue. This is a duplicate of #6861, so I'm closing this.

**Closed by BanzaiMan** 2016-12-08 19:47 UTC

**Comment by pond** [comment] 2016-12-08 20:51
My Google Fu is clearly weak - I had been unable to find prior reports. Thanks @BanzaiMan!
