### ISSUE TITLE
Neo4j service seems broken

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [travis-ci/travis-ci#6567] opened 2016-09-06 10:38 UTC
After an hour and half of waiting:
```
Starting Neo4j Server...process [2474]... waiting for server to be
ready.........................................................
..............................................................
............................ (1 page of dots)
```
below is my .travis.yml
```yml
services:
  - neo4j
language: node_js
node_js:
  - "6"
  - "4"
```

**Comment by BanzaiMan** [comment] 2016-09-07 21:31
Do you have a build log URL that shows the problem you are describing here?

**Comment by keyvan-m-sadeghi** [comment] 2016-09-08 12:41
@BanzaiMan  Sure, here:
https://travis-ci.org/satratech/koa-neo4j/builds/157830740

**Comment by BanzaiMan** [comment] 2016-09-08 21:12
Duplicate of #3243.

**Closed by BanzaiMan** 2016-09-08 21:12 UTC
