### ISSUE TITLE
Build failing on rake db:create:all step

### ISSUE THREAD

**Issue by mattlindsey** [travis-ci/travis-ci#6846] opened 2016-11-10 10:42 UTC
This build is failing on Travis but not locally:
https://github.com/strawberrycanyon/redeemify/compare/30646bae1bcc...d78042fc374e

Latest email from support:

Hi Matthew,

Sorry to hear that the problem persists.

So, to work out if it's a problem on our end or on yours, can you try restarting the last build that passed: https://travis-ci.org/strawberrycanyon/redeemify/builds/172895732

If it does pass, then there’s a good chance, that a dependency was updated and is causing the breakage. Make sure to check the list of dependencies in the build log, usually output including versions, and see if there’s anything that’s changed. Sometimes, this can also be caused by an indirect dependency that was updated. After figuring out which dependency was updated, lock it to the last known version.

If the build still fails then it will probably be a change in our build environment.

Additionally, we update our build environment regularly, which brings in newer versions of languages and the running services. I can't see a difference in the system information for th ebuild, from the last one that passed to the current one that's failing.

It *might* also be an issue with Ruby 2.3.1, as I did a search and found a CircleCI user with a similar problem. They reported that specifying a build image based on ubuntu 14.04 (trusty) helped. You can do this on travis by adding `dist: trusty sudo: required` to your .travis.yml  
See here for more info: https://docs.travis-ci.com/user/trusty-ci-environment/

Let us know if that helps.

Regards,

Carla

**Comment by mattlindsey** [comment] 2016-11-10 10:44
Note that I added 'dist: trusty sudo: required' and that did not fix anything.

**Comment by mattlindsey** [comment] 2016-11-10 10:54
Note error message below says ruby 2.3.0, but everything is set to 2.3.1:

bundler: failed to load command: rake (/home/travis/build/strawberrycanyon/redeemify/vendor/bundle/ruby/2.3.0/bin/rake)

**Comment by BanzaiMan** [comment] 2016-11-10 12:15
So, the restart appears to have fixed the issue. Is that right? Do you have the URL for a failing build?

**Comment by mattlindsey** [comment] 2016-11-10 12:51
It is still failing. https://travis-ci.org/strawberrycanyon/redeemify/builds/174537553
Thanks.

**Comment by tansaku** [comment] 2016-11-10 12:59
hi @BanzaiMan this error seems to be the problem:

```Gem::LoadError: You have already activated did_you_mean 1.0.0, but your Gemfile requires did_you_mean 1.0.2. ```

**Comment by tansaku** [comment] 2016-11-10 13:05
also this is strange (as @mattlindsey points out):

```
/home/travis/build/strawberrycanyon/redeemify/vendor/bundle/ruby/2.3.0/bin/rake
```

we don't have this checked into git ... wonder where ruby 2.3.0 is coming from ...

**Comment by BanzaiMan** [comment] 2016-11-10 13:40
I believe `did_you_mean` 1.0.0 comes from the 2.3.1 installation (https://github.com/ruby/ruby/blob/v2_3_1/gems/bundled_gems#L6). Your `Gemfile.lock` specifies [1.0.2](https://github.com/strawberrycanyon/redeemify/blob/a25c623d5471ca7764768cc086fe629a2e512af4/Gemfile.lock#L132). I think the error message is quite accurate.

`bundle install --deployment` installs gems under `vendor`. I don't know precisely how Bundler determines the path to install gems below `vendor`, but I do think that the `2.3.0` is probably a red herring.

I can reproduce this error on my local machine using a 2.3.1 installation. To resolve this problem, either:

1. Remove `did_you_mean` 1.0.0 from the Ruby 2.3.1 installation; on my machine, I ran:

        gem uninstall -i $rvm_global_gems_path did_you_mean

1. Delete `Gemfile.lock` and drop `--deployment` from the `gem install …` command.

**Comment by mattlindsey** [comment] 2016-11-10 19:42
@BanzaiMan: Sorry, but I was enable to resolve the problem on Travis.  The local build is fine, but the Travis build still gives the error.  Any advice?
Do I need to put the 'gem uninstall' command in my .travis.yml file?

**Comment by BanzaiMan** [comment] 2016-11-10 20:05
Do you mean you were *_unable_* to?

**Comment by mattlindsey** [comment] 2016-11-10 20:40
No. I mean is that what I should do to fix the build on Travis?  The problem has never occurred locally.

**Comment by mattlindsey** [comment] 2016-11-10 20:42
Sorry. Yes I meant 'unable.'

**Comment by BanzaiMan** [comment] 2016-11-10 22:00
If you want to retain `Gemfile.lock` in your repository, try replicating what I did in the previous comment:

```yamn
before_install:
  - gem uninstall -i $rvm_global_gems_path did_you_mean
⋮ #rest
```

**Comment by mattlindsey** [comment] 2016-11-10 22:54
That fixes our issue.  Thanks!

**Closed** 2016-11-12 13:12 UTC
