### ISSUE TITLE
Unable to delete new log for restarted build, if log already deleted before build restart

### ISSUE THREAD

**Issue by galeksandrp** [travis-ci/travis-ci#4676] opened 2015-08-20 00:21 UTC
No 'Remove Log' button shows on latest stable Chrome and Firefox.

Also unable to delete via API PATCH https://api.travis-ci.org/jobs/JOBNUMBER/log, it says

	{
	  "error": {
		"message": "Log for job JOBNUMBER has already been removed"
	  }
	}

Yes, it is strange usecase, but if it is a feature, it is a strange feature :smile:

**Comment by BanzaiMan** [comment] 2015-08-20 00:46
This is strange. We deployed a fix for this issue earlier today.

![build__1514_-_banzaiman_travis_production_test_-_travis_ci](https://cloud.githubusercontent.com/assets/25666/9372948/9af62f00-46b2-11e5-8d78-f7fe950fad80.png)

Does the problem persist if you reload the page?

As for the error returned when the log has already been removed, I see where you are coming from. Are you issuing 2 PATCH calls successively?

**Comment by galeksandrp** [comment] 2015-08-20 01:01
Yes, this problem persist on page reload.

I look likes when build restarted and new log writes, travis don't reset log deletion state for build. So, it is travis core limitation (or bug), not web ui display issue.

Right now i remove log via button, restart build, it finished, i refreshed page, and new log and no button here. I tried via api, and it says that log already deleted.

**Comment by BanzaiMan** [comment] 2015-08-20 01:59
Do you have a build log URL to show this? I cannot reproduce it. When I refresh the page after the restart (which comes after the log removal), I see the "Remove Log" button.

**Comment by galeksandrp** [comment] 2015-08-20 02:02
https://travis-ci.org/galeksandrp/wadl/builds/76391376

**Comment by BanzaiMan** [comment] 2015-08-20 03:10
I confirmed that this build is in an inconsistent state with respect to the logs. I am not quite sure how it got to this state. I didn't find anything interesting in our logs, either.

I can reset the build's state, so that you can remove the logs again.

**Comment by galeksandrp** [comment] 2015-08-20 12:37
Don't care about this build, this issue affects all my repos and builds. Good news that it is not critical for me. I just asked if it is a feature or a bug, and we investigated that it is a strange bug, that someday will be fixed.

**Comment by BanzaiMan** [comment] 2015-08-25 02:04
I agree that this may be a bug, but one that I have been unable to reproduce.

Have you seen recurrence of this problem?

**Comment by envygeeks** [comment] 2015-10-12 14:25
@BanzaiMan I'm seeing this currently right now and can always reproduce it.

**Comment by BanzaiMan** [comment] 2015-10-19 13:33
@envygeeks Great! How can it be reproduced?

**Comment by envygeeks** [comment] 2015-10-19 14:18
@BanzaiMan:

1. Create a build that fails.
2. Delete the log for said failed build.
3. Use the restart build button to restart the build.
4. Build logs can no longer be deleted.

Pretty much the same step as above.  We  experienced this issue on several failed builds while trying to debug a Docker issue on Trusty beta, but I think somebody ended up manually removing all the failed build logs after I emailed support.

**Comment by envygeeks** [comment] 2015-10-19 14:19
That leads into a separate issue that probably already exists: we were also no longer able to follow logs when a log was deleted and a build was restarted, the circle button that we click to follow logs just disappears to never return.

**Comment by joshk** [comment] 2015-10-19 14:33
Sounds like we have a small bug in the restart feature which doesn't reset that flag on the log.

@BanzaiMan can you please add this to the Sapphire backlog?

**Comment by anarosas** [comment] 2016-08-17 18:08
Fixed with https://github.com/travis-ci/travis-hub/pull/80  🎉

**Closed by anarosas** 2016-08-17 18:08 UTC
Labels: bug, travis-api
