### ISSUE TITLE
problems sharing settings with pull requests

### ISSUE THREAD

**Issue by calidion** [travis-ci/travis-ci#5787] opened 2016-03-15 06:18 UTC
when a project with encrypted variables, pull requests can not share them to build successfully, even triggered by the repo owner.

please consider to add the ability for repo owner to run pr with encrypted variables.

thanks.

**Comment by BanzaiMan** [comment] 2016-03-15 06:55
There is an outstanding issue about secure env vars not working on PRs. I can't locate it right now, but I'll do so when I can.

in the meantime, I'm closing this as a duplicate.

**Closed by BanzaiMan** 2016-03-15 06:55 UTC

**Comment by calidion** [comment] 2016-03-15 07:23
Is this feature supported now?

**Comment by BanzaiMan** [comment] 2016-03-15 07:24
The issue is outstanding.
