### ISSUE TITLE
oraclejdk10 not installed

### ISSUE THREAD

**Issue by MWGuy** [travis-ci/travis-ci#10271] opened 2018-10-19 16:22 UTC
```
Setting APT mirror in /etc/apt/sources.list: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
$ export JAVA_HOME=${TRAVIS_HOME}/oraclejdk10
$ bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk
install-jdk.sh 2018-10-17
Variables:
  feature = 10
  license = BCL
       os = linux-x64
      url = http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz
   status = 302
  archive = /home/travis/.cache/install-jdk/jdk-10.0.2_linux-x64_bin.tar.gz
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz...
The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 8 during .
Your build has been stopped.
```

**Comment by BanzaiMan** [comment] 2018-10-19 17:28
Duplicate of #19249.

**Closed by BanzaiMan** 2018-10-19 17:28 UTC
