### ISSUE TITLE
Ubuntu 16.04 and 18.04 LTS

### ISSUE THREAD

**Issue by aberaud** [travis-ci/travis-ci#5821] opened 2016-03-25 18:19 UTC
**Edit: Ubuntu 16.04 (Xenial) is now available. See https://blog.travis-ci.com/2018-11-08-xenial-release for more information.**

The next version of Ubuntu 16.04 LTS - Xenial Xerus–is scheduled to be released April 21. Aim to update to 16.04 after it's released.

This means to take advantage of all the new versions in the Ubuntu package repositories (the 14.04 versions are starting to get more and more outdated), but it also has the potential to break quite a bit.

Opening this to start tracking when and how to do the update.

**Comment by BanzaiMan** [comment] 2016-03-27 09:50
We do not have immediate plans to update the build environment's release. You can use our Docker feature (https://docs.travis-ci.com/user/trusty-ci-environment) to pull a reasonable image and use that instead.

**Comment by solarce** [comment] 2016-04-25 17:37
While we can understand the need for some folks to have the newest stuff, building and maintaining our image library, while also ensuring it's usable for the 250,000+ jobs we run each day is a unique challenge.

Given that, we are currently focused on support 12.04 and 14.04 as our primary environments. At the moment, it is unlikely that we'll be supporting 16.04 as a native environment this year.

If you're particular use cases require something newer, I would encourage you to use utilize our [Docker support](http://docs.travis-ci.com/user/docker/), as Hiro mentioned, which would allow you run your build inside a Docker image of a newer Ubuntu release. While the start up times are slower than our countainer-based builds, you get a full VM with 7.5GB of RAM, for each build.

Regards,
Brandon Burton
Infrastructure Manager

**Comment by aberaud** [comment] 2016-05-13 16:29
Since 16.04 Xenial is now the latest Ubuntu LTS, you might want to add a specific official documentation about how to use it, with an example .travis.yml configuration.

More and more new / innovative projects will need 16.04 to build.

**Comment by niemeyer** [comment] 2016-05-25 18:40
Surprised to see this issue closed. Containers don't work in many cases, even more if what you want to test is in fact depending on management of container-like logic. I also probably don't understand what the cost is on your side. You seem to be using GCE, which itself supports 16.04 already. Is it so expensive for Travis to support a new environment considering that?

**Comment by reece** [comment] 2016-08-17 18:41
Would switching to a paid account accelerate access to 16.04?

(I know this issue is closed, but for users/customers it's still very much an open issue.)

**Comment by BanzaiMan** [comment] 2016-08-17 18:47
@reece Sorry, but that wold not be any different.

**Comment by joshk** [comment] 2016-08-30 23:50
Hi @niemeyer, and everyone else

My name is Josh, I'm the Product Manager here at Travis CI.

I wanted to follow up on the question `Is it expensive for Travis to support a new environment?`

The issue isn't the cost of running the jobs, but the development and maintenance costs around providing the build environments.

We have a lot of work on our backlog, and as much as we want to support newer operating systems, the work required is very significant. For example, updating all Chef recipes, testing, more updating, more testing, and then providing regular updates. Rinse and repeat.

All the while we also have a lot of other regular work related to providing a stable, secure, and scalable platform for all our users.

Thank you for everyones feedback on this topic, and we hope to provide more information in the New Year.

Josh

**Comment by BanzaiMan** [comment] 2017-02-17 10:59
I'm reopening this, so it can be found easier (hopefully). It remains locked.

**Comment by luna-travisci** [comment] 2018-11-22 03:04
Ubuntu 16.04 is now available. See https://blog.travis-ci.com/2018-11-08-xenial-release for more information.

**Comment by BanzaiMan** [comment] 2018-11-28 17:38
I'm closing this one, as we've announced Xenial availability. Bionic will be tracked at https://travis-ci.community/ in the near future.

**Closed by BanzaiMan** 2018-11-28 17:38 UTC
Labels: locked, team blue, upgrade-request
