### ISSUE TITLE
Basic packages (e.g. autoconf) disallowed / not installable

### ISSUE THREAD

**Issue by gioele** [travis-ci/travis-ci#6822] opened 2016-11-04 00:50 UTC
The job https://travis-ci.org/gioele/fontforge/jobs/173126022 fails because

> Installing APT Packages (BETA)
>
> Disallowing packages: autoconf, automake, autotools-dev, bzip2, gcc-4.9, libtool, libjpeg-dev, libtiff4-dev, libpng12-dev, libfreetype6-dev, libgif-dev, libx11-dev, libxml2-dev, libpango1.0-dev, libcairo2-dev, python3.5-dev
> If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

And later fails to find a viable C compiler (see issue #6821).

These basic packages should be already whitelisted, at least this is what the closed issue #3434 says.

In a similar job (<https://travis-ci.org/gioele/fontforge/jobs/172814471>) launched yesterday with the same Travis settings, Travis correctly installed all the requested packages.

**Comment by BanzaiMan** [comment] 2016-11-04 01:02
We have updated our APT list package selection mechanism to differentiate Precise and Trusty. The change happened today.

The build started failing because `autoconf` and others are not found on the Trusty list.

**Comment by BanzaiMan** [comment] 2016-11-04 01:09
I should point out that `sudo: false` + `dist: trusty` is not quite ready yet, as you can see. If you need Trusty, please use `sudo: required`.

**Comment by BanzaiMan** [comment] 2016-11-04 01:23
See https://github.com/travis-ci/apt-package-whitelist/pull/3473.

**Comment by tmcdonell** [comment] 2016-11-04 01:59
@BanzaiMan are we supposed to submit new package whitelist requests for trusty, or you are planning to transition everything already in precise? (there are quite a few packages I use not listed in the output of https://github.com/travis-ci/apt-package-whitelist/pull/3473)

**Comment by schinzelh** [comment] 2016-11-04 08:02
We are running into the same issue: https://travis-ci.org/dashpay/dash/jobs/173071264
I have checked the packages in question and they have been whitelisted for precise but apparently not for trusty...

**Comment by karalabe** [comment] 2016-11-04 09:27
Same issue for https://github.com/ethereum/go-ethereum, all our builds fail now due to the trusty build white-list being tiny and missing things we use (e.g. `gcc-multilib`).

**Comment by karalabe** [comment] 2016-11-04 09:45
Btw, there are various packages that are whitelisted on precise but don't even exist in those apt repositories (as they have never been built for precise), so the only way to use them is via trusty, which now successfully blacklisted almost everything.

In essence this move just irreversibly broke our builds and looking at your 4 month backlog of accepting whitelist requests, this issue looks dire.

**Comment by BanzaiMan** [comment] 2016-11-04 13:06
With `sudo: required`, we skip checking against the lists. You can install whatever packages you need.

**Comment by schinzelh** [comment] 2016-11-04 13:26
@BanzaiMan So `sudo: required` is the fix for now and you will not update the whitelist for trusty soon?

**Comment by BanzaiMan** [comment] 2016-11-04 13:42
@schinzelh Package whitelist would be updated to some extent (see the PR above). It'll take a while for the Trusty list to catch up, I'm afraid.

**Comment by tmcdonell** [comment] 2016-11-04 23:44
@BanzaiMan how long until the lists catch up? Caching is disabled with `sudo: required` so my (and I'm sure many other people's) build times will increase _significantly_...

**Comment by BanzaiMan** [comment] 2016-11-05 01:01
@tmcdonell Not sure how you got the idea that you can't use caches on `sudo: required`. It's been enabled for 6 months. https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Comment by tmcdonell** [comment] 2016-11-05 01:08
@BanzaiMan ah, excellent! Thank you!

**Comment by BanzaiMan** [comment] 2016-11-07 15:55
I've merged the PR above. The packages included in the list are now available for installation on the Trusty container builds.

I'm still working on testing procedure updates so that we can test Trusty packages accordingly, but it may take a little longer than I'd hoped. I'll update https://github.com/travis-ci/apt-package-whitelist/blob/master/README.md when that is possible.

In the meantime, I am closing this.

**Comment by BanzaiMan** [comment] 2016-11-07 18:02
This is a bit more involved than just a whitelist.

**Comment by BanzaiMan** [comment] 2016-11-07 20:49
Here's how it broke.

## Past behavior

In the past, `sudo: false` + `dist: trusty` was an invalid configuration; we sent it to containers because `sudo: false`. You can see this in https://travis-ci.org/gioele/fontforge/jobs/172779734 and https://github.com/gioele/fontforge/blob/86f8fb8d9300efc9ebe2734458c95083150d990f/.travis.yml. We ignored `dist: trusty`, and used the list which was designed for Precise.

## Current behavior

We rolled out the changes to differentiate Precise and Trusty lists. Since some jobs have `dist: trusty`, although it was sent to a Precise image (you can see this in https://travis-ci.org/gioele/fontforge/jobs/173126022#L16), we used the Trusty list (which, as the previous discussion shows, is lacking).

This is where we stand now. As long as you have `dist: trusty` without actually opting in to the yet-to-be announced feature, your builds are potentially wrong based on a wrong list of whitelisted APT packages.

## What needs fixing

We need to detect the Ubuntu release name at run time (not at the compile time, based on the jobs' configuration in `.travis.yml`).

**Comment by BanzaiMan** [comment] 2016-11-09 15:03
We've announced Trusty on containers. https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/

**Comment by BanzaiMan** [comment] 2017-01-27 23:23
I think this is fixed. If you see a problem, please open a new issue.

**Closed by BanzaiMan** 2017-01-27 23:23 UTC
Labels: team blue
