### ISSUE TITLE
Using postgis on trusty container fails while trying to access file "$libdir/postgis-2.3"

### ISSUE THREAD

**Issue by fvanderbiest** [travis-ci/travis-ci#8292] opened 2017-08-24 14:26 UTC
Trying to use postgis on containers, and following the [official documentation](https://docs.travis-ci.com/user/database-setup/#PostgreSQL)...
```
language: python

sudo: false

dist: trusty

python:
  - "2.7"
  - "3.4"

addons:
  postgresql: "9.6"

git:
  depth: 1

install: make install

before_script:
  - psql -c "CREATE USER c2cgeoform WITH PASSWORD 'c2cgeoform';" -U postgres
  - psql -c "CREATE DATABASE c2cgeoform WITH OWNER c2cgeoform;" -U postgres
  - psql -d c2cgeoform -c "CREATE EXTENSION postgis" -U postgres

script: make check && make test
```

... results in https://travis-ci.org/camptocamp/c2cgeoform/jobs/267993026 which yields:
```
$ psql -d c2cgeoform -c "CREATE EXTENSION postgis" -U postgres
ERROR:  could not access file "$libdir/postgis-2.3": No such file or directory
The command "psql -d c2cgeoform -c "CREATE EXTENSION postgis" -U postgres" failed and exited with 1 during .
Your build has been stopped.
```

Am I missing something here ?

**Comment by BanzaiMan** [comment] 2017-08-24 14:56
I think this is a duplicate of #6972.

**Closed by BanzaiMan** 2017-08-24 14:56 UTC
