### ISSUE TITLE
Rust fails to install and no output to understand why

### ISSUE THREAD

**Issue by DoumanAsh** [travis-ci/travis-ci#6654] opened 2016-09-30 05:08 UTC
I setup integration for my new repo but i get fail when Travis is attempting to install Rust https://travis-ci.org/DoumanAsh/lazy-panic.rs/builds/163915229

But since there is no output i have no idea what could go wrong...
Maybe it would be better to redirect output of installation to a file and print on the fail?

**Comment by iKevinY** [comment] 2016-09-30 06:31
Noticed this as well. Perhaps Travis should install Rust using [`rustup.rs`](https://github.com/rust-lang-nursery/rustup.rs) rather than `rustup.sh`?

**Comment by K-Finlay** [comment] 2016-09-30 06:50
Looks like it might be caused by the latest pull request in rustup.sh.
[https://github.com/rust-lang/rustup.sh/commit/7c8692d7cddd047f6739690c28e8f805d2661888](https://github.com/rust-lang/rustup.sh/commit/7c8692d7cddd047f6739690c28e8f805d2661888)

**Comment by ninjabear** [comment] 2016-09-30 09:45
This appears to be all Rust projects and for all platforms:

https://travis-ci.org/snowplow/factotum/builds/163963871

**Comment by BanzaiMan** [comment] 2016-09-30 11:53
The problem:

```sh-session
$ sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=stable -y --disable-sudo
rustup: You need root permissions to install Rust. Please run with 'sudo'.
```

Did this change recently on the install script?

**Comment by BanzaiMan** [comment] 2016-09-30 11:56
https://github.com/rust-lang/rustup.sh/blame/7c8692d7cddd047f6739690c28e8f805d2661888/rustup.sh#L63

**Comment by BanzaiMan** [comment] 2016-09-30 11:57
If this is a hard requirement, we can move the Rust install logic to the place before `sudo` is disabled.

**Comment by ninjabear** [comment] 2016-09-30 12:07
@BanzaiMan it did change recently yes - it is supposed to support sudoless installs with `--disable-sudo` but this functionality appears to have been clobbered by a recent PR

**Comment by wigy-opensource-developer** [comment] 2016-09-30 13:06
This use-case of rustup.sh has been broken recently. rust-lang/rustup.sh#72 has been created to follow the fix. I doubt that Travis can do a workaround until that issue is fixed.

**Comment by brson** [comment] 2016-09-30 15:06
Fixed by https://github.com/rust-lang/rustup.sh/issues/73 and deploying now. Should be available within 10 minutes. Sorry for the hassle.

**Comment by carols10cents** [comment] 2016-09-30 15:41
Can confirm - builds are working again! Thank you @brson!!!! https://travis-ci.org/rust-lang/book/builds/164020983

**Comment by DoumanAsh** [comment] 2016-09-30 16:08
So it is ok now, should we close issue?

**Closed** 2016-09-30 16:30 UTC
Labels: rust
