### ISSUE TITLE
Please read .travis.yml from debian/.travis.yml as well

### ISSUE THREAD

**Issue by agx** [travis-ci/travis-ci#8210] opened 2017-08-05 17:01 UTC
Hi,
it would be great if travisci would support alternative locations of .travis.yml. For Debian and derivatives like Ubuntu this would be nice since for packages it's a bit complicated to add files outside of the debian/directory (see e.g. the 

$ echo 'extend-diff-ignore = "^\.travis\.yml$"' >> 
      debian/source/options

projects use to get it working). This is fragile and breaks often when upstream uses this file as well. So being able to read .travis.yml from debian/.travis.yml or debian/travis.yml would be great to automate testing of Debian packages in a non-hacky way.

**Comment by BanzaiMan** [comment] 2017-08-12 18:43
Duplicate of #5519.

**Closed by BanzaiMan** 2017-08-12 18:43 UTC
Labels: feature-request, travis-gatekeeper
