### ISSUE TITLE
Getting Error 65 without any reason (Xcode 8).

### ISSUE THREAD

**Issue by Fengson** [travis-ci/travis-ci#6758] opened 2016-10-20 11:59 UTC
After updating to Xcode 8, Travis often fails my builds with an error 65. After I restart the job (sometimes as much as 5 times) the same build passes without any issues.

I either only get:
`The command "./scripts/build.sh" exited with 65.` (where build.sh is a script that runs `xcodebuild test` and `xcodebuild` to build the app after testing finishes.)

or more verbose errors like:

```
Generating 'XYZ.app.dSYM'
❌  error: couldn't remove '/Users/travis/Library/Developer/Xcode/DerivedData/XYZ-aaltcjvmshpmlufpmzdsgbernspl/Build/Products/Debug-iphonesimulator/XYZ.app/SomeName.storyboardc' after command failed: Directory not empty
```
and at the end of log:
```
Testing failed:
    The file “056-Jj-FAu-view-XmS-Ro-0cO.nib” couldn’t be opened because there is no such file.
    error: couldn't remove '/Users/travis/Library/Developer/Xcode/DerivedData/XYZ-aaltcjvmshpmlufpmzdsgbernspl/Build/Products/Debug-iphonesimulator/XYZ.app/SomeName.storyboardc' after command failed: Directory not empty
    error: lipo: can't move temporary file: /Users/travis/Library/Developer/Xcode/DerivedData/XYZ-aaltcjvmshpmlufpmzdsgbernspl/Build/Products/Debug-iphonesimulator/XYZ.app.dSYM/Contents/Resources/DWARF/XYZ to file: /Users/travis/Library/Developer/Xcode/DerivedData/XYZ-aaltcjvmshpmlufpmzdsgbernspl/Build/Products/Debug-iphonesimulator/XYZ.app.dSYM/Contents/Resources/DWARF/XYZ.lipo (No such file or directory)
    Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil emitted errors but did not return a nonzero exit code to indicate failure
** TEST FAILED **
The following build commands failed:
    LinkStoryboards
    LinkStoryboards
(2 failures)
The command "./scripts/build.sh" exited with 65.
```

My main problem is that after restarting the job (sometimes couple of times) everything works as expected. I am using xcpretty. Never had this issues prior to Xcode 8.

**Comment by BanzaiMan** [comment] 2016-10-21 23:46
Closing as a duplicate of #6675.

**Closed by BanzaiMan** 2016-10-21 23:46 UTC
