### ISSUE TITLE
Crystal: build failure due missing key in keyring

### ISSUE THREAD

**Issue by luislavena** [travis-ci/travis-ci#6063] opened 2016-05-17 00:01 UTC
It appears that `crystal: latest` started to fail recently:

https://travis-ci.org/luislavena/radix/jobs/130708872

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.Eh1o5mzC57 --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
gpg: requesting key 7CC06B54 from hkp server keys.gnupg.net
gpgkeys: key 09617FD37CC06B54 not found on keyserver
gpg: no valid OpenPGP data found.
```

This seems to be a duplicate of #5461, however things were working properly in recent builds:

https://travis-ci.org/luislavena/radix/jobs/123613121

Any ideas? /cc @asterite @jhass @waj @will

**Comment by jhass** [comment] 2016-05-17 10:43
It looks like you retried the build and it passed? Then I'd like to have this closed as a duplicate of #5461, as it's the same core issue (unreliable keyservers).

**Comment by BanzaiMan** [comment] 2016-05-17 10:59
Closing.

**Closed by BanzaiMan** 2016-05-17 10:59 UTC
Labels: community:crystal

**Comment by luislavena** [comment] 2016-05-17 11:01
Correct @jhass, retried and worked. Thank you @BanzaiMan for closing (mobile device right now) 😊
