### ISSUE TITLE
APT whitelist request for gcc-4.8 and g++-4.8

### ISSUE THREAD

**Issue by kkaefer** [travis-ci/travis-ci#3296] opened 2015-02-27 14:40 UTC
Please whitelist `gcc-4.8` and `g++-4.8` (and its dependents) from `ppa:ubuntu-toolchain-r/test`.

I realize this is an external PPA and you seem to be averse to whitelisting those.

However, a newer GCC is **vital** to use Docker-based builds for anything other than legacy projects, as the default-installed GCC 4.6 lacks support for modern C++.

There have been many, many previous requests to get GCC 4.8 support, e.g. #3131, #1379, #979. I don't really care whether you use this exact PPA, but *please* provide a way to use a more modern GCC.

**Comment by BanzaiMan** [comment] 2015-02-27 14:45
This is a duplicate of #3131; we cannot allow custom PPA at this time.

**Comment by kkaefer** [comment] 2015-02-27 14:45
lol :(

**Closed by BanzaiMan** 2015-02-27 14:45 UTC
