### ISSUE TITLE
Add default support for headless Chrome

### ISSUE THREAD

**Issue by sebworks** [travis-ci/travis-ci#7650] opened 2017-04-23 17:35 UTC
Now that PhantomJS is [dying](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), would it be possible to add default support for headless Chrome?

**Comment by BanzaiMan** [comment] 2017-04-29 18:12
Am I correct to understand that it suffices to install a recent `google-chrome-stable` package?

Looking at dependencies and whatnot, it appears that only Trusty is feasible for support.

It would be something like:

```yaml
addons:
  - chrome # or google-chrome-stable
```

Then you would start Chrome with `--headless`:

```yaml
before_install:
  - google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 http://localhost:80 # or some such
```

and run your tests

**Comment by mafredri** [comment] 2017-04-29 21:49
> Am I correct to understand that it suffices to install a recent google-chrome-stable package?

I believe `google-chrome-beta` is required (headless was added in release 59).

**Comment by BanzaiMan** [comment] 2017-04-29 23:33
Thanks.

**Comment by BanzaiMan** [comment] 2017-04-29 23:38
Perhaps it makes sense to configure the addon with a map, a la [Firefox](https://docs.travis-ci.com/user/firefox):

```yaml
addons:
  - chrome: stable # or beta
```

**Comment by jbelmont** [comment] 2017-05-08 15:04
Hello @BanzaiMan 

I am trying to install google chrome beta and and run it in travis ci

here is my travis.yml

```yml
dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
    packages:
      - google-chrome-beta
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - google-chrome-beta --headless --no-sandbox

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
```

I am seeing the following error

`The command "google-chrome-beta --headless --no-sandbox" failed and exited with 127 during .`

**Comment by BanzaiMan** [comment] 2017-05-08 15:13
@jbelmomt The real error message _should_ appear before "The command …"

**Comment by jbelmont** [comment] 2017-05-08 15:14
@BanzaiMan yes here is the real error message
`google-chrome-beta: command not found`

**Comment by jbelmont** [comment] 2017-05-08 15:15
I updated my travis.yml to this

```
dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - google-chrome-beta --headless --no-sandbox

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
```

Does this seem correct, @BanzaiMan ?

**Comment by BanzaiMan** [comment] 2017-05-08 15:17
Is the `google-chrome-beta` package getting installed?

**Comment by jbelmont** [comment] 2017-05-08 15:20
Here is the newer error

```google-chrome-beta --headless --no-sandbox
[0508/151605.158316:ERROR:gl_implementation.cc(246)] Failed to load /opt/google/chrome-beta/libosmesa.so: /opt/google/chrome-beta/libosmesa.so: cannot open shared object file: No such file or directory
[0508/151605.160410:ERROR:gpu_child_thread.cc(174)] Exiting GPU process due to errors during initialization
[0508/151605.169896:WARNING:audio_manager.cc(293)] Multiple instances of AudioManager detected
[0508/151605.169941:WARNING:audio_manager.cc(254)] Multiple instances of AudioManager detected
[0508/151605.282959:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[0508/151605.314467:ERROR:gl_implementation.cc(246)] Failed to load /opt/google/chrome-beta/libosmesa.so: /opt/google/chrome-beta/libosmesa.so: cannot open shared object file: No such file or directory
[0508/151605.318417:ERROR:gpu_child_thread.cc(174)] Exiting GPU process due to errors during initialization
[0508/151605.323698:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.```

It doesn't look like google-chrome-beta is getting installed

**Comment by Trendy** [comment] 2017-05-08 15:35
@jbelmont If you look at this PR for [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher/pull/111), you need to use the `--disable-gpu` flag.

**Comment by jbelmont** [comment] 2017-05-08 17:23
@Trendy thanks for that tip, I will try that, I got my build to pass using 

```
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - google-chrome-stable --headless --no-sandbox
```

but this is using chrome 58 not chrome 59

**Comment by BanzaiMan** [comment] 2017-05-08 17:29
The use of Chrome 58 is up to Google's apt source. The addon will use a different mechanism, and the test showed it'll use 59.

**Comment by jbelmont** [comment] 2017-05-08 17:39
@BanzaiMan sorry I miswrote the  addons field yes I confirmed that travis ci does indeed install chrome 59 with 
```
packages
  - google-chrome-beta
```
I am actually running this with testem.js so in testem.json I have this
```
{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "Chrome"
  ],
  "launch_in_dev": [
    "Chrome"
  ],
  "browser_args": {
    "Chrome": [
      "--headless",
      "--disable-gpu",
      "--remote-debugging-port=9222"
    ]
  }
}
```

When I run in travis I see this error

```
not ok 1 Chrome - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: 1
            Stderr: 
             [6200:6200:0508/173637:ERROR:browser_main_loop.cc(265)] Gtk: cannot open display: 
            
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            { type: 'error', text: 'Non-zero exit code: 1' }
            { type: 'error',
              text: '[6200:6200:0508/173637:ERROR:browser_main_loop.cc(265)] Gtk: cannot open display: \n' }
```

**Comment by jbelmont** [comment] 2017-05-08 17:51
Quick update I got the travis build to pass using this configuration

```
dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
```

The key difference is that I added a before_script section
 and here is the testem.json that launches Chrome

```
{
  "framework": "qunit",
  "test_page": "tests/index.html?hidepassed",
  "disable_watching": true,
  "launch_in_ci": [
    "Chrome"
  ],
  "launch_in_dev": [
    "Chrome"
  ],
  "browser_args": {
    "Chrome": [
      "--headless",
      "--disable-gpu",
      "--remote-debugging-port=9222"
    ]
  }
}
```

Don't know but it seems launching with xvfb seems to be the key at the moment. 
Not sure if I run with chrome unstable if that will be different.

**Comment by jbelmont** [comment] 2017-05-08 19:50
Another update here

```
dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
```

Interestingly headless browser works with no issue on Chrome 58 on Ubuntu Trusty but has errors on Chrome 59 running, not sure what is going on.

**Comment by chosak** [comment] 2017-05-18 16:44
I was able to get Chrome 59 (installed via `google-chrome-beta`) working in headless mode using Protractor; the trick was specifying the correct path to the beta binary.

```yaml
# .travis.yml
dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - google-chrome-beta
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
```

Note that even though Chrome is running in headless mode, you still seem to need `xvfb` if your tests include keypresses, otherwise you'll get an error like `an X display is required for keycode conversions, consider using Xvfb`. There's a chromedriver bug filed against this [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1772).

```js
// package.json
{
  "main": "protractor.conf.js",
  "scripts": {
    "test": "protractor"
  },
  "devDependencies": {
    "protractor": "5.1.1",

    // other dependencies here...
  }
}
```

```js
// protractor.conf.js
var chromeOptions = {
  args: ['--headless', '--disable-gpu']
}

if (process.env.GOOGLE_CHROME_BINARY) {
  chromeOptions.binary = process.env.GOOGLE_CHROME_BINARY;
}

exports.config = {
  directConnect: true,
  capabilities: {
    browserName: 'chrome',
    chromeOptions: chromeOptions
  },

  // rest of your Protractor config here...
}
```

**Comment by BanzaiMan** [comment] 2017-05-23 16:03
Hi, @chosak, this appears to be very useful information that should be incorporated into our documentation. Once https://github.com/travis-ci/docs-travis-ci-com/pull/1136 is merged, perhaps you'd be keen on improving on it with your insight.

**Comment by rwwagner90** [comment] 2017-06-07 19:36
I was able to get headless Chrome working in one Ember app https://travis-ci.org/shipshapecode/shipshape.io/builds/240018405 but not another Ember addon https://travis-ci.org/shipshapecode/ember-flatpickr/builds/240028333.

The broken one gives an error like this:
```
not ok 1 Chrome - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: 1
            Stderr: 
             [2835:2835:0606/161625:ERROR:browser_main_loop.cc(260)] Gtk: cannot open display: 
```

I noticed the one that works has a line like this:
```
$ export CHROME_SOURCE_URL=http://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
```

The one that does not work, does not seem to do this.

Does anyone have any insight into why one works and one doesn't?

**Comment by BanzaiMan** [comment] 2017-06-07 20:03
@rwwagner90 In [the one that doesn't work](https://github.com/shipshapecode/ember-flatpickr/blob/30d07a15d2af6a1557da73076077c8cdb6c7dbc4/.travis.yml), you have two definitions of `addons`; by the YAML specifications, only [the latter](https://github.com/shipshapecode/ember-flatpickr/blob/30d07a15d2af6a1557da73076077c8cdb6c7dbc4/.travis.yml#L43-L46) is effective. You need to combine the two.

**Comment by jeanduplessis** [comment] 2017-06-07 20:05
@rwwagner90 We have headless Chrome working fine for our Ember app... here's our configs:

__.travis.yml__
```
---
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "7"

cache:
  directories:
    - node_modules
    - bower_components
    - "$HOME/.npm"
    - "$HOME/.cache"

env:
  - EMBER_VERSION=default

before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - "ember exam --split=4 --parallel"
```

__testem.js__
```
/* eslint-env node */
module.exports = {
  framework: 'qunit',
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  parallel: 4,
  launch_in_ci: ['Chrome'],
  launch_in_dev: ['Chrome'],
  browser_args: {
    Chrome: ['--headless', '--disable-gpu', '--no-sandbox', '--remote-debugging-port=9222']
  }
};
```

**Comment by jbelmont** [comment] 2017-06-07 20:51
@jeanduplessis I was able to get headless chrome to work as well but one thing to note here is that `google-chrome-stable` is chrome version 58 and `google-chrome-beta` is working on chrome version 59 and the reason I bring this up is because the [Headless Chrome Documentation](https://developers.google.com/web/updates/2017/04/headless-chrome) states this. Also when I run `google-chrome-stable` I don't have to do anything with `xvfb` like you are doing.

**Comment by BanzaiMan** [comment] 2017-06-07 21:02
We have documentation on using Google Chrome with the addon in headless mode. https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode

I think this issue can be closed now, and if anyone has suggestions for improving the document, we welcome PRs.

**Comment by rwwagner90** [comment] 2017-06-07 21:34
Oh dang @BanzaiMan good catch! Sorry for the stupid mistake there 😞

**Comment by BanzaiMan** [comment] 2017-06-07 22:03
@rwwagner90 No worries. I've been there before. :-)

**Comment by BanzaiMan** [comment] 2017-06-07 22:04
I'm closing this now. As I said before, if you have suggestions for improving the headless mode document (esp. for Google Chrome), do open PRs for docs. Thanks!

**Closed by BanzaiMan** 2017-06-07 22:04 UTC
Labels: build environment, feature-request, travis-build

**Comment by victormejia** [comment] 2017-06-19 06:43
@chosak thanks so much for the info you posted. I had to change the env variable to `CHROME_CANARY_BIN`
