### ISSUE TITLE
.travis/job_stages: line 475: yarn/apt-get: command not found

### ISSUE THREAD

**Issue by kenorb** [travis-ci/travis-ci#9464] opened 2018-04-09 22:38 UTC
macOS build: [#364351848](https://travis-ci.org/kenorb-contrib/afsctool/builds/364351848)

Warnings at the start:

```
/Users/travis/.travis/job_stages: line 475: yarn: command not found
sudo: apt-get: command not found
```

Warnings at the end:

```
Your build has been stopped.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```

### `.travis.yml`

```
os: osx
install:
- brew install cmake pkg-config google-sparsehash
script:
- cmake .
- make
```

**Comment by BanzaiMan** [comment] 2018-04-09 23:05
Duplicate of #9454.

**Closed by BanzaiMan** 2018-04-09 23:05 UTC
