### ISSUE TITLE
fast_finish notification should occur when first job fails

### ISSUE THREAD

**Issue by ezyang** [travis-ci/travis-ci#5875] opened 2016-04-08 03:05 UTC
Steps to reproduce:

1. Enable fast_finish
2. Setup Slack notifications
3. Start a build with multiple jobs, where one job fails quickly

Expected behavior: Get a Slack notification as soon as the quickly failing job fails.

Actual behavior: No notification when the job fails. BTW, due to #1696 we get an notification for each job once all the jobs finish. Certainly don't want that, but we DO want the notification as soon as the job fails.

**Comment by BanzaiMan** [comment] 2016-04-27 08:43
Closing as duplicate of #4928.

**Closed by BanzaiMan** 2016-04-27 08:43 UTC
Labels: notifications
