### ISSUE TITLE
sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test" failed

### ISSUE THREAD

**Issue by nlohmann** [travis-ci/travis-ci#6253] opened 2016-07-02 15:23 UTC
Recently, a [build](https://travis-ci.org/nlohmann/json/jobs/141846775) fails with the following error

```
$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
Cannot add PPA: 'ppa:ubuntu-toolchain-r/test'.
Please check that the PPA name or format is correct.
The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .
```

**Comment by nlohmann** [comment] 2016-07-02 15:36
I restarted the job, and the error did not occur again. This still may be an issue.

**Comment by BanzaiMan** [comment] 2016-07-02 16:44
Most likely a network issue. If the problem is not occurring now, I'm closing this.

**Closed by BanzaiMan** 2016-07-02 16:44 UTC

**Comment by rubenvb** [comment] 2018-06-08 17:28
I got this error just ten minutes ago: https://travis-ci.org/skui-org/skui/jobs/389820363

**Comment by avengerweb** [comment] 2018-08-11 20:10
https://travis-ci.org/wowserhq/blizzardry/jobs/414948072

**Comment by Ruin0x11** [comment] 2018-08-12 00:49
Also happening for me.
https://travis-ci.org/ElonaFoobar/ElonaFoobar/jobs/414981040

**Comment by dtracers** [comment] 2019-05-16 18:04
https://travis-ci.org/SaltieRL/DistributedReplays/jobs/533444032
I got this issue too and this is not the first time I have gotten it.

**Comment by uhop** [comment] 2019-12-06 23:57
Now I am getting it: https://travis-ci.org/uhop/node-re2 &mdash; some tasks worked, some didn't. I tried to restart them still failed.

**Comment by uhop** [comment] 2019-12-06 23:58
BTW, they work for me locally.
