### ISSUE TITLE
"sudo apt-get update" failed and exited with 100 during .

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [travis-ci/travis-ci#7998] opened 2017-06-29 20:54 UTC
`sudo apt-get update` is currently broken it seems

```
Reading package lists... Done
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
N: Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://download.docker.com/linux/ubuntu trusty InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'edge/binary-i386/Packages' as repository 'https://download.docker.com/linux/ubuntu trusty InRelease' doesn't support architecture 'i386'
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/builds/sphinxsearch-rel20/ubuntu/dists/trusty/Release.gpg: Signature by key 2FE7BA61B28B34B7A2B749A2B9D8946B16932B16 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/builds/sphinxsearch-rel21/ubuntu/dists/trusty/Release.gpg: Signature by key 2FE7BA61B28B34B7A2B749A2B9D8946B16932B16 uses weak digest algorithm (SHA1)
E: Failed to fetch https://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update" failed and exited with 100 during .
Your build has been stopped.
```

Similar to https://github.com/travis-ci/travis-ci/issues/5287 although that is a bit outdated

**Comment by BanzaiMan** [comment] 2017-06-29 21:32
Duplicate of #7997.

**Closed by BanzaiMan** 2017-06-29 21:32 UTC
