### ISSUE TITLE
PyPy3 build error

### ISSUE THREAD

**Issue by amoffat** [travis-ci/travis-ci#7771] opened 2017-05-16 22:23 UTC
Hi, recently there's been a build error for `pypy3`: https://travis-ci.org/amoffat/sh/jobs/232286260

Relevant error:

```
    raise RuntimeError("Python 3.3 or later is required")
RuntimeError: Python 3.3 or later is required
```

It looks like pypy3 is using a pip version that hates python 3.0-3.2.  I'm guessing the fix would be to use a different pip version for that environment, otherwise it seems like `pypy3` will never work.  Any thoughts?

**Comment by BanzaiMan** [comment] 2017-06-08 13:49
This is basically a duplicate of #6865.

**Closed by BanzaiMan** 2017-06-08 13:49 UTC
Labels: python
