### ISSUE TITLE
F# build failing on Travis that uses portable FSharp.Core.dll references

### ISSUE THREAD

**Issue by 7sharp9** [travis-ci/travis-ci#4650] opened 2015-08-13 07:52 UTC
In an F# project that uses portable references a canonical path is used:

`$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll`

During a build this expands to:
`/usr/lib/mono/xbuild/../Reference Assemblies/Microsoft/FSharp/.NETCore/3.259.3.1/FSharp.Core.dll`

This location does not seem to exist in the travis mono package, you can see an error message in the build log:

```
HintPath /usr/lib/mono/xbuild/../Reference Assemblies/Microsoft/FSharp/.NETCore/3.259.3.1/FSharp.Core.dll does not exist.
```
https://travis-ci.org/functionauts/Result/jobs/75306328

The canonical path mentioned above works fine on Windows and osx and is the standard way of referencing FSharp.Core.dll.  Im unsure on how the mono package is installed but it would be great to get the location resolved on travis mono packages.

**Comment by paulyoung** [comment] 2015-08-13 08:28
cc'ing @joshua-anderson @akoeplinger @nterry, as per the message in the Travis build log.

**Comment by akoeplinger** [comment] 2015-08-20 14:16
This looks like a packaging bug on the Linux packages, but in the meantime you can just reference the portable FSharp.Core from the NuGet package in Result.fsproj:

```diff
- <HintPath>$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
+ <HintPath>../packages/FSharp.Core.3.1.2.1/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1/FSharp.Core.dll</HintPath>
```

**Comment by BanzaiMan** [comment] 2015-08-24 15:36
Is there anything for us to do?

**Comment by akoeplinger** [comment] 2015-08-24 15:37
@BanzaiMan nope, this can be closed as we can't do anything on the Travis side.

**Comment by BanzaiMan** [comment] 2015-08-24 16:05
Thanks!

**Closed by BanzaiMan** 2015-08-24 16:05 UTC
Labels: community:csharp

**Comment by paulyoung** [comment] 2015-08-26 21:45
I can confirm that the workaround suggested by @akoeplinger worked in my case.

**Comment by 7sharp9** [comment] 2015-08-26 22:17
Be sure to revert to the well known oath when the mono recipe is fixed.

**Comment by 7sharp9** [comment] 2015-08-26 22:18
"Path"

**Comment by paulyoung** [comment] 2015-08-26 22:43
@7sharp9 I tried to do the following but haven't been able to get it to work:

```xml
<Choose>
  <When Condition="Exists('$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll')">
    <HintPath>$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
  </When>
  <Otherwise>
    <HintPath>..\packages\FSharp.Core.3.1.2.1\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\FSharp.Core.dll</HintPath>
  </Otherwise>
</Choose>
```

**Comment by paulyoung** [comment] 2015-08-26 22:45
Currently looking into doing a similar thing except when the `TRAVIS` environment variable is `true`.

**Comment by paulyoung** [comment] 2015-08-26 22:54
For what it's worth, here's what I'm currently doing:

```xml
<Choose>
  <When Condition="Exists('HintPath>$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll')">
    <ItemGroup>
      <Reference Include="FSharp.Core">
        <Name>FSharp.Core</Name>
        <AssemblyName>FSharp.Core.dll</AssemblyName>
        <HintPath>$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
      </Reference>
    </ItemGroup>
  </When>
  <Otherwise>
    <ItemGroup>
      <Reference Include="FSharp.Core">
        <Name>FSharp.Core</Name>
        <AssemblyName>FSharp.Core.dll</AssemblyName>
        <HintPath>..\packages\FSharp.Core.3.1.2.1\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\FSharp.Core.dll</HintPath>
      </Reference>
    </ItemGroup>
  </Otherwise>
</Choose>
```

This appears to work.
