### ISSUE TITLE
sudo apt-get update failed when running travis-ci

### ISSUE THREAD

**Issue by liuzxc** [travis-ci/travis-ci#5287] opened 2015-12-14 15:07 UTC
CI build is always failed:
```
............
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  403  Forbidden [IP: 130.211.168.42 80]
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  403  Forbidden [IP: 130.211.168.42 80]
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  403  Forbidden [IP: 130.211.168.42 80]
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  403  Forbidden [IP: 130.211.168.42 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get update" failed and exited with 100 during .
Your build has been stopped.
```

any idea for this?

**Comment by stefanhorning** [comment] 2015-12-14 15:13
yes, it's currently broken, see here: https://github.com/travis-ci/travis-ci/issues/5285

**Comment by solarce** [comment] 2015-12-14 15:22
Duplicate of https://github.com/travis-ci/travis-ci/issues/5285

**Closed by solarce** 2015-12-14 15:22 UTC
