### ISSUE TITLE
Travis build giving random results

### ISSUE THREAD

**Issue by RamprasadAkella** [travis-ci/travis-ci#6157] opened 2016-06-11 15:57 UTC
I am using container based infrastructure, for one test case, I am starting 3 servers before starting the test case, but for some reason one of the servers is getting killed with no exception, can anyone suggest what might be the issue.@BanzaiMan

**Comment by BanzaiMan** [comment] 2016-06-11 16:30
Sorry, but please give more details about what you are doing, what you expect to happen, and what you are observing instead. There is no information with which we can investigate.

**Comment by RamprasadAkella** [comment] 2016-06-11 17:14
I am starting three servers in the before block of the test case (these servers are spawned in the travis build environment), and one of the servers is getting killed in the middle. This we are identifying by the process Ids. I expect this process not to be killed. The reason I am guessing it's killed is because of outOfMemory, but I don't see any log for that one. Is it possible in a container infrastructure that when there is a increase in memory limit, it causes one of the spawned servers to be killed ?  Also, is there anyway through which I can access the console logs of the spawned servers.

**Comment by BanzaiMan** [comment] 2016-06-13 22:15
Processes can be killed for many reasons. It can reach the limit imposed by the shell, or the VM host can kill processes due to excess resource usage. Sometimes you get the core dump, and sometimes you get nothing.

If the problem is consistent, I suggest you use GCE, which gives you more memory.

**Comment by BanzaiMan** [comment] 2016-06-20 23:11
If you need access to a live debug VM, please email support@travis-ci.com.

There is not much to do here, so I'm closing this.

**Closed by BanzaiMan** 2016-06-20 23:11 UTC

**Comment by RamprasadAkella** [comment] 2016-06-21 06:22
Thanks a lot @BanzaiMan. I reproduced travis environment in local using Docker, and found out that this issue is coming because of out of memory as we are starting many processes in the before block of each test case.
