### ISSUE TITLE
apt-get fails for oracle-java8-installer

### ISSUE THREAD

**Issue by Odinodin** [travis-ci/travis-ci#6849] opened 2016-11-10 17:31 UTC
Our build is configured to update jdk8 according to this comment https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-93881360

Specifically it is configured like this:

```
language: clojure

lein: 2.6.1

jdk:
  - oraclejdk8

install: true

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
```

Today the build started failing with the following error: 

```
Downloading Oracle Java 8...
--2016-11-10 14:25:53--  http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.62.239.8, 23.62.239.25
Connecting to download.oracle.com (download.oracle.com)|23.62.239.8|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz [following]
--2016-11-10 14:25:53--  https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.197.41.178, 2001:428:6402:19c::2d3e, 2001:428:6402:18c::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.197.41.178|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.oracle.com/splash/edelivery/index.html [following]
--2016-11-10 14:25:53--  https://www.oracle.com/splash/edelivery/index.html
Resolving www.oracle.com (www.oracle.com)... 23.197.41.178, 2001:428:6402:18c::2d3e, 2001:428:6402:19c::2d3e
Connecting to www.oracle.com (www.oracle.com)|23.197.41.178|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2016-11-10 14:25:54 ERROR 503: Service Unavailable.
```

Any suggestions for how to fix it?

**Comment by BanzaiMan** [comment] 2016-11-10 17:44
Closing as a duplicate of #6848.

**Closed by BanzaiMan** 2016-11-10 17:44 UTC
