### ISSUE TITLE
fatal:destination path 'firstgit' already exists and is not an empty directory

### ISSUE THREAD

**Issue by SivaVelsamy** [travis-ci/travis-ci#8763] opened 2017-11-15 05:11 UTC
I got this when I clone.I don't know what is the reason for this.So I need  help!

**Comment by BanzaiMan** [comment] 2017-11-15 05:30
Probably a duplicate of #2715.

**Comment by SivaVelsamy** [comment] 2017-11-15 12:01
Thx!Banzaiman...

**Comment by BanzaiMan** [comment] 2017-11-16 14:47
OK. I'm closing this as a duplicate.

**Closed by BanzaiMan** 2017-11-16 14:47 UTC
