### ISSUE TITLE
Can't install i386 packages on trusty

### ISSUE THREAD

**Issue by ciscoheat** [travis-ci/travis-ci#6131] opened 2016-06-04 14:36 UTC
I've scoured the web hard for a solution, but I can't find how to install packages like `libcurl3:i386` and `libglib2.0-0:i386` on trusty for travis. Installing them on precise has always worked fine.

This works locally:
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libcurl3:i386
```

But on travis, it gives this when doing the update:

```
W: There is no public key available for the following key IDs:
1397BC53640DB551
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Any ideas? Here's the actual build: https://travis-ci.org/back2dos/travix/jobs/135253264#L229-L306

**Comment by BanzaiMan** [comment] 2016-06-04 15:04
This is a duplicate of #6048. Please try the workaround suggested there.

**Closed by BanzaiMan** 2016-06-04 15:04 UTC
