### ISSUE TITLE
APT source whitelist request for ppa:smspillaz/cmake-3.0.2

### ISSUE THREAD

**Issue by m-kuhn** [travis-ci/travis-ci#4567] opened 2015-07-24 18:41 UTC

**Comment by BanzaiMan** [comment] 2015-07-24 21:38
Duplicate of #4167.

**Comment by BanzaiMan** [comment] 2015-07-24 21:38
Which has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/39.

**Closed by BanzaiMan** 2015-07-24 21:38 UTC
