### ISSUE TITLE
trusty: php 7.0 apcu.so is missing and phpunit is not upgraded to 6.x

### ISSUE THREAD

**Issue by c9s** [travis-ci/travis-ci#7744] opened 2017-05-10 17:30 UTC
php7.1 has apcu.so and phpunit 6.x preinstalled so I am wondering if we can fix the php 7.0 env

**Comment by BanzaiMan** [comment] 2017-05-10 18:20
I'm closing this as a duplicate of #7525.

The Trusty image has an older version of 7.0.x preinstalled (released before PHPUnit 6.x was). If you want a newer version, try a newer version of PHP (e.g., 7.0.17) or update PHPUnit yourself.

**Closed by BanzaiMan** 2017-05-10 18:20 UTC
