### ISSUE TITLE
Adding BitBucket support

### ISSUE THREAD

**Issue by mrjcleaver** [travis-ci/travis-ci#4170] opened 2015-07-01 17:17 UTC
I know you are just going to close this ticket as won't fix. 

Go right ahead.

**Comment by saltinejustine** [comment] 2015-07-01 17:20
This is a duplicate of an issue we've previously closed therefore closing this issue.

Unfortunately at this time we do not support Bitbucket and have no intentions to in the near future.

**Closed by saltinejustine** 2015-07-01 17:20 UTC
