### ISSUE TITLE
$TRAVIS_COMMIT_MESSAGE does not match custom commit message when triggering custom build

### ISSUE THREAD

**Issue by maxnorth** [travis-ci/travis-ci#10184] opened 2018-10-05 01:40 UTC
When triggering a custom build via the dashboard 'More Options > Trigger build' feature, if I specify a custom commit message for the build it does not use this value for the $TRAVIS_COMMIT_MESSAGE environment variable, it uses the commit message for the last pushed commit of the specified branch.

**Comment by BanzaiMan** [comment] 2018-10-28 13:02
Duplicate of #8641.

**Closed by BanzaiMan** 2018-10-28 13:02 UTC
