### ISSUE TITLE
Simple maven java project: error with JAVA_HOME

### ISSUE THREAD

**Issue by surli** [travis-ci/travis-ci#8466] opened 2017-09-20 08:28 UTC
I have a really simple maven project with the following .travis.yml config:
```yml
git:
  depth: 1

language: java 

jdk:
- oraclejdk7
```

And a standard pom.xml file, but I just had the following error: 
```
The JAVA_HOME environment variable is not defined correctly

This environment variable is needed to run this program

NB: JAVA_HOME should point to a JDK not a JRE

The command "eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V " failed. Retrying, 2 of 3.
```

Source: https://travis-ci.org/SpoonLabs/spoon-maven-plugin/builds/277648236

**Comment by BanzaiMan** [comment] 2017-09-20 08:41
Duplicate of #7884.

**Closed by BanzaiMan** 2017-09-20 08:41 UTC
