### ISSUE TITLE
Link to PR is broken for merge commits

### ISSUE THREAD

**Issue by bsipocz** [travis-ci/travis-ci#7604] opened 2017-04-11 21:23 UTC
At the "builds" panel, the links to the merged PRs is broken as ``[object Object]`` doesn't get substituted with the owner of the repo. The same links work fine in the pull requests panel.

**Comment by BanzaiMan** [comment] 2017-04-12 10:21
Duplicate of #7415.

**Closed by BanzaiMan** 2017-04-12 10:21 UTC

**Comment by bsipocz** [comment] 2017-04-12 11:01
Oops, sorry I didn't looked that far back in the issues list.
