### ISSUE TITLE
Build not starting on OS X

### ISSUE THREAD

**Issue by JokerQyou** [travis-ci/travis-ci#6841] opened 2016-11-08 16:26 UTC
This build https://travis-ci.org/Microcore/KeyCounter/builds/174250342 does not start after being accepted for more than 20 minutes. As I see from https://www.traviscistatus.com/ your load of OS X machines is falling, so I don't quite understand. Is there an error in my config file?

**Comment by BanzaiMan** [comment] 2016-11-09 12:20
We tend to have a long queue on OS X builds during the US work day. 20 minutes is not uncommon at the moment, unfortunately. We are working on addressing this issue, but until then some delays are expected.

**Comment by JokerQyou** [comment] 2016-11-10 01:06
But it seems this build has been waiting for hours ( I think it's more than 6 hours and 20 minutes ) before it falls into the state of "error".

**Comment by jagerman** [comment] 2016-11-15 20:24
Could traviscistatus be updated to report the number of queued jobs?  For example, by adding something like "Queued jobs: 123" as a second line in the mouseover for the "Active <whatever> builds for Open Source projects" graphs?

Even better would be to also report the most recent queue wait time, so something like: "Queue: 123 jobs; last delay 43 minutes".

**Comment by whisperity** [comment] 2017-02-17 12:35
This issue is still happening from time to time. May I suggest an extra configuration option which allows us to mark the build _Successful_ if the OSX build couldn't start? So basically:

 * (anything) & osx build fails :arrow_right: build fail
 * (everything else successful) & osx build doesn't start :arrow_right: build successful
 * everything successful :arrow_right: build successful

**Comment by Lyoness** [comment] 2018-01-30 14:04
I'm closing this out because we've just migrated to a new datacenter which will fix queue times and boot times.

**Closed** 2018-01-30 14:03 UTC
Labels: mac

**Comment by DanySK** [comment] 2019-10-21 19:20
I believe the issue is currently ongoing, I got some builds waiting for well over one hour.

**Comment by dargueta** [comment] 2019-10-23 20:20
Same -- I started having this problem beginning about six days ago. A week ago OSX builds started pretty quickly but now it varies a lot. Sometimes it's only a ten-minute delay (rare) other times it's an hour (more common) or more.
