### ISSUE TITLE
Python 3.5/3.6 virtualenvs not available for different python versions

### ISSUE THREAD

**Issue by rpkilby** [travis-ci/travis-ci#7146] opened 2017-01-12 21:16 UTC
Regardless of the python version selected for a build job, it seems like all versions of python are made available through separate virtualenvs. eg, a job may run under python 3.4, but the python 2.7, 3.2, and 3.3 interpreters would also be available. This has been useful for tox integration. 

While most python versions are available, this doesn't seem to apply to the python 3.5 and 3.6 interpreters. See the below for example build failures:
1. https://travis-ci.org/tomchristie/django-rest-framework/builds/191387262
    python 3.5 - you'll notice that [this](https://travis-ci.org/tomchristie/django-rest-framework/jobs/191387279) job fails since python 3.6 cannot be found. Jobs using python 2.7, 3.3, and 3.4 are not affected.
2. https://travis-ci.org/tomchristie/django-rest-framework/builds/191420758
    python 3.6 - similar to the above, except jobs using python 3.5 now fail. 
3. https://travis-ci.org/tomchristie/django-rest-framework/builds/191424689
    python 2.7 - jobs using python 3.5 and 3.6 now fail.

It's not clear to me what is failing here. Is there an issue with python 3.5/3.6 being added to the path?

What should be the expected behavior here? Should users expect all versions of python to be available, or should they expect *just* the specified version?

**Comment by BanzaiMan** [comment] 2017-01-16 00:47
Some Python versions are provided on-demand when you set the `python` values appropriately, because those runtimes are not available on the build images.

As we update the build images, they will be available everywhere.

**Comment by shish** [comment] 2017-01-21 11:52
Now that 3.6 is stable (and 3.5 has been for a while), can they be added to the base images? I'd also like this for a different reason -- I'm using the image from quay.io to build a travis-compatible `python3.5-opencv` package, and I'm not sure that my python3.5 setup is identical to yours.

(This is what I'm doing to build a "fake travis-python+3.5" image: http://stackoverflow.com/questions/41635824/travis-docker-image-missing-python-3-5 )

**Comment by BanzaiMan** [comment] 2017-01-21 15:20
I'm closing this as a duplicate of #4990.

**Closed by BanzaiMan** 2017-01-21 15:20 UTC
Labels: python
