### ISSUE TITLE
Build crashed on release and branch

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#7309] opened 2017-02-12 15:18 UTC
https://travis-ci.org/LolexOrg/Lolex-Tools/jobs/200095183
Not sure why this happened but the other jobs failed too.

**Comment by BanzaiMan** [comment] 2017-02-12 23:39
I think this is a duplicate of https://github.com/travis-ci/travis-ci/issues/1590, where a branch and a tag share the same name.

**Comment by BanzaiMan** [comment] 2017-02-14 12:44
Closing this as a duplicate. If you believe there is a reason to suggest otherwise, do let us know.

**Closed by BanzaiMan** 2017-02-14 12:44 UTC
