### ISSUE TITLE
apt.llvm.org is very frequently unavailable

### ISSUE THREAD

**Issue by marco-c** [travis-ci/travis-ci#9019] opened 2018-01-08 15:53 UTC
This breaks https://github.com/marco-c/grcov builds very often (there are 6 builds in the matrix, every time I push something at least one of them fails to install LLVM).

Are there any plans to solve this issue? E.g. providing images with newer versions of Clang pre-installed?

**Comment by BanzaiMan** [comment] 2018-01-08 15:54
Probably a different manifestation of #9000. I'm closing this as a duplicate.

**Closed by BanzaiMan** 2018-01-08 15:54 UTC

**Comment by sylvestre** [comment] 2018-03-01 20:32
@marco-c it was caused by the cdn used by apt.llvm.org
it should be fixed now
