### ISSUE TITLE
OSX -> macOS

### ISSUE THREAD

**Issue by fulldecent** [travis-ci/travis-ci#7929] opened 2017-06-20 14:34 UTC
This is related to https://github.com/travis-ci/travis-web

OSX is the old naming, macOS is the old naming.

For the web front end, all occurrences of OSX should be replaced to macOS.

**Comment by BanzaiMan** [comment] 2017-06-20 14:51
Thanks for taking time to open this issue. I'm closing this as a duplicate of https://github.com/travis-ci/docs-travis-ci-com/issues/766.

**Closed by BanzaiMan** 2017-06-20 14:51 UTC
