### ISSUE TITLE
before_deploy not being run

### ISSUE THREAD

**Issue by linearregression** [travis-ci/travis-ci#5398] opened 2016-01-03 23:20 UTC
TravisCI build link:
https://travis-ci.org/linearregression/travis_elixir_plt_generator/builds/100015119
I am using travis.yml:
https://github.com/linearregression/travis_elixir_plt_generator/blob/23c5cf8531b043506b58dc26079dd1ba9ed1a9dc/.travis.yml
Issue:
It looks like before_deploy is never called.
Nothing echoed back within the before_deploy block

**Comment by BanzaiMan** [comment] 2016-01-03 23:28
Looks like a duplicate of #5397. The build in question is not a tagged build, so deployment is not triggered.

**Closed by BanzaiMan** 2016-01-03 23:28 UTC
