### ISSUE TITLE
add environment variable for stage name

### ISSUE THREAD

**Issue by gr2m** [travis-ci/travis-ci#8246] opened 2017-08-12 21:50 UTC
Hello friends 👋 

I currently can’t find a way to know if my script is run in a stage or not. The reason I need to know is that I’d like to make [semantic-release](https://github.com/semantic-release/semantic-release) optionally work with Travis Stages. It currently has a check to only run the publish on the first build by checking if the build numbers ends with `.1`, but stages continue adding the decimal number so `semantic-release` currently fails. If I could check whether the script is run in a stage I could work around the [check to only run on one job](https://github.com/semantic-release/condition-travis/blob/7ede54c09cbaac06cc31b6d122df608e09828b54/index.js#L46) entirely :)

**Comment by BanzaiMan** [comment] 2017-08-12 23:03
I'm closing this as a duplicate of #8239.

**Closed by BanzaiMan** 2017-08-12 23:03 UTC

**Comment by gr2m** [comment] 2017-08-12 23:23
Thanks and sorry that I didn’t find it myself. Just fyi, GitHub has an official way now to mark issues as duplicates: https://github.com/blog/2398-better-manage-issues-and-pull-requests-with-keyword-updates
