### ISSUE TITLE
C#: config not being used

### ISSUE THREAD

**Issue by OskarKlintrot** [travis-ci/travis-ci#7797] opened 2017-05-22 13:22 UTC
I'm trying to use Travic for CI for a dotnet core project that is using CAKE for build. Travis doesn't seem to be using the settings from the config file though. I started trying with a [`.travis.yml` file from SO](https://stackoverflow.com/questions/38652094/getting-cakes-build-cake-and-asp-net-core-to-work-on-travis-ci):

```
language: csharp

script:
  - ./src/build.sh

cache:
  directories:
    - ./src/tools
```

I have also tried to specify dist etc to see if Travis would behave in a different way:

```
language: csharp
mono: none
dotnet: 1.1.1
dist: trusty
solution: .src/Intranet.sln

before_script:
  - chmod a+x ./src/build.sh

script:
  - ./src/build.sh

cache:
  directories:
    - ./src/tools
```

However the tab `View config` always says this:

```
{
  "language": "csharp",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```

If a push an empty file then `language` will change to `ruby` but that's it. [Travis is always installing Mono and ends with the following message](https://travis-ci.org/Certaincy/Intranet/jobs/234817108):

```
No solution or script defined, exiting
```

ping @joshua-anderson @akoeplinger @nterry

**Comment by BanzaiMan** [comment] 2017-05-22 13:38
This is a duplicate of #4839; your [`.travis.yml`](https://raw.githubusercontent.com/Certaincy/Intranet/d00dcf6be7fdb825a2a49f11390c72c59ca2c261/.travis.yml) has a BOM, and only the `language` key is recognized. Remove BOM, and the build should go as you intended.

**Comment by BanzaiMan** [comment] 2017-05-22 13:40
I've reopened #4839. I'm closing this as a duplicate, however.

**Closed by BanzaiMan** 2017-05-22 13:40 UTC
