### ISSUE TITLE
how to build more than 50 mins

### ISSUE THREAD

**Issue by kevin-leptons** [travis-ci/travis-ci#5912] opened 2016-04-15 14:04 UTC
i am building [lfs-auto](https://github.com/kevin-leptons/lfs-auto)

my build take more than 50 mins, and i can not make paralell  build because next package build depend on prev package installed or not. you can see build [here](https://travis-ci.org/kevin-leptons/lfs-auto/builds/123358920)

how to build more than 50 mins in this case ?. i was watch build more than 1 hours here [AscEmu](https://travis-ci.org/AscEmu/AscEmu/builds/115501394)

**Comment by BanzaiMan** [comment] 2016-04-28 07:35
Closing as a duplicate of #5700.

**Closed by BanzaiMan** 2016-04-28 07:35 UTC
