### ISSUE TITLE
Certificate error with github

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#10233] opened 2018-10-12 18:26 UTC
I'm trying to upload release assets manually to github but I get a certificate error:

> requests.exceptions.SSLError: hostname 'uploads.github.com' doesn't match either of '*.githubusercontent.com', 'githubusercontent.com'

Is there some certificate issue on the travis side?

**Comment by BanzaiMan** [comment] 2018-10-12 18:38
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by Flamefire** [comment] 2018-10-12 18:40
Sure, sorry I thought the description was enough. Example is here: https://travis-ci.com/Flamefire/release-tests/jobs/151523149 (see the `githubrelease` call at the bottom)

**Comment by BanzaiMan** [comment] 2018-10-12 19:49
Seems like a temporary name resolution error, no? Within the same build, I see that a subsequent try worked https://travis-ci.com/Flamefire/release-tests/jobs/151523152#L585.

**Comment by Flamefire** [comment] 2018-10-13 06:38
This is different. The release process is:

1. Create (as draft)
2. Upload assets -> Fails
3. Publish

The uploading does use a different host as per Githubs Release API

**Comment by BanzaiMan** [comment] 2018-10-13 20:30
What I meant was: at some points in time, the server that responded to `uploads.github.com` name had the certificate that only had `'*.githubusercontent.com', 'githubusercontent.com'` instead of the correct wild card `*.github.com`.

I don't think there is anything for us to do here.

**Comment by Flamefire** [comment] 2018-10-14 08:07
Well, can't you flush the certificate storage on the build servers? I found that it only affects python2 not python3. So I guess the servers cached these wrong certificates. This failure just happened and is reproducible.

**Comment by BanzaiMan** [comment] 2018-10-15 13:36
Could you elaborate on this

> I found that it only affects python2 not python3.

and this?

> So I guess the servers cached these wrong certificates. This failure just happened and is reproducible.

If it is an issue with DNS cache, it doesn't seem likely to me that it is reproducible, unless you somehow can force the use of servers with stale cache.

If it *_is_* reproducible, what are the conditions that lead to the error?

**Comment by Flamefire** [comment] 2018-10-15 16:07
Test here: https://travis-ci.com/Flamefire/travis_test

I added 3 uploads with different pythons (via pyenv):

- System python
- Python 2.7
- Python 3.4

The first 2 fail with the mentioned error, the last succeeds.

Tell me if you need any more info

**Comment by BanzaiMan** [comment] 2018-10-28 12:51
I think this is due to an older version of Python 2.7. See https://github.com/travis-ci/travis-ci/issues/10141#issuecomment-424028581 for an explanation. For workarounds, see https://github.com/travis-ci/travis-ci/issues/9836#issuecomment-425765758; in addition, you may try adjusting your builds to run with `language: python`, so that you can specify a newer version of Python that can handle this.

**Comment by DrTorte** [comment] 2018-11-27 23:07
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Closed by DrTorte** 2018-11-27 23:07 UTC
Labels: python
