### ISSUE TITLE
Can not cancel build anymore when one failed with fast_finish

### ISSUE THREAD

**Issue by nickvergessen** [travis-ci/travis-ci#2658] opened 2014-08-11 17:21 UTC
The "Cancel build" option is swapped for "Restart build".
However if one test failes it might fail in other enviroments aswell.
Developers could save some time for the travis works if they could still cancel the full build suite with one click.

I guess most devs wont open the other builds to cancel them manually.

**Comment by BanzaiMan** [comment] 2015-02-22 23:45
Could someone show a reliable way to reproduce this?

**Comment by joshk** [comment] 2015-02-23 02:08
@BanzaiMan this is a confirmed bug.

This is essentially an issue with how `fast_finish` works. The solution would possibly mean adding an option to auto cancel remaining jobs. This might be worth looking into after `travis-core` is removed from `travis-hub`.

**Comment by joshk** [comment] 2015-02-23 02:10
Ok, I need to learn to read things better. Yes, this is a bug and is something we should fix.

I'll talk to the team about it and see what we can do.

**Comment by mtola** [comment] 2016-05-14 08:41
so what's new for that because, yes, fast_finish: true don't work :-(

**Comment by joepvd** [comment] 2016-09-20 21:41
Fixed with https://github.com/travis-ci/travis-web/pull/334

**Closed by joepvd** 2016-09-20 21:41 UTC
Labels: bug, team teal, ui
