### ISSUE TITLE
[Node.js builds] make build fail if nvm install fails

### ISSUE THREAD

**Issue by gr2m** [travis-ci/travis-ci#7577] opened 2017-04-05 18:02 UTC
Around 18h ago, several builds on travis were failing because the configured Node versions could not be downloaded via `nvm`, see https://github.com/nodejs/nodejs.org/issues/1191#issuecomment-291657788

Here is an example of how that looked like:
https://travis-ci.org/hoodiehq/hoodie-account-client/builds/218684940#L144

The outcome was that the build was run using the default Node version which currently seems to be `v0.10.36` (https://travis-ci.org/hoodiehq/hoodie-account-client/builds/218684940#L167)

I would suggest to make builds fail if the nvm install fails, with an error message that points to the problem at hand. Would that be possible?

**Comment by BanzaiMan** [comment] 2017-04-05 18:06
Duplicate of https://github.com/travis-ci/travis-ci/issues/7001#issuecomment-266431672.

**Closed by BanzaiMan** 2017-04-05 18:06 UTC
