### ISSUE TITLE
pip missing on new OSX default image xcode8.3

### ISSUE THREAD

**Issue by t20100** [travis-ci/travis-ci#8835] opened 2017-11-30 10:28 UTC
We test our python project with Travis-CI.
The new OSX default image xcode8.3 is missing `pip` which was available previously (error message below).
Is this expected? Do we have to install it ourself with get-pip.py?

```
$ python -m pip install --upgrade pip
/usr/bin/python: No module named pip
```
or
```
$ pip install --upgrade pip
/Users/travis/.travis/job_stages: line 57: pip: command not found
```

Our travis config: https://github.com/silx-kit/silx/blob/master/.travis.yml

**Comment by BanzaiMan** [comment] 2017-11-30 13:38
A duplicate of #8829. We don't support this setup, so you are responsible for providing `pip`. Thanks.

**Closed by BanzaiMan** 2017-11-30 13:38 UTC
