### ISSUE TITLE
Unable to retrigger jobs for a pull request I created

### ISSUE THREAD

**Issue by edmorley** [travis-ci/travis-ci#5169] opened 2015-11-25 18:51 UTC
I've opened a pull request against a project where I do not have commit access. One of the jobs failed due to a network issue, so I want to retrigger it -- but even though it's my PR, Travis isn't giving me the option to do so:
https://github.com/marcgibbons/django-rest-swagger/pull/381
https://travis-ci.org/marcgibbons/django-rest-swagger/builds/93179075

My only option is to amend the commit (eg add whitespace in the commit message) and force push to the branch, to force the whole PR test run to be repeated. This would be pretty wasteful, since it will result in 72 unnecessary test jobs (the testing matrix for this project is extremely large) taking almost 2 hours of compute time - when all I need is one ~60s job retriggered.

**Comment by BanzaiMan** [comment] 2015-11-25 19:20
This is a duplicate of #887. For now, please ask a repo owner to restart the job.

**Closed by BanzaiMan** 2015-11-25 19:20 UTC
