### ISSUE TITLE
Button used to abort tests isn't centered

### ISSUE THREAD

**Issue by kiler129** [travis-ci/travis-ci#4994] opened 2015-10-22 10:31 UTC
Don't laugh at me, but I discovered that following button is misaligned :)

<img width="93" alt="screenshot 2015-10-22 12 26 25" src="https://cloud.githubusercontent.com/assets/1227834/10663026/ac393608-78b8-11e5-9fe0-2487830e1e34.png">

Yup, grid confirmed it's not an optical illusion:
<img width="468" alt="screenshot 2015-10-22 12 30 49" src="https://cloud.githubusercontent.com/assets/1227834/10663040/c17f25c2-78b8-11e5-9aac-abfd386c2824.png">

**Comment by joshk** [comment] 2015-10-22 10:58
We don't laugh at you at all! Thank you for creating this, we will get it fixed today!

**Comment by BanzaiMan** [comment] 2015-10-22 11:41
Hello! This is a duplicate of #4150.

**Closed by BanzaiMan** 2015-10-22 11:41 UTC
