### ISSUE TITLE
PHP5.3 doesn't install into Trusty

### ISSUE THREAD

**Issue by dvdoug** [travis-ci/travis-ci#8340] opened 2017-09-04 10:02 UTC
See e.g. https://travis-ci.org/dvdoug/StringStream/jobs/271481496

Log gives

```
0.02s$ phpenv global 5.3 2>/dev/null

5.3 is not pre-installed; installing

Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.3.tar.bz2

0.16s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /

bzip2: (stdin) is not a bzip2 file.

tar: Child returned status 2

tar: Error is not recoverable: exiting now

0.00s

0.02s$ phpenv global 5.3

rbenv: version `5.3' not installed

The command "phpenv global 5.3" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by BanzaiMan** [comment] 2017-09-04 12:45
Duplicate of #8072, #8219.

This should be more clearly indicated. Will follow up in #8072.

**Closed by BanzaiMan** 2017-09-04 12:45 UTC
