### ISSUE TITLE
Using JRuby is extremely slow

### ISSUE THREAD

**Issue by alex** [travis-ci/travis-ci#4960] opened 2015-10-16 15:36 UTC
Right now every build that uses `jruby` needs to download and install it from scratch, this takes nearly 3 minutes:

https://travis-ci.org/department-of-veterans-affairs/caseflow/builds/85755403#L97

is there some way caching or something could be applied to this to speed it up?

**Comment by BanzaiMan** [comment] 2015-10-19 16:30
@alex Unfortunately, RVM needs to download and configure the runtime if it's not pre-installed. We are working on the next build environment updates, but until then, we do not have a good workaround.

**Comment by alex** [comment] 2015-10-19 16:50
@BanzaiMan, @meatballhat: Is there a way to leverage caching to fix this?

**Comment by alex** [comment] 2016-01-15 14:50
Is there any news on the build environment updates?

**Comment by BanzaiMan** [comment] 2016-05-06 22:11
Hey, @alex. No news for the update, but I think the issue is that there is not enough entropy in `/dev/random`. See https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm for how to fix it.

I'm closing this now optimistically.

**Closed by BanzaiMan** 2016-05-06 22:11 UTC
Labels: build environment, travis-cookbooks

**Comment by alex** [comment] 2016-05-07 02:12
Interesting, thanks.

On Fri, May 6, 2016 at 6:11 PM, Hiro Asari <notifications@github.com> wrote:

> Hey, @alex <https://github.com/alex>. No news for the update, but I think
> the issue is that there is not enough entropy in /dev/random. See
> https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm
> for how to fix it.
>
> I'm closing this now optimistically.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/4960#issuecomment-217575552>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6
