### ISSUE TITLE
Possibility to build any commit

### ISSUE THREAD

**Issue by MitchK** [travis-ci/travis-ci#3919] opened 2015-05-18 11:19 UTC
Currently when activating a repo on Travis CI, an artificial commit needs to be created in order to trigger the build, especially if the ```.travis.yml``` has been created before the repo was activated. This often happens with forks, where the ```.travis.yml``` already exists and I don't want to create an artificial commit.

Is there already a possibility to avoid this?

**Comment by BanzaiMan** [comment] 2015-05-18 11:38
Sounds like a duplicate of #714. There are some ideas to make this happen, and it is on the roadmap, but there is no ETA.

You can create an empty commit and push that, if you don't want to taint the source unnecessarily.

**Comment by BanzaiMan** [comment] 2015-07-11 13:51
Closing as duplicate.

**Closed by BanzaiMan** 2015-07-11 13:51 UTC
