### ISSUE TITLE
Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by attiks** [travis-ci/travis-ci#10198] opened 2018-10-08 07:01 UTC
Since last week we're seeing "Expected — Waiting for status to be reported", although the checks are passing: "Some checks haven’t completed yet, 1 expected and 2 successful checks"

So we can no longer merge (unless super admins)

Repo is private, https://github.com/UN-OCHA/unocha-org/pull/732

AFAIK no settings changed on Github and Travis side

All advice appreciated.

**Comment by attiks** [comment] 2018-10-08 07:03
![screenshot from 2018-10-08 09-03-15](https://user-images.githubusercontent.com/105144/46595518-08d9b700-cad9-11e8-9322-80cf9eafd27a.png)

**Comment by DimitarD** [comment] 2018-10-08 07:29
This also currently occurs in our own private repository.

**Comment by adrienjoly** [comment] 2018-10-08 07:32
Same for all our PRs, on our private repository... I just sent a message to travis-ci's support and hope that this will be fixed soon.

**Comment by vitorreis** [comment] 2018-10-08 09:04
It's also happening at our repos.

**Comment by mjenny** [comment] 2018-10-08 10:55
It is happening to us as well:
![image](https://user-images.githubusercontent.com/4191545/46605325-71389080-caf9-11e8-9440-d948f85ad228.png)

**Comment by BanzaiMan** [comment] 2018-10-08 12:14
Hello there. This is most likely a duplicate of https://github.com/travis-ci/travis-ci/issues/10187#issuecomment-427471218. I'm closing as such.

**Closed by BanzaiMan** 2018-10-08 12:14 UTC

**Comment by attiks** [comment] 2018-10-08 12:18
Thanks @BanzaiMan
