### ISSUE TITLE
Travis starting error

### ISSUE THREAD

**Issue by dpolivaev** [travis-ci/travis-ci#8992] opened 2018-01-01 10:02 UTC
https://travis-ci.org/freeplane/freeplane/builds/323744623
"could not create session key: disk quota exceeded"

~~~~
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: 609d63b2-501a-4fcd-bac8-8f593d9ff302@1.i-0f8b0ff-production-2-worker-org-ec2.travisci.net
version: v3.4.0 https://github.com/travis-ci/worker/tree/ce0440bc30c289a49a9b0c21e4e1e6f7d7825101
instance: eb6cbed travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 669.497165ms
travis_fold:end:worker_info
[0Koci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"
~~~~

**Comment by matthew-brett** [comment] 2018-01-01 12:10
Likewise:

* https://travis-ci.org/matthew-brett/nb2plots/jobs/323694309
* https://travis-ci.org/scipy/scipy/jobs/323743227

I've sent an email to support@travis-ci.com

**Comment by mernst** [comment] 2018-01-01 16:08
I'm also having this problem: https://travis-ci.org/typetests/plume-lib-typecheck/builds/323629814
Possibly related: https://github.com/travis-ci/travis-ci/issues/8991

**Comment by xoviat** [comment] 2018-01-01 18:24
The "Travis CI status" says "all systems operational." IMO all systems are not operational. Something is definitely wrong,

**Comment by magneticflux-** [comment] 2018-01-01 18:33
I'm having the same issue. The charts on https://www.traviscistatus.com/ have plummeted and all my builds are reporting as "errored" without even booting.

**Comment by BorzdeG** [comment] 2018-01-01 19:06
sample job: https://travis-ci.org/itbasis/java-module-gradle-plugin/jobs/323854641

**Comment by BanzaiMan** [comment] 2018-01-01 20:15
Sorry for the troubles, everyone. I'm closing this as a duplicate of #8991, so that info can be found in one place.

**Closed by BanzaiMan** 2018-01-01 20:15 UTC
