### ISSUE TITLE
Update Git

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-ci#6328] opened 2016-07-18 07:53 UTC
Please update Git to 2.9.1 or newer. We got report that [the following fix](https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.1.txt):

> Fix an unintended regression in v2.9 that breaks "clone --depth" that recurses down to submodules by forcing the submodules to also be cloned shallowly, which many server instances that host upstream of the submodules are not prepared for.

Would prevent some build failures.

**Comment by mrhyde** [comment] 2016-08-25 16:47
Is there any reason we are still using git version that was released almost 3 years ago?

**Comment by BanzaiMan** [comment] 2016-08-25 17:30
@mrhyde For a while, we had to stay with an old `git` version to ensure that deployment worked with Heroku. I must say that we have not tested this portion in a while, so that reason may no longer be valid.

**Comment by ArmorDarks** [comment] 2016-08-25 20:22
@BanzaiMan That would be great, since all other services already moved on to newer version, and it becomes quite hard to provide working git commands for Travis and those other services... Not to mention that git now works inconsistently in Travis and local environment...

**Comment by mrhyde** [comment] 2016-08-25 23:14
@BanzaiMan The problem is that in travis docker containers it's impossible to install a newer version of git  since it's impossible to `sudo` and I was unable to find cookbooks for travis is using for docker containers... If there is such thing I will gladly contribute and submit a PR

**Comment by BanzaiMan** [comment] 2016-08-30 21:38
Looks like Heroku's `git` strategy still has a problem with `git` 2.9.3. https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/156354798#L358-L369

I do note that if I try the identical deployment with `git` (with the same version), the deployment works.

**Comment by ArmorDarks** [comment] 2016-08-30 21:45
Is Heroku support aware of issue? [Not super relevant place](https://github.com/heroku/heroku) to post, but worth a try

**Comment by BanzaiMan** [comment] 2016-08-30 21:53
Yes, I have opened a support ticket with Heroku. I'll update here if we have any breakthrough.

**Comment by ArmorDarks** [comment] 2016-08-30 22:08
You can ref it here, just in case

**Comment by jeffhammond** [comment] 2016-10-04 20:50
@mrhyde 

> The problem is that in travis docker containers it's impossible to install a newer version of git since it's impossible to `sudo` ...

You can always [build Git from source](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#Installing-from-Source).  Granted, that means you either have to get the dependencies, which either requires them to be whitelisted, or you can in-turn build those from source.  As Git does not depend on any kernel modules, you should be able to build all of its dependencies in userspace.

You may find building all your userspace dependencies from source *discouraging* but it is not *impossible*.  I build an absurd [amount of stuff](https://github.com/ParRes/Kernels/tree/master/travis) from source in order to use containers.  This currently does not include Git, but I've built Git from source many times in the past when the system installation was inadequate.

**Comment by mrhyde** [comment] 2016-10-05 12:00
Travis is a slowest CI platform so far and building git from source will make builds run for an absurd amount of time to the point of making them unusable in testing. But thank you for suggestion.

**Comment by jeffhammond** [comment] 2016-10-05 12:19
@mrhyde You don't have to build dependencies every time if you use [caching](https://docs.travis-ci.com/user/caching/).

**Comment by BanzaiMan** [comment] 2016-10-05 14:35
@mrhyde I've worked with Heroku support to eradicate the git issue. The images still needs to be updated with a newer version, which will be addressed in https://github.com/travis-ci/packer-templates/issues/303.

**Comment by BanzaiMan** [comment] 2016-10-05 14:42
@mrhyde I'm curious to know if your build requires git 2.x.

**Comment by mrhyde** [comment] 2016-10-05 16:19
@BanzaiMan We are using multiple CI platforms for testing and having different versions of git cause some issues, so we were forced to make some hacks to make our builds work on Travis. Updating git to 2.9.1 or newer would be definitely appreciated.

**Comment by shellscape** [comment] 2016-11-11 18:06
I can't even perform simple diff-tree commands that work on every version since 2.0. When are we going to see an update?

**Comment by jola5** [comment] 2017-08-10 21:52
Any progress on getting git to 2.x? There hasn't been an update for a long time and the related https://github.com/travis-ci/packer-templates/issues/303 issue is closed. 
Personally I need git >= 2.7 for `git tag --list --merged`.

**Comment by ArmorDarks** [comment] 2018-04-13 09:08
Wat?

**Comment by jvenezia** [comment] 2018-04-27 09:41
I have a git extensions library with unit tests, tests are broken on travis because git version is too old...
Is there any way to choose which git version to use?

**Comment by ArmorDarks** [comment] 2018-04-27 09:51
@BanzaiMan ping. Can you reopen issue, please?

**Comment by chenrui333** [comment] 2018-06-13 10:37
where are we on this?

**Comment by domwashburn** [comment] 2018-06-29 12:06
I can’t get the latest version to semantic release to work because the GIT version is too old. 

It’s insanely frustrating to have completed all the build setup and CI integration only to be blocked by something totally out of my control. 

I guess for now I’ll downgrade and lock semantic release related packages...but this is a huge blocker and seems like it’s becominng a pattern.

**Comment by domwashburn** [comment] 2018-06-29 12:14
@jeffhammond

> I've built Git from source many times in the past when the system installation was inadequate.

I agree that it’ll most likely make the build run forever... but how?

@travis-cig can we re-open this...?

**Comment by domwashburn** [comment] 2018-07-09 20:12
@renee-travisci @travis-ci Is this going to get fixed any time soon? I'm blocked on using new features for semantic release that allow for pre-release tags because your tool is lagging behind...

**Comment by domwashburn** [comment] 2018-07-16 19:47
Is this ever going to get addressed??

**Comment by chenrui333** [comment] 2018-10-14 21:16
+1

**Comment by stsewd** [comment] 2018-10-29 23:56
We also need this on Read the Docs https://github.com/rtfd/readthedocs.org/pull/4811

**Comment by BanzaiMan** [comment] 2018-10-30 01:41
Current Trusty images have git 2.15.1. If you need a newer version, run `sudo apt-get install git` and you'll get the most up-to-date release (currently at 2.19.1). This takes about 20 seconds. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/448120507#L441

Precise images don't get that, but I suppose you are not looking for advice for Precise builds.

**Comment by stsewd** [comment] 2018-10-30 01:52
@BanzaiMan it worked :tada:, thanks a lot!

**Closed** 2018-11-13 17:25 UTC
Labels: upgrade-request
