### ISSUE TITLE
debug when failed

### ISSUE THREAD

**Issue by calidion** [travis-ci/travis-ci#4931] opened 2015-10-13 15:59 UTC
travis-ci failed are currently none debuggable.
so some times we don't know what the problem is.

please add debug support for failed projects.

**Comment by BanzaiMan** [comment] 2015-10-19 14:00
Thanks for opening this issue. This is one of the older outstanding requests, and it is on our roadmap, but there is no ETA. I am closing this as a duplicate of #761.

**Closed by BanzaiMan** 2015-10-19 14:00 UTC
