### ISSUE TITLE
IPv6 lack in GCE

### ISSUE THREAD

**Issue by mcr** [travis-ci/travis-ci#5261] opened 2015-12-10 00:39 UTC
I noticed that no only is there no IPv6, but it appears that "lo" has IPv6 disabled, so I think you can not even bind to ::1.  This will set back IPv6 regression testing for some projects, I suspect.  Is this something GCE does, or is it under your control?  

It was mentioned that you considered ways of getting IPv6 in; I guess tunnels.  Can you tell say more about what was considered, and why it was not acceptable... perhaps the IPv6 community can help do something?
Has Google said what the block on IPv6 at GCE is?  I know that ganeti is weak (but not totally lacking) in this area, but I don't know what's really underneath GCE.

**Comment by Joshua-Anderson** [comment] 2015-12-10 00:46
This is probably a dupe of #3302. I don't think travis can do much unless gce and aws decide to support ipv6.

**Comment by BanzaiMan** [comment] 2015-12-10 00:50
This is a duplicate of previous issues, such as #4964 and #5200.

**Closed by BanzaiMan** 2015-12-10 00:50 UTC
