### ISSUE TITLE
TRAVIS_OS_NAME is an array in matrix.include jobs

### ISSUE THREAD

**Issue by mockdeep** [travis-ci/travis-ci#4627] opened 2015-08-07 03:12 UTC
I'm having some trouble getting an `include:` build running on our repo. It looks like the environment variable `$TRAVIS_OS_NAME` is being returned as a JSON array instead of just a string os. In the normal builds it is `"linux"`, but in the `include:` build it comes through as `"[\"linux\"]"`.

Build here: https://travis-ci.org/rmagick/rmagick/jobs/74477667
Commit here: https://github.com/rmagick/rmagick/commit/7c0492004a1d9c22be3bf97fccaa13fdce2dcc09

**Comment by joshk** [comment] 2015-08-07 03:32
Very interesting, thank you for reporting this.

@BanzaiMan can you please add this to the sapphire backlog?

**Comment by BanzaiMan** [comment] 2015-08-07 03:44
I've confirmed this bug.

For the time being, please specify `os` key in the job you want to include:

```yaml
matrix:
  include:
    - os: linux
      rvm: 2.1
      env: STYLE_CHECKS=true
⋮
```

**Comment by mockdeep** [comment] 2015-08-07 15:00
Great, thanks!

**Comment by BanzaiMan** [comment] 2017-01-27 16:46
I think this was due to the `multi_os` feature not being available to some users before.

I just checked this, and I think this is fixed. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/195932615#L119

Closing this optimistically, but if you still see problems, do let us know.

**Closed by BanzaiMan** 2017-01-27 16:46 UTC
Labels: bug, matrix expansion, travis-gatekeeper
