### ISSUE TITLE
Homebrew addon

### ISSUE THREAD

**Issue by asbjornu** [travis-ci/travis-ci#6463] opened 2016-08-11 13:04 UTC
Currently, packages has to be installed through manual scripting, which leads to rather messy code if you're targeting several operating systems:

``` yaml
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl; fi
```

It would be neat if, like on Linux, you could declaratively define Homebrew dependencies, like so:

``` yaml
addons:
  apt:
    packages:
      - libsdl1.2-dev
  homebrew:
    packages:
      - sdl
```

**Comment by KOLANICH** [comment] 2016-08-23 09:54
and it'd be nice to have a repo where users can share their code

**Comment by austlane** [comment] 2016-08-24 21:35
:+1:

**Comment by drdanz** [comment] 2017-01-03 10:02
Also support for taps would be useful, i.e. instead of

```yml
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
```

```yml
addons:
  homebrew:
    taps:
      - homebrew/science
    packages:
      - opencv
```

**Comment by BanzaiMan** [comment] 2017-01-31 13:53
Duplicate of #5377.

**Closed by BanzaiMan** 2017-01-31 13:53 UTC
Labels: feature-request, travis-build
