### ISSUE TITLE
Support deploy beta for npm

### ISSUE THREAD

**Issue by olamothe** [travis-ci/travis-ci#6511] opened 2016-08-22 14:27 UTC
It would be nice if we could add a setting in travis.yml to support `npm publish --tag beta` in the deploy section.

Maybe something like : 

    deploy:
        provider: npm
        email: [.....]
        api_key:
            secure: [.....]
    on:
        tags: true
        repo: [...]
        all_branches: true
        beta: (some boolean condition in the build config, maybe a check for an env variable ?)

Or is there already a way to accomplish this ?

Thank you, Travis is a great product by the way !

**Comment by joepvd** [comment] 2016-08-22 15:59
Closing as a duplicate of https://github.com/travis-ci/dpl/issues/415

**Closed by joepvd** 2016-08-22 15:59 UTC
Labels: deployment, feature-request
