### ISSUE TITLE
no more pip in xcode8.3

### ISSUE THREAD

**Issue by piem** [travis-ci/travis-ci#8860] opened 2017-12-04 13:06 UTC
hello,

[aubio](https://github.com/aubio/aubio) fails building since a few days against `xcode8.3` because `pip` can not be found.

Should we add `brew install python` or is there another way to build both C and Python code on osx?

cheers, piem

**Comment by BanzaiMan** [comment] 2017-12-04 16:00
Duplicate of #8829.

**Closed by BanzaiMan** 2017-12-04 16:00 UTC
