### ISSUE TITLE
Oracle JDK 1.8.0_31 contains a bug

### ISSUE THREAD

**Issue by jub77** [travis-ci/travis-ci#4740] opened 2015-09-02 10:21 UTC
Would it be possible to upgrade oracle jdk 8 (version 31), it contains bugs:
https://bugs.openjdk.java.net/browse/JDK-8056038

see: https://travis-ci.org/jub77/grafikon/builds/78369377

on oracle jdk 1.8.0_45 it compiles fine

**Comment by BanzaiMan** [comment] 2015-09-02 11:13
Thanks for the detailed report.

I'm closing this as a duplicate of #3259.

If you need a more recent version of Java 8, please see https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-93881360.

**Closed by BanzaiMan** 2015-09-02 11:14 UTC
