### ISSUE TITLE
Caching feature never executes in "osx" environment - private repositories

### ISSUE THREAD

**Issue by darvin** [travis-ci/travis-ci#4864] opened 2015-09-29 16:16 UTC
The same error messages as #4011, travis-pro, xcode 6.4

**Comment by BanzaiMan** [comment] 2015-09-29 16:23
@darvin Is this an error message issue (#4207)? Or cache not getting fetched? Do you have a build log URL to show the problem? If you'd rather communicate privately, please email support@travis-ci.com and close this issue.

Thank you.

**Comment by darvin** [comment] 2015-09-29 19:12
```
$ export CASHER_DIR=$HOME/.casher
1.00s$ Installing caching utilities
1.00sWarning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
attempting to download cache archive
fetching 2.0.0/cache--rvm-default--gemfile-Gemfile.tgz
fetching 2.0.0/cache--rvm-default--gemfile-Gemfile.tbz
fetching master/cache--rvm-default--gemfile-Gemfile.tgz
fetching master/cache--rvm-default--gemfile-Gemfile.tbz
could not download cache
20.00sWarning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p643'.
adding /Users/travis/appledoc to cache
adding /Library/Caches/Homebrew to cache
==> Downloading https://homebrew.bintray.com/bottles/md5deep-4.4.yosemite.bottle
######################################################################## 100.0%
==> Pouring md5deep-4.4.yosemite.bottle.tar.gz
  /usr/local/Cellar/md5deep/4.4: 20 files, 1.8M
```

**Comment by BanzaiMan** [comment] 2015-09-29 19:35
OK. so the caching utility is getting used, which leads me to believe that this is a separate issue from #4011. And I believe this is really a duplicate of #4027.

**Closed by BanzaiMan** 2015-09-29 19:35 UTC

**Comment by darvin** [comment] 2015-09-29 22:05
there is no apt on osx

**Comment by BanzaiMan** [comment] 2015-09-29 23:17
Oops. Sorry. I meant #4207.
