### ISSUE TITLE
Build Groovy project with Jdk7 

### ISSUE THREAD

**Issue by pszymczyk** [travis-ci/travis-ci#7476] opened 2017-03-16 17:07 UTC
Hi 

I've tried to build my Groovy project with jdk7 and it failed with some strange way:

```
3.04s$ ./gradlew assemble
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

Here is full build log:
https://travis-ci.org/pszymczyk/embedded-consul/builds/211792110

And here is full travis.yml:

```
language: groovy

jdk:
  - oraclejdk7

dist: trusty

script:
  - "./gradlew check"
```

**Comment by BanzaiMan** [comment] 2017-03-17 03:03
Does it work with `dist: precise` (which is currently the default, but may change soon)? My guess is that our Trusty image doesn't have Java 7 (possibly an oversight).

**Comment by pszymczyk** [comment] 2017-03-17 08:12
Yes it works with `dist:precise`:
https://travis-ci.org/pszymczyk/embedded-consul/builds/212033553

I'm 99% sure that previous problem with SSL wasn't strict connected with box type, I try to build my project on `precise`. Thanks @BanzaiMan .

**Comment by BanzaiMan** [comment] 2017-03-17 13:09
Closing as a duplicate of #7019.

**Closed by BanzaiMan** 2017-03-17 13:09 UTC
Labels: trusty-container
