### ISSUE TITLE
The command "android-update-sdk --components=tools" failed and exited with 127 during .

### ISSUE THREAD

**Issue by arctouch-rafaelcamargo** [travis-ci/travis-ci#5986] opened 2016-05-03 01:15 UTC
My company (www.cotap.com) suddenly started having this error. We didn't change anything on our side, do you guys made any changes?

Screenshot from build:
https://www.dropbox.com/s/6953sfoycw4b3nh/Screenshot%202016-05-02%2017.15.42.png?dl=0

Log:
[log.txt](https://github.com/travis-ci/travis-ci/files/246185/log.txt)

Our last successful was 3 days ago, here's log:
[log-success.txt](https://github.com/travis-ci/travis-ci/files/246187/log-success.txt)

Not sure if you can access:
https://travis-ci.com/cotap/robo-tap/builds/

We're using `TRUSTY` environments.

Here's a piece of my .travis file:
```
language: android
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
```
Appreciate your help.

**Comment by BanzaiMan** [comment] 2016-05-03 02:11
I believe this is a fallout from https://github.com/travis-ci/travis-ci/issues/5973, and a duplicate of https://github.com/travis-ci/travis-ci/issues/5976. `language: android` + `dist: trusty` used to be routed to a Precise image, but not it is really routed to the Trusty image, which lacks Android tools.

If the Precise image was working for you, I suggest moving back to Precise with `dist: precise`.

**Comment by BanzaiMan** [comment] 2016-05-03 06:52
Closing as a duplicate.

**Closed by BanzaiMan** 2016-05-03 06:52 UTC
Labels: android

**Comment by arctouch-rafaelcamargo** [comment] 2016-05-03 18:23
@BanzaiMan thank you for your help on this.
