### ISSUE TITLE
All commands exited with 0 but still at started status

### ISSUE THREAD

**Issue by Kayorlien** [travis-ci/travis-ci#6917] opened 2016-11-22 13:34 UTC
Although all the command exited with 0,
when the last script finished, it didn't finished build,
however, it continue waiting for output.

I'm new to travis-ci.
Thx for help.

```
...
The command "gulp" exited with 0.
...
The command "pm2 delete 0" exited with 0.
store build cache

nothing changed, not updating cache


Done. Your build exited with 0.


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by apihlaja** [comment] 2016-11-22 13:41
There is something odd going on at the moment, bad time to test Travis CI first time. Their [status](https://www.traviscistatus.com/) service shows there has been issues lately with container based builds.

I was watching my own builds to get stuck. Mostly in the beginning state, but now I have one job which have been "ready" for over 45 min, even build is green but job is still in pending state: https://travis-ci.org/apihlaja/lazy-debug/jobs/177958711

**Comment by BanzaiMan** [comment] 2016-11-22 14:33
I think this is a duplicate of #6861. Closing as such.

**Closed by BanzaiMan** 2016-11-22 14:33 UTC
