### ISSUE TITLE
Travis build caching failing due to `sw_vers: not found`

### ISSUE THREAD

**Issue by JonRowe** [travis-ci/travis-ci#8724] opened 2017-11-09 03:36 UTC
Hi, our `rspec/rspec-rails` builds are encountering Travis's caching mechanism failing to store the resulting cache, when it attempts to it's getting a `sw_vers: not found` error?  https://travis-ci.org/rspec/rspec-rails/jobs/296891645

*Edit* originally I assumed this was the cause of the build failure, its not, its just the last thing in the logs.

**Comment by BanzaiMan** [comment] 2017-11-09 08:39
I'm closing this as a duplicate of #8714.

**Closed by BanzaiMan** 2017-11-09 08:39 UTC

**Comment by JonRowe** [comment] 2017-11-09 22:35
My apologies for the duplicate Hiro! I did try searching for sw_vers but it didn't come up :/

**Comment by BanzaiMan** [comment] 2017-11-10 14:11
No worries, @JonRowe. It was a screen capture, so it was impossible for you to know that.
