### ISSUE TITLE
Pushing git tags stopped working

### ISSUE THREAD

**Issue by Deilan** [travis-ci/travis-ci#8686] opened 2017-11-01 09:23 UTC
Starting from today's morning pushing git tags stopped working in private repos with the following error message:
```
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

bash script being used for pushing tags:
```shell
#!/bin/bash

GIT_USER_EMAIL="${1:-${GIT_USER_EMAIL}}"
GIT_USER_NAME="${2:-${GIT_USER_NAME}}"
GIT_TAG="${3:-${GIT_TAG}}"
GIT_COMMIT_MESSAGE="${4:-${GIT_COMMIT_MESSAGE}}"

if [[ ! $(git config user.email) ]]; then
    git config user.email "${GIT_USER_EMAIL}"
fi

if [[ ! $(git config user.name) ]]; then
    git config user.name "${GIT_USER_NAME}"
fi

if [[ ! $(git tag -l "${GIT_TAG}") ]]; then
    git tag -a "${GIT_TAG}" -m "${GIT_COMMIT_MESSAGE}"
    git push -q origin --tags
fi
```

**Comment by BanzaiMan** [comment] 2017-11-01 12:50
Closing as a duplicate of #8680.

**Closed by BanzaiMan** 2017-11-01 12:50 UTC
