### ISSUE TITLE
Incorrect file from https://s3.amazonaws.com/travis-python-archives/; log listing shown; multiple instances

### ISSUE THREAD

**Issue by drallensmith** [travis-ci/travis-ci#8121] opened 2017-07-19 14:39 UTC
Hi. I'm seeing errors - 
[like in the attached file](https://github.com/travis-ci/travis-ci/files/1159455/Travis_OS_X_Python_2.7.txt) - with installation of Python versions failing in the untarring stage. See [here](https://travis-ci.org/drallensmith/neat-python/jobs/255286026) for an example from a different build, and [here](https://travis-ci.org/drallensmith/neat-python/jobs/255410519) for another. As those overall builds show, it's an intermittent problem - perhaps depending on the node it's running on?

Thanks,

-Allen

Here's a log listing, if people aren't able to read the attached file for some reason...
>Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/-.tar.bz2
>$ sudo tar xjf -.tar.bz2 --directory /
>bzip2: (stdin) is not a bzip2 file.
>tar: Child returned status 2
>tar: Error is not recoverable: exiting now

**Comment by BanzaiMan** [comment] 2017-07-20 02:37
This is a duplicate of #6865.

**Closed by BanzaiMan** 2017-07-20 02:37 UTC
