### ISSUE TITLE
possible bug with submitting build requests for specific commits

### ISSUE THREAD

**Issue by chris-ratcliffe** [travis-ci/travis-ci#8300] opened 2017-08-25 20:51 UTC
@acnagy @BanzaiMan , I am attempting to do exactly what you mentioned in the Feb 22 comment of issue #7364 , which is to use the API to trigger a build for a specific commit.  It doesn't give an error, but it keeps using the latest commit instead of the one I am specifying.  I assume I am passing the payload incorrectly but not sure.  Can you point me to any example of what the payload should look like?  I am doing the following:

curl -d '{"request": {"commit": { "sha" : "8bbe48e4740fc4683238fa44f1719878fcbf6131" }}}' -L -X POST -H "Travis-API-Version: 3" -H "Accept: application/json" -H "Authorization: token <token>" ...

**Comment by BanzaiMan** [comment] 2017-08-25 21:41
Is this a duplicate of that issue, then?

**Comment by chris-ratcliffe** [comment] 2017-08-25 23:23
No.  That issue was requesting the same ability in the UI, and there was mention of the ability to do it with the API, but that is not working for me the way I expect, but I might be providing the payload wrong.  Trying to confirm.

**Comment by chris-ratcliffe** [comment] 2017-08-30 19:04
@BanzaiMan @acnagy , can you confirm that it is possible to use the API to run a travis build with a particular commit, and if so, can you provide an example payload of how the commit should be specified?  If it doesn't work for me, then we can pursue it as a bug.  Thanks.

**Comment by chris-ratcliffe** [comment] 2017-09-05 14:25
@svenfuchs , I see you closed issue #895 a few years ago that is related to this.  Can you confirm whether it should be possible to submit specific commit's sha's when using the API to start a travis build?

**Comment by BanzaiMan** [comment] 2017-09-15 19:09
I've tested this, but I think you are right, that it is not possible to trigger a build by a commit SHA, and by the commit SHA alone.

**Comment by chris-ratcliffe** [comment] 2018-04-16 13:43
I would like to this feature request reopened.

**Comment by cotsog** [comment] 2018-11-09 13:45
@chris-ratcliffe Sorry for the delay! We are tracking this internally. We will let you know if/when it's available.

**Closed** 2018-11-09 13:44 UTC
Labels: feature-request, important, team teal, travis-api
