### ISSUE TITLE
`Homebrew must be run under Ruby 2.3!` on older Mac images

### ISSUE THREAD

**Issue by ThomasWaldmann** [travis-ci/travis-ci#9581] opened 2018-05-06 23:28 UTC
https://travis-ci.org/borgbackup/borg/builds/373700499

our builds typically look like that since a while (some weeks, iirc) and it started without us changing anything OS X related.

so, can this please get fixed?

**Comment by ThomasWaldmann** [comment] 2018-05-06 23:33
looks like #8552 somehow.

**Comment by ThomasWaldmann** [comment] 2018-05-06 23:35
BTW, we had brew upgrade in our scripts for a while, but that just often ended in the error that brew upgrade is already running (huh? in the background or what?), which also failed the build.

**Comment by BanzaiMan** [comment] 2018-05-07 10:58
Could you try a more recent Xcode image?

**Comment by ThomasWaldmann** [comment] 2018-05-07 15:53
sure: https://github.com/borgbackup/borg/pull/3809

but, that won't fix the xcode6.4 image. OS X 10.10 is our minimum requirement, so we like to test on that.

**Comment by ThomasWaldmann** [comment] 2018-05-07 16:28
https://travis-ci.org/borgbackup/borg/builds/375961188

so, every older image than 8.3 xcode is broken. 8.3 is the default version.

**Comment by ThomasWaldmann** [comment] 2018-08-05 16:45
if you didn't fix it, i think it is still an issue.

**Comment by BanzaiMan** [comment] 2018-10-29 03:54
So, the issue was that you could not upgrade OpenSSL because of [this error](https://travis-ci.org/borgbackup/borg/jobs/373700506#L1857):

    /usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)

Switching to, or using, Ruby 2.3 prior to running `brew upgrade` should fix this issue.

```yaml
install:
  - rvm use 2.3
  - brew update
  - brew upgrade openssl
```

We'd probably want to document this, and make sure that `brew addon` does it before hand.

**Comment by BanzaiMan** [comment] 2018-10-29 03:56
Duplicate of #9253.

**Closed by BanzaiMan** 2018-10-29 03:56 UTC
Labels: mac, travis-build
