### ISSUE TITLE
Update Cassandra to >= 2.1.8

### ISSUE THREAD

**Issue by thefosk** [travis-ci/travis-ci#4626] opened 2015-08-06 22:34 UTC
The latest stable version of Cassandra is 2.1.8. Can Travis be updated with a version >= 2.1.8?

**Comment by BanzaiMan** [comment] 2015-08-07 00:37
Hello. Thanks for taking time to open this issue.

I'm closing this as a duplicate of #3952. We tried 2.1.x for the April update, but it introduced incompatibility with 2.0.x, and we rolled it back. We have not scheduled the next update to introduce this yet.

**Closed by BanzaiMan** 2015-08-07 00:37 UTC

**Comment by thefosk** [comment] 2015-08-07 00:39
I guess one way of dealing with this would be so support versions, like:

```yaml
services:
  - cassandra20
  - cassandra21
```

and so on, with:

```yaml
services:
  - cassandra
```

always being the latest.

**Comment by sksumit1** [comment] 2015-08-30 04:12
Agreed 2.1.x is required. I am having a hellish time installing 2.1.x from the scripts
