### ISSUE TITLE
Can't convert to container-based build - different builds have different deps

### ISSUE THREAD

**Issue by bfops** [travis-ci/travis-ci#5356] opened 2015-12-23 14:32 UTC
[ocaml-re](https://github.com/ocaml/ocaml-re) can't be converted to a container-based build. It spawns different builds for different versions of ocaml, by setting environment variables, and then installing the relevant packages. It can't install _all_ these packages, because they all provide the same targets.

Is there a way to specify `addons.apt.sources` and `addons.apt.packages` on a per-build basis?

**Comment by BanzaiMan** [comment] 2015-12-23 15:35
I think this is a duplicate of #5338.

**Comment by bfops** [comment] 2015-12-23 18:00
If #5338 were fixed, it would make this redundant, but I think this is a somewhat simpler case. It says

> My build scripts require certain packages, but which packages can only be determined at runtime rather than upfront.

I'm not sure what "can only be determined at runtime" exactly means, but this isn't quite true for ocaml-re - the packages can be specified statically, they just need to be different for different builds. If that's similar to #5338's use case, then yeah, this is a dup.

**Comment by BanzaiMan** [comment] 2015-12-24 03:53
See also https://github.com/travis-ci/travis-ci/issues/5357#issuecomment-166932293

**Closed by BanzaiMan** 2015-12-24 03:53 UTC
