### ISSUE TITLE
Allow configuring which email address notifications are sent to in account settings

### ISSUE THREAD

**Issue by jameshiew** [travis-ci/travis-ci#5717] opened 2016-02-29 21:25 UTC
I work on an organizational repo, but get all email notifications to my primary Github email rather than my organizational email. I do have an organization-specific email set up on my Github account. It would be good if it was possible to configure your Travis-CI account to route email notifications to a different email, without having to touch the .travis.yml (or at least having a default of personal repo notifications -> primary email address, and organizational repo notifications -> organization repo address).

**Comment by BanzaiMan** [comment] 2016-02-29 21:43
Looks like a duplicate of #1094.

**Closed by BanzaiMan** 2016-02-29 21:43 UTC
