### ISSUE TITLE
"language: android" is listed as "no language set"

### ISSUE THREAD

**Issue by donv** [travis-ci/travis-ci#5493] opened 2016-01-21 14:28 UTC
Hi!

When setting "language: android" in .travis.yml the builds are listed as "no language set".

I would expect the language to be listed as "android".

Example: https://travis-ci.org/ruboto/ruboto/builds/103839566

**Comment by BanzaiMan** [comment] 2016-01-22 04:52
I'm going to close this as a duplicate of #3655.

**Closed by BanzaiMan** 2016-01-22 04:52 UTC
Labels: travis-web

**Comment by donv** [comment] 2016-01-22 15:29
Thanks!  I'll follow that issue.
