### ISSUE TITLE
Lower vs. Uppercase or Vendor/Project-Names in Travis-CI URLs

### ISSUE THREAD

**Issue by andygrunwald** [travis-ci/travis-ci#3198] opened 2015-02-08 12:42 UTC
There is a project on Github called [TYPO3/TYPO3.CMS](https://github.com/TYPO3/TYPO3.CMS).
The corresponding Travis CI url is https://travis-ci.org/TYPO3/TYPO3.CMS.

When i "slightly" modify the vendor / project name in case of upper and lowercase ("typo3/typo3.cms", "Typo3/Typo3.CMS", ...) the Travis-CI won`t work anymore.
See https://travis-ci.org/typo3/typo3.cms or https://travis-ci.org/Typo3/Typo3.CMS

The output is `The repository at Typo3/Typo3.CMS was not found.`
On Github every version works. See https://github.com/typo3/typo3.cms or https://github.com/Typo3/Typo3.CMS.

I stumbled upon this bug, because i was typing the travis ci url manually and was confused if i don`t get a match.

As far as i know urls are case insensitive.
My question is: Is this a bug or a feature?

IMO this is a bug, but i like to get your opinion. Do you consider to change this behaviour?

**Comment by BanzaiMan** [comment] 2015-02-08 14:16
See https://tools.ietf.org/html/rfc3986#section-6.2.2 and http://stackoverflow.com/questions/7996919/should-url-be-case-sensitive. GitHub chose to normalize entity names (wisely, perhaps, in order to avoid having multiple organizations with different casing; github vs GitHub vs Github, etc.).

In my opinion, this is not a bug, but this behavior on Travis CI's part is confusing nonetheless.

**Comment by joshk** [comment] 2015-02-09 02:01
Agree, not strictly a bug, but we could improve this none the less, and shouldn't be hard to either.

I'll talk to the team about this and see what we can do.

**Comment by BanzaiMan** [comment] 2015-02-12 16:59
I'm thinking we'd need to add indices on entity names in lower cases, and normalize our queries to lower case. (I'll ignore different collation types.)

**Comment by andygrunwald** [comment] 2015-02-16 09:14
Would love to see this @BanzaiMan & @joshk.
@BanzaiMan Thx for the ietf link.

**Comment by drogus** [comment] 2015-02-16 09:29
I think that we could address that with the new API /cc @rkh 

The only non-trivial part seems to be adding normalised organisation, user and repository names for a fast lookup in the DB (or maybe just indexing them with `LOWER(name)`, I'm not sure what would be the implications)

**Comment by rkh** [comment] 2015-04-15 15:11
Index added, v3 API is no longer case sensitive.

**Comment by szabgab** [comment] 2015-11-24 13:55
The public web interface is still case sensitive. Do I understand correctly that it is now "just a matter of using v3 API?"

The case I bumped into was
https://travis-ci.org/Manwar/pdf-create/  working and https://travis-ci.org/manwar/pdf-create/ not working.

**Comment by drogus** [comment] 2015-11-24 15:09
@szabgab unfortunately the public interface doesn't use the API V3 version yet. We plan to switch it, but we don't have any ETA.

**Comment by terbach** [comment] 2016-05-22 11:25
Great! Now third party libraries cannot be used if they are mixed with lower- and uppercase? Unacceptable! Thats my problem currently.

**Comment by OmgImAlexis** [comment] 2016-10-10 23:16
@drogus any updates on this? It'd be nice to have all case urls match since you shouldn't be able to have two projects with the same name but different case.

**Comment by OmgImAlexis** [comment] 2018-04-14 10:52
Please don't close this as it's still an issue.

**Comment by OmgImAlexis** [comment] 2018-07-13 11:51
Please don't close this as it's still an issue.

**Comment by Varun-garg** [comment] 2019-04-02 11:11
Still facing this issue:
```$ travis encrypt "BROWSERSTACK_ACCESS_KEY='$BROWSERSTACK_ACCESS_KEY'"
repository not known to https://api.travis-ci.org/: varun-garg/travis-browserstack-example```

I also tried updating the git remote and still wasn't able to get it working. Do you guys really care about the case, if not a fix would be greatly appreciated.

**Comment by MariadeAnton** [comment] 2019-05-10 15:34
This is finally fixed! Check out https://changelog.travis-ci.com/repositories'-urls-are-now-case-insensitive!-100772 

Please let us know if anything is amiss or if you find something that you'd like to see improved at https://travis-ci.community/

Thank you all!

**Closed by MariadeAnton** 2019-05-10 15:34 UTC
Labels: feature-request, important, travis-api

**Comment by MOSSSKITO** [comment] 2019-05-11 23:21
?
