### ISSUE TITLE
Auto-cancel redundant builds

### ISSUE THREAD

**Issue by gfx** [travis-ci/travis-ci#6813] opened 2016-11-02 02:01 UTC
As Circle CI does:

https://twitter.com/circleci/status/757968243072131072

> Changelog - We've added the option to auto-cancel redundant builds. Read more, and how to enable it, here: 

I know you have no plans to do in 2015 (https://github.com/travis-ci/travis-ci/issues/964), but now it's 2016.

**Comment by BanzaiMan** [comment] 2016-11-02 11:42
I'm closing this as a duplicate of #5160 and #6782. If you are asking for things which are not covered by these, do let us know.

**Closed by BanzaiMan** 2016-11-02 11:42 UTC
