### ISSUE TITLE
Caching Docker Images on Build

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#5358] opened 2015-12-23 19:28 UTC
When [using Docker in my travis build](https://docs.travis-ci.com/user/docker/) what are the steps to take in order to get travis-ci to cache the build steps so that subsequent builds are able to use the cache?

**Comment by obazoud** [comment] 2015-12-29 20:55
+1

**Comment by rochdev** [comment] 2016-01-06 14:45
+1

**Comment by joshk** [comment] 2016-01-07 13:43
Sorry, I am not sure I fully understand the question of the issue.

Are you wanting to cache Docker images between builds?

**Comment by obazoud** [comment] 2016-01-07 14:24
I think caching docker layer between builds should be a better solution.

**Comment by cancan101** [comment] 2016-01-07 14:31
Yes that is fine

**Comment by joshk** [comment] 2016-01-07 15:27
We will keep this request in mind, but we can not provide an ETA as this is fairly complicated since we use fresh, clean, ephemeral VMs for each Job.

**Comment by cancan101** [comment] 2016-01-07 15:30
What about caching the directory that docker uses to  store images like Is
done for pip, Apt, etc?

**Comment by BanzaiMan** [comment] 2016-01-07 15:43
Just FYI: `apt` caching is completely different.

My gut feeling is that Docker image caches tend to be large, and uploading/downloading such a cache may still incur a considerable amount of time. It should be tested in the wild, of course.

**Comment by cancan101** [comment] 2016-01-07 15:46
Even though large, I assume that same amount of data will need to be pulled
to the machine as part of the docker build process.

**Comment by joshk** [comment] 2016-01-07 20:25
I'm sorry but this is not currently feasible right now, and will provide little to no improvement over Docker or Quay or other third party services serving the images. The Docker client is pretty smart and pull images, and puts them together, in a smart way, so providing caching would provide little to no benefit.

I am going to close this issue for the time being.

Thank you for opening this issue to discuss the topic.

**Closed by joshk** 2016-01-07 20:25 UTC
Labels: feature-request

**Comment by saulshanabrook** [comment] 2016-01-08 00:56
@joshk Could you elaborate on why you think this would provide little to no benefit? Travis could cache the layers of the docker images left after each build, so that commands like `docker build` would be quicker on subsequent builds. Also this would make `docker pull/run` faster, because it wouldn't have to re pull in the remote images on every build.

I see how this might not be worth the trouble, but I do think it would speed up some builds considerably.

**Comment by cancan101** [comment] 2016-01-08 01:02
FWIW: [circle-ci](https://circleci.com/docs/docker#caching-docker-layers) provides some guidance on caching layers.

**Comment by joshk** [comment] 2016-01-08 01:11
Hi @saulshanabrook, 'caching' still requires us to store the data somewhere, in our case we use S3. For example, for bundler, we tar up the directory which contains all the ruby gems and upload them. Then when we set up the cache when the next build starts, we download the tar, expand it, and then continue with the build.

For one, the circle docs explain the issues you can expect. Second to that, the Docker client, as I explained before, is essentially doing all this for us, and is very smart and efficient with downloading the layers needed.

This might be something we will add in the future, but we have no ETA on this right now.

**Comment by denvned** [comment] 2016-02-20 13:16
@joshk Achieving Docker image layer caching could be really simple. After a build, push the resulting image to some Docker repository, and pull it before the next build. In the end Docker will be able to reuse layers from the previous build. That's all!

CodeShip uses the same approach: https://codeship.com/documentation/docker/caching/

And it could drastically reduce build times with carefully prepared Dockerfile.

I think this issue should be reopened.

**Comment by denvned** [comment] 2016-02-20 15:20
> I think this issue should be reopened.

Or, as Travis allows user to add `docker pull`/`push` commands to *.travis.yml*, that approach is already possible, isn't it? Sorry, I'm new to Travis.

**Comment by steffenbrem** [comment] 2016-03-05 17:29
@denvned This would not solve the problem, since you almost always have multiple docker services, that you also want to cache (redis, mysql etc.). I have yet to see a hosted CI to support full docker cache and I don't think it will come soon.

**Comment by davibe** [comment] 2016-03-11 07:04
I recently integrated travis ci into one of my projects. It's interesting because i can use docker-compose to pull and run dependencies like services/DBs i want to use during integration tests, just like i do locally.

That being said my project takes 9 minutes to build and test. The actual testing is less than a minute. Another minute i think is for fetching related service images (elastic search, mongodb). I estimate 80% of the time is spent building the docker images. The image that takes the most internally just installs "a lot of stuff" using npm. Travis already supports caching directories but unfortunately we can't mount volumes during the docker build process.

One solution could be to move the npm install phase to the run phase, mount `node_modules/` and ask travis to cache it. This is kind of bad because it means maintaining a different docker/docker-compose file just for travis. If i did this i estimate the build would take less than 2 minutes.

Alternatively we could try to pull the last version of the docker image that is known to work and start from that.. Other ideas ?

**Comment by OJFord** [comment] 2016-07-29 10:32
I don't understand the distinction, surely it's the same as pip, or anything else - if the download is slow but the install is fast, don't cache; if the install is the bottleneck then maybe do cache.

If you have a long docker build process, why wouldn't you want to be able to cache those layers on CI?

Sure, if you're just using `image: foobar` then there's no point - caching will just change the download location for no gain.

But if you instead `build` a Dockerfile `FROM foobar` with many layers, and it takes significantly longer to run through these steps than download the base image, surely that's a good candidate for caching?

It's presumably possible manually by directory, but it would be nice to just say `cache: - docker`.

**Comment by corydodt** [comment] 2016-09-10 22:46
Support for caching is the right approach. Docker is designed at every level to work well with caching.

- You'll waste less bandwidth downloading layers from public docker repositories
- You'll waste less time downloading layers from public docker repositories
- You'll waste less CPU building layers repeatedly that can be easily cached
- You'll waste less time building layers repeatedly that can be easily cached.

If travis-ci's CPU and bandwidth are limitless and cheap, then you should still respect your users' time wasted waiting for layer downloads and builds that aren't necessary. Approximately half of our build time is wasted downlading and rebuilding layers unnecessarily.

**Comment by hc2p** [comment] 2016-09-12 10:00
I worked on leveraging travis' folder cache for persisting the docker cache between builds: https://gist.github.com/hc2p/9e284cee3d585eefbc59454e44cc247a 

Currently we fill up the docker cache by pulling the latest image from a docker repo (ECR repo in eu-west-1, close to travis) before building and pushing the new one.
The main reason for this is to make sure our new images only differ in changed layers. This leads to faster pulls on the container instances.

The new solution speeds that up a little. Keep in mind that you copy around almost the same amounts. Only this time from travis-cache (S3 bucket) instead of from your own ECR. 

What do you think about both solutions?

**Comment by s12v** [comment] 2016-09-22 14:12
My solution is similar - `docker save` all the images:
```
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
```

Load:
```
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
```

Also need to declare a cache folder:
```
cache:
  bundler: true
  directories:
    - $HOME/docker
```
Example build: https://travis-ci.org/s12v/sns/builds/161873445

**Comment by mirague** [comment] 2016-10-05 16:12
I would love to hear thoughts from the Travis CI team on the above approaches on caching the images.

**Comment by mparent61** [comment] 2016-10-05 16:22
I've tried several Travis-friendly caching approaches (suggested in this thread and elsewhere), but the bottleneck seems to be S3 reads + writes. The actual image builds were faster, but the time to read + write to the cache made it a wash.

I was using a stock Debian image, maybe something slimmer like Alpine would help.

**Comment by msurdi** [comment] 2016-10-05 20:39
Wouldn't this problem be solved/alleviated by persisting the VMS/workers Travis runs on? Imagine you recycle the same workers for a given customer and just shut them down after X hours of inactivity or something like that. Then the service could make use of the local disk as storage. But I suppose this would raise their costs and that's why its not done like that maybe?

**Comment by mirague** [comment] 2016-10-05 21:05
@mparent61 We've found that S3 read+writes are still a lot faster than downloading and installing all of our dependencies on every run (`npm install`)

**Comment by mzsanford** [comment] 2016-10-10 20:45
Many of the work around solutions presented here were rendered ineffective in Docker 1.10 (per https://github.com/docker/docker/issues/20380). A new option (`--cache-from`) will be available when Docker 1.13 is out and available for use via Travis (per https://github.com/docker/docker/pull/26839).

**Comment by marcbachmann** [comment] 2017-01-20 09:29
🎉  Docker 1.13 got released 2 days ago.
@joshk It would be awesome if you plan to upgrade soon

**Comment by jasonmp85** [comment] 2017-02-23 00:51
Since this ticket is closed; is there any work being done with Docker 1.13 and the caching feature? Will it actually help?

**Comment by dylanscott** [comment] 2017-03-01 17:51
FWIW until Travis updates their version, you can update the version of Docker your Travis build is using, e.g. [like this](https://gist.github.com/dylanscott/ea6cff4900c50f4e85a58c01477e9473). Note that I still needed to list the docker service under the services key in .travis.yml, otherwise I was having issues running the docker cli without sudo.

I can confirm that the `--cache-from` feature in 1.13 works wonderfully. It's saving us a ton of build time on a large node app since we avoid `yarn install`ing every build unless `package.json` changes. It's by far the easiest way to take advantage of the docker layer cache that I've seen. Also if it saves anyone any trouble, FYI `--cache-from` does **not** pull the image in question for you. You need to pull it yourself.

**Comment by jakirkham** [comment] 2017-03-01 18:34
As far as including Docker 1.13 on Travis CI, please see issue ( https://github.com/travis-ci/travis-ci/issues/7380 ).

**Comment by kish3007** [comment] 2017-03-01 22:10
I have been trying to make use of --cache-from command in docker 1.13, no luck so far, any help would be really appreciated. This is the step I have been following:
**Dockerfile1:**
FROM centos:7
RUN echo "Step1"
RUN echo "step2"

docker build -t test1 .
docker push registry/test1:latest


**Dockerfile2:**
FROM centos:7
RUN echo "Step1"
RUN echo "step2"
RUN echo "step3"
RUN echo "step4"

In the second build I have been trying to make use of cache:
docker pull registry/test1:latest
docker build --cache-from registry/test1:latest -t registry/test2:latest .

It doesn't make use of cache for the first 2 instructions rather it runs each instructions  again. Am I missing anything?

**Comment by dylanscott** [comment] 2017-03-01 22:41
@kish3007 I haven't tried to repro but I'm wondering if that could be resulting from incorrect use of the `latest` tag. As far as I can tell, your first build doesn't tag the built image as `latest` (it tags it as `test1`), so the subsequent push may not refer to the image just built, and the second build may not be pulling/using the right image.

I could be way off, but the `latest` tag often confuses me (see e.g. [this post](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375#.v7tapa8e2) or [this post](http://container-solutions.com/docker-latest-confusion/))

**Comment by marcbachmann** [comment] 2017-03-02 06:42
I'm always explicitly tagging my images. Maybe that will help.

```
docker build -t test1 .
docker tag test1 registry/test1:latest
docker push registry/test1:latest
```

Here's what I'm using to update docker, build the images & push them: https://gist.github.com/marcbachmann/16574ba8c614bb3b78614a351f324b86

**Comment by pecigonzalo** [comment] 2017-03-29 16:08
Im doing something like this for 1.13 for images on amazon ECR, but you get the idea.
```
before_install:
- sudo apt-get update && sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
- export REPO=$AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME
- docker pull $(REPO):$(TRAVIS_BRANCH)
script:
- docker build --cache-from $(REPO):$(TRAVIS_BRANCH) -t $(REPO):$(TRAVIS_COMMIT) .
```

Works like a charm.

**Comment by kish3007** [comment] 2017-03-29 20:58
This seems to be #31189 . It should be fixed when you update to v17.03.0-ce.

**Comment by aking1012** [comment] 2018-10-02 13:00
We have a VERY heavy docker container, that takes 13 minutes to build and save, but only 4 minutes to load and run using @s12v  's approach

**Comment by pwaller** [comment] 2018-11-29 16:02
I guess new and exciting things will be possible with the new [docker buildkit](https://github.com/moby/buildkit) - note this is natively built in to docker now. For example, the new builder is able to fetch layers from a cache.

**Comment by Fandekasp** [comment] 2019-01-29 06:51
Hi there. Is @s12v's solution from 2016 still the best practice in 2019 to speed up docker builds?

**Comment by christhomas** [comment] 2019-04-22 09:14
The problem with wanting me to push and pull to a repository all these images is that the repository I have for all of this is public and I don't want to push broken images that fail later stages of testing into a public repository.

The other problem is that it's not trivial to delete images from a docker repository once you've build them, you have to bullshit around with a curl request to get it done. Why docker didn't feel the need to allow you to delete images when it's LITERALLY THE FIRST THING I WOULD WANT (when developing, surely you break stuff and wanna easily delete and cleanup, right?), is another question.

So is the only way around this some script from 2016 because apparently making a cache between stages too difficult when literally every other solution I've tried has solved this problem years ago? Gitlab works flawlessly.

**Comment by jasonmp85** [comment] 2019-04-22 14:56
I found a good workaround is to just drop Travis.

**Comment by christhomas** [comment] 2019-04-23 09:31
This works btw:

```
sudo: required

services:
  - docker

language: generic

env:
  global:
    - NAME=myprojectname
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz

jobs:
  include:
    - stage: build
      script:
        - docker build -t ${IMAGE} ${PWD}
        - mkdir -p ${CACHE_FOLDER}
        - docker save ${IMAGE} | gzip -c > ${CACHE_FILE}
    - stage: push
      script:
        - ls -la ${CACHE_FOLDER}
        - if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi
        - docker images
        - echo "now you should see your image in the next stage, you can do what you wanted"

cache:
  bundler: true
  directories:
    - ${CACHE_FOLDER}

```

**Comment by pietrodn** [comment] 2019-08-08 06:44
The solution from @s12v is brilliant but can be improved, since it calls `docker save` on one image at a time, creating multiple archives. If the saved images share some layers (extreme case: I have `image_a`, and `image_b` which has `image_a` as the base image), then the common layer are duplicated in the archive file.

It would be better to specify all the images in a single `docker save` command:

```
docker save image_a:latest image_b:dev image_c:prod | gzip -2 > "$HOME/docker/docker_images.tar.gz"
```

In this way the layers from `image_a` are saved only once, avoiding unnecessary disk space and execution time.

**Comment by chrisjsewell** [comment] 2019-08-20 20:44
I wonder if anyone can help me. Using the @s12v solution, my images appear to be caching and loading, but then they are not used during `docker build`. Am I missing a step?

From [this build](https://travis-ci.com/chrisjsewell/pytest-moose/jobs/226830217):

[before_install]
```shell
$ if [[ "$TEST_TYPE" == "docker" ]] && [[ -d $HOME/.cache/docker ]]; then
    ls $HOME/.cache/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"
    docker images -a --filter='dangling=false'
  fi

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pytest_moose        latest              ad5f413d7b2d        2 hours ago         1.84GB
centos              7.6.1810            f1cb7c7d58b7        5 months ago        202MB
```

[install]
```shell
$ if [[ "$TEST_TYPE" == "docker" ]]; then
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        DOCKER_TAG=latest
      else
        DOCKER_TAG="$TRAVIS_BRANCH"
      fi
      docker build -t pytest_moose:$DOCKER_TAG .
  fi

Sending build context to Docker daemon  251.7MB
Step 1/17 : FROM centos:7.6.1810
 ---> f1cb7c7d58b7
Step 2/17 : RUN yum update -y && yum clean all
 ---> Running in 2f4106c033a6
Loaded plugins: fastestmirror, ovl
```

**Comment by pietrodn** [comment] 2019-08-20 21:37
Try passing the `--cache-from` argument to `docker build` to explicitly tell Docker that it should consider that image as a cache source ([details](https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/#the-cache-from-argument)).

**Comment by chrisjsewell** [comment] 2019-08-20 23:35
@pietrodn that worked perfectly thanks!

**Comment by samuelcolvin** [comment] 2019-10-16 12:20
To simplify @s12v's excellent answer for modern docker.

Docker caching can be simplified to just:

```yml
cache:
  directories:
  - docker_images

before_install:
- docker load -i docker_images/images.tar || true

before_cache:
- docker save -o docker_images/images.tar $(docker images -a --filter="dangling=false" -q)
```

**Note**: I haven't bother with gzipping `images.tar` since travis caches are already compressed - repeat compression is a waste of time.

**Comment by adibrastegarnia** [comment] 2019-10-26 02:18
> ```yaml
> before_install:
> - docker load -i docker_images/images.tar || true
> 
> before_cache:
> - docker save -o docker_images/images.tar $(docker images -a -q)
> ```
@samuelcolvin 
I tried the one you suggested but it increases the build time overall. My build time was around 2:30 but after using this method, it is increased to more than 5 minutes.

**Comment by samuelcolvin** [comment] 2019-10-26 09:10
1. Caching will only help on the second build on a given branch.
2. If you're build is only taking 2.5 minutes caching probably won't help, caching helps for long build stages like compiling.

My build time improved from 15 minutes to 8 minutes.

**Comment by marcusschiesser** [comment] 2019-11-13 03:54
For our use case using `docker load/save` to a cache folder also slows down the build. How about Travis adds the following:
1. Enable caching for the docker system folder (currently that's not possible due to missing permissions)
2. Upgrade Docker, so [Docker BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/) can be used
