### ISSUE TITLE
[trusty/container] Java openjdk6 not working

### ISSUE THREAD

**Issue by mschwager** [travis-ci/travis-ci#8206] opened 2017-08-04 19:01 UTC
From the build log (https://travis-ci.org/mschwager/duo_client_java/jobs/261116438):

```
$ jdk_switcher use openjdk6
Switching to OpenJDK6 (java-1.6.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-6-openjdk-amd64
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-1.6.0-openjdk-amd64
```

Which then fails when trying to run the tests:

```
$ javac -J-Xmx32m -version
javac 1.8.0_131
0.05s$ mvn install --define "skipTests=true" --define "maven.javadoc.skip=true" --batch-mode --show-version --file duo-client/pom.xml
  
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-6-openjdk-amd64/bin/java
```

I then tried to install `openjdk-6-jdk` and continue with the build in https://travis-ci.org/mschwager/duo_client_java/jobs/261120529, but it appears `jdk_switcher` is run before package installation so `openjdk-6-jdk` doesn't exist yet.

EDIT: Forgot to mention, `openjdk6` support may have even been dropped at this point, but https://docs.travis-ci.com/user/languages/java/#Overview still says it's available.

**Comment by abelsromero** [comment] 2017-08-05 16:56
I am having the same issue for Java 7 builds.
We have a current traviCI working on the origin project, but if someone forks it and enables travis on its own fork, it fails.

See:
https://travis-ci.org/abelsromero/asciidoctorj/jobs/261344488

**Comment by abelsromero** [comment] 2017-08-05 17:06
Btw, I got the same issues on osx builds.

**Comment by abelsromero** [comment] 2017-08-07 19:53
I am doing more testing and it seems there's some obvious problem with `jdk_switcher` on the `trusty` images.
When not using Java8, you get a message saying that the Java directory does not exists:

```
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
```
full log:https://travis-ci.org/abelsromero/asciidoctorj/jobs/261968385

Forcing the dist to `precise` fixes it, but I assume that's not desirable and everyone should move to `trusty`. However, with this issue, it's not possible.

**Comment by mschwager** [comment] 2017-08-09 14:09
Looks like this may be the same issue as https://github.com/travis-ci/travis-ci/issues/8199.

Seems there's some fallout from the `precise` -> `trusty` update, which I'd say is par for the course for a infrastructure change like that.

**Comment by BanzaiMan** [comment] 2017-08-14 13:49
I'm closing this as a duplicate of #8199.

**Closed by BanzaiMan** 2017-08-14 13:49 UTC
Labels: java
