### ISSUE TITLE
Neo4j service doesn't work at all?

### ISSUE THREAD

**Issue by i-am-tom** [travis-ci/travis-ci#7387] opened 2017-02-26 11:42 UTC
Hello! Before anything else, _thank you_ for Travis CI - it's wonderful. <3

I'm having some trouble with the neo4j service. I started by trying to `wget` the binary and install it, had no luck. Similarly, I've tried using `trusty` betas, various versions, boxes based on both `node_js` and `java`, you name it - if it's somewhere in the depths of the Travis issues, I've probably tried it!

However, I'm still having no luck. [Here's my build history](https://travis-ci.org/i-am-tom/neopreen/builds) - don't believe the passes! - and I would appreciate any information on this. So far, the Travis-supplied `neo4j` service seems to hang indefinitely _or_ not be found :(

Thanks for any help you can give!
Tom

**Comment by BanzaiMan** [comment] 2017-03-19 03:23
Sorry, but I don't think we have a good explanation for this. Closing as a duplicate of #3243.

**Closed by BanzaiMan** 2017-03-19 03:23 UTC

**Comment by i-am-tom** [comment] 2017-03-19 11:17
Does this mean there's no plan to fix Travis' support for Neo4j?
Are there plans to fix the `neo4j` service?
