### ISSUE TITLE
Homebrew must be run under Ruby 2.3! You're running 2.0.0 on xcode7.3

### ISSUE THREAD

**Issue by Flamefire** [travis-ci/travis-ci#9913] opened 2018-07-25 09:38 UTC
I'm getting the error `Homebrew must be run under Ruby 2.3! You're running 2.0.0` for `osx_image: xcode7.3` (only)

According to the docs, it is not recommended to run `brew update` so I'd considers this as a bug in the travis image.

Any ideas how to solve this?

**Comment by BanzaiMan** [comment] 2018-10-29 03:56
Duplicate of #9253.

**Closed by BanzaiMan** 2018-10-29 03:56 UTC
