### ISSUE TITLE
Multiple IRC build reports for single build

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#4988] opened 2015-10-21 15:13 UTC
In the past few days we've started to get multiple IRC notifications for a single build, and it's clogging up the channel.

https://www.dropbox.com/s/gjrhqbxub6v5dfq/Screenshot%202015-10-21%2010.10.08.png?dl=0

For now I will need to silence travis in #jruby but we'd appreciate having someone investigate this issue.

**Comment by joshk** [comment] 2015-10-21 15:40
hey @headius, are you using `fast_finish` by chance?

**Comment by eregon** [comment] 2015-10-22 12:48
@joshk Yes

**Comment by joshk** [comment] 2015-10-22 12:58
please remove that for the time being, we have a bug with that feature which we will look into fixing soon.

**Comment by Croydon** [comment] 2015-12-20 15:42
This issue still floods our IRC channel. Any progress so far?

**Comment by joshk** [comment] 2015-12-21 14:51
Closing as this is a duplicate of #4928

**Closed by joshk** 2015-12-21 14:51 UTC
