### ISSUE TITLE
'TRAVIS_BRANCH' points to branch that introduced commit, not the branch being built

### ISSUE THREAD

**Issue by VincentHokie** [travis-ci/travis-ci#10188] opened 2018-10-05 16:33 UTC
The `TRAVIS_BRANCH` Environment variable actually points to the branch that introduced the commit not the branch that is being built.

To reproduce:
- I have a branch `feature-1`
- Create a branch off `feature-1` called `feature-2`
- Push `feature-2`
- The variable 'TRAVIS_BRANCH' during a push build refers to `feature-1` instead of `feature-2`

**Comment by BanzaiMan** [comment] 2018-10-05 19:14
When reporting a problem, please include a build log URL that shows the problem you are describing. If it’s for a private repository and (or for any reason) you’d rather not discuss it in public, please close this issue and send email to support@travis-ci.com.

Thank you!

**Comment by BanzaiMan** [comment] 2018-11-08 03:39
I can't reproduce it. https://travis-ci.org/BanzaiMan/travis_production_test/builds/452209371#L470

**Comment by BanzaiMan** [comment] 2018-11-08 03:39
Please include build log URL if you still see this. Thanks.

**Closed by BanzaiMan** 2018-11-08 03:39 UTC
