### ISSUE TITLE
Travis-CI does not process travis.yaml

### ISSUE THREAD

**Issue by Aethylred** [travis-ci/travis-ci#8068] opened 2017-07-11 02:41 UTC
Hello Travis,

There is nothing wrong with `travis.yml` being processed, that works.

However the [correct extension for a YAML file](http://www.yaml.org/faq.html) is `.yaml`

Travis-CI ignores `travis.yaml` and runs using the default configuration.

My explectation is that Travis-CI would process `travis.yaml` when `travis.yml` is not present.

Could this be implemented?

**Comment by Aethylred** [comment] 2017-07-11 02:42
This might seem pedantic, but some other tools ignore files with the .yml extension, like [yaml-lint](https://github.com/Pryz/yaml-lint)

**Comment by BanzaiMan** [comment] 2017-07-11 03:14
A duplicate of #672.

**Closed by BanzaiMan** 2017-07-11 03:14 UTC
