### ISSUE TITLE
Should profile page link to builds page rather than GitHub repositories?

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3013] opened 2014-12-10 20:22 UTC
https://travis-ci.org/profile/USER has a list of repositories, which link to GitHub, rather than travis-ci. Perhaps they should go to their respective builds page.

**Comment by roidrage** [comment] 2015-07-23 16:54
Closing this as a duplicate of #2955.

**Closed by roidrage** 2015-07-23 16:54 UTC
Labels: travis-web, ux
