### ISSUE TITLE
macOS build failures for R packages

### ISSUE THREAD

**Issue by romainfrancois** [travis-ci/travis-ci#10295] opened 2018-10-25 12:55 UTC
e.g. https://travis-ci.org/tidyverse/dplyr/jobs/446154785

ping @jeroen @jimhester, but maybe this is a homebrew issue 🍺 ?

**Comment by jeroen** [comment] 2018-10-25 12:59
@fxcoudert did you remove these installers from your homepage? The installers linked from the GNU website now give 404:https://gcc.gnu.org/wiki/GFortranBinaries#MacOS

@romainfrancois an easy workaround is setting `fortran:false` in your build.

**Comment by romainfrancois** [comment] 2018-10-25 13:47
Thanks. That seems to fix it: https://travis-ci.org/tidyverse/dplyr/builds/446174553

**Comment by jeroen** [comment] 2018-10-26 11:44
@fxcoudert do you still have the old installers somewhere? We can just put them in a github repo for archive purposes and setup a redirect from your site. It's a bit unfortunate that the link on the official GCC website is suddenly dead.

Anyway I'll fix the travis script on our end as well.

**Comment by fxcoudert** [comment] 2018-10-26 18:33
@jeroen in fact I have not been active in GCC for a few years, and I hadn't updated these packages recently, so I didn't realise people were downloading them in large number and/or for automated testing! I have a simple personal website.

I've started a github repo for hosting those binaries: https://github.com/fxcoudert/gfortran-for-macOS/releases I am in the process of getting my website backups and moving the packages to github, should be done soon.

**Comment by richelbilderbeek** [comment] 2018-10-30 15:28
@fxcoudert: I would also enjoy you fixing this :+1:

Of course, take your time, just wanted to make sure you'd know you'd make people happy by fixing this :grin:

**Comment by fxcoudert** [comment] 2018-10-30 16:31
I can't restore the files to their previous URL, but they are now hosted here: https://github.com/fxcoudert/gfortran-for-macOS/releases

For example, the missing link in the original bug report can now be found at 
https://github.com/fxcoudert/gfortran-for-macOS/releases/download/6.1/gfortran-6.1-ElCapitan.dmg
I expect that this URL will be as stable as GitHub itself :)

**Comment by richelbilderbeek** [comment] 2018-10-30 16:51
Great @fxcoudert! 

I've created [a Pull Request](https://github.com/travis-ci/travis-build/pull/1557) that points the scripts to the correct new location :+1:

**Comment by richelbilderbeek** [comment] 2018-10-30 17:07
[This Pull Request](https://github.com/travis-ci/travis-build/pull/1553) is a older functional duplicate of mine, so mine has been closed.

**Closed** 2018-10-31 19:17 UTC
Labels: community:r
