### ISSUE TITLE
Linux (Mono) builds fail

### ISSUE THREAD

**Issue by patriksvensson** [travis-ci/travis-ci#5099] opened 2015-11-12 18:00 UTC
@joshua-anderson @akoeplinger @nterry

I'm getting errors when starting Linux builds (with mono) on Travis CI.

```csharp
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-corlib4.5-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-xml4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-security4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-configuration4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-security4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-4.0-gac_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-gac_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-runtime-common_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-runtime-sgen_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-runtime_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/ca-certificates-mono_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-posix4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-core4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-numerics4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build-framework4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build-utilities-v4.0-4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build-engine4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-xbuild-tasks4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build-tasks-v4.0-4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-runtime-serialization-formatters-soap4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-data-tds4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-transactions4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-enterpriseservices4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-sqlite4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-componentmodel-dataannotations4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-drawing4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-applicationservices4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-services4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-runtime4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-accessibility4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-webbrowser4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n-west4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-windows-forms4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-xbuild_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-compilerservices-symbolwriter4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-cecil-private-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-codecontracts4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-csharp4.0c-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-ldap4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-messaging4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-peapi4.0a-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-rabbitmq4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-relaxng4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-sharpzip4.84-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-componentmodel-composition4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-configuration-install4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-runtime-serialization4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data-linq4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-xml-linq4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data-services-client4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-design4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-identitymodel4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-identitymodel-selectors4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-messaging4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-servicemodel4.0a-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-servicemodel-activation4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-extensions4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-servicemodel-web4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-xaml4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-csharp4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-mcs_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-c5-1.1-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-cairo4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-cscompmgd0.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-custommarshalers4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-db2-1.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-debugger-soft4.0a-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-http4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n-cjk4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n-mideast4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n-other4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n-rare4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-i18n4.0-all_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-management4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-messaging-rabbitmq4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-build4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-visualc10.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-microsoft-web-infrastructure1.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-oracle4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-parallel4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-simd4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data-datasetextensions4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data-entity4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-data-services4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-drawing-design4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-dynamic4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-io-compression4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-io-compression-filesystem4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-json4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-json-microsoft4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-ldap4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-ldap-protocols4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-management4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-net4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-net-http4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-net-http-formatting4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-net-http-webrequest4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-interfaces2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-core2.2-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-linq2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-debugger2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-experimental2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-providers2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-observable-aliases0.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-platformservices2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-runtime-remoting2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-windows-forms2.2-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-windowsbase4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-reactive-windows-threading2.2-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-runtime-caching4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-runtime-durableinstancing4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-servicemodel-discovery4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-servicemodel-routing4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-serviceprocess4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-threading-tasks-dataflow4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-abstractions4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-dynamicdata4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-extensions-design4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-http4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-http-selfhost4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-http-webhost4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-razor2.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-webpages-deployment2.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-webpages2.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-webpages-razor2.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-mvc3.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-web-routing4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-windows4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-windows-forms-datavisualization4.0a-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-system-xml-serialization4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-tasklets4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-webmatrix-data4.0-cil_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-cil-dev_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmonoboehm-2.0-1_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmonoboehm-2.0-dev_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-2.0-dev_4.0.5.1-0xamarin1_amd64.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-devel_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-2.0-1_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-corlib4.0-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmonosgen-2.0-1_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-profiler_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-4.0-service_4.0.5.1-0xamarin1_all.deb  Hash Sum mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-utils_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-jay_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-csharp-shell_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/monodoc-base_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/monodoc-manual_4.0.5.1-0xamarin1_all.deb  Size mismatch
Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/mono-complete_4.0.5.1-0xamarin1_amd64.deb  Size mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by akoeplinger** [comment] 2015-11-12 18:04
See https://github.com/travis-ci/travis-ci/issues/5095. Did this happen on any recent build?

**Comment by patriksvensson** [comment] 2015-11-12 18:06
Ah, so it might fix itself soon if I understand correctly.

It happened to me an hour ago, but I'll wait some more and try re-running
the build later. Thanks!

**Comment by akoeplinger** [comment] 2015-11-12 18:09
Thanks. Yeah we've done everything we could think of to invalidate the CDN caches, but if it still happens in say 12 hours please shout!

**Comment by BanzaiMan** [comment] 2015-11-12 19:29
I'm closing this as a duplicate of #5095.

**Closed by BanzaiMan** 2015-11-12 19:29 UTC
Labels: community:csharp
