### ISSUE TITLE
Git fetch fails on linux in julia build script

### ISSUE THREAD

**Issue by Luthaf** [travis-ci/travis-ci#5696] opened 2016-02-24 20:48 UTC
@tkelman, @ninjin, @staticfloat

[This build](https://travis-ci.org/Luthaf/Conda.jl/builds/111577714) fails on Linux (but not on OS X) with the following error:

```
$ git fetch --unshallow
fatal: git fetch-pack: expected shallow list

$ julia --color=yes -e 'Pkg.clone(pwd())'
INFO: Initializing package repository /home/travis/.julia/v0.3
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning Conda from /home/travis/build/Luthaf/Conda.jl
fatal: attempt to fetch/clone from a shallow repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
ERROR: unlink: no such file or directory (ENOENT)
 in unlink at fs.jl:97
 in rm at file.jl:57
 in clone at pkg/entry.jl:151
 in clone at pkg/entry.jl:175
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#229__ at ./pkg/dir.jl:28
 in clone at pkg.jl:30
 in process_options at ./client.jl:213
 in _start at ./client.jl:354
```

Perhaps an update of `git` which changed the syntax for `git fetch --unshallow`? This command is also failing on Julia 0.5, but it looks like `Pkg.clone(pwd())` works despite this.

**Comment by tkelman** [comment] 2016-02-24 21:36
There are other open issues on this. Travis' shallow clone isn't working properly. There's an option, probably still undocumented, to specify `git: depth: 999999` to override the default shallow clone but I can't recall the exact syntax.

**Comment by tkelman** [comment] 2016-02-25 06:47
duplicate of #4942

**Closed** 2016-02-25 09:10 UTC
Labels: community:julia
