### ISSUE TITLE
tag with same name as a branch might break builds

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#3178] opened 2015-02-04 16:58 UTC
If there is a tag with the same name as a branch, we might fail at checking out a specific sha, as it's not being being fetched with the clone. We should make the ref an explicit branch ref when cloning to fix this.

**Comment by joshk** [comment] 2015-02-15 07:07
Hmmmmm, interesting, @drogus could you weigh in with some advice?

**Comment by BanzaiMan** [comment] 2015-03-06 13:13
I think this is a duplicate of #1590.

**Closed by BanzaiMan** 2015-03-06 13:13 UTC
