### ISSUE TITLE
pypi: deploy script ends with 0 even though deploy failed

### ISSUE THREAD

**Issue by TomasTomecek** [travis-ci/travis-ci#5393] opened 2016-01-03 13:41 UTC
https://travis-ci.org/TomasTomecek/sen/jobs/99947834#L374

```
HTTPError: 400 Client Error: A file named "sen-0.1.1.tar.gz" already exists for  sen-0.1.1. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi

running upload_docs

creating build/docs

error: no files found in upload directory 'build/docs'

No stash found.

Done. Your build exited with 0.
```

**Comment by BanzaiMan** [comment] 2016-01-03 14:20
This is basically a duplicate of #2521. We do not test the exit status of deployment, so failure is not marked as such.

**Closed by BanzaiMan** 2016-01-03 14:20 UTC
