### ISSUE TITLE
No after_* scripts when build times out

### ISSUE THREAD

**Issue by tamastimar** [travis-ci/travis-ci#4777] opened 2015-09-11 10:00 UTC
I have a build which times out (`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself. The build has been terminated`).

I'd like to gather logs after the failure. I've tried by `after_failure` and `after_script` but it seems these aren't run when time-out happens.

See the build here: https://travis-ci.org/tamastimar/TTZoomTransition/builds/79815674

**Comment by BanzaiMan** [comment] 2015-09-11 11:37
This is a known issue. I'm closing this as a duplicate of #4221.

**Closed by BanzaiMan** 2015-09-11 11:37 UTC
