### ISSUE TITLE
Container builds sometimes stall with no messages after printing worker info

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#10005] opened 2018-08-15 00:53 UTC
For the first attempt of https://travis-ci.org/Pr0methean/BetterRandom/jobs/416150298, the entire log follows:

```
Worker information
hostname: bc570e28-0418-49ae-a550-4b657f58ac99@1.production-1-worker-org-09-packet
version: v4.0.0 https://github.com/travis-ci/worker/tree/e5cb567e10c0eefe380e81c9a2229ac8fb6a16ce
instance: 948ba16 travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 952.711203ms
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by Spongman** [comment] 2018-08-19 23:55
i'm seeing the same thing. really annoying to have to manually retrigger builds, spamming other pull request collaborators.

here's another example: https://travis-ci.org/processing/p5.js/builds/417804128

why does this happen?

**Comment by cotsog** [comment] 2018-09-14 02:46
Sorry for the delay of my reply of our reply

We believe there's 2 different issues described here:

1) Container stalling at the very beginning.

2) Build stalling while running `npm install`.

We are looking into #1.

#2 is something that is probably out of our control. We've reached out to NPM's support but we couldn't find the root cause. We do have the following workaround which is to retry the command and add a timeout. Here's how it would look like in your .travis.yml file:

```yaml
install:
  - for i in {1..3}; do travis_wait 5 npm install && break; rm -rf node_modules; done
```

Here's a PR with this change => https://github.com/processing/p5.js/pull/3212

Could you try this out and let me know if it helps?

Thanks!

**Comment by Spongman** [comment] 2018-09-15 15:52
Here’s another

https://travis-ci.org/processing/p5.js/jobs/429009862

This has nothing to do with bpm, it’s just another abrupt termination without error.

**Comment by Spongman** [comment] 2018-09-15 16:37
and another: https://travis-ci.org/processing/p5.js/jobs/428922499

**Comment by Spongman** [comment] 2018-09-15 16:38
can you check to see if there's some OOM condition or something that's killing the container?

**Comment by dylandechant** [comment] 2018-12-01 04:40
seeing the same thing

**Comment by cotsog** [comment] 2018-12-01 14:48
@dylandechant Sorry to hear this is still happening! Could you post a link to the build where this is happening? You can send it to support@travis-ci.com is it's private. Thanks!

**Comment by DrTorte** [comment] 2018-12-03 17:05
Hi all,

Closing this issue for now. If there's anything that comes up in regards to this your best bet is to email support@travis-ci.com, and for any other conversations you'd like to have, please feel free to use the [Travis CI Community Forum](https://travis-ci.community). Thanks and happy building!

**Closed by DrTorte** 2018-12-03 17:05 UTC
