### ISSUE TITLE
oraclejdk10 not available

### ISSUE THREAD

**Issue by JeffreyFalgout** [travis-ci/travis-ci#10262] opened 2018-10-18 14:10 UTC
https://travis-ci.com/JeffreyFalgout/junit5-extensions/jobs/152587866

[Job log](https://github.com/travis-ci/travis-ci/files/2492197/log.txt):

> The command "bash install-jdk.sh -F 10 -L BCL --target $JAVA_HOME --workspace ${TRAVIS_HOME}/.cache/install-jdk" failed and exited with 8 during .

If I manually try to download JDK 10 from Oracle's website, I get a 404: https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html

I know oraclejdk10 is EOL. If it's actually no longer available, would it be worth removing support for it from install-jdk?

**Comment by BanzaiMan** [comment] 2018-10-18 14:42
Duplicate of #10249.

**Closed by BanzaiMan** 2018-10-18 14:42 UTC
