### ISSUE TITLE
gh-pages deploy not working since about 3 days ago

### ISSUE THREAD

**Issue by gholt** [travis-ci/travis-ci#9319] opened 2018-03-10 00:53 UTC
Hi, I'm out of ideas to try to get the gh-pages push working again.

Travis pushed fine a few days ago https://github.com/troubling/hummingbird/tree/gh-pages

But, now it just blows up with https://travis-ci.org/troubling/hummingbird/builds/351564750?utm_source=email&utm_medium=notification

```
Logged in as @redbo (Michael Barton)
Starting deployment of gh-pages branch to GitHub Pages...
Created a temporary work directory /tmp/d20180310-14459-gnkf9h/work
cd /tmp/d20180310-14459-gnkf9h/work
Creating a brand new local repo from scratch in dir /tmp/d20180310-14459-gnkf9h/work...
dpl.2
Preparing deploy
dpl.3
Deploying application
Initialized empty Git repository in /tmp/d20180310-14459-gnkf9h/work/.git/
Repo created successfully
Switched to a new branch 'gh-pages'
An orphan branch gh-pages created successfully
cd -
cd /tmp/d20180310-14459-gnkf9h/work
Copying /home/travis/gopath/src/github.com/troubling/hummingbird/output contents to /tmp/d20180310-14459-gnkf9h/work (workdir: /tmp/d20180310-14459-gnkf9h/work)...
Configuring git committer to be Deployment Bot (from Travis CI) <deploy@travis-ci.org> (workdir: /tmp/d20180310-14459-gnkf9h/work)
Preparing to deploy gh-pages branch to gh-pages (workdir: /tmp/d20180310-14459-gnkf9h/work)
commit 41163202ec4d4d002135607f98620515e471af74
Author: Deployment Bot (from Travis CI) <deploy@travis-ci.org>
Date:   Sat Mar 10 00:46:34 2018 +0000
    Deploy troubling/hummingbird to github.com/troubling/hummingbird.git:gh-pages
 bin/hummingbird         |   Bin 0 -> 23926662 bytes
 coverage.html           | 36315 ++++++++++++++++++++++++++++++++++++++++++++++
 functional_hbproxy.html |  1028 ++
 index.html              |     3 +
 4 files changed, 37346 insertions(+)
Doing the git push (workdir: /tmp/d20180310-14459-gnkf9h/work)...
Couldn't push the build to github.com/troubling/hummingbird.git:gh-pages
failed to deploy
```

No changes were made to our .travis.yml since Feb 22nd, excepting the change I just now made to set `verbose: true` to hopefully get a clue as to why it's breaking now.

Can anyone here help?

**Comment by BanzaiMan** [comment] 2018-03-10 02:17
Duplicate of #9312.

**Closed by BanzaiMan** 2018-03-10 02:17 UTC

**Comment by gholt** [comment] 2018-03-12 15:01
Thanks, most of that other issue was gibberish to me, but good to know a fix is in upcoming. :)
