### ISSUE TITLE
Error: no certificate subject alternative name matches requested host name `cmake.org' on travis sudoless environment

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#5642] opened 2016-02-17 07:05 UTC
See https://travis-ci.org/deepstreamIO/libdeepstream/jobs/109796838#L184
Locally wget works just fine.

**Comment by BanzaiMan** [comment] 2016-02-17 14:03
This is a duplicate of #5059.

**Closed by BanzaiMan** 2016-02-17 14:03 UTC
